TracktionEngine: tracktion::engine::StepClip Class Reference
tracktion::engine::StepClip Class Reference
tracktion_engine » model
#include <tracktion_StepClip.h>
Classes
struct Channel
struct Pattern
struct PatternInstance
Public Types
enum Defaults {
defaultNumNotes = 16 , defaultNumChannels = 8 , defaultMidiChannel = 1 , defaultNoteNumber = 60 ,
defaultNoteValue = 96 , minNumNotes = 2 , maxNumNotes = 512 , minNumChannels = 1 ,
maxNumChannels = 60
}
using Ptr = juce::ReferenceCountedObjectPtr< StepClip >
using PatternArray = juce::ReferenceCountedArray< PatternInstance >
Public Types inherited from tracktion::engine::Clip
enum class FollowActionDurationType { beats , loops }
Defines the types of duration follow actions can use.
enum SyncType { syncBarsBeats = 0 , syncAbsolute }
Determines the clip sync type.
using Ptr = juce::ReferenceCountedObjectPtr< Clip >
using Array = juce::ReferenceCountedArray< Clip >
Public Types inherited from tracktion::engine::TrackItem
enum class Type {
unknown , wave , midi , edit ,
step , marker , pitch , timeSig ,
collection , video , recording , chord ,
arranger , container
}
Defines the types of item that can live on Track[s].
Public Types inherited from tracktion::engine::Selectable
using WeakRef = juce::WeakReference< Selectable >
Public Member Functions
StepClip (const juce::ValueTree &, EditItemID, ClipOwner &)
~StepClip () override
void cloneFrom (Clip *) override
Clones the given clip to this clip.
const juce::Array< Channel * > & getChannels () const noexcept
void removeChannel (int index)
void insertNewChannel (int index)
bool usesProbability ()
PatternArray getPatternSequence () const
void setPatternSequence (const PatternArray &)
void insertVariation (int patternIndex, int insertIndex)
void removeVariation (int variationIndex)
void removeAllVariations ()
void createDefaultPatternIfEmpty ()
void setPatternForVariation (int variationIndex, int newPatternIndex)
int insertPattern (const Pattern &, int index)
int insertNewPattern (int index)
void removePattern (int patternIndex)
void removeUnusedPatterns ()
bool getCell (int patternIndex, int channelIndex, int noteIndex)
void setCell (int patternIndex, int channelIndex, int noteIndex, bool value)
Pattern getPattern (int index)
int getNumPatterns () const
juce::Array< Pattern > getPatterns ()
float getVolumeDb () const
void setVolumeDb (float v)
void generateMidiSequence (juce::MidiMessageSequence &result, bool convertToSeconds=true, PatternInstance *instance=nullptr)
Generate a MidiMessageSequence from either the entire clip or one of its pattern instances.
juce::MidiMessageSequence generateMidiSequence (MidiList::TimeBase, PatternInstance *instance=nullptr)
Generate a MidiMessageSequence from either the entire clip or one of its pattern instances.
juce::Array< BeatPosition > getBeatTimesOfPatternStarts () const
BeatPosition getStartBeatOf (PatternInstance *)
BeatPosition getEndBeatOf (PatternInstance *)
int getBeatsPerBar ()
void resizeClipForPatternInstances ()
bool canBeAddedTo (ClipOwner &) override
Tests whether this clip can go on the given parent.
juce::String getSelectableDescription () override
Subclasses must return a description of what they are.
juce::Colour getDefaultColour () const override
Returns the default colour for this clip.
bool isMidi () const override
Returns true if this is a MidiClip.
bool beatBasedLooping () const override
Returns true if this clip's looping is based on beats or false if absolute time.
bool isMuted () const override
Returns true if the clip is muted.
void setMuted (bool m) override
Mutes or unmutes the clip.
LiveClipLevel getLiveClipLevel ()
bool canLoop () const override
StepClips can only loop if they're being used as launcher clips.
ClipPosition getPosition () const override
bool isLooping () const override
void setNumberOfLoops (int) override
void disableLooping () override
void setLoopRange (TimeRange) override
void setLoopRangeBeats (BeatRange) override
BeatPosition getLoopStartBeats () const override
BeatDuration getLoopLengthBeats () const override
TimePosition getLoopStart () const override
TimeDuration getLoopLength () const override
std::shared_ptr< LaunchHandle > getLaunchHandle () override
void setUsesGlobalLaunchQuatisation (bool useGlobal) override
bool usesGlobalLaunchQuatisation () override
LaunchQuantisation * getLaunchQuantisation () override
FollowActions * getFollowActions () override
Public Member Functions inherited from tracktion::engine::Clip
Clip (const juce::ValueTree &, ClipOwner &, EditItemID, Type)
Creates a clip of a given type from a ValueTree state.
~Clip () override
Destructor.
virtual void initialise ()
Initialises the Clip.
virtual void flushStateToValueTree ()
Can be overridden to ensure any state (e.g.
virtual void sourceMediaChanged ()
Called when the source media file reference (attribute "source") has changed - i.e.
virtual void pitchTempoTrackChanged ()
Called when there are pitch or tempo changes made which might require clips to adjust timing information.
virtual juce::String getName () const override
Returns the name of the clip.
void setName (const juce::String &newName)
Sets a new name for a clip.
virtual bool usesSourceFile () const
True if it references a source file - i.e.
SourceFileReference & getSourceFileReference ()
Returns the SourceFileReference of the Clip.
juce::File getCurrentSourceFile () const
Returns the current source file, this is different to the SourceFileReference as it could be a temporary comp file, clipFX, reverse render etc.
juce::Array< ReferencedItem > getReferencedItems () override
Returns an array of any ReferencedItem[s] e.g.
void reassignReferencedItem (const ReferencedItem &, ProjectItemID, double) override
Should be implemented to change the underlying source to a new ProjectItemID.
BeatPosition getContentBeatAtTime (TimePosition) const
Returns the beat number (with offset) at the given time.
TimePosition getTimeOfContentBeat (BeatPosition) const
Returns time of a beat number.
virtual TimeDuration getMaximumLength ()
Returns the maximum length this clip can have.
virtual juce::Array< TimePosition > getInterestingTimes ()
Returns times for snapping to, relative to the Edit.
TimePosition getSpottingPoint () const
Returns the first marked time in the source file which can be used for syncronising newly added clips.
TimeRange getLoopRange () const
Returns the loop range in seconds.
BeatRange getLoopRangeBeats () const
Returns the loop range in beats.
virtual void setSyncType (SyncType sync)
Sets the sync type for the clip.
SyncType getSyncType () const
Returns the sync type clip is using.
void setPosition (ClipPosition newPosition)
Sets the position of the clip.
void setStart (TimePosition newStart, bool preserveSync, bool keepLength)
Sets the start time of the clip.
void setLength (TimeDuration newLength, bool preserveSync)
Sets the length of the clip.
void setEnd (TimePosition newEnd, bool preserveSync)
Sets the end of the clip.
void setOffset (TimeDuration newOffset)
Sets the offset of the clip, i.e.
void trimAwayOverlap (TimeRange editRangeToTrim)
Trims away any part of the clip that overlaps this region.
void removeFromParent ()
Removes this clip from the parent track or container clip.
bool moveTo (ClipOwner &)
Moves the clip to a new parent (if possible).
double getSpeedRatio () const noexcept
Returns the speed ratio i.e.
virtual void setSpeedRatio (double)
Sets a speed ratio i.e.
virtual void rescale (TimePosition pivotTimeInEdit, double factor)
stretches and scales this clip relative to a fixed point in the edit.
bool isGrouped () const override
Returns true if the clip is part of a group.
TrackItem * getGroupParent () const override
Returns the parent TrackItem if part of a group.
void setGroup (EditItemID newGroupID)
Sets the clip to be part of a group.
EditItemID getGroupID () const noexcept
Returns the ID of the group.
CollectionClip * getGroupClip () const
Returns this as a CollectionClip if it is one.
bool isLinked () const
Returns true if this clip is linked with any others.
void setLinkGroupID (juce::String newLinkID)
Sets the link ID to link this clip with others.
juce::String getLinkGroupID () const
Returns the link ID of this clip.
ClipOwner * getParent () const
Returns the parent ClipOwner this clip is on.
ClipTrack * getClipTrack () const
Returns the parent ClipTrack this clip is on (if any).
Track * getTrack () const override
Returns the parent Track this clip is on (if any).
ClipSlot * getClipSlot () const
Returns the parent ClipSlot this clip is on (if any).
virtual juce::Colour getColour () const
Returns the colour property of this clip.
void setColour (juce::Colour col)
Sets the colour property of this clip.
virtual void removePlugin (const Plugin::Ptr &)
Removes the given plugin from the clip if the clip supports plugins.
virtual bool addClipPlugin (const Plugin::Ptr &, SelectionManager &)
Adds a plugin to the clip.
virtual Plugin::Array getAllPlugins ()
Returns all the plugins on the clip.
virtual void sendMirrorUpdateToAllPlugins (Plugin &) const
Sends an update to all plugins mirroing the one passed in.
virtual PluginList * getPluginList ()
Returns the PluginList for this clip if it has one.
virtual void clearTakes ()
Clears any takes this clip has.
virtual bool hasAnyTakes () const
Returns true if this clip has any takes.
virtual juce::StringArray getTakeDescriptions () const
Returns the descriptions of any takes.
virtual void setCurrentTake (int)
Sets a given take index to be the current take.
virtual int getCurrentTake () const
Returns the current take index.
virtual int getNumTakes (bool)
Returns the total number of takes.
virtual bool isCurrentTakeComp ()
Returns true if the current take is a comp.
virtual void setShowingTakes (bool shouldShow)
Sets whether the clip should be showing takes.
virtual bool isShowingTakes () const
Returns true if the clip is showing takes.
virtual Clip::Array unpackTakes (bool)
Attempts to unpack the takes to new clips.
void updateLinkedClips ()
Triggers a call to cloneFrom for all clips with the same linkID.
virtual PatternGenerator * getPatternGenerator ()
Returns the PatternGenerator for this clip if it has one.
void addListener (Listener *)
Adds a Listener.
void removeListener (Listener *)
Removes a Listener.
juce::ListenerList< Listener > & getListeners ()
Returns the listener list so Nodes can manually call them.
void changed () override
juce::UndoManager * getUndoManager () const
Returns the UndoManager.
virtual void setParent (ClipOwner *)
Public Member Functions inherited from tracktion::engine::TrackItem
TrackItem (Edit &, EditItemID, Type)
Creates a TrackItem with an ID and type.
~TrackItem ()
Destructor.
TimeRange getEditTimeRange () const
Returns the time range of this item.
BeatRange getEditBeatRange () const
Returns the beat range of this item.
BeatPosition getStartBeat () const
Returns the start beat in the Edit of this item.
BeatPosition getContentStartBeat () const
Returns the start beat of the content in the Edit of this item.
BeatPosition getEndBeat () const
Returns the end beat in the Edit of this item.
BeatDuration getLengthInBeats () const
Returns the duration in beats the of this item.
TimePosition getTimeOfRelativeBeat (BeatDuration) const
Returns an Edit time point for a given number of beats from the start of this item.
BeatPosition getBeatOfRelativeTime (TimeDuration) const
Returns an Edit beat point for a given number of seconds from the start of this item.
BeatDuration getOffsetInBeats () const
Returns an the offset of this item in beats.
EditItemID getTrackID () const
Returns the ID of the Track this item lives on.
Public Member Functions inherited from tracktion::engine::EditItem
EditItem (EditItemID, Edit &)
EditItem (Edit &, const juce::ValueTree &)
virtual ~EditItem ()=default
Public Member Functions inherited from tracktion::engine::Selectable
Selectable ()
virtual ~Selectable ()
virtual void selectionStatusChanged (bool isNowSelected)
Can be overridden to tell this object that it has just been selected or deselected.
virtual void selectableAboutToBeDeleted ()
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void addListener (SelectableListener *)
void removeListener (SelectableListener *)
void addSelectableListener (SelectableListener *)
void removeSelectableListener (SelectableListener *)
void cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
void deselect ()
void propertiesChanged ()
void notifyListenersOfDeletion ()
WeakRef getWeakRef ()
Public Member Functions inherited from tracktion::engine::Exportable
virtual ~Exportable ()=default
Public Attributes
juce::CachedValue< bool > repeatSequence
Public Attributes inherited from tracktion::engine::Clip
juce::CachedValue< FollowActionDurationType > followActionDurationType
The type of duration to use for when to trigger the follow action.
juce::CachedValue< BeatDuration > followActionBeats
Determines the time for which a launched clip will play before a follow action is taken.
juce::CachedValue< double > followActionNumLoops
Determines the number of loops for which a launched clip will play before a follow action is taken.
juce::ValueTree state
The ValueTree of the Clip state.
juce::CachedValue< juce::Colour > colour
The colour property.
juce::CachedValue< bool > disabled
Whether the Clip is disabled or not.
Public Attributes inherited from tracktion::engine::TrackItem
const Type type
The type of this item.
Public Attributes inherited from tracktion::engine::EditItem
Edit & edit
const EditItemID itemID
Every EditItem has an ID which is unique within the edit.
Public Attributes inherited from tracktion::engine::Selectable
WeakRef::Master masterReference
Additional Inherited Members
Static Public Member Functions inherited from tracktion::engine::Clip
static bool isClipState (const juce::ValueTree &)
Checks whether a ValueTree is some kind of clip state.
static bool isClipState (const juce::Identifier &)
Checks whether a ValueTree type is some kind of clip state.
static Ptr createClipForState (const juce::ValueTree &, ClipOwner &targetParent)
Creates a clip for a given ValueTree representation.
Static Public Member Functions inherited from tracktion::engine::TrackItem
static const char * typeToString (Type)
Returns the string version of a TrackItem::Type.
static juce::Identifier clipTypeToXMLType (Type)
Returns an Identifier version of a TrackItem::Type.
static TrackItem::Type xmlTagToType (juce::StringRef)
Returns the TrackItem::Type of a type string.
static TrackItem::Type stringToType (const juce::String &)
Returns the TrackItem::Type of a type string.
static juce::String getSuggestedNameForNewItem (Type)
Returns a text string for a new clip of the given type.
template<typename ArrayType >
static void sortByTime (ArrayType &items)
Helper function to sort an array of TrackItem[s] by their start time.
template<typename ArrayType >
static void stableSortByTime (ArrayType &items)
Helper function to sort an array of TrackItem[s] by their start time without changing the order of items at the same time.
Static Public Member Functions inherited from tracktion::engine::Selectable
static void initialise ()
static bool isSelectableValid (const Selectable *) noexcept
checks whether this object has been deleted.
Static Public Member Functions inherited from tracktion::engine::Exportable
static juce::Array< Exportable * > addAllExportables (Edit &)
Returns all the Exportables contained in an Edit.
Protected Member Functions inherited from tracktion::engine::Clip
void setCurrentSourceFile (const juce::File &)
Sets a new source file for this clip.
virtual juce::Array< TimePosition > getRescaledMarkPoints () const
Returns the mark points relative to the start of the clip, rescaled to the current speed.
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeParentChanged (juce::ValueTree &) override
Protected Attributes inherited from tracktion::engine::Clip
bool isInitialised = false
bool cloneInProgress = false
juce::CachedValue< juce::String > clipName
ClipOwner * parent = nullptr
juce::CachedValue< TimePosition > clipStart
juce::CachedValue< TimeDuration > length
juce::CachedValue< TimeDuration > offset
juce::CachedValue< double > speedRatio
SourceFileReference sourceFileReference
juce::CachedValue< EditItemID > groupID
juce::CachedValue< juce::String > linkID
juce::File currentSourceFile
juce::CachedValue< SyncType > syncType
juce::CachedValue< bool > showingTakes
std::unique_ptr< PatternGenerator > patternGenerator
AsyncCaller updateLinkedClipsCaller
juce::ListenerList< Listener > listeners
Member Typedef Documentation
Ptr
using tracktion::engine::StepClip::Ptr = juce::ReferenceCountedObjectPtr<StepClip>
PatternArray
using tracktion::engine::StepClip::PatternArray = juce::ReferenceCountedArray<PatternInstance>
Member Enumeration Documentation
Defaults
enum tracktion::engine::StepClip::Defaults
Enumerator
defaultNumNotes
defaultNumChannels
defaultMidiChannel
defaultNoteNumber
defaultNoteValue
minNumNotes
maxNumNotes
minNumChannels
maxNumChannels
Constructor & Destructor Documentation
StepClip()
tracktion::engine::StepClip::StepClip (const juce::ValueTree & , EditItemID , ClipOwner &)
~StepClip()
tracktion::engine::StepClip::~StepClip () override
Member Function Documentation
cloneFrom()
void tracktion::engine::StepClip::cloneFrom (Clip *) override virtual
Clones the given clip to this clip.
Reimplemented from tracktion::engine::Clip.
getChannels()
const juce::Array< Channel * > & tracktion::engine::StepClip::getChannels () const noexcept
removeChannel()
void tracktion::engine::StepClip::removeChannel (int index)
insertNewChannel()
void tracktion::engine::StepClip::insertNewChannel (int index)
usesProbability()
bool tracktion::engine::StepClip::usesProbability ()
getPatternSequence()
PatternArray tracktion::engine::StepClip::getPatternSequence () const
setPatternSequence()
void tracktion::engine::StepClip::setPatternSequence (const PatternArray &)
insertVariation()
void tracktion::engine::StepClip::insertVariation (int patternIndex, int insertIndex)
removeVariation()
void tracktion::engine::StepClip::removeVariation (int variationIndex)
removeAllVariations()
void tracktion::engine::StepClip::removeAllVariations ()
createDefaultPatternIfEmpty()
void tracktion::engine::StepClip::createDefaultPatternIfEmpty ()
setPatternForVariation()
void tracktion::engine::StepClip::setPatternForVariation (int variationIndex, int newPatternIndex)
insertPattern()
int tracktion::engine::StepClip::insertPattern (const Pattern & , int index)
insertNewPattern()
int tracktion::engine::StepClip::insertNewPattern (int index)
removePattern()
void tracktion::engine::StepClip::removePattern (int patternIndex)
removeUnusedPatterns()
void tracktion::engine::StepClip::removeUnusedPatterns ()
getCell()
bool tracktion::engine::StepClip::getCell (int patternIndex, int channelIndex, int noteIndex)
setCell()
void tracktion::engine::StepClip::setCell (int patternIndex, int channelIndex, int noteIndex, bool value)
getPattern()
Pattern tracktion::engine::StepClip::getPattern (int index)
getNumPatterns()
int tracktion::engine::StepClip::getNumPatterns () const
getPatterns()
juce::Array< Pattern > tracktion::engine::StepClip::getPatterns ()
getVolumeDb()
float tracktion::engine::StepClip::getVolumeDb () const
setVolumeDb()
void tracktion::engine::StepClip::setVolumeDb (float v)
generateMidiSequence() [1/2]
void tracktion::engine::StepClip::generateMidiSequence (juce::MidiMessageSequence & result, bool convertToSeconds = true, PatternInstance * instance = nullptr)
Generate a MidiMessageSequence from either the entire clip or one of its pattern instances.
Parameters
[out] result Result sequence to add the messages to
[in] convertToSeconds Leave the timestamps in beats, or convert them to seconds while generating
[in] instance Specific pattern to generate, nullptr for the whole clip
generateMidiSequence() [2/2]
juce::MidiMessageSequence tracktion::engine::StepClip::generateMidiSequence (MidiList::TimeBase , PatternInstance * instance = nullptr)
Generate a MidiMessageSequence from either the entire clip or one of its pattern instances.
Parameters
[in] PatternInstance Specific pattern to generate, nullptr for the whole clip
[in] TimeBase The time base for the sequence
Returns
result Result sequence
getBeatTimesOfPatternStarts()
juce::Array< BeatPosition > tracktion::engine::StepClip::getBeatTimesOfPatternStarts () const
getStartBeatOf()
BeatPosition tracktion::engine::StepClip::getStartBeatOf (PatternInstance *)
getEndBeatOf()
BeatPosition tracktion::engine::StepClip::getEndBeatOf (PatternInstance *)
getBeatsPerBar()
int tracktion::engine::StepClip::getBeatsPerBar ()
resizeClipForPatternInstances()
void tracktion::engine::StepClip::resizeClipForPatternInstances ()
canBeAddedTo()
bool tracktion::engine::StepClip::canBeAddedTo (ClipOwner &) override virtual
Tests whether this clip can go on the given parent.
Implements tracktion::engine::Clip.
getSelectableDescription()
juce::String tracktion::engine::StepClip::getSelectableDescription () override virtual
Subclasses must return a description of what they are.
Implements tracktion::engine::Selectable.
getDefaultColour()
juce::Colour tracktion::engine::StepClip::getDefaultColour () const override virtual
Returns the default colour for this clip.
Implements tracktion::engine::Clip.
isMidi()
bool tracktion::engine::StepClip::isMidi () const override virtual
Returns true if this is a MidiClip.
Implements tracktion::engine::Clip.
beatBasedLooping()
bool tracktion::engine::StepClip::beatBasedLooping () const override virtual
Returns true if this clip's looping is based on beats or false if absolute time.
Reimplemented from tracktion::engine::Clip.
isMuted()
bool tracktion::engine::StepClip::isMuted () const override virtual
Returns true if the clip is muted.
Implements tracktion::engine::Clip.
setMuted()
void tracktion::engine::StepClip::setMuted (bool) override virtual
Mutes or unmutes the clip.
Reimplemented from tracktion::engine::Clip.
getLiveClipLevel()
LiveClipLevel tracktion::engine::StepClip::getLiveClipLevel ()
canLoop()
bool tracktion::engine::StepClip::canLoop () const override virtual
StepClips can only loop if they're being used as launcher clips.
Arranger clips will automatically loop until their end time.
Reimplemented from tracktion::engine::Clip.
Referenced by getLoopLengthBeats(), getLoopStartBeats(), and isLooping().
getPosition()
ClipPosition tracktion::engine::StepClip::getPosition () const override virtual
Reimplemented from tracktion::engine::Clip.
isLooping()
bool tracktion::engine::StepClip::isLooping () const override virtual
Reimplemented from tracktion::engine::Clip.
References canLoop().
setNumberOfLoops()
void tracktion::engine::StepClip::setNumberOfLoops (int) override virtual
Reimplemented from tracktion::engine::Clip.
disableLooping()
void tracktion::engine::StepClip::disableLooping () override virtual
Reimplemented from tracktion::engine::Clip.
setLoopRange()
void tracktion::engine::StepClip::setLoopRange (TimeRange) override virtual
Reimplemented from tracktion::engine::Clip.
setLoopRangeBeats()
void tracktion::engine::StepClip::setLoopRangeBeats (BeatRange) override virtual
Reimplemented from tracktion::engine::Clip.
getLoopStartBeats()
BeatPosition tracktion::engine::StepClip::getLoopStartBeats () const override virtual
Reimplemented from tracktion::engine::Clip.
References canLoop().
getLoopLengthBeats()
BeatDuration tracktion::engine::StepClip::getLoopLengthBeats () const override virtual
Reimplemented from tracktion::engine::Clip.
References canLoop().
getLoopStart()
TimePosition tracktion::engine::StepClip::getLoopStart () const override virtual
Reimplemented from tracktion::engine::Clip.
getLoopLength()
TimeDuration tracktion::engine::StepClip::getLoopLength () const override virtual
Reimplemented from tracktion::engine::Clip.
getLaunchHandle()
std::shared_ptr< LaunchHandle > tracktion::engine::StepClip::getLaunchHandle () override virtual
Reimplemented from tracktion::engine::Clip.
setUsesGlobalLaunchQuatisation()
void tracktion::engine::StepClip::setUsesGlobalLaunchQuatisation (bool useGlobal) override virtual
Reimplemented from tracktion::engine::Clip.
usesGlobalLaunchQuatisation()
bool tracktion::engine::StepClip::usesGlobalLaunchQuatisation () override virtual
Reimplemented from tracktion::engine::Clip.
getLaunchQuantisation()
LaunchQuantisation * tracktion::engine::StepClip::getLaunchQuantisation () override virtual
Reimplemented from tracktion::engine::Clip.
getFollowActions()
FollowActions * tracktion::engine::StepClip::getFollowActions () override virtual
Reimplemented from tracktion::engine::Clip.
Member Data Documentation
repeatSequence
juce::CachedValue<bool> tracktion::engine::StepClip::repeatSequence
The documentation for this class was generated from the following file:
tracktion_StepClip.h