TracktionEngine: tracktion_engine::MessageThreadCallback Class Reference
tracktion_engine::MessageThreadCallback Class Reference abstract
Calls a function on the message thread checking a calling thread for an exit signal.
Public Member Functions
MessageThreadCallback ()=default
~MessageThreadCallback () override
bool hasFinished () const noexcept
Returns true if the callback has completed.
void triggerAndWaitForCallback ()
Triggers the callback to happen on the message thread and blocks until it has returned or the thread signals it should exit.
virtual void performAction ()=0
Detailed Description
Calls a function on the message thread checking a calling thread for an exit signal.
Constructor & Destructor Documentation
MessageThreadCallback()
tracktion_engine::MessageThreadCallback::MessageThreadCallback () default
~MessageThreadCallback()
tracktion_engine::MessageThreadCallback::~MessageThreadCallback () override
Member Function Documentation
hasFinished()
bool tracktion_engine::MessageThreadCallback::hasFinished () const noexcept
Returns true if the callback has completed.
Referenced by tracktion_engine::callBlocking(), and triggerAndWaitForCallback().
triggerAndWaitForCallback()
void tracktion_engine::MessageThreadCallback::triggerAndWaitForCallback ()
Triggers the callback to happen on the message thread and blocks until it has returned or the thread signals it should exit.
References hasFinished().
Referenced by tracktion_engine::callBlocking().
performAction()
virtual void tracktion_engine::MessageThreadCallback::performAction () pure virtual
The documentation for this class was generated from the following file:
tracktion_AsyncFunctionUtils.h