TracktionEngine: AudioSourceWrapper Class Reference
AudioSourceWrapper Class Reference
tracktion_engine » plugins
#include <tracktion_ARAWrapperInterfaces.h>
Public Member Functions
AudioSourceWrapper (ARADocument &d, AudioClipBase &audioClip)
~AudioSourceWrapper ()
NodeReader * createReader ()
void enableAccess (bool b)
SizedStruct< ARA_STRUCT_MEMBER(ARAAudioSourceProperties, merits64BitSamples)> getAudioSourceProperties ()
Static Public Member Functions
static ARAAudioReaderHostRef ARA_CALL createAudioReaderForSource (ARAAudioAccessControllerHostRef, ARAAudioSourceHostRef hostAudioSourceRef, ARABool)
static ARABool ARA_CALL readAudioSamples (ARAAudioAccessControllerHostRef, ARAAudioReaderHostRef hostReaderRef, ARASamplePosition samplePosition, ARASampleCount samplesPerChannel, void *const *buffers)
static void ARA_CALL destroyAudioReader (ARAAudioAccessControllerHostRef, ARAAudioReaderHostRef hostReaderRef)
Public Attributes
ARADocument & doc
AudioClipBase & clip
ARAAudioSourceRef audioSourceRef = {}
Constructor & Destructor Documentation
AudioSourceWrapper()
AudioSourceWrapper::AudioSourceWrapper (ARADocument & d, AudioClipBase & audioClip)
References audioSourceRef, CRASH_TRACER, ARADocument::dci, ARADocument::dcRef, doc, and getAudioSourceProperties().
~AudioSourceWrapper()
AudioSourceWrapper::~AudioSourceWrapper ()
References audioSourceRef, CRASH_TRACER, ARADocument::dci, ARADocument::dcRef, doc, and enableAccess().
Member Function Documentation
createReader()
NodeReader * AudioSourceWrapper::createReader ()
References clip, and CRASH_TRACER.
Referenced by getAudioSourceProperties().
enableAccess()
void AudioSourceWrapper::enableAccess (bool b)
References audioSourceRef, ARADocument::dci, ARADocument::dcRef, and doc.
Referenced by ~AudioSourceWrapper().
createAudioReaderForSource()
static ARAAudioReaderHostRef ARA_CALL AudioSourceWrapper::createAudioReaderForSource (ARAAudioAccessControllerHostRef , ARAAudioSourceHostRef hostAudioSourceRef, ARABool) static
References CRASH_TRACER.
readAudioSamples()
static ARABool ARA_CALL AudioSourceWrapper::readAudioSamples (ARAAudioAccessControllerHostRef , ARAAudioReaderHostRef hostReaderRef, ARASamplePosition samplePosition, ARASampleCount samplesPerChannel, void *const * buffers) static
destroyAudioReader()
static void ARA_CALL AudioSourceWrapper::destroyAudioReader (ARAAudioAccessControllerHostRef , ARAAudioReaderHostRef hostReaderRef) static
References CRASH_TRACER.
getAudioSourceProperties()
SizedStruct< ARA_STRUCT_MEMBER(ARAAudioSourceProperties, merits64BitSamples)> AudioSourceWrapper::getAudioSourceProperties ()
References clip, and createReader().
Referenced by AudioSourceWrapper().
Member Data Documentation
doc
ARADocument& AudioSourceWrapper::doc
Referenced by AudioSourceWrapper(), enableAccess(), and ~AudioSourceWrapper().
clip
AudioClipBase& AudioSourceWrapper::clip
Referenced by createReader(), and getAudioSourceProperties().
audioSourceRef
ARAAudioSourceRef AudioSourceWrapper::audioSourceRef = {}
Referenced by AudioModificationWrapper::AudioModificationWrapper(), AudioSourceWrapper(), enableAccess(), and ~AudioSourceWrapper().
The documentation for this class was generated from the following file:
tracktion_ARAWrapperInterfaces.h