TracktionEngine: tracktion_engine::WaveAudioClip Class Reference
tracktion_engine::WaveAudioClip Class Reference
tracktion_engine » model
Public Types
using Ptr = juce::ReferenceCountedObjectPtr< WaveAudioClip >
Public Types inherited from tracktion_engine::AudioClipBase
enum FadeBehaviour { gainFade = 0, speedRamp }
enum AutoPitchMode { pitchTrack = 0, chordTrackMono, chordTrackPoly }
enum ClipDirection { ClipDirection::previous, ClipDirection::next, ClipDirection::none }
Public Types inherited from tracktion_engine::Clip
enum SyncType { syncBarsBeats = 0, syncAbsolute }
using Ptr = juce::ReferenceCountedObjectPtr< Clip >
using Array = juce::ReferenceCountedArray< Clip >
Public Types inherited from tracktion_engine::TrackItem
enum Type {
Type::unknown, Type::wave, Type::midi, Type::edit,
Type::step, Type::marker, Type::pitch, Type::timeSig,
Type::collection, Type::video, Type::recording, Type::chord,
Type::arranger
}
Public Types inherited from tracktion_engine::Selectable
using WeakRef = juce::WeakReference< Selectable >
Public Member Functions
WaveAudioClip (const juce::ValueTree &, EditItemID, ClipTrack &)
~WaveAudioClip () override
void initialise () override
void cloneFrom (Clip *) override
juce::String getSelectableDescription () override
Subclasses must return a description of what they are.
bool isMidi () const override
bool usesSourceFile () override
true if it references a source file - i.e.
double getSourceLength () const override
Must return the length in seconds of the source material e.g.
void sourceMediaChanged () override
this is called when the source media file reference (attribute "source") has changed - i.e.
juce::File getOriginalFile () const override
Must return the file that the source ProjectItemID refers to.
juce::int64 getHash () const override
Must return a unique hash for this clip's source.
void setLoopDefaults () override
Override this to fill in the LoopInfo structure as best fits the source.
void addTake (ProjectItemID)
void addTake (const juce::File &)
bool hasAnyTakes () const override
int getNumTakes (bool includeComps) override
juce::Array< ProjectItemID > getTakes () const override
void clearTakes () override
int getCurrentTake () const override
void setCurrentTake (int takeIndex) override
bool isCurrentTakeComp () override
juce::StringArray getTakeDescriptions () const override
void deleteAllUnusedTakes (bool deleteSourceFiles)
void deleteAllUnusedTakesConfirmingWithUser (bool deleteSourceFiles)
Clip::Array unpackTakes (bool toNewTracks) override
WaveCompManager & getCompManager ()
void reassignReferencedItem (const ReferencedItem &, ProjectItemID newID, double newStartTime) override
bool needsRender () const override
Subclasses should override this to return true if they need the rest of the render callbacks.
RenderManager::Job::Ptr getRenderJob (const AudioFile &destFile) override
Subclasses should override this to return a RenderJob suitable for rendering its source file.
juce::String getRenderMessage () override
Override this to return a custom message to be displayed over waveforms during rendering.
void renderComplete () override
Callback to indicate that the render has completed.
bool isUsingFile (const AudioFile &af) override
Should return true if the clip is referencing the file in any way.
Public Member Functions inherited from tracktion_engine::AudioClipBase
AudioClipBase (const juce::ValueTree &, EditItemID, Type, ClipTrack &)
Creates a basic AudioClip.
~AudioClipBase () override
Destructor.
void flushStateToValueTree () override
void setTrack (ClipTrack *) override
bool canGoOnTrack (Track &) override
void changed () override
This should be called to send a change notification to any SelectableListeners that are registered with this object.
juce::Colour getDefaultColour () const override
double getMaximumLength () override
Returns the maximum length for this clip.
virtual AudioFile getAudioFile () const
Returns the file used to play back the source and will get proxied etc.
AudioFile getPlaybackFile ()
Returns the current AudioFile being used by the Clip, either the original source or a proxy.
virtual AudioFileInfo getWaveInfo ()
Returns the WaveInfo for a clip.
void markAsDirty ()
Resets the dirty flag so that a new render will be attempted.
void updateSourceFile ()
Checks the current source file to see if it's up to date and then triggers a source render if needed.
virtual juce::String getClipMessage ()
Override this to return a custom message to display over the clip where the "file missing" text usually goes.
void cancelCurrentRender ()
PatternGenerator * getPatternGenerator () override
void setGainDB (float dB)
float getGainDB () const noexcept
float getGain () const noexcept
void setPan (float pan)
float getPan () const noexcept
void setMuted (bool shouldBeMuted) override
bool isMuted () const override
LiveClipLevel getLiveClipLevel ()
void setLeftChannelActive (bool)
bool isLeftChannelActive () const
void setRightChannelActive (bool)
bool isRightChannelActive () const
bool setFadeIn (double length)
double getFadeIn () const
bool setFadeOut (double length)
double getFadeOut () const
void setFadeInType (AudioFadeCurve::Type newType)
AudioFadeCurve::Type getFadeInType () const
void setFadeOutType (AudioFadeCurve::Type newType)
AudioFadeCurve::Type getFadeOutType () const
void setAutoCrossfade (bool shouldAutoCrossfade)
bool getAutoCrossfade () const noexcept
void updateAutoCrossfadesAsync (bool updateOverlapped)
void applyEdgeFades ()
void copyFadeToAutomation (bool fadeIn, bool removeClipFade)
void setFadeInBehaviour (FadeBehaviour newBehaviour)
FadeBehaviour getFadeInBehaviour () const
void setFadeOutBehaviour (FadeBehaviour newBehaviour)
FadeBehaviour getFadeOutBehaviour () const
void setLoopInfo (const LoopInfo &)
const LoopInfo & getLoopInfo () const
LoopInfo & getLoopInfo ()
bool canLoop () const override
bool isLooping () const override
bool beatBasedLooping () const override
void setNumberOfLoops (int num) override
void disableLooping () override
EditTimeRange getLoopRange () const
double getLoopStartBeats () const override
double getLoopStart () const override
double getLoopLengthBeats () const override
double getLoopLength () const override
void setLoopRange (EditTimeRange) override
void setLoopRangeBeats (juce::Range< double >) override
void setAutoDetectBeats (bool)
bool getAutoDetectBeats () const
void setBeatSensitivity (float s)
float getBeatSensitivity () const
void pitchTempoTrackChanged () override
void clearCachedAudioSegmentList ()
const AudioSegmentList * getAudioSegmentList ()
void setSpeedRatio (double newSpeed) override
void setTimeStretchMode (TimeStretcher::Mode mode)
TimeStretcher::Mode getTimeStretchMode () const noexcept
TimeStretcher::Mode getActualTimeStretchMode () const noexcept
void setAutoTempo (bool shouldUseAutoTempo)
bool getAutoTempo () const
void setAutoPitch (bool shouldUseAutoPitch)
bool getAutoPitch () const
void setAutoPitchMode (AutoPitchMode m)
AutoPitchMode getAutoPitchMode ()
void setWarpTime (bool shouldUseWarpTime)
bool getWarpTime () const
WarpTimeManager & getWarpTimeManager () const
void setTranspose (int numSemitones)
int getTransposeSemiTones (bool includeAutoPitch) const
void setPitchChange (float semitones)
float getPitchChange () const
float getPitchRatio () const
void setIsReversed (bool shouldBeReversed)
bool getIsReversed () const noexcept
LoopInfo autoDetectBeatMarkers (const LoopInfo &current, bool autoBeat, float sens) const
bool performTempoDetect ()
juce::StringArray getPitchChoices ()
virtual bool canHaveEffects () const
void enableEffects (bool, bool warn)
bool effectsEnabled () const
void addEffect (const juce::ValueTree &effectsTree)
void setEffectsVisible (bool b)
bool getEffectsVisible () const
ClipEffects * getClipEffects () const noexcept
void addMark (double relCursorPos)
void moveMarkTo (double relCursorPos)
void deleteMark (double relCursorPos)
juce::Array< double > getRescaledMarkPoints () const override
bool canSnapToOriginalBWavTime ()
void snapToOriginalBWavTime ()
juce::Array< ReferencedItem > getReferencedItems () override
juce::String canAddClipPlugin (const Plugin::Ptr &) const
bool addClipPlugin (const Plugin::Ptr &, SelectionManager &) override
returns false if the clip can't do this
Plugin::Array getAllPlugins () override
void sendMirrorUpdateToAllPlugins (Plugin &) const override
PluginList * getPluginList () override
AudioNode * createAudioNode (const CreateAudioNodeParams &) override
Creates the AudioNode used to playback this Clip in an Edit.
AudioNode * createMelodyneAudioNode ()
AudioFile getProxyFileToCreate (bool renderTimestretched)
void setUsesProxy (bool canUseProxy) noexcept
bool canUseProxy () const noexcept
bool usesTimeStretchedProxy () const
std::unique_ptr< ProxyRenderingInfo > createProxyRenderingInfo ()
juce::int64 getProxyHash ()
void beginRenderingNewProxyIfNeeded ()
void setUsesTimestretchedPreview (bool shouldUsePreview) noexcept
bool usesTimestretchedPreview () const noexcept
void reverseLoopPoints ()
void checkFadeLengthsForOverrun ()
AudioClipBase * getOverlappingClip (ClipDirection) const
void getRescaledMarkPoints (juce::Array< double > &rescaled, juce::Array< int > &orig) const
bool isUsingMelodyne () const
void loadMelodyneState (Edit &)
void showMelodyneWindow ()
void hideMelodyneWindow ()
void melodyneConvertToMIDI ()
Public Member Functions inherited from tracktion_engine::Clip
Clip (const juce::ValueTree &, ClipTrack &, EditItemID, Type)
~Clip () override
virtual juce::String getName () override
void setName (const juce::String &newName)
SourceFileReference & getSourceFileReference ()
Returns the SourceFileReference of the Clip.
juce::File getCurrentSourceFile () const
Returns the current source file, this is different to the SourceFileReference as it could be a temporary comp file, clipFX, reverse render etc.
juce::Array< ReferencedItem > getReferencedItems () override
ClipPosition getPosition () const override
double getContentBeatAtTime (double time) const
Returns the beat number (with offset) at the given time.
double getTimeOfContentBeat (double beat) const
Returns time of a beat number.
virtual juce::Array< double > getInterestingTimes ()
Returns times for snapping to, relative to the edit.
double getSpottingPoint () const
virtual void setSyncType (SyncType sync)
SyncType getSyncType () const
void setPosition (ClipPosition newPosition)
void setStart (double newStart, bool preserveSync, bool keepLength)
void setLength (double newLength, bool preserveSync)
void setEnd (double newEnd, bool preserveSync)
void setOffset (double newOffset)
void trimAwayOverlap (EditTimeRange editRangeToTrim)
trims away any part of the clip that overlaps this region.
void removeFromParentTrack ()
bool moveToTrack (Track &)
double getSpeedRatio () const noexcept
virtual void rescale (double pivotTimeInEdit, double factor)
bool isGrouped () const override
TrackItem * getGroupParent () const override
void setGroup (EditItemID newGroupID)
EditItemID getGroupID () const noexcept
CollectionClip * getGroupClip () const
bool isLinked () const
void setLinkGroupID (EditItemID newLinkID)
EditItemID getLinkGroupID () const
ClipTrack * getClipTrack () const
Track * getTrack () const override
virtual juce::Colour getColour () const
void setColour (juce::Colour col)
virtual void removePlugin (const Plugin::Ptr &)
if the clip can contain plugins, it should implement this
virtual void setShowingTakes (bool shouldShow)
virtual bool isShowingTakes () const
void updateLinkedClips ()
void showLoopMenu ()
void changed () override
This should be called to send a change notification to any SelectableListeners that are registered with this object.
juce::UndoManager * getUndoManager () const
Public Member Functions inherited from tracktion_engine::TrackItem
TrackItem (Edit &, EditItemID, Type)
~TrackItem ()
EditTimeRange getEditTimeRange () const
double getStartBeat () const
double getContentStartBeat () const
double getEndBeat () const
double getLengthInBeats () const
double getTimeOfRelativeBeat (double beat) const
double getBeatOfRelativeTime (double t) const
double getOffsetInBeats () const
EditItemID getTrackID () const
Public Member Functions inherited from tracktion_engine::EditItem
EditItem (EditItemID, Edit &)
virtual ~EditItem ()=default
Public Member Functions inherited from tracktion_engine::Selectable
Selectable ()
virtual ~Selectable ()
virtual void selectionStatusChanged (bool isNowSelected)
Can be overridden to tell this object that it has just been selected or deselected.
virtual void selectableAboutToBeDeleted ()
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void addSelectableListener (SelectableListener *)
void removeSelectableListener (SelectableListener *)
void cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
void deselect ()
void propertiesChanged ()
void notifyListenersOfDeletion ()
WeakRef getWeakRef ()
Public Member Functions inherited from tracktion_engine::Exportable
virtual ~Exportable ()=default
Public Member Functions inherited from tracktion_engine::RenderManager::Job::Listener
virtual ~Listener ()
virtual void jobStarted (RenderManager::Job &)
Additional Inherited Members
Static Public Member Functions inherited from tracktion_engine::AudioClipBase
static juce::StringArray getRootNoteChoices (Engine &)
Static Public Member Functions inherited from tracktion_engine::Clip
static bool isClipState (const juce::ValueTree &)
Checks whether a ValueTree is some kind of clip state.
static bool isClipState (const juce::Identifier &)
Checks whether a ValueTree type is some kind of clip state.
static Ptr createClipForState (const juce::ValueTree &, ClipTrack &targetTrack)
Creates a clip for a given ValueTree representation.
Static Public Member Functions inherited from tracktion_engine::TrackItem
static const char * typeToString (Type)
static juce::Identifier clipTypeToXMLType (Type)
static TrackItem::Type xmlTagToType (juce::StringRef)
static TrackItem::Type stringToType (const juce::String &)
static juce::String getSuggestedNameForNewItem (Type)
template<typename ArrayType >
static void sortByTime (ArrayType &items)
template<typename ArrayType >
static void stableSortByTime (ArrayType &items)
Static Public Member Functions inherited from tracktion_engine::Selectable
static void initialise ()
static bool isSelectableValid (const Selectable *) noexcept
checks whether this object has been deleted.
Static Public Member Functions inherited from tracktion_engine::Exportable
static juce::Array< Exportable * > addAllExportables (Edit &)
Returns all the Exportables contained in an Edit.
Public Attributes inherited from tracktion_engine::AudioClipBase
juce::ReferenceCountedObjectPtr< MelodyneFileReader > melodyneProxy
juce::CachedValue< TimeStretcher::ElastiqueProOptions > elastiqueProOptions
Public Attributes inherited from tracktion_engine::Clip
juce::ValueTree state
juce::CachedValue< juce::Colour > colour
Public Attributes inherited from tracktion_engine::TrackItem
const Type type
Public Attributes inherited from tracktion_engine::EditItem
Edit & edit
const EditItemID itemID
Every EditItem has an ID which is unique within the edit.
Public Attributes inherited from tracktion_engine::Selectable
WeakRef::Master masterReference
Protected Member Functions inherited from tracktion_engine::AudioClipBase
void updateLeftRightChannelActivenessFlags ()
void createNewProxyAsync ()
Triggers a source or proxy render after a timeout.
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeChildAdded (juce::ValueTree &parent, juce::ValueTree &) override
void valueTreeChildRemoved (juce::ValueTree &parent, juce::ValueTree &, int) override
void valueTreeChildOrderChanged (juce::ValueTree &, int, int) override
void valueTreeParentChanged (juce::ValueTree &) override
Protected Member Functions inherited from tracktion_engine::Clip
void setCurrentSourceFile (const juce::File &)
void updateParentTrack ()
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeChildAdded (juce::ValueTree &, juce::ValueTree &) override
void valueTreeChildRemoved (juce::ValueTree &, juce::ValueTree &, int) override
void valueTreeChildOrderChanged (juce::ValueTree &, int, int) override
void valueTreeParentChanged (juce::ValueTree &) override
Protected Attributes inherited from tracktion_engine::AudioClipBase
std::shared_ptr< ClipLevel > level { std::make_shared<ClipLevel>() }
juce::CachedValue< juce::String > channels
juce::CachedValue< double > fadeIn
juce::CachedValue< double > fadeOut
double autoFadeIn = 0
double autoFadeOut = 0
juce::CachedValue< AudioFadeCurve::Type > fadeInType
juce::CachedValue< AudioFadeCurve::Type > fadeOutType
juce::CachedValue< bool > autoCrossfade
juce::CachedValue< FadeBehaviour > fadeInBehaviour
juce::CachedValue< FadeBehaviour > fadeOutBehaviour
juce::CachedValue< double > loopStart
juce::CachedValue< double > loopLength
juce::CachedValue< double > loopStartBeats
juce::CachedValue< double > loopLengthBeats
juce::CachedValue< int > transpose
juce::CachedValue< float > pitchChange
LoopInfo loopInfo
juce::CachedValue< float > beatSensitivity
juce::CachedValue< TimeStretcher::Mode > timeStretchMode
juce::CachedValue< bool > autoPitch
juce::CachedValue< bool > autoTempo
juce::CachedValue< bool > isReversed
juce::CachedValue< bool > autoDetectBeats
juce::CachedValue< bool > warpTime
juce::CachedValue< bool > clipEffectsVisible
juce::CachedValue< AutoPitchMode > autoPitchMode
WarpTimeManager::Ptr warpTimeManager
std::unique_ptr< AudioSegmentList > audioSegmentList
std::unique_ptr< ClipEffects > clipEffects
AsyncFunctionCaller asyncFunctionCaller
juce::AudioChannelSet activeChannels
bool proxyAllowed = true
bool useTimestretchedPreview = false
PluginList pluginList
bool lastRenderJobFailed = false
RenderManager::Job::Ptr renderJob
AudioFile lastProxy
Protected Attributes inherited from tracktion_engine::Clip
bool isInitialised = false
bool cloneInProgress = false
juce::CachedValue< juce::String > clipName
ClipTrack * track = nullptr
juce::CachedValue< double > clipStart
juce::CachedValue< double > length
juce::CachedValue< double > offset
juce::CachedValue< double > speedRatio
SourceFileReference sourceFileReference
juce::CachedValue< EditItemID > groupID
juce::CachedValue< EditItemID > linkID
juce::File currentSourceFile
juce::CachedValue< SyncType > syncType
juce::CachedValue< bool > showingTakes
std::unique_ptr< PatternGenerator > patternGenerator
AsyncCaller updateLinkedClipsCaller
Member Typedef Documentation
Ptr
using tracktion_engine::WaveAudioClip::Ptr = juce::ReferenceCountedObjectPtr<WaveAudioClip>
Constructor & Destructor Documentation
WaveAudioClip()
tracktion_engine::WaveAudioClip::WaveAudioClip (const juce::ValueTree & , EditItemID , ClipTrack &)
~WaveAudioClip()
tracktion_engine::WaveAudioClip::~WaveAudioClip () override
Member Function Documentation
initialise()
void tracktion_engine::WaveAudioClip::initialise () override virtual
Reimplemented from tracktion_engine::AudioClipBase.
cloneFrom()
void tracktion_engine::WaveAudioClip::cloneFrom (Clip *) override virtual
Reimplemented from tracktion_engine::AudioClipBase.
getSelectableDescription()
juce::String tracktion_engine::WaveAudioClip::getSelectableDescription () override virtual
Subclasses must return a description of what they are.
Implements tracktion_engine::Selectable.
isMidi()
bool tracktion_engine::WaveAudioClip::isMidi () const override virtual
Implements tracktion_engine::Clip.
usesSourceFile()
bool tracktion_engine::WaveAudioClip::usesSourceFile () override virtual
true if it references a source file - i.e.
audio clips do, midi doesn't.
Reimplemented from tracktion_engine::Clip.
References addTake(), getHash(), getOriginalFile(), getSourceLength(), setLoopDefaults(), and sourceMediaChanged().
getSourceLength()
double tracktion_engine::WaveAudioClip::getSourceLength () const override virtual
Must return the length in seconds of the source material e.g.
the length of the audio file or edit.
Implements tracktion_engine::AudioClipBase.
Referenced by usesSourceFile().
sourceMediaChanged()
void tracktion_engine::WaveAudioClip::sourceMediaChanged () override virtual
this is called when the source media file reference (attribute "source") has changed - i.e.
when the clip has a new media id assigned, not when the file itself changes.
Reimplemented from tracktion_engine::Clip.
Referenced by usesSourceFile().
getOriginalFile()
juce::File tracktion_engine::WaveAudioClip::getOriginalFile () const override virtual
Must return the file that the source ProjectItemID refers to.
Implements tracktion_engine::AudioClipBase.
Referenced by usesSourceFile().
getHash()
juce::int64 tracktion_engine::WaveAudioClip::getHash () const override virtual
Must return a unique hash for this clip's source.
This should be the same until the clip changes as it is used to determine if the proxy needs regenerating.
Implements tracktion_engine::AudioClipBase.
Referenced by usesSourceFile().
setLoopDefaults()
void tracktion_engine::WaveAudioClip::setLoopDefaults () override virtual
Override this to fill in the LoopInfo structure as best fits the source.
Implements tracktion_engine::AudioClipBase.
Referenced by usesSourceFile().
addTake() [1/2]
void tracktion_engine::WaveAudioClip::addTake (ProjectItemID)
Referenced by usesSourceFile().
addTake() [2/2]
void tracktion_engine::WaveAudioClip::addTake (const juce::File &)
hasAnyTakes()
bool tracktion_engine::WaveAudioClip::hasAnyTakes () const override virtual
Reimplemented from tracktion_engine::Clip.
References clearTakes(), deleteAllUnusedTakes(), deleteAllUnusedTakesConfirmingWithUser(), getCompManager(), getCurrentTake(), getNumTakes(), getRenderJob(), getRenderMessage(), getTakeDescriptions(), getTakes(), isCurrentTakeComp(), isUsingFile(), needsRender(), reassignReferencedItem(), renderComplete(), setCurrentTake(), tracktion_engine::Clip::state, and unpackTakes().
getNumTakes()
int tracktion_engine::WaveAudioClip::getNumTakes (bool includeComps) override virtual
Reimplemented from tracktion_engine::Clip.
Referenced by hasAnyTakes().
getTakes()
juce::Array<ProjectItemID> tracktion_engine::WaveAudioClip::getTakes () const override virtual
Reimplemented from tracktion_engine::AudioClipBase.
Referenced by hasAnyTakes().
clearTakes()
void tracktion_engine::WaveAudioClip::clearTakes () override virtual
Reimplemented from tracktion_engine::Clip.
Referenced by hasAnyTakes().
getCurrentTake()
int tracktion_engine::WaveAudioClip::getCurrentTake () const override virtual
Reimplemented from tracktion_engine::Clip.
Referenced by hasAnyTakes().
setCurrentTake()
void tracktion_engine::WaveAudioClip::setCurrentTake (int takeIndex) override virtual
Reimplemented from tracktion_engine::Clip.
Referenced by hasAnyTakes().
isCurrentTakeComp()
bool tracktion_engine::WaveAudioClip::isCurrentTakeComp () override virtual
Reimplemented from tracktion_engine::Clip.
Referenced by hasAnyTakes().
getTakeDescriptions()
juce::StringArray tracktion_engine::WaveAudioClip::getTakeDescriptions () const override virtual
Reimplemented from tracktion_engine::Clip.
Referenced by hasAnyTakes().
deleteAllUnusedTakes()
void tracktion_engine::WaveAudioClip::deleteAllUnusedTakes (bool deleteSourceFiles)
Referenced by hasAnyTakes().
deleteAllUnusedTakesConfirmingWithUser()
void tracktion_engine::WaveAudioClip::deleteAllUnusedTakesConfirmingWithUser (bool deleteSourceFiles)
Referenced by hasAnyTakes().
unpackTakes()
Clip::Array tracktion_engine::WaveAudioClip::unpackTakes (bool toNewTracks) override virtual
Reimplemented from tracktion_engine::Clip.
Referenced by hasAnyTakes().
getCompManager()
WaveCompManager& tracktion_engine::WaveAudioClip::getCompManager ()
Referenced by hasAnyTakes().
reassignReferencedItem()
void tracktion_engine::WaveAudioClip::reassignReferencedItem (const ReferencedItem & , ProjectItemID newID, double newStartTime) override virtual
Reimplemented from tracktion_engine::AudioClipBase.
Referenced by hasAnyTakes().
needsRender()
bool tracktion_engine::WaveAudioClip::needsRender () const override virtual
Subclasses should override this to return true if they need the rest of the render callbacks.
Reimplemented from tracktion_engine::AudioClipBase.
Referenced by hasAnyTakes().
getRenderJob()
RenderManager::Job::Ptr tracktion_engine::WaveAudioClip::getRenderJob (const AudioFile &) override virtual
Subclasses should override this to return a RenderJob suitable for rendering its source file.
Note that because we can only render one source this should also check to see if the source should be reversed and do so accordingly. This will be called on the message thread so should complete quickly, if your source needs some time consuming setup (e.g. loading Edits) then make sure your render job does this in its render thread.
Reimplemented from tracktion_engine::AudioClipBase.
Referenced by hasAnyTakes().
getRenderMessage()
juce::String tracktion_engine::WaveAudioClip::getRenderMessage () override virtual
Override this to return a custom message to be displayed over waveforms during rendering.
This is called periodically once a render has started. Once you are done, this should return an empty string to let the AudioStripBase know to stop updating.
Reimplemented from tracktion_engine::AudioClipBase.
Referenced by hasAnyTakes().
renderComplete()
void tracktion_engine::WaveAudioClip::renderComplete () override virtual
Callback to indicate that the render has completed.
If you override this, make sure to call the base class implementation first.
Reimplemented from tracktion_engine::AudioClipBase.
Referenced by hasAnyTakes().
isUsingFile()
bool tracktion_engine::WaveAudioClip::isUsingFile (const AudioFile &) override virtual
Should return true if the clip is referencing the file in any way.
Reimplemented from tracktion_engine::AudioClipBase.
Referenced by hasAnyTakes().
The documentation for this class was generated from the following file:
tracktion_WaveAudioClip.h