TracktionEngine: tracktion::engine::LambdaSelectableListener Class Reference
tracktion::engine::LambdaSelectableListener Class Reference
A SelectableListener that safely handles listener to a Selectable and uses a lambda for its callback.
Public Member Functions
LambdaSelectableListener ()=default
Constructs an empty listener.
~LambdaSelectableListener () override
Destructor.
LambdaSelectableListener (Selectable &s)
Constructs a listener for a Selectable.
void reset (Selectable *s=nullptr)
Resets the Selectable.
Public Member Functions inherited from tracktion::engine::SelectableListener
virtual ~SelectableListener ()
Public Attributes
std::function< void()> onSelectableChanged
std::function< void()> onSelectableAboutToBeDeleted
Detailed Description
A SelectableListener that safely handles listener to a Selectable and uses a lambda for its callback.
Constructor & Destructor Documentation
LambdaSelectableListener() [1/2]
tracktion::engine::LambdaSelectableListener::LambdaSelectableListener () default
Constructs an empty listener.
~LambdaSelectableListener()
tracktion::engine::LambdaSelectableListener::~LambdaSelectableListener () override
Destructor.
References reset().
LambdaSelectableListener() [2/2]
tracktion::engine::LambdaSelectableListener::LambdaSelectableListener (Selectable & s)
Constructs a listener for a Selectable.
References reset().
Member Function Documentation
reset()
void tracktion::engine::LambdaSelectableListener::reset (Selectable * s = nullptr)
Resets the Selectable.
Referenced by LambdaSelectableListener(), and ~LambdaSelectableListener().
Member Data Documentation
onSelectableChanged
std::function<void()> tracktion::engine::LambdaSelectableListener::onSelectableChanged
onSelectableAboutToBeDeleted
std::function<void()> tracktion::engine::LambdaSelectableListener::onSelectableAboutToBeDeleted
The documentation for this class was generated from the following file:
tracktion_Selectable.h