TracktionEngine: tracktion::engine::Clipboard Class Reference
tracktion::engine::Clipboard Class Reference
tracktion_engine » selection
#include <tracktion_Clipboard.h>
Inherits juce::DeletedAtShutdown.
Classes
struct AutomationPoints
struct Clips
struct ContentType
struct MIDIEvents
struct Modifiers
struct Pitches
struct Plugins
struct ProjectItems
struct Scenes
struct Takes
struct TempoChanges
struct TimeSigs
struct Tracks
Public Member Functions
Clipboard ()
~Clipboard ()
void clear ()
bool isEmpty () const
void setContent (std::unique_ptr< ContentType > newContent)
const ContentType * getContent () const
template<typename Type , typename... Args>
void makeContent (Args &&... args)
template<typename Type >
const Type * getContentWithType () const
template<typename Type >
bool hasContentWithType () const
void addListener (juce::ChangeListener *)
void removeListener (juce::ChangeListener *)
Constructor & Destructor Documentation
Clipboard()
tracktion::engine::Clipboard::Clipboard ()
~Clipboard()
tracktion::engine::Clipboard::~Clipboard ()
Member Function Documentation
clear()
void tracktion::engine::Clipboard::clear ()
isEmpty()
bool tracktion::engine::Clipboard::isEmpty () const
setContent()
void tracktion::engine::Clipboard::setContent (std::unique_ptr< ContentType > newContent)
Referenced by makeContent().
getContent()
const ContentType * tracktion::engine::Clipboard::getContent () const
Referenced by getContentWithType().
makeContent()
template<typename Type , typename... Args> void tracktion::engine::Clipboard::makeContent (Args &&... args)
References setContent().
getContentWithType()
template<typename Type > const Type * tracktion::engine::Clipboard::getContentWithType () const
References getContent().
hasContentWithType()
template<typename Type > bool tracktion::engine::Clipboard::hasContentWithType () const
addListener()
void tracktion::engine::Clipboard::addListener (juce::ChangeListener *)
removeListener()
void tracktion::engine::Clipboard::removeListener (juce::ChangeListener *)
The documentation for this class was generated from the following file:
tracktion_Clipboard.h