TracktionEngine: tracktion::engine::TrackItem Class Reference
tracktion::engine::TrackItem Class Reference abstract
tracktion_engine » model
Base class for EditItems that live in a Track, e.g.
#include <tracktion_TrackItem.h>
Public Types
enum class Type {
unknown , wave , midi , edit ,
step , marker , pitch , timeSig ,
collection , video , recording , chord ,
arranger , container
}
Defines the types of item that can live on Track[s].
Public Types inherited from tracktion::engine::Selectable
using WeakRef = juce::WeakReference< Selectable >
Public Member Functions
TrackItem (Edit &, EditItemID, Type)
Creates a TrackItem with an ID and type.
~TrackItem ()
Destructor.
virtual Track * getTrack () const =0
Must return the track this item lives on.
virtual bool isGrouped () const
Should return true if this clip is part of a group.
virtual TrackItem * getGroupParent () const
If this clip is part of a group, this should return the parent item it belongs to.
virtual ClipPosition getPosition () const =0
Must return the position of this item.
TimeRange getEditTimeRange () const
Returns the time range of this item.
BeatRange getEditBeatRange () const
Returns the beat range of this item.
BeatPosition getStartBeat () const
Returns the start beat in the Edit of this item.
BeatPosition getContentStartBeat () const
Returns the start beat of the content in the Edit of this item.
BeatPosition getEndBeat () const
Returns the end beat in the Edit of this item.
BeatDuration getLengthInBeats () const
Returns the duration in beats the of this item.
TimePosition getTimeOfRelativeBeat (BeatDuration) const
Returns an Edit time point for a given number of beats from the start of this item.
BeatPosition getBeatOfRelativeTime (TimeDuration) const
Returns an Edit beat point for a given number of seconds from the start of this item.
BeatDuration getOffsetInBeats () const
Returns an the offset of this item in beats.
EditItemID getTrackID () const
Returns the ID of the Track this item lives on.
Public Member Functions inherited from tracktion::engine::EditItem
EditItem (EditItemID, Edit &)
EditItem (Edit &, const juce::ValueTree &)
virtual ~EditItem ()=default
virtual juce::String getName () const =0
Public Member Functions inherited from tracktion::engine::Selectable
Selectable ()
virtual ~Selectable ()
virtual juce::String getSelectableDescription ()=0
Subclasses must return a description of what they are.
virtual void selectionStatusChanged (bool isNowSelected)
Can be overridden to tell this object that it has just been selected or deselected.
virtual void changed ()
This should be called to send a change notification to any SelectableListeners that are registered with this object.
virtual void selectableAboutToBeDeleted ()
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void addListener (SelectableListener *)
void removeListener (SelectableListener *)
void addSelectableListener (SelectableListener *)
void removeSelectableListener (SelectableListener *)
void cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
void deselect ()
void propertiesChanged ()
void notifyListenersOfDeletion ()
WeakRef getWeakRef ()
Static Public Member Functions
static const char * typeToString (Type)
Returns the string version of a TrackItem::Type.
static juce::Identifier clipTypeToXMLType (Type)
Returns an Identifier version of a TrackItem::Type.
static TrackItem::Type xmlTagToType (juce::StringRef)
Returns the TrackItem::Type of a type string.
static TrackItem::Type stringToType (const juce::String &)
Returns the TrackItem::Type of a type string.
static juce::String getSuggestedNameForNewItem (Type)
Returns a text string for a new clip of the given type.
template<typename ArrayType >
static void sortByTime (ArrayType &items)
Helper function to sort an array of TrackItem[s] by their start time.
template<typename ArrayType >
static void stableSortByTime (ArrayType &items)
Helper function to sort an array of TrackItem[s] by their start time without changing the order of items at the same time.
Static Public Member Functions inherited from tracktion::engine::Selectable
static void initialise ()
static bool isSelectableValid (const Selectable *) noexcept
checks whether this object has been deleted.
Public Attributes
const Type type
The type of this item.
Public Attributes inherited from tracktion::engine::EditItem
Edit & edit
const EditItemID itemID
Every EditItem has an ID which is unique within the edit.
Public Attributes inherited from tracktion::engine::Selectable
WeakRef::Master masterReference
Detailed Description
Base class for EditItems that live in a Track, e.g.
clips
See also
WaveAudioClip, MidiClip, StepClip, MarkerClip, PitchSetting, TimeSigSetting
Member Enumeration Documentation
Type
enum class tracktion::engine::TrackItem::Type strong
Defines the types of item that can live on Track[s].
Enumerator
unknown
A placeholder for unknown items.
wave
A wave clip.
See also
WaveAudioClip
midi
A MIDI clip.
See also
MidiClip.
edit
An Edit clip.
See also
EditClip.
step
A MIDI step clip.
See also
StepClip.
marker
A marker clip.
See also
MarkerClip.
pitch
A pitch setting.
See also
PitchSetting.
timeSig
A time signature settings.
See also
TimeSigSetting.
collection
A collection clip.
See also
CollectionClip.
video
A video clip.
N.B. not yet imlemented.
recording
A temporary recording clip.
chord
A chord clip.
See also
ChordClip.
arranger
An arranger clip.
See also
ArrangerClip.
container
An container clip.
See also
ContainerClip.
Constructor & Destructor Documentation
TrackItem()
tracktion::engine::TrackItem::TrackItem (Edit & , EditItemID , Type)
Creates a TrackItem with an ID and type.
IDs should be unique within an Edit.
~TrackItem()
tracktion::engine::TrackItem::~TrackItem ()
Destructor.
Member Function Documentation
typeToString()
static const char * tracktion::engine::TrackItem::typeToString (Type) static
Returns the string version of a TrackItem::Type.
clipTypeToXMLType()
static juce::Identifier tracktion::engine::TrackItem::clipTypeToXMLType (Type) static
Returns an Identifier version of a TrackItem::Type.
xmlTagToType()
static TrackItem::Type tracktion::engine::TrackItem::xmlTagToType (juce::StringRef) static
Returns the TrackItem::Type of a type string.
stringToType()
static TrackItem::Type tracktion::engine::TrackItem::stringToType (const juce::String &) static
Returns the TrackItem::Type of a type string.
getSuggestedNameForNewItem()
static juce::String tracktion::engine::TrackItem::getSuggestedNameForNewItem (Type) static
Returns a text string for a new clip of the given type.
E.g. "New Audio Clip" for Type::wave
getTrack()
virtual Track * tracktion::engine::TrackItem::getTrack () const pure virtual
Must return the track this item lives on.
Implemented in tracktion::engine::Clip, tracktion::engine::CollectionClip, tracktion::engine::PitchSetting, and tracktion::engine::TimeSigSetting.
Referenced by tracktion::engine::TrackSection::merge().
isGrouped()
virtual bool tracktion::engine::TrackItem::isGrouped () const virtual
Should return true if this clip is part of a group.
Reimplemented in tracktion::engine::Clip.
getGroupParent()
virtual TrackItem * tracktion::engine::TrackItem::getGroupParent () const virtual
If this clip is part of a group, this should return the parent item it belongs to.
Reimplemented in tracktion::engine::Clip.
getPosition()
virtual ClipPosition tracktion::engine::TrackItem::getPosition () const pure virtual
Must return the position of this item.
Implemented in tracktion::engine::Clip, tracktion::engine::CollectionClip, tracktion::engine::StepClip, tracktion::engine::PitchSetting, and tracktion::engine::TimeSigSetting.
Referenced by getEditTimeRange().
getEditTimeRange()
TimeRange tracktion::engine::TrackItem::getEditTimeRange () const
Returns the time range of this item.
References getPosition(), and tracktion::engine::ClipPosition::time.
Referenced by tracktion::engine::TrackSection::merge().
getEditBeatRange()
BeatRange tracktion::engine::TrackItem::getEditBeatRange () const
Returns the beat range of this item.
getStartBeat()
BeatPosition tracktion::engine::TrackItem::getStartBeat () const
Returns the start beat in the Edit of this item.
getContentStartBeat()
BeatPosition tracktion::engine::TrackItem::getContentStartBeat () const
Returns the start beat of the content in the Edit of this item.
I.e. the beat index of (start - offset)
getEndBeat()
BeatPosition tracktion::engine::TrackItem::getEndBeat () const
Returns the end beat in the Edit of this item.
getLengthInBeats()
BeatDuration tracktion::engine::TrackItem::getLengthInBeats () const
Returns the duration in beats the of this item.
getTimeOfRelativeBeat()
TimePosition tracktion::engine::TrackItem::getTimeOfRelativeBeat (BeatDuration) const
Returns an Edit time point for a given number of beats from the start of this item.
getBeatOfRelativeTime()
BeatPosition tracktion::engine::TrackItem::getBeatOfRelativeTime (TimeDuration) const
Returns an Edit beat point for a given number of seconds from the start of this item.
getOffsetInBeats()
BeatDuration tracktion::engine::TrackItem::getOffsetInBeats () const
Returns an the offset of this item in beats.
getTrackID()
EditItemID tracktion::engine::TrackItem::getTrackID () const
Returns the ID of the Track this item lives on.
sortByTime()
template<typename ArrayType > static void tracktion::engine::TrackItem::sortByTime (ArrayType & items) static
Helper function to sort an array of TrackItem[s] by their start time.
stableSortByTime()
template<typename ArrayType > static void tracktion::engine::TrackItem::stableSortByTime (ArrayType & items) static
Helper function to sort an array of TrackItem[s] by their start time without changing the order of items at the same time.
Member Data Documentation
type
const Type tracktion::engine::TrackItem::type
The type of this item.
The documentation for this class was generated from the following file:
tracktion_TrackItem.h