TracktionEngine: tracktion::engine::AirWindowsAutomatableParameter Class Reference
tracktion::engine::AirWindowsAutomatableParameter Class Reference
tracktion_engine » plugins
#include <tracktion_AirWindowsBase.h>
Public Member Functions
AirWindowsAutomatableParameter (AirWindowsPlugin &p, int idx)
~AirWindowsAutomatableParameter () override
void resetToDefault ()
void autodetectRange ()
void refresh ()
void setConversionRange (juce::NormalisableRange< float > range)
void parameterChanged (float newValue, bool byAutomation) override
juce::String getCurrentValueAsString () override
void markAsChanged () const noexcept
Public Member Functions inherited from tracktion::engine::AutomatableParameter
AutomatableParameter (const juce::String &paramID, const juce::String &name, AutomatableEditItem &, juce::NormalisableRange< float > valueRange)
~AutomatableParameter () override
juce::Range< float > getValueRange () const
Plugin * getPlugin () const
Engine & getEngine () const noexcept
Edit & getEdit () const noexcept
Track * getTrack () const noexcept
AutomationCurve & getCurve () const noexcept
void attachToCurrentValue (juce::CachedValue< float > &)
void attachToCurrentValue (juce::CachedValue< int > &)
void attachToCurrentValue (juce::CachedValue< bool > &)
void updateFromAttachedValue ()
void detachFromCurrentValue ()
virtual juce::String getParameterName () const
virtual juce::String getParameterShortName (int) const
virtual juce::String getLabel ()
virtual juce::String getPluginAndParamName () const
virtual juce::String getFullName () const
Selectable * getOwnerSelectable () const
Returns the thing that you'd select if you wanted to show this param.
EditItemID getOwnerID () const
Returns the thing that you'd select if you wanted to show this param.
float getCurrentValue () const noexcept
float getCurrentNormalisedValue () const noexcept
virtual juce::String valueToString (float value)
virtual float stringToValue (const juce::String &s)
juce::String getCurrentValueAsStringWithLabel ()
void setParameter (float value, juce::NotificationType)
void setNormalisedParameter (float value, juce::NotificationType)
void updateToFollowCurve (TimePosition)
void parameterChangeGestureBegin ()
Call to indicate this parameter is about to be changed.
void parameterChangeGestureEnd ()
Call to indicate this parameter has stopped being to be changed.
bool hasAutomationPoints () const noexcept
ModifierAssignment::Ptr addModifier (ModifierSource &, float value=1.0f, float offset=0.0f, float curve=0.5f)
Creates an assignment for a given source.
void removeModifier (ModifierAssignment &)
Removes an assignment.
void removeModifier (ModifierSource &)
Removes assignments for a ModifierSource.
bool hasActiveModifierAssignments () const
Returns true if any ModifierSources are currently in use by assignments.
juce::ReferenceCountedArray< ModifierAssignment > getAssignments () const
Returns all the current ModifierAssignments.
juce::Array< ModifierSource * > getModifiers () const
Returns all the current ModifierSources currently in use by assignments.
float getCurrentExplicitValue () const
This is the value that has been set explicity, either by calling setParameter or the plugin telling us one if its parameters has changed.
float getCurrentBaseValue () const
This is the current base value of the parameter i.e.
float getCurrentModifierValue () const
This is the ammount of the modifier that has been applied to the base value to give the current parameter value.
bool isAutomationActive () const
Returns true if the parameter is being dynamically changed somehow, either through automation or a ModifierAssignment.
void updateStream ()
Forces the parameter to update its automation stream for reading automation.
void updateFromAutomationSources (TimePosition)
Updates the parameter and modifier values from its current automation sources.
virtual bool isParameterActive () const
virtual bool isDiscrete () const
virtual int getNumberOfStates () const
virtual float getValueForState (int) const
virtual int getStateForValue (float) const
virtual std::optional< float > getDefaultValue () const
virtual bool hasLabels () const
virtual juce::String getLabelForValue (float) const
virtual float snapToState (float val) const
virtual juce::StringArray getAllLabels () const
bool isCurrentlyRecording () const
true if the parameter been moved while in an automation record mode.
void resetRecordingStatus ()
this is called before and after playback or recording.
void midiControllerMoved (float newPosition)
void midiControllerPressed ()
void curveHasChanged ()
juce::String getSelectableDescription () override
Subclasses must return a description of what they are.
void addListener (Listener *l)
void removeListener (Listener *l)
Public Member Functions inherited from tracktion::engine::Selectable
Selectable ()
virtual ~Selectable ()
virtual void selectionStatusChanged (bool isNowSelected)
Can be overridden to tell this object that it has just been selected or deselected.
virtual void changed ()
This should be called to send a change notification to any SelectableListeners that are registered with this object.
virtual void selectableAboutToBeDeleted ()
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void addListener (SelectableListener *)
void removeListener (SelectableListener *)
void addSelectableListener (SelectableListener *)
void removeSelectableListener (SelectableListener *)
void cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
void deselect ()
void propertiesChanged ()
void notifyListenersOfDeletion ()
WeakRef getWeakRef ()
Static Public Member Functions
static juce::String getParamId (AirWindowsPlugin &p, int idx)
static juce::String getParamName (AirWindowsPlugin &p, int idx)
Static Public Member Functions inherited from tracktion::engine::Selectable
static void initialise ()
static bool isSelectableValid (const Selectable *) noexcept
checks whether this object has been deleted.
Public Attributes
AirWindowsPlugin & awPlugin
int index = 0
float defaultValue = 0.0f
juce::NormalisableRange< float > conversionRange
Public Attributes inherited from tracktion::engine::AutomatableParameter
const juce::String paramID
const juce::NormalisableRange< float > valueRange
AutomatableEditItem & automatableEditElement
std::function< juce::String(float)> valueToStringFunction
std::function< float(const juce::String &)> stringToValueFunction
const juce::String paramName
juce::ValueTree parentState
Public Attributes inherited from tracktion::engine::Selectable
WeakRef::Master masterReference
Additional Inherited Members
Public Types inherited from tracktion::engine::AutomatableParameter
using Ptr = juce::ReferenceCountedObjectPtr< AutomatableParameter >
using Array = juce::ReferenceCountedArray< AutomatableParameter >
Public Types inherited from tracktion::engine::Selectable
using WeakRef = juce::WeakReference< Selectable >
Protected Member Functions inherited from tracktion::engine::AutomatableParameter
AutomationSourceList & getAutomationSourceList () const
void setParameterValue (float value, bool isFollowingCurve)
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeChildAdded (juce::ValueTree &, juce::ValueTree &) override
void valueTreeChildRemoved (juce::ValueTree &, juce::ValueTree &, int) override
void valueTreeChildOrderChanged (juce::ValueTree &, int, int) override
void valueTreeParentChanged (juce::ValueTree &) override
void valueTreeRedirected (juce::ValueTree &) override
Protected Attributes inherited from tracktion::engine::AutomatableParameter
std::unique_ptr< AttachedValue > attachedValue
juce::ListenerList< Listener > listeners
SafeSelectable< Edit > editRef
Plugin * plugin = nullptr
Modifier * modifierOwner = nullptr
MacroParameterList * macroOwner = nullptr
std::unique_ptr< AutomationCurveSource > curveSource
std::atomic< float > currentValue { 0.0f }
std::atomic< float > currentParameterValue { 0.0f }
std::atomic< float > currentBaseValue { 0.0f }
std::atomic< float > currentModifierValue { 0.0f }
std::atomic< bool > isRecording { false }
bool updateParametersRecursionCheck = false
AsyncCaller parameterChangedCaller { [this] { listeners.call (&Listener::currentValueChanged, *this); } }
int gestureCount = 0
juce::ValueTree modifiersState
std::unique_ptr< AutomationSourceList > automationSourceList
Constructor & Destructor Documentation
AirWindowsAutomatableParameter()
tracktion::engine::AirWindowsAutomatableParameter::AirWindowsAutomatableParameter (AirWindowsPlugin & p, int idx)
~AirWindowsAutomatableParameter()
tracktion::engine::AirWindowsAutomatableParameter::~AirWindowsAutomatableParameter () override
References tracktion::engine::Selectable::notifyListenersOfDeletion().
Member Function Documentation
resetToDefault()
void tracktion::engine::AirWindowsAutomatableParameter::resetToDefault ()
References defaultValue, and tracktion::engine::AutomatableParameter::setParameter().
autodetectRange()
void tracktion::engine::AirWindowsAutomatableParameter::autodetectRange ()
References awPlugin, getCurrentValueAsString(), tracktion::engine::AirWindowsPlugin::impl, index, and setConversionRange().
refresh()
void tracktion::engine::AirWindowsAutomatableParameter::refresh ()
References awPlugin, tracktion::engine::AutomatableParameter::currentParameterValue, tracktion::engine::AutomatableParameter::currentValue, tracktion::engine::AutomatableParameter::curveHasChanged(), tracktion::engine::AirWindowsPlugin::impl, index, and tracktion::engine::AutomatableParameter::listeners.
setConversionRange()
void tracktion::engine::AirWindowsAutomatableParameter::setConversionRange (juce::NormalisableRange< float > range)
References conversionRange, and tracktion::engine::AutomatableParameter::stringToValueFunction.
Referenced by autodetectRange().
parameterChanged()
void tracktion::engine::AirWindowsAutomatableParameter::parameterChanged (float newValue, bool byAutomation) override virtual
Reimplemented from tracktion::engine::AutomatableParameter.
References awPlugin, tracktion::engine::AirWindowsPlugin::impl, index, and markAsChanged().
getCurrentValueAsString()
juce::String tracktion::engine::AirWindowsAutomatableParameter::getCurrentValueAsString () override virtual
Reimplemented from tracktion::engine::AutomatableParameter.
References awPlugin, tracktion::engine::AirWindowsPlugin::impl, index, and kVstMaxParamStrLen.
Referenced by autodetectRange().
markAsChanged()
void tracktion::engine::AirWindowsAutomatableParameter::markAsChanged () const noexcept
References awPlugin, tracktion::engine::AutomatableParameter::getEdit(), and tracktion::engine::Edit::pluginChanged().
Referenced by parameterChanged().
getParamId()
static juce::String tracktion::engine::AirWindowsAutomatableParameter::getParamId (AirWindowsPlugin & p, int idx) static
References getParamName().
getParamName()
static juce::String tracktion::engine::AirWindowsAutomatableParameter::getParamName (AirWindowsPlugin & p, int idx) static
References kVstMaxParamStrLen, and tracktion::engine::AutomatableParameter::paramName.
Referenced by getParamId().
Member Data Documentation
awPlugin
AirWindowsPlugin& tracktion::engine::AirWindowsAutomatableParameter::awPlugin
Referenced by autodetectRange(), getCurrentValueAsString(), markAsChanged(), parameterChanged(), and refresh().
index
int tracktion::engine::AirWindowsAutomatableParameter::index = 0
Referenced by autodetectRange(), getCurrentValueAsString(), parameterChanged(), and refresh().
defaultValue
float tracktion::engine::AirWindowsAutomatableParameter::defaultValue = 0.0f
Referenced by resetToDefault().
conversionRange
juce::NormalisableRange<float> tracktion::engine::AirWindowsAutomatableParameter::conversionRange
Referenced by setConversionRange().
The documentation for this class was generated from the following file:
tracktion_AirWindowsBase.h