TracktionEngine: tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType > Class Template Reference
tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType > Class Template Reference abstract
Public Types
using ScopedLockType = typename CriticalSectionType::ScopedLockType
Public Member Functions
ValueTreeObjectList (const juce::ValueTree &parentTree)
~ValueTreeObjectList () override
int size () const
bool isEmpty () const noexcept
ObjectType * operator[] (int idx) const
ObjectType * at (int idx)
ObjectType ** begin ()
ObjectType *const * begin () const
ObjectType ** end ()
ObjectType *const * end () const
void rebuildObjects ()
void freeObjects ()
virtual bool isSuitableType (const juce::ValueTree &) const =0
virtual ObjectType * createNewObject (const juce::ValueTree &)=0
virtual void deleteObject (ObjectType *)=0
virtual void newObjectAdded (ObjectType *)=0
virtual void objectRemoved (ObjectType *)=0
virtual void objectOrderChanged ()=0
void valueTreeChildAdded (juce::ValueTree &, juce::ValueTree &tree) override
void valueTreeChildRemoved (juce::ValueTree &exParent, juce::ValueTree &tree, int) override
void valueTreeChildOrderChanged (juce::ValueTree &tree, int, int) override
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeParentChanged (juce::ValueTree &) override
void valueTreeRedirected (juce::ValueTree &) override
int compareElements (ObjectType *first, ObjectType *second) const
Public Attributes
juce::Array< ObjectType * > objects
CriticalSectionType arrayLock
Protected Member Functions
void deleteAllObjects ()
bool isChildTree (juce::ValueTree &v) const
int indexOf (const juce::ValueTree &v) const noexcept
void sortArray ()
Protected Attributes
juce::ValueTree parent
Member Typedef Documentation
ScopedLockType
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> using tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::ScopedLockType = typename CriticalSectionType::ScopedLockType
Constructor & Destructor Documentation
ValueTreeObjectList()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::ValueTreeObjectList (const juce::ValueTree & parentTree)
References tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::parent.
~ValueTreeObjectList()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::~ValueTreeObjectList () override
References tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objects.
Member Function Documentation
size()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> int tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::size () const
References tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objects.
Referenced by tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::isEmpty().
isEmpty()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> bool tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::isEmpty () const noexcept
References tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::size().
operator[]()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> ObjectType* tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::operator[] (int idx) const
References tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objects.
at()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> ObjectType* tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::at (int idx)
References tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objects.
begin() [1/2]
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> ObjectType** tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::begin ()
References tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objects.
begin() [2/2]
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> ObjectType* const* tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::begin () const
References tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objects.
end() [1/2]
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> ObjectType** tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::end ()
References tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objects.
end() [2/2]
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> ObjectType* const* tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::end () const
References tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objects.
rebuildObjects()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> void tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::rebuildObjects ()
References tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::createNewObject(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::isSuitableType(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objects, and tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::parent.
freeObjects()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> void tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::freeObjects ()
References tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::deleteAllObjects(), and tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::parent.
isSuitableType()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> virtual bool tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::isSuitableType (const juce::ValueTree &) const pure virtual
Implemented in tracktion::engine::InputDeviceInstance::InputDeviceDestinationList, tracktion::engine::ClipEffects, tracktion::engine::TrackList, tracktion::engine::TrackCompManager::TrackComp, and tracktion::engine::ModifierList.
Referenced by tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::isChildTree(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::rebuildObjects(), and tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildRemoved().
createNewObject()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> virtual ObjectType* tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::createNewObject (const juce::ValueTree &) pure virtual
Implemented in tracktion::engine::InputDeviceInstance::InputDeviceDestinationList, tracktion::engine::ClipEffects, tracktion::engine::TrackList, tracktion::engine::TrackCompManager::TrackComp, and tracktion::engine::ModifierList.
Referenced by tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::rebuildObjects(), and tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildAdded().
deleteObject()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> virtual void tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::deleteObject (ObjectType *) pure virtual
Implemented in tracktion::engine::TrackList, tracktion::engine::ModifierList, and tracktion::engine::ClipEffects.
Referenced by tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::deleteAllObjects(), and tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildRemoved().
newObjectAdded()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> virtual void tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::newObjectAdded (ObjectType *) pure virtual
Implemented in tracktion::engine::TrackList, tracktion::engine::SortedValueTreeObjectList< ObjectType >, tracktion::engine::ModifierList, and tracktion::engine::ClipEffects.
Referenced by tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildAdded().
objectRemoved()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> virtual void tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objectRemoved (ObjectType *) pure virtual
Implemented in tracktion::engine::TrackList, tracktion::engine::ModifierList, and tracktion::engine::ClipEffects.
Referenced by tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildRemoved().
objectOrderChanged()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> virtual void tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objectOrderChanged () pure virtual
Implemented in tracktion::engine::SortedValueTreeObjectList< ObjectType >, tracktion::engine::InputDeviceInstance::InputDeviceDestinationList, tracktion::engine::TrackList, tracktion::engine::TrackCompManager::TrackComp, tracktion::engine::ClipEffects, and tracktion::engine::ModifierList.
Referenced by tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildOrderChanged().
valueTreeChildAdded()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> void tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildAdded (juce::ValueTree & , juce::ValueTree & tree) override
References tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::arrayLock, tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::createNewObject(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::isChildTree(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::newObjectAdded(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objects, and tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::parent.
valueTreeChildRemoved()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> void tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildRemoved (juce::ValueTree & exParent, juce::ValueTree & tree, int) override
References tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::arrayLock, tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::deleteObject(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::indexOf(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::isSuitableType(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objectRemoved(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objects, and tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::parent.
valueTreeChildOrderChanged()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> void tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildOrderChanged (juce::ValueTree & tree, int , int) override
References tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::arrayLock, tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objectOrderChanged(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::parent, and tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::sortArray().
valueTreePropertyChanged()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> void tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreePropertyChanged (juce::ValueTree & , const juce::Identifier &) override
valueTreeParentChanged()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> void tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeParentChanged (juce::ValueTree &) override
valueTreeRedirected()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> void tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeRedirected (juce::ValueTree &) override
deleteAllObjects()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> void tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::deleteAllObjects () protected
References tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::arrayLock, tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::deleteObject(), and tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objects.
Referenced by tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::freeObjects().
isChildTree()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> bool tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::isChildTree (juce::ValueTree & v) const protected
References tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::isSuitableType(), and tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::parent.
Referenced by tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildAdded(), and tracktion::engine::SortedValueTreeObjectList< ObjectType >::valueTreePropertyChanged().
indexOf()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> int tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::indexOf (const juce::ValueTree & v) const protected noexcept
References tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objects.
Referenced by tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildRemoved().
sortArray()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> void tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::sortArray () protected
References tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objects.
Referenced by tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildOrderChanged().
compareElements()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> int tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::compareElements (ObjectType * first, ObjectType * second) const
References tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::parent.
Member Data Documentation
objects
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> juce::Array<ObjectType*> tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objects
Referenced by tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::at(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::begin(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::deleteAllObjects(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::end(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::indexOf(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::operator[](), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::rebuildObjects(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::size(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::sortArray(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildAdded(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildRemoved(), and tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::~ValueTreeObjectList().
arrayLock
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> CriticalSectionType tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::arrayLock
Referenced by tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::deleteAllObjects(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildAdded(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildOrderChanged(), and tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildRemoved().
parent
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> juce::ValueTree tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::parent protected
Referenced by tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::compareElements(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::freeObjects(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::isChildTree(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::rebuildObjects(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildAdded(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildOrderChanged(), tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildRemoved(), and tracktion::engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::ValueTreeObjectList().
The documentation for this class was generated from the following file:
tracktion_ValueTreeUtilities.h