TracktionEngine: tracktion_engine::AudioFileCache::Reader Class Reference
tracktion_engine::AudioFileCache::Reader Class Reference
tracktion_engine » audio_files
Inherits ReferenceCountedObject.
Public Types
using Ptr = juce::ReferenceCountedObjectPtr< Reader >
Public Member Functions
~Reader ()
void setReadPosition (juce::int64 pos) noexcept
juce::int64 getReadPosition () const noexcept
bool readSamples (int numSamples, juce::AudioBuffer< float > &destBuffer, const juce::AudioChannelSet &destBufferChannels, int startOffsetInDestBuffer, const juce::AudioChannelSet &sourceBufferChannels, int timeoutMs)
bool readSamples (int **destSamples, int numDestChannels, int startOffsetInDestBuffer, int numSamples, int timeoutMs)
bool getRange (int numSamples, float &lmax, float &lmin, float &rmax, float &rmin, int timeoutMs)
void setLoopRange (juce::Range< juce::int64 > newRange)
int getNumChannels () const noexcept
double getSampleRate () const noexcept
Member Typedef Documentation
Ptr
using tracktion_engine::AudioFileCache::Reader::Ptr = juce::ReferenceCountedObjectPtr<Reader>
Constructor & Destructor Documentation
~Reader()
tracktion_engine::AudioFileCache::Reader::~Reader ()
Member Function Documentation
setReadPosition()
void tracktion_engine::AudioFileCache::Reader::setReadPosition (juce::int64 pos) noexcept
getReadPosition()
juce::int64 tracktion_engine::AudioFileCache::Reader::getReadPosition () const noexcept
References getNumChannels(), getRange(), getSampleRate(), readSamples(), and setLoopRange().
readSamples() [1/2]
bool tracktion_engine::AudioFileCache::Reader::readSamples (int numSamples, juce::AudioBuffer< float > & destBuffer, const juce::AudioChannelSet & destBufferChannels, int startOffsetInDestBuffer, const juce::AudioChannelSet & sourceBufferChannels, int timeoutMs)
Referenced by getReadPosition().
readSamples() [2/2]
bool tracktion_engine::AudioFileCache::Reader::readSamples (int ** destSamples, int numDestChannels, int startOffsetInDestBuffer, int numSamples, int timeoutMs)
getRange()
bool tracktion_engine::AudioFileCache::Reader::getRange (int numSamples, float & lmax, float & lmin, float & rmax, float & rmin, int timeoutMs)
Referenced by getReadPosition().
setLoopRange()
void tracktion_engine::AudioFileCache::Reader::setLoopRange (juce::Range< juce::int64 > newRange)
Referenced by getReadPosition().
getNumChannels()
int tracktion_engine::AudioFileCache::Reader::getNumChannels () const noexcept
Referenced by getReadPosition().
getSampleRate()
double tracktion_engine::AudioFileCache::Reader::getSampleRate () const noexcept
Referenced by getReadPosition().
The documentation for this class was generated from the following file:
tracktion_AudioFileCache.h