TracktionEngine: tracktion_engine::DeviceManager Class Reference
tracktion_engine::DeviceManager Class Reference
Inherits ChangeBroadcaster, ChangeListener, and AudioIODeviceCallback.
Classes
struct ContextDeviceListRebuilder
struct CPUUsageListener
Public Member Functions
~DeviceManager () override
void initialise (int defaultNumInputChannelsToOpen=512, int defaultNumOutputChannelsToOpen=512)
void closeDevices ()
void saveSettings ()
HostedAudioDeviceInterface & getHostedAudioDeviceInterface ()
If you are using the engine in a plugin or an application that accesses the audio device directly, use this interface to pass audio and midi to the DeviceManager.
bool isHostedAudioDeviceInterfaceInUse () const
Returns true if the hosted interface is available and in use.
void removeHostedAudioDeviceInterface ()
Removes the hosted audio device.
float getCpuUsage () const noexcept
void setCpuLimitBeforeMuting (double newLimit)
void updateNumCPUs ()
void addCPUUsageListener (CPUUsageListener *listener)
void removeCPUUsageListener (CPUUsageListener *listener)
double getSampleRate () const
int getBitDepth () const
int getBlockSize () const
double getBlockSizeMs () const
int getNumWaveOutDevices () const
WaveOutputDevice * getWaveOutDevice (int index) const
WaveOutputDevice * getDefaultWaveOutDevice () const
void setDefaultWaveOutDevice (int index)
int getNumWaveInDevices () const
WaveInputDevice * getWaveInDevice (int index) const
WaveInputDevice * getDefaultWaveInDevice () const
void setDefaultWaveInDevice (int index)
void setDeviceOutChannelStereo (int channelNum, bool isStereoPair)
bool isDeviceOutChannelStereo (int chan) const
bool isDeviceOutEnabled (int chanNum)
void setDeviceInChannelStereo (int channelNum, bool isStereoPair)
bool isDeviceInChannelStereo (int chan) const
bool isDeviceInEnabled (int chanNum)
void setWaveOutChannelsEnabled (const std::vector< ChannelIndex > &, bool)
void setWaveInChannelsEnabled (const std::vector< ChannelIndex > &, bool)
bool rebuildWaveDeviceListIfNeeded ()
void rescanMidiDeviceList (bool forceRescan)
int getNumMidiOutDevices () const
MidiOutputDevice * getMidiOutDevice (int index) const
MidiOutputDevice * getDefaultMidiOutDevice () const
void setDefaultMidiOutDevice (int index)
int getNumMidiInDevices () const
MidiInputDevice * getMidiInDevice (int index) const
MidiInputDevice * getDefaultMidiInDevice () const
void setDefaultMidiInDevice (int index)
void broadcastStreamTimeToMidiDevices (double streamTime)
bool shouldSendMidiTimecode () const noexcept
double getCurrentStreamTime () const noexcept
Returns the current block's stream time.
bool isMSWavetableSynthPresent () const
void resetToDefaults (bool deviceSettings, bool resetInputDevices, bool resetOutputDevices, bool latencySettings, bool mixSettings)
int getNumInputDevices () const
InputDevice * getInputDevice (int index) const
int getNumOutputDevices () const
OutputDevice * getOutputDeviceAt (int index) const
OutputDevice * findOutputDeviceForID (const juce::String &id) const
OutputDevice * findOutputDeviceWithName (const juce::String &name) const
void checkDefaultDevicesAreValid ()
juce::Result createVirtualMidiDevice (const juce::String &name)
void deleteVirtualMidiDevice (VirtualMidiInputDevice *)
double getRecordAdjustmentMs ()
int getRecordAdjustmentSamples ()
double getOutputLatencySeconds () const
void addContext (EditPlaybackContext *)
void removeContext (EditPlaybackContext *)
void clearAllContextDevices ()
void reloadAllContextDevices ()
void setGlobalOutputAudioProcessor (juce::AudioProcessor *)
juce::AudioProcessor * getGlobalOutputAudioProcessor () const
Static Public Member Functions
static juce::String getDefaultAudioOutDeviceName (bool translated)
static juce::String getDefaultMidiOutDeviceName (bool translated)
static juce::String getDefaultAudioInDeviceName (bool translated)
static juce::String getDefaultMidiInDeviceName (bool translated)
Public Attributes
std::unique_ptr< HostedAudioDeviceInterface > hostedAudioDeviceInterface
juce::AudioDeviceManager deviceManager
juce::OwnedArray< MidiInputDevice, juce::CriticalSection > midiInputs
juce::OwnedArray< MidiOutputDevice > midiOutputs
juce::OwnedArray< WaveInputDevice > waveInputs
juce::OwnedArray< WaveOutputDevice > waveOutputs
std::function< void(InputDevice *)> warnOfWastedMidiMessagesFunction
Engine & engine
Constructor & Destructor Documentation
~DeviceManager()
tracktion_engine::DeviceManager::~DeviceManager () override
Member Function Documentation
initialise()
void tracktion_engine::DeviceManager::initialise (int defaultNumInputChannelsToOpen = 512, int defaultNumOutputChannelsToOpen = 512)
closeDevices()
void tracktion_engine::DeviceManager::closeDevices ()
saveSettings()
void tracktion_engine::DeviceManager::saveSettings ()
getHostedAudioDeviceInterface()
HostedAudioDeviceInterface& tracktion_engine::DeviceManager::getHostedAudioDeviceInterface ()
If you are using the engine in a plugin or an application that accesses the audio device directly, use this interface to pass audio and midi to the DeviceManager.
isHostedAudioDeviceInterfaceInUse()
bool tracktion_engine::DeviceManager::isHostedAudioDeviceInterfaceInUse () const
Returns true if the hosted interface is available and in use.
removeHostedAudioDeviceInterface()
void tracktion_engine::DeviceManager::removeHostedAudioDeviceInterface ()
Removes the hosted audio device.
You shouldn't normally need to call this but can be useful for running tests. Afterwards, you'll need to call initialise again.
getCpuUsage()
float tracktion_engine::DeviceManager::getCpuUsage () const noexcept
setCpuLimitBeforeMuting()
void tracktion_engine::DeviceManager::setCpuLimitBeforeMuting (double newLimit)
updateNumCPUs()
void tracktion_engine::DeviceManager::updateNumCPUs ()
addCPUUsageListener()
void tracktion_engine::DeviceManager::addCPUUsageListener (CPUUsageListener * listener)
removeCPUUsageListener()
void tracktion_engine::DeviceManager::removeCPUUsageListener (CPUUsageListener * listener)
getSampleRate()
double tracktion_engine::DeviceManager::getSampleRate () const
getBitDepth()
int tracktion_engine::DeviceManager::getBitDepth () const
getBlockSize()
int tracktion_engine::DeviceManager::getBlockSize () const
getBlockSizeMs()
double tracktion_engine::DeviceManager::getBlockSizeMs () const
getNumWaveOutDevices()
int tracktion_engine::DeviceManager::getNumWaveOutDevices () const
References waveOutputs.
getWaveOutDevice()
WaveOutputDevice* tracktion_engine::DeviceManager::getWaveOutDevice (int index) const
References waveOutputs.
Referenced by getDefaultWaveOutDevice().
getDefaultWaveOutDevice()
WaveOutputDevice* tracktion_engine::DeviceManager::getDefaultWaveOutDevice () const
References getWaveOutDevice().
setDefaultWaveOutDevice()
void tracktion_engine::DeviceManager::setDefaultWaveOutDevice (int index)
getNumWaveInDevices()
int tracktion_engine::DeviceManager::getNumWaveInDevices () const
References waveInputs.
getWaveInDevice()
WaveInputDevice* tracktion_engine::DeviceManager::getWaveInDevice (int index) const
References waveInputs.
Referenced by getDefaultWaveInDevice().
getDefaultWaveInDevice()
WaveInputDevice* tracktion_engine::DeviceManager::getDefaultWaveInDevice () const
References getWaveInDevice().
setDefaultWaveInDevice()
void tracktion_engine::DeviceManager::setDefaultWaveInDevice (int index)
setDeviceOutChannelStereo()
void tracktion_engine::DeviceManager::setDeviceOutChannelStereo (int channelNum, bool isStereoPair)
isDeviceOutChannelStereo()
bool tracktion_engine::DeviceManager::isDeviceOutChannelStereo (int chan) const
isDeviceOutEnabled()
bool tracktion_engine::DeviceManager::isDeviceOutEnabled (int chanNum)
setDeviceInChannelStereo()
void tracktion_engine::DeviceManager::setDeviceInChannelStereo (int channelNum, bool isStereoPair)
isDeviceInChannelStereo()
bool tracktion_engine::DeviceManager::isDeviceInChannelStereo (int chan) const
isDeviceInEnabled()
bool tracktion_engine::DeviceManager::isDeviceInEnabled (int chanNum)
setWaveOutChannelsEnabled()
void tracktion_engine::DeviceManager::setWaveOutChannelsEnabled (const std::vector< ChannelIndex > & , bool)
setWaveInChannelsEnabled()
void tracktion_engine::DeviceManager::setWaveInChannelsEnabled (const std::vector< ChannelIndex > & , bool)
rebuildWaveDeviceListIfNeeded()
bool tracktion_engine::DeviceManager::rebuildWaveDeviceListIfNeeded ()
rescanMidiDeviceList()
void tracktion_engine::DeviceManager::rescanMidiDeviceList (bool forceRescan)
getNumMidiOutDevices()
int tracktion_engine::DeviceManager::getNumMidiOutDevices () const
References midiOutputs.
getMidiOutDevice()
MidiOutputDevice* tracktion_engine::DeviceManager::getMidiOutDevice (int index) const
References midiOutputs.
Referenced by getDefaultMidiOutDevice().
getDefaultMidiOutDevice()
MidiOutputDevice* tracktion_engine::DeviceManager::getDefaultMidiOutDevice () const
References getMidiOutDevice().
setDefaultMidiOutDevice()
void tracktion_engine::DeviceManager::setDefaultMidiOutDevice (int index)
getNumMidiInDevices()
int tracktion_engine::DeviceManager::getNumMidiInDevices () const
getMidiInDevice()
MidiInputDevice* tracktion_engine::DeviceManager::getMidiInDevice (int index) const
Referenced by getDefaultMidiInDevice().
getDefaultMidiInDevice()
MidiInputDevice* tracktion_engine::DeviceManager::getDefaultMidiInDevice () const
References getMidiInDevice().
setDefaultMidiInDevice()
void tracktion_engine::DeviceManager::setDefaultMidiInDevice (int index)
broadcastStreamTimeToMidiDevices()
void tracktion_engine::DeviceManager::broadcastStreamTimeToMidiDevices (double streamTime)
shouldSendMidiTimecode()
bool tracktion_engine::DeviceManager::shouldSendMidiTimecode () const noexcept
getCurrentStreamTime()
double tracktion_engine::DeviceManager::getCurrentStreamTime () const noexcept
Returns the current block's stream time.
This shouldn't really be used and may be removed in future.
isMSWavetableSynthPresent()
bool tracktion_engine::DeviceManager::isMSWavetableSynthPresent () const
resetToDefaults()
void tracktion_engine::DeviceManager::resetToDefaults (bool deviceSettings, bool resetInputDevices, bool resetOutputDevices, bool latencySettings, bool mixSettings)
getNumInputDevices()
int tracktion_engine::DeviceManager::getNumInputDevices () const
getInputDevice()
InputDevice* tracktion_engine::DeviceManager::getInputDevice (int index) const
getNumOutputDevices()
int tracktion_engine::DeviceManager::getNumOutputDevices () const
getOutputDeviceAt()
OutputDevice* tracktion_engine::DeviceManager::getOutputDeviceAt (int index) const
findOutputDeviceForID()
OutputDevice* tracktion_engine::DeviceManager::findOutputDeviceForID (const juce::String & id) const
findOutputDeviceWithName()
OutputDevice* tracktion_engine::DeviceManager::findOutputDeviceWithName (const juce::String & name) const
checkDefaultDevicesAreValid()
void tracktion_engine::DeviceManager::checkDefaultDevicesAreValid ()
getDefaultAudioOutDeviceName()
static juce::String tracktion_engine::DeviceManager::getDefaultAudioOutDeviceName (bool translated) static
getDefaultMidiOutDeviceName()
static juce::String tracktion_engine::DeviceManager::getDefaultMidiOutDeviceName (bool translated) static
getDefaultAudioInDeviceName()
static juce::String tracktion_engine::DeviceManager::getDefaultAudioInDeviceName (bool translated) static
getDefaultMidiInDeviceName()
static juce::String tracktion_engine::DeviceManager::getDefaultMidiInDeviceName (bool translated) static
createVirtualMidiDevice()
juce::Result tracktion_engine::DeviceManager::createVirtualMidiDevice (const juce::String & name)
deleteVirtualMidiDevice()
void tracktion_engine::DeviceManager::deleteVirtualMidiDevice (VirtualMidiInputDevice *)
getRecordAdjustmentMs()
double tracktion_engine::DeviceManager::getRecordAdjustmentMs ()
getRecordAdjustmentSamples()
int tracktion_engine::DeviceManager::getRecordAdjustmentSamples ()
getOutputLatencySeconds()
double tracktion_engine::DeviceManager::getOutputLatencySeconds () const
addContext()
void tracktion_engine::DeviceManager::addContext (EditPlaybackContext *)
removeContext()
void tracktion_engine::DeviceManager::removeContext (EditPlaybackContext *)
clearAllContextDevices()
void tracktion_engine::DeviceManager::clearAllContextDevices ()
reloadAllContextDevices()
void tracktion_engine::DeviceManager::reloadAllContextDevices ()
setGlobalOutputAudioProcessor()
void tracktion_engine::DeviceManager::setGlobalOutputAudioProcessor (juce::AudioProcessor *)
getGlobalOutputAudioProcessor()
juce::AudioProcessor* tracktion_engine::DeviceManager::getGlobalOutputAudioProcessor () const
Member Data Documentation
hostedAudioDeviceInterface
std::unique_ptr<HostedAudioDeviceInterface> tracktion_engine::DeviceManager::hostedAudioDeviceInterface
deviceManager
juce::AudioDeviceManager tracktion_engine::DeviceManager::deviceManager
midiInputs
juce::OwnedArray<MidiInputDevice, juce::CriticalSection> tracktion_engine::DeviceManager::midiInputs
midiOutputs
juce::OwnedArray<MidiOutputDevice> tracktion_engine::DeviceManager::midiOutputs
Referenced by getMidiOutDevice(), and getNumMidiOutDevices().
waveInputs
juce::OwnedArray<WaveInputDevice> tracktion_engine::DeviceManager::waveInputs
Referenced by getNumWaveInDevices(), and getWaveInDevice().
waveOutputs
juce::OwnedArray<WaveOutputDevice> tracktion_engine::DeviceManager::waveOutputs
Referenced by getNumWaveOutDevices(), and getWaveOutDevice().
warnOfWastedMidiMessagesFunction
std::function<void(InputDevice*)> tracktion_engine::DeviceManager::warnOfWastedMidiMessagesFunction
engine
Engine& tracktion_engine::DeviceManager::engine
The documentation for this class was generated from the following file:
tracktion_DeviceManager.h