TracktionEngine: tracktion_engine::AudioSegmentList Class Reference
tracktion_engine::AudioSegmentList Class Reference
Holds a list of audio regions for playback of things like warp time.
Classes
struct Segment
Public Member Functions
const juce::Array< Segment > & getSegments () const
double getStart () const
double getEnd () const
double getLength () const
double getCrossfadeLength () const
bool operator== (const AudioSegmentList &) const noexcept
bool operator!= (const AudioSegmentList &) const noexcept
Static Public Member Functions
static std::unique_ptr< AudioSegmentList > create (AudioClipBase &)
static std::unique_ptr< AudioSegmentList > create (AudioClipBase &, bool relativeTime, bool crossFade)
static std::unique_ptr< AudioSegmentList > create (AudioClipBase &, const WarpTimeManager &, const AudioFile &)
static std::unique_ptr< AudioSegmentList > create (AudioClipBase &, const WarpTimeManager &, const AudioFileInfo &, const LoopInfo &)
Detailed Description
Holds a list of audio regions for playback of things like warp time.
Member Function Documentation
create() [1/4]
static std::unique_ptr<AudioSegmentList> tracktion_engine::AudioSegmentList::create (AudioClipBase &) static
create() [2/4]
static std::unique_ptr<AudioSegmentList> tracktion_engine::AudioSegmentList::create (AudioClipBase & , bool relativeTime, bool crossFade) static
create() [3/4]
static std::unique_ptr<AudioSegmentList> tracktion_engine::AudioSegmentList::create (AudioClipBase & , const WarpTimeManager & , const AudioFile &) static
create() [4/4]
static std::unique_ptr<AudioSegmentList> tracktion_engine::AudioSegmentList::create (AudioClipBase & , const WarpTimeManager & , const AudioFileInfo & , const LoopInfo &) static
getSegments()
const juce::Array<Segment>& tracktion_engine::AudioSegmentList::getSegments () const
getStart()
double tracktion_engine::AudioSegmentList::getStart () const
Referenced by getLength().
getEnd()
double tracktion_engine::AudioSegmentList::getEnd () const
Referenced by getLength().
getLength()
double tracktion_engine::AudioSegmentList::getLength () const
References getEnd(), and getStart().
getCrossfadeLength()
double tracktion_engine::AudioSegmentList::getCrossfadeLength () const
operator==()
bool tracktion_engine::AudioSegmentList::operator== (const AudioSegmentList &) const noexcept
operator!=()
bool tracktion_engine::AudioSegmentList::operator!= (const AudioSegmentList &) const noexcept
The documentation for this class was generated from the following file:
tracktion_AudioSegmentList.h