TracktionEngine: tracktion_engine::AudioFile Class Reference
tracktion_engine::AudioFile Class Reference
Public Member Functions
AudioFile ()=delete
AudioFile (Engine &e) noexcept
AudioFile (Engine &, const juce::File &) noexcept
AudioFile (const AudioFile &) noexcept
AudioFile & operator= (const AudioFile &) noexcept
~AudioFile ()
const juce::File & getFile () const noexcept
juce::int64 getHash () const noexcept
juce::String getHashString () const
bool operator== (const AudioFile &other) const noexcept
bool operator!= (const AudioFile &other) const noexcept
bool deleteFile () const
bool isNull () const noexcept
bool isValid () const
AudioFileInfo getInfo () const
juce::int64 getLengthInSamples () const
double getLength () const
int getNumChannels () const
double getSampleRate () const
int getBitsPerSample () const
bool isFloatingPoint () const
juce::StringPairArray getMetadata () const
juce::AudioFormat * getFormat () const
bool isWavFile () const
bool isAiffFile () const
bool isOggFile () const
bool isMp3File () const
bool isFlacFile () const
bool isRexFile () const
Static Public Member Functions
static bool deleteFiles (Engine &, const juce::Array< juce::File > &files)
Public Attributes
Engine * engine = nullptr
Constructor & Destructor Documentation
AudioFile() [1/4]
tracktion_engine::AudioFile::AudioFile () delete
AudioFile() [2/4]
tracktion_engine::AudioFile::AudioFile (Engine & e) noexcept
AudioFile() [3/4]
tracktion_engine::AudioFile::AudioFile (Engine & , const juce::File &) explicit noexcept
AudioFile() [4/4]
tracktion_engine::AudioFile::AudioFile (const AudioFile &) noexcept
~AudioFile()
tracktion_engine::AudioFile::~AudioFile ()
Member Function Documentation
operator=()
AudioFile& tracktion_engine::AudioFile::operator= (const AudioFile &) noexcept
getFile()
const juce::File& tracktion_engine::AudioFile::getFile () const noexcept
Referenced by tracktion_engine::WarpTimeRenderJob::renderNextBlock(), and tracktion_engine::ReverseRenderJob::renderNextBlock().
getHash()
juce::int64 tracktion_engine::AudioFile::getHash () const noexcept
getHashString()
juce::String tracktion_engine::AudioFile::getHashString () const
operator==()
bool tracktion_engine::AudioFile::operator== (const AudioFile & other) const noexcept
operator!=()
bool tracktion_engine::AudioFile::operator!= (const AudioFile & other) const noexcept
deleteFile()
bool tracktion_engine::AudioFile::deleteFile () const
deleteFiles()
static bool tracktion_engine::AudioFile::deleteFiles (Engine & , const juce::Array< juce::File > & files) static
isNull()
bool tracktion_engine::AudioFile::isNull () const noexcept
Referenced by tracktion_engine::SubSampleWaveAudioNode::isReadyToRender().
isValid()
bool tracktion_engine::AudioFile::isValid () const
getInfo()
AudioFileInfo tracktion_engine::AudioFile::getInfo () const
Referenced by tracktion_engine::WarpTimeRenderJob::renderNextBlock().
getLengthInSamples()
juce::int64 tracktion_engine::AudioFile::getLengthInSamples () const
getLength()
double tracktion_engine::AudioFile::getLength () const
getNumChannels()
int tracktion_engine::AudioFile::getNumChannels () const
Referenced by tracktion_engine::SubSampleWaveAudioNode::getAudioNodeProperties().
getSampleRate()
double tracktion_engine::AudioFile::getSampleRate () const
getBitsPerSample()
int tracktion_engine::AudioFile::getBitsPerSample () const
isFloatingPoint()
bool tracktion_engine::AudioFile::isFloatingPoint () const
getMetadata()
juce::StringPairArray tracktion_engine::AudioFile::getMetadata () const
getFormat()
juce::AudioFormat* tracktion_engine::AudioFile::getFormat () const
isWavFile()
bool tracktion_engine::AudioFile::isWavFile () const
isAiffFile()
bool tracktion_engine::AudioFile::isAiffFile () const
isOggFile()
bool tracktion_engine::AudioFile::isOggFile () const
isMp3File()
bool tracktion_engine::AudioFile::isMp3File () const
isFlacFile()
bool tracktion_engine::AudioFile::isFlacFile () const
isRexFile()
bool tracktion_engine::AudioFile::isRexFile () const
Member Data Documentation
engine
Engine* tracktion_engine::AudioFile::engine = nullptr
The documentation for this class was generated from the following file:
tracktion_AudioFile.h