TracktionEngine: tracktion_engine::ToneGeneratorPlugin Class Reference
tracktion_engine::ToneGeneratorPlugin Class Reference
Public Types
enum OscType {
OscType::sin, OscType::triangle, OscType::sawUp, OscType::sawDown,
OscType::square, OscType::noise
}
Public Types inherited from tracktion_engine::Plugin
enum Type { Type::allPlugins, Type::folderTrackPlugins, Type::effectPlugins }
using Ptr = juce::ReferenceCountedObjectPtr< Plugin >
using Array = juce::ReferenceCountedArray< Plugin >
Public Types inherited from tracktion_engine::Selectable
using WeakRef = juce::WeakReference< Selectable >
Public Member Functions
ToneGeneratorPlugin (PluginCreationInfo)
~ToneGeneratorPlugin () override
juce::String getName () override
The name of the type, e.g.
juce::String getPluginType () override
juce::String getShortName (int) override
bool producesAudioWhenNoAudioInput () override
bool isSynth () override
int getNumOutputChannelsGivenInputs (int numInputChannels) override
This must return the number of output channels that the plugin will produce, given a number of input channels.
void initialise (const PluginInitialisationInfo &) override
Gives the plugin a chance to set itself up before being played.
void deinitialise () override
Called after play stops to release resources.
void applyToBuffer (const PluginRenderContext &) override
Process the next block of data.
juce::String getSelectableDescription () override
Subclasses must return a description of what they are.
bool needsConstantBufferSize () override
void restorePluginStateFromValueTree (const juce::ValueTree &) override
Public Member Functions inherited from tracktion_engine::Plugin
Plugin (PluginCreationInfo)
~Plugin () override
void selectableAboutToBeDeleted () override
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void playStartedOrStopped ()
called by the system to let the plugin manage its automation stuff
virtual void initialiseFully ()
Gives the plugin a chance to do extra initialisation when it's been added to an edit.
virtual void flushPluginStateToValueTree () override
virtual juce::String getVendor ()
virtual juce::String getIdentifierString ()
A unique string to idenitify plugin independant of install location.
virtual juce::String getTooltip ()
default returns the name, others can return special stuff if needed
virtual void setEnabled (bool)
Enable/disable the plugin.
bool isEnabled () const noexcept
void setFrozen (bool shouldBeFrozen)
This is a bit different to being enabled as when frozen a plugin can't be interacted with.
bool isFrozen () const noexcept
void setProcessingEnabled (bool p)
Enable/Disable processing.
bool isProcessingEnabled () const noexcept
virtual void initialiseWithoutStopping (const PluginInitialisationInfo &)
Tells the plugin that the audio graph has changed but the plugin isn't being re-initialised - i.e.
virtual void reset ()
Should reset synth voices, tails, clear delay buffers, etc.
virtual void prepareForNextBlock (double)
Called between successive rendering blocks.
void applyToBufferWithAutomation (const PluginRenderContext &)
double getCpuUsage () const noexcept
virtual bool noTail ()
virtual void getChannelNames (juce::StringArray *ins, juce::StringArray *outs)
virtual bool takesAudioInput ()
virtual bool takesMidiInput ()
virtual double getLatencySeconds ()
virtual double getTailLength () const
virtual bool canSidechain ()
juce::StringArray getInputChannelNames ()
juce::StringArray getSidechainSourceNames (bool allowNone)
void setSidechainSourceByName (const juce::String &name)
juce::String getSidechainSourceName ()
void guessSidechainRouting ()
int getNumWires () const
Wire * getWire (int index) const
void makeConnection (int srcChannel, int dstChannel, juce::UndoManager *)
void breakConnection (int srcChannel, int dstChannel)
virtual bool hasNameForMidiNoteNumber (int note, int midiChannel, juce::String &name)
If it's a synth that names its notes, this can return the name it uses for this note 0-127.
virtual bool hasNameForMidiProgram (int programNum, int bank, juce::String &name)
Returns the name for a midi program, if there is one.
virtual bool hasNameForMidiBank (int bank, juce::String &name)
virtual bool canBeAddedToClip ()
virtual bool canBeAddedToRack ()
virtual bool canBeAddedToFolderTrack ()
virtual bool canBeAddedToMaster ()
virtual bool canBeDisabled ()
virtual bool canBeMoved ()
virtual bool isMissing ()
for things like VSTs where the DLL is missing.
virtual bool isDisabled ()
Plugins can be disabled to avoid them crashing Edits.
bool isInRack () const
juce::ReferenceCountedObjectPtr< RackType > getOwnerRackType () const
bool isClipEffectPlugin () const
virtual juce::AudioProcessor * getWrappedAudioProcessor () const
AutomatableParameter::Ptr getQuickControlParameter () const
void setQuickControlParameter (AutomatableParameter *)
virtual void deleteFromParent ()
Attempts to delete this plugin, whether it's a master plugin, track plugin, etc.
void removeFromParent ()
Detaches the plugin from any parent it might be in.
Track * getOwnerTrack () const
Returns the track if it's a track or clip plugin.
Clip * getOwnerClip () const
Returns the clip if that's what it's in.
PluginList * getOwnerList () const
Ptr findPluginThatFeedsIntoThis () const
Ptr findPluginThatThisFeedsInto () const
void changed () override
method from Selectable, that's been overridden here to also tell the edit that it's changed.
juce::Array< ReferencedItem > getReferencedItems () override
void reassignReferencedItem (const ReferencedItem &, ProjectItemID newID, double newStartTime) override
virtual void sourceMediaChanged ()
Called when ProjectItem sources are re-assigned so you can reload from the new source.
bool setPluginToMirror (const Plugin::Ptr &)
virtual void updateFromMirroredPluginIfNeeded (Plugin &)
Plugin::Ptr getMirroredPlugin () const
bool baseClassNeedsInitialising () const noexcept
void baseClassInitialise (const PluginInitialisationInfo &)
void baseClassDeinitialise ()
void setSidechainSourceID (EditItemID newID)
EditItemID getSidechainSourceID () const
void showWindowExplicitly ()
void hideWindowForShutdown ()
juce::UndoManager * getUndoManager () const noexcept
Public Member Functions inherited from tracktion_engine::Selectable
Selectable ()
virtual ~Selectable ()
virtual void selectionStatusChanged (bool isNowSelected)
Can be overridden to tell this object that it has just been selected or deselected.
void addSelectableListener (SelectableListener *)
void removeSelectableListener (SelectableListener *)
void cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
void deselect ()
void propertiesChanged ()
void notifyListenersOfDeletion ()
WeakRef getWeakRef ()
Public Member Functions inherited from tracktion_engine::Exportable
virtual ~Exportable ()=default
Public Member Functions inherited from tracktion_engine::AutomatableEditItem
AutomatableEditItem (Edit &, const juce::ValueTree &)
virtual ~AutomatableEditItem ()
juce::Array< AutomatableParameter * > getAutomatableParameters () const
int getNumAutomatableParameters () const
AutomatableParameter::Ptr getAutomatableParameter (int index) const
AutomatableParameter::Ptr getAutomatableParameterByID (const juce::String &paramID) const
void deleteParameter (AutomatableParameter *)
void deleteAutomatableParameters ()
int indexOfAutomatableParameter (const AutomatableParameter::Ptr &) const
AutomatableParameterTree & getParameterTree () const
juce::ReferenceCountedArray< AutomatableParameter > getFlattenedParameterTree () const
void addParameterListChangeListener (ParameterListChangeListener *)
void removeParameterListChangeListener (ParameterListChangeListener *)
bool isAutomationNeeded () const noexcept
void setAutomatableParamPosition (double t)
bool isBeingActivelyPlayed () const
virtual void updateAutomatableParamPosition (double time)
Updates all the auto params to their positions at this time.
void updateParameterStreams (double time)
Updates all the parameter streams to their positions at this time.
void updateActiveParameters ()
Iterates all the parameters to find out which ones need to be automated.
void resetRecordingStatus ()
Marks the end of an automation recording stream.
Public Member Functions inherited from tracktion_engine::EditItem
EditItem (EditItemID, Edit &)
virtual ~EditItem ()=default
Public Member Functions inherited from tracktion_engine::MacroParameterElement
MacroParameterElement (Edit &, const juce::ValueTree &)
Constructor.
virtual ~MacroParameterElement ()=default
Destructor.
int getNumMacroParameters () const
Returns the number of macro parameters for this object.
Static Public Member Functions
static const char * getPluginName ()
static juce::StringArray getOscTypeNames ()
Static Public Member Functions inherited from tracktion_engine::Plugin
static bool areSelectedPluginsRackable (SelectionManager &)
static RackInstance * wrapSelectedPluginsInRack (SelectionManager &)
static void sortPlugins (Plugin::Array &)
static void sortPlugins (std::vector< Plugin * > &)
Static Public Member Functions inherited from tracktion_engine::Selectable
static void initialise ()
static bool isSelectableValid (const Selectable *) noexcept
checks whether this object has been deleted.
Static Public Member Functions inherited from tracktion_engine::Exportable
static juce::Array< Exportable * > addAllExportables (Edit &)
Returns all the Exportables contained in an Edit.
Public Attributes
juce::CachedValue< float > oscType
juce::CachedValue< float > bandLimit
juce::CachedValue< float > frequency
juce::CachedValue< float > level
AutomatableParameter::Ptr oscTypeParam
AutomatableParameter::Ptr bandLimitParam
AutomatableParameter::Ptr frequencyParam
AutomatableParameter::Ptr levelParam
Public Attributes inherited from tracktion_engine::Plugin
std::unique_ptr< WindowState > windowState
Engine & engine
juce::ValueTree state
Public Attributes inherited from tracktion_engine::Selectable
WeakRef::Master masterReference
Public Attributes inherited from tracktion_engine::AutomatableEditItem
juce::ValueTree elementState
juce::CachedValue< bool > remapOnTempoChange
Public Attributes inherited from tracktion_engine::EditItem
Edit & edit
const EditItemID itemID
Every EditItem has an ID which is unique within the edit.
Public Attributes inherited from tracktion_engine::MacroParameterElement
MacroParameterList macroParameterList
Static Public Attributes
static const char * xmlTypeName
Additional Inherited Members
Protected Member Functions inherited from tracktion_engine::Plugin
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeChanged () override
void valueTreeChildAdded (juce::ValueTree &, juce::ValueTree &) override
void valueTreeChildRemoved (juce::ValueTree &, juce::ValueTree &, int) override
void valueTreeParentChanged (juce::ValueTree &) override
virtual void processingChanged ()
AutomatableParameter * addParam (const juce::String &paramID, const juce::String &name, juce::NormalisableRange< float > valueRange)
AutomatableParameter * addParam (const juce::String &paramID, const juce::String &name, juce::NormalisableRange< float > valueRange, std::function< juce::String(float)> valueToStringFunction, std::function< float(const juce::String &)> stringToValueFunction)
Protected Member Functions inherited from tracktion_engine::AutomatableEditItem
virtual void buildParameterTree () const
void updateLastPlaybackTime ()
void clearParameterList ()
void addAutomatableParameter (const AutomatableParameter::Ptr &)
void rebuildParameterTree ()
void saveChangedParametersToState ()
Saves the explicit value of any parameters that have deviated to the state.
void restoreChangedParametersFromState ()
Restores the value of any explicitly set parameters.
Protected Member Functions inherited from tracktion_engine::ValueTreeAllEventListener
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeChildAdded (juce::ValueTree &, juce::ValueTree &) override
void valueTreeChildRemoved (juce::ValueTree &, juce::ValueTree &, int) override
void valueTreeChildOrderChanged (juce::ValueTree &, int, int) override
void valueTreeParentChanged (juce::ValueTree &) override
void valueTreeRedirected (juce::ValueTree &) override
Static Protected Member Functions inherited from tracktion_engine::Plugin
static void getLeftRightChannelNames (juce::StringArray *ins, juce::StringArray *outs)
static void getLeftRightChannelNames (juce::StringArray *chans)
Protected Attributes inherited from tracktion_engine::Plugin
juce::CachedValue< bool > enabled
juce::CachedValue< bool > frozen
juce::CachedValue< bool > processing
juce::CachedValue< juce::String > quickParamName
juce::CachedValue< EditItemID > masterPluginID
juce::CachedValue< EditItemID > sidechainSourceID
double sampleRate = 44100.0
int blockSizeSamples = 512
Member Enumeration Documentation
OscType
enum tracktion_engine::ToneGeneratorPlugin::OscType strong
Enumerator
sin
triangle
sawUp
sawDown
square
noise
Constructor & Destructor Documentation
ToneGeneratorPlugin()
tracktion_engine::ToneGeneratorPlugin::ToneGeneratorPlugin (PluginCreationInfo)
~ToneGeneratorPlugin()
tracktion_engine::ToneGeneratorPlugin::~ToneGeneratorPlugin () override
Member Function Documentation
getPluginName()
static const char* tracktion_engine::ToneGeneratorPlugin::getPluginName () static
Referenced by getName().
getName()
juce::String tracktion_engine::ToneGeneratorPlugin::getName () override virtual
The name of the type, e.g.
"Compressor"
Implements tracktion_engine::Plugin.
References getPluginName().
Referenced by getSelectableDescription(), and getShortName().
getPluginType()
juce::String tracktion_engine::ToneGeneratorPlugin::getPluginType () override virtual
Implements tracktion_engine::Plugin.
References xmlTypeName.
getShortName()
juce::String tracktion_engine::ToneGeneratorPlugin::getShortName (int) override virtual
Reimplemented from tracktion_engine::Plugin.
References getName().
producesAudioWhenNoAudioInput()
bool tracktion_engine::ToneGeneratorPlugin::producesAudioWhenNoAudioInput () override virtual
Reimplemented from tracktion_engine::Plugin.
isSynth()
bool tracktion_engine::ToneGeneratorPlugin::isSynth () override virtual
Reimplemented from tracktion_engine::Plugin.
getNumOutputChannelsGivenInputs()
int tracktion_engine::ToneGeneratorPlugin::getNumOutputChannelsGivenInputs (int numInputChannels) override virtual
This must return the number of output channels that the plugin will produce, given a number of input channels.
E.g. some might be able to do mono, so will return 1 if the input is 1, 2 if it is 2, etc.
The default impl just returns the number of items that getChannelNames() returns.
Reimplemented from tracktion_engine::Plugin.
initialise()
void tracktion_engine::ToneGeneratorPlugin::initialise (const PluginInitialisationInfo &) override virtual
Gives the plugin a chance to set itself up before being played.
The sample rate and the average block size - although the blocks won't always be the same, and may be bigger.
Don't call this directly or the initialise count will become out of sync.
See also
baseClassInitialise
Implements tracktion_engine::Plugin.
deinitialise()
void tracktion_engine::ToneGeneratorPlugin::deinitialise () override virtual
Called after play stops to release resources.
Don't call this directly or the initialise count will become out of sync.
See also
baseClassDeinitialise
Implements tracktion_engine::Plugin.
applyToBuffer()
void tracktion_engine::ToneGeneratorPlugin::applyToBuffer (const PluginRenderContext &) override virtual
Process the next block of data.
The incoming buffer will have an unknown number of channels, and the plugin has to deal with them however it wants to.
The buffer should be resized to the number of output channels that the plugin wants to return (which should be the same or less than the number of output channel names it returns from getChannelNames() - never more than this).
Implements tracktion_engine::Plugin.
getSelectableDescription()
juce::String tracktion_engine::ToneGeneratorPlugin::getSelectableDescription () override virtual
Subclasses must return a description of what they are.
Implements tracktion_engine::Selectable.
References getName().
needsConstantBufferSize()
bool tracktion_engine::ToneGeneratorPlugin::needsConstantBufferSize () override virtual
Implements tracktion_engine::Plugin.
restorePluginStateFromValueTree()
void tracktion_engine::ToneGeneratorPlugin::restorePluginStateFromValueTree (const juce::ValueTree &) override virtual
Reimplemented from tracktion_engine::AutomatableEditItem.
getOscTypeNames()
static juce::StringArray tracktion_engine::ToneGeneratorPlugin::getOscTypeNames () static
Member Data Documentation
xmlTypeName
const char* tracktion_engine::ToneGeneratorPlugin::xmlTypeName static
Referenced by getPluginType().
oscType
juce::CachedValue<float> tracktion_engine::ToneGeneratorPlugin::oscType
bandLimit
juce::CachedValue<float> tracktion_engine::ToneGeneratorPlugin::bandLimit
frequency
juce::CachedValue<float> tracktion_engine::ToneGeneratorPlugin::frequency
level
juce::CachedValue<float> tracktion_engine::ToneGeneratorPlugin::level
oscTypeParam
AutomatableParameter::Ptr tracktion_engine::ToneGeneratorPlugin::oscTypeParam
bandLimitParam
AutomatableParameter::Ptr tracktion_engine::ToneGeneratorPlugin::bandLimitParam
frequencyParam
AutomatableParameter::Ptr tracktion_engine::ToneGeneratorPlugin::frequencyParam
levelParam
AutomatableParameter::Ptr tracktion_engine::ToneGeneratorPlugin::levelParam
The documentation for this class was generated from the following file:
tracktion_ToneGenerator.h