TracktionEngine: tracktion_engine::LevelMeasurerProcessingNode Class Reference
tracktion_engine::LevelMeasurerProcessingNode Class Reference final
A Node that introduces latency to balance the latency at the root Node and its position in the graph.
Public Member Functions
LevelMeasurerProcessingNode (std::unique_ptr< tracktion_graph::Node > inputNode, LevelMeterPlugin &levelMeterPlugin)
~LevelMeasurerProcessingNode () override
tracktion_graph::NodeProperties getNodeProperties () override
Should return the properties of the node.
std::vector< tracktion_graph::Node * > getDirectInputNodes () override
Should return all the inputs directly feeding in to this node.
bool isReadyToProcess () override
Should return true when this node is ready to be processed.
void prepareToPlay (const tracktion_graph::PlaybackInitialisationInfo &info) override
Called once before playback begins for each node.
void process (ProcessContext &pc) override
Called when the node is to be processed.
Public Member Functions inherited from tracktion_graph::Node
Node ()=default
virtual ~Node ()=default
void initialise (const PlaybackInitialisationInfo &)
Call once after the graph has been constructed to initialise buffers etc.
void prepareForNextBlock (juce::Range< int64_t > referenceSampleRange)
Call before processing the next block, used to reset the process status.
void process (juce::Range< int64_t > referenceSampleRange)
Call to process the node, which will in turn call the process method with the buffers to fill.
bool hasProcessed () const
Returns true if this node has processed and its outputs can be retrieved.
AudioAndMidiBuffer getProcessedOutput ()
Returns the processed audio and MIDI output.
virtual bool transform (Node &)
Called after construction to give the node a chance to modify its topology.
void retain ()
Retains the buffers so they won't be deallocated after the Node has processed.
void release ()
Releases the buffers allowing internal storage to be deallocated.
virtual size_t getAllocatedBytes () const
Additional Inherited Members
Public Attributes inherited from tracktion_graph::Node
void * internal = nullptr
int numOutputNodes = -1
Protected Member Functions inherited from tracktion_graph::Node
virtual void prefetchBlock (juce::Range< int64_t >)
Called before once on all Nodes before they are processed.
void setOptimisations (NodeOptimisations)
This can be called to provide some hints about allocating or playing back a Node to improve efficiency.
void setAudioOutput (Node *sourceNode, const choc::buffer::ChannelArrayView< float > &)
This can be called during your process function to set a view to the output.
Detailed Description
A Node that introduces latency to balance the latency at the root Node and its position in the graph.
Constructor & Destructor Documentation
LevelMeasurerProcessingNode()
tracktion_engine::LevelMeasurerProcessingNode::LevelMeasurerProcessingNode (std::unique_ptr< tracktion_graph::Node > inputNode, LevelMeterPlugin & levelMeterPlugin)
~LevelMeasurerProcessingNode()
tracktion_engine::LevelMeasurerProcessingNode::~LevelMeasurerProcessingNode () override
References tracktion_engine::Plugin::baseClassDeinitialise(), and tracktion_engine::Plugin::baseClassNeedsInitialising().
Member Function Documentation
getNodeProperties()
tracktion_graph::NodeProperties tracktion_engine::LevelMeasurerProcessingNode::getNodeProperties () override virtual
Should return the properties of the node.
This should not be called until after initialise.
Implements tracktion_graph::Node.
Referenced by prepareToPlay().
getDirectInputNodes()
std::vector<tracktion_graph::Node*> tracktion_engine::LevelMeasurerProcessingNode::getDirectInputNodes () override virtual
Should return all the inputs directly feeding in to this node.
Reimplemented from tracktion_graph::Node.
isReadyToProcess()
bool tracktion_engine::LevelMeasurerProcessingNode::isReadyToProcess () override virtual
Should return true when this node is ready to be processed.
This is usually when its input's output buffers are ready.
Implements tracktion_graph::Node.
prepareToPlay()
void tracktion_engine::LevelMeasurerProcessingNode::prepareToPlay (const tracktion_graph::PlaybackInitialisationInfo &) override virtual
Called once before playback begins for each node.
Use this to allocate buffers etc. This step can be used to modify the topology of the graph (i.e. add/remove nodes). However, if you do this, you must make sure to call initialise on them so they are fully prepared for processing.
Reimplemented from tracktion_graph::Node.
References tracktion_graph::PlaybackInitialisationInfo::blockSize, getNodeProperties(), tracktion_graph::Node::getNodeProperties(), tracktion_graph::NodeProperties::latencyNumSamples, tracktion_graph::NodeProperties::numberOfChannels, tracktion_graph::PlaybackInitialisationInfo::rootNode, and tracktion_graph::PlaybackInitialisationInfo::sampleRate.
process()
void tracktion_engine::LevelMeasurerProcessingNode::process (ProcessContext &) override virtual
Called when the node is to be processed.
This should add in to the buffers available making sure not to change their size at all.
Implements tracktion_graph::Node.
References tracktion_graph::Node::AudioAndMidiBuffer::audio, tracktion_graph::Node::ProcessContext::buffers, tracktion_engine::MidiMessageArray::clear(), tracktion_engine::AppFunctions::copy(), tracktion_engine::MidiMessageArray::copyFrom(), tracktion_engine::LevelMeterPlugin::measurer, tracktion_graph::Node::AudioAndMidiBuffer::midi, tracktion_graph::Node::numOutputNodes, tracktion_graph::Node::setAudioOutput(), and tracktion_engine::MidiMessageArray::swapWith().
The documentation for this class was generated from the following file:
tracktion_LevelMeasurerProcessingNode.h