TracktionEngine: tracktion_engine::PlayHead Class Reference
tracktion_engine::PlayHead Class Reference
tracktion_engine » playback
Classes
struct EditTimeWindow
Public Member Functions
PlayHead ()=default
void setPosition (double newTime)
void play (EditTimeRange rangeToPlay, bool looped)
void play ()
void playLockedToEngine (EditTimeRange rangeToPlay)
void stop ()
void setUserIsDragging (bool b)
bool isUserDragging () const
juce::Time getLastUserInteractionTime () const
double streamTimeToSourceTime (double streamTime) const
double streamTimeToSourceTimeUnlooped (double streamTime) const
EditTimeWindow streamTimeToEditWindow (EditTimeRange streamTime) const
double getPosition () const
double getUnloopedPosition () const
void overridePosition (double newTime)
bool isPlaying () const noexcept
bool isStopped () const noexcept
bool isLooping () const noexcept
bool isRollingIntoLoop () const noexcept
EditTimeRange getLoopTimes () const noexcept
void setLoopTimes (bool loop, EditTimeRange times)
void setRollInToLoop (double t)
void deviceManagerPositionUpdate (double newTime, double newTimeEnd)
called by the DeviceManager
Static Public Member Functions
static double linearTimeToLoopTime (double time, EditTimeRange loop)
static double linearTimeToLoopTime (double time, double loopStart, double loopLen)
Constructor & Destructor Documentation
PlayHead()
tracktion_engine::PlayHead::PlayHead () default
Member Function Documentation
setPosition()
void tracktion_engine::PlayHead::setPosition (double newTime)
References getPosition(), and overridePosition().
Referenced by play(), setLoopTimes(), and stop().
play() [1/2]
void tracktion_engine::PlayHead::play (EditTimeRange rangeToPlay, bool looped)
References tracktion_engine::EditTimeRange::getLength(), setPosition(), and tracktion_engine::EditTimeRange::start.
play() [2/2]
void tracktion_engine::PlayHead::play ()
References getPosition(), and setPosition().
Referenced by playLockedToEngine().
playLockedToEngine()
void tracktion_engine::PlayHead::playLockedToEngine (EditTimeRange rangeToPlay)
References play().
stop()
void tracktion_engine::PlayHead::stop ()
References getPosition(), and setPosition().
setUserIsDragging()
void tracktion_engine::PlayHead::setUserIsDragging (bool b)
isUserDragging()
bool tracktion_engine::PlayHead::isUserDragging () const
Referenced by tracktion_engine::ClickMutingNode::renderAdding(), and tracktion_engine::SubSampleWaveAudioNode::renderSection().
getLastUserInteractionTime()
juce::Time tracktion_engine::PlayHead::getLastUserInteractionTime () const
streamTimeToSourceTime()
double tracktion_engine::PlayHead::streamTimeToSourceTime (double streamTime) const
References linearTimeToLoopTime(), and streamTimeToSourceTimeUnlooped().
Referenced by getPosition().
streamTimeToSourceTimeUnlooped()
double tracktion_engine::PlayHead::streamTimeToSourceTimeUnlooped (double streamTime) const
Referenced by getUnloopedPosition(), streamTimeToEditWindow(), and streamTimeToSourceTime().
linearTimeToLoopTime() [1/2]
static double tracktion_engine::PlayHead::linearTimeToLoopTime (double time, EditTimeRange loop) static
References tracktion_engine::EditTimeRange::getLength(), and tracktion_engine::EditTimeRange::start.
Referenced by streamTimeToEditWindow(), and streamTimeToSourceTime().
linearTimeToLoopTime() [2/2]
static double tracktion_engine::PlayHead::linearTimeToLoopTime (double time, double loopStart, double loopLen) static
streamTimeToEditWindow()
EditTimeWindow tracktion_engine::PlayHead::streamTimeToEditWindow (EditTimeRange streamTime) const
References tracktion_engine::PlayHead::EditTimeWindow::EditTimeWindow(), tracktion_engine::EditTimeRange::end, getLoopTimes(), linearTimeToLoopTime(), tracktion_engine::EditTimeRange::start, and streamTimeToSourceTimeUnlooped().
getPosition()
double tracktion_engine::PlayHead::getPosition () const
References streamTimeToSourceTime().
Referenced by deviceManagerPositionUpdate(), play(), setLoopTimes(), setPosition(), and stop().
getUnloopedPosition()
double tracktion_engine::PlayHead::getUnloopedPosition () const
References streamTimeToSourceTimeUnlooped().
overridePosition()
void tracktion_engine::PlayHead::overridePosition (double newTime)
Referenced by setPosition().
isPlaying()
bool tracktion_engine::PlayHead::isPlaying () const noexcept
Referenced by tracktion_engine::ClickMutingNode::renderAdding(), tracktion_engine::TimedMutingAudioNode::renderAdding(), and tracktion_engine::SpeedRampAudioNode::renderSection().
isStopped()
bool tracktion_engine::PlayHead::isStopped () const noexcept
isLooping()
bool tracktion_engine::PlayHead::isLooping () const noexcept
Referenced by tracktion_engine::AudioNode::invokeSplitRender().
isRollingIntoLoop()
bool tracktion_engine::PlayHead::isRollingIntoLoop () const noexcept
Referenced by tracktion_engine::AudioNode::invokeSplitRender().
getLoopTimes()
EditTimeRange tracktion_engine::PlayHead::getLoopTimes () const noexcept
Referenced by tracktion_engine::AudioNode::invokeSplitRender(), setLoopTimes(), and streamTimeToEditWindow().
setLoopTimes()
void tracktion_engine::PlayHead::setLoopTimes (bool loop, EditTimeRange times)
References getLoopTimes(), getPosition(), and setPosition().
setRollInToLoop()
void tracktion_engine::PlayHead::setRollInToLoop (double t)
deviceManagerPositionUpdate()
void tracktion_engine::PlayHead::deviceManagerPositionUpdate (double newTime, double newTimeEnd)
called by the DeviceManager
References getPosition().
The documentation for this class was generated from the following file:
tracktion_PlayHead.h