TracktionEngine: tracktion::engine::MultiThreadedNodePlayer Class Reference
tracktion::engine::MultiThreadedNodePlayer Class Reference
Plays back a Node with PlayHeadState and ProcessState.
Public Member Functions
MultiThreadedNodePlayer (ProcessState &processStateToUse)
Creates an NodePlayer to process a Node.
MultiThreadedNodePlayer (std::unique_ptr< tracktion::graph::Node > node, ProcessState &processStateToUse, double sampleRate, int blockSize)
Creates an NodePlayer to process a Node.
void setNumThreads (size_t numThreads)
Sets the number of threads to use for rendering.
tracktion::graph::Node * getNode ()
void setNode (std::unique_ptr< tracktion::graph::Node > newNode)
void setNode (std::unique_ptr< tracktion::graph::Node > newNode, double sampleRateToUse, int blockSizeToUse)
void prepareToPlay (double sampleRateToUse, int blockSizeToUse)
int process (const tracktion::graph::Node::ProcessContext &pc)
Processes a block of audio and MIDI data.
void clearNode ()
Clears the Node currently playing.
double getSampleRate () const
Returns the current sample rate.
Detailed Description
Plays back a Node with PlayHeadState and ProcessState.
Constructor & Destructor Documentation
MultiThreadedNodePlayer() [1/2]
tracktion::engine::MultiThreadedNodePlayer::MultiThreadedNodePlayer (ProcessState & processStateToUse)
Creates an NodePlayer to process a Node.
MultiThreadedNodePlayer() [2/2]
tracktion::engine::MultiThreadedNodePlayer::MultiThreadedNodePlayer (std::unique_ptr< tracktion::graph::Node > node, ProcessState & processStateToUse, double sampleRate, int blockSize)
Creates an NodePlayer to process a Node.
References tracktion::graph::MultiThreadedNodePlayer::setNode().
Member Function Documentation
setNumThreads()
void tracktion::engine::MultiThreadedNodePlayer::setNumThreads (size_t numThreads)
Sets the number of threads to use for rendering.
This can be 0 in which case only the process calling thread will be used for processing. N.B. this will pause processing whilst updating the threads so there will be a gap in the audio.
References tracktion::graph::MultiThreadedNodePlayer::setNumThreads().
getNode()
tracktion::graph::Node* tracktion::engine::MultiThreadedNodePlayer::getNode ()
References tracktion::graph::MultiThreadedNodePlayer::getNode().
setNode() [1/2]
void tracktion::engine::MultiThreadedNodePlayer::setNode (std::unique_ptr< tracktion::graph::Node > newNode)
References tracktion::graph::MultiThreadedNodePlayer::setNode().
setNode() [2/2]
void tracktion::engine::MultiThreadedNodePlayer::setNode (std::unique_ptr< tracktion::graph::Node > newNode, double sampleRateToUse, int blockSizeToUse)
References tracktion::graph::MultiThreadedNodePlayer::setNode().
prepareToPlay()
void tracktion::engine::MultiThreadedNodePlayer::prepareToPlay (double sampleRateToUse, int blockSizeToUse)
References tracktion::graph::MultiThreadedNodePlayer::prepareToPlay().
process()
int tracktion::engine::MultiThreadedNodePlayer::process (const tracktion::graph::Node::ProcessContext & pc)
Processes a block of audio and MIDI data.
Returns the number of times a node was checked but unable to be processed.
References tracktion::graph::Node::AudioAndMidiBuffer::audio, tracktion::graph::Node::ProcessContext::buffers, tracktion::engine::MidiMessageArray::clear(), tracktion::engine::ProcessState::editTimeRange, tracktion::graph::MultiThreadedNodePlayer::getSampleRate(), tracktion::graph::Node::AudioAndMidiBuffer::midi, tracktion::graph::Node::ProcessContext::numSamples, tracktion::graph::PlayHeadState::playHead, tracktion::graph::MultiThreadedNodePlayer::process(), tracktion::graph::Node::ProcessContext::referenceSampleRange, tracktion::graph::PlayHead::setReferenceSampleRange(), tracktion::engine::ProcessState::update(), and tracktion::engine::ProcessState::yes.
clearNode()
void tracktion::engine::MultiThreadedNodePlayer::clearNode ()
Clears the Node currently playing.
References tracktion::graph::MultiThreadedNodePlayer::clearNode().
getSampleRate()
double tracktion::engine::MultiThreadedNodePlayer::getSampleRate () const
Returns the current sample rate.
References tracktion::graph::MultiThreadedNodePlayer::getSampleRate().
The documentation for this class was generated from the following file:
tracktion_engine/playback/graph/tracktion_MultiThreadedNodePlayer.h