TracktionEngine: tracktion::engine::TracktionNodePlayer Class Reference
tracktion::engine::TracktionNodePlayer Class Reference
Plays back a Node with PlayHeadState and ProcessState.
Public Member Functions
TracktionNodePlayer (ProcessState &processStateToUse, tracktion::graph::LockFreeMultiThreadedNodePlayer::ThreadPoolCreator poolCreator)
Creates an NodePlayer to process a Node.
TracktionNodePlayer (std::unique_ptr< tracktion::graph::Node > node, ProcessState &processStateToUse, double sampleRate, int blockSize, tracktion::graph::LockFreeMultiThreadedNodePlayer::ThreadPoolCreator poolCreator)
Creates an NodePlayer to process a Node.
void setNumThreads (size_t numThreads)
Sets the number of threads to use for rendering.
tracktion::graph::Node * getNode ()
void setNode (std::unique_ptr< tracktion::graph::Node > newNode)
void setNode (std::unique_ptr< tracktion::graph::Node > newNode, double sampleRateToUse, int blockSizeToUse)
void prepareToPlay (double sampleRateToUse, int blockSizeToUse)
int process (const tracktion::graph::Node::ProcessContext &pc)
Processes a block of audio and MIDI data.
void clearNode ()
Clears the Node currently playing.
double getSampleRate () const
Returns the current sample rate.
void enablePooledMemoryAllocations (bool enablePooledMemory)
Detailed Description
Plays back a Node with PlayHeadState and ProcessState.
Constructor & Destructor Documentation
TracktionNodePlayer() [1/2]
tracktion::engine::TracktionNodePlayer::TracktionNodePlayer (ProcessState & processStateToUse, tracktion::graph::LockFreeMultiThreadedNodePlayer::ThreadPoolCreator poolCreator)
Creates an NodePlayer to process a Node.
TracktionNodePlayer() [2/2]
tracktion::engine::TracktionNodePlayer::TracktionNodePlayer (std::unique_ptr< tracktion::graph::Node > node, ProcessState & processStateToUse, double sampleRate, int blockSize, tracktion::graph::LockFreeMultiThreadedNodePlayer::ThreadPoolCreator poolCreator)
Creates an NodePlayer to process a Node.
References tracktion::graph::LockFreeMultiThreadedNodePlayer::setNode().
Member Function Documentation
setNumThreads()
void tracktion::engine::TracktionNodePlayer::setNumThreads (size_t numThreads)
Sets the number of threads to use for rendering.
This can be 0 in which case only the process calling thread will be used for processing. N.B. this will pause processing whilst updating the threads so there will be a gap in the audio.
References tracktion::graph::LockFreeMultiThreadedNodePlayer::setNumThreads().
getNode()
tracktion::graph::Node* tracktion::engine::TracktionNodePlayer::getNode ()
References tracktion::graph::LockFreeMultiThreadedNodePlayer::getNode().
setNode() [1/2]
void tracktion::engine::TracktionNodePlayer::setNode (std::unique_ptr< tracktion::graph::Node > newNode)
References tracktion::graph::LockFreeMultiThreadedNodePlayer::setNode().
setNode() [2/2]
void tracktion::engine::TracktionNodePlayer::setNode (std::unique_ptr< tracktion::graph::Node > newNode, double sampleRateToUse, int blockSizeToUse)
References tracktion::graph::LockFreeMultiThreadedNodePlayer::setNode().
prepareToPlay()
void tracktion::engine::TracktionNodePlayer::prepareToPlay (double sampleRateToUse, int blockSizeToUse)
References tracktion::graph::LockFreeMultiThreadedNodePlayer::prepareToPlay().
process()
int tracktion::engine::TracktionNodePlayer::process (const tracktion::graph::Node::ProcessContext & pc)
Processes a block of audio and MIDI data.
Returns the number of times a node was checked but unable to be processed.
References tracktion::graph::PlayHeadState::playHead, tracktion::graph::Node::ProcessContext::referenceSampleRange, and tracktion::graph::PlayHead::setReferenceSampleRange().
clearNode()
void tracktion::engine::TracktionNodePlayer::clearNode ()
Clears the Node currently playing.
References tracktion::graph::LockFreeMultiThreadedNodePlayer::clearNode().
getSampleRate()
double tracktion::engine::TracktionNodePlayer::getSampleRate () const
Returns the current sample rate.
References tracktion::graph::LockFreeMultiThreadedNodePlayer::getSampleRate().
enablePooledMemoryAllocations()
void tracktion::engine::TracktionNodePlayer::enablePooledMemoryAllocations (bool enablePooledMemory)
References tracktion::graph::LockFreeMultiThreadedNodePlayer::enablePooledMemoryAllocations().
The documentation for this class was generated from the following file:
tracktion_TracktionNodePlayer.h