TracktionEngine: tracktion_engine::SubSampleWaveAudioNode Class Reference
tracktion_engine::SubSampleWaveAudioNode Class Reference
Public Member Functions
SubSampleWaveAudioNode (Engine &e, const AudioFile &af, EditTimeRange editTime, double off, EditTimeRange loop, LiveClipLevel level, double speed, const juce::AudioChannelSet &channels)
void getAudioNodeProperties (AudioNodeProperties &info) override
void visitNodes (const VisitorFn &v) override
bool purgeSubNodes (bool keepAudio, bool) override
Tells the node to delete any sub-nodes that don't produce the required type of output.
void prepareAudioNodeToPlay (const PlaybackInitialisationInfo &info) override
tells the node to initialise itself ready for playing from the given time.
bool isReadyToRender () override
void releaseAudioNodeResources () override
tells the node that play has stopped, and it can free up anything it no longer needs.
void renderOver (const AudioRenderContext &rc) override
void renderAdding (const AudioRenderContext &rc) override
void prepareForNextBlock (const AudioRenderContext &rc) override
void renderSection (const AudioRenderContext &rc, EditTimeRange editTime)
Public Member Functions inherited from tracktion_engine::AudioNode
AudioNode ()
virtual ~AudioNode ()
virtual juce::ReferenceCountedObjectPtr< Plugin > getPlugin () const
void callRenderAdding (const AudioRenderContext &)
void callRenderOver (const AudioRenderContext &)
Public Attributes
Engine & engine
Additional Inherited Members
Public Types inherited from tracktion_engine::AudioNode
using VisitorFn = std::function< void(AudioNode &)>
Static Public Member Functions inherited from tracktion_engine::AudioNode
template<typename CallbackType >
static void invokeSplitRender (const AudioRenderContext &rc, CallbackType &target)
Constructor & Destructor Documentation
SubSampleWaveAudioNode()
tracktion_engine::SubSampleWaveAudioNode::SubSampleWaveAudioNode (Engine & e, const AudioFile & af, EditTimeRange editTime, double off, EditTimeRange loop, LiveClipLevel level, double speed, const juce::AudioChannelSet & channels)
Member Function Documentation
getAudioNodeProperties()
void tracktion_engine::SubSampleWaveAudioNode::getAudioNodeProperties (AudioNodeProperties & info) override virtual
Implements tracktion_engine::AudioNode.
References tracktion_engine::AudioFile::getNumChannels(), tracktion_engine::AudioNodeProperties::hasAudio, tracktion_engine::AudioNodeProperties::hasMidi, and tracktion_engine::AudioNodeProperties::numberOfChannels.
visitNodes()
void tracktion_engine::SubSampleWaveAudioNode::visitNodes (const VisitorFn & v) override virtual
Implements tracktion_engine::AudioNode.
purgeSubNodes()
bool tracktion_engine::SubSampleWaveAudioNode::purgeSubNodes (bool keepAudio, bool keepMidi) override virtual
Tells the node to delete any sub-nodes that don't produce the required type of output.
This optimises out any unplayable bits of the audio graph. Returns true if this node should be kept, false if this node can itself be deleted.
Implements tracktion_engine::AudioNode.
prepareAudioNodeToPlay()
void tracktion_engine::SubSampleWaveAudioNode::prepareAudioNodeToPlay (const PlaybackInitialisationInfo &) override virtual
tells the node to initialise itself ready for playing from the given time.
This call may be made more than once before releaseAudioNodeResources() is called
Implements tracktion_engine::AudioNode.
References tracktion_engine::AudioFileManager::cache, tracktion_engine::AudioFileCache::createReader(), engine, tracktion_engine::Engine::getAudioFileManager(), and tracktion_engine::PlaybackInitialisationInfo::sampleRate.
isReadyToRender()
bool tracktion_engine::SubSampleWaveAudioNode::isReadyToRender () override virtual
Implements tracktion_engine::AudioNode.
References tracktion_engine::AudioFileManager::cache, tracktion_engine::AudioFileCache::createReader(), engine, tracktion_engine::Engine::getAudioFileManager(), and tracktion_engine::AudioFile::isNull().
releaseAudioNodeResources()
void tracktion_engine::SubSampleWaveAudioNode::releaseAudioNodeResources () override virtual
tells the node that play has stopped, and it can free up anything it no longer needs.
Implements tracktion_engine::AudioNode.
renderOver()
void tracktion_engine::SubSampleWaveAudioNode::renderOver (const AudioRenderContext & rc) override virtual
Implements tracktion_engine::AudioNode.
References tracktion_engine::AudioNode::callRenderAdding().
renderAdding()
void tracktion_engine::SubSampleWaveAudioNode::renderAdding (const AudioRenderContext & rc) override virtual
Implements tracktion_engine::AudioNode.
References tracktion_engine::AudioNode::invokeSplitRender().
prepareForNextBlock()
void tracktion_engine::SubSampleWaveAudioNode::prepareForNextBlock (const AudioRenderContext & rc) override virtual
Reimplemented from tracktion_engine::AudioNode.
References tracktion_engine::PlayHead::EditTimeWindow::editRange1, tracktion_engine::AudioRenderContext::getEditTime(), tracktion_engine::EditTimeRange::getStart(), and SCOPED_REALTIME_CHECK.
renderSection()
void tracktion_engine::SubSampleWaveAudioNode::renderSection (const AudioRenderContext & rc, EditTimeRange editTime)
References tracktion_engine::AudioScratchBuffer::buffer, tracktion_engine::AudioRenderContext::bufferNumSamples, tracktion_engine::AudioRenderContext::bufferStartSample, tracktion_engine::AudioRenderContext::destBuffer, tracktion_engine::EditTimeRange::getEnd(), tracktion_engine::LiveClipLevel::getGainIncludingMute(), tracktion_engine::LiveClipLevel::getLeftAndRightGains(), tracktion_engine::EditTimeRange::getStart(), tracktion_engine::AudioRenderContext::isContiguousWithPreviousBlock(), tracktion_engine::AudioRenderContext::isFirstBlockOfLoop(), tracktion_engine::AudioRenderContext::isRendering, tracktion_engine::PlayHead::isUserDragging(), tracktion_engine::AudioRenderContext::playhead, tracktion_engine::AudioRenderContext::sanityCheck(), and SCOPED_REALTIME_CHECK.
Member Data Documentation
engine
Engine& tracktion_engine::SubSampleWaveAudioNode::engine
Referenced by isReadyToRender(), and prepareAudioNodeToPlay().
The documentation for this class was generated from the following file:
tracktion_SpeedRampAudioNode.h