TracktionEngine: tracktion_engine::ProjectItem Class Reference
tracktion_engine::ProjectItem Class Reference
Represents a file-based resource that is used in a project.
Public Types
enum Category {
Category::none, Category::edit, Category::recorded, Category::exports,
Category::archives, Category::imported, Category::rendered, Category::frozen,
Category::video
}
enum RenameMode { RenameMode::always, RenameMode::local, RenameMode::never }
enum SetNameMode { SetNameMode::doDefault, SetNameMode::forceRename, SetNameMode::forceNoRename }
using Ptr = juce::ReferenceCountedObjectPtr< ProjectItem >
using Array = juce::ReferenceCountedArray< ProjectItem >
Public Types inherited from tracktion_engine::Selectable
using WeakRef = juce::WeakReference< Selectable >
Public Member Functions
ProjectItem (Engine &, ProjectItemID, juce::InputStream *)
Loads a ProjectItem from a stream that was saved using writeToStream().
ProjectItem (Engine &, const juce::String &name, const juce::String &type, const juce::String &desc, const juce::String &file, Category, double length, ProjectItemID)
Creates a ProjectItem with some settings.
~ProjectItem () override
juce::String getSelectableDescription () override
Subclasses must return a description of what they are.
void selectionStatusChanged (bool isNowSelected) override
Can be overridden to tell this object that it has just been selected or deselected.
ProjectItemID getID () const noexcept
juce::ReferenceCountedObjectPtr< Project > getProject () const
bool hasBeenDeleted () const
const juce::String & getType () const
bool isWave () const noexcept
bool isMidi () const noexcept
bool isEdit () const noexcept
bool isVideo () const noexcept
const juce::String & getName () const
void setName (const juce::String &name, SetNameMode mode)
Category getCategory () const
void setCategory (Category cat)
juce::String getNamedProperty (const juce::String &name) const
void setNamedProperty (const juce::String &name, const juce::String &value)
juce::String getDescription () const
void setDescription (const juce::String &newDesc)
juce::Array< double > getMarkedPoints () const
optional set of interesting time markers, for wave files
void setMarkedPoints (const juce::Array< double > &points)
void copyAllPropertiesFrom (const ProjectItem &other)
copies the full description, categories, properties, etc.
bool convertEditFile ()
double getLength () const
void setLength (double length)
juce::String getProjectName () const
name of the project it's inside.
juce::File getEditPreviewFile () const
Returns the file that should be used as a preview for this Edit.
juce::File getEditThumbnailFile () const
Returns the file that should be used as a visual preview for this Edit.
juce::File getSourceFile ()
juce::String getRawFileName () const
juce::String getFileName () const
void setSourceFile (const juce::File &)
bool isForFile (const juce::File &)
void renameSourceFile ()
lets the user rename the file.
Ptr createCopy ()
Creates a copy of this object and returns the copy.
void sendChange ()
bool copySectionToNewFile (const juce::File &destFile, juce::File &actualFileCreated, double startTime, double length)
the actual file created may differ, e.g.
bool deleteSourceFile ()
void verifyLength ()
Updates the stored length value in this object.
void changeProjectId (int oldID, int newID)
used when moving to another project.
void writeToStream (juce::OutputStream &) const
juce::StringArray getSearchTokens () const
Returns a list of search strings for this object, by chopping up the name and description into words.
Public Member Functions inherited from tracktion_engine::Selectable
Selectable ()
virtual ~Selectable ()
virtual void changed ()
This should be called to send a change notification to any SelectableListeners that are registered with this object.
virtual void selectableAboutToBeDeleted ()
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void addSelectableListener (SelectableListener *)
void removeSelectableListener (SelectableListener *)
void cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
void deselect ()
void propertiesChanged ()
void notifyListenersOfDeletion ()
WeakRef getWeakRef ()
Static Public Member Functions
static const char * waveItemType () noexcept
static const char * editItemType () noexcept
static const char * midiItemType () noexcept
static const char * videoItemType () noexcept
Static Public Member Functions inherited from tracktion_engine::Selectable
static void initialise ()
static bool isSelectableValid (const Selectable *) noexcept
checks whether this object has been deleted.
Additional Inherited Members
Public Attributes inherited from tracktion_engine::Selectable
WeakRef::Master masterReference
Detailed Description
Represents a file-based resource that is used in a project.
This might be an edit, audio file, midi file, etc.
Member Typedef Documentation
Ptr
using tracktion_engine::ProjectItem::Ptr = juce::ReferenceCountedObjectPtr<ProjectItem>
Array
using tracktion_engine::ProjectItem::Array = juce::ReferenceCountedArray<ProjectItem>
Member Enumeration Documentation
Category
enum tracktion_engine::ProjectItem::Category strong
Enumerator
none
edit
recorded
exports
archives
imported
rendered
frozen
video
RenameMode
enum tracktion_engine::ProjectItem::RenameMode strong
Enumerator
always
local
never
SetNameMode
enum tracktion_engine::ProjectItem::SetNameMode strong
Enumerator
doDefault
forceRename
forceNoRename
Constructor & Destructor Documentation
ProjectItem() [1/2]
tracktion_engine::ProjectItem::ProjectItem (Engine & , ProjectItemID , juce::InputStream *)
Loads a ProjectItem from a stream that was saved using writeToStream().
ProjectItem() [2/2]
tracktion_engine::ProjectItem::ProjectItem (Engine & , const juce::String & name, const juce::String & type, const juce::String & desc, const juce::String & file, Category , double length, ProjectItemID)
Creates a ProjectItem with some settings.
~ProjectItem()
tracktion_engine::ProjectItem::~ProjectItem () override
Member Function Documentation
getSelectableDescription()
juce::String tracktion_engine::ProjectItem::getSelectableDescription () override virtual
Subclasses must return a description of what they are.
Implements tracktion_engine::Selectable.
selectionStatusChanged()
void tracktion_engine::ProjectItem::selectionStatusChanged (bool isNowSelected) override virtual
Can be overridden to tell this object that it has just been selected or deselected.
Reimplemented from tracktion_engine::Selectable.
getID()
ProjectItemID tracktion_engine::ProjectItem::getID () const noexcept
getProject()
juce::ReferenceCountedObjectPtr<Project> tracktion_engine::ProjectItem::getProject () const
hasBeenDeleted()
bool tracktion_engine::ProjectItem::hasBeenDeleted () const
waveItemType()
static const char* tracktion_engine::ProjectItem::waveItemType () static noexcept
Referenced by isWave().
editItemType()
static const char* tracktion_engine::ProjectItem::editItemType () static noexcept
Referenced by isEdit().
midiItemType()
static const char* tracktion_engine::ProjectItem::midiItemType () static noexcept
Referenced by isMidi().
videoItemType()
static const char* tracktion_engine::ProjectItem::videoItemType () static noexcept
Referenced by isVideo().
getType()
const juce::String& tracktion_engine::ProjectItem::getType () const
Referenced by isEdit(), isMidi(), isVideo(), and isWave().
isWave()
bool tracktion_engine::ProjectItem::isWave () const noexcept
References getType(), and waveItemType().
isMidi()
bool tracktion_engine::ProjectItem::isMidi () const noexcept
References getType(), and midiItemType().
isEdit()
bool tracktion_engine::ProjectItem::isEdit () const noexcept
References editItemType(), and getType().
isVideo()
bool tracktion_engine::ProjectItem::isVideo () const noexcept
References getType(), and videoItemType().
getName()
const juce::String& tracktion_engine::ProjectItem::getName () const
setName()
void tracktion_engine::ProjectItem::setName (const juce::String & name, SetNameMode mode)
getCategory()
Category tracktion_engine::ProjectItem::getCategory () const
setCategory()
void tracktion_engine::ProjectItem::setCategory (Category cat)
getNamedProperty()
juce::String tracktion_engine::ProjectItem::getNamedProperty (const juce::String & name) const
setNamedProperty()
void tracktion_engine::ProjectItem::setNamedProperty (const juce::String & name, const juce::String & value)
getDescription()
juce::String tracktion_engine::ProjectItem::getDescription () const
setDescription()
void tracktion_engine::ProjectItem::setDescription (const juce::String & newDesc)
getMarkedPoints()
juce::Array<double> tracktion_engine::ProjectItem::getMarkedPoints () const
optional set of interesting time markers, for wave files
setMarkedPoints()
void tracktion_engine::ProjectItem::setMarkedPoints (const juce::Array< double > & points)
copyAllPropertiesFrom()
void tracktion_engine::ProjectItem::copyAllPropertiesFrom (const ProjectItem & other)
copies the full description, categories, properties, etc.
convertEditFile()
bool tracktion_engine::ProjectItem::convertEditFile ()
getLength()
double tracktion_engine::ProjectItem::getLength () const
setLength()
void tracktion_engine::ProjectItem::setLength (double length)
getProjectName()
juce::String tracktion_engine::ProjectItem::getProjectName () const
name of the project it's inside.
getEditPreviewFile()
juce::File tracktion_engine::ProjectItem::getEditPreviewFile () const
Returns the file that should be used as a preview for this Edit.
getEditThumbnailFile()
juce::File tracktion_engine::ProjectItem::getEditThumbnailFile () const
Returns the file that should be used as a visual preview for this Edit.
getSourceFile()
juce::File tracktion_engine::ProjectItem::getSourceFile ()
getRawFileName()
juce::String tracktion_engine::ProjectItem::getRawFileName () const
getFileName()
juce::String tracktion_engine::ProjectItem::getFileName () const
setSourceFile()
void tracktion_engine::ProjectItem::setSourceFile (const juce::File &)
isForFile()
bool tracktion_engine::ProjectItem::isForFile (const juce::File &)
renameSourceFile()
void tracktion_engine::ProjectItem::renameSourceFile ()
lets the user rename the file.
createCopy()
Ptr tracktion_engine::ProjectItem::createCopy ()
Creates a copy of this object and returns the copy.
sendChange()
void tracktion_engine::ProjectItem::sendChange ()
copySectionToNewFile()
bool tracktion_engine::ProjectItem::copySectionToNewFile (const juce::File & destFile, juce::File & actualFileCreated, double startTime, double length)
the actual file created may differ, e.g.
if an ogg file is chopped up and has to become a wav.
deleteSourceFile()
bool tracktion_engine::ProjectItem::deleteSourceFile ()
verifyLength()
void tracktion_engine::ProjectItem::verifyLength ()
Updates the stored length value in this object.
changeProjectId()
void tracktion_engine::ProjectItem::changeProjectId (int oldID, int newID)
used when moving to another project.
writeToStream()
void tracktion_engine::ProjectItem::writeToStream (juce::OutputStream &) const
getSearchTokens()
juce::StringArray tracktion_engine::ProjectItem::getSearchTokens () const
Returns a list of search strings for this object, by chopping up the name and description into words.
The documentation for this class was generated from the following file:
tracktion_ProjectItem.h