TracktionEngine: tracktion_engine::Engine Class Reference
tracktion_engine::Engine Class Reference
tracktion_engine » utilities
The Engine is the central class for all tracktion sessions.
Public Types
using WeakRef = juce::WeakReference< Engine >
Public Member Functions
Engine (juce::String applicationName)
Engine (juce::String applicationName, std::unique_ptr< UIBehaviour >, std::unique_ptr< EngineBehaviour >)
Engine (std::unique_ptr< PropertyStorage >, std::unique_ptr< UIBehaviour >, std::unique_ptr< EngineBehaviour >)
~Engine ()
TemporaryFileManager & getTemporaryFileManager () const
AudioFileFormatManager & getAudioFileFormatManager () const
PropertyStorage & getPropertyStorage () const
UIBehaviour & getUIBehaviour () const
EngineBehaviour & getEngineBehaviour () const
DeviceManager & getDeviceManager () const
MidiProgramManager & getMidiProgramManager () const
ExternalControllerManager & getExternalControllerManager () const
RenderManager & getRenderManager () const
BackgroundJobManager & getBackgroundJobs () const
AudioFileManager & getAudioFileManager () const
MidiLearnState & getMidiLearnState () const
PluginManager & getPluginManager () const
EditDeleter & getEditDeleter () const
RecordingThumbnailManager & getRecordingThumbnailManager () const
WaveInputRecordingThread & getWaveInputRecordingThread () const
ActiveEdits & getActiveEdits () const noexcept
GrooveTemplateManager & getGrooveTemplateManager ()
CompFactory & getCompFactory () const
WarpTimeFactory & getWarpTimeFactory () const
ProjectManager & getProjectManager () const
Static Public Member Functions
static juce::Array< Engine * > getEngines ()
Detailed Description
The Engine is the central class for all tracktion sessions.
Create a Engine before creating any edits. Pass in subclasses of behaviours to customise how the engine behaves or pass nullptr to use the defaults. To get going quickly, just use the constructor that takes an application name, which uses default settings.
Member Typedef Documentation
WeakRef
using tracktion_engine::Engine::WeakRef = juce::WeakReference<Engine>
Constructor & Destructor Documentation
Engine() [1/3]
tracktion_engine::Engine::Engine (juce::String applicationName)
Engine() [2/3]
tracktion_engine::Engine::Engine (juce::String applicationName, std::unique_ptr< UIBehaviour > , std::unique_ptr< EngineBehaviour >)
Engine() [3/3]
tracktion_engine::Engine::Engine (std::unique_ptr< PropertyStorage > , std::unique_ptr< UIBehaviour > , std::unique_ptr< EngineBehaviour >)
~Engine()
tracktion_engine::Engine::~Engine ()
Member Function Documentation
getEngines()
static juce::Array<Engine*> tracktion_engine::Engine::getEngines () static
getTemporaryFileManager()
TemporaryFileManager& tracktion_engine::Engine::getTemporaryFileManager () const
getAudioFileFormatManager()
AudioFileFormatManager& tracktion_engine::Engine::getAudioFileFormatManager () const
Referenced by tracktion_engine::AudioFileUtils::readFromFormat(), and tracktion_engine::WarpTimeRenderJob::renderNextBlock().
getPropertyStorage()
PropertyStorage& tracktion_engine::Engine::getPropertyStorage () const
getUIBehaviour()
UIBehaviour& tracktion_engine::Engine::getUIBehaviour () const
getEngineBehaviour()
EngineBehaviour& tracktion_engine::Engine::getEngineBehaviour () const
Referenced by tracktion_engine::Pitch::getPitchAsString(), and tracktion_engine::Pitch::getPitchAsStrings().
getDeviceManager()
DeviceManager& tracktion_engine::Engine::getDeviceManager () const
getMidiProgramManager()
MidiProgramManager& tracktion_engine::Engine::getMidiProgramManager () const
Referenced by tracktion_engine::MidiOutputDevice::getMidiProgramManager().
getExternalControllerManager()
ExternalControllerManager& tracktion_engine::Engine::getExternalControllerManager () const
getRenderManager()
RenderManager& tracktion_engine::Engine::getRenderManager () const
Referenced by tracktion_engine::WarpTimeRenderJob::getOrCreateRenderJob(), and tracktion_engine::ReverseRenderJob::getOrCreateRenderJob().
getBackgroundJobs()
BackgroundJobManager& tracktion_engine::Engine::getBackgroundJobs () const
getAudioFileManager()
AudioFileManager& tracktion_engine::Engine::getAudioFileManager () const
Referenced by tracktion_engine::SubSampleWaveAudioNode::isReadyToRender(), tracktion_engine::SubSampleWaveAudioNode::prepareAudioNodeToPlay(), and tracktion_engine::ReverseRenderJob::renderNextBlock().
getMidiLearnState()
MidiLearnState& tracktion_engine::Engine::getMidiLearnState () const
getPluginManager()
PluginManager& tracktion_engine::Engine::getPluginManager () const
getEditDeleter()
EditDeleter& tracktion_engine::Engine::getEditDeleter () const
getRecordingThumbnailManager()
RecordingThumbnailManager& tracktion_engine::Engine::getRecordingThumbnailManager () const
Referenced by tracktion_engine::RecordingThumbnailManager::Thumbnail::~Thumbnail().
getWaveInputRecordingThread()
WaveInputRecordingThread& tracktion_engine::Engine::getWaveInputRecordingThread () const
getActiveEdits()
ActiveEdits& tracktion_engine::Engine::getActiveEdits () const noexcept
getGrooveTemplateManager()
GrooveTemplateManager& tracktion_engine::Engine::getGrooveTemplateManager ()
getCompFactory()
CompFactory& tracktion_engine::Engine::getCompFactory () const
getWarpTimeFactory()
WarpTimeFactory& tracktion_engine::Engine::getWarpTimeFactory () const
getProjectManager()
ProjectManager& tracktion_engine::Engine::getProjectManager () const
The documentation for this class was generated from the following file:
tracktion_Engine.h