TracktionEngine: tracktion_graph::SummingNode Class Reference
tracktion_graph::SummingNode Class Reference final
An Node which sums together the multiple inputs adding additional latency to provide a coherent output.
Public Member Functions
SummingNode ()=default
SummingNode (std::vector< std::unique_ptr< Node >> inputs)
SummingNode (std::vector< Node * > inputs)
SummingNode (std::vector< std::unique_ptr< Node >> ownedInputs, std::vector< Node * > referencedInputs)
void addInput (std::unique_ptr< Node > newInput)
Adds an input to be summed in this Node.
void setDoubleProcessingPrecision (bool shouldSumInDoublePrecision)
Enables Nodes to be intermediately summed using double precision.
NodeProperties getNodeProperties () override
Should return the properties of the node.
std::vector< Node * > getDirectInputNodes () override
Should return all the inputs directly feeding in to this node.
bool transform (Node &) override
Called after construction to give the node a chance to modify its topology.
void prepareToPlay (const PlaybackInitialisationInfo &info) override
Called once before playback begins for each node.
bool isReadyToProcess () override
Should return true when this node is ready to be processed.
void process (ProcessContext &pc) override
Called when the node is to be processed.
Public Member Functions inherited from tracktion_graph::Node
Node ()=default
virtual ~Node ()=default
void initialise (const PlaybackInitialisationInfo &)
Call once after the graph has been constructed to initialise buffers etc.
void prepareForNextBlock (juce::Range< int64_t > referenceSampleRange)
Call before processing the next block, used to reset the process status.
void process (juce::Range< int64_t > referenceSampleRange)
Call to process the node, which will in turn call the process method with the buffers to fill.
bool hasProcessed () const
Returns true if this node has processed and its outputs can be retrieved.
AudioAndMidiBuffer getProcessedOutput ()
Returns the processed audio and MIDI output.
void retain ()
Retains the buffers so they won't be deallocated after the Node has processed.
void release ()
Releases the buffers allowing internal storage to be deallocated.
virtual size_t getAllocatedBytes () const
Additional Inherited Members
Public Attributes inherited from tracktion_graph::Node
void * internal = nullptr
int numOutputNodes = -1
Protected Member Functions inherited from tracktion_graph::Node
virtual void prefetchBlock (juce::Range< int64_t >)
Called before once on all Nodes before they are processed.
void setOptimisations (NodeOptimisations)
This can be called to provide some hints about allocating or playing back a Node to improve efficiency.
void setAudioOutput (Node *sourceNode, const choc::buffer::ChannelArrayView< float > &)
This can be called during your process function to set a view to the output.
Detailed Description
An Node which sums together the multiple inputs adding additional latency to provide a coherent output.
Constructor & Destructor Documentation
SummingNode() [1/4]
tracktion_graph::SummingNode::SummingNode () default
SummingNode() [2/4]
tracktion_graph::SummingNode::SummingNode (std::vector< std::unique_ptr< Node >> inputs)
SummingNode() [3/4]
tracktion_graph::SummingNode::SummingNode (std::vector< Node * > inputs)
SummingNode() [4/4]
tracktion_graph::SummingNode::SummingNode (std::vector< std::unique_ptr< Node >> ownedInputs, std::vector< Node * > referencedInputs)
Member Function Documentation
addInput()
void tracktion_graph::SummingNode::addInput (std::unique_ptr< Node > newInput)
Adds an input to be summed in this Node.
setDoubleProcessingPrecision()
void tracktion_graph::SummingNode::setDoubleProcessingPrecision (bool shouldSumInDoublePrecision)
Enables Nodes to be intermediately summed using double precision.
This must be set before the node is initialised. N.B. The output will still be single-precision floats.
getNodeProperties()
NodeProperties tracktion_graph::SummingNode::getNodeProperties () override virtual
Should return the properties of the node.
This should not be called until after initialise.
Implements tracktion_graph::Node.
References tracktion_graph::NodeProperties::hasAudio, tracktion_graph::hash_combine(), tracktion_graph::NodeProperties::hasMidi, tracktion_graph::NodeProperties::latencyNumSamples, tracktion_graph::NodeProperties::nodeID, and tracktion_graph::NodeProperties::numberOfChannels.
Referenced by prepareToPlay().
getDirectInputNodes()
std::vector<Node*> tracktion_graph::SummingNode::getDirectInputNodes () override virtual
Should return all the inputs directly feeding in to this node.
Reimplemented from tracktion_graph::Node.
transform()
bool tracktion_graph::SummingNode::transform (Node &) override virtual
Called after construction to give the node a chance to modify its topology.
This should return true if any changes were made to the topology as this indicates that the method may need to be called again after other nodes have had their toplogy changed.
Reimplemented from tracktion_graph::Node.
prepareToPlay()
void tracktion_graph::SummingNode::prepareToPlay (const PlaybackInitialisationInfo &) override virtual
Called once before playback begins for each node.
Use this to allocate buffers etc. This step can be used to modify the topology of the graph (i.e. add/remove nodes). However, if you do this, you must make sure to call initialise on them so they are fully prepared for processing.
Reimplemented from tracktion_graph::Node.
References tracktion_graph::PlaybackInitialisationInfo::blockSize, getNodeProperties(), and tracktion_graph::NodeProperties::numberOfChannels.
isReadyToProcess()
bool tracktion_graph::SummingNode::isReadyToProcess () override virtual
Should return true when this node is ready to be processed.
This is usually when its input's output buffers are ready.
Implements tracktion_graph::Node.
process()
void tracktion_graph::SummingNode::process (ProcessContext &) override virtual
Called when the node is to be processed.
This should add in to the buffers available making sure not to change their size at all.
Implements tracktion_graph::Node.
The documentation for this class was generated from the following file:
tracktion_graph_SummingNode.h