TracktionEngine: tracktion_engine::MarkerClip Class Reference
tracktion_engine::MarkerClip Class Reference
tracktion_engine » model
Public Member Functions
MarkerClip (const juce::ValueTree &, EditItemID, ClipTrack &targetTrack)
~MarkerClip () override
int getMarkerID ()
void setMarkerID (int newID)
bool isSyncAbsolute () const noexcept
bool isSyncBarsBeats () const noexcept
juce::String getSelectableDescription () override
Subclasses must return a description of what they are.
bool canGoOnTrack (Track &) override
juce::Colour getColour () const override
juce::Colour getDefaultColour () const override
void initialise () override
bool isMidi () const override
bool isMuted () const override
AudioNode * createAudioNode (const CreateAudioNodeParams &) override
Public Member Functions inherited from tracktion_engine::Clip
Clip (const juce::ValueTree &, ClipTrack &, EditItemID, Type)
~Clip () override
virtual void flushStateToValueTree ()
virtual void sourceMediaChanged ()
this is called when the source media file reference (attribute "source") has changed - i.e.
virtual void pitchTempoTrackChanged ()
virtual juce::String getName () override
void setName (const juce::String &newName)
virtual bool usesSourceFile ()
true if it references a source file - i.e.
SourceFileReference & getSourceFileReference ()
Returns the SourceFileReference of the Clip.
juce::File getCurrentSourceFile () const
Returns the current source file, this is different to the SourceFileReference as it could be a temporary comp file, clipFX, reverse render etc.
juce::Array< ReferencedItem > getReferencedItems () override
void reassignReferencedItem (const ReferencedItem &, ProjectItemID, double) override
ClipPosition getPosition () const override
double getContentBeatAtTime (double time) const
Returns the beat number (with offset) at the given time.
double getTimeOfContentBeat (double beat) const
Returns time of a beat number.
virtual double getMaximumLength ()
virtual juce::Array< double > getInterestingTimes ()
Returns times for snapping to, relative to the edit.
double getSpottingPoint () const
virtual bool canLoop () const
virtual bool isLooping () const
virtual bool beatBasedLooping () const
virtual void setNumberOfLoops (int)
virtual void disableLooping ()
virtual double getLoopStartBeats () const
virtual double getLoopStart () const
virtual double getLoopLengthBeats () const
virtual double getLoopLength () const
virtual void setLoopRange (EditTimeRange newLoopRange)
virtual void setLoopRangeBeats (juce::Range< double > newBeatRange)
virtual void setMuted (bool)
virtual void setSyncType (SyncType sync)
SyncType getSyncType () const
void setPosition (ClipPosition newPosition)
void setStart (double newStart, bool preserveSync, bool keepLength)
void setLength (double newLength, bool preserveSync)
void setEnd (double newEnd, bool preserveSync)
void setOffset (double newOffset)
void trimAwayOverlap (EditTimeRange editRangeToTrim)
trims away any part of the clip that overlaps this region.
void removeFromParentTrack ()
bool moveToTrack (Track &)
double getSpeedRatio () const noexcept
virtual void setSpeedRatio (double)
virtual void rescale (double pivotTimeInEdit, double factor)
bool isGrouped () const override
TrackItem * getGroupParent () const override
void setGroup (EditItemID newGroupID)
EditItemID getGroupID () const noexcept
CollectionClip * getGroupClip () const
bool isLinked () const
void setLinkGroupID (EditItemID newLinkID)
EditItemID getLinkGroupID () const
ClipTrack * getClipTrack () const
Track * getTrack () const override
void setColour (juce::Colour col)
virtual void removePlugin (const Plugin::Ptr &)
if the clip can contain plugins, it should implement this
virtual bool addClipPlugin (const Plugin::Ptr &, SelectionManager &)
returns false if the clip can't do this
virtual Plugin::Array getAllPlugins ()
virtual void sendMirrorUpdateToAllPlugins (Plugin &) const
virtual PluginList * getPluginList ()
virtual void clearTakes ()
virtual bool hasAnyTakes () const
virtual juce::StringArray getTakeDescriptions () const
virtual void setCurrentTake (int)
virtual int getCurrentTake () const
virtual int getNumTakes (bool)
virtual bool isCurrentTakeComp ()
virtual void setShowingTakes (bool shouldShow)
virtual bool isShowingTakes () const
virtual Clip::Array unpackTakes (bool)
virtual void cloneFrom (Clip *)
void updateLinkedClips ()
void showLoopMenu ()
virtual PatternGenerator * getPatternGenerator ()
void changed () override
This should be called to send a change notification to any SelectableListeners that are registered with this object.
juce::UndoManager * getUndoManager () const
Public Member Functions inherited from tracktion_engine::TrackItem
TrackItem (Edit &, EditItemID, Type)
~TrackItem ()
EditTimeRange getEditTimeRange () const
double getStartBeat () const
double getContentStartBeat () const
double getEndBeat () const
double getLengthInBeats () const
double getTimeOfRelativeBeat (double beat) const
double getBeatOfRelativeTime (double t) const
double getOffsetInBeats () const
EditItemID getTrackID () const
Public Member Functions inherited from tracktion_engine::EditItem
EditItem (EditItemID, Edit &)
virtual ~EditItem ()=default
Public Member Functions inherited from tracktion_engine::Selectable
Selectable ()
virtual ~Selectable ()
virtual void selectionStatusChanged (bool isNowSelected)
Can be overridden to tell this object that it has just been selected or deselected.
virtual void selectableAboutToBeDeleted ()
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void addSelectableListener (SelectableListener *)
void removeSelectableListener (SelectableListener *)
void cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
void deselect ()
void propertiesChanged ()
void notifyListenersOfDeletion ()
WeakRef getWeakRef ()
Public Member Functions inherited from tracktion_engine::Exportable
virtual ~Exportable ()=default
Protected Member Functions
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
Protected Member Functions inherited from tracktion_engine::Clip
void setCurrentSourceFile (const juce::File &)
virtual void setTrack (ClipTrack *)
void updateParentTrack ()
virtual juce::Array< double > getRescaledMarkPoints () const
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeChildAdded (juce::ValueTree &, juce::ValueTree &) override
void valueTreeChildRemoved (juce::ValueTree &, juce::ValueTree &, int) override
void valueTreeChildOrderChanged (juce::ValueTree &, int, int) override
void valueTreeParentChanged (juce::ValueTree &) override
Additional Inherited Members
Public Types inherited from tracktion_engine::Clip
enum SyncType { syncBarsBeats = 0, syncAbsolute }
using Ptr = juce::ReferenceCountedObjectPtr< Clip >
using Array = juce::ReferenceCountedArray< Clip >
Public Types inherited from tracktion_engine::TrackItem
enum Type {
Type::unknown, Type::wave, Type::midi, Type::edit,
Type::step, Type::marker, Type::pitch, Type::timeSig,
Type::collection, Type::video, Type::recording, Type::chord,
Type::arranger
}
Public Types inherited from tracktion_engine::Selectable
using WeakRef = juce::WeakReference< Selectable >
Static Public Member Functions inherited from tracktion_engine::Clip
static bool isClipState (const juce::ValueTree &)
Checks whether a ValueTree is some kind of clip state.
static bool isClipState (const juce::Identifier &)
Checks whether a ValueTree type is some kind of clip state.
static Ptr createClipForState (const juce::ValueTree &, ClipTrack &targetTrack)
Creates a clip for a given ValueTree representation.
Static Public Member Functions inherited from tracktion_engine::TrackItem
static const char * typeToString (Type)
static juce::Identifier clipTypeToXMLType (Type)
static TrackItem::Type xmlTagToType (juce::StringRef)
static TrackItem::Type stringToType (const juce::String &)
static juce::String getSuggestedNameForNewItem (Type)
template<typename ArrayType >
static void sortByTime (ArrayType &items)
template<typename ArrayType >
static void stableSortByTime (ArrayType &items)
Static Public Member Functions inherited from tracktion_engine::Selectable
static void initialise ()
static bool isSelectableValid (const Selectable *) noexcept
checks whether this object has been deleted.
Static Public Member Functions inherited from tracktion_engine::Exportable
static juce::Array< Exportable * > addAllExportables (Edit &)
Returns all the Exportables contained in an Edit.
Public Attributes inherited from tracktion_engine::Clip
juce::ValueTree state
juce::CachedValue< juce::Colour > colour
Public Attributes inherited from tracktion_engine::TrackItem
const Type type
Public Attributes inherited from tracktion_engine::EditItem
Edit & edit
const EditItemID itemID
Every EditItem has an ID which is unique within the edit.
Public Attributes inherited from tracktion_engine::Selectable
WeakRef::Master masterReference
Protected Attributes inherited from tracktion_engine::Clip
bool isInitialised = false
bool cloneInProgress = false
juce::CachedValue< juce::String > clipName
ClipTrack * track = nullptr
juce::CachedValue< double > clipStart
juce::CachedValue< double > length
juce::CachedValue< double > offset
juce::CachedValue< double > speedRatio
SourceFileReference sourceFileReference
juce::CachedValue< EditItemID > groupID
juce::CachedValue< EditItemID > linkID
juce::File currentSourceFile
juce::CachedValue< SyncType > syncType
juce::CachedValue< bool > showingTakes
std::unique_ptr< PatternGenerator > patternGenerator
AsyncCaller updateLinkedClipsCaller
Constructor & Destructor Documentation
MarkerClip()
tracktion_engine::MarkerClip::MarkerClip (const juce::ValueTree & , EditItemID , ClipTrack & targetTrack)
~MarkerClip()
tracktion_engine::MarkerClip::~MarkerClip () override
Member Function Documentation
getMarkerID()
int tracktion_engine::MarkerClip::getMarkerID ()
References setMarkerID().
setMarkerID()
void tracktion_engine::MarkerClip::setMarkerID (int newID)
Referenced by getMarkerID().
isSyncAbsolute()
bool tracktion_engine::MarkerClip::isSyncAbsolute () const noexcept
References tracktion_engine::Clip::syncAbsolute, and tracktion_engine::Clip::syncType.
isSyncBarsBeats()
bool tracktion_engine::MarkerClip::isSyncBarsBeats () const noexcept
References canGoOnTrack(), getColour(), getDefaultColour(), getSelectableDescription(), initialise(), tracktion_engine::Clip::syncBarsBeats, and tracktion_engine::Clip::syncType.
getSelectableDescription()
juce::String tracktion_engine::MarkerClip::getSelectableDescription () override virtual
Subclasses must return a description of what they are.
Implements tracktion_engine::Selectable.
Referenced by isSyncBarsBeats().
canGoOnTrack()
bool tracktion_engine::MarkerClip::canGoOnTrack (Track &) override virtual
Implements tracktion_engine::Clip.
Referenced by isSyncBarsBeats().
getColour()
juce::Colour tracktion_engine::MarkerClip::getColour () const override virtual
Reimplemented from tracktion_engine::Clip.
Referenced by isSyncBarsBeats().
getDefaultColour()
juce::Colour tracktion_engine::MarkerClip::getDefaultColour () const override virtual
Implements tracktion_engine::Clip.
Referenced by isSyncBarsBeats().
initialise()
void tracktion_engine::MarkerClip::initialise () override virtual
Reimplemented from tracktion_engine::Clip.
Referenced by isSyncBarsBeats().
isMidi()
bool tracktion_engine::MarkerClip::isMidi () const override virtual
Implements tracktion_engine::Clip.
isMuted()
bool tracktion_engine::MarkerClip::isMuted () const override virtual
Implements tracktion_engine::Clip.
createAudioNode()
AudioNode* tracktion_engine::MarkerClip::createAudioNode (const CreateAudioNodeParams &) override virtual
Implements tracktion_engine::Clip.
References valueTreePropertyChanged().
valueTreePropertyChanged()
void tracktion_engine::MarkerClip::valueTreePropertyChanged (juce::ValueTree & , const juce::Identifier &) override protected
Referenced by createAudioNode().
The documentation for this class was generated from the following file:
tracktion_MarkerClip.h