TracktionEngine: tracktion::engine::PlayHead Class Reference
tracktion::engine::PlayHead Class Reference
Classes
struct EditTimeWindow
Public Member Functions
PlayHead ()=default
void setPosition (double newTime)
void play (legacy::EditTimeRange rangeToPlay, bool looped)
void play ()
void playLockedToEngine (legacy::EditTimeRange rangeToPlay)
void stop ()
void setUserIsDragging (bool b)
bool isUserDragging () const
juce::Time getLastUserInteractionTime () const
double streamTimeToSourceTime (double streamTime) const
double streamTimeToSourceTimeUnlooped (double streamTime) const
EditTimeWindow streamTimeToEditWindow (legacy::EditTimeRange streamTime) const
double getPosition () const
double getUnloopedPosition () const
void overridePosition (double newTime)
bool isPlaying () const noexcept
bool isStopped () const noexcept
bool isLooping () const noexcept
bool isRollingIntoLoop () const noexcept
legacy::EditTimeRange getLoopTimes () const noexcept
void setLoopTimes (bool loop, legacy::EditTimeRange times)
void setRollInToLoop (double t)
void deviceManagerPositionUpdate (double newTime, double newTimeEnd)
called by the DeviceManager
Static Public Member Functions
static double linearTimeToLoopTime (double time, legacy::EditTimeRange loop)
static double linearTimeToLoopTime (double time, double loopStart, double loopLen)
Constructor & Destructor Documentation
PlayHead()
tracktion::engine::PlayHead::PlayHead () default
Member Function Documentation
setPosition()
void tracktion::engine::PlayHead::setPosition (double newTime)
References getPosition(), and overridePosition().
Referenced by play(), setLoopTimes(), and stop().
play() [1/2]
void tracktion::engine::PlayHead::play (legacy::EditTimeRange rangeToPlay, bool looped)
References tracktion::engine::legacy::EditTimeRange::getLength(), setPosition(), and tracktion::engine::legacy::EditTimeRange::start.
play() [2/2]
void tracktion::engine::PlayHead::play ()
References getPosition(), and setPosition().
Referenced by playLockedToEngine().
playLockedToEngine()
void tracktion::engine::PlayHead::playLockedToEngine (legacy::EditTimeRange rangeToPlay)
References play().
stop()
void tracktion::engine::PlayHead::stop ()
References getPosition(), and setPosition().
setUserIsDragging()
void tracktion::engine::PlayHead::setUserIsDragging (bool b)
isUserDragging()
bool tracktion::engine::PlayHead::isUserDragging () const
Referenced by tracktion::engine::PluginAudioNode::createPluginRenderContext(), and tracktion::engine::SubSampleWaveAudioNode::renderSection().
getLastUserInteractionTime()
juce::Time tracktion::engine::PlayHead::getLastUserInteractionTime () const
streamTimeToSourceTime()
double tracktion::engine::PlayHead::streamTimeToSourceTime (double streamTime) const
References linearTimeToLoopTime(), and streamTimeToSourceTimeUnlooped().
Referenced by getPosition().
streamTimeToSourceTimeUnlooped()
double tracktion::engine::PlayHead::streamTimeToSourceTimeUnlooped (double streamTime) const
Referenced by getUnloopedPosition(), streamTimeToEditWindow(), and streamTimeToSourceTime().
linearTimeToLoopTime() [1/2]
static double tracktion::engine::PlayHead::linearTimeToLoopTime (double time, legacy::EditTimeRange loop) static
References tracktion::engine::legacy::EditTimeRange::getLength(), and tracktion::engine::legacy::EditTimeRange::start.
Referenced by streamTimeToEditWindow(), and streamTimeToSourceTime().
linearTimeToLoopTime() [2/2]
static double tracktion::engine::PlayHead::linearTimeToLoopTime (double time, double loopStart, double loopLen) static
streamTimeToEditWindow()
EditTimeWindow tracktion::engine::PlayHead::streamTimeToEditWindow (legacy::EditTimeRange streamTime) const
References tracktion::engine::legacy::EditTimeRange::end, getLoopTimes(), linearTimeToLoopTime(), tracktion::engine::legacy::EditTimeRange::start, and streamTimeToSourceTimeUnlooped().
getPosition()
double tracktion::engine::PlayHead::getPosition () const
References streamTimeToSourceTime().
Referenced by deviceManagerPositionUpdate(), play(), setLoopTimes(), setPosition(), and stop().
getUnloopedPosition()
double tracktion::engine::PlayHead::getUnloopedPosition () const
References streamTimeToSourceTimeUnlooped().
overridePosition()
void tracktion::engine::PlayHead::overridePosition (double newTime)
References tracktion::engine::legacy::EditTimeRange::clipValue(), and tracktion::engine::legacy::EditTimeRange::end.
Referenced by setPosition().
isPlaying()
bool tracktion::engine::PlayHead::isPlaying () const noexcept
Referenced by tracktion::engine::PluginAudioNode::createPluginRenderContext().
isStopped()
bool tracktion::engine::PlayHead::isStopped () const noexcept
isLooping()
bool tracktion::engine::PlayHead::isLooping () const noexcept
Referenced by tracktion::engine::AudioNode::invokeSplitRender().
isRollingIntoLoop()
bool tracktion::engine::PlayHead::isRollingIntoLoop () const noexcept
Referenced by tracktion::engine::AudioNode::invokeSplitRender().
getLoopTimes()
legacy::EditTimeRange tracktion::engine::PlayHead::getLoopTimes () const noexcept
Referenced by tracktion::engine::AudioNode::invokeSplitRender(), setLoopTimes(), and streamTimeToEditWindow().
setLoopTimes()
void tracktion::engine::PlayHead::setLoopTimes (bool loop, legacy::EditTimeRange times)
References getLoopTimes(), getPosition(), and setPosition().
setRollInToLoop()
void tracktion::engine::PlayHead::setRollInToLoop (double t)
References tracktion::engine::legacy::EditTimeRange::end.
deviceManagerPositionUpdate()
void tracktion::engine::PlayHead::deviceManagerPositionUpdate (double newTime, double newTimeEnd)
called by the DeviceManager
References getPosition(), and tracktion::engine::legacy::EditTimeRange::start.
The documentation for this class was generated from the following file:
tracktion_engine/playback/audionodes/tracktion_PlayHead.h