TracktionEngine: tracktion_engine::TempoSequence Class Reference
tracktion_engine::TempoSequence Class Reference
tracktion_engine » model
Holds a list of TempoSetting objects, to form a sequence of tempo changes.
Classes
struct BarsAndBeats
struct SectionDetails
struct TempoSections
Public Member Functions
TempoSequence (Edit &)
~TempoSequence () override
Edit & getEdit () const
const juce::ValueTree & getState () const
void setState (const juce::ValueTree &)
void createEmptyState ()
void copyFrom (const TempoSequence &)
void freeResources ()
juce::UndoManager * getUndoManager () const noexcept
const juce::Array< TimeSigSetting * > & getTimeSigs () const
int getNumTimeSigs () const
TimeSigSetting * getTimeSig (int index) const
TimeSigSetting & getTimeSigAt (double time) const
TimeSigSetting & getTimeSigAtBeat (double beat) const
int indexOfTimeSigAt (double time) const
int indexOfTimeSig (const TimeSigSetting *) const
const juce::Array< TempoSetting * > & getTempos () const
int getNumTempos () const
TempoSetting * getTempo (int index) const
TempoSetting & getTempoAt (double time) const
TempoSetting & getTempoAtBeat (double beat) const
double getBpmAt (double time) const
double getBeatsPerSecondAt (double time) const
bool isTripletsAtTime (double time) const
int indexOfTempoAt (double t) const
int indexOfNextTempoAt (double t) const
int indexOfTempo (const TempoSetting *) const
int countTemposInRegion (EditTimeRange range) const
juce::int64 createHashForTemposInRange (EditTimeRange) const
TempoSetting::Ptr insertTempo (double time)
inserts a tempo break that can be edited later.
TempoSetting::Ptr insertTempo (double beatNum, double bpm, float curve)
TimeSigSetting::Ptr insertTimeSig (double time)
void removeTempo (int index, bool remapEdit)
void removeTemposBetween (EditTimeRange, bool remapEdit)
void removeTimeSig (int index)
void removeTimeSigsBetween (EditTimeRange)
void moveTempoStart (int index, double deltaBeats, bool snapToBeat)
void moveTimeSigStart (int index, double deltaBeats, bool snapToBeat)
void insertSpaceIntoSequence (double time, double amountOfSpaceInSeconds, bool snapToBeat)
Inserts space in to a sequence, shifting TempoSettings and TimeSigs.
void deleteRegion (EditTimeRange)
Removes a region in a sequence, shifting TempoSettings and TimeSigs.
double timeToBeats (double time) const
juce::Range< double > timeToBeats (EditTimeRange timeRange) const
BarsAndBeats timeToBarsBeats (double time) const
double barsBeatsToTime (BarsAndBeats) const
double barsBeatsToBeats (BarsAndBeats) const
double beatsToTime (double beats) const
EditTimeRange beatsToTime (juce::Range< double > beatsRange) const
const TempoSections & getTempoSections ()
juce::String getSelectableDescription () override
Subclasses must return a description of what they are.
void updateTempoData ()
Public Member Functions inherited from tracktion_engine::Selectable
Selectable ()
virtual ~Selectable ()
virtual void selectionStatusChanged (bool isNowSelected)
Can be overridden to tell this object that it has just been selected or deselected.
virtual void changed ()
This should be called to send a change notification to any SelectableListeners that are registered with this object.
virtual void selectableAboutToBeDeleted ()
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void addSelectableListener (SelectableListener *)
void removeSelectableListener (SelectableListener *)
void cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
void deselect ()
void propertiesChanged ()
void notifyListenersOfDeletion ()
WeakRef getWeakRef ()
Public Attributes
Edit & edit
Public Attributes inherited from tracktion_engine::Selectable
WeakRef::Master masterReference
Additional Inherited Members
Public Types inherited from tracktion_engine::Selectable
using WeakRef = juce::WeakReference< Selectable >
Static Public Member Functions inherited from tracktion_engine::Selectable
static void initialise ()
static bool isSelectableValid (const Selectable *) noexcept
checks whether this object has been deleted.
Detailed Description
Holds a list of TempoSetting objects, to form a sequence of tempo changes.
You can query this at particular points, but it's wise to use a TempoSequencePosition object to iterate it.
Constructor & Destructor Documentation
TempoSequence()
tracktion_engine::TempoSequence::TempoSequence (Edit &)
~TempoSequence()
tracktion_engine::TempoSequence::~TempoSequence () override
Member Function Documentation
getEdit()
Edit& tracktion_engine::TempoSequence::getEdit () const
References edit.
getState()
const juce::ValueTree& tracktion_engine::TempoSequence::getState () const
References copyFrom(), createEmptyState(), freeResources(), getBpmAt(), getNumTempos(), getNumTimeSigs(), getTempo(), getTempoAt(), getTempoAtBeat(), getTempos(), getTimeSig(), getTimeSigAt(), getTimeSigAtBeat(), getTimeSigs(), getUndoManager(), indexOfTimeSig(), indexOfTimeSigAt(), and setState().
setState()
void tracktion_engine::TempoSequence::setState (const juce::ValueTree &)
Referenced by getState().
createEmptyState()
void tracktion_engine::TempoSequence::createEmptyState ()
Referenced by getState().
copyFrom()
void tracktion_engine::TempoSequence::copyFrom (const TempoSequence &)
Referenced by getState().
freeResources()
void tracktion_engine::TempoSequence::freeResources ()
Referenced by getState().
getUndoManager()
juce::UndoManager* tracktion_engine::TempoSequence::getUndoManager () const noexcept
Referenced by getState().
getTimeSigs()
const juce::Array<TimeSigSetting*>& tracktion_engine::TempoSequence::getTimeSigs () const
Referenced by getState().
getNumTimeSigs()
int tracktion_engine::TempoSequence::getNumTimeSigs () const
Referenced by getState().
getTimeSig()
TimeSigSetting* tracktion_engine::TempoSequence::getTimeSig (int index) const
Referenced by getState().
getTimeSigAt()
TimeSigSetting& tracktion_engine::TempoSequence::getTimeSigAt (double time) const
Referenced by getState().
getTimeSigAtBeat()
TimeSigSetting& tracktion_engine::TempoSequence::getTimeSigAtBeat (double beat) const
Referenced by getState().
indexOfTimeSigAt()
int tracktion_engine::TempoSequence::indexOfTimeSigAt (double time) const
Referenced by getState().
indexOfTimeSig()
int tracktion_engine::TempoSequence::indexOfTimeSig (const TimeSigSetting *) const
Referenced by getState().
getTempos()
const juce::Array<TempoSetting*>& tracktion_engine::TempoSequence::getTempos () const
Referenced by getState().
getNumTempos()
int tracktion_engine::TempoSequence::getNumTempos () const
Referenced by getState().
getTempo()
TempoSetting* tracktion_engine::TempoSequence::getTempo (int index) const
Referenced by getState().
getTempoAt()
TempoSetting& tracktion_engine::TempoSequence::getTempoAt (double time) const
Referenced by getState().
getTempoAtBeat()
TempoSetting& tracktion_engine::TempoSequence::getTempoAtBeat (double beat) const
Referenced by getState().
getBpmAt()
double tracktion_engine::TempoSequence::getBpmAt (double time) const
Referenced by getBeatsPerSecondAt(), and getState().
getBeatsPerSecondAt()
double tracktion_engine::TempoSequence::getBeatsPerSecondAt (double time) const
References countTemposInRegion(), createHashForTemposInRange(), deleteRegion(), getBpmAt(), indexOfNextTempoAt(), indexOfTempo(), indexOfTempoAt(), insertSpaceIntoSequence(), insertTempo(), insertTimeSig(), isTripletsAtTime(), moveTempoStart(), moveTimeSigStart(), removeTempo(), removeTemposBetween(), removeTimeSig(), removeTimeSigsBetween(), and timeToBeats().
isTripletsAtTime()
bool tracktion_engine::TempoSequence::isTripletsAtTime (double time) const
Referenced by getBeatsPerSecondAt().
indexOfTempoAt()
int tracktion_engine::TempoSequence::indexOfTempoAt (double t) const
Referenced by getBeatsPerSecondAt().
indexOfNextTempoAt()
int tracktion_engine::TempoSequence::indexOfNextTempoAt (double t) const
Referenced by getBeatsPerSecondAt().
indexOfTempo()
int tracktion_engine::TempoSequence::indexOfTempo (const TempoSetting *) const
Referenced by getBeatsPerSecondAt().
countTemposInRegion()
int tracktion_engine::TempoSequence::countTemposInRegion (EditTimeRange range) const
Referenced by getBeatsPerSecondAt().
createHashForTemposInRange()
juce::int64 tracktion_engine::TempoSequence::createHashForTemposInRange (EditTimeRange) const
Referenced by getBeatsPerSecondAt().
insertTempo() [1/2]
TempoSetting::Ptr tracktion_engine::TempoSequence::insertTempo (double time)
inserts a tempo break that can be edited later.
Referenced by getBeatsPerSecondAt().
insertTempo() [2/2]
TempoSetting::Ptr tracktion_engine::TempoSequence::insertTempo (double beatNum, double bpm, float curve)
insertTimeSig()
TimeSigSetting::Ptr tracktion_engine::TempoSequence::insertTimeSig (double time)
Referenced by getBeatsPerSecondAt().
removeTempo()
void tracktion_engine::TempoSequence::removeTempo (int index, bool remapEdit)
Referenced by getBeatsPerSecondAt().
removeTemposBetween()
void tracktion_engine::TempoSequence::removeTemposBetween (EditTimeRange , bool remapEdit)
Referenced by getBeatsPerSecondAt().
removeTimeSig()
void tracktion_engine::TempoSequence::removeTimeSig (int index)
Referenced by getBeatsPerSecondAt().
removeTimeSigsBetween()
void tracktion_engine::TempoSequence::removeTimeSigsBetween (EditTimeRange)
Referenced by getBeatsPerSecondAt().
moveTempoStart()
void tracktion_engine::TempoSequence::moveTempoStart (int index, double deltaBeats, bool snapToBeat)
Referenced by getBeatsPerSecondAt().
moveTimeSigStart()
void tracktion_engine::TempoSequence::moveTimeSigStart (int index, double deltaBeats, bool snapToBeat)
Referenced by getBeatsPerSecondAt().
insertSpaceIntoSequence()
void tracktion_engine::TempoSequence::insertSpaceIntoSequence (double time, double amountOfSpaceInSeconds, bool snapToBeat)
Inserts space in to a sequence, shifting TempoSettings and TimeSigs.
Referenced by getBeatsPerSecondAt().
deleteRegion()
void tracktion_engine::TempoSequence::deleteRegion (EditTimeRange)
Removes a region in a sequence, shifting TempoSettings and TimeSigs.
Referenced by getBeatsPerSecondAt().
timeToBeats() [1/2]
double tracktion_engine::TempoSequence::timeToBeats (double time) const
Referenced by getBeatsPerSecondAt().
timeToBeats() [2/2]
juce::Range<double> tracktion_engine::TempoSequence::timeToBeats (EditTimeRange timeRange) const
timeToBarsBeats()
BarsAndBeats tracktion_engine::TempoSequence::timeToBarsBeats (double time) const
barsBeatsToTime()
double tracktion_engine::TempoSequence::barsBeatsToTime (BarsAndBeats) const
barsBeatsToBeats()
double tracktion_engine::TempoSequence::barsBeatsToBeats (BarsAndBeats) const
beatsToTime() [1/2]
double tracktion_engine::TempoSequence::beatsToTime (double beats) const
beatsToTime() [2/2]
EditTimeRange tracktion_engine::TempoSequence::beatsToTime (juce::Range< double > beatsRange) const
getTempoSections()
const TempoSections& tracktion_engine::TempoSequence::getTempoSections ()
References getSelectableDescription().
getSelectableDescription()
juce::String tracktion_engine::TempoSequence::getSelectableDescription () override virtual
Subclasses must return a description of what they are.
Implements tracktion_engine::Selectable.
Referenced by getTempoSections().
updateTempoData()
void tracktion_engine::TempoSequence::updateTempoData ()
Member Data Documentation
edit
Edit& tracktion_engine::TempoSequence::edit
Referenced by getEdit().
The documentation for this class was generated from the following file:
tracktion_TempoSequence.h