TracktionEngine: tracktion_engine::Clipboard Class Reference
tracktion_engine::Clipboard Class Reference
Inherits DeletedAtShutdown.
Classes
struct AutomationPoints
struct Clips
struct ContentType
struct MIDIEvents
struct Modifiers
struct Pitches
struct Plugins
struct ProjectItems
struct Takes
struct TempoChanges
struct TimeSigs
struct Tracks
Public Member Functions
Clipboard ()
~Clipboard ()
void clear ()
bool isEmpty () const
void setContent (std::unique_ptr< ContentType > newContent)
const ContentType * getContent () const
template<typename Type , typename... Args>
void makeContent (Args &&... args)
template<typename Type >
const Type * getContentWithType () const
template<typename Type >
bool hasContentWithType () const
void addListener (juce::ChangeListener *)
void removeListener (juce::ChangeListener *)
Constructor & Destructor Documentation
Clipboard()
tracktion_engine::Clipboard::Clipboard ()
~Clipboard()
tracktion_engine::Clipboard::~Clipboard ()
Member Function Documentation
clear()
void tracktion_engine::Clipboard::clear ()
isEmpty()
bool tracktion_engine::Clipboard::isEmpty () const
setContent()
void tracktion_engine::Clipboard::setContent (std::unique_ptr< ContentType > newContent)
Referenced by makeContent().
getContent()
const ContentType* tracktion_engine::Clipboard::getContent () const
Referenced by getContentWithType().
makeContent()
template<typename Type , typename... Args> void tracktion_engine::Clipboard::makeContent (Args &&... args)
References setContent().
getContentWithType()
template<typename Type > const Type* tracktion_engine::Clipboard::getContentWithType () const
References getContent().
hasContentWithType()
template<typename Type > bool tracktion_engine::Clipboard::hasContentWithType () const
addListener()
void tracktion_engine::Clipboard::addListener (juce::ChangeListener *)
removeListener()
void tracktion_engine::Clipboard::removeListener (juce::ChangeListener *)
The documentation for this class was generated from the following file:
tracktion_Clipboard.h