TracktionEngine: tracktion::engine::SubSampleWaveAudioNode Class Reference
tracktion::engine::SubSampleWaveAudioNode Class Reference
Public Member Functions
SubSampleWaveAudioNode (Engine &e, const AudioFile &af, legacy::EditTimeRange editTime, double off, legacy::EditTimeRange loop, LiveClipLevel level, double speed, const juce::AudioChannelSet &channels)
void getAudioNodeProperties (AudioNodeProperties &info) override
void visitNodes (const VisitorFn &v) override
bool purgeSubNodes (bool keepAudio, bool) override
Tells the node to delete any sub-nodes that don't produce the required type of output.
void prepareAudioNodeToPlay (const PlaybackInitialisationInfo &info) override
tells the node to initialise itself ready for playing from the given time.
bool isReadyToRender () override
void releaseAudioNodeResources () override
tells the node that play has stopped, and it can free up anything it no longer needs.
void renderOver (const AudioRenderContext &rc) override
void renderAdding (const AudioRenderContext &rc) override
void prepareForNextBlock (const AudioRenderContext &rc) override
void renderSection (const AudioRenderContext &rc, legacy::EditTimeRange editTime)
Public Member Functions inherited from tracktion::engine::AudioNode
AudioNode ()
virtual ~AudioNode ()
virtual juce::ReferenceCountedObjectPtr< Plugin > getPlugin () const
void callRenderAdding (const AudioRenderContext &)
void callRenderOver (const AudioRenderContext &)
Public Attributes
Engine & engine
Additional Inherited Members
Public Types inherited from tracktion::engine::AudioNode
using VisitorFn = std::function< void(AudioNode &)>
Static Public Member Functions inherited from tracktion::engine::AudioNode
template<typename CallbackType >
static void invokeSplitRender (const AudioRenderContext &rc, CallbackType &target)
Constructor & Destructor Documentation
SubSampleWaveAudioNode()
tracktion::engine::SubSampleWaveAudioNode::SubSampleWaveAudioNode (Engine & e, const AudioFile & af, legacy::EditTimeRange editTime, double off, legacy::EditTimeRange loop, LiveClipLevel level, double speed, const juce::AudioChannelSet & channels)
Member Function Documentation
getAudioNodeProperties()
void tracktion::engine::SubSampleWaveAudioNode::getAudioNodeProperties (AudioNodeProperties & info) override virtual
Implements tracktion::engine::AudioNode.
References tracktion::engine::AudioFile::getNumChannels(), tracktion::engine::AudioNodeProperties::hasAudio, tracktion::engine::AudioNodeProperties::hasMidi, and tracktion::engine::AudioNodeProperties::numberOfChannels.
visitNodes()
void tracktion::engine::SubSampleWaveAudioNode::visitNodes (const VisitorFn & v) override virtual
Implements tracktion::engine::AudioNode.
purgeSubNodes()
bool tracktion::engine::SubSampleWaveAudioNode::purgeSubNodes (bool keepAudio, bool keepMidi) override virtual
Tells the node to delete any sub-nodes that don't produce the required type of output.
This optimises out any unplayable bits of the audio graph. Returns true if this node should be kept, false if this node can itself be deleted.
Implements tracktion::engine::AudioNode.
prepareAudioNodeToPlay()
void tracktion::engine::SubSampleWaveAudioNode::prepareAudioNodeToPlay (const PlaybackInitialisationInfo &) override virtual
tells the node to initialise itself ready for playing from the given time.
This call may be made more than once before releaseAudioNodeResources() is called
Implements tracktion::engine::AudioNode.
References tracktion::engine::PlaybackInitialisationInfo::sampleRate.
isReadyToRender()
bool tracktion::engine::SubSampleWaveAudioNode::isReadyToRender () override virtual
Implements tracktion::engine::AudioNode.
References tracktion::engine::AudioFile::isNull().
releaseAudioNodeResources()
void tracktion::engine::SubSampleWaveAudioNode::releaseAudioNodeResources () override virtual
tells the node that play has stopped, and it can free up anything it no longer needs.
Implements tracktion::engine::AudioNode.
renderOver()
void tracktion::engine::SubSampleWaveAudioNode::renderOver (const AudioRenderContext & rc) override virtual
Implements tracktion::engine::AudioNode.
References tracktion::engine::AudioNode::callRenderAdding().
renderAdding()
void tracktion::engine::SubSampleWaveAudioNode::renderAdding (const AudioRenderContext & rc) override virtual
Implements tracktion::engine::AudioNode.
References tracktion::engine::AudioNode::invokeSplitRender().
prepareForNextBlock()
void tracktion::engine::SubSampleWaveAudioNode::prepareForNextBlock (const AudioRenderContext & rc) override virtual
Reimplemented from tracktion::engine::AudioNode.
References tracktion::engine::PlayHead::EditTimeWindow::editRange1, tracktion::engine::AudioRenderContext::getEditTime(), tracktion::engine::legacy::EditTimeRange::getStart(), and SCOPED_REALTIME_CHECK.
renderSection()
void tracktion::engine::SubSampleWaveAudioNode::renderSection (const AudioRenderContext & rc, legacy::EditTimeRange editTime)
References tracktion::engine::AudioScratchBuffer::buffer, tracktion::engine::AudioRenderContext::bufferNumSamples, tracktion::engine::AudioRenderContext::bufferStartSample, tracktion::engine::AudioRenderContext::destBuffer, tracktion::engine::legacy::EditTimeRange::getEnd(), tracktion::engine::LiveClipLevel::getGainIncludingMute(), tracktion::engine::LiveClipLevel::getLeftAndRightGains(), tracktion::engine::legacy::EditTimeRange::getStart(), tracktion::engine::AudioRenderContext::isContiguousWithPreviousBlock(), tracktion::engine::AudioRenderContext::isFirstBlockOfLoop(), tracktion::engine::AudioRenderContext::isRendering, tracktion::engine::PlayHead::isUserDragging(), tracktion::engine::AudioRenderContext::playhead, tracktion::engine::AudioRenderContext::sanityCheck(), and SCOPED_REALTIME_CHECK.
Member Data Documentation
engine
Engine& tracktion::engine::SubSampleWaveAudioNode::engine
The documentation for this class was generated from the following file:
tracktion_SpeedRampAudioNode.h