TracktionEngine: tracktion_engine::Scale Class Reference
tracktion_engine::Scale Class Reference
tracktion_engine » midi
Public Types
enum ScaleType {
major = 0, minor, ionian, dorian,
phrygian, lydian, mixolydian, aeolian,
locrian, melodicMinor, harmonicMinor
}
enum Steps { Whole = 0, Half, WholeHalf }
enum Intervals {
i = 0, ii, iii, iv,
v, vi, vii
}
Public Member Functions
Scale (ScaleType type=major)
ScaleType getType () const
juce::String getName () const
juce::String getShortName () const
juce::Array< int > getSteps (int octaves=1) const
juce::String getIntervalName (Intervals interval) const
juce::Array< Chord > getTriads () const
juce::Array< Chord > getSixths () const
juce::Array< Chord > getSevenths () const
Static Public Member Functions
static juce::StringArray getIntervalNames ()
static juce::Array< ScaleType > getAllScaleTypes ()
static juce::StringArray getScaleStrings ()
static juce::String getNameForType (ScaleType type)
static juce::String getShortNameForType (ScaleType type)
static ScaleType getTypeFromName (juce::String name)
Member Enumeration Documentation
ScaleType
enum tracktion_engine::Scale::ScaleType
Enumerator
major
minor
ionian
dorian
phrygian
lydian
mixolydian
aeolian
locrian
melodicMinor
harmonicMinor
Steps
enum tracktion_engine::Scale::Steps
Enumerator
Whole
Half
WholeHalf
Intervals
enum tracktion_engine::Scale::Intervals
Enumerator
i
ii
iii
iv
v
vi
vii
Constructor & Destructor Documentation
Scale()
tracktion_engine::Scale::Scale (ScaleType type = major)
Member Function Documentation
getType()
ScaleType tracktion_engine::Scale::getType () const
References tracktion_engine::Chord::getName(), tracktion_engine::Chord::getShortName(), and tracktion_engine::Chord::getSteps().
getName()
juce::String tracktion_engine::Scale::getName () const
getShortName()
juce::String tracktion_engine::Scale::getShortName () const
getIntervalNames()
static juce::StringArray tracktion_engine::Scale::getIntervalNames () static
getAllScaleTypes()
static juce::Array<ScaleType> tracktion_engine::Scale::getAllScaleTypes () static
getScaleStrings()
static juce::StringArray tracktion_engine::Scale::getScaleStrings () static
getNameForType()
static juce::String tracktion_engine::Scale::getNameForType (ScaleType type) static
getShortNameForType()
static juce::String tracktion_engine::Scale::getShortNameForType (ScaleType type) static
getTypeFromName()
static ScaleType tracktion_engine::Scale::getTypeFromName (juce::String name) static
getSteps()
juce::Array<int> tracktion_engine::Scale::getSteps (int octaves = 1) const
getIntervalName()
juce::String tracktion_engine::Scale::getIntervalName (Intervals interval) const
getTriads()
juce::Array<Chord> tracktion_engine::Scale::getTriads () const
getSixths()
juce::Array<Chord> tracktion_engine::Scale::getSixths () const
getSevenths()
juce::Array<Chord> tracktion_engine::Scale::getSevenths () const
The documentation for this class was generated from the following file:
tracktion_Musicality.h