TracktionEngine: tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType > Class Template Reference
tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType > Class Template Reference abstract
Inherits Listener.
Public Types
using ScopedLockType = typename CriticalSectionType::ScopedLockType
Public Member Functions
ValueTreeObjectList (const juce::ValueTree &parentTree)
~ValueTreeObjectList () override
int size () const
bool isEmpty () const noexcept
ObjectType * operator[] (int idx) const
ObjectType * at (int idx)
ObjectType ** begin ()
ObjectType *const * begin () const
ObjectType ** end ()
ObjectType *const * end () const
void rebuildObjects ()
void freeObjects ()
virtual bool isSuitableType (const juce::ValueTree &) const =0
virtual ObjectType * createNewObject (const juce::ValueTree &)=0
virtual void deleteObject (ObjectType *)=0
virtual void newObjectAdded (ObjectType *)=0
virtual void objectRemoved (ObjectType *)=0
virtual void objectOrderChanged ()=0
void valueTreeChildAdded (juce::ValueTree &, juce::ValueTree &tree) override
void valueTreeChildRemoved (juce::ValueTree &exParent, juce::ValueTree &tree, int) override
void valueTreeChildOrderChanged (juce::ValueTree &tree, int, int) override
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeParentChanged (juce::ValueTree &) override
void valueTreeRedirected (juce::ValueTree &) override
int compareElements (ObjectType *first, ObjectType *second) const
Public Attributes
juce::Array< ObjectType * > objects
CriticalSectionType arrayLock
Protected Member Functions
void deleteAllObjects ()
bool isChildTree (juce::ValueTree &v) const
int indexOf (const juce::ValueTree &v) const noexcept
void sortArray ()
Protected Attributes
juce::ValueTree parent
Member Typedef Documentation
ScopedLockType
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> using tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::ScopedLockType = typename CriticalSectionType::ScopedLockType
Constructor & Destructor Documentation
ValueTreeObjectList()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::ValueTreeObjectList (const juce::ValueTree & parentTree)
~ValueTreeObjectList()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::~ValueTreeObjectList () override
Member Function Documentation
size()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> int tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::size () const
Referenced by tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::isEmpty().
isEmpty()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> bool tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::isEmpty () const noexcept
operator[]()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> ObjectType* tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::operator[] (int idx) const
at()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> ObjectType* tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::at (int idx)
begin() [1/2]
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> ObjectType** tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::begin ()
begin() [2/2]
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> ObjectType* const* tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::begin () const
end() [1/2]
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> ObjectType** tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::end ()
end() [2/2]
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> ObjectType* const* tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::end () const
rebuildObjects()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> void tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::rebuildObjects ()
freeObjects()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> void tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::freeObjects ()
isSuitableType()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> virtual bool tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::isSuitableType (const juce::ValueTree &) const pure virtual
Implemented in tracktion_engine::InputDeviceInstance::InputDeviceDestinationList, tracktion_engine::ClipEffects, tracktion_engine::ModifierList, tracktion_engine::TrackList, and tracktion_engine::TrackCompManager::TrackComp.
Referenced by tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::isChildTree(), tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::rebuildObjects(), and tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::valueTreeChildRemoved().
createNewObject()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> virtual ObjectType* tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::createNewObject (const juce::ValueTree &) pure virtual
Implemented in tracktion_engine::InputDeviceInstance::InputDeviceDestinationList, tracktion_engine::ClipEffects, tracktion_engine::ModifierList, tracktion_engine::TrackList, and tracktion_engine::TrackCompManager::TrackComp.
Referenced by tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::rebuildObjects(), and tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::valueTreeChildAdded().
deleteObject()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> virtual void tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::deleteObject (ObjectType *) pure virtual
Implemented in tracktion_engine::TrackList, tracktion_engine::ModifierList, and tracktion_engine::ClipEffects.
Referenced by tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::deleteAllObjects(), and tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::valueTreeChildRemoved().
newObjectAdded()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> virtual void tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::newObjectAdded (ObjectType *) pure virtual
Implemented in tracktion_engine::TrackList, tracktion_engine::SortedValueTreeObjectList< ObjectType >, tracktion_engine::ModifierList, and tracktion_engine::ClipEffects.
Referenced by tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::valueTreeChildAdded().
objectRemoved()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> virtual void tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objectRemoved (ObjectType *) pure virtual
Implemented in tracktion_engine::TrackList, tracktion_engine::ModifierList, and tracktion_engine::ClipEffects.
Referenced by tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::valueTreeChildRemoved().
objectOrderChanged()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> virtual void tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objectOrderChanged () pure virtual
Implemented in tracktion_engine::SortedValueTreeObjectList< ObjectType >, tracktion_engine::InputDeviceInstance::InputDeviceDestinationList, tracktion_engine::ClipEffects, tracktion_engine::ModifierList, tracktion_engine::TrackList, and tracktion_engine::TrackCompManager::TrackComp.
Referenced by tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::valueTreeChildOrderChanged().
valueTreeChildAdded()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> void tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildAdded (juce::ValueTree & , juce::ValueTree & tree) override
valueTreeChildRemoved()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> void tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildRemoved (juce::ValueTree & exParent, juce::ValueTree & tree, int) override
valueTreeChildOrderChanged()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> void tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeChildOrderChanged (juce::ValueTree & tree, int , int) override
valueTreePropertyChanged()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> void tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreePropertyChanged (juce::ValueTree & , const juce::Identifier &) override
valueTreeParentChanged()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> void tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeParentChanged (juce::ValueTree &) override
valueTreeRedirected()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> void tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::valueTreeRedirected (juce::ValueTree &) override
deleteAllObjects()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> void tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::deleteAllObjects () protected
Referenced by tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::freeObjects().
isChildTree()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> bool tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::isChildTree (juce::ValueTree & v) const protected
Referenced by tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::valueTreeChildAdded().
indexOf()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> int tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::indexOf (const juce::ValueTree & v) const protected noexcept
Referenced by tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::valueTreeChildRemoved().
sortArray()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> void tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::sortArray () protected
Referenced by tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::valueTreeChildOrderChanged().
compareElements()
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> int tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::compareElements (ObjectType * first, ObjectType * second) const
Member Data Documentation
objects
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> juce::Array<ObjectType*> tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::objects
Referenced by tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::at(), tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::begin(), tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::deleteAllObjects(), tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::end(), tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::indexOf(), tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::operator[](), tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::rebuildObjects(), tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::size(), tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::sortArray(), tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::valueTreeChildAdded(), tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::valueTreeChildRemoved(), and tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::~ValueTreeObjectList().
arrayLock
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> CriticalSectionType tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::arrayLock
Referenced by tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::deleteAllObjects(), tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::valueTreeChildAdded(), tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::valueTreeChildOrderChanged(), and tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::valueTreeChildRemoved().
parent
template<typename ObjectType , typename CriticalSectionType = juce::DummyCriticalSection> juce::ValueTree tracktion_engine::ValueTreeObjectList< ObjectType, CriticalSectionType >::parent protected
Referenced by tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::compareElements(), tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::freeObjects(), tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::isChildTree(), tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::rebuildObjects(), tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::valueTreeChildAdded(), tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::valueTreeChildOrderChanged(), tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::valueTreeChildRemoved(), and tracktion_engine::ValueTreeObjectList< tracktion_engine::MidiControllerEvent >::ValueTreeObjectList().
The documentation for this class was generated from the following file:
tracktion_ValueTreeUtilities.h