TracktionEngine: tracktion_engine::SpeedRampAudioNode Class Reference
tracktion_engine::SpeedRampAudioNode Class Reference
An AudioNode that speeds up and slows down its input node in/out at given times.
Public Member Functions
SpeedRampAudioNode (AudioNode *source, EditTimeRange in, EditTimeRange out, AudioFadeCurve::Type fadeInType_, AudioFadeCurve::Type fadeOutType_)
void renderOver (const AudioRenderContext &rc) override
void renderAdding (const AudioRenderContext &rc) override
void renderSection (const AudioRenderContext &rc, EditTimeRange editTime)
Public Member Functions inherited from tracktion_engine::SingleInputAudioNode
SingleInputAudioNode (AudioNode *input)
void getAudioNodeProperties (AudioNodeProperties &) override
void visitNodes (const VisitorFn &) override
void prepareAudioNodeToPlay (const PlaybackInitialisationInfo &) override
tells the node to initialise itself ready for playing from the given time.
juce::ReferenceCountedObjectPtr< Plugin > getPlugin () const override
bool isReadyToRender () override
bool purgeSubNodes (bool keepAudio, bool keepMidi) override
Tells the node to delete any sub-nodes that don't produce the required type of output.
void releaseAudioNodeResources () override
tells the node that play has stopped, and it can free up anything it no longer needs.
void prepareForNextBlock (const AudioRenderContext &) override
Public Member Functions inherited from tracktion_engine::AudioNode
AudioNode ()
virtual ~AudioNode ()
void callRenderAdding (const AudioRenderContext &)
void callRenderOver (const AudioRenderContext &)
Additional Inherited Members
Public Types inherited from tracktion_engine::AudioNode
using VisitorFn = std::function< void(AudioNode &)>
Static Public Member Functions inherited from tracktion_engine::AudioNode
template<typename CallbackType >
static void invokeSplitRender (const AudioRenderContext &rc, CallbackType &target)
Public Attributes inherited from tracktion_engine::SingleInputAudioNode
const std::unique_ptr< AudioNode > input
Detailed Description
An AudioNode that speeds up and slows down its input node in/out at given times.
Constructor & Destructor Documentation
SpeedRampAudioNode()
tracktion_engine::SpeedRampAudioNode::SpeedRampAudioNode (AudioNode * source, EditTimeRange in, EditTimeRange out, AudioFadeCurve::Type fadeInType_, AudioFadeCurve::Type fadeOutType_)
References tracktion_engine::EditTimeRange::isEmpty().
Member Function Documentation
renderOver()
void tracktion_engine::SpeedRampAudioNode::renderOver (const AudioRenderContext & rc) override virtual
Reimplemented from tracktion_engine::SingleInputAudioNode.
References tracktion_engine::SingleInputAudioNode::input, and tracktion_engine::AudioNode::invokeSplitRender().
renderAdding()
void tracktion_engine::SpeedRampAudioNode::renderAdding (const AudioRenderContext & rc) override virtual
Reimplemented from tracktion_engine::SingleInputAudioNode.
References tracktion_engine::AudioNode::callRenderOver(), and tracktion_engine::SingleInputAudioNode::input.
renderSection()
void tracktion_engine::SpeedRampAudioNode::renderSection (const AudioRenderContext & rc, EditTimeRange editTime)
References tracktion_engine::AudioRenderContext::bufferNumSamples, tracktion_engine::AudioRenderContext::bufferStartSample, tracktion_engine::EditTimeRange::getEnd(), tracktion_engine::EditTimeRange::getIntersectionWith(), tracktion_engine::EditTimeRange::getLength(), tracktion_engine::EditTimeRange::getStart(), tracktion_engine::EditTimeRange::overlaps(), tracktion_engine::AudioRenderContext::streamTime, and tracktion_engine::EditTimeRange::withLength().
The documentation for this class was generated from the following file:
tracktion_SpeedRampAudioNode.h