TracktionEngine: tracktion_engine::BenchmarkList Class Reference
tracktion_engine::BenchmarkList Class Reference
Contans a list of BenchmarkResult[s].
Public Member Functions
BenchmarkList ()=default
Constructs a BenchmarkList.
void addResult (BenchmarkResult r)
Adds a result to the list.
std::vector< BenchmarkResult > getResults () const
Returns all the results.
void clear ()
Removes all the current results.
Static Public Member Functions
static BenchmarkList & getInstance ()
Gets the singleton instance.
Detailed Description
Contans a list of BenchmarkResult[s].
For easy use, this can be used as a singleton so results can easily be added to it from anywhere in your code.
Once you've finished benchmarking, you can get all the results to publish them to your database.
Constructor & Destructor Documentation
BenchmarkList()
tracktion_engine::BenchmarkList::BenchmarkList () default
Constructs a BenchmarkList.
See also
getInstance
Member Function Documentation
addResult()
void tracktion_engine::BenchmarkList::addResult (BenchmarkResult r)
Adds a result to the list.
[[ thread_safe ]]
Referenced by tracktion_engine::benchmark_utilities::prepareRenderAndDestroy(), and tracktion_engine::ScopedBenchmark::~ScopedBenchmark().
getResults()
std::vector<BenchmarkResult> tracktion_engine::BenchmarkList::getResults () const
Returns all the results.
[[ thread_safe ]]
clear()
void tracktion_engine::BenchmarkList::clear ()
Removes all the current results.
[[ thread_safe ]]
getInstance()
static BenchmarkList& tracktion_engine::BenchmarkList::getInstance () static
Gets the singleton instance.
[[ thread_safe ]]
Referenced by tracktion_engine::benchmark_utilities::prepareRenderAndDestroy(), and tracktion_engine::ScopedBenchmark::~ScopedBenchmark().
The documentation for this class was generated from the following file:
tracktion_Benchmark.h