TracktionEngine: tracktion::graph::NodePlayer Class Reference
tracktion::graph::NodePlayer Class Reference
Simple player for an Node.
Public Member Functions
NodePlayer ()=default
Creates an empty NodePlayer.
NodePlayer (std::unique_ptr< Node > nodeToProcess, PlayHeadState *playHeadStateToUse=nullptr)
Creates an NodePlayer to process a Node.
Node * getNode ()
Returns the current Node.
void setNode (std::unique_ptr< Node > newNode)
Sets the Node to process.
void setNode (std::unique_ptr< Node > newNode, double sampleRateToUse, int blockSizeToUse)
Sets the Node to process with a new sample rate and block size.
void prepareToPlay (double sampleRateToUse, int blockSizeToUse, Node *oldNode=nullptr)
Prepares the current Node to be played.
std::vector< Node * > prepareToPlay (Node *node, Node *oldNode, double sampleRateToUse, int blockSizeToUse)
Prepares a specific Node to be played and returns all the Nodes.
int process (const Node::ProcessContext &pc)
Processes a block of audio and MIDI data.
double getSampleRate () const
int processPostorderedNodes (Node &rootNodeToProcess, const std::vector< Node * > &nodes, const Node::ProcessContext &pc)
Protected Member Functions
int processWithPlayHeadState (PlayHeadState &phs, Node &rootNodeToProcess, const std::vector< Node * > &nodes, const Node::ProcessContext &pc)
Static Protected Member Functions
static int processPostorderedNodesSingleThreaded (Node &rootNode, const std::vector< Node * > &allNodes, const Node::ProcessContext &pc)
Processes a group of Nodes assuming a postordering VertexOrdering.
Protected Attributes
std::unique_ptr< Node > input
PlayHeadState * playHeadState = nullptr
std::vector< Node * > allNodes
double sampleRate = 44100.0
int blockSize = 512
juce::SpinLock inputAndNodesLock
Detailed Description
Simple player for an Node.
This simply iterate all the nodes attempting to process them in a single thread.
Constructor & Destructor Documentation
NodePlayer() [1/2]
tracktion::graph::NodePlayer::NodePlayer () default
Creates an empty NodePlayer.
NodePlayer() [2/2]
tracktion::graph::NodePlayer::NodePlayer (std::unique_ptr< Node > nodeToProcess, PlayHeadState * playHeadStateToUse = nullptr)
Creates an NodePlayer to process a Node.
Member Function Documentation
getNode()
Node* tracktion::graph::NodePlayer::getNode ()
Returns the current Node.
References input.
setNode() [1/2]
void tracktion::graph::NodePlayer::setNode (std::unique_ptr< Node > newNode)
Sets the Node to process.
References blockSize, and sampleRate.
setNode() [2/2]
void tracktion::graph::NodePlayer::setNode (std::unique_ptr< Node > newNode, double sampleRateToUse, int blockSizeToUse)
Sets the Node to process with a new sample rate and block size.
References allNodes, input, inputAndNodesLock, and prepareToPlay().
prepareToPlay() [1/2]
void tracktion::graph::NodePlayer::prepareToPlay (double sampleRateToUse, int blockSizeToUse, Node * oldNode = nullptr)
Prepares the current Node to be played.
References allNodes, and input.
Referenced by setNode().
prepareToPlay() [2/2]
std::vector<Node*> tracktion::graph::NodePlayer::prepareToPlay (Node * node, Node * oldNode, double sampleRateToUse, int blockSizeToUse)
Prepares a specific Node to be played and returns all the Nodes.
References blockSize, tracktion::graph::PlayHeadState::playHead, playHeadState, sampleRate, tracktion::graph::PlayHead::setScrubbingBlockLength(), and tracktion::graph::timeToSample().
process()
int tracktion::graph::NodePlayer::process (const Node::ProcessContext & pc)
Processes a block of audio and MIDI data.
Returns the number of times a node was checked but unable to be processed.
References allNodes, input, inputAndNodesLock, playHeadState, processPostorderedNodes(), and processWithPlayHeadState().
getSampleRate()
double tracktion::graph::NodePlayer::getSampleRate () const
References sampleRate.
processPostorderedNodes()
int tracktion::graph::NodePlayer::processPostorderedNodes (Node & rootNodeToProcess, const std::vector< Node * > & nodes, const Node::ProcessContext & pc)
References processPostorderedNodesSingleThreaded().
Referenced by process(), and processWithPlayHeadState().
processWithPlayHeadState()
int tracktion::graph::NodePlayer::processWithPlayHeadState (PlayHeadState & phs, Node & rootNodeToProcess, const std::vector< Node * > & nodes, const Node::ProcessContext & pc) protected
References tracktion::graph::Node::AudioAndMidiBuffer::audio, tracktion::graph::Node::ProcessContext::buffers, tracktion::graph::Node::AudioAndMidiBuffer::midi, tracktion::graph::Node::ProcessContext::numSamples, tracktion::graph::PlayHeadState::playHead, processPostorderedNodes(), tracktion::graph::Node::ProcessContext::referenceSampleRange, and tracktion::graph::PlayHeadState::update().
Referenced by process().
processPostorderedNodesSingleThreaded()
static int tracktion::graph::NodePlayer::processPostorderedNodesSingleThreaded (Node & rootNode, const std::vector< Node * > & allNodes, const Node::ProcessContext & pc) static protected
Processes a group of Nodes assuming a postordering VertexOrdering.
If these conditions are met the Nodes should be processed in a single loop iteration.
References allNodes, tracktion::graph::Node::AudioAndMidiBuffer::audio, tracktion::graph::Node::ProcessContext::buffers, tracktion::graph::Node::getProcessedOutput(), tracktion::graph::Node::AudioAndMidiBuffer::midi, tracktion::graph::Node::ProcessContext::numSamples, and tracktion::graph::Node::ProcessContext::referenceSampleRange.
Referenced by processPostorderedNodes().
Member Data Documentation
input
std::unique_ptr<Node> tracktion::graph::NodePlayer::input protected
Referenced by getNode(), prepareToPlay(), process(), and setNode().
playHeadState
PlayHeadState* tracktion::graph::NodePlayer::playHeadState = nullptr protected
Referenced by prepareToPlay(), and process().
allNodes
std::vector<Node*> tracktion::graph::NodePlayer::allNodes protected
Referenced by prepareToPlay(), process(), processPostorderedNodesSingleThreaded(), and setNode().
sampleRate
double tracktion::graph::NodePlayer::sampleRate = 44100.0 protected
Referenced by getSampleRate(), prepareToPlay(), and setNode().
blockSize
int tracktion::graph::NodePlayer::blockSize = 512 protected
Referenced by prepareToPlay(), and setNode().
inputAndNodesLock
juce::SpinLock tracktion::graph::NodePlayer::inputAndNodesLock protected
Referenced by process(), and setNode().
The documentation for this class was generated from the following file:
tracktion_NodePlayer.h