TracktionEngine: tracktion::engine::AudioFifo Class Reference
tracktion::engine::AudioFifo Class Reference
Public Member Functions
AudioFifo (int channels, int numSamples)
void setSize (int numChannels, int numSamples)
int getFreeSpace () const noexcept
int getNumReady () const noexcept
int getNumChannels () const noexcept
void reset () noexcept
void ensureFreeSpace (int numSamples)
bool write (const juce::AudioBuffer< float > &src)
bool write (const juce::AudioBuffer< float > &src, int startSample, int numSamples)
bool write (const float *const *data, int numSamples)
bool writeSilence (int numSamples)
bool read (juce::AudioBuffer< float > &dest, int startSampleInDestBuffer)
bool read (juce::AudioBuffer< float > &dest, int startSampleInDestBuffer, int numSamples)
bool readAdding (juce::AudioBuffer< float > &dest, int startSampleInDestBuffer)
bool readAdding (juce::AudioBuffer< float > &dest, int startSampleInDestBuffer, int numSamples)
Constructor & Destructor Documentation
AudioFifo()
tracktion::engine::AudioFifo::AudioFifo (int channels, int numSamples)
Member Function Documentation
setSize()
void tracktion::engine::AudioFifo::setSize (int numChannels, int numSamples)
getFreeSpace()
int tracktion::engine::AudioFifo::getFreeSpace () const noexcept
Referenced by ensureFreeSpace().
getNumReady()
int tracktion::engine::AudioFifo::getNumReady () const noexcept
Referenced by ensureFreeSpace().
getNumChannels()
int tracktion::engine::AudioFifo::getNumChannels () const noexcept
reset()
void tracktion::engine::AudioFifo::reset () noexcept
ensureFreeSpace()
void tracktion::engine::AudioFifo::ensureFreeSpace (int numSamples)
References getFreeSpace(), and getNumReady().
write() [1/3]
bool tracktion::engine::AudioFifo::write (const juce::AudioBuffer< float > & src)
write() [2/3]
bool tracktion::engine::AudioFifo::write (const juce::AudioBuffer< float > & src, int startSample, int numSamples)
write() [3/3]
bool tracktion::engine::AudioFifo::write (const float *const * data, int numSamples)
writeSilence()
bool tracktion::engine::AudioFifo::writeSilence (int numSamples)
read() [1/2]
bool tracktion::engine::AudioFifo::read (juce::AudioBuffer< float > & dest, int startSampleInDestBuffer)
read() [2/2]
bool tracktion::engine::AudioFifo::read (juce::AudioBuffer< float > & dest, int startSampleInDestBuffer, int numSamples)
readAdding() [1/2]
bool tracktion::engine::AudioFifo::readAdding (juce::AudioBuffer< float > & dest, int startSampleInDestBuffer)
readAdding() [2/2]
bool tracktion::engine::AudioFifo::readAdding (juce::AudioBuffer< float > & dest, int startSampleInDestBuffer, int numSamples)
The documentation for this class was generated from the following file:
tracktion_engine/audio_files/tracktion_AudioFifo.h