TracktionEngine: tracktion::engine::Track Class Reference
tracktion::engine::Track Class Reference abstract
Base class for tracks which contain clips and plugins and can be added to Edit[s].
Public Types
enum FreezeType { groupFreeze = 0 , individualFreeze , anyFreeze }
Determines the type of freeze.
enum MuteAndSoloLightState {
soloLit = 1 , soloFlashing = 2 , soloIsolate = 4 , muteLit = 8 ,
muteFlashing = 16
}
Determines the status of the mute and solo indicators.
using Ptr = juce::ReferenceCountedObjectPtr< Track >
using Array = juce::ReferenceCountedArray< Track >
Public Types inherited from tracktion::engine::Selectable
using WeakRef = juce::WeakReference< Selectable >
Public Member Functions
Track (Edit &, const juce::ValueTree &, double defaultTrackHeight, double minTrackHeight, double maxTrackHeight)
Creates a track with a given state.
~Track () override
Destructor.
virtual void initialise ()
Initialises the Track.
virtual void flushStateToValueTree ()
Flushes all plugin states on the track to the state object.
void refreshCurrentAutoParam ()
Updates the current parameter bases on the set IDs.
juce::String getName () const override
Returns the name of the Track.
void setName (const juce::String &)
Sets the name of the Track.
void resetName ()
Sets the name of the Track to an empty string.
virtual void sanityCheckName ()
Sub-classes can impliment this to avoid certain characters being used in a name.
virtual bool isAudioTrack () const
Returns true if this is an AudioTrack.
virtual bool isAutomationTrack () const
Returns true if this is an AutomationTrack.
virtual bool isFolderTrack () const
Returns true if this is a FolderTrack.
virtual bool isMarkerTrack () const
Returns true if this is a MarkerTrack.
virtual bool isTempoTrack () const
Returns true if this is a TempoTrack.
virtual bool isChordTrack () const
Returns true if this is a ChordTrack.
virtual bool isArrangerTrack () const
Returns true if this is an ArrangerTrack.
virtual bool isMasterTrack () const
Returns true if this is a MasterTrack.
bool canContainMarkers () const
Returns true if this Track can contain MarkerClip[s].
bool canContainMIDI () const
Returns true if this Track can contain MidiClip[s].
bool canContainAudio () const
Returns true if this Track can contain WaveAudioClip[s].
bool canContainEditClips () const
Returns true if this Track can contain EditClip[s].
bool canContainPlugins () const
Returns true if this Track can contain Plugin[s].
bool isMovable () const
Returns true if this Track is movable.
bool acceptsInput () const
Returns true if this track can have inputs assigned to it.
bool createsOutput () const
Returns true if this track creates audible output.
bool wantsAutomation () const
Returns true if this track can show automation.
virtual bool canContainPlugin (Plugin *) const =0
Returns true if this track can contain a specific Plugin.
virtual bool isFrozen (FreezeType) const
Returns true if this track is frozen using the given type.
virtual void setFrozen (bool, FreezeType)
Attempts to freeze or unfreeze the track using a given FreezeType.
bool isHidden () const
Returns true if this track should be hidden from view.
void setHidden (bool h)
Sets whether this track should be hidden from view.
bool isProcessing (bool includeParents) const
Returns true if this track should be included in playback.
void setProcessing (bool p)
Sets whether this track should be included in playback.
virtual bool processAudioNodesWhileMuted () const
Subclasses can override this to ensure track contents are still played even when the track is muted.
virtual juce::Array< Track * > getInputTracks () const
Should return any tracks which feed into this track.
juce::Array< Track * > getAllSubTracks (bool recursive) const
Returns all nested tracks.
juce::Array< AudioTrack * > getAllAudioSubTracks (bool recursive) const
Returns all nested AudioTrack[s].
TrackList * getSubTrackList () const
Returns the TrackList if this Track has any sub-tracks.
bool hasSubTracks () const
Returns true if this track has any subtracks.
virtual Clip * findClipForID (EditItemID) const
Returns a clip one with a matching ID can be found on this Track.
Track * getSiblingTrack (int delta, bool keepWithinSameParent) const
Returns a sibling Track to this one.
virtual int getNumTrackItems () const
Should return the number of TrackItem[s] on this Track.
virtual TrackItem * getTrackItem (int) const
Should return the TrackItem at the given index.
virtual int indexOfTrackItem (TrackItem *) const
Should return the index of the given TrackItem.
virtual int getIndexOfNextTrackItemAt (TimePosition)
Should return the index of the TrackItem after this time.
virtual TrackItem * getNextTrackItemAt (TimePosition)
Should return the TrackItem after this time.
virtual void insertSpaceIntoTrack (TimePosition, TimeDuration)
Should insert empty space in to the track, shuffling down any items after the time.
juce::ValueTree getParentTrackTree () const
Returns the state of the parent Track.
Track * getParentTrack () const
Returns the parent Track if this is a nested track.
FolderTrack * getParentFolderTrack () const
Returns the parent FolderTrack if this is nested in one.
bool isAChildOf (const Track &possibleParent) const
Tests whether this is a child of a given Track.
bool isPartOfSubmix () const
Tests whether this nested within a submix FolderTrack.
int getIndexInEditTrackList () const
Returns the index of this track in a flat list of tracks contained in an Edit.
int getTrackDepth () const
Returns the number of parents within which this track is nested.
virtual bool isMuted (bool) const
Returns true if this track is muted.
virtual bool isSolo (bool) const
Returns true if this track is soloed.
virtual bool isSoloIsolate (bool) const
Returns true if this track is solo isolated.
virtual void setMute (bool)
Subclasses should implement this to mute themselves.
virtual void setSolo (bool)
Subclasses should implement this to solo themselves.
virtual void setSoloIsolate (bool)
Subclasses should implement this to solo isolate themselves.
MuteAndSoloLightState getMuteAndSoloLightState () const
Returns the mute a solo status.
bool shouldBePlayed () const noexcept
Tests whether this track should be audible in the playback graph i.e.
void updateAudibility (bool areAnyTracksSolo)
Updates the audibility state of the Track.
juce::Array< AutomatableParameter * > getAllAutomatableParams () const
Returns all the parameteres for this track's Plugin[s] and Modifier[s].
AutomatableParameter * getCurrentlyShownAutoParam () const noexcept
Returns the parameter whos curve should be shown on this Track.
void setCurrentlyShownAutoParam (const AutomatableParameter::Ptr &)
Sets a parameter to display on this Track.
void hideAutomatableParametersForSource (EditItemID pluginOrParameterID)
Hides a shown parameter if it matches the given ID.
virtual bool containsPlugin (const Plugin *) const
Tests whether this Track or a clip on it contains the given plugin.
bool hasFreezePointPlugin () const
Tests whether this Track contains a FreezePointPlugin.
juce::Array< AutomatableEditItem * > getAllAutomatableEditItems () const
Returns all AutomatableEditItem[s] on this Track.
virtual Plugin::Array getAllPlugins () const
Returns all pugins on this Track.
virtual void sendMirrorUpdateToAllPlugins (Plugin &changedPlugin) const
Sends a message to all plugins that the given plugin has changed.
void flipAllPluginsEnablement ()
Toggles the Plugin::isEnabled state for all Plugin[s] on this Track.
ModifierList & getModifierList () const
Returns the ModifierList for this Track.
void setColour (juce::Colour newColour)
Sets a colour for this track to use.
juce::Colour getColour () const
Returns the the of this.
bool canShowImage () const
Tests whether this Track can show an image.
void setTrackImage (const juce::String &idOrData)
Sets some image data to use.
juce::String getTrackImage () const
Returns previously set image data.
bool imageHasChanged ()
Tests and resets a flag internally kept when the image changes.
void setTags (const juce::StringArray &)
Sets an array of Strings to use as tags.
juce::String getTags () const
Returns the tags as a pipe-separated single String.
const juce::StringArray & getTagsArray () const noexcept
Returns the array of tags.
Public Member Functions inherited from tracktion::engine::EditItem
EditItem (EditItemID, Edit &)
virtual ~EditItem ()=default
Public Member Functions inherited from tracktion::engine::Selectable
Selectable ()
virtual ~Selectable ()
virtual juce::String getSelectableDescription ()=0
Subclasses must return a description of what they are.
virtual void selectionStatusChanged (bool isNowSelected)
Can be overridden to tell this object that it has just been selected or deselected.
virtual void changed ()
This should be called to send a change notification to any SelectableListeners that are registered with this object.
virtual void selectableAboutToBeDeleted ()
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void addSelectableListener (SelectableListener *)
void removeSelectableListener (SelectableListener *)
void cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
void deselect ()
void propertiesChanged ()
void notifyListenersOfDeletion ()
WeakRef getWeakRef ()
Public Member Functions inherited from tracktion::engine::MacroParameterElement
MacroParameterElement (Edit &, const juce::ValueTree &)
Constructor.
virtual ~MacroParameterElement ()=default
Destructor.
int getNumMacroParameters () const
Returns the number of macro parameters for this object.
Public Attributes
const double defaultTrackHeight
The default height of this Track.
const double minTrackHeight
The minimum height of this Track.
const double maxTrackHeight
The maximum height of this Track.
juce::ValueTree state
The state of this Track.
PluginList pluginList
The Track's PluginList.
Public Attributes inherited from tracktion::engine::EditItem
Edit & edit
const EditItemID itemID
Every EditItem has an ID which is unique within the edit.
Public Attributes inherited from tracktion::engine::Selectable
WeakRef::Master masterReference
Public Attributes inherited from tracktion::engine::MacroParameterElement
MacroParameterList macroParameterList
Static Public Attributes
static const int minTrackHeightForDetail = 10
The minimim height to show track contents at.
static const int trackHeightForEditor = 180
The height at which inline editors should be shown.
static const int frozenTrackHeight = 15
The height to show group frozen tracks.
Protected Member Functions
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeChildAdded (juce::ValueTree &, juce::ValueTree &) override
void valueTreeChildRemoved (juce::ValueTree &, juce::ValueTree &, int) override
void valueTreeChildOrderChanged (juce::ValueTree &, int, int) override
void valueTreeParentChanged (juce::ValueTree &) override
void handleAsyncUpdate () override
virtual bool isTrackAudible (bool areAnyTracksSolo) const
Returns whether this Track should be audible.
Additional Inherited Members
Static Public Member Functions inherited from tracktion::engine::Selectable
static void initialise ()
static bool isSelectableValid (const Selectable *) noexcept
checks whether this object has been deleted.
Detailed Description
Base class for tracks which contain clips and plugins and can be added to Edit[s].
See also
AudioTrack, FolderTrack, AutomationTrack, MarkerTrack, TempoTrack, ChordTrack, ArrangerTrack
Member Typedef Documentation
Ptr
using tracktion::engine::Track::Ptr = juce::ReferenceCountedObjectPtr<Track>
Array
using tracktion::engine::Track::Array = juce::ReferenceCountedArray<Track>
Member Enumeration Documentation
FreezeType
enum tracktion::engine::Track::FreezeType
Determines the type of freeze.
Enumerator
groupFreeze
Freezes multiple tracks together in to a single file.
individualFreeze
Freezes a track in to a single audio file.
anyFreeze
Either a group or individual freeze.
MuteAndSoloLightState
enum tracktion::engine::Track::MuteAndSoloLightState
Determines the status of the mute and solo indicators.
Enumerator
soloLit
Track is explicitly soloed.
soloFlashing
Track is implicitly soloed.
soloIsolate
Track is explicitly solo isolated.
muteLit
Track is explicitly muted.
muteFlashing
Track is implicitly muted.
Constructor & Destructor Documentation
Track()
tracktion::engine::Track::Track (Edit & , const juce::ValueTree & , double defaultTrackHeight, double minTrackHeight, double maxTrackHeight)
Creates a track with a given state.
~Track()
tracktion::engine::Track::~Track () override
Destructor.
Member Function Documentation
initialise()
virtual void tracktion::engine::Track::initialise () virtual
Initialises the Track.
You shouldn't need to call this directly, it will be called by the track creation methods.
See also
Edit::insertTrack
Reimplemented in tracktion::engine::MasterTrack, tracktion::engine::FolderTrack, tracktion::engine::ClipTrack, and tracktion::engine::AudioTrack.
flushStateToValueTree()
virtual void tracktion::engine::Track::flushStateToValueTree () virtual
Flushes all plugin states on the track to the state object.
This is usually called automatically when an Edit is saved.
Reimplemented in tracktion::engine::ClipTrack.
refreshCurrentAutoParam()
void tracktion::engine::Track::refreshCurrentAutoParam ()
Updates the current parameter bases on the set IDs.
This is usually called automatically by the Edit when the ID changes or an Edit is loaded.
See also
getCurrentlyShownAutoParam
getName()
juce::String tracktion::engine::Track::getName () const override virtual
Returns the name of the Track.
Implements tracktion::engine::EditItem.
setName()
void tracktion::engine::Track::setName (const juce::String &)
Sets the name of the Track.
resetName()
void tracktion::engine::Track::resetName ()
Sets the name of the Track to an empty string.
Base classes may then use this an an indication to return a name based on the track type and index
sanityCheckName()
virtual void tracktion::engine::Track::sanityCheckName () virtual
Sub-classes can impliment this to avoid certain characters being used in a name.
Reimplemented in tracktion::engine::FolderTrack, and tracktion::engine::AudioTrack.
isAudioTrack()
virtual bool tracktion::engine::Track::isAudioTrack () const virtual
Returns true if this is an AudioTrack.
Reimplemented in tracktion::engine::AudioTrack.
Referenced by acceptsInput(), canContainAudio(), canContainEditClips(), canContainMIDI(), canContainPlugins(), createsOutput(), and isMovable().
isAutomationTrack()
virtual bool tracktion::engine::Track::isAutomationTrack () const virtual
Returns true if this is an AutomationTrack.
Reimplemented in tracktion::engine::AutomationTrack.
isFolderTrack()
virtual bool tracktion::engine::Track::isFolderTrack () const virtual
Returns true if this is a FolderTrack.
Reimplemented in tracktion::engine::FolderTrack.
Referenced by canContainPlugins(), and isMovable().
isMarkerTrack()
virtual bool tracktion::engine::Track::isMarkerTrack () const virtual
Returns true if this is a MarkerTrack.
Reimplemented in tracktion::engine::MarkerTrack.
Referenced by canContainMarkers(), and wantsAutomation().
isTempoTrack()
virtual bool tracktion::engine::Track::isTempoTrack () const virtual
Returns true if this is a TempoTrack.
Reimplemented in tracktion::engine::TempoTrack.
isChordTrack()
virtual bool tracktion::engine::Track::isChordTrack () const virtual
Returns true if this is a ChordTrack.
Reimplemented in tracktion::engine::ChordTrack.
Referenced by wantsAutomation().
isArrangerTrack()
virtual bool tracktion::engine::Track::isArrangerTrack () const virtual
Returns true if this is an ArrangerTrack.
Reimplemented in tracktion::engine::ArrangerTrack.
Referenced by wantsAutomation().
isMasterTrack()
virtual bool tracktion::engine::Track::isMasterTrack () const virtual
Returns true if this is a MasterTrack.
Reimplemented in tracktion::engine::MasterTrack.
Referenced by canContainPlugins().
canContainMarkers()
bool tracktion::engine::Track::canContainMarkers () const
Returns true if this Track can contain MarkerClip[s].
References isMarkerTrack().
canContainMIDI()
bool tracktion::engine::Track::canContainMIDI () const
Returns true if this Track can contain MidiClip[s].
References isAudioTrack().
canContainAudio()
bool tracktion::engine::Track::canContainAudio () const
Returns true if this Track can contain WaveAudioClip[s].
References isAudioTrack().
canContainEditClips()
bool tracktion::engine::Track::canContainEditClips () const
Returns true if this Track can contain EditClip[s].
References isAudioTrack().
canContainPlugins()
bool tracktion::engine::Track::canContainPlugins () const
Returns true if this Track can contain Plugin[s].
References isAudioTrack(), isFolderTrack(), and isMasterTrack().
isMovable()
bool tracktion::engine::Track::isMovable () const
Returns true if this Track is movable.
See also
AudioTrack, FolderTrack
References isAudioTrack(), and isFolderTrack().
acceptsInput()
bool tracktion::engine::Track::acceptsInput () const
Returns true if this track can have inputs assigned to it.
See also
AudioTrack
References isAudioTrack().
createsOutput()
bool tracktion::engine::Track::createsOutput () const
Returns true if this track creates audible output.
See also
AudioTrack
References isAudioTrack().
wantsAutomation()
bool tracktion::engine::Track::wantsAutomation () const
Returns true if this track can show automation.
See also
AudioTrack, FolderTrack, AutomationTrack
References isArrangerTrack(), isChordTrack(), and isMarkerTrack().
canContainPlugin()
virtual bool tracktion::engine::Track::canContainPlugin (Plugin *) const pure virtual
Returns true if this track can contain a specific Plugin.
Subclasses can override this to avoid specific plugins such as VCAPlugin[s] on AudioTrack[s].
Implemented in tracktion::engine::TempoTrack, tracktion::engine::MasterTrack, tracktion::engine::MarkerTrack, tracktion::engine::FolderTrack, tracktion::engine::ChordTrack, tracktion::engine::AutomationTrack, tracktion::engine::AudioTrack, and tracktion::engine::ArrangerTrack.
isFrozen()
virtual bool tracktion::engine::Track::isFrozen (FreezeType) const virtual
Returns true if this track is frozen using the given type.
Reimplemented in tracktion::engine::FolderTrack, and tracktion::engine::AudioTrack.
setFrozen()
virtual void tracktion::engine::Track::setFrozen (bool , FreezeType) virtual
Attempts to freeze or unfreeze the track using a given FreezeType.
Reimplemented in tracktion::engine::AudioTrack.
isHidden()
bool tracktion::engine::Track::isHidden () const
Returns true if this track should be hidden from view.
setHidden()
void tracktion::engine::Track::setHidden (bool h)
Sets whether this track should be hidden from view.
isProcessing()
bool tracktion::engine::Track::isProcessing (bool includeParents) const
Returns true if this track should be included in playback.
setProcessing()
void tracktion::engine::Track::setProcessing (bool p)
Sets whether this track should be included in playback.
processAudioNodesWhileMuted()
virtual bool tracktion::engine::Track::processAudioNodesWhileMuted () const virtual
Subclasses can override this to ensure track contents are still played even when the track is muted.
This may be required if this track is a sidechain source or feeding an aux for example.
Reimplemented in tracktion::engine::AudioTrack.
getInputTracks()
virtual juce::Array<Track*> tracktion::engine::Track::getInputTracks () const virtual
Should return any tracks which feed into this track.
Reimplemented in tracktion::engine::FolderTrack, and tracktion::engine::AudioTrack.
getAllSubTracks()
juce::Array<Track*> tracktion::engine::Track::getAllSubTracks (bool recursive) const
Returns all nested tracks.
Parameters
recursive Whether to include all tracks recursively.
getAllAudioSubTracks()
juce::Array<AudioTrack*> tracktion::engine::Track::getAllAudioSubTracks (bool recursive) const
Returns all nested AudioTrack[s].
Parameters
recursive Whether to include all tracks recursively.
getSubTrackList()
TrackList* tracktion::engine::Track::getSubTrackList () const
Returns the TrackList if this Track has any sub-tracks.
May be nullptr if it doesn't.
hasSubTracks()
bool tracktion::engine::Track::hasSubTracks () const
Returns true if this track has any subtracks.
findClipForID()
virtual Clip* tracktion::engine::Track::findClipForID (EditItemID) const virtual
Returns a clip one with a matching ID can be found on this Track.
Reimplemented in tracktion::engine::ClipTrack.
getSiblingTrack()
Track* tracktion::engine::Track::getSiblingTrack (int delta, bool keepWithinSameParent) const
Returns a sibling Track to this one.
Parameters
delta The offset from this track. 1 is the next track, -1 is the previous.
keepWithinSameParent Whether to include parent and sub tracks or only tracks at this level.
getNumTrackItems()
virtual int tracktion::engine::Track::getNumTrackItems () const virtual
Should return the number of TrackItem[s] on this Track.
Reimplemented in tracktion::engine::TempoTrack, tracktion::engine::FolderTrack, and tracktion::engine::ClipTrack.
getTrackItem()
virtual TrackItem* tracktion::engine::Track::getTrackItem (int) const virtual
Should return the TrackItem at the given index.
Reimplemented in tracktion::engine::TempoTrack, tracktion::engine::FolderTrack, and tracktion::engine::ClipTrack.
indexOfTrackItem()
virtual int tracktion::engine::Track::indexOfTrackItem (TrackItem *) const virtual
Should return the index of the given TrackItem.
Reimplemented in tracktion::engine::TempoTrack, tracktion::engine::FolderTrack, and tracktion::engine::ClipTrack.
getIndexOfNextTrackItemAt()
virtual int tracktion::engine::Track::getIndexOfNextTrackItemAt (TimePosition) virtual
Should return the index of the TrackItem after this time.
Reimplemented in tracktion::engine::TempoTrack, tracktion::engine::FolderTrack, and tracktion::engine::ClipTrack.
getNextTrackItemAt()
virtual TrackItem* tracktion::engine::Track::getNextTrackItemAt (TimePosition) virtual
Should return the TrackItem after this time.
Reimplemented in tracktion::engine::TempoTrack, tracktion::engine::FolderTrack, and tracktion::engine::ClipTrack.
insertSpaceIntoTrack()
virtual void tracktion::engine::Track::insertSpaceIntoTrack (TimePosition , TimeDuration) virtual
Should insert empty space in to the track, shuffling down any items after the time.
Parameters
time The time point in seconds to insert at
amountOfSpace The duration of time to insert
Reimplemented in tracktion::engine::TempoTrack, and tracktion::engine::ClipTrack.
getParentTrackTree()
juce::ValueTree tracktion::engine::Track::getParentTrackTree () const
Returns the state of the parent Track.
getParentTrack()
Track* tracktion::engine::Track::getParentTrack () const
Returns the parent Track if this is a nested track.
Referenced by getParentFolderTrack().
getParentFolderTrack()
FolderTrack* tracktion::engine::Track::getParentFolderTrack () const
Returns the parent FolderTrack if this is nested in one.
References getParentTrack().
isAChildOf()
bool tracktion::engine::Track::isAChildOf (const Track & possibleParent) const
Tests whether this is a child of a given Track.
isPartOfSubmix()
bool tracktion::engine::Track::isPartOfSubmix () const
Tests whether this nested within a submix FolderTrack.
See also
FolderTrack::isSubmixFolder
getIndexInEditTrackList()
int tracktion::engine::Track::getIndexInEditTrackList () const
Returns the index of this track in a flat list of tracks contained in an Edit.
Useful for naming Tracks.
getTrackDepth()
int tracktion::engine::Track::getTrackDepth () const
Returns the number of parents within which this track is nested.
isMuted()
virtual bool tracktion::engine::Track::isMuted (bool) const virtual
Returns true if this track is muted.
Parameters
includeMutingByDestination If this is true, this will retrn true if any tracks this feeds in to are muted.
Reimplemented in tracktion::engine::FolderTrack, and tracktion::engine::AudioTrack.
isSolo()
virtual bool tracktion::engine::Track::isSolo (bool) const virtual
Returns true if this track is soloed.
Parameters
includeIndirectSolo If this is true, this will retrn true if any tracks this feeds in to are soloed.
Reimplemented in tracktion::engine::FolderTrack, and tracktion::engine::AudioTrack.
isSoloIsolate()
virtual bool tracktion::engine::Track::isSoloIsolate (bool) const virtual
Returns true if this track is solo isolated.
Parameters
includeIndirectSolo If this is true, this will retrn true if any tracks this feeds in to are solo isolated.
Reimplemented in tracktion::engine::FolderTrack, and tracktion::engine::AudioTrack.
setMute()
virtual void tracktion::engine::Track::setMute (bool) virtual
Subclasses should implement this to mute themselves.
Reimplemented in tracktion::engine::FolderTrack, and tracktion::engine::AudioTrack.
setSolo()
virtual void tracktion::engine::Track::setSolo (bool) virtual
Subclasses should implement this to solo themselves.
Reimplemented in tracktion::engine::FolderTrack, and tracktion::engine::AudioTrack.
setSoloIsolate()
virtual void tracktion::engine::Track::setSoloIsolate (bool) virtual
Subclasses should implement this to solo isolate themselves.
Reimplemented in tracktion::engine::FolderTrack, and tracktion::engine::AudioTrack.
getMuteAndSoloLightState()
MuteAndSoloLightState tracktion::engine::Track::getMuteAndSoloLightState () const
Returns the mute a solo status.
shouldBePlayed()
bool tracktion::engine::Track::shouldBePlayed () const noexcept
Tests whether this track should be audible in the playback graph i.e.
explicitly or implicitly soloed or not muted.
updateAudibility()
void tracktion::engine::Track::updateAudibility (bool areAnyTracksSolo)
Updates the audibility state of the Track.
N.B. You shouldn't need to call this directly. It will get called by the Edit when a track's solo/mute status changes.
getAllAutomatableParams()
juce::Array<AutomatableParameter*> tracktion::engine::Track::getAllAutomatableParams () const
Returns all the parameteres for this track's Plugin[s] and Modifier[s].
getCurrentlyShownAutoParam()
AutomatableParameter* tracktion::engine::Track::getCurrentlyShownAutoParam () const noexcept
Returns the parameter whos curve should be shown on this Track.
setCurrentlyShownAutoParam()
void tracktion::engine::Track::setCurrentlyShownAutoParam (const AutomatableParameter::Ptr &)
Sets a parameter to display on this Track.
hideAutomatableParametersForSource()
void tracktion::engine::Track::hideAutomatableParametersForSource (EditItemID pluginOrParameterID)
Hides a shown parameter if it matches the given ID.
containsPlugin()
virtual bool tracktion::engine::Track::containsPlugin (const Plugin *) const virtual
Tests whether this Track or a clip on it contains the given plugin.
Reimplemented in tracktion::engine::ClipTrack.
hasFreezePointPlugin()
bool tracktion::engine::Track::hasFreezePointPlugin () const
Tests whether this Track contains a FreezePointPlugin.
getAllAutomatableEditItems()
juce::Array<AutomatableEditItem*> tracktion::engine::Track::getAllAutomatableEditItems () const
Returns all AutomatableEditItem[s] on this Track.
See also
Plugin, Modifier
getAllPlugins()
virtual Plugin::Array tracktion::engine::Track::getAllPlugins () const virtual
Returns all pugins on this Track.
Subclasses may implement this to also return Plugin[s] on Clip[s]
Reimplemented in tracktion::engine::ClipTrack.
sendMirrorUpdateToAllPlugins()
virtual void tracktion::engine::Track::sendMirrorUpdateToAllPlugins (Plugin & changedPlugin) const virtual
Sends a message to all plugins that the given plugin has changed.
Reimplemented in tracktion::engine::ClipTrack.
flipAllPluginsEnablement()
void tracktion::engine::Track::flipAllPluginsEnablement ()
Toggles the Plugin::isEnabled state for all Plugin[s] on this Track.
getModifierList()
ModifierList& tracktion::engine::Track::getModifierList () const
Returns the ModifierList for this Track.
setColour()
void tracktion::engine::Track::setColour (juce::Colour newColour)
Sets a colour for this track to use.
getColour()
juce::Colour tracktion::engine::Track::getColour () const
Returns the the of this.
canShowImage()
bool tracktion::engine::Track::canShowImage () const
Tests whether this Track can show an image.
N.B. May be removed in a future version.
setTrackImage()
void tracktion::engine::Track::setTrackImage (const juce::String & idOrData)
Sets some image data to use.
N.B. May be removed in a future version.
getTrackImage()
juce::String tracktion::engine::Track::getTrackImage () const
Returns previously set image data.
N.B. May be removed in a future version.
imageHasChanged()
bool tracktion::engine::Track::imageHasChanged ()
Tests and resets a flag internally kept when the image changes.
N.B. May be removed in a future version.
setTags()
void tracktion::engine::Track::setTags (const juce::StringArray &)
Sets an array of Strings to use as tags.
N.B. May be removed in a future version.
getTags()
juce::String tracktion::engine::Track::getTags () const
Returns the tags as a pipe-separated single String.
N.B. May be removed in a future version.
getTagsArray()
const juce::StringArray& tracktion::engine::Track::getTagsArray () const noexcept
Returns the array of tags.
N.B. May be removed in a future version.
valueTreePropertyChanged()
void tracktion::engine::Track::valueTreePropertyChanged (juce::ValueTree & , const juce::Identifier &) override protected
valueTreeChildAdded()
void tracktion::engine::Track::valueTreeChildAdded (juce::ValueTree & , juce::ValueTree &) override protected
valueTreeChildRemoved()
void tracktion::engine::Track::valueTreeChildRemoved (juce::ValueTree & , juce::ValueTree & , int) override protected
valueTreeChildOrderChanged()
void tracktion::engine::Track::valueTreeChildOrderChanged (juce::ValueTree & , int , int) override protected
valueTreeParentChanged()
void tracktion::engine::Track::valueTreeParentChanged (juce::ValueTree &) override protected
handleAsyncUpdate()
void tracktion::engine::Track::handleAsyncUpdate () override protected
isTrackAudible()
virtual bool tracktion::engine::Track::isTrackAudible (bool areAnyTracksSolo) const protected virtual
Returns whether this Track should be audible.
Subclasses can override for custom behaviour.
Reimplemented in tracktion::engine::AudioTrack.
Member Data Documentation
minTrackHeightForDetail
const int tracktion::engine::Track::minTrackHeightForDetail = 10 static
The minimim height to show track contents at.
trackHeightForEditor
const int tracktion::engine::Track::trackHeightForEditor = 180 static
The height at which inline editors should be shown.
frozenTrackHeight
const int tracktion::engine::Track::frozenTrackHeight = 15 static
The height to show group frozen tracks.
defaultTrackHeight
const double tracktion::engine::Track::defaultTrackHeight
The default height of this Track.
minTrackHeight
const double tracktion::engine::Track::minTrackHeight
The minimum height of this Track.
maxTrackHeight
const double tracktion::engine::Track::maxTrackHeight
The maximum height of this Track.
state
juce::ValueTree tracktion::engine::Track::state
The state of this Track.
pluginList
PluginList tracktion::engine::Track::pluginList
The Track's PluginList.
The documentation for this class was generated from the following file:
tracktion_Track.h