TracktionEngine: tracktion_engine::MouseHoverDetector Class Reference
tracktion_engine::MouseHoverDetector Class Reference abstract
Public Member Functions
MouseHoverDetector (int hoverTimeMillisecs_=400)
virtual ~MouseHoverDetector ()
void setHoverTimeMillisecs (int newTimeInMillisecs)
void setHoverComponent (juce::Component *newSourceComponent, bool wantsEventsForAllNestedChildComponents)
void hoverTimerCallback ()
void checkJustHoveredCallback ()
Protected Member Functions
virtual void mouseHovered (int mouseX, int mouseY)=0
virtual void mouseMovedAfterHover ()=0
Constructor & Destructor Documentation
MouseHoverDetector()
tracktion_engine::MouseHoverDetector::MouseHoverDetector (int hoverTimeMillisecs_ = 400)
~MouseHoverDetector()
virtual tracktion_engine::MouseHoverDetector::~MouseHoverDetector () virtual
References setHoverComponent().
Member Function Documentation
setHoverTimeMillisecs()
void tracktion_engine::MouseHoverDetector::setHoverTimeMillisecs (int newTimeInMillisecs)
setHoverComponent()
void tracktion_engine::MouseHoverDetector::setHoverComponent (juce::Component * newSourceComponent, bool wantsEventsForAllNestedChildComponents)
Referenced by ~MouseHoverDetector().
hoverTimerCallback()
void tracktion_engine::MouseHoverDetector::hoverTimerCallback ()
References mouseHovered().
checkJustHoveredCallback()
void tracktion_engine::MouseHoverDetector::checkJustHoveredCallback ()
References mouseMovedAfterHover().
mouseHovered()
virtual void tracktion_engine::MouseHoverDetector::mouseHovered (int mouseX, int mouseY) protected pure virtual
Implemented in tracktion_engine::CurveEditor.
Referenced by hoverTimerCallback().
mouseMovedAfterHover()
virtual void tracktion_engine::MouseHoverDetector::mouseMovedAfterHover () protected pure virtual
Implemented in tracktion_engine::CurveEditor.
Referenced by checkJustHoveredCallback().
The documentation for this class was generated from the following file:
tracktion_MouseHoverDetector.h