TracktionEngine: tracktion::engine::PluginAudioNode Class Reference
tracktion::engine::PluginAudioNode Class Reference
tracktion_engine » playback
#include <tracktion_PluginAudioNode.h>
Public Member Functions
PluginAudioNode (const Plugin::Ptr &p, AudioNode *in, bool denormalisationNoise)
~PluginAudioNode () override
void getAudioNodeProperties (AudioNodeProperties &info) override
void visitNodes (const VisitorFn &v) override
Plugin::Ptr getPlugin () const override
bool purgeSubNodes (bool keepAudio, bool keepMidi) override
Tells the node to delete any sub-nodes that don't produce the required type of output.
void prepareAudioNodeToPlay (const PlaybackInitialisationInfo &info) override
tells the node to initialise itself ready for playing from the given time.
bool isReadyToRender () override
double getLatencySeconds () const noexcept
void releaseAudioNodeResources () override
tells the node that play has stopped, and it can free up anything it no longer needs.
void renderAdding (const AudioRenderContext &rc) override
void renderOver (const AudioRenderContext &rc) override
virtual void renderPlugin (const AudioRenderContext &rc)
void prepareForNextBlock (const AudioRenderContext &rc) override
Public Member Functions inherited from tracktion::engine::AudioNode
AudioNode ()
virtual ~AudioNode ()
void callRenderAdding (const AudioRenderContext &)
void callRenderOver (const AudioRenderContext &)
Protected Member Functions
PluginRenderContext createPluginRenderContext (const AudioRenderContext &rc)
Protected Attributes
Plugin::Ptr plugin
std::unique_ptr< AudioNode > input
bool hasAudioInput = false
bool hasMidiInput = false
bool applyAntiDenormalisationNoise = false
bool hasInitialised = false
double latencySeconds = 0.0
Additional Inherited Members
Public Types inherited from tracktion::engine::AudioNode
using VisitorFn = std::function< void(AudioNode &)>
Static Public Member Functions inherited from tracktion::engine::AudioNode
template<typename CallbackType >
static void invokeSplitRender (const AudioRenderContext &rc, CallbackType &target)
Constructor & Destructor Documentation
PluginAudioNode()
tracktion::engine::PluginAudioNode::PluginAudioNode (const Plugin::Ptr & p, AudioNode * in, bool denormalisationNoise)
References input, and plugin.
~PluginAudioNode()
tracktion::engine::PluginAudioNode::~PluginAudioNode () override
References input, and releaseAudioNodeResources().
Member Function Documentation
getAudioNodeProperties()
void tracktion::engine::PluginAudioNode::getAudioNodeProperties (AudioNodeProperties & info) override virtual
Implements tracktion::engine::AudioNode.
References tracktion::engine::AudioNodeProperties::hasAudio, hasAudioInput, tracktion::engine::AudioNodeProperties::hasMidi, hasMidiInput, input, tracktion::engine::AudioNodeProperties::numberOfChannels, and plugin.
visitNodes()
void tracktion::engine::PluginAudioNode::visitNodes (const VisitorFn & v) override virtual
Implements tracktion::engine::AudioNode.
References input.
getPlugin()
Plugin::Ptr tracktion::engine::PluginAudioNode::getPlugin () const override virtual
Reimplemented from tracktion::engine::AudioNode.
References plugin.
purgeSubNodes()
bool tracktion::engine::PluginAudioNode::purgeSubNodes (bool keepAudio, bool keepMidi) override virtual
Tells the node to delete any sub-nodes that don't produce the required type of output.
This optimises out any unplayable bits of the audio graph. Returns true if this node should be kept, false if this node can itself be deleted.
Implements tracktion::engine::AudioNode.
References input, and plugin.
prepareAudioNodeToPlay()
void tracktion::engine::PluginAudioNode::prepareAudioNodeToPlay (const PlaybackInitialisationInfo &) override virtual
tells the node to initialise itself ready for playing from the given time.
This call may be made more than once before releaseAudioNodeResources() is called
Implements tracktion::engine::AudioNode.
References tracktion::engine::PlaybackInitialisationInfo::blockSizeSamples, hasInitialised, input, latencySeconds, plugin, tracktion::engine::PlaybackInitialisationInfo::sampleRate, and tracktion::engine::PlaybackInitialisationInfo::startTime.
isReadyToRender()
bool tracktion::engine::PluginAudioNode::isReadyToRender () override virtual
Implements tracktion::engine::AudioNode.
References input.
getLatencySeconds()
double tracktion::engine::PluginAudioNode::getLatencySeconds () const noexcept
References latencySeconds.
releaseAudioNodeResources()
void tracktion::engine::PluginAudioNode::releaseAudioNodeResources () override virtual
tells the node that play has stopped, and it can free up anything it no longer needs.
Implements tracktion::engine::AudioNode.
References hasInitialised, input, and plugin.
Referenced by ~PluginAudioNode().
renderAdding()
void tracktion::engine::PluginAudioNode::renderAdding (const AudioRenderContext & rc) override virtual
Implements tracktion::engine::AudioNode.
References tracktion::engine::AudioNode::callRenderOver(), tracktion::engine::AudioRenderContext::didPlayheadJump(), input, tracktion::engine::AudioRenderContext::isRendering, and plugin.
renderOver()
void tracktion::engine::PluginAudioNode::renderOver (const AudioRenderContext & rc) override virtual
Implements tracktion::engine::AudioNode.
References tracktion::engine::AudioRenderContext::didPlayheadJump(), input, tracktion::engine::AudioRenderContext::isRendering, latencySeconds, plugin, renderPlugin(), and tracktion::engine::AudioRenderContext::streamTime.
renderPlugin()
virtual void tracktion::engine::PluginAudioNode::renderPlugin (const AudioRenderContext & rc) virtual
References tracktion::engine::AudioRenderContext::addAntiDenormalisationNoise(), applyAntiDenormalisationNoise, createPluginRenderContext(), tracktion::engine::PlayHead::EditTimeWindow::editRange1, tracktion::engine::AudioRenderContext::getEditTime(), tracktion::engine::legacy::EditTimeRange::getStart(), tracktion::engine::AudioRenderContext::isContiguousWithPreviousBlock(), plugin, and SCOPED_REALTIME_CHECK.
Referenced by renderOver().
prepareForNextBlock()
void tracktion::engine::PluginAudioNode::prepareForNextBlock (const AudioRenderContext & rc) override virtual
Reimplemented from tracktion::engine::AudioNode.
References tracktion::engine::PlayHead::EditTimeWindow::editRange1, tracktion::engine::AudioRenderContext::getEditTime(), tracktion::engine::legacy::EditTimeRange::getStart(), input, and plugin.
createPluginRenderContext()
PluginRenderContext tracktion::engine::PluginAudioNode::createPluginRenderContext (const AudioRenderContext & rc) protected
References tracktion::engine::AudioRenderContext::bufferForMidiMessages, tracktion::engine::AudioRenderContext::bufferNumSamples, tracktion::engine::AudioRenderContext::bufferStartSample, tracktion::engine::AudioRenderContext::destBuffer, tracktion::engine::AudioRenderContext::destBufferChannels, tracktion::engine::PlayHead::EditTimeWindow::editRange1, tracktion::engine::AudioRenderContext::getEditTime(), tracktion::engine::PlayHead::isPlaying(), tracktion::engine::AudioRenderContext::isRendering, tracktion::engine::PlayHead::isUserDragging(), tracktion::engine::AudioRenderContext::midiBufferOffset, and tracktion::engine::AudioRenderContext::playhead.
Referenced by renderPlugin().
Member Data Documentation
plugin
Plugin::Ptr tracktion::engine::PluginAudioNode::plugin protected
Referenced by getAudioNodeProperties(), getPlugin(), PluginAudioNode(), prepareAudioNodeToPlay(), prepareForNextBlock(), purgeSubNodes(), releaseAudioNodeResources(), renderAdding(), renderOver(), and renderPlugin().
input
std::unique_ptr<AudioNode> tracktion::engine::PluginAudioNode::input protected
Referenced by getAudioNodeProperties(), isReadyToRender(), PluginAudioNode(), prepareAudioNodeToPlay(), prepareForNextBlock(), purgeSubNodes(), releaseAudioNodeResources(), renderAdding(), renderOver(), visitNodes(), and ~PluginAudioNode().
hasAudioInput
bool tracktion::engine::PluginAudioNode::hasAudioInput = false protected
Referenced by getAudioNodeProperties().
hasMidiInput
bool tracktion::engine::PluginAudioNode::hasMidiInput = false protected
Referenced by getAudioNodeProperties().
applyAntiDenormalisationNoise
bool tracktion::engine::PluginAudioNode::applyAntiDenormalisationNoise = false protected
Referenced by renderPlugin().
hasInitialised
bool tracktion::engine::PluginAudioNode::hasInitialised = false protected
Referenced by prepareAudioNodeToPlay(), and releaseAudioNodeResources().
latencySeconds
double tracktion::engine::PluginAudioNode::latencySeconds = 0.0 protected
Referenced by getLatencySeconds(), prepareAudioNodeToPlay(), and renderOver().
The documentation for this class was generated from the following file:
tracktion_PluginAudioNode.h