TracktionEngine: tracktion_engine::ControlSurface Class Reference
tracktion_engine::ControlSurface Class Reference abstract
Base class for types of control surface.
Public Member Functions
ControlSurface (ExternalControllerManager &)
~ControlSurface () override
virtual void initialiseDevice (bool connect)=0
virtual void shutDownDevice ()=0
virtual void updateOSCSettings (int, int, juce::String)
virtual void updateMiscFeatures ()=0
virtual void acceptMidiMessage (const juce::MidiMessage &)=0
virtual void moveFader (int channelNum, float newSliderPos)=0
virtual void moveMasterLevelFader (float newLeftSliderPos, float newRightSliderPos)=0
virtual void movePanPot (int channelNum, float newPan)=0
virtual void moveAux (int channel, const char *bus, float newPos)=0
virtual void clearAux (int)
virtual void updateSoloAndMute (int channelNum, Track::MuteAndSoloLightState, bool isBright)=0
virtual void soloCountChanged (bool anySoloTracks)=0
virtual void playStateChanged (bool isPlaying)=0
virtual void recordStateChanged (bool isRecording)=0
virtual void automationReadModeChanged (bool isReading)=0
virtual void automationWriteModeChanged (bool isWriting)=0
virtual void faderBankChanged (int newStartChannelNumber, const juce::StringArray &trackNames)=0
virtual void channelLevelChanged (int channel, float level)=0
virtual void trackSelectionChanged (int channel, bool isSelected)=0
virtual void trackRecordEnabled (int channel, bool isEnabled)=0
virtual void masterLevelsChanged (float leftLevel, float rightLevel)=0
virtual void timecodeChanged (int barsOrHours, int beatsOrMinutes, int ticksOrSeconds, int millisecs, bool isBarsBeats, bool isFrames)=0
virtual void clickOnOffChanged (bool isClickOn)=0
virtual void snapOnOffChanged (bool isSnapOn)=0
virtual void loopOnOffChanged (bool isLoopOn)=0
virtual void slaveOnOffChanged (bool isSlaving)=0
virtual void punchOnOffChanged (bool isPunching)=0
virtual void undoStatusChanged (bool, bool)
virtual void parameterChanged (int parameterNumber, const ParameterSetting &newValue)=0
virtual void clearParameter (int parameterNumber)=0
virtual void markerChanged (int parameterNumber, const MarkerSetting &newValue)=0
virtual void clearMarker (int parameterNumber)=0
virtual void auxBankChanged (int)
virtual bool wantsMessage (const juce::MidiMessage &)
virtual bool eatsAllMessages ()
virtual bool canSetEatsAllMessages ()
virtual void setEatsAllMessages (bool)
virtual bool canChangeSelectedPlugin ()
virtual void currentSelectionChanged (juce::String)
juce::String getSelectableDescription () override
Subclasses must return a description of what they are.
virtual bool showingPluginParams ()
virtual bool showingMarkers ()
virtual bool showingTracks ()
virtual void deleteController ()
virtual void pluginBypass (bool)
virtual bool isPluginSelected (Plugin *)
virtual void currentEditChanged (Edit *e)
Edit * getEdit () const noexcept
TransportControl * getTransport () const noexcept
void sendMidiCommandToController (const void *midiData, int numBytes)
void sendMidiCommandToController (const juce::MidiMessage &)
template<size_t size>
void sendMidiArray (const juce::uint8(&rawData)[size])
void userMovedFader (int channelNum, float newFaderPosition)
void userMovedPanPot (int channelNum, float newPanPosition)
void userMovedMasterLevelFader (float newLevel)
void userMovedMasterPanPot (float newLevel)
void userMovedAux (int channelNum, float newPosition)
void userPressedAux (int channelNum)
void userMovedQuickParam (float newLevel)
void userPressedSolo (int channelNum)
void userPressedSoloIsolate (int channelNum)
void userPressedMute (int channelNum, bool muteVolumeControl)
void userSelectedTrack (int channelNum)
void userSelectedClipInTrack (int channelNum)
void userSelectedPluginInTrack (int channelNum)
void userPressedRecEnable (int channelNum, bool enableEtoE)
void userPressedPlay ()
void userPressedRecord ()
void userPressedStop ()
void userPressedHome ()
void userPressedEnd ()
void userPressedMarkIn ()
void userPressedMarkOut ()
void userPressedAutomationReading ()
void userPressedAutomationWriting ()
void userToggledBeatsSecondsMode ()
void userPressedSave ()
void userPressedSaveAs ()
void userPressedArmAll ()
void userPressedJumpToMarkIn ()
void userPressedJumpToMarkOut ()
void userPressedZoomIn ()
void userPressedZoomOut ()
void userPressedZoomToFit ()
void userPressedCreateMarker ()
void userPressedNextMarker ()
void userPressedPreviousMarker ()
void userPressedRedo ()
void userPressedUndo ()
void userPressedAbort ()
void userPressedAbortRestart ()
void userPressedCut ()
void userPressedCopy ()
void userPressedPaste (bool insert)
void userPressedDelete (bool marked)
void userPressedZoomFitToTracks ()
void userPressedInsertTempoChange ()
void userPressedInsertPitchChange ()
void userPressedInsertTimeSigChange ()
void userToggledVideoWindow ()
void userPressedFreeze ()
void userPressedClearAllSolo ()
void userPressedClearAllMute ()
void userToggledLoopOnOff ()
void userToggledPunchOnOff ()
void userToggledClickOnOff ()
void userToggledSnapOnOff ()
void userToggledSlaveOnOff ()
void userToggledEtoE ()
void userToggledScroll ()
void userSkippedToNextMarkerLeft ()
void userSkippedToNextMarkerRight ()
void userNudgedLeft ()
void userNudgedRight ()
void userZoomedIn ()
void userZoomedOut ()
void userScrolledTracksUp ()
void userScrolledTracksDown ()
void userScrolledTracksLeft ()
void userScrolledTracksRight ()
void userZoomedTracksIn ()
void userZoomedTracksOut ()
void selectOtherObject (SelectableClass::Relationship, bool moveFromCurrentPlugin)
void muteOrUnmutePluginsInTrack ()
void userChangedFaderBanks (int channelNumDelta)
void userMovedJogWheel (float amount)
void userChangedRewindButton (bool isButtonDown)
void userChangedFastForwardButton (bool isButtonDown)
void userMovedParameterControl (int parameter, float newValue)
void userPressedParameterControl (int paramNumber)
void userChangedParameterBank (int deltaParams)
void userChangedMarkerBank (int deltaMarkers)
void userPressedGoToMarker (int marker)
void userChangedAuxBank (int delta)
void updateDeviceState ()
void redrawSelectedPlugin ()
void redrawSelectedTracks ()
Edit * getEditIfOnEditScreen () const
Public Member Functions inherited from tracktion_engine::Selectable
Selectable ()
virtual ~Selectable ()
virtual void selectionStatusChanged (bool isNowSelected)
Can be overridden to tell this object that it has just been selected or deselected.
virtual void changed ()
This should be called to send a change notification to any SelectableListeners that are registered with this object.
virtual void selectableAboutToBeDeleted ()
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void addSelectableListener (SelectableListener *)
void removeSelectableListener (SelectableListener *)
void cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
void deselect ()
void propertiesChanged ()
void notifyListenersOfDeletion ()
WeakRef getWeakRef ()
Public Attributes
juce::String deviceDescription
These values need to be set by the subclass.
bool needsMidiChannel = true
bool needsMidiBackChannel = false
bool needsOSCSocket = false
bool wantsClock = false
bool deletable = false
int numberOfFaderChannels = 0
int numCharactersForTrackNames = 0
bool allowBankingOffEnd = false
int numParameterControls = 0
int numCharactersForParameterLabels = 0
int numMarkers = 0
int numCharactersForMarkerLabels = 0
int numAuxes = 0
int numCharactersForAuxLabels = 0
bool wantsAuxBanks = 0
bool followsTrackSelection = false
Engine & engine
ExternalControllerManager & externalControllerManager
ExternalController * owner = nullptr
Public Attributes inherited from tracktion_engine::Selectable
WeakRef::Master masterReference
Additional Inherited Members
Public Types inherited from tracktion_engine::Selectable
using WeakRef = juce::WeakReference< Selectable >
Static Public Member Functions inherited from tracktion_engine::Selectable
static void initialise ()
static bool isSelectableValid (const Selectable *) noexcept
checks whether this object has been deleted.
Detailed Description
Base class for types of control surface.
Constructor & Destructor Documentation
ControlSurface()
tracktion_engine::ControlSurface::ControlSurface (ExternalControllerManager &)
~ControlSurface()
tracktion_engine::ControlSurface::~ControlSurface () override
Member Function Documentation
initialiseDevice()
virtual void tracktion_engine::ControlSurface::initialiseDevice (bool connect) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::MackieMCU, tracktion_engine::NovationRemoteSl, tracktion_engine::MackieXT, tracktion_engine::RemoteSLCompact, and tracktion_engine::TranzportControlSurface.
shutDownDevice()
virtual void tracktion_engine::ControlSurface::shutDownDevice () pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::MackieMCU, tracktion_engine::NovationRemoteSl, tracktion_engine::MackieXT, tracktion_engine::RemoteSLCompact, and tracktion_engine::TranzportControlSurface.
updateOSCSettings()
virtual void tracktion_engine::ControlSurface::updateOSCSettings (int , int , juce::String) virtual
Reimplemented in tracktion_engine::CustomControlSurface.
updateMiscFeatures()
virtual void tracktion_engine::ControlSurface::updateMiscFeatures () pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::MackieMCU, tracktion_engine::NovationRemoteSl, tracktion_engine::TranzportControlSurface, tracktion_engine::MackieXT, and tracktion_engine::RemoteSLCompact.
acceptMidiMessage()
virtual void tracktion_engine::ControlSurface::acceptMidiMessage (const juce::MidiMessage &) pure virtual
Implemented in tracktion_engine::MackieXT, tracktion_engine::CustomControlSurface, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::MackieMCU, tracktion_engine::NovationRemoteSl, tracktion_engine::TranzportControlSurface, and tracktion_engine::RemoteSLCompact.
moveFader()
virtual void tracktion_engine::ControlSurface::moveFader (int channelNum, float newSliderPos) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::NovationRemoteSl, tracktion_engine::TranzportControlSurface, tracktion_engine::MackieXT, and tracktion_engine::RemoteSLCompact.
moveMasterLevelFader()
virtual void tracktion_engine::ControlSurface::moveMasterLevelFader (float newLeftSliderPos, float newRightSliderPos) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::NovationRemoteSl, tracktion_engine::TranzportControlSurface, tracktion_engine::MackieXT, and tracktion_engine::RemoteSLCompact.
movePanPot()
virtual void tracktion_engine::ControlSurface::movePanPot (int channelNum, float newPan) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::NovationRemoteSl, tracktion_engine::TranzportControlSurface, tracktion_engine::MackieXT, and tracktion_engine::RemoteSLCompact.
moveAux()
virtual void tracktion_engine::ControlSurface::moveAux (int channel, const char * bus, float newPos) pure virtual
Implemented in tracktion_engine::MackieMCU, tracktion_engine::MackieC4, tracktion_engine::CustomControlSurface, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::NovationRemoteSl, tracktion_engine::TranzportControlSurface, tracktion_engine::MackieXT, and tracktion_engine::RemoteSLCompact.
clearAux()
virtual void tracktion_engine::ControlSurface::clearAux (int) virtual
Reimplemented in tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, and tracktion_engine::RemoteSLCompact.
updateSoloAndMute()
virtual void tracktion_engine::ControlSurface::updateSoloAndMute (int channelNum, Track::MuteAndSoloLightState , bool isBright) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::NovationRemoteSl, tracktion_engine::RemoteSLCompact, tracktion_engine::TranzportControlSurface, and tracktion_engine::MackieXT.
soloCountChanged()
virtual void tracktion_engine::ControlSurface::soloCountChanged (bool anySoloTracks) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::NovationRemoteSl, tracktion_engine::RemoteSLCompact, tracktion_engine::TranzportControlSurface, and tracktion_engine::MackieXT.
playStateChanged()
virtual void tracktion_engine::ControlSurface::playStateChanged (bool isPlaying) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::NovationRemoteSl, tracktion_engine::RemoteSLCompact, tracktion_engine::TranzportControlSurface, and tracktion_engine::MackieXT.
recordStateChanged()
virtual void tracktion_engine::ControlSurface::recordStateChanged (bool isRecording) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::NovationRemoteSl, tracktion_engine::RemoteSLCompact, tracktion_engine::TranzportControlSurface, and tracktion_engine::MackieXT.
automationReadModeChanged()
virtual void tracktion_engine::ControlSurface::automationReadModeChanged (bool isReading) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::NovationRemoteSl, tracktion_engine::RemoteSLCompact, tracktion_engine::TranzportControlSurface, and tracktion_engine::MackieXT.
automationWriteModeChanged()
virtual void tracktion_engine::ControlSurface::automationWriteModeChanged (bool isWriting) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::NovationRemoteSl, tracktion_engine::RemoteSLCompact, tracktion_engine::TranzportControlSurface, and tracktion_engine::MackieXT.
faderBankChanged()
virtual void tracktion_engine::ControlSurface::faderBankChanged (int newStartChannelNumber, const juce::StringArray & trackNames) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::NovationRemoteSl, tracktion_engine::RemoteSLCompact, tracktion_engine::TranzportControlSurface, and tracktion_engine::MackieXT.
channelLevelChanged()
virtual void tracktion_engine::ControlSurface::channelLevelChanged (int channel, float level) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::NovationRemoteSl, tracktion_engine::RemoteSLCompact, tracktion_engine::TranzportControlSurface, and tracktion_engine::MackieXT.
trackSelectionChanged()
virtual void tracktion_engine::ControlSurface::trackSelectionChanged (int channel, bool isSelected) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::NovationRemoteSl, tracktion_engine::RemoteSLCompact, tracktion_engine::TranzportControlSurface, and tracktion_engine::MackieXT.
trackRecordEnabled()
virtual void tracktion_engine::ControlSurface::trackRecordEnabled (int channel, bool isEnabled) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::MackieC4, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::NovationRemoteSl, tracktion_engine::RemoteSLCompact, tracktion_engine::TranzportControlSurface, and tracktion_engine::MackieXT.
masterLevelsChanged()
virtual void tracktion_engine::ControlSurface::masterLevelsChanged (float leftLevel, float rightLevel) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::NovationRemoteSl, tracktion_engine::RemoteSLCompact, tracktion_engine::TranzportControlSurface, and tracktion_engine::MackieXT.
timecodeChanged()
virtual void tracktion_engine::ControlSurface::timecodeChanged (int barsOrHours, int beatsOrMinutes, int ticksOrSeconds, int millisecs, bool isBarsBeats, bool isFrames) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::NovationRemoteSl, tracktion_engine::RemoteSLCompact, tracktion_engine::TranzportControlSurface, and tracktion_engine::MackieXT.
clickOnOffChanged()
virtual void tracktion_engine::ControlSurface::clickOnOffChanged (bool isClickOn) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::NovationRemoteSl, tracktion_engine::RemoteSLCompact, tracktion_engine::TranzportControlSurface, and tracktion_engine::MackieXT.
snapOnOffChanged()
virtual void tracktion_engine::ControlSurface::snapOnOffChanged (bool isSnapOn) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::NovationRemoteSl, tracktion_engine::RemoteSLCompact, tracktion_engine::TranzportControlSurface, and tracktion_engine::MackieXT.
loopOnOffChanged()
virtual void tracktion_engine::ControlSurface::loopOnOffChanged (bool isLoopOn) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::NovationRemoteSl, tracktion_engine::RemoteSLCompact, tracktion_engine::TranzportControlSurface, and tracktion_engine::MackieXT.
slaveOnOffChanged()
virtual void tracktion_engine::ControlSurface::slaveOnOffChanged (bool isSlaving) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::NovationRemoteSl, tracktion_engine::RemoteSLCompact, tracktion_engine::TranzportControlSurface, and tracktion_engine::MackieXT.
punchOnOffChanged()
virtual void tracktion_engine::ControlSurface::punchOnOffChanged (bool isPunching) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::NovationRemoteSl, tracktion_engine::RemoteSLCompact, tracktion_engine::TranzportControlSurface, and tracktion_engine::MackieXT.
undoStatusChanged()
virtual void tracktion_engine::ControlSurface::undoStatusChanged (bool , bool) virtual
Reimplemented in tracktion_engine::MackieMCU, and tracktion_engine::RemoteSLCompact.
parameterChanged()
virtual void tracktion_engine::ControlSurface::parameterChanged (int parameterNumber, const ParameterSetting & newValue) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::TranzportControlSurface, tracktion_engine::MackieXT, tracktion_engine::MackieC4, tracktion_engine::MackieMCU, tracktion_engine::RemoteSLCompact, and tracktion_engine::NovationRemoteSl.
clearParameter()
virtual void tracktion_engine::ControlSurface::clearParameter (int parameterNumber) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::RemoteSLCompact, tracktion_engine::NovationRemoteSl, tracktion_engine::TranzportControlSurface, tracktion_engine::MackieXT, and tracktion_engine::MackieC4.
markerChanged()
virtual void tracktion_engine::ControlSurface::markerChanged (int parameterNumber, const MarkerSetting & newValue) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::TranzportControlSurface, tracktion_engine::MackieXT, tracktion_engine::MackieMCU, tracktion_engine::NovationRemoteSl, and tracktion_engine::RemoteSLCompact.
clearMarker()
virtual void tracktion_engine::ControlSurface::clearMarker (int parameterNumber) pure virtual
Implemented in tracktion_engine::CustomControlSurface, tracktion_engine::MackieMCU, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::MackieC4, tracktion_engine::NovationRemoteSl, tracktion_engine::TranzportControlSurface, tracktion_engine::RemoteSLCompact, and tracktion_engine::MackieXT.
auxBankChanged()
virtual void tracktion_engine::ControlSurface::auxBankChanged (int) virtual
Reimplemented in tracktion_engine::MackieMCU, tracktion_engine::MackieC4, and tracktion_engine::RemoteSLCompact.
wantsMessage()
virtual bool tracktion_engine::ControlSurface::wantsMessage (const juce::MidiMessage &) virtual
Reimplemented in tracktion_engine::CustomControlSurface, tracktion_engine::RemoteSLCompact, and tracktion_engine::NovationRemoteSl.
eatsAllMessages()
virtual bool tracktion_engine::ControlSurface::eatsAllMessages () virtual
Reimplemented in tracktion_engine::CustomControlSurface, tracktion_engine::RemoteSLCompact, and tracktion_engine::NovationRemoteSl.
canSetEatsAllMessages()
virtual bool tracktion_engine::ControlSurface::canSetEatsAllMessages () virtual
Reimplemented in tracktion_engine::CustomControlSurface, and tracktion_engine::RemoteSLCompact.
setEatsAllMessages()
virtual void tracktion_engine::ControlSurface::setEatsAllMessages (bool) virtual
Reimplemented in tracktion_engine::CustomControlSurface, and tracktion_engine::RemoteSLCompact.
canChangeSelectedPlugin()
virtual bool tracktion_engine::ControlSurface::canChangeSelectedPlugin () virtual
Reimplemented in tracktion_engine::CustomControlSurface, tracktion_engine::RemoteSLCompact, tracktion_engine::MackieC4, tracktion_engine::NovationRemoteSl, and tracktion_engine::TranzportControlSurface.
currentSelectionChanged()
virtual void tracktion_engine::ControlSurface::currentSelectionChanged (juce::String) virtual
Reimplemented in tracktion_engine::CustomControlSurface, tracktion_engine::AlphaTrackControlSurface, tracktion_engine::RemoteSLCompact, tracktion_engine::NovationRemoteSl, tracktion_engine::TranzportControlSurface, and tracktion_engine::MackieC4.
getSelectableDescription()
juce::String tracktion_engine::ControlSurface::getSelectableDescription () override virtual
Subclasses must return a description of what they are.
Implements tracktion_engine::Selectable.
showingPluginParams()
virtual bool tracktion_engine::ControlSurface::showingPluginParams () virtual
Reimplemented in tracktion_engine::MackieMCU, tracktion_engine::RemoteSLCompact, tracktion_engine::MackieC4, and tracktion_engine::NovationRemoteSl.
showingMarkers()
virtual bool tracktion_engine::ControlSurface::showingMarkers () virtual
Reimplemented in tracktion_engine::MackieMCU, and tracktion_engine::RemoteSLCompact.
showingTracks()
virtual bool tracktion_engine::ControlSurface::showingTracks () virtual
Reimplemented in tracktion_engine::MackieMCU, tracktion_engine::RemoteSLCompact, tracktion_engine::MackieC4, and tracktion_engine::NovationRemoteSl.
deleteController()
virtual void tracktion_engine::ControlSurface::deleteController () virtual
Reimplemented in tracktion_engine::CustomControlSurface.
pluginBypass()
virtual void tracktion_engine::ControlSurface::pluginBypass (bool) virtual
Reimplemented in tracktion_engine::MackieC4, tracktion_engine::RemoteSLCompact, and tracktion_engine::AlphaTrackControlSurface.
isPluginSelected()
virtual bool tracktion_engine::ControlSurface::isPluginSelected (Plugin *) virtual
Reimplemented in tracktion_engine::AlphaTrackControlSurface, and tracktion_engine::RemoteSLCompact.
currentEditChanged()
virtual void tracktion_engine::ControlSurface::currentEditChanged (Edit * e) virtual
getEdit()
Edit* tracktion_engine::ControlSurface::getEdit () const noexcept
Referenced by tracktion_engine::ExternalController::getEdit().
getTransport()
TransportControl* tracktion_engine::ControlSurface::getTransport () const noexcept
References tracktion_engine::Edit::getTransport().
Referenced by tracktion_engine::ExternalController::getTransport().
sendMidiCommandToController() [1/2]
void tracktion_engine::ControlSurface::sendMidiCommandToController (const void * midiData, int numBytes)
Referenced by sendMidiArray().
sendMidiCommandToController() [2/2]
void tracktion_engine::ControlSurface::sendMidiCommandToController (const juce::MidiMessage &)
sendMidiArray()
template<size_t size> void tracktion_engine::ControlSurface::sendMidiArray (const juce::uint8(&) rawData[size])
References sendMidiCommandToController().
userMovedFader()
void tracktion_engine::ControlSurface::userMovedFader (int channelNum, float newFaderPosition)
userMovedPanPot()
void tracktion_engine::ControlSurface::userMovedPanPot (int channelNum, float newPanPosition)
userMovedMasterLevelFader()
void tracktion_engine::ControlSurface::userMovedMasterLevelFader (float newLevel)
userMovedMasterPanPot()
void tracktion_engine::ControlSurface::userMovedMasterPanPot (float newLevel)
userMovedAux()
void tracktion_engine::ControlSurface::userMovedAux (int channelNum, float newPosition)
userPressedAux()
void tracktion_engine::ControlSurface::userPressedAux (int channelNum)
userMovedQuickParam()
void tracktion_engine::ControlSurface::userMovedQuickParam (float newLevel)
userPressedSolo()
void tracktion_engine::ControlSurface::userPressedSolo (int channelNum)
userPressedSoloIsolate()
void tracktion_engine::ControlSurface::userPressedSoloIsolate (int channelNum)
userPressedMute()
void tracktion_engine::ControlSurface::userPressedMute (int channelNum, bool muteVolumeControl)
userSelectedTrack()
void tracktion_engine::ControlSurface::userSelectedTrack (int channelNum)
userSelectedClipInTrack()
void tracktion_engine::ControlSurface::userSelectedClipInTrack (int channelNum)
userSelectedPluginInTrack()
void tracktion_engine::ControlSurface::userSelectedPluginInTrack (int channelNum)
userPressedRecEnable()
void tracktion_engine::ControlSurface::userPressedRecEnable (int channelNum, bool enableEtoE)
userPressedPlay()
void tracktion_engine::ControlSurface::userPressedPlay ()
userPressedRecord()
void tracktion_engine::ControlSurface::userPressedRecord ()
userPressedStop()
void tracktion_engine::ControlSurface::userPressedStop ()
userPressedHome()
void tracktion_engine::ControlSurface::userPressedHome ()
userPressedEnd()
void tracktion_engine::ControlSurface::userPressedEnd ()
userPressedMarkIn()
void tracktion_engine::ControlSurface::userPressedMarkIn ()
userPressedMarkOut()
void tracktion_engine::ControlSurface::userPressedMarkOut ()
userPressedAutomationReading()
void tracktion_engine::ControlSurface::userPressedAutomationReading ()
userPressedAutomationWriting()
void tracktion_engine::ControlSurface::userPressedAutomationWriting ()
userToggledBeatsSecondsMode()
void tracktion_engine::ControlSurface::userToggledBeatsSecondsMode ()
userPressedSave()
void tracktion_engine::ControlSurface::userPressedSave ()
userPressedSaveAs()
void tracktion_engine::ControlSurface::userPressedSaveAs ()
userPressedArmAll()
void tracktion_engine::ControlSurface::userPressedArmAll ()
userPressedJumpToMarkIn()
void tracktion_engine::ControlSurface::userPressedJumpToMarkIn ()
userPressedJumpToMarkOut()
void tracktion_engine::ControlSurface::userPressedJumpToMarkOut ()
userPressedZoomIn()
void tracktion_engine::ControlSurface::userPressedZoomIn ()
userPressedZoomOut()
void tracktion_engine::ControlSurface::userPressedZoomOut ()
userPressedZoomToFit()
void tracktion_engine::ControlSurface::userPressedZoomToFit ()
userPressedCreateMarker()
void tracktion_engine::ControlSurface::userPressedCreateMarker ()
userPressedNextMarker()
void tracktion_engine::ControlSurface::userPressedNextMarker ()
userPressedPreviousMarker()
void tracktion_engine::ControlSurface::userPressedPreviousMarker ()
userPressedRedo()
void tracktion_engine::ControlSurface::userPressedRedo ()
userPressedUndo()
void tracktion_engine::ControlSurface::userPressedUndo ()
userPressedAbort()
void tracktion_engine::ControlSurface::userPressedAbort ()
userPressedAbortRestart()
void tracktion_engine::ControlSurface::userPressedAbortRestart ()
userPressedCut()
void tracktion_engine::ControlSurface::userPressedCut ()
userPressedCopy()
void tracktion_engine::ControlSurface::userPressedCopy ()
userPressedPaste()
void tracktion_engine::ControlSurface::userPressedPaste (bool insert)
userPressedDelete()
void tracktion_engine::ControlSurface::userPressedDelete (bool marked)
userPressedZoomFitToTracks()
void tracktion_engine::ControlSurface::userPressedZoomFitToTracks ()
userPressedInsertTempoChange()
void tracktion_engine::ControlSurface::userPressedInsertTempoChange ()
userPressedInsertPitchChange()
void tracktion_engine::ControlSurface::userPressedInsertPitchChange ()
userPressedInsertTimeSigChange()
void tracktion_engine::ControlSurface::userPressedInsertTimeSigChange ()
userToggledVideoWindow()
void tracktion_engine::ControlSurface::userToggledVideoWindow ()
userPressedFreeze()
void tracktion_engine::ControlSurface::userPressedFreeze ()
userPressedClearAllSolo()
void tracktion_engine::ControlSurface::userPressedClearAllSolo ()
userPressedClearAllMute()
void tracktion_engine::ControlSurface::userPressedClearAllMute ()
userToggledLoopOnOff()
void tracktion_engine::ControlSurface::userToggledLoopOnOff ()
userToggledPunchOnOff()
void tracktion_engine::ControlSurface::userToggledPunchOnOff ()
userToggledClickOnOff()
void tracktion_engine::ControlSurface::userToggledClickOnOff ()
userToggledSnapOnOff()
void tracktion_engine::ControlSurface::userToggledSnapOnOff ()
userToggledSlaveOnOff()
void tracktion_engine::ControlSurface::userToggledSlaveOnOff ()
userToggledEtoE()
void tracktion_engine::ControlSurface::userToggledEtoE ()
userToggledScroll()
void tracktion_engine::ControlSurface::userToggledScroll ()
userSkippedToNextMarkerLeft()
void tracktion_engine::ControlSurface::userSkippedToNextMarkerLeft ()
userSkippedToNextMarkerRight()
void tracktion_engine::ControlSurface::userSkippedToNextMarkerRight ()
userNudgedLeft()
void tracktion_engine::ControlSurface::userNudgedLeft ()
userNudgedRight()
void tracktion_engine::ControlSurface::userNudgedRight ()
userZoomedIn()
void tracktion_engine::ControlSurface::userZoomedIn ()
userZoomedOut()
void tracktion_engine::ControlSurface::userZoomedOut ()
userScrolledTracksUp()
void tracktion_engine::ControlSurface::userScrolledTracksUp ()
userScrolledTracksDown()
void tracktion_engine::ControlSurface::userScrolledTracksDown ()
userScrolledTracksLeft()
void tracktion_engine::ControlSurface::userScrolledTracksLeft ()
userScrolledTracksRight()
void tracktion_engine::ControlSurface::userScrolledTracksRight ()
userZoomedTracksIn()
void tracktion_engine::ControlSurface::userZoomedTracksIn ()
userZoomedTracksOut()
void tracktion_engine::ControlSurface::userZoomedTracksOut ()
selectOtherObject()
void tracktion_engine::ControlSurface::selectOtherObject (SelectableClass::Relationship , bool moveFromCurrentPlugin)
muteOrUnmutePluginsInTrack()
void tracktion_engine::ControlSurface::muteOrUnmutePluginsInTrack ()
userChangedFaderBanks()
void tracktion_engine::ControlSurface::userChangedFaderBanks (int channelNumDelta)
userMovedJogWheel()
void tracktion_engine::ControlSurface::userMovedJogWheel (float amount)
userChangedRewindButton()
void tracktion_engine::ControlSurface::userChangedRewindButton (bool isButtonDown)
userChangedFastForwardButton()
void tracktion_engine::ControlSurface::userChangedFastForwardButton (bool isButtonDown)
userMovedParameterControl()
void tracktion_engine::ControlSurface::userMovedParameterControl (int parameter, float newValue)
userPressedParameterControl()
void tracktion_engine::ControlSurface::userPressedParameterControl (int paramNumber)
userChangedParameterBank()
void tracktion_engine::ControlSurface::userChangedParameterBank (int deltaParams)
userChangedMarkerBank()
void tracktion_engine::ControlSurface::userChangedMarkerBank (int deltaMarkers)
userPressedGoToMarker()
void tracktion_engine::ControlSurface::userPressedGoToMarker (int marker)
userChangedAuxBank()
void tracktion_engine::ControlSurface::userChangedAuxBank (int delta)
updateDeviceState()
void tracktion_engine::ControlSurface::updateDeviceState ()
redrawSelectedPlugin()
void tracktion_engine::ControlSurface::redrawSelectedPlugin ()
redrawSelectedTracks()
void tracktion_engine::ControlSurface::redrawSelectedTracks ()
getEditIfOnEditScreen()
Edit* tracktion_engine::ControlSurface::getEditIfOnEditScreen () const
Member Data Documentation
deviceDescription
juce::String tracktion_engine::ControlSurface::deviceDescription
These values need to be set by the subclass.
needsMidiChannel
bool tracktion_engine::ControlSurface::needsMidiChannel = true
needsMidiBackChannel
bool tracktion_engine::ControlSurface::needsMidiBackChannel = false
needsOSCSocket
bool tracktion_engine::ControlSurface::needsOSCSocket = false
Referenced by tracktion_engine::CustomControlSurface::allowsManualEditing().
wantsClock
bool tracktion_engine::ControlSurface::wantsClock = false
deletable
bool tracktion_engine::ControlSurface::deletable = false
numberOfFaderChannels
int tracktion_engine::ControlSurface::numberOfFaderChannels = 0
numCharactersForTrackNames
int tracktion_engine::ControlSurface::numCharactersForTrackNames = 0
allowBankingOffEnd
bool tracktion_engine::ControlSurface::allowBankingOffEnd = false
numParameterControls
int tracktion_engine::ControlSurface::numParameterControls = 0
numCharactersForParameterLabels
int tracktion_engine::ControlSurface::numCharactersForParameterLabels = 0
numMarkers
int tracktion_engine::ControlSurface::numMarkers = 0
numCharactersForMarkerLabels
int tracktion_engine::ControlSurface::numCharactersForMarkerLabels = 0
numAuxes
int tracktion_engine::ControlSurface::numAuxes = 0
numCharactersForAuxLabels
int tracktion_engine::ControlSurface::numCharactersForAuxLabels = 0
wantsAuxBanks
bool tracktion_engine::ControlSurface::wantsAuxBanks = 0
followsTrackSelection
bool tracktion_engine::ControlSurface::followsTrackSelection = false
engine
Engine& tracktion_engine::ControlSurface::engine
externalControllerManager
ExternalControllerManager& tracktion_engine::ControlSurface::externalControllerManager
owner
ExternalController* tracktion_engine::ControlSurface::owner = nullptr
The documentation for this class was generated from the following file:
tracktion_ControlSurface.h