TracktionEngine: tracktion_graph::Node Class Reference
tracktion_graph::Node Class Reference abstract
Main graph Node processor class.
Classes
struct AudioAndMidiBuffer
Contains the buffers for a processing operation.
struct ProcessContext
Struct to describe a single iteration of a process call.
Public Member Functions
Node ()=default
virtual ~Node ()=default
void initialise (const PlaybackInitialisationInfo &)
Call once after the graph has been constructed to initialise buffers etc.
void prepareForNextBlock (juce::Range< int64_t > referenceSampleRange)
Call before processing the next block, used to reset the process status.
void process (juce::Range< int64_t > referenceSampleRange)
Call to process the node, which will in turn call the process method with the buffers to fill.
bool hasProcessed () const
Returns true if this node has processed and its outputs can be retrieved.
AudioAndMidiBuffer getProcessedOutput ()
Returns the processed audio and MIDI output.
virtual bool transform (Node &)
Called after construction to give the node a chance to modify its topology.
virtual std::vector< Node * > getDirectInputNodes ()
Should return all the inputs directly feeding in to this node.
virtual NodeProperties getNodeProperties ()=0
Should return the properties of the node.
virtual bool isReadyToProcess ()=0
Should return true when this node is ready to be processed.
void retain ()
Retains the buffers so they won't be deallocated after the Node has processed.
void release ()
Releases the buffers allowing internal storage to be deallocated.
virtual size_t getAllocatedBytes () const
Public Attributes
void * internal = nullptr
int numOutputNodes = -1
Protected Member Functions
virtual void prepareToPlay (const PlaybackInitialisationInfo &)
Called once before playback begins for each node.
virtual void prefetchBlock (juce::Range< int64_t >)
Called before once on all Nodes before they are processed.
virtual void process (ProcessContext &)=0
Called when the node is to be processed.
void setOptimisations (NodeOptimisations)
This can be called to provide some hints about allocating or playing back a Node to improve efficiency.
void setAudioOutput (Node *sourceNode, const choc::buffer::ChannelArrayView< float > &)
This can be called during your process function to set a view to the output.
Detailed Description
Main graph Node processor class.
Nodes are combined together to form a graph with a root Node which can then be initialsed and processed.
Subclasses should implement the various virtual methods but never call these directly. They will be called automatically by the non-virtual methods.
Constructor & Destructor Documentation
Node()
tracktion_graph::Node::Node () default
~Node()
virtual tracktion_graph::Node::~Node () virtual default
Member Function Documentation
initialise()
void tracktion_graph::Node::initialise (const PlaybackInitialisationInfo & info)
Call once after the graph has been constructed to initialise buffers etc.
References tracktion_graph::NodeOptimisations::allocate, tracktion_graph::PlaybackInitialisationInfo::allocateAudioBuffer, tracktion_graph::PlaybackInitialisationInfo::blockSize, tracktion_graph::PlaybackInitialisationInfo::deallocateAudioBuffer, getDirectInputNodes(), getNodeProperties(), prepareToPlay(), and tracktion_graph::yes.
prepareForNextBlock()
void tracktion_graph::Node::prepareForNextBlock (juce::Range< int64_t > referenceSampleRange)
Call before processing the next block, used to reset the process status.
References getDirectInputNodes(), prefetchBlock(), and retain().
process() [1/2]
void tracktion_graph::Node::process (juce::Range< int64_t > referenceSampleRange)
Call to process the node, which will in turn call the process method with the buffers to fill.
Parameters
referenceSampleRange The monotonic stream time in samples. This will be passed to the ProcessContext during the process callback so nodes can use this to determine file reading positions etc. Some nodes may ignore this completely but it should at the least specify the number to samples to process in this block.
References tracktion_graph::NodeOptimisations::allocate, tracktion_engine::MidiMessageArray::clear(), tracktion_graph::NodeOptimisations::clear, release(), and tracktion_graph::yes.
hasProcessed()
bool tracktion_graph::Node::hasProcessed () const
Returns true if this node has processed and its outputs can be retrieved.
Referenced by getProcessedOutput(), and tracktion_graph::LatencyNode::isReadyToProcess().
getProcessedOutput()
Node::AudioAndMidiBuffer tracktion_graph::Node::getProcessedOutput ()
Returns the processed audio and MIDI output.
Must only be called after hasProcessed returns true.
References hasProcessed().
Referenced by tracktion_graph::LatencyNode::process(), and tracktion_graph::NodePlayer::processPostorderedNodesSingleThreaded().
transform()
virtual bool tracktion_graph::Node::transform (Node &) virtual
Called after construction to give the node a chance to modify its topology.
This should return true if any changes were made to the topology as this indicates that the method may need to be called again after other nodes have had their toplogy changed.
Reimplemented in tracktion_graph::ReturnNode, tracktion_graph::SummingNode, and tracktion_graph::ConnectedNode.
getDirectInputNodes()
virtual std::vector<Node*> tracktion_graph::Node::getDirectInputNodes () virtual
Should return all the inputs directly feeding in to this node.
Reimplemented in tracktion_graph::ForwardingNode, tracktion_graph::SinkNode, tracktion_graph::ChannelRemappingNode, tracktion_graph::ReturnNode, tracktion_graph::SendNode, tracktion_graph::GainNode, tracktion_graph::FunctionNode, tracktion_graph::BasicSummingNode, tracktion_graph::SummingNode, tracktion_engine::TrackMutingNode, tracktion_graph::ConnectedNode, tracktion_engine::ClickNode, tracktion_engine::InsertSendNode, tracktion_engine::PluginNode, tracktion_graph::LatencyNode, tracktion_engine::ModifierNode, tracktion_engine::PlayHeadPositionNode, tracktion_engine::CombiningNode, tracktion_engine::LevelMeasurerProcessingNode, tracktion_engine::InsertSendReturnDependencyNode, tracktion_engine::FadeInOutNode, tracktion_engine::InsertReturnNode, tracktion_engine::LiveMidiInjectingNode, tracktion_engine::TimeStretchingWaveNode, tracktion_engine::LiveMidiOutputNode, tracktion_engine::MelodyneNode, tracktion_engine::MidiOutputDeviceInstanceInjectingNode, tracktion_engine::RackReturnNode, tracktion_engine::TimedMutingNode, tracktion_engine::RackInstanceNode, tracktion_engine::LevelMeasuringNode, tracktion_engine::TrackMidiInputDeviceNode, tracktion_engine::SharedLevelMeasuringNode, and tracktion_engine::TrackWaveInputDeviceNode.
Referenced by initialise(), tracktion_graph::test_utilities::logGraph(), prepareForNextBlock(), tracktion_graph::detail::VisitNodesWithRecord::visit(), and tracktion_graph::detail::VisitNodesWithRecordBFS::visit().
getNodeProperties()
virtual NodeProperties tracktion_graph::Node::getNodeProperties () pure virtual
Should return the properties of the node.
This should not be called until after initialise.
Implemented in tracktion_graph::ForwardingNode, tracktion_graph::SinkNode, tracktion_graph::ChannelRemappingNode, tracktion_graph::ReturnNode, tracktion_graph::SendNode, tracktion_graph::GainNode, tracktion_graph::FunctionNode, tracktion_graph::BasicSummingNode, tracktion_graph::SilentNode, tracktion_graph::SinNode, tracktion_engine::TrackMutingNode, tracktion_graph::SummingNode, tracktion_engine::ClickNode, tracktion_graph::ConnectedNode, tracktion_engine::InsertSendNode, tracktion_engine::PluginNode, tracktion_engine::ModifierNode, tracktion_engine::SpeedRampWaveNode, tracktion_graph::LatencyNode, tracktion_engine::CombiningNode, tracktion_engine::WaveNode, tracktion_engine::MidiNode, tracktion_engine::InsertSendReturnDependencyNode, tracktion_engine::LevelMeasurerProcessingNode, tracktion_graph::MidiNode, tracktion_engine::FadeInOutNode, tracktion_engine::PlayHeadPositionNode, tracktion_engine::RackReturnNode, tracktion_engine::InsertReturnNode, tracktion_engine::LiveMidiInjectingNode, tracktion_engine::RackInstanceNode, tracktion_engine::TimeStretchingWaveNode, tracktion_engine::LiveMidiOutputNode, tracktion_engine::MelodyneNode, tracktion_engine::MidiOutputDeviceInstanceInjectingNode, tracktion_engine::TimedMutingNode, tracktion_engine::HostedMidiInputDeviceNode, tracktion_engine::MidiInputDeviceNode, tracktion_engine::WaveInputDeviceNode, tracktion_engine::TrackMidiInputDeviceNode, tracktion_engine::SharedLevelMeasuringNode, tracktion_engine::TrackWaveInputDeviceNode, and tracktion_engine::LevelMeasuringNode.
Referenced by tracktion_graph::LatencyNode::getNodeProperties(), initialise(), tracktion_engine::LevelMeasurerProcessingNode::prepareToPlay(), and tracktion_engine::PlayHeadPositionNode::prepareToPlay().
isReadyToProcess()
virtual bool tracktion_graph::Node::isReadyToProcess () pure virtual
Should return true when this node is ready to be processed.
This is usually when its input's output buffers are ready.
Implemented in tracktion_graph::ForwardingNode, tracktion_graph::SinkNode, tracktion_graph::ChannelRemappingNode, tracktion_graph::ReturnNode, tracktion_graph::SendNode, tracktion_graph::GainNode, tracktion_graph::FunctionNode, tracktion_graph::BasicSummingNode, tracktion_graph::SilentNode, tracktion_graph::SummingNode, tracktion_graph::SinNode, tracktion_engine::TrackMutingNode, tracktion_engine::ClickNode, tracktion_graph::ConnectedNode, tracktion_graph::LatencyNode, tracktion_engine::InsertSendNode, tracktion_engine::PluginNode, tracktion_engine::ModifierNode, tracktion_engine::SpeedRampWaveNode, tracktion_engine::CombiningNode, tracktion_engine::WaveNode, tracktion_engine::PlayHeadPositionNode, tracktion_engine::MidiNode, tracktion_engine::LevelMeasurerProcessingNode, tracktion_engine::InsertSendReturnDependencyNode, tracktion_graph::MidiNode, tracktion_engine::FadeInOutNode, tracktion_engine::RackReturnNode, tracktion_engine::InsertReturnNode, tracktion_engine::LiveMidiInjectingNode, tracktion_engine::TimeStretchingWaveNode, tracktion_engine::LiveMidiOutputNode, tracktion_engine::MelodyneNode, tracktion_engine::MidiOutputDeviceInstanceInjectingNode, tracktion_engine::RackInstanceNode, tracktion_engine::TimedMutingNode, tracktion_engine::HostedMidiInputDeviceNode, tracktion_engine::MidiInputDeviceNode, tracktion_engine::WaveInputDeviceNode, tracktion_engine::TrackMidiInputDeviceNode, tracktion_engine::SharedLevelMeasuringNode, tracktion_engine::TrackWaveInputDeviceNode, and tracktion_engine::LevelMeasuringNode.
retain()
void tracktion_graph::Node::retain ()
Retains the buffers so they won't be deallocated after the Node has processed.
You shouldn't normally need to call this unles your Node player has special requirements.
Referenced by prepareForNextBlock(), and setAudioOutput().
release()
void tracktion_graph::Node::release ()
Releases the buffers allowing internal storage to be deallocated.
You shouldn't normally need to call this unles your Node player has special requirements.
Referenced by process().
getAllocatedBytes()
size_t tracktion_graph::Node::getAllocatedBytes () const virtual
Reimplemented in tracktion_engine::CombiningNode.
References tracktion_engine::MidiMessageArray::size().
prepareToPlay()
virtual void tracktion_graph::Node::prepareToPlay (const PlaybackInitialisationInfo &) protected virtual
Called once before playback begins for each node.
Use this to allocate buffers etc. This step can be used to modify the topology of the graph (i.e. add/remove nodes). However, if you do this, you must make sure to call initialise on them so they are fully prepared for processing.
Reimplemented in tracktion_engine::PlayHeadPositionNode, tracktion_engine::LevelMeasurerProcessingNode, tracktion_engine::TrackMutingNode, tracktion_engine::ClickNode, tracktion_engine::InsertSendNode, tracktion_engine::PluginNode, tracktion_engine::ModifierNode, tracktion_engine::SpeedRampWaveNode, tracktion_engine::CombiningNode, tracktion_engine::WaveNode, tracktion_engine::MidiNode, tracktion_engine::InsertSendReturnDependencyNode, tracktion_engine::AuxSendNode, tracktion_engine::FadeInOutNode, tracktion_engine::RackReturnNode, tracktion_engine::InsertReturnNode, tracktion_engine::LiveMidiInjectingNode, tracktion_engine::TimeStretchingWaveNode, tracktion_engine::LiveMidiOutputNode, tracktion_engine::MelodyneNode, tracktion_engine::MidiOutputDeviceInstanceInjectingNode, tracktion_engine::RackInstanceNode, tracktion_engine::TimedMutingNode, tracktion_engine::HostedMidiInputDeviceNode, tracktion_engine::MidiInputDeviceNode, tracktion_engine::WaveInputDeviceNode, tracktion_engine::TrackMidiInputDeviceNode, tracktion_engine::SharedLevelMeasuringNode, tracktion_engine::TrackWaveInputDeviceNode, tracktion_graph::SilentNode, tracktion_graph::SummingNode, tracktion_graph::SinNode, tracktion_graph::LatencyNode, tracktion_graph::MidiNode, and tracktion_graph::ConnectedNode.
Referenced by initialise().
prefetchBlock()
virtual void tracktion_graph::Node::prefetchBlock (juce::Range< int64_t >) protected virtual
Called before once on all Nodes before they are processed.
This can be used to prefetch audio data or update mute statuses etc..
Reimplemented in tracktion_engine::TrackMutingNode, tracktion_engine::PluginNode, tracktion_engine::CombiningNode, and tracktion_engine::SharedLevelMeasuringNode.
Referenced by prepareForNextBlock().
process() [2/2]
virtual void tracktion_graph::Node::process (ProcessContext &) protected pure virtual
Called when the node is to be processed.
This should add in to the buffers available making sure not to change their size at all.
Implemented in tracktion_engine::LevelMeasuringNode, tracktion_graph::ForwardingNode, tracktion_graph::ChannelRemappingNode, tracktion_graph::ReturnNode, tracktion_graph::SendNode, tracktion_graph::GainNode, tracktion_graph::FunctionNode, tracktion_graph::BasicSummingNode, tracktion_graph::SilentNode, tracktion_graph::SummingNode, tracktion_graph::SinNode, tracktion_graph::LatencyNode, tracktion_engine::LevelMeasurerProcessingNode, tracktion_engine::PlayHeadPositionNode, tracktion_graph::MidiNode, tracktion_graph::SinkNode, tracktion_engine::TrackMutingNode, tracktion_graph::ConnectedNode, tracktion_engine::ClickNode, tracktion_engine::InsertSendNode, tracktion_engine::PluginNode, tracktion_engine::ModifierNode, tracktion_engine::SpeedRampWaveNode, tracktion_engine::CombiningNode, tracktion_engine::WaveNode, tracktion_engine::MidiNode, tracktion_engine::InsertSendReturnDependencyNode, tracktion_engine::FadeInOutNode, tracktion_engine::RackReturnNode, tracktion_engine::AuxSendNode, tracktion_engine::InsertReturnNode, tracktion_engine::LiveMidiInjectingNode, tracktion_engine::TimeStretchingWaveNode, tracktion_engine::LiveMidiOutputNode, tracktion_engine::MelodyneNode, tracktion_engine::MidiOutputDeviceInstanceInjectingNode, tracktion_engine::RackInstanceNode, tracktion_engine::TimedMutingNode, tracktion_engine::HostedMidiInputDeviceNode, tracktion_engine::MidiInputDeviceNode, tracktion_engine::WaveInputDeviceNode, tracktion_engine::SharedLevelMeasuringNode, tracktion_engine::TrackMidiInputDeviceNode, and tracktion_engine::TrackWaveInputDeviceNode.
setOptimisations()
void tracktion_graph::Node::setOptimisations (NodeOptimisations newOptimisations) protected
This can be called to provide some hints about allocating or playing back a Node to improve efficiency.
Be careful with these as they change the default and often expected behaviour.
Referenced by tracktion_graph::LatencyNode::LatencyNode(), tracktion_graph::ReturnNode::ReturnNode(), tracktion_graph::SendNode::SendNode(), and tracktion_graph::SilentNode::SilentNode().
setAudioOutput()
void tracktion_graph::Node::setAudioOutput (Node * sourceNode, const choc::buffer::ChannelArrayView< float > & newAudioView) protected
This can be called during your process function to set a view to the output.
This is useful to avoid having to allocate an internal buffer and always fill it if you're just passing on data.
References retain().
Referenced by tracktion_engine::LevelMeasurerProcessingNode::process(), tracktion_graph::SilentNode::process(), tracktion_graph::SendNode::process(), and tracktion_graph::ReturnNode::process().
Member Data Documentation
internal
void* tracktion_graph::Node::internal = nullptr
numOutputNodes
int tracktion_graph::Node::numOutputNodes = -1
Referenced by tracktion_engine::LevelMeasurerProcessingNode::process(), and tracktion_graph::SendNode::process().
The documentation for this class was generated from the following file:
tracktion_graph_Node.h