TracktionEngine: tracktion::engine::ExternalPlugin Class Reference
tracktion::engine::ExternalPlugin Class Reference
tracktion_engine » plugins
#include <tracktion_ExternalPlugin.h>
Public Types
using Ptr = juce::ReferenceCountedObjectPtr< ExternalPlugin >
Public Types inherited from tracktion::engine::Plugin
enum class Type { allPlugins , folderTrackPlugins , effectPlugins }
using Ptr = juce::ReferenceCountedObjectPtr< Plugin >
using Array = juce::ReferenceCountedArray< Plugin >
Public Types inherited from tracktion::engine::Selectable
using WeakRef = juce::WeakReference< Selectable >
Public Member Functions
ExternalPlugin (PluginCreationInfo)
~ExternalPlugin () override
juce::String getIdentifierString () override
A unique string to idenitify plugin independant of install location.
void selectableAboutToBeDeleted () override
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void processingChanged () override
void initialiseFully () override
Gives the plugin a chance to do extra initialisation when it's been added to an edit.
void forceFullReinitialise ()
juce::String getLoadError ()
Returns an error message if the plugin failed to load.
bool isInitialisingAsync () const
Returns true if the plugin has started initialising but not completed yet.
void flushPluginStateToValueTree () override
void flushBusesLayoutToValueTree ()
void restorePluginStateFromValueTree (const juce::ValueTree &) override
void getPluginStateFromTree (juce::MemoryBlock &)
void updateFromMirroredPluginIfNeeded (Plugin &) override
void initialise (const PluginInitialisationInfo &) override
Gives the plugin a chance to set itself up before being played.
void deinitialise () override
Called after play stops to release resources.
void reset () override
Should reset synth voices, tails, clear delay buffers, etc.
void midiPanic () override
Tells the plugin to turn off any playing notes, if applicable.
void setEnabled (bool enabled) override
Enable/disable the plugin.
juce::Array< Exportable::ReferencedItem > getReferencedItems () override
void reassignReferencedItem (const ReferencedItem &, ProjectItemID newID, double newStartTime) override
void applyToBuffer (const PluginRenderContext &) override
Process the next block of data.
bool producesAudioWhenNoAudioInput () override
int getNumOutputChannelsGivenInputs (int numInputs) override
This must return the number of output channels that the plugin will produce, given a number of input channels.
void getChannelNames (juce::StringArray *ins, juce::StringArray *outs) override
bool isVST () const noexcept
bool isVST3 () const noexcept
bool isAU () const noexcept
juce::String getName () const override
The name of the type, e.g.
juce::String getVendor () override
juce::String getTooltip () override
default returns the name, others can return special stuff if needed
juce::String getPluginType () override
bool isSynth () override
bool takesMidiInput () override
bool takesAudioInput () override
bool isMissing () override
for things like VSTs where the DLL is missing.
bool isDisabled () override
Plugins can be disabled to avoid them crashing Edits.
double getLatencySeconds () override
bool noTail () override
double getTailLength () const override
void trackPropertiesChanged () override
Track name or colour has changed.
juce::AudioProcessor * getWrappedAudioProcessor () const override
void deleteFromParent () override
Attempts to delete this plugin, whether it's a master plugin, track plugin, etc.
juce::String getSelectableDescription () override
Subclasses must return a description of what they are.
juce::File getFile () const
juce::String getPluginUID () const
const char * getDebugName () const noexcept
int getNumInputs () const
int getNumOutputs () const
bool setBusesLayout (juce::AudioProcessor::BusesLayout)
Attempts to change the layout of the plugin.
bool setBusLayout (juce::AudioChannelSet, bool isInput, int busIndex)
Attempts to change the layout of the plugin.
int getNumPrograms () const
int getCurrentProgram () const
juce::String getProgramName (int index)
juce::String getNumberedProgramName (int i)
juce::String getCurrentProgramName ()
void setCurrentProgram (int index, bool sendChangeMessage)
void setCurrentProgramName (const juce::String &name)
bool hasNameForMidiProgram (int programNum, int bank, juce::String &name) override
Returns the name for a midi program, if there is one.
bool hasNameForMidiNoteNumber (int note, int midiChannel, juce::String &name) override
If it's a synth that names its notes, this can return the name it uses for this note 0-127.
const VSTXML * getVSTXML () const noexcept
juce::AudioPluginInstance * getAudioPluginInstance () const
ActiveNoteList getActiveNotes () const
std::unique_ptr< EditorComponent > createEditor () override
Public Member Functions inherited from tracktion::engine::Plugin
Plugin (PluginCreationInfo)
~Plugin () override
void selectableAboutToBeDeleted () override
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void playStartedOrStopped ()
called by the system to let the plugin manage its automation stuff
virtual juce::String getShortName (int)
bool isEnabled () const noexcept
void setFrozen (bool shouldBeFrozen)
This is a bit different to being enabled as when frozen a plugin can't be interacted with.
bool isFrozen () const noexcept
void setProcessingEnabled (bool p)
Enable/Disable processing.
bool isProcessingEnabled () const noexcept
virtual void initialiseWithoutStopping (const PluginInitialisationInfo &)
Tells the plugin that the audio graph has changed but the plugin isn't being re-initialised - i.e.
virtual void prepareForNextBlock (TimePosition)
Called between successive rendering blocks.
void applyToBufferWithAutomation (const PluginRenderContext &)
virtual bool shouldMeasureCpuUsage () const noexcept
Plugins can return false if they want to avoid the overhead of measuring the CPU usage.
double getCpuUsage () const noexcept
Returns the proportion of the current buffer size spent processing this plugin.
virtual bool canSidechain ()
AutomatableParameter * addParam (const juce::String &paramID, const juce::String &name, juce::NormalisableRange< float > valueRange)
AutomatableParameter * addParam (const juce::String &paramID, const juce::String &name, juce::NormalisableRange< float > valueRange, std::function< juce::String(float)> valueToStringFunction, std::function< float(const juce::String &)> stringToValueFunction)
juce::StringArray getInputChannelNames ()
juce::StringArray getSidechainSourceNames (bool allowNone)
void setSidechainSourceByName (const juce::String &name)
juce::String getSidechainSourceName ()
void guessSidechainRouting ()
int getNumWires () const
Wire * getWire (int index) const
void makeConnection (int srcChannel, int dstChannel, juce::UndoManager *)
void breakConnection (int srcChannel, int dstChannel)
virtual bool hasNameForMidiBank (int bank, juce::String &name)
virtual bool canBeAddedToClip ()
virtual bool canBeAddedToRack ()
virtual bool canBeAddedToFolderTrack ()
virtual bool canBeAddedToMaster ()
virtual bool canBeDisabled ()
virtual bool canBeMoved ()
virtual bool needsConstantBufferSize ()
bool isInRack () const
juce::ReferenceCountedObjectPtr< RackType > getOwnerRackType () const
bool isClipEffectPlugin () const
AutomatableParameter::Ptr getQuickControlParameter () const
void setQuickControlParameter (AutomatableParameter *)
void removeFromParent ()
Detaches the plugin from any parent it might be in.
Track * getOwnerTrack () const
Returns the track if it's a track or clip plugin.
Clip * getOwnerClip () const
Returns the clip if that's what it's in.
PluginList * getOwnerList () const
Ptr findPluginThatFeedsIntoThis () const
Ptr findPluginThatThisFeedsInto () const
void changed () override
method from Selectable, that's been overridden here to also tell the edit that it's changed.
juce::Array< ReferencedItem > getReferencedItems () override
void reassignReferencedItem (const ReferencedItem &, ProjectItemID newID, double newStartTime) override
virtual void sourceMediaChanged ()
Called when ProjectItem sources are re-assigned so you can reload from the new source.
bool setPluginToMirror (const Plugin::Ptr &)
Plugin::Ptr getMirroredPlugin () const
bool baseClassNeedsInitialising () const noexcept
void baseClassInitialise (const PluginInitialisationInfo &)
void baseClassDeinitialise ()
void setSidechainSourceID (EditItemID newID)
EditItemID getSidechainSourceID () const
void showWindowExplicitly ()
void hideWindowForShutdown ()
juce::UndoManager * getUndoManager () const noexcept
bool isInitialising () const
Public Member Functions inherited from tracktion::engine::Selectable
Selectable ()
virtual ~Selectable ()
virtual void selectionStatusChanged (bool isNowSelected)
Can be overridden to tell this object that it has just been selected or deselected.
void addListener (SelectableListener *)
void removeListener (SelectableListener *)
void addSelectableListener (SelectableListener *)
void removeSelectableListener (SelectableListener *)
void cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
void deselect ()
void propertiesChanged ()
void notifyListenersOfDeletion ()
WeakRef getWeakRef ()
Public Member Functions inherited from tracktion::engine::Exportable
virtual ~Exportable ()=default
Public Member Functions inherited from tracktion::engine::AutomatableEditItem
AutomatableEditItem (Edit &, const juce::ValueTree &)
~AutomatableEditItem () override
juce::Array< AutomatableParameter * > getAutomatableParameters () const
int getNumAutomatableParameters () const
AutomatableParameter::Ptr getAutomatableParameter (int index) const
AutomatableParameter::Ptr getAutomatableParameterByID (const juce::String &paramID) const
void visitAllAutomatableParams (const std::function< void(AutomatableParameter &)> &visit) const
void deleteParameter (AutomatableParameter *)
void deleteAutomatableParameters ()
int indexOfAutomatableParameter (const AutomatableParameter::Ptr &) const
AutomatableParameterTree & getParameterTree () const
juce::ReferenceCountedArray< AutomatableParameter > getFlattenedParameterTree () const
void addParameterListChangeListener (ParameterListChangeListener *)
void removeParameterListChangeListener (ParameterListChangeListener *)
bool isAutomationNeeded () const noexcept
void setAutomatableParamPosition (TimePosition)
bool isBeingActivelyPlayed () const
virtual void updateAutomatableParamPosition (TimePosition)
Updates all the auto params to their positions at this time.
void updateParameterStreams (TimePosition)
Updates all the parameter streams to their positions at this time.
void updateActiveParameters ()
Iterates all the parameters to find out which ones need to be automated.
void resetRecordingStatus ()
Marks the end of an automation recording stream.
Public Member Functions inherited from tracktion::engine::EditItem
EditItem (EditItemID, Edit &)
EditItem (Edit &, const juce::ValueTree &)
virtual ~EditItem ()=default
Public Member Functions inherited from tracktion::engine::MacroParameterElement
MacroParameterElement (Edit &, const juce::ValueTree &)
Constructor.
virtual ~MacroParameterElement ()=default
Destructor.
MacroParameterList * getMacroParameterList ()
If no parameters have been created, this may return nullptr.
MacroParameterList & getMacroParameterListForWriting ()
This ensures that the list has been created.
juce::ReferenceCountedArray< MacroParameter > getMacroParameters () const
Static Public Member Functions
static juce::ValueTree create (Engine &, const juce::PluginDescription &)
Static Public Member Functions inherited from tracktion::engine::Plugin
static bool areSelectedPluginsRackable (SelectionManager &)
static RackInstance * wrapSelectedPluginsInRack (SelectionManager &)
static void sortPlugins (Plugin::Array &)
static void sortPlugins (std::vector< Plugin * > &)
Static Public Member Functions inherited from tracktion::engine::Selectable
static void initialise ()
static bool isSelectableValid (const Selectable *) noexcept
checks whether this object has been deleted.
Static Public Member Functions inherited from tracktion::engine::Exportable
static juce::Array< Exportable * > addAllExportables (Edit &)
Returns all the Exportables contained in an Edit.
Public Attributes
juce::PluginDescription desc
juce::CachedValue< float > dryValue
juce::CachedValue< float > wetValue
AutomatableParameter::Ptr dryGain
AutomatableParameter::Ptr wetGain
Public Attributes inherited from tracktion::engine::Plugin
std::unique_ptr< WindowState > windowState
Engine & engine
juce::ValueTree state
Public Attributes inherited from tracktion::engine::Selectable
WeakRef::Master masterReference
Public Attributes inherited from tracktion::engine::AutomatableEditItem
juce::ValueTree elementState
juce::CachedValue< bool > remapOnTempoChange
Public Attributes inherited from tracktion::engine::EditItem
Edit & edit
const EditItemID itemID
Every EditItem has an ID which is unique within the edit.
Public Attributes inherited from tracktion::engine::MacroParameterElement
Edit & ownerEdit
juce::ValueTree parentStateForList
Static Public Attributes
static const char * xmlTypeName
Additional Inherited Members
Protected Member Functions inherited from tracktion::engine::Plugin
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeChanged () override
void valueTreeChildAdded (juce::ValueTree &, juce::ValueTree &) override
void valueTreeChildRemoved (juce::ValueTree &, juce::ValueTree &, int) override
void valueTreeParentChanged (juce::ValueTree &) override
Protected Member Functions inherited from tracktion::engine::AutomatableEditItem
void updateLastPlaybackTime ()
void clearParameterList ()
void addAutomatableParameter (const AutomatableParameter::Ptr &)
void rebuildParameterTree ()
void saveChangedParametersToState ()
Saves the explicit value of any parameters that have deviated to the state.
void restoreChangedParametersFromState ()
Restores the value of any explicitly set parameters.
Protected Member Functions inherited from tracktion::engine::ValueTreeAllEventListener
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeChildAdded (juce::ValueTree &, juce::ValueTree &) override
void valueTreeChildRemoved (juce::ValueTree &, juce::ValueTree &, int) override
void valueTreeChildOrderChanged (juce::ValueTree &, int, int) override
void valueTreeParentChanged (juce::ValueTree &) override
void valueTreeRedirected (juce::ValueTree &) override
Static Protected Member Functions inherited from tracktion::engine::Plugin
static void getLeftRightChannelNames (juce::StringArray *ins, juce::StringArray *outs)
static void getLeftRightChannelNames (juce::StringArray *chans)
Protected Attributes inherited from tracktion::engine::Plugin
juce::CachedValue< AtomicWrapper< bool > > enabled
juce::CachedValue< bool > frozen
juce::CachedValue< bool > processing
juce::CachedValue< juce::String > quickParamName
juce::CachedValue< EditItemID > masterPluginID
juce::CachedValue< EditItemID > sidechainSourceID
double sampleRate = 44100.0
int blockSizeSamples = 512
Member Typedef Documentation
Ptr
using tracktion::engine::ExternalPlugin::Ptr = juce::ReferenceCountedObjectPtr<ExternalPlugin>
Constructor & Destructor Documentation
ExternalPlugin()
tracktion::engine::ExternalPlugin::ExternalPlugin (PluginCreationInfo)
~ExternalPlugin()
tracktion::engine::ExternalPlugin::~ExternalPlugin () override
Member Function Documentation
getIdentifierString()
juce::String tracktion::engine::ExternalPlugin::getIdentifierString () override virtual
A unique string to idenitify plugin independant of install location.
Reimplemented from tracktion::engine::Plugin.
References tracktion::engine::createIdentifierString(), and desc.
selectableAboutToBeDeleted()
void tracktion::engine::ExternalPlugin::selectableAboutToBeDeleted () override virtual
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
Reimplemented from tracktion::engine::Selectable.
create()
static juce::ValueTree tracktion::engine::ExternalPlugin::create (Engine & , const juce::PluginDescription &) static
processingChanged()
void tracktion::engine::ExternalPlugin::processingChanged () override virtual
Reimplemented from tracktion::engine::Plugin.
initialiseFully()
void tracktion::engine::ExternalPlugin::initialiseFully () override virtual
Gives the plugin a chance to do extra initialisation when it's been added to an edit.
Reimplemented from tracktion::engine::Plugin.
forceFullReinitialise()
void tracktion::engine::ExternalPlugin::forceFullReinitialise ()
getLoadError()
juce::String tracktion::engine::ExternalPlugin::getLoadError ()
Returns an error message if the plugin failed to load.
isInitialisingAsync()
bool tracktion::engine::ExternalPlugin::isInitialisingAsync () const
Returns true if the plugin has started initialising but not completed yet.
This happens in the case of some external formats like AUv3. You can use this to show an indicator in your UI.
flushPluginStateToValueTree()
void tracktion::engine::ExternalPlugin::flushPluginStateToValueTree () override virtual
Reimplemented from tracktion::engine::Plugin.
flushBusesLayoutToValueTree()
void tracktion::engine::ExternalPlugin::flushBusesLayoutToValueTree ()
restorePluginStateFromValueTree()
void tracktion::engine::ExternalPlugin::restorePluginStateFromValueTree (const juce::ValueTree &) override virtual
Reimplemented from tracktion::engine::AutomatableEditItem.
getPluginStateFromTree()
void tracktion::engine::ExternalPlugin::getPluginStateFromTree (juce::MemoryBlock &)
updateFromMirroredPluginIfNeeded()
void tracktion::engine::ExternalPlugin::updateFromMirroredPluginIfNeeded (Plugin &) override virtual
Reimplemented from tracktion::engine::Plugin.
initialise()
void tracktion::engine::ExternalPlugin::initialise (const PluginInitialisationInfo &) override virtual
Gives the plugin a chance to set itself up before being played.
This won't be called concurrently with the process thread.
The sample rate and the average block size - although the blocks won't always be the same, and may be bigger.
Don't call this directly or the initialise count will become out of sync.
See also
baseClassInitialise [[ message_thread ]]
Implements tracktion::engine::Plugin.
deinitialise()
void tracktion::engine::ExternalPlugin::deinitialise () override virtual
Called after play stops to release resources.
Don't call this directly or the initialise count will become out of sync.
See also
baseClassDeinitialise
Implements tracktion::engine::Plugin.
reset()
void tracktion::engine::ExternalPlugin::reset () override virtual
Should reset synth voices, tails, clear delay buffers, etc.
Reimplemented from tracktion::engine::Plugin.
midiPanic()
void tracktion::engine::ExternalPlugin::midiPanic () override virtual
Tells the plugin to turn off any playing notes, if applicable.
Reimplemented from tracktion::engine::Plugin.
setEnabled()
void tracktion::engine::ExternalPlugin::setEnabled (bool) override virtual
Enable/disable the plugin.
Reimplemented from tracktion::engine::Plugin.
getReferencedItems()
juce::Array< Exportable::ReferencedItem > tracktion::engine::ExternalPlugin::getReferencedItems () override virtual
Implements tracktion::engine::Exportable.
reassignReferencedItem()
void tracktion::engine::ExternalPlugin::reassignReferencedItem (const ReferencedItem & , ProjectItemID newID, double newStartTime) override virtual
Implements tracktion::engine::Exportable.
applyToBuffer()
void tracktion::engine::ExternalPlugin::applyToBuffer (const PluginRenderContext &) override virtual
Process the next block of data.
The incoming buffer will have an unknown number of channels, and the plugin has to deal with them however it wants to.
The buffer should be resized to the number of output channels that the plugin wants to return (which should be the same or less than the number of output channel names it returns from getChannelNames() - never more than this).
Implements tracktion::engine::Plugin.
producesAudioWhenNoAudioInput()
bool tracktion::engine::ExternalPlugin::producesAudioWhenNoAudioInput () override virtual
Reimplemented from tracktion::engine::Plugin.
References tracktion::engine::AutomatableEditItem::isAutomationNeeded(), isSynth(), and noTail().
getNumOutputChannelsGivenInputs()
int tracktion::engine::ExternalPlugin::getNumOutputChannelsGivenInputs (int numInputChannels) override virtual
This must return the number of output channels that the plugin will produce, given a number of input channels.
E.g. some might be able to do mono, so will return 1 if the input is 1, 2 if it is 2, etc.
The default impl just returns the number of items that getChannelNames() returns.
Reimplemented from tracktion::engine::Plugin.
getChannelNames()
void tracktion::engine::ExternalPlugin::getChannelNames (juce::StringArray * ins, juce::StringArray * outs) override virtual
Reimplemented from tracktion::engine::Plugin.
isVST()
bool tracktion::engine::ExternalPlugin::isVST () const noexcept
References desc.
isVST3()
bool tracktion::engine::ExternalPlugin::isVST3 () const noexcept
References desc.
isAU()
bool tracktion::engine::ExternalPlugin::isAU () const noexcept
References desc.
getName()
juce::String tracktion::engine::ExternalPlugin::getName () const override virtual
The name of the type, e.g.
"Compressor"
Implements tracktion::engine::Plugin.
References desc.
Referenced by getTooltip().
getVendor()
juce::String tracktion::engine::ExternalPlugin::getVendor () override virtual
Reimplemented from tracktion::engine::Plugin.
References desc.
getTooltip()
juce::String tracktion::engine::ExternalPlugin::getTooltip () override virtual
default returns the name, others can return special stuff if needed
Reimplemented from tracktion::engine::Plugin.
References getName().
getPluginType()
juce::String tracktion::engine::ExternalPlugin::getPluginType () override virtual
Implements tracktion::engine::Plugin.
References xmlTypeName.
isSynth()
bool tracktion::engine::ExternalPlugin::isSynth () override virtual
Reimplemented from tracktion::engine::Plugin.
References desc.
Referenced by producesAudioWhenNoAudioInput(), and takesAudioInput().
takesMidiInput()
bool tracktion::engine::ExternalPlugin::takesMidiInput () override virtual
Reimplemented from tracktion::engine::Plugin.
takesAudioInput()
bool tracktion::engine::ExternalPlugin::takesAudioInput () override virtual
Reimplemented from tracktion::engine::Plugin.
References dryGain, and isSynth().
isMissing()
bool tracktion::engine::ExternalPlugin::isMissing () override virtual
for things like VSTs where the DLL is missing.
Reimplemented from tracktion::engine::Plugin.
isDisabled()
bool tracktion::engine::ExternalPlugin::isDisabled () override virtual
Plugins can be disabled to avoid them crashing Edits.
Reimplemented from tracktion::engine::Plugin.
getLatencySeconds()
double tracktion::engine::ExternalPlugin::getLatencySeconds () override virtual
Reimplemented from tracktion::engine::Plugin.
noTail()
bool tracktion::engine::ExternalPlugin::noTail () override virtual
Reimplemented from tracktion::engine::Plugin.
Referenced by producesAudioWhenNoAudioInput().
getTailLength()
double tracktion::engine::ExternalPlugin::getTailLength () const override virtual
Reimplemented from tracktion::engine::Plugin.
trackPropertiesChanged()
void tracktion::engine::ExternalPlugin::trackPropertiesChanged () override virtual
Track name or colour has changed.
Reimplemented from tracktion::engine::Plugin.
getWrappedAudioProcessor()
juce::AudioProcessor * tracktion::engine::ExternalPlugin::getWrappedAudioProcessor () const override virtual
Reimplemented from tracktion::engine::Plugin.
References getAudioPluginInstance().
deleteFromParent()
void tracktion::engine::ExternalPlugin::deleteFromParent () override virtual
Attempts to delete this plugin, whether it's a master plugin, track plugin, etc.
This will call removeFromParent but also hide any automation parameters etc. being shown on tracks and hide plugin windows etc. Use this method if the plugin is being fully deleted from the Edit.
Reimplemented from tracktion::engine::Plugin.
getSelectableDescription()
juce::String tracktion::engine::ExternalPlugin::getSelectableDescription () override virtual
Subclasses must return a description of what they are.
Implements tracktion::engine::Selectable.
getFile()
juce::File tracktion::engine::ExternalPlugin::getFile () const
getPluginUID()
juce::String tracktion::engine::ExternalPlugin::getPluginUID () const
References desc.
getDebugName()
const char * tracktion::engine::ExternalPlugin::getDebugName () const noexcept
getNumInputs()
int tracktion::engine::ExternalPlugin::getNumInputs () const
getNumOutputs()
int tracktion::engine::ExternalPlugin::getNumOutputs () const
setBusesLayout()
bool tracktion::engine::ExternalPlugin::setBusesLayout (juce::AudioProcessor::BusesLayout)
Attempts to change the layout of the plugin.
setBusLayout()
bool tracktion::engine::ExternalPlugin::setBusLayout (juce::AudioChannelSet , bool isInput, int busIndex)
Attempts to change the layout of the plugin.
getNumPrograms()
int tracktion::engine::ExternalPlugin::getNumPrograms () const
getCurrentProgram()
int tracktion::engine::ExternalPlugin::getCurrentProgram () const
getProgramName()
juce::String tracktion::engine::ExternalPlugin::getProgramName (int index)
getNumberedProgramName()
juce::String tracktion::engine::ExternalPlugin::getNumberedProgramName (int i)
getCurrentProgramName()
juce::String tracktion::engine::ExternalPlugin::getCurrentProgramName ()
setCurrentProgram()
void tracktion::engine::ExternalPlugin::setCurrentProgram (int index, bool sendChangeMessage)
setCurrentProgramName()
void tracktion::engine::ExternalPlugin::setCurrentProgramName (const juce::String & name)
hasNameForMidiProgram()
bool tracktion::engine::ExternalPlugin::hasNameForMidiProgram (int programNum, int bank, juce::String & name) override virtual
Returns the name for a midi program, if there is one.
programNum = 0 to 127.
Reimplemented from tracktion::engine::Plugin.
hasNameForMidiNoteNumber()
bool tracktion::engine::ExternalPlugin::hasNameForMidiNoteNumber (int note, int midiChannel, juce::String & name) override virtual
If it's a synth that names its notes, this can return the name it uses for this note 0-127.
Midi channel is 1-16
Reimplemented from tracktion::engine::Plugin.
getVSTXML()
const VSTXML * tracktion::engine::ExternalPlugin::getVSTXML () const noexcept
Referenced by tracktion::engine::ExternalAutomatableParameter::ExternalAutomatableParameter().
getAudioPluginInstance()
juce::AudioPluginInstance * tracktion::engine::ExternalPlugin::getAudioPluginInstance () const
Referenced by getWrappedAudioProcessor().
getActiveNotes()
ActiveNoteList tracktion::engine::ExternalPlugin::getActiveNotes () const
createEditor()
std::unique_ptr< EditorComponent > tracktion::engine::ExternalPlugin::createEditor () override virtual
Reimplemented from tracktion::engine::Plugin.
Member Data Documentation
xmlTypeName
const char* tracktion::engine::ExternalPlugin::xmlTypeName static
Referenced by getPluginType().
desc
juce::PluginDescription tracktion::engine::ExternalPlugin::desc
Referenced by getIdentifierString(), getName(), getPluginUID(), getVendor(), isAU(), isSynth(), isVST(), and isVST3().
dryValue
juce::CachedValue<float> tracktion::engine::ExternalPlugin::dryValue
wetValue
juce::CachedValue<float> tracktion::engine::ExternalPlugin::wetValue
dryGain
AutomatableParameter::Ptr tracktion::engine::ExternalPlugin::dryGain
Referenced by takesAudioInput().
wetGain
AutomatableParameter::Ptr tracktion::engine::ExternalPlugin::wetGain
The documentation for this class was generated from the following file:
tracktion_ExternalPlugin.h