TracktionEngine: tracktion::engine::WarpTimeRenderJob Class Reference
tracktion::engine::WarpTimeRenderJob Class Reference
tracktion_engine » model
#include <tracktion_WarpTimeRenderJob.h>
Static Public Member Functions
static Ptr getOrCreateRenderJob (AudioClipBase &clip, const juce::File &source, const juce::File &destination)
Protected Member Functions
bool setUpRender () override
Subclasses should override this to set-up their render process.
bool renderNextBlock () override
During a render process this will be repeatedly called.
bool completeRender () override
This is called once after all the render blocks have completed.
Protected Member Functions inherited from tracktion::engine::RenderManager::Job
Job (Engine &, const AudioFile &proxy)
Additional Inherited Members
Public Types inherited from tracktion::engine::RenderManager::Job
using Ptr = juce::ReferenceCountedObjectPtr< Job >
Public Member Functions inherited from tracktion::engine::RenderManager::Job
~Job () override
JobStatus runJob () override
Performs the render.
float getCurrentTaskProgress () override
Returns the progress of the job.
void cancelJob ()
Cancels the current job safely making sure any listeners are called appropriately.
void cleanUpDanglingJob ()
Called during app shutdown by the manager on any jobs that haven't had a chance to recieve their async completion callbacks.
void incReferenceCount () noexcept
bool decReferenceCountWithoutDeleting () noexcept
int getReferenceCount () const noexcept
void addListener (Listener *l)
void removeListener (Listener *l)
Public Member Functions inherited from tracktion::engine::ThreadPoolJobWithProgress
ThreadPoolJobWithProgress (const juce::String &name)
~ThreadPoolJobWithProgress ()
virtual bool canCancel () const
void setManager (BackgroundJobManager &)
void setName (const juce::String &newName)
Sets the job's name but also updates the manager so the list will reflect it.
void prepareForJobDeletion ()
Call this in your sub-class destructor to to remvoe it from the manager queue before this class's destructor is called which can result in a pure virtual call.
Public Attributes inherited from tracktion::engine::RenderManager::Job
Engine & engine
AudioFile proxy
std::atomic< float > progress { 0 }
Member Function Documentation
getOrCreateRenderJob()
static Ptr tracktion::engine::WarpTimeRenderJob::getOrCreateRenderJob (AudioClipBase & clip, const juce::File & source, const juce::File & destination) static
References tracktion::engine::EditItem::edit, tracktion::engine::Edit::engine, tracktion::engine::RenderManager::getRenderJobWithoutCreating(), and tracktion::engine::Engine::getRenderManager().
setUpRender()
bool tracktion::engine::WarpTimeRenderJob::setUpRender () override protected virtual
Subclasses should override this to set-up their render process.
Return true if the set-up completed successfully and the rest of the render callbacks should be called, false if there was a problem and the render should be stopped.
Implements tracktion::engine::RenderManager::Job.
renderNextBlock()
bool tracktion::engine::WarpTimeRenderJob::renderNextBlock () override protected virtual
During a render process this will be repeatedly called.
Return true once all the blocks have completed, false if this needs to be called again.
Implements tracktion::engine::RenderManager::Job.
References tracktion::engine::AudioFileInfo::bitsPerSample, CRASH_TRACER, tracktion::engine::AudioFile::getFile(), tracktion::engine::AudioFile::getInfo(), tracktion::engine::AudioFileWriter::isOpen(), tracktion::engine::AudioFileInfo::metadata, tracktion::engine::AudioFileInfo::numChannels, tracktion::engine::RenderManager::Job::progress, tracktion::engine::RenderManager::Job::proxy, and tracktion::engine::AudioFileInfo::sampleRate.
completeRender()
bool tracktion::engine::WarpTimeRenderJob::completeRender () override protected virtual
This is called once after all the render blocks have completed.
Subclasses should override this to finish off their render by closing files and etc. returning true if everything completed successfully, false otherwise.
Implements tracktion::engine::RenderManager::Job.
The documentation for this class was generated from the following file:
tracktion_WarpTimeRenderJob.h