TracktionEngine: NodeReader Class Reference
NodeReader Class Reference
Public Member Functions
NodeReader (const AudioFile &af)
ARABool readAudioSamples (ARASamplePosition samplePosition, ARASampleCount samplesPerChannel, void *const *buffers)
double getSampleRate () const
int getNumChannels () const
Constructor & Destructor Documentation
NodeReader()
NodeReader::NodeReader (const AudioFile & af)
Member Function Documentation
readAudioSamples()
ARABool NodeReader::readAudioSamples (ARASamplePosition samplePosition, ARASampleCount samplesPerChannel, void *const * buffers)
References tracktion_engine::AppFunctions::copy().
getSampleRate()
double NodeReader::getSampleRate () const
Referenced by AudioSourceWrapper::getAudioSourceProperties().
getNumChannels()
int NodeReader::getNumChannels () const
Referenced by AudioSourceWrapper::getAudioSourceProperties().
The documentation for this class was generated from the following file:
tracktion_ARAWrapperInterfaces.h