TracktionEngine: tracktion_graph::PlayHeadState Class Reference
tracktion_graph::PlayHeadState Class Reference
Determines how this block releates to other previous render blocks and if the play head has jumped in time.
Public Member Functions
PlayHeadState (PlayHead &ph)
void update (juce::Range< int64_t > referenceSampleRange)
Call once per block to update the jumped state.
bool isContiguousWithPreviousBlock () noexcept
Returns true if the play head did not jump and this block is contiguous with the previous block.
bool didPlayheadJump () noexcept
Returns true if the play head jumped.
bool isFirstBlockOfLoop () noexcept
Returns true if this is the first block of a loop.
bool isLastBlockOfLoop () noexcept
Returns true if this is the last block of a loop.
Public Attributes
PlayHead & playHead
Detailed Description
Determines how this block releates to other previous render blocks and if the play head has jumped in time.
Constructor & Destructor Documentation
PlayHeadState()
tracktion_graph::PlayHeadState::PlayHeadState (PlayHead & ph)
Member Function Documentation
update()
void tracktion_graph::PlayHeadState::update (juce::Range< int64_t > referenceSampleRange)
Call once per block to update the jumped state.
Usually called at the same time as the PlayHead::incrementReferenceSampleCount method.
References tracktion_graph::PlayHead::getLastUserInteractionTime(), tracktion_graph::PlayHead::getLoopRange(), tracktion_graph::PlayHead::isLooping(), tracktion_graph::PlayHead::isPlaying(), tracktion_graph::PlayHead::isRollingIntoLoop(), playHead, and tracktion_graph::PlayHead::referenceSamplePositionToTimelinePosition().
Referenced by tracktion_graph::NodePlayer::processWithPlayHeadState().
isContiguousWithPreviousBlock()
bool tracktion_graph::PlayHeadState::isContiguousWithPreviousBlock () noexcept
Returns true if the play head did not jump and this block is contiguous with the previous block.
References didPlayheadJump(), and isFirstBlockOfLoop().
didPlayheadJump()
bool tracktion_graph::PlayHeadState::didPlayheadJump () noexcept
Returns true if the play head jumped.
Referenced by isContiguousWithPreviousBlock().
isFirstBlockOfLoop()
bool tracktion_graph::PlayHeadState::isFirstBlockOfLoop () noexcept
Returns true if this is the first block of a loop.
Referenced by isContiguousWithPreviousBlock().
isLastBlockOfLoop()
bool tracktion_graph::PlayHeadState::isLastBlockOfLoop () noexcept
Returns true if this is the last block of a loop.
Member Data Documentation
playHead
PlayHead& tracktion_graph::PlayHeadState::playHead
Referenced by tracktion_engine::TracktionEngineNode::getPlayHead(), tracktion_engine::benchmark_utilities::prepareRenderAndDestroy(), tracktion_graph::NodePlayer::prepareToPlay(), tracktion_engine::MultiThreadedNodePlayer::process(), tracktion_engine::TracktionNodePlayer::process(), tracktion_graph::NodePlayer::processWithPlayHeadState(), and update().
The documentation for this class was generated from the following file:
tracktion_graph_PlayHeadState.h