TracktionEngine: tracktion::engine::AudioTrack Class Reference
tracktion::engine::AudioTrack Class Reference
tracktion_engine » model
#include <tracktion_AudioTrack.h>
Classes
struct FreezePointRemovalInhibitor
Prevents the freeze point from being removed during an unfreeze operation.
struct Listener
Listener interface to be notified of recorded MIDI being sent to the plugins.
Public Types
using Ptr = juce::ReferenceCountedObjectPtr< AudioTrack >
Public Types inherited from tracktion::engine::ClipTrack
using Ptr = juce::ReferenceCountedObjectPtr< ClipTrack >
Public Types inherited from tracktion::engine::Track
enum FreezeType { groupFreeze = 0 , individualFreeze , anyFreeze }
Determines the type of freeze.
enum MuteAndSoloLightState {
soloLit = 1 , soloFlashing = 2 , soloIsolate = 4 , muteLit = 8 ,
muteFlashing = 16
}
Determines the status of the mute and solo indicators.
using Ptr = juce::ReferenceCountedObjectPtr< Track >
using Array = juce::ReferenceCountedArray< Track >
Public Types inherited from tracktion::engine::Selectable
using WeakRef = juce::WeakReference< Selectable >
Public Member Functions
AudioTrack (Edit &, const juce::ValueTree &)
~AudioTrack () override
void initialise () override
Initialises the Track.
bool isAudioTrack () const override
Returns true if this is an AudioTrack.
juce::String getSelectableDescription () override
Subclasses must return a description of what they are.
int getAudioTrackNumber () const noexcept
void sanityCheckName () override
checks whether the name is 'track n' and if so, makes sure the number is right
juce::String getName () const override
juce::String getNameAsTrackNumber () const
Returns a name in the form "Track [number]".
juce::String getNameAsTrackNumberWithDescription () const
Returns a name in the form "Track [number] ([track name])" (This is smart enough to not add the parenthesised name if it's just a "Track X" type name)
bool canContainPlugin (Plugin *) const override
Returns true if this track can contain a specific Plugin.
bool processAudioNodesWhileMuted () const override
Subclasses can override this to ensure track contents are still played even when the track is muted.
juce::String getTrackPlayabilityWarning () const
returns a warning message about this track not being playable, or "" if it's ok
juce::String getLauncherPlayabilityWarning () const
VolumeAndPanPlugin * getVolumePlugin ()
LevelMeterPlugin * getLevelMeterPlugin ()
EqualiserPlugin * getEqualiserPlugin ()
AuxSendPlugin * getAuxSendPlugin (int bus=-1, AuxPosition ap=AuxPosition::byBus) const
juce::String getNameForMidiNoteNumber (int note, int midiChannel, bool preferSharp=true) const
looks for a name for a midi note by trying all the plugins, and returning a default on failure.
juce::String getNameForProgramNumber (int programNumber, int bank) const
prog number is 0 based.
juce::String getNameForBank (int bank) const
int getIdForBank (int bank) const
bool areMidiPatchesZeroBased () const
WaveInputDevice & getWaveInputDevice () const noexcept
MidiInputDevice & getMidiInputDevice () const noexcept
TrackOutput & getOutput () const noexcept
int getMaxNumOfInputs () const noexcept
void setMaxNumOfInputs (int newMaxNumber)
bool canPlayAudio () const
checks whether audio clips can be played - i.e.
bool canPlayMidi () const
ClipSlotList & getClipSlotList ()
Returns the ClipSlotList for this track.
bool isFrozen (FreezeType) const override
Returns true if this track is frozen using the given type.
void setFrozen (bool, FreezeType) override
Attempts to freeze or unfreeze the track using a given FreezeType.
void insertFreezePointAfterPlugin (const Plugin::Ptr &)
void removeFreezePoint ()
void freezeTrackAsync () const
bool hasAnyLiveInputs ()
bool hasAnyTracksFeedingIn ()
juce::Array< Track * > getInputTracks () const override
Should return any tracks which feed into this track.
juce::Array< Track * > findSidechainSourceTracks () const
void injectLiveMidiMessage (const MidiMessageWithSource &)
void injectLiveMidiMessage (const juce::MidiMessage &, MPESourceID)
bool isMuted (bool includeMutingByDestination) const override
Returns true if this track is muted.
bool isSolo (bool includeIndirectSolo) const override
Returns true if this track is soloed.
bool isSoloIsolate (bool includeIndirectSolo) const override
Returns true if this track is solo isolated.
void setMute (bool) override
Subclasses should implement this to mute themselves.
void setSolo (bool) override
Subclasses should implement this to solo themselves.
void setSoloIsolate (bool) override
Subclasses should implement this to solo isolate themselves.
double getMidiVisibleProportion () const
vertical scales for displaying the midi note editor
double getMidiVerticalOffset () const
void setMidiVerticalPos (double visibleProp, double offset)
void scaleVerticallyToFitMidi ()
void setVerticalScaleToDefault ()
void setTrackToGhost (AudioTrack *, bool shouldGhost)
void clearGhostTracks ()
juce::Array< AudioTrack * > getGhostTracks () const
int getCompGroup () const noexcept
void setCompGroup (int groupIndex)
bool hasMidiNoteNames ()
void clearMidiNoteNames ()
void loadMidiNoteNames (const juce::String namesFile)
bool mergeInMidiSequence (juce::MidiMessageSequence, TimePosition startTime, MidiClip *, MidiList::NoteAutomationType)
try to add this MIDI sequence to any MIDI clips that are already in the track.
void playGuideNote (int note, MidiChannel midiChannel, int velocity, bool stopOtherFirst=true, bool forceNote=false, bool autorelease=false)
void playGuideNotes (const juce::Array< int > &notes, MidiChannel midiChannel, const juce::Array< int > &velocities, bool stopOthersFirst=true)
void turnOffGuideNotes ()
void turnOffGuideNotes (MidiChannel)
void addListener (Listener *)
Adds a Listener.
void removeListener (Listener *)
Removes a Listener.
juce::ListenerList< Listener > & getListeners ()
Returns the listener list so Nodes can manually call them.
Public Member Functions inherited from tracktion::engine::ClipTrack
ClipTrack (Edit &, const juce::ValueTree &, bool hasModifierList)
~ClipTrack () override
void initialise () override
void flushStateToValueTree () override
Clip * findClipForID (EditItemID) const override
Returns a clip one with a matching ID can be found on this Track.
CollectionClip * getCollectionClip (int index) const noexcept
CollectionClip * getCollectionClip (Clip *) const
int getNumCollectionClips () const noexcept
int indexOfCollectionClip (CollectionClip *) const
int getIndexOfNextCollectionClipAt (TimePosition)
CollectionClip * getNextCollectionClipAt (TimePosition)
bool contains (CollectionClip *) const
void addCollectionClip (CollectionClip *)
void removeCollectionClip (CollectionClip *)
int getNumTrackItems () const override
Should return the number of TrackItem[s] on this Track.
TrackItem * getTrackItem (int idx) const override
Should return the TrackItem at the given index.
int indexOfTrackItem (TrackItem *) const override
Should return the index of the given TrackItem.
int getIndexOfNextTrackItemAt (TimePosition) override
Should return the index of the TrackItem after this time.
TrackItem * getNextTrackItemAt (TimePosition) override
Should return the TrackItem after this time.
void insertSpaceIntoTrack (TimePosition, TimeDuration) override
inserts space and moves everything up
TimeDuration getLength () const
TimeDuration getLengthIncludingInputTracks () const
TimeRange getTotalRange () const
bool addClip (const Clip::Ptr &)
Clip * insertClipWithState (juce::ValueTree)
Clip * insertClipWithState (const juce::ValueTree &stateToUse, const juce::String &name, TrackItem::Type type, ClipPosition position, bool deleteExistingClips, bool allowSpottingAdjustment)
Clip * insertNewClip (TrackItem::Type, TimeRange position, SelectionManager *selectionManagerToSelectWith)
Clip * insertNewClip (TrackItem::Type, const juce::String &name, TimeRange position, SelectionManager *selectionManagerToSelectWith)
Clip * insertNewClip (TrackItem::Type, const juce::String &name, ClipPosition position, SelectionManager *selectionManagerToSelectWith)
juce::ReferenceCountedObjectPtr< WaveAudioClip > insertWaveClip (const juce::String &name, const juce::File &sourceFile, ClipPosition position, bool deleteExistingClips)
juce::ReferenceCountedObjectPtr< WaveAudioClip > insertWaveClip (const juce::String &name, ProjectItemID sourceID, ClipPosition position, bool deleteExistingClips)
juce::ReferenceCountedObjectPtr< MidiClip > insertMIDIClip (TimeRange position, SelectionManager *selectionManagerToSelectWith)
juce::ReferenceCountedObjectPtr< MidiClip > insertMIDIClip (const juce::String &name, TimeRange position, SelectionManager *selectionManagerToSelectWith)
juce::ReferenceCountedObjectPtr< EditClip > insertEditClip (TimeRange position, ProjectItemID sourceID)
void deleteRegion (TimeRange, SelectionManager *)
void deleteRegionOfClip (Clip::Ptr, TimeRange, SelectionManager *)
Clip * splitClip (Clip &, TimePosition)
breaks a clip into 2 bits
void splitAt (TimePosition)
split all clips at this time
TimePosition getNextTimeOfInterest (TimePosition afterThisTime)
finds the next cut point
TimePosition getPreviousTimeOfInterest (TimePosition beforeThisTime)
bool containsPlugin (const Plugin *) const override
Tests whether this Track or a clip on it contains the given plugin.
Plugin::Array getAllPlugins () const override
Returns all pugins on this Track.
void sendMirrorUpdateToAllPlugins (Plugin &) const override
Sends a message to all plugins that the given plugin has changed.
bool areAnyClipsUsingFile (const AudioFile &)
bool containsAnyMIDIClips () const
juce::ValueTree & getClipOwnerState () override
EditItemID getClipOwnerID () override
Selectable * getClipOwnerSelectable () override
Edit & getClipOwnerEdit () override
void clipCreated (Clip &) override
void clipAddedOrRemoved () override
void clipOrderChanged () override
void clipPositionChanged () override
Public Member Functions inherited from tracktion::engine::Track
Track (Edit &, const juce::ValueTree &, bool hasModifierList)
Creates a track with a given state.
~Track () override
Destructor.
void refreshCurrentAutoParam ()
Updates the current parameter bases on the set IDs.
juce::String getName () const override
Returns the name of the Track.
void setName (const juce::String &)
Sets the name of the Track.
void resetName ()
Sets the name of the Track to an empty string.
virtual bool isAutomationTrack () const
Returns true if this is an AutomationTrack.
virtual bool isFolderTrack () const
Returns true if this is a FolderTrack.
virtual bool isMarkerTrack () const
Returns true if this is a MarkerTrack.
virtual bool isTempoTrack () const
Returns true if this is a TempoTrack.
virtual bool isChordTrack () const
Returns true if this is a ChordTrack.
virtual bool isArrangerTrack () const
Returns true if this is an ArrangerTrack.
virtual bool isMasterTrack () const
Returns true if this is a MasterTrack.
bool canContainMarkers () const
Returns true if this Track can contain MarkerClip[s].
bool canContainMIDI () const
Returns true if this Track can contain MidiClip[s].
bool canContainAudio () const
Returns true if this Track can contain WaveAudioClip[s].
bool canContainEditClips () const
Returns true if this Track can contain EditClip[s].
bool canContainPlugins () const
Returns true if this Track can contain Plugin[s].
bool isMovable () const
Returns true if this Track is movable.
bool acceptsInput () const
Returns true if this track can have inputs assigned to it.
bool createsOutput () const
Returns true if this track creates audible output.
bool wantsAutomation () const
Returns true if this track can show automation.
bool isHidden () const
Returns true if this track should be hidden from view.
void setHidden (bool h)
Sets whether this track should be hidden from view.
bool isProcessing (bool includeParents) const
Returns true if this track should be included in playback.
void setProcessing (bool p)
Sets whether this track should be included in playback.
juce::Array< Track * > getAllSubTracks (bool recursive) const
Returns all nested tracks.
juce::Array< AudioTrack * > getAllAudioSubTracks (bool recursive) const
Returns all nested AudioTrack[s].
TrackList * getSubTrackList () const
Returns the TrackList if this Track has any sub-tracks.
bool hasSubTracks () const
Returns true if this track has any subtracks.
Track * getSiblingTrack (int delta, bool keepWithinSameParent) const
Returns a sibling Track to this one.
juce::ValueTree getParentTrackTree () const
Returns the state of the parent Track.
Track * getParentTrack () const
Returns the parent Track if this is a nested track.
FolderTrack * getParentFolderTrack () const
Returns the parent FolderTrack if this is nested in one.
bool isAChildOf (const Track &possibleParent) const
Tests whether this is a child of a given Track.
bool isPartOfSubmix () const
Tests whether this nested within a submix FolderTrack.
int getIndexInEditTrackList () const
Returns the index of this track in a flat list of tracks contained in an Edit.
int getTrackDepth () const
Returns the number of parents within which this track is nested.
MuteAndSoloLightState getMuteAndSoloLightState () const
Returns the mute a solo status.
bool shouldBePlayed () const noexcept
Tests whether this track should be audible in the playback graph i.e.
void updateAudibility (bool areAnyTracksSolo)
Updates the audibility state of the Track.
juce::Array< AutomatableParameter * > getAllAutomatableParams () const
Returns all the parameters for this track's Plugin[s] and Modifier[s].
void visitAllAutomatableParams (const std::function< void(AutomatableParameter &)> &) const
Visits all the parameters for this track's Plugin[s] and Modifier[s].
AutomatableParameter * getCurrentlyShownAutoParam () const noexcept
Returns the parameter whos curve should be shown on this Track.
void setCurrentlyShownAutoParam (const AutomatableParameter::Ptr &)
Sets a parameter to display on this Track.
void hideAutomatableParametersForSource (EditItemID pluginOrParameterID)
Hides a shown parameter if it matches the given ID.
bool hasFreezePointPlugin () const
Tests whether this Track contains a FreezePointPlugin.
juce::Array< AutomatableEditItem * > getAllAutomatableEditItems () const
Returns all AutomatableEditItem[s] on this Track.
void flipAllPluginsEnablement ()
Toggles the Plugin::isEnabled state for all Plugin[s] on this Track.
ModifierList * getModifierList () const
Returns the ModifierList for this track, if it has one.
void setColour (juce::Colour newColour)
Sets a colour for this track to use.
juce::Colour getColour () const
Returns the the of this.
bool canShowImage () const
Tests whether this Track can show an image.
void setTrackImage (const juce::String &idOrData)
Sets some image data to use.
juce::String getTrackImage () const
Returns previously set image data.
bool imageHasChanged ()
Tests and resets a flag internally kept when the image changes.
void setTags (const juce::StringArray &)
Sets an array of Strings to use as tags.
juce::String getTags () const
Returns the tags as a pipe-separated single String.
const juce::StringArray & getTagsArray () const noexcept
Returns the array of tags.
Public Member Functions inherited from tracktion::engine::EditItem
EditItem (EditItemID, Edit &)
EditItem (Edit &, const juce::ValueTree &)
virtual ~EditItem ()=default
Public Member Functions inherited from tracktion::engine::Selectable
Selectable ()
virtual ~Selectable ()
virtual void selectionStatusChanged (bool isNowSelected)
Can be overridden to tell this object that it has just been selected or deselected.
virtual void changed ()
This should be called to send a change notification to any SelectableListeners that are registered with this object.
virtual void selectableAboutToBeDeleted ()
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void addListener (SelectableListener *)
void removeListener (SelectableListener *)
void addSelectableListener (SelectableListener *)
void removeSelectableListener (SelectableListener *)
void cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
void deselect ()
void propertiesChanged ()
void notifyListenersOfDeletion ()
WeakRef getWeakRef ()
Public Member Functions inherited from tracktion::engine::ClipOwner
ClipOwner ()
Constructs an empty ClipOwner.
virtual ~ClipOwner ()
Destructor.
const juce::Array< Clip * > & getClips () const
Returns the clips this owner contains.
Public Member Functions inherited from tracktion::engine::MacroParameterElement
MacroParameterElement (Edit &, const juce::ValueTree &)
Constructor.
virtual ~MacroParameterElement ()=default
Destructor.
MacroParameterList * getMacroParameterList ()
If no parameters have been created, this may return nullptr.
MacroParameterList & getMacroParameterListForWriting ()
This ensures that the list has been created.
juce::ReferenceCountedArray< MacroParameter > getMacroParameters () const
Public Attributes
juce::CachedValue< AtomicWrapper< bool > > playSlotClips
Determines if the track's arrange clips or clip slots should be audible.
Public Attributes inherited from tracktion::engine::Track
juce::ValueTree state
The state of this Track.
PluginList pluginList
The Track's PluginList.
juce::CachedValue< AutomationMode > automationMode
The automation mode for parameters on this track to use.
Public Attributes inherited from tracktion::engine::EditItem
Edit & edit
const EditItemID itemID
Every EditItem has an ID which is unique within the edit.
Public Attributes inherited from tracktion::engine::Selectable
WeakRef::Master masterReference
Public Attributes inherited from tracktion::engine::MacroParameterElement
Edit & ownerEdit
juce::ValueTree parentStateForList
Protected Member Functions
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeParentChanged (juce::ValueTree &v) override
bool isTrackAudible (bool areAnyTracksSolo) const override
Returns whether this Track should be audible.
void timerCallback () override
Protected Member Functions inherited from tracktion::engine::ClipTrack
juce::Array< TimePosition > findAllTimesOfInterest ()
void refreshTrackItems () const
Protected Member Functions inherited from tracktion::engine::Track
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeChildAdded (juce::ValueTree &, juce::ValueTree &) override
void valueTreeChildRemoved (juce::ValueTree &, juce::ValueTree &, int) override
void valueTreeChildOrderChanged (juce::ValueTree &, int, int) override
void valueTreeParentChanged (juce::ValueTree &) override
void handleAsyncUpdate () override
Protected Member Functions inherited from tracktion::engine::ClipOwner
void initialiseClipOwner (Edit &, juce::ValueTree clipParentState)
Must be called once from the subclass constructor to init the clip owner.
Additional Inherited Members
Static Public Member Functions inherited from tracktion::engine::Selectable
static void initialise ()
static bool isSelectableValid (const Selectable *) noexcept
checks whether this object has been deleted.
Static Public Attributes inherited from tracktion::engine::Track
static const int minTrackHeightForDetail = 10
The minimim height to show track contents at.
static const int trackHeightForEditor = 180
The height at which inline editors should be shown.
static const int frozenTrackHeight = 15
The height to show group frozen tracks.
Protected Attributes inherited from tracktion::engine::ClipTrack
std::unique_ptr< CollectionClipList > collectionClipList
bool trackItemsDirty = false
juce::Array< TrackItem * > trackItems
Member Typedef Documentation
Ptr
using tracktion::engine::AudioTrack::Ptr = juce::ReferenceCountedObjectPtr<AudioTrack>
Constructor & Destructor Documentation
AudioTrack()
tracktion::engine::AudioTrack::AudioTrack (Edit & , const juce::ValueTree &)
~AudioTrack()
tracktion::engine::AudioTrack::~AudioTrack () override
Member Function Documentation
initialise()
void tracktion::engine::AudioTrack::initialise () override virtual
Initialises the Track.
You shouldn't need to call this directly, it will be called by the track creation methods.
See also
Edit::insertTrack
Reimplemented from tracktion::engine::Track.
isAudioTrack()
bool tracktion::engine::AudioTrack::isAudioTrack () const override virtual
Returns true if this is an AudioTrack.
Reimplemented from tracktion::engine::Track.
getSelectableDescription()
juce::String tracktion::engine::AudioTrack::getSelectableDescription () override virtual
Subclasses must return a description of what they are.
Implements tracktion::engine::Selectable.
getAudioTrackNumber()
int tracktion::engine::AudioTrack::getAudioTrackNumber () const noexcept
sanityCheckName()
void tracktion::engine::AudioTrack::sanityCheckName () override virtual
checks whether the name is 'track n' and if so, makes sure the number is right
Reimplemented from tracktion::engine::Track.
getName()
juce::String tracktion::engine::AudioTrack::getName () const override virtual
Implements tracktion::engine::EditItem.
getNameAsTrackNumber()
juce::String tracktion::engine::AudioTrack::getNameAsTrackNumber () const
Returns a name in the form "Track [number]".
getNameAsTrackNumberWithDescription()
juce::String tracktion::engine::AudioTrack::getNameAsTrackNumberWithDescription () const
Returns a name in the form "Track [number] ([track name])" (This is smart enough to not add the parenthesised name if it's just a "Track X" type name)
canContainPlugin()
bool tracktion::engine::AudioTrack::canContainPlugin (Plugin *) const override virtual
Returns true if this track can contain a specific Plugin.
Subclasses can override this to avoid specific plugins such as VCAPlugin[s] on AudioTrack[s].
Implements tracktion::engine::Track.
processAudioNodesWhileMuted()
bool tracktion::engine::AudioTrack::processAudioNodesWhileMuted () const override virtual
Subclasses can override this to ensure track contents are still played even when the track is muted.
This may be required if this track is a sidechain source or feeding an aux for example.
Reimplemented from tracktion::engine::Track.
References tracktion::engine::EditItem::edit, tracktion::engine::Edit::engine, tracktion::engine::Engine::getEngineBehaviour(), and tracktion::engine::EngineBehaviour::shouldProcessMutedTracks().
getTrackPlayabilityWarning()
juce::String tracktion::engine::AudioTrack::getTrackPlayabilityWarning () const
returns a warning message about this track not being playable, or "" if it's ok
getLauncherPlayabilityWarning()
juce::String tracktion::engine::AudioTrack::getLauncherPlayabilityWarning () const
getVolumePlugin()
VolumeAndPanPlugin * tracktion::engine::AudioTrack::getVolumePlugin ()
getLevelMeterPlugin()
LevelMeterPlugin * tracktion::engine::AudioTrack::getLevelMeterPlugin ()
getEqualiserPlugin()
EqualiserPlugin * tracktion::engine::AudioTrack::getEqualiserPlugin ()
getAuxSendPlugin()
AuxSendPlugin * tracktion::engine::AudioTrack::getAuxSendPlugin (int bus = -1, AuxPosition ap = AuxPosition::byBus) const
getNameForMidiNoteNumber()
juce::String tracktion::engine::AudioTrack::getNameForMidiNoteNumber (int note, int midiChannel, bool preferSharp = true) const
looks for a name for a midi note by trying all the plugins, and returning a default on failure.
midiChannel is 1-16
getNameForProgramNumber()
juce::String tracktion::engine::AudioTrack::getNameForProgramNumber (int programNumber, int bank) const
prog number is 0 based.
getNameForBank()
juce::String tracktion::engine::AudioTrack::getNameForBank (int bank) const
getIdForBank()
int tracktion::engine::AudioTrack::getIdForBank (int bank) const
areMidiPatchesZeroBased()
bool tracktion::engine::AudioTrack::areMidiPatchesZeroBased () const
getWaveInputDevice()
WaveInputDevice & tracktion::engine::AudioTrack::getWaveInputDevice () const noexcept
getMidiInputDevice()
MidiInputDevice & tracktion::engine::AudioTrack::getMidiInputDevice () const noexcept
getOutput()
TrackOutput & tracktion::engine::AudioTrack::getOutput () const noexcept
getMaxNumOfInputs()
int tracktion::engine::AudioTrack::getMaxNumOfInputs () const noexcept
setMaxNumOfInputs()
void tracktion::engine::AudioTrack::setMaxNumOfInputs (int newMaxNumber)
canPlayAudio()
bool tracktion::engine::AudioTrack::canPlayAudio () const
checks whether audio clips can be played - i.e.
can they make it past the plugins, and is the track going to an audio output
canPlayMidi()
bool tracktion::engine::AudioTrack::canPlayMidi () const
getClipSlotList()
ClipSlotList & tracktion::engine::AudioTrack::getClipSlotList ()
Returns the ClipSlotList for this track.
isFrozen()
bool tracktion::engine::AudioTrack::isFrozen (FreezeType) const override virtual
Returns true if this track is frozen using the given type.
Reimplemented from tracktion::engine::Track.
setFrozen()
void tracktion::engine::AudioTrack::setFrozen (bool , FreezeType) override virtual
Attempts to freeze or unfreeze the track using a given FreezeType.
Reimplemented from tracktion::engine::Track.
insertFreezePointAfterPlugin()
void tracktion::engine::AudioTrack::insertFreezePointAfterPlugin (const Plugin::Ptr &)
removeFreezePoint()
void tracktion::engine::AudioTrack::removeFreezePoint ()
freezeTrackAsync()
void tracktion::engine::AudioTrack::freezeTrackAsync () const
hasAnyLiveInputs()
bool tracktion::engine::AudioTrack::hasAnyLiveInputs ()
hasAnyTracksFeedingIn()
bool tracktion::engine::AudioTrack::hasAnyTracksFeedingIn ()
getInputTracks()
juce::Array< Track * > tracktion::engine::AudioTrack::getInputTracks () const override virtual
Should return any tracks which feed into this track.
Reimplemented from tracktion::engine::Track.
findSidechainSourceTracks()
juce::Array< Track * > tracktion::engine::AudioTrack::findSidechainSourceTracks () const
injectLiveMidiMessage() [1/2]
void tracktion::engine::AudioTrack::injectLiveMidiMessage (const MidiMessageWithSource &)
injectLiveMidiMessage() [2/2]
void tracktion::engine::AudioTrack::injectLiveMidiMessage (const juce::MidiMessage & , MPESourceID)
isMuted()
bool tracktion::engine::AudioTrack::isMuted (bool) const override virtual
Returns true if this track is muted.
Parameters
includeMutingByDestination If this is true, this will retrn true if any tracks this feeds in to are muted.
Reimplemented from tracktion::engine::Track.
isSolo()
bool tracktion::engine::AudioTrack::isSolo (bool) const override virtual
Returns true if this track is soloed.
Parameters
includeIndirectSolo If this is true, this will retrn true if any tracks this feeds in to are soloed.
Reimplemented from tracktion::engine::Track.
isSoloIsolate()
bool tracktion::engine::AudioTrack::isSoloIsolate (bool) const override virtual
Returns true if this track is solo isolated.
Parameters
includeIndirectSolo If this is true, this will retrn true if any tracks this feeds in to are solo isolated.
Reimplemented from tracktion::engine::Track.
setMute()
void tracktion::engine::AudioTrack::setMute (bool) override virtual
Subclasses should implement this to mute themselves.
Reimplemented from tracktion::engine::Track.
setSolo()
void tracktion::engine::AudioTrack::setSolo (bool) override virtual
Subclasses should implement this to solo themselves.
Reimplemented from tracktion::engine::Track.
setSoloIsolate()
void tracktion::engine::AudioTrack::setSoloIsolate (bool) override virtual
Subclasses should implement this to solo isolate themselves.
Reimplemented from tracktion::engine::Track.
getMidiVisibleProportion()
double tracktion::engine::AudioTrack::getMidiVisibleProportion () const
vertical scales for displaying the midi note editor
getMidiVerticalOffset()
double tracktion::engine::AudioTrack::getMidiVerticalOffset () const
setMidiVerticalPos()
void tracktion::engine::AudioTrack::setMidiVerticalPos (double visibleProp, double offset)
scaleVerticallyToFitMidi()
void tracktion::engine::AudioTrack::scaleVerticallyToFitMidi ()
setVerticalScaleToDefault()
void tracktion::engine::AudioTrack::setVerticalScaleToDefault ()
setTrackToGhost()
void tracktion::engine::AudioTrack::setTrackToGhost (AudioTrack * , bool shouldGhost)
clearGhostTracks()
void tracktion::engine::AudioTrack::clearGhostTracks ()
getGhostTracks()
juce::Array< AudioTrack * > tracktion::engine::AudioTrack::getGhostTracks () const
getCompGroup()
int tracktion::engine::AudioTrack::getCompGroup () const noexcept
setCompGroup()
void tracktion::engine::AudioTrack::setCompGroup (int groupIndex)
hasMidiNoteNames()
bool tracktion::engine::AudioTrack::hasMidiNoteNames ()
clearMidiNoteNames()
void tracktion::engine::AudioTrack::clearMidiNoteNames ()
loadMidiNoteNames()
void tracktion::engine::AudioTrack::loadMidiNoteNames (const juce::String namesFile)
mergeInMidiSequence()
bool tracktion::engine::AudioTrack::mergeInMidiSequence (juce::MidiMessageSequence , TimePosition startTime, MidiClip * , MidiList::NoteAutomationType)
try to add this MIDI sequence to any MIDI clips that are already in the track.
Returns
False if there's no existing clips in the places it needs them.
playGuideNote()
void tracktion::engine::AudioTrack::playGuideNote (int note, MidiChannel midiChannel, int velocity, bool stopOtherFirst = true, bool forceNote = false, bool autorelease = false)
playGuideNotes()
void tracktion::engine::AudioTrack::playGuideNotes (const juce::Array< int > & notes, MidiChannel midiChannel, const juce::Array< int > & velocities, bool stopOthersFirst = true)
turnOffGuideNotes() [1/2]
void tracktion::engine::AudioTrack::turnOffGuideNotes ()
Referenced by timerCallback().
turnOffGuideNotes() [2/2]
void tracktion::engine::AudioTrack::turnOffGuideNotes (MidiChannel)
addListener()
void tracktion::engine::AudioTrack::addListener (Listener *)
Adds a Listener.
This will automatically call Edit::restartPlayback for the callbacks to take effect.
removeListener()
void tracktion::engine::AudioTrack::removeListener (Listener *)
Removes a Listener.
getListeners()
juce::ListenerList< Listener > & tracktion::engine::AudioTrack::getListeners ()
Returns the listener list so Nodes can manually call them.
valueTreePropertyChanged()
void tracktion::engine::AudioTrack::valueTreePropertyChanged (juce::ValueTree & , const juce::Identifier &) override protected
valueTreeParentChanged()
void tracktion::engine::AudioTrack::valueTreeParentChanged (juce::ValueTree & v) override protected
isTrackAudible()
bool tracktion::engine::AudioTrack::isTrackAudible (bool areAnyTracksSolo) const override protected virtual
Returns whether this Track should be audible.
Subclasses can override for custom behaviour.
Reimplemented from tracktion::engine::Track.
timerCallback()
void tracktion::engine::AudioTrack::timerCallback () override protected
References turnOffGuideNotes().
Member Data Documentation
playSlotClips
juce::CachedValue<AtomicWrapper<bool> > tracktion::engine::AudioTrack::playSlotClips
Determines if the track's arrange clips or clip slots should be audible.
The documentation for this class was generated from the following file:
tracktion_AudioTrack.h