TracktionEngine: PlaybackRegionWrapper Class Reference
PlaybackRegionWrapper Class Reference
Public Member Functions
PlaybackRegionWrapper (ARADocument &d, AudioClipBase &audioClip, const ARAFactory &factory, const AudioModificationWrapper &audioModification)
~PlaybackRegionWrapper ()
void updateRange ()
SizedStruct< ARA_MEMBER_PTR_ARGS(ARAPlaybackRegionProperties, color)> getPlaybackRegionProperties ()
NB: This is where time-stretching is setup.
Public Attributes
ARAPlaybackRegionRef playbackRegionRef = nullptr
ARADocument & doc
AudioClipBase & clip
Constructor & Destructor Documentation
PlaybackRegionWrapper()
PlaybackRegionWrapper::PlaybackRegionWrapper (ARADocument & d, AudioClipBase & audioClip, const ARAFactory & factory, const AudioModificationWrapper & audioModification)
References AudioModificationWrapper::audioModificationRef, clip, CRASH_TRACER, ARADocument::dci, ARADocument::dcRef, doc, ARADocument::edit, getPlaybackRegionProperties(), ARADocument::musicalContext, playbackRegionRef, and ARADocument::willCreatePlaybackRegionOnTrack().
~PlaybackRegionWrapper()
PlaybackRegionWrapper::~PlaybackRegionWrapper ()
References clip, CRASH_TRACER, ARADocument::dci, ARADocument::dcRef, doc, playbackRegionRef, and ARADocument::willDestroyPlaybackRegionOnTrack().
Member Function Documentation
updateRange()
void PlaybackRegionWrapper::updateRange ()
References CRASH_TRACER, ARADocument::dci, ARADocument::dcRef, doc, getPlaybackRegionProperties(), and playbackRegionRef.
getPlaybackRegionProperties()
SizedStruct<ARA_MEMBER_PTR_ARGS (ARAPlaybackRegionProperties, color)> PlaybackRegionWrapper::getPlaybackRegionProperties ()
NB: This is where time-stretching is setup.
References clip, doc, ARADocument::musicalContext, and ARADocument::regionSequences.
Referenced by PlaybackRegionWrapper(), and updateRange().
Member Data Documentation
playbackRegionRef
ARAPlaybackRegionRef PlaybackRegionWrapper::playbackRegionRef = nullptr
Referenced by PlaybackRegionWrapper(), updateRange(), and ~PlaybackRegionWrapper().
doc
ARADocument& PlaybackRegionWrapper::doc
Referenced by getPlaybackRegionProperties(), PlaybackRegionWrapper(), updateRange(), and ~PlaybackRegionWrapper().
clip
AudioClipBase& PlaybackRegionWrapper::clip
Referenced by getPlaybackRegionProperties(), PlaybackRegionWrapper(), and ~PlaybackRegionWrapper().
The documentation for this class was generated from the following file:
tracktion_ARAWrapperInterfaces.h