TracktionEngine: tracktion::engine::SampleFader Class Reference
tracktion::engine::SampleFader Class Reference
tracktion_engine » playback
#include <tracktion_ArrangerLauncherSwitchingNode.h>
Public Types
enum class FadeType { fadeOut , crossfade }
Public Member Functions
SampleFader ()=default
SampleFader (size_t numChannels)
void reset (size_t numChannels)
size_t getNumChannels () const
template<typename Buffer >
void push (const Buffer &buffer)
void trigger (size_t numFramesToFade_)
template<typename Buffer >
void apply (Buffer &&buffer, FadeType fadeType)
template<typename Buffer >
void applyAt (Buffer &buffer, choc::buffer::FrameCount frameNum, FadeType fadeType)
Member Enumeration Documentation
FadeType
enum class tracktion::engine::SampleFader::FadeType strong
Enumerator
fadeOut
crossfade
Constructor & Destructor Documentation
SampleFader() [1/2]
tracktion::engine::SampleFader::SampleFader () default
SampleFader() [2/2]
tracktion::engine::SampleFader::SampleFader (size_t numChannels)
References reset().
Member Function Documentation
reset()
void tracktion::engine::SampleFader::reset (size_t numChannels)
Referenced by SampleFader().
getNumChannels()
size_t tracktion::engine::SampleFader::getNumChannels () const
push()
template<typename Buffer > void tracktion::engine::SampleFader::push (const Buffer & buffer)
trigger()
void tracktion::engine::SampleFader::trigger (size_t numFramesToFade_)
apply()
template<typename Buffer > void tracktion::engine::SampleFader::apply (Buffer && buffer, FadeType fadeType)
References crossfade, and fadeOut.
Referenced by applyAt().
applyAt()
template<typename Buffer > void tracktion::engine::SampleFader::applyAt (Buffer & buffer, choc::buffer::FrameCount frameNum, FadeType fadeType)
References apply().
The documentation for this class was generated from the following file:
tracktion_ArrangerLauncherSwitchingNode.h