TracktionEngine: tracktion_engine::Selectable Class Reference
tracktion_engine::Selectable Class Reference abstract
Base class for things that can be selected, and whose properties can appear in the properties panel.
Public Types
using WeakRef = juce::WeakReference< Selectable >
Public Member Functions
Selectable ()
virtual ~Selectable ()
virtual juce::String getSelectableDescription ()=0
Subclasses must return a description of what they are.
virtual void selectionStatusChanged (bool isNowSelected)
Can be overridden to tell this object that it has just been selected or deselected.
virtual void changed ()
This should be called to send a change notification to any SelectableListeners that are registered with this object.
virtual void selectableAboutToBeDeleted ()
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void addSelectableListener (SelectableListener *)
void removeSelectableListener (SelectableListener *)
void cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
void deselect ()
void propertiesChanged ()
void notifyListenersOfDeletion ()
WeakRef getWeakRef ()
Static Public Member Functions
static void initialise ()
static bool isSelectableValid (const Selectable *) noexcept
checks whether this object has been deleted.
Public Attributes
WeakRef::Master masterReference
Detailed Description
Base class for things that can be selected, and whose properties can appear in the properties panel.
Member Typedef Documentation
WeakRef
using tracktion_engine::Selectable::WeakRef = juce::WeakReference<Selectable>
Constructor & Destructor Documentation
Selectable()
tracktion_engine::Selectable::Selectable ()
~Selectable()
virtual tracktion_engine::Selectable::~Selectable () virtual
Member Function Documentation
initialise()
static void tracktion_engine::Selectable::initialise () static
getSelectableDescription()
virtual juce::String tracktion_engine::Selectable::getSelectableDescription () pure virtual
Subclasses must return a description of what they are.
Implemented in tracktion_engine::MakeMonoEffect, tracktion_engine::NormaliseEffect, tracktion_engine::StepVolumeEffect, tracktion_engine::Edit, tracktion_engine::StepClip, tracktion_engine::AutomatableParameter, tracktion_engine::FourOscPlugin, tracktion_engine::ControlSurface, tracktion_engine::InputDeviceInstance::InputDeviceDestination, tracktion_engine::StepClip::PatternInstance, tracktion_engine::TempoSequence, tracktion_engine::Project, tracktion_engine::RackType, tracktion_engine::MidiClip, tracktion_engine::FreezePointPlugin, tracktion_engine::ExternalPlugin, tracktion_engine::TrackCompManager::TrackComp, tracktion_engine::InputDevice, tracktion_engine::ImpulseResponsePlugin, tracktion_engine::ProjectItem, tracktion_engine::WaveInputDevice, tracktion_engine::WaveAudioClip, tracktion_engine::DelayPlugin, tracktion_engine::SelectedMidiEvents, tracktion_engine::BreakpointOscillatorModifier, tracktion_engine::LFOModifier, tracktion_engine::MIDITrackerModifier, tracktion_engine::RandomModifier, tracktion_engine::StepModifier, tracktion_engine::EnvelopeFollowerModifier, tracktion_engine::SamplerPlugin, tracktion_engine::VolumeAndPanPlugin, tracktion_engine::AirWindowsPlugin, tracktion_engine::EditClip, tracktion_engine::TempoSetting, tracktion_engine::AuxSendPlugin, tracktion_engine::RackInstance, tracktion_engine::InsertPlugin, tracktion_engine::MidiModifierPlugin, tracktion_engine::PatchBayPlugin, tracktion_engine::TimeSigSetting, tracktion_engine::CompressorPlugin, tracktion_engine::CollectionClip, tracktion_engine::VCAPlugin, tracktion_engine::PitchShiftPlugin, tracktion_engine::StepClip::Channel, tracktion_engine::MasterTrack, tracktion_engine::OutputDevice, tracktion_engine::EqualiserPlugin, tracktion_engine::LevelMeterPlugin, tracktion_engine::TextPlugin, tracktion_engine::MidiPatchBayPlugin, tracktion_engine::TempoTrack, tracktion_engine::ToneGeneratorPlugin, tracktion_engine::ReverbPlugin, tracktion_engine::ChorusPlugin, tracktion_engine::PhaserPlugin, tracktion_engine::LatencyPlugin, tracktion_engine::MarkerClip, tracktion_engine::AudioTrack, tracktion_engine::PitchSetting, tracktion_engine::LowPassPlugin, tracktion_engine::AuxReturnPlugin, tracktion_engine::ArrangerClip, tracktion_engine::ChordClip, tracktion_engine::FolderTrack, tracktion_engine::VirtualMidiInputDevice, tracktion_engine::ArrangerTrack, tracktion_engine::AutomationTrack, tracktion_engine::ChordTrack, and tracktion_engine::MarkerTrack.
selectionStatusChanged()
virtual void tracktion_engine::Selectable::selectionStatusChanged (bool isNowSelected) virtual
Can be overridden to tell this object that it has just been selected or deselected.
Reimplemented in tracktion_engine::ProjectItem, tracktion_engine::SelectedMidiEvents, and tracktion_engine::CurveEditorPoint.
changed()
virtual void tracktion_engine::Selectable::changed () virtual
This should be called to send a change notification to any SelectableListeners that are registered with this object.
Reimplemented in tracktion_engine::AudioClipBase, tracktion_engine::Clip, tracktion_engine::Plugin, and tracktion_engine::EditClip.
selectableAboutToBeDeleted()
virtual void tracktion_engine::Selectable::selectableAboutToBeDeleted () virtual
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
Reimplemented in tracktion_engine::Plugin, and tracktion_engine::ExternalPlugin.
addSelectableListener()
void tracktion_engine::Selectable::addSelectableListener (SelectableListener *)
removeSelectableListener()
void tracktion_engine::Selectable::removeSelectableListener (SelectableListener *)
isSelectableValid()
static bool tracktion_engine::Selectable::isSelectableValid (const Selectable *) static noexcept
checks whether this object has been deleted.
This is pretty reliable, and can be called with a null pointer, but isn't 100% perfect, as it can provide a false-positive when an object is deleted, and another one later created that happens to have the same memory address.
cancelAnyPendingUpdates()
void tracktion_engine::Selectable::cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
deselect()
void tracktion_engine::Selectable::deselect ()
propertiesChanged()
void tracktion_engine::Selectable::propertiesChanged ()
notifyListenersOfDeletion()
void tracktion_engine::Selectable::notifyListenersOfDeletion ()
Referenced by tracktion_engine::DiscreteLabelledParameter::~DiscreteLabelledParameter(), tracktion_engine::ExternalAutomatableParameter::~ExternalAutomatableParameter(), tracktion_engine::InputDeviceInstance::InputDeviceDestination::~InputDeviceDestination(), tracktion_engine::InputDeviceInstance::MidiInputDeviceDestination::~MidiInputDeviceDestination(), tracktion_engine::StepClip::PatternInstance::~PatternInstance(), tracktion_engine::SuffixedParameter::~SuffixedParameter(), tracktion_engine::InputDeviceInstance::VirtualMidiInputDeviceDestination::~VirtualMidiInputDeviceDestination(), and tracktion_engine::InputDeviceInstance::WaveInputDeviceDestination::~WaveInputDeviceDestination().
getWeakRef()
WeakRef tracktion_engine::Selectable::getWeakRef ()
Member Data Documentation
masterReference
WeakRef::Master tracktion_engine::Selectable::masterReference
The documentation for this class was generated from the following file:
tracktion_Selectable.h