TracktionEngine: tracktion::engine::Engine Class Reference
tracktion::engine::Engine Class Reference
tracktion_engine » utilities
The Engine is the central class for all tracktion sessions.
#include <tracktion_Engine.h>
Public Types
using WeakRef = juce::WeakReference< Engine >
Public Member Functions
Engine (juce::String applicationName)
Constructs a default Engine with an application name.
Engine (juce::String applicationName, std::unique_ptr< UIBehaviour >, std::unique_ptr< EngineBehaviour >)
Constructs an Engine with an application name and custom UIBehaviour and EngineBehaviour.
Engine (std::unique_ptr< PropertyStorage >, std::unique_ptr< UIBehaviour >, std::unique_ptr< EngineBehaviour >)
Constructs an Engine with custom PropertyStorage, UIBehaviour and EngineBehaviour.
~Engine ()
Destructor.
TemporaryFileManager & getTemporaryFileManager () const
Returns the TemporaryFileManager allowing to handle the default app and user temporary folders.
AudioFileFormatManager & getAudioFileFormatManager () const
Returns the AudioFileFormatManager that maintains a list of available audio file formats.
PropertyStorage & getPropertyStorage () const
Returns the PropertyStorage user settings customisable XML file.
UIBehaviour & getUIBehaviour () const
Returns the UIBehaviour class.
EngineBehaviour & getEngineBehaviour () const
Returns the EngineBehaviour instance.
DeviceManager & getDeviceManager () const
Returns the DeviceManager instance for handling audio / MIDI devices.
MidiProgramManager & getMidiProgramManager () const
Returns the MidiProgramManager instance that handles MIDI banks, programs, sets or presets.
ExternalControllerManager & getExternalControllerManager () const
Returns the ExternalControllerManager instance.
RenderManager & getRenderManager () const
Returns the RenderManager instance.
BackgroundJobManager & getBackgroundJobs () const
Returns the BackgroundJobManager instance.
AudioFileManager & getAudioFileManager () const
Returns the AudioFileManager instance.
MidiLearnState & getMidiLearnState () const
Returns the MidiLearnState instance.
PluginManager & getPluginManager () const
Returns the PluginManager instance.
EditDeleter & getEditDeleter () const
Returns the EditDeleter instance.
RecordingThumbnailManager & getRecordingThumbnailManager () const
Returns the RecordingThumbnailManager instance.
WaveInputRecordingThread & getWaveInputRecordingThread () const
Returns the WaveInputRecordingThread instance.
ActiveEdits & getActiveEdits () const noexcept
Returns the ActiveEdits instance.
GrooveTemplateManager & getGrooveTemplateManager ()
Returns the GrooveTemplateManager instance.
CompFactory & getCompFactory () const
Returns the CompFactory instance.
WarpTimeFactory & getWarpTimeFactory () const
Returns the WarpTimeFactory instance.
ProjectManager & getProjectManager () const
Returns the ProjectManager instance.
SharedTimer & getBackToArrangerUpdateTimer () const
Returns the SharedTimer instance.
BufferedAudioFileManager & getBufferedAudioFileManager ()
Returns the BufferedAudioFileManager instance.
Static Public Member Functions
static juce::String getVersion ()
Returns the current version of Tracktion Engine.
static juce::Array< Engine * > getEngines ()
Returns the list of currently active engines.
Detailed Description
The Engine is the central class for all tracktion sessions.
Create a Engine before creating any edits. Pass in subclasses of behaviours to customise how the engine behaves or pass nullptr to use the defaults. To get going quickly, just use the constructor that takes an application name, which uses default settings.
Typical declaration in your main component:
private:
    tracktion_engine::Engine engine { ProjectInfo::projectName}
For Extended UI use:
private:
    tracktion_engine::Engine engine { ProjectInfo::projectName, std::make_unique<ExtendedUIBehaviour>(), nullptr };
Member Typedef Documentation
WeakRef
using tracktion::engine::Engine::WeakRef = juce::WeakReference<Engine>
Constructor & Destructor Documentation
Engine() [1/3]
tracktion::engine::Engine::Engine (juce::String applicationName)
Constructs a default Engine with an application name.
Engine() [2/3]
tracktion::engine::Engine::Engine (juce::String applicationName, std::unique_ptr< UIBehaviour > , std::unique_ptr< EngineBehaviour >)
Constructs an Engine with an application name and custom UIBehaviour and EngineBehaviour.
Engine() [3/3]
tracktion::engine::Engine::Engine (std::unique_ptr< PropertyStorage > , std::unique_ptr< UIBehaviour > , std::unique_ptr< EngineBehaviour >)
Constructs an Engine with custom PropertyStorage, UIBehaviour and EngineBehaviour.
~Engine()
tracktion::engine::Engine::~Engine ()
Destructor.
Member Function Documentation
getVersion()
static juce::String tracktion::engine::Engine::getVersion () static
Returns the current version of Tracktion Engine.
getEngines()
static juce::Array< Engine * > tracktion::engine::Engine::getEngines () static
Returns the list of currently active engines.
getTemporaryFileManager()
TemporaryFileManager & tracktion::engine::Engine::getTemporaryFileManager () const
Returns the TemporaryFileManager allowing to handle the default app and user temporary folders.
getAudioFileFormatManager()
AudioFileFormatManager & tracktion::engine::Engine::getAudioFileFormatManager () const
Returns the AudioFileFormatManager that maintains a list of available audio file formats.
getPropertyStorage()
PropertyStorage & tracktion::engine::Engine::getPropertyStorage () const
Returns the PropertyStorage user settings customisable XML file.
getUIBehaviour()
UIBehaviour & tracktion::engine::Engine::getUIBehaviour () const
Returns the UIBehaviour class.
getEngineBehaviour()
EngineBehaviour & tracktion::engine::Engine::getEngineBehaviour () const
Returns the EngineBehaviour instance.
Referenced by tracktion::engine::AudioTrack::processAudioNodesWhileMuted().
getDeviceManager()
DeviceManager & tracktion::engine::Engine::getDeviceManager () const
Returns the DeviceManager instance for handling audio / MIDI devices.
getMidiProgramManager()
MidiProgramManager & tracktion::engine::Engine::getMidiProgramManager () const
Returns the MidiProgramManager instance that handles MIDI banks, programs, sets or presets.
getExternalControllerManager()
ExternalControllerManager & tracktion::engine::Engine::getExternalControllerManager () const
Returns the ExternalControllerManager instance.
getRenderManager()
RenderManager & tracktion::engine::Engine::getRenderManager () const
Returns the RenderManager instance.
Referenced by tracktion::engine::WarpTimeRenderJob::getOrCreateRenderJob(), and tracktion::engine::ReverseRenderJob::getOrCreateRenderJob().
getBackgroundJobs()
BackgroundJobManager & tracktion::engine::Engine::getBackgroundJobs () const
Returns the BackgroundJobManager instance.
getAudioFileManager()
AudioFileManager & tracktion::engine::Engine::getAudioFileManager () const
Returns the AudioFileManager instance.
getMidiLearnState()
MidiLearnState & tracktion::engine::Engine::getMidiLearnState () const
Returns the MidiLearnState instance.
getPluginManager()
PluginManager & tracktion::engine::Engine::getPluginManager () const
Returns the PluginManager instance.
getEditDeleter()
EditDeleter & tracktion::engine::Engine::getEditDeleter () const
Returns the EditDeleter instance.
getRecordingThumbnailManager()
RecordingThumbnailManager & tracktion::engine::Engine::getRecordingThumbnailManager () const
Returns the RecordingThumbnailManager instance.
getWaveInputRecordingThread()
WaveInputRecordingThread & tracktion::engine::Engine::getWaveInputRecordingThread () const
Returns the WaveInputRecordingThread instance.
getActiveEdits()
ActiveEdits & tracktion::engine::Engine::getActiveEdits () const noexcept
Returns the ActiveEdits instance.
getGrooveTemplateManager()
GrooveTemplateManager & tracktion::engine::Engine::getGrooveTemplateManager ()
Returns the GrooveTemplateManager instance.
getCompFactory()
CompFactory & tracktion::engine::Engine::getCompFactory () const
Returns the CompFactory instance.
getWarpTimeFactory()
WarpTimeFactory & tracktion::engine::Engine::getWarpTimeFactory () const
Returns the WarpTimeFactory instance.
getProjectManager()
ProjectManager & tracktion::engine::Engine::getProjectManager () const
Returns the ProjectManager instance.
getBackToArrangerUpdateTimer()
SharedTimer & tracktion::engine::Engine::getBackToArrangerUpdateTimer () const
Returns the SharedTimer instance.
getBufferedAudioFileManager()
BufferedAudioFileManager & tracktion::engine::Engine::getBufferedAudioFileManager ()
Returns the BufferedAudioFileManager instance.
The documentation for this class was generated from the following file:
tracktion_Engine.h