TracktionEngine: tracktion_graph::PerformanceMeasurement Class Reference
tracktion_graph::PerformanceMeasurement Class Reference
A timer for measuring performance of code.
Classes
struct Statistics
Holds the current statistics.
Public Member Functions
PerformanceMeasurement (const std::string &counterName, int runsPerPrintout=100, bool printOnDestruction=true)
Creates a PerformanceMeasurement object.
~PerformanceMeasurement ()
Destructor.
void start () noexcept
Starts timing.
bool stop ()
Stops timing and prints out the results.
void printStatistics ()
Dumps the current metrics to std::cout.
Statistics getStatistics () const
Returns a copy of the current stats.
Statistics getStatisticsAndReset ()
Returns a copy of the current stats, and resets the internal counter.
Detailed Description
A timer for measuring performance of code.
e.g.
PerformanceMeasurement pc ("fish", 50);
for (;;)
{
    const ScopedPerformanceMeasurement (pc);
    doSomethingFishy();
}
In this example, the time of each period between calling start/stop will be measured and averaged over 50 runs, and the results logged to std::cout every 50 times round the loop.
Constructor & Destructor Documentation
PerformanceMeasurement()
tracktion_graph::PerformanceMeasurement::PerformanceMeasurement (const std::string & counterName, int runsPerPrintout = 100, bool printOnDestruction = true)
Creates a PerformanceMeasurement object.
Parameters
counterName the name used when printing out the statistics
runsPerPrintout the number of start/stop iterations before calling printStatistics()
References tracktion_graph::PerformanceMeasurement::Statistics::name.
~PerformanceMeasurement()
tracktion_graph::PerformanceMeasurement::~PerformanceMeasurement ()
Destructor.
References tracktion_graph::PerformanceMeasurement::Statistics::numRuns, and printStatistics().
Member Function Documentation
start()
void tracktion_graph::PerformanceMeasurement::start () noexcept
Starts timing.
See also
stop
Referenced by tracktion_graph::ScopedPerformanceMeasurement::ScopedPerformanceMeasurement(), and tracktion_engine::Benchmark::start().
stop()
bool tracktion_graph::PerformanceMeasurement::stop ()
Stops timing and prints out the results.
The number of iterations before doing a printout of the results is set in the constructor.
See also
start
References tracktion_graph::PerformanceMeasurement::Statistics::addResult(), tracktion_graph::PerformanceMeasurement::Statistics::numRuns, and printStatistics().
Referenced by tracktion_engine::Benchmark::stop(), and tracktion_graph::ScopedPerformanceMeasurement::~ScopedPerformanceMeasurement().
printStatistics()
void tracktion_graph::PerformanceMeasurement::printStatistics ()
Dumps the current metrics to std::cout.
References getStatisticsAndReset(), and tracktion_graph::PerformanceMeasurement::Statistics::toString().
Referenced by stop(), and ~PerformanceMeasurement().
getStatistics()
PerformanceMeasurement::Statistics tracktion_graph::PerformanceMeasurement::getStatistics () const
Returns a copy of the current stats.
Referenced by tracktion_engine::Benchmark::getResult().
getStatisticsAndReset()
PerformanceMeasurement::Statistics tracktion_graph::PerformanceMeasurement::getStatisticsAndReset ()
Returns a copy of the current stats, and resets the internal counter.
References tracktion_graph::PerformanceMeasurement::Statistics::clear().
Referenced by tracktion_graph::test_utilities::TestProcess< NodePlayerType >::getStatisticsAndReset(), and printStatistics().
The documentation for this class was generated from the following file:
tracktion_PerformanceMeasurement.h