TracktionEngine: tracktion::engine::ReferencedMaterialList Class Reference
tracktion::engine::ReferencedMaterialList Class Reference
A list of all the source files needed by an edit (or a section of an edit).
Classes
struct IntervalList
Represents the sections of a wave file that are being used.
Public Member Functions
ReferencedMaterialList (ProjectManager &pm, double handleSizeToUse)
void add (ProjectItemID id)
Adds the whole of a media id to the list.
void add (ProjectItemID id, double startTime, double length)
Adds just a section of a media id to the list.
void add (const Exportable::ReferencedItem &item)
void add (const ProjectItem::Ptr &mop, double start, double length)
juce::String getReassignedFileName (ProjectItemID id, double requiredTime, double &newStartTime, double &newLength) const
int getTotalNumThingsToExport ()
Public Attributes
ProjectManager & projectManager
juce::Array< ProjectItemID > ids
Detailed Description
A list of all the source files needed by an edit (or a section of an edit).
Constructor & Destructor Documentation
ReferencedMaterialList()
tracktion::engine::ReferencedMaterialList::ReferencedMaterialList (ProjectManager & pm, double handleSizeToUse)
Member Function Documentation
add() [1/4]
void tracktion::engine::ReferencedMaterialList::add (ProjectItemID id)
Adds the whole of a media id to the list.
References tracktion::engine::ProjectManager::getProjectItem(), and projectManager.
Referenced by add().
add() [2/4]
void tracktion::engine::ReferencedMaterialList::add (ProjectItemID id, double startTime, double length)
Adds just a section of a media id to the list.
References add(), tracktion::engine::ProjectManager::getProjectItem(), projectManager, and tracktion::engine::AppFunctions::start().
add() [3/4]
void tracktion::engine::ReferencedMaterialList::add (const Exportable::ReferencedItem & item)
References add(), tracktion::engine::Exportable::ReferencedItem::firstTimeUsed, tracktion::engine::Exportable::ReferencedItem::itemID, and tracktion::engine::Exportable::ReferencedItem::lengthUsed.
add() [4/4]
void tracktion::engine::ReferencedMaterialList::add (const ProjectItem::Ptr & mop, double start, double length)
References ids, and tracktion::engine::AppFunctions::start().
getReassignedFileName()
juce::String tracktion::engine::ReferencedMaterialList::getReassignedFileName (ProjectItemID id, double requiredTime, double & newStartTime, double & newLength) const
References tracktion::engine::ProjectManager::getProjectItem(), and projectManager.
getTotalNumThingsToExport()
int tracktion::engine::ReferencedMaterialList::getTotalNumThingsToExport ()
Member Data Documentation
projectManager
ProjectManager& tracktion::engine::ReferencedMaterialList::projectManager
Referenced by add(), and getReassignedFileName().
ids
juce::Array<ProjectItemID> tracktion::engine::ReferencedMaterialList::ids
Referenced by add().
The documentation for this class was generated from the following file:
tracktion_ReferencedMaterialList.h