TracktionEngine: tracktion_engine::MidiList Class Reference
tracktion_engine::MidiList Class Reference
Public Types
enum NoteAutomationType { NoteAutomationType::none, NoteAutomationType::expression }
Public Member Functions
MidiList ()
MidiList (const juce::ValueTree &, juce::UndoManager *)
~MidiList ()
void copyFrom (const MidiList &, juce::UndoManager *)
Clears the current list and copies the others contents and properties.
void addFrom (const MidiList &, juce::UndoManager *)
Adds copies of the events in another list to this one.
const juce::Array< MidiNote * > & getNotes () const
const juce::Array< MidiControllerEvent * > & getControllerEvents () const
const juce::Array< MidiSysexEvent * > & getSysexEvents () const
bool isAttachedToClip () const noexcept
void setCompList (bool shouldBeComp) noexcept
bool isCompList () const noexcept
MidiChannel getMidiChannel () const
Gets the list's midi channel number.
void setMidiChannel (MidiChannel chanNum)
Gives the list a channel number that it'll use when generating real midi messages.
juce::String getImportedMidiTrackName () const noexcept
If the data was pulled from a midi file then this may have a useful name describing its purpose.
bool isEmpty () const noexcept
void clear (juce::UndoManager *)
void trimOutside (double firstBeat, double lastBeat, juce::UndoManager *)
void moveAllBeatPositions (double deltaBeats, juce::UndoManager *)
void rescale (double factor, juce::UndoManager *)
int getNumNotes () const
MidiNote * getNote (int index) const
MidiNote * getNoteFor (const juce::ValueTree &)
juce::Range< int > getNoteNumberRange () const
double getFirstBeatNumber () const
Beat number of first event in the list.
double getLastBeatNumber () const
Beat number of last event in the list.
MidiNote * addNote (const MidiNote &, juce::UndoManager *)
MidiNote * addNote (int pitch, double startBeat, double lengthInBeats, int velocity, int colourIndex, juce::UndoManager *)
void removeNote (MidiNote &, juce::UndoManager *)
void removeAllNotes (juce::UndoManager *)
int getNumControllerEvents () const
MidiControllerEvent * getControllerEvent (int index) const
MidiControllerEvent * getControllerEventAt (double beatNumber, int controllerType) const
MidiControllerEvent * addControllerEvent (const MidiControllerEvent &, juce::UndoManager *)
MidiControllerEvent * addControllerEvent (double beat, int controllerType, int controllerValue, juce::UndoManager *)
MidiControllerEvent * addControllerEvent (double beat, int controllerType, int controllerValue, int metadata, juce::UndoManager *)
void removeControllerEvent (MidiControllerEvent &, juce::UndoManager *)
void removeAllControllers (juce::UndoManager *)
bool containsController (int controllerType) const
True if there are any controller events of this type.
void setControllerValueAt (int controllerType, double beatNumber, int newValue, juce::UndoManager *)
void removeControllersBetween (int controllerType, double beatNumberStart, double beatNumberEnd, juce::UndoManager *)
void insertRepeatedControllerValue (int type, int startVal, int endVal, juce::Range< double > rangeBeats, double intervalBeats, juce::UndoManager *)
Adds controller values over a specified time, at an even interval.
int getNumSysExEvents () const
MidiSysexEvent * getSysexEvent (int index) const
MidiSysexEvent * getSysexEventUnchecked (int index) const
MidiSysexEvent * getSysexEventFor (const juce::ValueTree &) const
MidiSysexEvent & addSysExEvent (const juce::MidiMessage &, double beatNumber, juce::UndoManager *)
void removeSysExEvent (const MidiSysexEvent &, juce::UndoManager *)
void removeAllSysexes (juce::UndoManager *)
void importMidiSequence (const juce::MidiMessageSequence &, Edit *, double editTimeOfListTimeZero, juce::UndoManager *)
Adds the contents of a MidiMessageSequence to this list.
void importFromEditTimeSequenceWithNoteExpression (const juce::MidiMessageSequence &, Edit *, double editTimeOfListTimeZero, juce::UndoManager *)
Adds the contents of a MidiSequence to this list assigning MPE expression changes to EXP expression.
void exportToPlaybackMidiSequence (juce::MidiMessageSequence &, MidiClip &, bool generateMPE) const
Static Public Member Functions
static juce::ValueTree createMidiList ()
static juce::MidiMessageSequence createDefaultPlaybackMidiSequence (const MidiList &, MidiClip &, bool generateMPE)
Creates the default MIDI playback sequence.
static bool looksLikeMPEData (const juce::File &)
static bool fileHasTempoChanges (const juce::File &)
static bool readSeparateTracksFromFile (const juce::File &, juce::OwnedArray< MidiList > &lists, juce::Array< double > &tempoChangeBeatNumbers, juce::Array< double > &bpms, juce::Array< int > &numerators, juce::Array< int > &denominators, double &songLength, bool importAsNoteExpression)
template<typename Type >
static void sortMidiEventsByTime (juce::Array< Type > &notes)
template<typename Type >
static void sortMidiEventsByNoteNumber (juce::Array< Type > &notes)
Public Attributes
juce::ValueTree state
Static Public Attributes
static constexpr const double defaultInitialTimbreValue = 0.5
static constexpr const double defaultInitialPitchBendValue = 0
static constexpr const double defaultInitialPressureValue = 0
Member Enumeration Documentation
NoteAutomationType
enum tracktion_engine::MidiList::NoteAutomationType strong
Enumerator
none
No automation, add the sequence as plain MIDI with the channel of the clip.
expression
Add the automation as EXP assuming the source sequence is MPE MIDI.
Constructor & Destructor Documentation
MidiList() [1/2]
tracktion_engine::MidiList::MidiList ()
MidiList() [2/2]
tracktion_engine::MidiList::MidiList (const juce::ValueTree & , juce::UndoManager *)
~MidiList()
tracktion_engine::MidiList::~MidiList ()
Member Function Documentation
createMidiList()
static juce::ValueTree tracktion_engine::MidiList::createMidiList () static
copyFrom()
void tracktion_engine::MidiList::copyFrom (const MidiList & , juce::UndoManager *)
Clears the current list and copies the others contents and properties.
addFrom()
void tracktion_engine::MidiList::addFrom (const MidiList & , juce::UndoManager *)
Adds copies of the events in another list to this one.
getNotes()
const juce::Array<MidiNote*>& tracktion_engine::MidiList::getNotes () const
Referenced by getNote(), and getNumNotes().
getControllerEvents()
const juce::Array<MidiControllerEvent*>& tracktion_engine::MidiList::getControllerEvents () const
Referenced by getControllerEvent(), and getNumControllerEvents().
getSysexEvents()
const juce::Array<MidiSysexEvent*>& tracktion_engine::MidiList::getSysexEvents () const
Referenced by getNumSysExEvents(), getSysexEvent(), and getSysexEventUnchecked().
isAttachedToClip()
bool tracktion_engine::MidiList::isAttachedToClip () const noexcept
References state.
setCompList()
void tracktion_engine::MidiList::setCompList (bool shouldBeComp) noexcept
isCompList()
bool tracktion_engine::MidiList::isCompList () const noexcept
getMidiChannel()
MidiChannel tracktion_engine::MidiList::getMidiChannel () const
Gets the list's midi channel number.
Value is 1 to 16.
Referenced by tracktion_engine::MidiClip::getMidiChannel().
setMidiChannel()
void tracktion_engine::MidiList::setMidiChannel (MidiChannel chanNum)
Gives the list a channel number that it'll use when generating real midi messages.
Value is 1 to 16.
Referenced by tracktion_engine::MidiClip::setMidiChannel().
getImportedMidiTrackName()
juce::String tracktion_engine::MidiList::getImportedMidiTrackName () const noexcept
If the data was pulled from a midi file then this may have a useful name describing its purpose.
isEmpty()
bool tracktion_engine::MidiList::isEmpty () const noexcept
References state.
clear()
void tracktion_engine::MidiList::clear (juce::UndoManager *)
trimOutside()
void tracktion_engine::MidiList::trimOutside (double firstBeat, double lastBeat, juce::UndoManager *)
moveAllBeatPositions()
void tracktion_engine::MidiList::moveAllBeatPositions (double deltaBeats, juce::UndoManager *)
rescale()
void tracktion_engine::MidiList::rescale (double factor, juce::UndoManager *)
getNumNotes()
int tracktion_engine::MidiList::getNumNotes () const
References getNotes().
getNote()
MidiNote* tracktion_engine::MidiList::getNote (int index) const
References getNotes().
getNoteFor()
MidiNote* tracktion_engine::MidiList::getNoteFor (const juce::ValueTree &)
getNoteNumberRange()
juce::Range<int> tracktion_engine::MidiList::getNoteNumberRange () const
getFirstBeatNumber()
double tracktion_engine::MidiList::getFirstBeatNumber () const
Beat number of first event in the list.
getLastBeatNumber()
double tracktion_engine::MidiList::getLastBeatNumber () const
Beat number of last event in the list.
addNote() [1/2]
MidiNote* tracktion_engine::MidiList::addNote (const MidiNote & , juce::UndoManager *)
addNote() [2/2]
MidiNote* tracktion_engine::MidiList::addNote (int pitch, double startBeat, double lengthInBeats, int velocity, int colourIndex, juce::UndoManager *)
removeNote()
void tracktion_engine::MidiList::removeNote (MidiNote & , juce::UndoManager *)
removeAllNotes()
void tracktion_engine::MidiList::removeAllNotes (juce::UndoManager *)
getNumControllerEvents()
int tracktion_engine::MidiList::getNumControllerEvents () const
References getControllerEvents().
getControllerEvent()
MidiControllerEvent* tracktion_engine::MidiList::getControllerEvent (int index) const
References getControllerEvents().
getControllerEventAt()
MidiControllerEvent* tracktion_engine::MidiList::getControllerEventAt (double beatNumber, int controllerType) const
addControllerEvent() [1/3]
MidiControllerEvent* tracktion_engine::MidiList::addControllerEvent (const MidiControllerEvent & , juce::UndoManager *)
addControllerEvent() [2/3]
MidiControllerEvent* tracktion_engine::MidiList::addControllerEvent (double beat, int controllerType, int controllerValue, juce::UndoManager *)
addControllerEvent() [3/3]
MidiControllerEvent* tracktion_engine::MidiList::addControllerEvent (double beat, int controllerType, int controllerValue, int metadata, juce::UndoManager *)
removeControllerEvent()
void tracktion_engine::MidiList::removeControllerEvent (MidiControllerEvent & , juce::UndoManager *)
removeAllControllers()
void tracktion_engine::MidiList::removeAllControllers (juce::UndoManager *)
containsController()
bool tracktion_engine::MidiList::containsController (int controllerType) const
True if there are any controller events of this type.
setControllerValueAt()
void tracktion_engine::MidiList::setControllerValueAt (int controllerType, double beatNumber, int newValue, juce::UndoManager *)
removeControllersBetween()
void tracktion_engine::MidiList::removeControllersBetween (int controllerType, double beatNumberStart, double beatNumberEnd, juce::UndoManager *)
insertRepeatedControllerValue()
void tracktion_engine::MidiList::insertRepeatedControllerValue (int type, int startVal, int endVal, juce::Range< double > rangeBeats, double intervalBeats, juce::UndoManager *)
Adds controller values over a specified time, at an even interval.
getNumSysExEvents()
int tracktion_engine::MidiList::getNumSysExEvents () const
References getSysexEvents().
getSysexEvent()
MidiSysexEvent* tracktion_engine::MidiList::getSysexEvent (int index) const
References getSysexEvents().
getSysexEventUnchecked()
MidiSysexEvent* tracktion_engine::MidiList::getSysexEventUnchecked (int index) const
References getSysexEvents().
getSysexEventFor()
MidiSysexEvent* tracktion_engine::MidiList::getSysexEventFor (const juce::ValueTree &) const
addSysExEvent()
MidiSysexEvent& tracktion_engine::MidiList::addSysExEvent (const juce::MidiMessage & , double beatNumber, juce::UndoManager *)
removeSysExEvent()
void tracktion_engine::MidiList::removeSysExEvent (const MidiSysexEvent & , juce::UndoManager *)
removeAllSysexes()
void tracktion_engine::MidiList::removeAllSysexes (juce::UndoManager *)
importMidiSequence()
void tracktion_engine::MidiList::importMidiSequence (const juce::MidiMessageSequence & , Edit * , double editTimeOfListTimeZero, juce::UndoManager *)
Adds the contents of a MidiMessageSequence to this list.
If an Edit is provided, it'll be used to convert the timestamps from possible seconds to beats
importFromEditTimeSequenceWithNoteExpression()
void tracktion_engine::MidiList::importFromEditTimeSequenceWithNoteExpression (const juce::MidiMessageSequence & , Edit * , double editTimeOfListTimeZero, juce::UndoManager *)
Adds the contents of a MidiSequence to this list assigning MPE expression changes to EXP expression.
exportToPlaybackMidiSequence()
void tracktion_engine::MidiList::exportToPlaybackMidiSequence (juce::MidiMessageSequence & , MidiClip & , bool generateMPE) const
createDefaultPlaybackMidiSequence()
static juce::MidiMessageSequence tracktion_engine::MidiList::createDefaultPlaybackMidiSequence (const MidiList & , MidiClip & , bool generateMPE) static
Creates the default MIDI playback sequence.
Referenced by tracktion_engine::EngineBehaviour::createPlaybackMidiSequence().
looksLikeMPEData()
static bool tracktion_engine::MidiList::looksLikeMPEData (const juce::File &) static
fileHasTempoChanges()
static bool tracktion_engine::MidiList::fileHasTempoChanges (const juce::File &) static
readSeparateTracksFromFile()
static bool tracktion_engine::MidiList::readSeparateTracksFromFile (const juce::File & , juce::OwnedArray< MidiList > & lists, juce::Array< double > & tempoChangeBeatNumbers, juce::Array< double > & bpms, juce::Array< int > & numerators, juce::Array< int > & denominators, double & songLength, bool importAsNoteExpression) static
sortMidiEventsByTime()
template<typename Type > static void tracktion_engine::MidiList::sortMidiEventsByTime (juce::Array< Type > & notes) static
sortMidiEventsByNoteNumber()
template<typename Type > static void tracktion_engine::MidiList::sortMidiEventsByNoteNumber (juce::Array< Type > & notes) static
Member Data Documentation
defaultInitialTimbreValue
constexpr const double tracktion_engine::MidiList::defaultInitialTimbreValue = 0.5 static constexpr
defaultInitialPitchBendValue
constexpr const double tracktion_engine::MidiList::defaultInitialPitchBendValue = 0 static constexpr
defaultInitialPressureValue
constexpr const double tracktion_engine::MidiList::defaultInitialPressureValue = 0 static constexpr
state
juce::ValueTree tracktion_engine::MidiList::state
Referenced by isAttachedToClip(), and isEmpty().
The documentation for this class was generated from the following file:
tracktion_MidiList.h