TracktionEngine: MusicalContextWrapper Class Reference
MusicalContextWrapper Class Reference
tracktion_engine » plugins
#include <tracktion_ARAWrapperInterfaces.h>
Public Member Functions
MusicalContextWrapper (ARADocument &doc)
~MusicalContextWrapper ()
void update ()
SizedStruct< ARA_STRUCT_MEMBER(ARAMusicalContextProperties, color)> getMusicalContextProperties ()
Static Public Member Functions
static ARABool ARA_CALL isMusicalContextContentAvailable (ARAContentAccessControllerHostRef editRef, ARAMusicalContextHostRef, ARAContentType type)
static ARAContentGrade ARA_CALL getMusicalContextContentGrade (ARAContentAccessControllerHostRef, ARAMusicalContextHostRef, ARAContentType)
static ARAContentReaderHostRef ARA_CALL createMusicalContextContentReader (ARAContentAccessControllerHostRef controllerHostRef, ARAMusicalContextHostRef, ARAContentType type, const ARAContentTimeRange *range)
static ARABool ARA_CALL isAudioSourceContentAvailable (ARAContentAccessControllerHostRef, ARAAudioSourceHostRef, ARAContentType)
static ARAContentGrade ARA_CALL getAudioSourceContentGrade (ARAContentAccessControllerHostRef, ARAAudioSourceHostRef, ARAContentType)
static ARAContentReaderHostRef ARA_CALL createAudioSourceContentReader (ARAContentAccessControllerHostRef, ARAAudioSourceHostRef, ARAContentType, const ARAContentTimeRange *)
static ARAInt32 ARA_CALL getContentReaderEventCount (ARAContentAccessControllerHostRef, ARAContentReaderHostRef contentReaderRef)
static const void *ARA_CALL getContentReaderDataForEvent (ARAContentAccessControllerHostRef, ARAContentReaderHostRef contentReaderRef, ARAInt32 eventIndex)
static void ARA_CALL destroyContentReader (ARAContentAccessControllerHostRef, ARAContentReaderHostRef contentReaderRef)
Public Attributes
ARADocument & document
ARAMusicalContextRef musicalContextRef = {}
Constructor & Destructor Documentation
MusicalContextWrapper()
MusicalContextWrapper::MusicalContextWrapper (ARADocument & doc)
References ARADocument::beginEditing(), CRASH_TRACER, ARADocument::dci, ARADocument::dcRef, document, ARADocument::edit, ARADocument::endEditing(), getMusicalContextProperties(), and musicalContextRef.
~MusicalContextWrapper()
MusicalContextWrapper::~MusicalContextWrapper ()
References CRASH_TRACER, ARADocument::dci, ARADocument::dcRef, document, and musicalContextRef.
Member Function Documentation
update()
void MusicalContextWrapper::update ()
References CRASH_TRACER, ARADocument::dci, ARADocument::dcRef, document, and musicalContextRef.
getMusicalContextProperties()
SizedStruct< ARA_STRUCT_MEMBER(ARAMusicalContextProperties, color)> MusicalContextWrapper::getMusicalContextProperties ()
Referenced by MusicalContextWrapper().
isMusicalContextContentAvailable()
static ARABool ARA_CALL MusicalContextWrapper::isMusicalContextContentAvailable (ARAContentAccessControllerHostRef editRef, ARAMusicalContextHostRef , ARAContentType type) static
getMusicalContextContentGrade()
static ARAContentGrade ARA_CALL MusicalContextWrapper::getMusicalContextContentGrade (ARAContentAccessControllerHostRef , ARAMusicalContextHostRef , ARAContentType) static
createMusicalContextContentReader()
static ARAContentReaderHostRef ARA_CALL MusicalContextWrapper::createMusicalContextContentReader (ARAContentAccessControllerHostRef controllerHostRef, ARAMusicalContextHostRef , ARAContentType type, const ARAContentTimeRange * range) static
isAudioSourceContentAvailable()
static ARABool ARA_CALL MusicalContextWrapper::isAudioSourceContentAvailable (ARAContentAccessControllerHostRef , ARAAudioSourceHostRef , ARAContentType) static
getAudioSourceContentGrade()
static ARAContentGrade ARA_CALL MusicalContextWrapper::getAudioSourceContentGrade (ARAContentAccessControllerHostRef , ARAAudioSourceHostRef , ARAContentType) static
createAudioSourceContentReader()
static ARAContentReaderHostRef ARA_CALL MusicalContextWrapper::createAudioSourceContentReader (ARAContentAccessControllerHostRef , ARAAudioSourceHostRef , ARAContentType , const ARAContentTimeRange *) static
getContentReaderEventCount()
static ARAInt32 ARA_CALL MusicalContextWrapper::getContentReaderEventCount (ARAContentAccessControllerHostRef , ARAContentReaderHostRef contentReaderRef) static
References CRASH_TRACER.
getContentReaderDataForEvent()
static const void *ARA_CALL MusicalContextWrapper::getContentReaderDataForEvent (ARAContentAccessControllerHostRef , ARAContentReaderHostRef contentReaderRef, ARAInt32 eventIndex) static
References CRASH_TRACER.
destroyContentReader()
static void ARA_CALL MusicalContextWrapper::destroyContentReader (ARAContentAccessControllerHostRef , ARAContentReaderHostRef contentReaderRef) static
References CRASH_TRACER.
Member Data Documentation
document
ARADocument& MusicalContextWrapper::document
Referenced by MusicalContextWrapper(), update(), and ~MusicalContextWrapper().
musicalContextRef
ARAMusicalContextRef MusicalContextWrapper::musicalContextRef = {}
Referenced by MusicalContextWrapper(), update(), and ~MusicalContextWrapper().
The documentation for this class was generated from the following file:
tracktion_ARAWrapperInterfaces.h