TracktionEngine: tracktion_engine::MultiThreadedNodePlayer Class Reference
tracktion_engine::MultiThreadedNodePlayer Class Reference
Plays back a Node with PlayHeadState and ProcessState.
Public Member Functions
MultiThreadedNodePlayer (ProcessState &processStateToUse)
Creates an NodePlayer to process a Node.
MultiThreadedNodePlayer (std::unique_ptr< tracktion_graph::Node > node, ProcessState &processStateToUse, double sampleRate, int blockSize)
Creates an NodePlayer to process a Node.
void setNumThreads (size_t numThreads)
Sets the number of threads to use for rendering.
tracktion_graph::Node * getNode ()
void setNode (std::unique_ptr< tracktion_graph::Node > newNode)
void setNode (std::unique_ptr< tracktion_graph::Node > newNode, double sampleRateToUse, int blockSizeToUse)
void prepareToPlay (double sampleRateToUse, int blockSizeToUse)
int process (const tracktion_graph::Node::ProcessContext &pc)
Processes a block of audio and MIDI data.
void clearNode ()
Clears the Node currently playing.
double getSampleRate () const
Returns the current sample rate.
Detailed Description
Plays back a Node with PlayHeadState and ProcessState.
Constructor & Destructor Documentation
MultiThreadedNodePlayer() [1/2]
tracktion_engine::MultiThreadedNodePlayer::MultiThreadedNodePlayer (ProcessState & processStateToUse)
Creates an NodePlayer to process a Node.
MultiThreadedNodePlayer() [2/2]
tracktion_engine::MultiThreadedNodePlayer::MultiThreadedNodePlayer (std::unique_ptr< tracktion_graph::Node > node, ProcessState & processStateToUse, double sampleRate, int blockSize)
Creates an NodePlayer to process a Node.
References tracktion_graph::MultiThreadedNodePlayer::setNode().
Member Function Documentation
setNumThreads()
void tracktion_engine::MultiThreadedNodePlayer::setNumThreads (size_t numThreads)
Sets the number of threads to use for rendering.
This can be 0 in which case only the process calling thread will be used for processing. N.B. this will pause processing whilst updating the threads so there will be a gap in the audio.
References tracktion_graph::MultiThreadedNodePlayer::setNumThreads().
getNode()
tracktion_graph::Node* tracktion_engine::MultiThreadedNodePlayer::getNode ()
References tracktion_graph::MultiThreadedNodePlayer::getNode().
setNode() [1/2]
void tracktion_engine::MultiThreadedNodePlayer::setNode (std::unique_ptr< tracktion_graph::Node > newNode)
References tracktion_graph::MultiThreadedNodePlayer::setNode().
setNode() [2/2]
void tracktion_engine::MultiThreadedNodePlayer::setNode (std::unique_ptr< tracktion_graph::Node > newNode, double sampleRateToUse, int blockSizeToUse)
References tracktion_graph::MultiThreadedNodePlayer::setNode().
prepareToPlay()
void tracktion_engine::MultiThreadedNodePlayer::prepareToPlay (double sampleRateToUse, int blockSizeToUse)
References tracktion_graph::MultiThreadedNodePlayer::prepareToPlay().
process()
int tracktion_engine::MultiThreadedNodePlayer::process (const tracktion_graph::Node::ProcessContext & pc)
Processes a block of audio and MIDI data.
Returns the number of times a node was checked but unable to be processed.
References tracktion_graph::PlayHeadState::playHead, tracktion_graph::Node::ProcessContext::referenceSampleRange, and tracktion_graph::PlayHead::setReferenceSampleRange().
clearNode()
void tracktion_engine::MultiThreadedNodePlayer::clearNode ()
Clears the Node currently playing.
References tracktion_graph::MultiThreadedNodePlayer::clearNode().
getSampleRate()
double tracktion_engine::MultiThreadedNodePlayer::getSampleRate () const
Returns the current sample rate.
References tracktion_graph::MultiThreadedNodePlayer::getSampleRate().
The documentation for this class was generated from the following file:
tracktion_MultiThreadedNodePlayer.h