TracktionEngine: tracktion_engine::ExternalController Class Reference
tracktion_engine::ExternalController Class Reference
Acts as a holder for a ControlSurface object.
Public Member Functions
ExternalController (Engine &, ControlSurface *)
~ExternalController () override
juce::String getName () const
bool needsMidiChannel () const
bool needsMidiBackChannel () const
bool needsOSCSocket () const
juce::String getMidiInputDevice () const
void setMidiInputDevice (const juce::String &nameOfMidiInput)
juce::String getBackChannelDevice () const
void setBackChannelDevice (const juce::String &nameOfMidiOutput)
bool isUsingMidiOutputDevice (const MidiOutputDevice *d) const noexcept
int getOSCInputPort ()
void setOSCInputPort (int port)
int getOSCOutputPort ()
void setOSCOutputPort (int port)
juce::String getOSCOutputAddress ()
void setOSCOutputAddress (const juce::String addr)
bool isEnabled () const
void setEnabled (bool)
bool isDeletable () const
void deleteController ()
bool wantsMidiClock () const
void currentEditChanged (Edit *)
void moveFader (int channelNum, float newSliderPos)
void moveMasterFaders (float newLeftPos, float newRightPos)
void movePanPot (int channelNum, float newPan)
void updateSoloAndMute (int channelNum, Track::MuteAndSoloLightState, bool isBright)
void soloCountChanged (bool)
void playStateChanged (bool isPlaying)
void recordStateChanged (bool isRecording)
void automationModeChanged (bool isReading, bool isWriting)
void snapChanged (bool isOn)
void loopChanged (bool isOn)
void clickChanged (bool isOn)
void channelLevelChanged (int channel, float level)
void masterLevelsChanged (float leftLevel, float rightLevel)
void timecodeChanged (int barsOrHours, int beatsOrMinutes, int ticksOrSeconds, int millisecs, bool isBarsBeats, bool isFrames)
void trackSelected (int channel, bool isSelected)
void selectOtherObject (SelectableClass::Relationship, bool moveFromCurrentPlugin)
void muteOrUnmutePlugin ()
void muteOrUnmutePluginsInTrack ()
void changePluginPreset (int delta)
void soloPluginTrack ()
void auxSendLevelsChanged ()
void updateDeviceState ()
void updateParameters ()
void updateMarkers ()
void selectedPluginChanged ()
void selectableObjectChanged (Selectable *) override
void selectableObjectAboutToBeDeleted (Selectable *) override
void curveHasChanged (AutomatableParameter &) override
Called when the automation curve has changed, point time, value or curve.
void currentValueChanged (AutomatableParameter &, float) override
Called when the current value of the parameter changed, either from setting the parameter, automation, a macro or modifier.
void updateTrackSelectLights ()
void updateTrackRecordLights ()
void updatePunchLights ()
void updateUndoLights ()
int getNumFaderChannels () const noexcept
int getFaderIndexInActiveRegion (int num) const noexcept
juce::Range< int > getActiveChannels () const noexcept
int getNumParameterControls () const noexcept
juce::Range< int > getActiveParams () const noexcept
void midiInOutDevicesChanged ()
void oscSettingsChanged ()
void handleAsyncUpdate () override
void acceptMidiMessage (const juce::MidiMessage &)
bool wantsMessage (const juce::MidiMessage &)
bool eatsAllMessages () const
bool canSetEatsAllMessages ()
void setEatsAllMessages (bool eatAll)
juce::Colour getSelectionColour () const
bool getShowSelectionColour () const
void setSelectionColour (juce::Colour)
void setShowSelectionColour (bool)
bool shouldTrackBeColoured (int channelNum)
void getTrackColour (int channelNum, juce::Colour &)
bool shouldPluginBeColoured (Plugin *)
void getPluginColour (Plugin *, juce::Colour &)
void repaintParamSource ()
void redrawTracks ()
ControlSurface & getControlSurface () const noexcept
template<typename Type >
Type * getControlSurfaceIfType () const noexcept
ExternalControllerManager & getExternalControllerManager () const noexcept
Edit * getEdit () const
TransportControl * getTransport () const noexcept
juce::String getInputDeviceName () const
juce::String getOutputDeviceName () const
juce::StringArray getMidiInputPorts () const
juce::StringArray getMidiOutputPorts () const
Static Public Member Functions
static juce::String shortenName (juce::String, int maxLen)
static juce::String getNoDeviceSelectedMessage ()
Public Attributes
Engine & engine
Detailed Description
Acts as a holder for a ControlSurface object.
Constructor & Destructor Documentation
ExternalController()
tracktion_engine::ExternalController::ExternalController (Engine & , ControlSurface *)
~ExternalController()
tracktion_engine::ExternalController::~ExternalController () override
Member Function Documentation
getName()
juce::String tracktion_engine::ExternalController::getName () const
needsMidiChannel()
bool tracktion_engine::ExternalController::needsMidiChannel () const
needsMidiBackChannel()
bool tracktion_engine::ExternalController::needsMidiBackChannel () const
needsOSCSocket()
bool tracktion_engine::ExternalController::needsOSCSocket () const
getMidiInputDevice()
juce::String tracktion_engine::ExternalController::getMidiInputDevice () const
setMidiInputDevice()
void tracktion_engine::ExternalController::setMidiInputDevice (const juce::String & nameOfMidiInput)
getBackChannelDevice()
juce::String tracktion_engine::ExternalController::getBackChannelDevice () const
setBackChannelDevice()
void tracktion_engine::ExternalController::setBackChannelDevice (const juce::String & nameOfMidiOutput)
isUsingMidiOutputDevice()
bool tracktion_engine::ExternalController::isUsingMidiOutputDevice (const MidiOutputDevice * d) const noexcept
getOSCInputPort()
int tracktion_engine::ExternalController::getOSCInputPort ()
setOSCInputPort()
void tracktion_engine::ExternalController::setOSCInputPort (int port)
getOSCOutputPort()
int tracktion_engine::ExternalController::getOSCOutputPort ()
setOSCOutputPort()
void tracktion_engine::ExternalController::setOSCOutputPort (int port)
getOSCOutputAddress()
juce::String tracktion_engine::ExternalController::getOSCOutputAddress ()
setOSCOutputAddress()
void tracktion_engine::ExternalController::setOSCOutputAddress (const juce::String addr)
isEnabled()
bool tracktion_engine::ExternalController::isEnabled () const
setEnabled()
void tracktion_engine::ExternalController::setEnabled (bool)
isDeletable()
bool tracktion_engine::ExternalController::isDeletable () const
deleteController()
void tracktion_engine::ExternalController::deleteController ()
wantsMidiClock()
bool tracktion_engine::ExternalController::wantsMidiClock () const
currentEditChanged()
void tracktion_engine::ExternalController::currentEditChanged (Edit *)
moveFader()
void tracktion_engine::ExternalController::moveFader (int channelNum, float newSliderPos)
moveMasterFaders()
void tracktion_engine::ExternalController::moveMasterFaders (float newLeftPos, float newRightPos)
movePanPot()
void tracktion_engine::ExternalController::movePanPot (int channelNum, float newPan)
updateSoloAndMute()
void tracktion_engine::ExternalController::updateSoloAndMute (int channelNum, Track::MuteAndSoloLightState , bool isBright)
soloCountChanged()
void tracktion_engine::ExternalController::soloCountChanged (bool)
playStateChanged()
void tracktion_engine::ExternalController::playStateChanged (bool isPlaying)
recordStateChanged()
void tracktion_engine::ExternalController::recordStateChanged (bool isRecording)
automationModeChanged()
void tracktion_engine::ExternalController::automationModeChanged (bool isReading, bool isWriting)
snapChanged()
void tracktion_engine::ExternalController::snapChanged (bool isOn)
loopChanged()
void tracktion_engine::ExternalController::loopChanged (bool isOn)
clickChanged()
void tracktion_engine::ExternalController::clickChanged (bool isOn)
channelLevelChanged()
void tracktion_engine::ExternalController::channelLevelChanged (int channel, float level)
masterLevelsChanged()
void tracktion_engine::ExternalController::masterLevelsChanged (float leftLevel, float rightLevel)
timecodeChanged()
void tracktion_engine::ExternalController::timecodeChanged (int barsOrHours, int beatsOrMinutes, int ticksOrSeconds, int millisecs, bool isBarsBeats, bool isFrames)
trackSelected()
void tracktion_engine::ExternalController::trackSelected (int channel, bool isSelected)
selectOtherObject()
void tracktion_engine::ExternalController::selectOtherObject (SelectableClass::Relationship , bool moveFromCurrentPlugin)
muteOrUnmutePlugin()
void tracktion_engine::ExternalController::muteOrUnmutePlugin ()
muteOrUnmutePluginsInTrack()
void tracktion_engine::ExternalController::muteOrUnmutePluginsInTrack ()
changePluginPreset()
void tracktion_engine::ExternalController::changePluginPreset (int delta)
soloPluginTrack()
void tracktion_engine::ExternalController::soloPluginTrack ()
auxSendLevelsChanged()
void tracktion_engine::ExternalController::auxSendLevelsChanged ()
updateDeviceState()
void tracktion_engine::ExternalController::updateDeviceState ()
updateParameters()
void tracktion_engine::ExternalController::updateParameters ()
updateMarkers()
void tracktion_engine::ExternalController::updateMarkers ()
selectedPluginChanged()
void tracktion_engine::ExternalController::selectedPluginChanged ()
selectableObjectChanged()
void tracktion_engine::ExternalController::selectableObjectChanged (Selectable *) override virtual
Implements tracktion_engine::SelectableListener.
selectableObjectAboutToBeDeleted()
void tracktion_engine::ExternalController::selectableObjectAboutToBeDeleted (Selectable *) override virtual
Implements tracktion_engine::SelectableListener.
curveHasChanged()
void tracktion_engine::ExternalController::curveHasChanged (AutomatableParameter &) override virtual
Called when the automation curve has changed, point time, value or curve.
Implements tracktion_engine::AutomatableParameter::Listener.
currentValueChanged()
void tracktion_engine::ExternalController::currentValueChanged (AutomatableParameter & , float) override virtual
Called when the current value of the parameter changed, either from setting the parameter, automation, a macro or modifier.
This will be called on the audio thread so make sure you don't do anything time consuming or block etc.
Reimplemented from tracktion_engine::AutomatableParameter::Listener.
updateTrackSelectLights()
void tracktion_engine::ExternalController::updateTrackSelectLights ()
updateTrackRecordLights()
void tracktion_engine::ExternalController::updateTrackRecordLights ()
updatePunchLights()
void tracktion_engine::ExternalController::updatePunchLights ()
updateUndoLights()
void tracktion_engine::ExternalController::updateUndoLights ()
getNumFaderChannels()
int tracktion_engine::ExternalController::getNumFaderChannels () const noexcept
getFaderIndexInActiveRegion()
int tracktion_engine::ExternalController::getFaderIndexInActiveRegion (int num) const noexcept
getActiveChannels()
juce::Range<int> tracktion_engine::ExternalController::getActiveChannels () const noexcept
getNumParameterControls()
int tracktion_engine::ExternalController::getNumParameterControls () const noexcept
getActiveParams()
juce::Range<int> tracktion_engine::ExternalController::getActiveParams () const noexcept
midiInOutDevicesChanged()
void tracktion_engine::ExternalController::midiInOutDevicesChanged ()
oscSettingsChanged()
void tracktion_engine::ExternalController::oscSettingsChanged ()
handleAsyncUpdate()
void tracktion_engine::ExternalController::handleAsyncUpdate () override
acceptMidiMessage()
void tracktion_engine::ExternalController::acceptMidiMessage (const juce::MidiMessage &)
wantsMessage()
bool tracktion_engine::ExternalController::wantsMessage (const juce::MidiMessage &)
eatsAllMessages()
bool tracktion_engine::ExternalController::eatsAllMessages () const
canSetEatsAllMessages()
bool tracktion_engine::ExternalController::canSetEatsAllMessages ()
setEatsAllMessages()
void tracktion_engine::ExternalController::setEatsAllMessages (bool eatAll)
getSelectionColour()
juce::Colour tracktion_engine::ExternalController::getSelectionColour () const
getShowSelectionColour()
bool tracktion_engine::ExternalController::getShowSelectionColour () const
setSelectionColour()
void tracktion_engine::ExternalController::setSelectionColour (juce::Colour)
setShowSelectionColour()
void tracktion_engine::ExternalController::setShowSelectionColour (bool)
shouldTrackBeColoured()
bool tracktion_engine::ExternalController::shouldTrackBeColoured (int channelNum)
getTrackColour()
void tracktion_engine::ExternalController::getTrackColour (int channelNum, juce::Colour &)
shouldPluginBeColoured()
bool tracktion_engine::ExternalController::shouldPluginBeColoured (Plugin *)
getPluginColour()
void tracktion_engine::ExternalController::getPluginColour (Plugin * , juce::Colour &)
repaintParamSource()
void tracktion_engine::ExternalController::repaintParamSource ()
redrawTracks()
void tracktion_engine::ExternalController::redrawTracks ()
getControlSurface()
ControlSurface& tracktion_engine::ExternalController::getControlSurface () const noexcept
Referenced by getEdit(), and getTransport().
getControlSurfaceIfType()
template<typename Type > Type* tracktion_engine::ExternalController::getControlSurfaceIfType () const noexcept
getExternalControllerManager()
ExternalControllerManager& tracktion_engine::ExternalController::getExternalControllerManager () const noexcept
getEdit()
Edit* tracktion_engine::ExternalController::getEdit () const
References getControlSurface(), and tracktion_engine::ControlSurface::getEdit().
getTransport()
TransportControl* tracktion_engine::ExternalController::getTransport () const noexcept
References getControlSurface(), and tracktion_engine::ControlSurface::getTransport().
shortenName()
static juce::String tracktion_engine::ExternalController::shortenName (juce::String , int maxLen) static
getInputDeviceName()
juce::String tracktion_engine::ExternalController::getInputDeviceName () const
getOutputDeviceName()
juce::String tracktion_engine::ExternalController::getOutputDeviceName () const
getMidiInputPorts()
juce::StringArray tracktion_engine::ExternalController::getMidiInputPorts () const
getMidiOutputPorts()
juce::StringArray tracktion_engine::ExternalController::getMidiOutputPorts () const
getNoDeviceSelectedMessage()
static juce::String tracktion_engine::ExternalController::getNoDeviceSelectedMessage () static
Member Data Documentation
engine
Engine& tracktion_engine::ExternalController::engine
The documentation for this class was generated from the following file:
tracktion_ExternalController.h