TracktionEngine: tracktion::graph::AudioFifo Class Reference
tracktion::graph::AudioFifo Class Reference
Public Member Functions
AudioFifo (choc::buffer::ChannelCount numChannels, choc::buffer::FrameCount numFrames)
void setSize (choc::buffer::ChannelCount numChannels, choc::buffer::FrameCount numFrames)
int getFreeSpace () const noexcept
int getNumReady () const noexcept
choc::buffer::ChannelCount getNumChannels () const noexcept
void reset () noexcept
void ensureFreeSpace (int numFrames)
bool write (choc::buffer::ChannelArrayView< float > block)
bool writeSilence (choc::buffer::FrameCount numFrames)
bool readAdding (choc::buffer::ChannelArrayView< float > dest)
bool readOverwriting (choc::buffer::ChannelArrayView< float > dest)
void removeSamples (int numSamples)
Constructor & Destructor Documentation
AudioFifo()
tracktion::graph::AudioFifo::AudioFifo (choc::buffer::ChannelCount numChannels, choc::buffer::FrameCount numFrames)
References setSize().
Member Function Documentation
setSize()
void tracktion::graph::AudioFifo::setSize (choc::buffer::ChannelCount numChannels, choc::buffer::FrameCount numFrames)
Referenced by AudioFifo(), and tracktion::graph::LatencyProcessor::prepareToPlay().
getFreeSpace()
int tracktion::graph::AudioFifo::getFreeSpace () const noexcept
Referenced by ensureFreeSpace().
getNumReady()
int tracktion::graph::AudioFifo::getNumReady () const noexcept
Referenced by ensureFreeSpace(), tracktion::graph::LatencyProcessor::prepareToPlay(), tracktion::graph::LatencyProcessor::readAudioAdding(), and tracktion::graph::LatencyProcessor::readAudioOverwriting().
getNumChannels()
choc::buffer::ChannelCount tracktion::graph::AudioFifo::getNumChannels () const noexcept
Referenced by tracktion::graph::LatencyProcessor::hasConfiguration(), tracktion::graph::LatencyProcessor::hasSameConfigurationAs(), tracktion::graph::LatencyProcessor::readAudioAdding(), tracktion::graph::LatencyProcessor::readAudioOverwriting(), and tracktion::graph::LatencyProcessor::writeAudio().
reset()
void tracktion::graph::AudioFifo::reset () noexcept
ensureFreeSpace()
void tracktion::graph::AudioFifo::ensureFreeSpace (int numFrames)
References getFreeSpace(), and getNumReady().
write()
bool tracktion::graph::AudioFifo::write (choc::buffer::ChannelArrayView< float > block)
Referenced by tracktion::graph::LatencyProcessor::writeAudio().
writeSilence()
bool tracktion::graph::AudioFifo::writeSilence (choc::buffer::FrameCount numFrames)
Referenced by tracktion::graph::LatencyProcessor::prepareToPlay().
readAdding()
bool tracktion::graph::AudioFifo::readAdding (choc::buffer::ChannelArrayView< float > dest)
Referenced by tracktion::graph::LatencyProcessor::readAudioAdding().
readOverwriting()
bool tracktion::graph::AudioFifo::readOverwriting (choc::buffer::ChannelArrayView< float > dest)
References tracktion::engine::AppFunctions::copy().
Referenced by tracktion::graph::LatencyProcessor::readAudioOverwriting().
removeSamples()
void tracktion::graph::AudioFifo::removeSamples (int numSamples)
Referenced by tracktion::graph::LatencyProcessor::clearAudio().
The documentation for this class was generated from the following file:
tracktion_graph/utilities/tracktion_AudioFifo.h