TracktionEngine: tracktion_engine::AudioTrack Class Reference
tracktion_engine::AudioTrack Class Reference
Classes
struct FreezePointRemovalInhibitor
Prevents the freeze point from being removed during an unfreeze operation.
struct Listener
Listener interface to be notified of recorded MIDI being sent to the plugins.
Public Types
using Ptr = juce::ReferenceCountedObjectPtr< AudioTrack >
Public Types inherited from tracktion_engine::Track
enum FreezeType { groupFreeze = 0, individualFreeze, anyFreeze }
Determines the type of freeze.
enum MuteAndSoloLightState {
soloLit = 1, soloFlashing = 2, soloIsolate = 4, muteLit = 8,
muteFlashing = 16
}
Determines the status of the mute and solo indicators.
using Ptr = juce::ReferenceCountedObjectPtr< Track >
using Array = juce::ReferenceCountedArray< Track >
Public Types inherited from tracktion_engine::Selectable
using WeakRef = juce::WeakReference< Selectable >
Public Member Functions
AudioTrack (Edit &, const juce::ValueTree &)
~AudioTrack () override
void initialise () override
Initialises the Track.
bool isAudioTrack () const override
Returns true if this is an AudioTrack.
juce::String getSelectableDescription () override
Subclasses must return a description of what they are.
int getAudioTrackNumber () noexcept
void sanityCheckName () override
checks whether the name is 'track n' and if so, makes sure the number is right
juce::String getName () override
bool canContainPlugin (Plugin *) const override
Returns true if this track can contain a specific Plugin.
bool processAudioNodesWhileMuted () const override
Subclasses can override this to ensure track contents are still played even when the track is muted.
juce::String getTrackPlayabilityWarning () const
returns a warning message about this track not being playable, or "" if it's ok
VolumeAndPanPlugin * getVolumePlugin ()
LevelMeterPlugin * getLevelMeterPlugin ()
EqualiserPlugin * getEqualiserPlugin ()
AuxSendPlugin * getAuxSendPlugin (int bus=-1) const
juce::String getNameForMidiNoteNumber (int note, int midiChannel, bool preferSharp=true) const
looks for a name for a midi note by trying all the plugins, and returning a default on failure.
juce::String getNameForProgramNumber (int programNumber, int bank) const
prog number is 0 based.
juce::String getNameForBank (int bank) const
int getIdForBank (int bank) const
bool areMidiPatchesZeroBased () const
WaveInputDevice & getWaveInputDevice () const noexcept
MidiInputDevice & getMidiInputDevice () const noexcept
TrackOutput & getOutput () const noexcept
int getMaxNumOfInputs () const noexcept
void setMaxNumOfInputs (int newMaxNumber)
bool canPlayAudio () const
checks whether audio clips can be played - i.e.
bool canPlayMidi () const
bool isFrozen (FreezeType) const override
Returns true if this track is frozen using the given type.
void setFrozen (bool, FreezeType) override
Attempts to freeze or unfreeze the track using a given FreezeType.
void insertFreezePointAfterPlugin (const Plugin::Ptr &)
void removeFreezePoint ()
void freezeTrackAsync () const
bool hasAnyLiveInputs ()
bool hasAnyTracksFeedingIn ()
juce::Array< Track * > getInputTracks () const override
Should return any tracks which feed into this track.
juce::Array< Track * > findSidechainSourceTracks () const
void injectLiveMidiMessage (const MidiMessageArray::MidiMessageWithSource &)
void injectLiveMidiMessage (const juce::MidiMessage &, MidiMessageArray::MPESourceID)
bool isMuted (bool includeMutingByDestination) const override
Returns true if this track is muted.
bool isSolo (bool includeIndirectSolo) const override
Returns true if this track is soloed.
bool isSoloIsolate (bool includeIndirectSolo) const override
Returns true if this track is solo isolated.
void setMute (bool) override
Subclasses should implement this to mute themselves.
void setSolo (bool) override
Subclasses should implement this to solo themselves.
void setSoloIsolate (bool) override
Subclasses should implement this to solo isolate themselves.
double getMidiVisibleProportion () const
vertical scales for displaying the midi note editor
double getMidiVerticalOffset () const
void setMidiVerticalPos (double visibleProp, double offset)
void scaleVerticallyToFitMidi ()
void setVerticalScaleToDefault ()
void setTrackToGhost (AudioTrack *, bool shouldGhost)
void clearGhostTracks ()
juce::Array< AudioTrack * > getGhostTracks () const
int getCompGroup () const noexcept
void setCompGroup (int groupIndex)
bool hasMidiNoteNames ()
void clearMidiNoteNames ()
void loadMidiNoteNames (const juce::String namesFile)
bool mergeInMidiSequence (const juce::MidiMessageSequence &, double startTime, MidiClip *, MidiList::NoteAutomationType)
try to add this MIDI sequence to any MIDI clips that are already in the track.
void playGuideNote (int note, MidiChannel midiChannel, int velocity, bool stopOtherFirst=true, bool forceNote=false, bool autorelease=false)
void playGuideNotes (const juce::Array< int > &notes, MidiChannel midiChannel, const juce::Array< int > &velocities, bool stopOthersFirst=true)
void turnOffGuideNotes ()
void turnOffGuideNotes (MidiChannel)
void addListener (Listener *)
Adds a Listener.
void removeListener (Listener *)
Removes a Listener.
juce::ListenerList< Listener > & getListeners ()
Returns the listener list so Nodes can manually call them.
Public Member Functions inherited from tracktion_engine::ClipTrack
ClipTrack (Edit &, const juce::ValueTree &, double defaultHeight, double minHeight, double maxHeight)
~ClipTrack () override
void flushStateToValueTree () override
Flushes all plugin states on the track to the state object.
const juce::Array< Clip * > & getClips () const noexcept
Clip * findClipForID (EditItemID) const override
Returns a clip one with a matching ID can be found on this Track.
void refreshCollectionClips (Clip &newClip)
CollectionClip * getCollectionClip (int index) const noexcept
CollectionClip * getCollectionClip (Clip *) const
int getNumCollectionClips () const noexcept
int indexOfCollectionClip (CollectionClip *) const
int getIndexOfNextCollectionClipAt (double time)
CollectionClip * getNextCollectionClipAt (double time)
bool contains (CollectionClip *) const
void addCollectionClip (CollectionClip *)
void removeCollectionClip (CollectionClip *)
int getNumTrackItems () const override
Should return the number of TrackItem[s] on this Track.
TrackItem * getTrackItem (int idx) const override
Should return the TrackItem at the given index.
int indexOfTrackItem (TrackItem *) const override
Should return the index of the given TrackItem.
int getIndexOfNextTrackItemAt (double time) override
Should return the index of the TrackItem after this time.
TrackItem * getNextTrackItemAt (double time) override
Should return the TrackItem after this time.
void insertSpaceIntoTrack (double time, double amountOfSpace) override
inserts space and moves everything up
double getLength () const
double getLengthIncludingInputTracks () const
EditTimeRange getTotalRange () const
void addClip (const Clip::Ptr &clip)
Clip * insertClipWithState (juce::ValueTree)
Clip * insertClipWithState (const juce::ValueTree &stateToUse, const juce::String &name, TrackItem::Type type, ClipPosition position, bool deleteExistingClips, bool allowSpottingAdjustment)
Clip * insertNewClip (TrackItem::Type, EditTimeRange position, SelectionManager *selectionManagerToSelectWith)
Clip * insertNewClip (TrackItem::Type, const juce::String &name, EditTimeRange position, SelectionManager *selectionManagerToSelectWith)
Clip * insertNewClip (TrackItem::Type, const juce::String &name, ClipPosition position, SelectionManager *selectionManagerToSelectWith)
juce::ReferenceCountedObjectPtr< WaveAudioClip > insertWaveClip (const juce::String &name, const juce::File &sourceFile, ClipPosition position, bool deleteExistingClips)
juce::ReferenceCountedObjectPtr< WaveAudioClip > insertWaveClip (const juce::String &name, ProjectItemID sourceID, ClipPosition position, bool deleteExistingClips)
juce::ReferenceCountedObjectPtr< MidiClip > insertMIDIClip (EditTimeRange position, SelectionManager *selectionManagerToSelectWith)
juce::ReferenceCountedObjectPtr< MidiClip > insertMIDIClip (const juce::String &name, EditTimeRange position, SelectionManager *selectionManagerToSelectWith)
juce::ReferenceCountedObjectPtr< EditClip > insertEditClip (EditTimeRange position, ProjectItemID sourceID)
void deleteRegion (EditTimeRange range, SelectionManager *)
void deleteRegionOfClip (Clip::Ptr, EditTimeRange range, SelectionManager *)
Clip * splitClip (Clip &, double time)
breaks a clip into 2 bits
void splitAt (double time)
split all clips at this time
double getNextTimeOfInterest (double afterThisTime)
finds the next cut point
double getPreviousTimeOfInterest (double beforeThisTime)
bool containsPlugin (const Plugin *) const override
Tests whether this Track or a clip on it contains the given plugin.
Plugin::Array getAllPlugins () const override
Returns all pugins on this Track.
void sendMirrorUpdateToAllPlugins (Plugin &) const override
Sends a message to all plugins that the given plugin has changed.
bool areAnyClipsUsingFile (const AudioFile &)
bool containsAnyMIDIClips () const
Public Member Functions inherited from tracktion_engine::Track
Track (Edit &, const juce::ValueTree &, double defaultTrackHeight, double minTrackHeight, double maxTrackHeight)
Creates a track with a given state.
~Track () override
Destructor.
void refreshCurrentAutoParam ()
Updates the current parameter bases on the set IDs.
juce::String getName () override
Returns the name of the Track.
void setName (const juce::String &)
Sets the name of the Track.
void resetName ()
Sets the name of the Track to an empty string.
virtual bool isAutomationTrack () const
Returns true if this is an AutomationTrack.
virtual bool isFolderTrack () const
Returns true if this is a FolderTrack.
virtual bool isMarkerTrack () const
Returns true if this is a MarkerTrack.
virtual bool isTempoTrack () const
Returns true if this is a TempoTrack.
virtual bool isChordTrack () const
Returns true if this is a ChordTrack.
virtual bool isArrangerTrack () const
Returns true if this is an ArrangerTrack.
virtual bool isMasterTrack () const
Returns true if this is a MasterTrack.
bool canContainMarkers () const
Returns true if this Track can contain MarkerClip[s].
bool canContainMIDI () const
Returns true if this Track can contain MidiClip[s].
bool canContainAudio () const
Returns true if this Track can contain WaveAudioClip[s].
bool canContainEditClips () const
Returns true if this Track can contain EditClip[s].
bool canContainPlugins () const
Returns true if this Track can contain Plugin[s].
bool isMovable () const
Returns true if this Track is movable.
bool isOnTop () const
Returns true if this a global Track and should be on top of others.
bool acceptsInput () const
Returns true if this track can have inputs assigned to it.
bool createsOutput () const
Returns true if this track creates audible output.
bool wantsAutomation () const
Returns true if this track can show automation.
bool isHidden () const
Returns true if this track should be hidden from view.
void setHidden (bool h)
Sets whether this track should be hidden from view.
bool isProcessing (bool includeParents) const
Returns true if this track should be included in playback.
void setProcessing (bool p)
Sets whether this track should be included in playback.
juce::Array< Track * > getAllSubTracks (bool recursive) const
Returns all nested tracks.
juce::Array< AudioTrack * > getAllAudioSubTracks (bool recursive) const
Returns all nested AudioTrack[s].
TrackList * getSubTrackList () const
Returns the TrackList if this Track has any sub-tracks.
bool hasSubTracks () const
Returns true if this track has any subtracks.
Track * getSiblingTrack (int delta, bool keepWithinSameParent) const
Returns a sibling Track to this one.
juce::ValueTree getParentTrackTree () const
Returns the state of the parent Track.
Track * getParentTrack () const
Returns the parent Track if this is a nested track.
FolderTrack * getParentFolderTrack () const
Returns the parent FolderTrack if this is nested in one.
bool isAChildOf (const Track &possibleParent) const
Tests whether this is a child of a given Track.
bool isPartOfSubmix () const
Tests whether this nested within a submix FolderTrack.
int getIndexInEditTrackList () const
Returns the index of this track in a flat list of tracks contained in an Edit.
int getTrackDepth () const
Returns the number of parents within which this track is nested.
MuteAndSoloLightState getMuteAndSoloLightState () const
Returns the mute a solo status.
bool shouldBePlayed () const noexcept
Tests whether this track should be audible in the playback graph i.e.
void updateAudibility (bool areAnyTracksSolo)
Updates the audibility state of the Track.
juce::Array< AutomatableParameter * > getAllAutomatableParams () const
Returns all the parameteres for this track's Plugin[s] and Modifier[s].
AutomatableParameter * getCurrentlyShownAutoParam () const noexcept
Returns the parameter whos curve should be shown on this Track.
void setCurrentlyShownAutoParam (const AutomatableParameter::Ptr &)
Sets a parameter to display on this Track.
void hideAutomatableParametersForSource (EditItemID pluginOrParameterID)
Hides a shown parameter if it matches the given ID.
bool hasFreezePointPlugin () const
Tests whether this Track contains a FreezePointPlugin.
juce::Array< AutomatableEditItem * > getAllAutomatableEditItems () const
Returns all AutomatableEditItem[s] on this Track.
void flipAllPluginsEnablement ()
Toggles the Plugin::isEnabled state for all Plugin[s] on this Track.
ModifierList & getModifierList () const
Returns the ModifierList for this Track.
void setColour (juce::Colour newColour)
Sets a colour for this track to use.
juce::Colour getColour () const
Returns the the of this.
bool canShowImage () const
Tests whether this Track can show an image.
void setTrackImage (const juce::String &idOrData)
Sets some image data to use.
juce::String getTrackImage () const
Returns previously set image data.
bool imageHasChanged ()
Tests and resets a flag internally kept when the image changes.
void setTags (const juce::StringArray &)
Sets an array of Strings to use as tags.
juce::String getTags () const
Returns the tags as a pipe-separated single String.
const juce::StringArray & getTagsArray () const noexcept
Returns the array of tags.
Public Member Functions inherited from tracktion_engine::EditItem
EditItem (EditItemID, Edit &)
virtual ~EditItem ()=default
Public Member Functions inherited from tracktion_engine::Selectable
Selectable ()
virtual ~Selectable ()
virtual void selectionStatusChanged (bool isNowSelected)
Can be overridden to tell this object that it has just been selected or deselected.
virtual void changed ()
This should be called to send a change notification to any SelectableListeners that are registered with this object.
virtual void selectableAboutToBeDeleted ()
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void addSelectableListener (SelectableListener *)
void removeSelectableListener (SelectableListener *)
void cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
void deselect ()
void propertiesChanged ()
void notifyListenersOfDeletion ()
WeakRef getWeakRef ()
Public Member Functions inherited from tracktion_engine::MacroParameterElement
MacroParameterElement (Edit &, const juce::ValueTree &)
Constructor.
virtual ~MacroParameterElement ()=default
Destructor.
int getNumMacroParameters () const
Returns the number of macro parameters for this object.
Protected Member Functions
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
bool isTrackAudible (bool areAnyTracksSolo) const override
Returns whether this Track should be audible.
void timerCallback () override
Protected Member Functions inherited from tracktion_engine::ClipTrack
juce::Array< double > findAllTimesOfInterest ()
void refreshTrackItems () const
Protected Member Functions inherited from tracktion_engine::Track
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeChildAdded (juce::ValueTree &, juce::ValueTree &) override
void valueTreeChildRemoved (juce::ValueTree &, juce::ValueTree &, int) override
void valueTreeChildOrderChanged (juce::ValueTree &, int, int) override
void valueTreeParentChanged (juce::ValueTree &) override
Additional Inherited Members
Static Public Member Functions inherited from tracktion_engine::Selectable
static void initialise ()
static bool isSelectableValid (const Selectable *) noexcept
checks whether this object has been deleted.
Public Attributes inherited from tracktion_engine::Track
const double defaultTrackHeight
The default height of this Track.
const double minTrackHeight
The minimum height of this Track.
const double maxTrackHeight
The maximum height of this Track.
juce::ValueTree state
The state of this Track.
PluginList pluginList
The Track's PluginList.
Public Attributes inherited from tracktion_engine::EditItem
Edit & edit
const EditItemID itemID
Every EditItem has an ID which is unique within the edit.
Public Attributes inherited from tracktion_engine::Selectable
WeakRef::Master masterReference
Public Attributes inherited from tracktion_engine::MacroParameterElement
MacroParameterList macroParameterList
Static Public Attributes inherited from tracktion_engine::Track
static const int minTrackHeightForDetail = 10
The minimim height to show track contents at.
static const int trackHeightForEditor = 180
The height at which inline editors should be shown.
static const int frozenTrackHeight = 15
The height to show group frozen tracks.
Protected Attributes inherited from tracktion_engine::ClipTrack
std::unique_ptr< ClipList > clipList
std::unique_ptr< CollectionClipList > collectionClipList
bool trackItemsDirty = false
juce::Array< TrackItem * > trackItems
Member Typedef Documentation
Ptr
using tracktion_engine::AudioTrack::Ptr = juce::ReferenceCountedObjectPtr<AudioTrack>
Constructor & Destructor Documentation
AudioTrack()
tracktion_engine::AudioTrack::AudioTrack (Edit & , const juce::ValueTree &)
~AudioTrack()
tracktion_engine::AudioTrack::~AudioTrack () override
Member Function Documentation
initialise()
void tracktion_engine::AudioTrack::initialise () override virtual
Initialises the Track.
You shouldn't need to call this directly, it will be called by the track creation methods.
See also
Edit::insertTrack
Reimplemented from tracktion_engine::Track.
isAudioTrack()
bool tracktion_engine::AudioTrack::isAudioTrack () const override virtual
Returns true if this is an AudioTrack.
Reimplemented from tracktion_engine::Track.
getSelectableDescription()
juce::String tracktion_engine::AudioTrack::getSelectableDescription () override virtual
Subclasses must return a description of what they are.
Implements tracktion_engine::Selectable.
References getName().
getAudioTrackNumber()
int tracktion_engine::AudioTrack::getAudioTrackNumber () noexcept
sanityCheckName()
void tracktion_engine::AudioTrack::sanityCheckName () override virtual
checks whether the name is 'track n' and if so, makes sure the number is right
Reimplemented from tracktion_engine::Track.
getName()
juce::String tracktion_engine::AudioTrack::getName () override virtual
Implements tracktion_engine::EditItem.
Referenced by getSelectableDescription().
canContainPlugin()
bool tracktion_engine::AudioTrack::canContainPlugin (Plugin *) const override virtual
Returns true if this track can contain a specific Plugin.
Subclasses can override this to avoid specific plugins such as VCAPlugin[s] on AudioTrack[s].
Implements tracktion_engine::Track.
processAudioNodesWhileMuted()
bool tracktion_engine::AudioTrack::processAudioNodesWhileMuted () const override virtual
Subclasses can override this to ensure track contents are still played even when the track is muted.
This may be required if this track is a sidechain source or feeding an aux for example.
Reimplemented from tracktion_engine::Track.
References tracktion_engine::EditItem::edit, tracktion_engine::Edit::engine, tracktion_engine::Engine::getEngineBehaviour(), and tracktion_engine::EngineBehaviour::shouldProcessMutedTracks().
getTrackPlayabilityWarning()
juce::String tracktion_engine::AudioTrack::getTrackPlayabilityWarning () const
returns a warning message about this track not being playable, or "" if it's ok
getVolumePlugin()
VolumeAndPanPlugin* tracktion_engine::AudioTrack::getVolumePlugin ()
getLevelMeterPlugin()
LevelMeterPlugin* tracktion_engine::AudioTrack::getLevelMeterPlugin ()
getEqualiserPlugin()
EqualiserPlugin* tracktion_engine::AudioTrack::getEqualiserPlugin ()
getAuxSendPlugin()
AuxSendPlugin* tracktion_engine::AudioTrack::getAuxSendPlugin (int bus = -1) const
getNameForMidiNoteNumber()
juce::String tracktion_engine::AudioTrack::getNameForMidiNoteNumber (int note, int midiChannel, bool preferSharp = true) const
looks for a name for a midi note by trying all the plugins, and returning a default on failure.
midiChannel is 1-16
getNameForProgramNumber()
juce::String tracktion_engine::AudioTrack::getNameForProgramNumber (int programNumber, int bank) const
prog number is 0 based.
getNameForBank()
juce::String tracktion_engine::AudioTrack::getNameForBank (int bank) const
getIdForBank()
int tracktion_engine::AudioTrack::getIdForBank (int bank) const
areMidiPatchesZeroBased()
bool tracktion_engine::AudioTrack::areMidiPatchesZeroBased () const
getWaveInputDevice()
WaveInputDevice& tracktion_engine::AudioTrack::getWaveInputDevice () const noexcept
getMidiInputDevice()
MidiInputDevice& tracktion_engine::AudioTrack::getMidiInputDevice () const noexcept
getOutput()
TrackOutput& tracktion_engine::AudioTrack::getOutput () const noexcept
getMaxNumOfInputs()
int tracktion_engine::AudioTrack::getMaxNumOfInputs () const noexcept
setMaxNumOfInputs()
void tracktion_engine::AudioTrack::setMaxNumOfInputs (int newMaxNumber)
canPlayAudio()
bool tracktion_engine::AudioTrack::canPlayAudio () const
checks whether audio clips can be played - i.e.
can they make it past the plugins, and is the track going to an audio output
canPlayMidi()
bool tracktion_engine::AudioTrack::canPlayMidi () const
isFrozen()
bool tracktion_engine::AudioTrack::isFrozen (FreezeType) const override virtual
Returns true if this track is frozen using the given type.
Reimplemented from tracktion_engine::Track.
setFrozen()
void tracktion_engine::AudioTrack::setFrozen (bool , FreezeType) override virtual
Attempts to freeze or unfreeze the track using a given FreezeType.
Reimplemented from tracktion_engine::Track.
insertFreezePointAfterPlugin()
void tracktion_engine::AudioTrack::insertFreezePointAfterPlugin (const Plugin::Ptr &)
removeFreezePoint()
void tracktion_engine::AudioTrack::removeFreezePoint ()
freezeTrackAsync()
void tracktion_engine::AudioTrack::freezeTrackAsync () const
hasAnyLiveInputs()
bool tracktion_engine::AudioTrack::hasAnyLiveInputs ()
hasAnyTracksFeedingIn()
bool tracktion_engine::AudioTrack::hasAnyTracksFeedingIn ()
getInputTracks()
juce::Array<Track*> tracktion_engine::AudioTrack::getInputTracks () const override virtual
Should return any tracks which feed into this track.
Reimplemented from tracktion_engine::Track.
findSidechainSourceTracks()
juce::Array<Track*> tracktion_engine::AudioTrack::findSidechainSourceTracks () const
injectLiveMidiMessage() [1/2]
void tracktion_engine::AudioTrack::injectLiveMidiMessage (const MidiMessageArray::MidiMessageWithSource &)
injectLiveMidiMessage() [2/2]
void tracktion_engine::AudioTrack::injectLiveMidiMessage (const juce::MidiMessage & , MidiMessageArray::MPESourceID)
isMuted()
bool tracktion_engine::AudioTrack::isMuted (bool) const override virtual
Returns true if this track is muted.
Parameters
includeMutingByDestination If this is true, this will retrn true if any tracks this feeds in to are muted.
Reimplemented from tracktion_engine::Track.
isSolo()
bool tracktion_engine::AudioTrack::isSolo (bool) const override virtual
Returns true if this track is soloed.
Parameters
includeIndirectSolo If this is true, this will retrn true if any tracks this feeds in to are soloed.
Reimplemented from tracktion_engine::Track.
isSoloIsolate()
bool tracktion_engine::AudioTrack::isSoloIsolate (bool) const override virtual
Returns true if this track is solo isolated.
Parameters
includeIndirectSolo If this is true, this will retrn true if any tracks this feeds in to are solo isolated.
Reimplemented from tracktion_engine::Track.
setMute()
void tracktion_engine::AudioTrack::setMute (bool) override virtual
Subclasses should implement this to mute themselves.
Reimplemented from tracktion_engine::Track.
setSolo()
void tracktion_engine::AudioTrack::setSolo (bool) override virtual
Subclasses should implement this to solo themselves.
Reimplemented from tracktion_engine::Track.
setSoloIsolate()
void tracktion_engine::AudioTrack::setSoloIsolate (bool) override virtual
Subclasses should implement this to solo isolate themselves.
Reimplemented from tracktion_engine::Track.
getMidiVisibleProportion()
double tracktion_engine::AudioTrack::getMidiVisibleProportion () const
vertical scales for displaying the midi note editor
getMidiVerticalOffset()
double tracktion_engine::AudioTrack::getMidiVerticalOffset () const
setMidiVerticalPos()
void tracktion_engine::AudioTrack::setMidiVerticalPos (double visibleProp, double offset)
scaleVerticallyToFitMidi()
void tracktion_engine::AudioTrack::scaleVerticallyToFitMidi ()
setVerticalScaleToDefault()
void tracktion_engine::AudioTrack::setVerticalScaleToDefault ()
setTrackToGhost()
void tracktion_engine::AudioTrack::setTrackToGhost (AudioTrack * , bool shouldGhost)
clearGhostTracks()
void tracktion_engine::AudioTrack::clearGhostTracks ()
getGhostTracks()
juce::Array<AudioTrack*> tracktion_engine::AudioTrack::getGhostTracks () const
getCompGroup()
int tracktion_engine::AudioTrack::getCompGroup () const noexcept
setCompGroup()
void tracktion_engine::AudioTrack::setCompGroup (int groupIndex)
hasMidiNoteNames()
bool tracktion_engine::AudioTrack::hasMidiNoteNames ()
clearMidiNoteNames()
void tracktion_engine::AudioTrack::clearMidiNoteNames ()
loadMidiNoteNames()
void tracktion_engine::AudioTrack::loadMidiNoteNames (const juce::String namesFile)
mergeInMidiSequence()
bool tracktion_engine::AudioTrack::mergeInMidiSequence (const juce::MidiMessageSequence & , double startTime, MidiClip * , MidiList::NoteAutomationType)
try to add this MIDI sequence to any MIDI clips that are already in the track.
Returns
False if there's no existing clips in the places it needs them.
playGuideNote()
void tracktion_engine::AudioTrack::playGuideNote (int note, MidiChannel midiChannel, int velocity, bool stopOtherFirst = true, bool forceNote = false, bool autorelease = false)
playGuideNotes()
void tracktion_engine::AudioTrack::playGuideNotes (const juce::Array< int > & notes, MidiChannel midiChannel, const juce::Array< int > & velocities, bool stopOthersFirst = true)
turnOffGuideNotes() [1/2]
void tracktion_engine::AudioTrack::turnOffGuideNotes ()
Referenced by timerCallback().
turnOffGuideNotes() [2/2]
void tracktion_engine::AudioTrack::turnOffGuideNotes (MidiChannel)
addListener()
void tracktion_engine::AudioTrack::addListener (Listener *)
Adds a Listener.
This will automatically call Edit::restartPlayback for the callbacks to take effect.
removeListener()
void tracktion_engine::AudioTrack::removeListener (Listener *)
Removes a Listener.
getListeners()
juce::ListenerList<Listener>& tracktion_engine::AudioTrack::getListeners ()
Returns the listener list so Nodes can manually call them.
valueTreePropertyChanged()
void tracktion_engine::AudioTrack::valueTreePropertyChanged (juce::ValueTree & , const juce::Identifier &) override protected
isTrackAudible()
bool tracktion_engine::AudioTrack::isTrackAudible (bool areAnyTracksSolo) const override protected virtual
Returns whether this Track should be audible.
Subclasses can override for custom behaviour.
Reimplemented from tracktion_engine::Track.
timerCallback()
void tracktion_engine::AudioTrack::timerCallback () override protected
References turnOffGuideNotes().
The documentation for this class was generated from the following file:
tracktion_AudioTrack.h