TracktionEngine: tracktion::engine::ExternalAutomatableParameter Class Reference
tracktion::engine::ExternalAutomatableParameter Class Reference
Public Member Functions
ExternalAutomatableParameter (const juce::String &parameterID, const juce::String &name, ExternalPlugin &owner, int parameterIndex_, juce::Range< float > valueRangeToUse)
~ExternalAutomatableParameter () override
void registerAsListener ()
void unregisterAsListener ()
std::optional< float > getDefaultValue () const override
void parameterChanged (float newValue, bool byAutomation) override
void beginParameterChangeGesture () override
void endParameterChangeGesture () override
juce::String valueToString (float value) override
float stringToValue (const juce::String &str) override
juce::String getCurrentValueAsString () override
juce::String getLabel () override
void valueChangedByPlugin ()
juce::String getParameterName () const override
int getParameterIndex () const noexcept
juce::String getParameterShortName (int suggestedLength) const override
void setDisplayName (const juce::String &str)
bool isDiscrete () const override
int getNumberOfStates () const override
float getValueForState (int state) const override
juce::String getLabelForValue (float val) const override
juce::StringArray getAllLabels () const override
float snapToState (float val) const override
bool hasLabels () const override
int getStateForValue (float val) const override
Public Member Functions inherited from tracktion::engine::AutomatableParameter
AutomatableParameter (const juce::String &paramID, const juce::String &name, AutomatableEditItem &, juce::NormalisableRange< float > valueRange)
~AutomatableParameter () override
juce::Range< float > getValueRange () const
Plugin * getPlugin () const
Engine & getEngine () const noexcept
Edit & getEdit () const noexcept
Track * getTrack () const noexcept
AutomationCurve & getCurve () const noexcept
void attachToCurrentValue (juce::CachedValue< float > &)
void attachToCurrentValue (juce::CachedValue< int > &)
void attachToCurrentValue (juce::CachedValue< bool > &)
void updateFromAttachedValue ()
void detachFromCurrentValue ()
virtual juce::String getPluginAndParamName () const
virtual juce::String getFullName () const
Selectable * getOwnerSelectable () const
Returns the thing that you'd select if you wanted to show this param.
EditItemID getOwnerID () const
Returns the thing that you'd select if you wanted to show this param.
float getCurrentValue () const noexcept
float getCurrentNormalisedValue () const noexcept
juce::String getCurrentValueAsStringWithLabel ()
void setParameter (float value, juce::NotificationType)
void setNormalisedParameter (float value, juce::NotificationType)
void updateToFollowCurve (TimePosition)
void parameterChangeGestureBegin ()
Call to indicate this parameter is about to be changed.
void parameterChangeGestureEnd ()
Call to indicate this parameter has stopped being to be changed.
bool hasAutomationPoints () const noexcept
ModifierAssignment::Ptr addModifier (ModifierSource &, float value=1.0f, float offset=0.0f, float curve=0.5f)
Creates an assignment for a given source.
void removeModifier (ModifierAssignment &)
Removes an assignment.
void removeModifier (ModifierSource &)
Removes assignments for a ModifierSource.
bool hasActiveModifierAssignments () const
Returns true if any ModifierSources are currently in use by assignments.
juce::ReferenceCountedArray< ModifierAssignment > getAssignments () const
Returns all the current ModifierAssignments.
juce::Array< ModifierSource * > getModifiers () const
Returns all the current ModifierSources currently in use by assignments.
float getCurrentExplicitValue () const
This is the value that has been set explicity, either by calling setParameter or the plugin telling us one if its parameters has changed.
float getCurrentBaseValue () const
This is the current base value of the parameter i.e.
float getCurrentModifierValue () const
This is the ammount of the modifier that has been applied to the base value to give the current parameter value.
bool isAutomationActive () const
Returns true if the parameter is being dynamically changed somehow, either through automation or a ModifierAssignment.
void updateStream ()
Forces the parameter to update its automation stream for reading automation.
void updateFromAutomationSources (TimePosition)
Updates the parameter and modifier values from its current automation sources.
virtual bool isParameterActive () const
bool isCurrentlyRecording () const
true if the parameter been moved while in an automation record mode.
void resetRecordingStatus ()
this is called before and after playback or recording.
void midiControllerMoved (float newPosition)
void midiControllerPressed ()
void curveHasChanged ()
juce::String getSelectableDescription () override
Subclasses must return a description of what they are.
void addListener (Listener *l)
void removeListener (Listener *l)
Public Member Functions inherited from tracktion::engine::Selectable
Selectable ()
virtual ~Selectable ()
virtual void selectionStatusChanged (bool isNowSelected)
Can be overridden to tell this object that it has just been selected or deselected.
virtual void changed ()
This should be called to send a change notification to any SelectableListeners that are registered with this object.
virtual void selectableAboutToBeDeleted ()
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void addListener (SelectableListener *)
void removeListener (SelectableListener *)
void addSelectableListener (SelectableListener *)
void removeSelectableListener (SelectableListener *)
void cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
void deselect ()
void propertiesChanged ()
void notifyListenersOfDeletion ()
WeakRef getWeakRef ()
Additional Inherited Members
Public Types inherited from tracktion::engine::AutomatableParameter
using Ptr = juce::ReferenceCountedObjectPtr< AutomatableParameter >
using Array = juce::ReferenceCountedArray< AutomatableParameter >
Public Types inherited from tracktion::engine::Selectable
using WeakRef = juce::WeakReference< Selectable >
Static Public Member Functions inherited from tracktion::engine::Selectable
static void initialise ()
static bool isSelectableValid (const Selectable *) noexcept
checks whether this object has been deleted.
Public Attributes inherited from tracktion::engine::AutomatableParameter
const juce::String paramID
const juce::NormalisableRange< float > valueRange
AutomatableEditItem & automatableEditElement
std::function< juce::String(float)> valueToStringFunction
std::function< float(const juce::String &)> stringToValueFunction
const juce::String paramName
juce::ValueTree parentState
Public Attributes inherited from tracktion::engine::Selectable
WeakRef::Master masterReference
Protected Member Functions inherited from tracktion::engine::AutomatableParameter
AutomationSourceList & getAutomationSourceList () const
void setParameterValue (float value, bool isFollowingCurve)
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeChildAdded (juce::ValueTree &, juce::ValueTree &) override
void valueTreeChildRemoved (juce::ValueTree &, juce::ValueTree &, int) override
void valueTreeChildOrderChanged (juce::ValueTree &, int, int) override
void valueTreeParentChanged (juce::ValueTree &) override
void valueTreeRedirected (juce::ValueTree &) override
Protected Attributes inherited from tracktion::engine::AutomatableParameter
std::unique_ptr< AttachedValue > attachedValue
juce::ListenerList< Listener > listeners
SafeSelectable< Edit > editRef
Plugin * plugin = nullptr
Modifier * modifierOwner = nullptr
MacroParameterList * macroOwner = nullptr
std::unique_ptr< AutomationCurveSource > curveSource
std::atomic< float > currentValue { 0.0f }
std::atomic< float > currentParameterValue { 0.0f }
std::atomic< float > currentBaseValue { 0.0f }
std::atomic< float > currentModifierValue { 0.0f }
std::atomic< bool > isRecording { false }
bool updateParametersRecursionCheck = false
AsyncCaller parameterChangedCaller { [this] { listeners.call (&Listener::currentValueChanged, *this); } }
juce::ValueTree modifiersState
std::unique_ptr< AutomationSourceList > automationSourceList
Constructor & Destructor Documentation
ExternalAutomatableParameter()
tracktion::engine::ExternalAutomatableParameter::ExternalAutomatableParameter (const juce::String & parameterID, const juce::String & name, ExternalPlugin & owner, int parameterIndex_, juce::Range< float > valueRangeToUse)
References tracktion::engine::ExternalPlugin::getVSTXML(), tracktion::engine::VSTXML::Param::name, tracktion::engine::VSTXML::Base::parent, registerAsListener(), and tracktion::engine::VSTXML::Param::type.
~ExternalAutomatableParameter()
tracktion::engine::ExternalAutomatableParameter::~ExternalAutomatableParameter () override
References CRASH_TRACER, tracktion::engine::Selectable::notifyListenersOfDeletion(), and unregisterAsListener().
Member Function Documentation
registerAsListener()
void tracktion::engine::ExternalAutomatableParameter::registerAsListener ()
Referenced by ExternalAutomatableParameter().
unregisterAsListener()
void tracktion::engine::ExternalAutomatableParameter::unregisterAsListener ()
Referenced by ~ExternalAutomatableParameter().
getDefaultValue()
std::optional<float> tracktion::engine::ExternalAutomatableParameter::getDefaultValue () const override virtual
Reimplemented from tracktion::engine::AutomatableParameter.
parameterChanged()
void tracktion::engine::ExternalAutomatableParameter::parameterChanged (float newValue, bool byAutomation) override virtual
Reimplemented from tracktion::engine::AutomatableParameter.
beginParameterChangeGesture()
void tracktion::engine::ExternalAutomatableParameter::beginParameterChangeGesture () override virtual
Reimplemented from tracktion::engine::AutomatableParameter.
endParameterChangeGesture()
void tracktion::engine::ExternalAutomatableParameter::endParameterChangeGesture () override virtual
Reimplemented from tracktion::engine::AutomatableParameter.
valueToString()
juce::String tracktion::engine::ExternalAutomatableParameter::valueToString (float value) override virtual
Reimplemented from tracktion::engine::AutomatableParameter.
stringToValue()
float tracktion::engine::ExternalAutomatableParameter::stringToValue (const juce::String & str) override virtual
Reimplemented from tracktion::engine::AutomatableParameter.
References tracktion::engine::dbStringToDb().
getCurrentValueAsString()
juce::String tracktion::engine::ExternalAutomatableParameter::getCurrentValueAsString () override virtual
Reimplemented from tracktion::engine::AutomatableParameter.
getLabel()
juce::String tracktion::engine::ExternalAutomatableParameter::getLabel () override virtual
Reimplemented from tracktion::engine::AutomatableParameter.
valueChangedByPlugin()
void tracktion::engine::ExternalAutomatableParameter::valueChangedByPlugin ()
References tracktion::engine::AutomatableParameter::setParameter().
getParameterName()
juce::String tracktion::engine::ExternalAutomatableParameter::getParameterName () const override virtual
Reimplemented from tracktion::engine::AutomatableParameter.
getParameterIndex()
int tracktion::engine::ExternalAutomatableParameter::getParameterIndex () const noexcept
getParameterShortName()
juce::String tracktion::engine::ExternalAutomatableParameter::getParameterShortName (int suggestedLength) const override virtual
Reimplemented from tracktion::engine::AutomatableParameter.
setDisplayName()
void tracktion::engine::ExternalAutomatableParameter::setDisplayName (const juce::String & str)
isDiscrete()
bool tracktion::engine::ExternalAutomatableParameter::isDiscrete () const override virtual
Reimplemented from tracktion::engine::AutomatableParameter.
References tracktion::engine::VSTXML::Param::numberOfStates, and tracktion::engine::VSTXML::Param::type.
Referenced by getNumberOfStates(), getStateForValue(), and snapToState().
getNumberOfStates()
int tracktion::engine::ExternalAutomatableParameter::getNumberOfStates () const override virtual
Reimplemented from tracktion::engine::AutomatableParameter.
References isDiscrete(), and tracktion::engine::VSTXML::Param::numberOfStates.
Referenced by getStateForValue(), getValueForState(), and snapToState().
getValueForState()
float tracktion::engine::ExternalAutomatableParameter::getValueForState (int state) const override virtual
Reimplemented from tracktion::engine::AutomatableParameter.
References tracktion::engine::VSTXML::ValueType::entries, and getNumberOfStates().
Referenced by snapToState().
getLabelForValue()
juce::String tracktion::engine::ExternalAutomatableParameter::getLabelForValue (float val) const override virtual
Reimplemented from tracktion::engine::AutomatableParameter.
References tracktion::engine::VSTXML::ValueType::entries, and tracktion::engine::VSTXML::Param::type.
getAllLabels()
juce::StringArray tracktion::engine::ExternalAutomatableParameter::getAllLabels () const override virtual
Reimplemented from tracktion::engine::AutomatableParameter.
References tracktion::engine::VSTXML::ValueType::entries, and tracktion::engine::VSTXML::Param::type.
snapToState()
float tracktion::engine::ExternalAutomatableParameter::snapToState (float val) const override virtual
Reimplemented from tracktion::engine::AutomatableParameter.
References tracktion::engine::VSTXML::ValueType::entries, getNumberOfStates(), getValueForState(), and isDiscrete().
hasLabels()
bool tracktion::engine::ExternalAutomatableParameter::hasLabels () const override virtual
Reimplemented from tracktion::engine::AutomatableParameter.
References tracktion::engine::VSTXML::ValueType::entries, and tracktion::engine::VSTXML::Param::type.
getStateForValue()
int tracktion::engine::ExternalAutomatableParameter::getStateForValue (float val) const override virtual
Reimplemented from tracktion::engine::AutomatableParameter.
References tracktion::engine::VSTXML::ValueType::entries, getNumberOfStates(), and isDiscrete().
The documentation for this class was generated from the following file:
tracktion_ExternalAutomatableParameter.h