TracktionEngine: tracktion::engine::AudioSegmentList Class Reference
tracktion::engine::AudioSegmentList Class Reference
tracktion_engine » model
Holds a list of audio regions for playback of things like warp time.
#include <tracktion_AudioSegmentList.h>
Classes
struct Segment
Public Member Functions
const juce::Array< Segment > & getSegments () const
TimePosition getStart () const
TimePosition getEnd () const
TimeDuration getLength () const
TimeDuration getCrossfadeLength () const
bool operator== (const AudioSegmentList &) const noexcept
bool operator!= (const AudioSegmentList &) const noexcept
Static Public Member Functions
static std::unique_ptr< AudioSegmentList > create (AudioClipBase &)
static std::unique_ptr< AudioSegmentList > create (AudioClipBase &, bool relativeTime, bool crossFade)
static std::unique_ptr< AudioSegmentList > create (AudioClipBase &, const WarpTimeManager &, const AudioFile &)
static std::unique_ptr< AudioSegmentList > create (AudioClipBase &, const WarpTimeManager &, const AudioFileInfo &, const LoopInfo &)
Detailed Description
Holds a list of audio regions for playback of things like warp time.
Member Function Documentation
create() [1/4]
static std::unique_ptr< AudioSegmentList > tracktion::engine::AudioSegmentList::create (AudioClipBase &) static
create() [2/4]
static std::unique_ptr< AudioSegmentList > tracktion::engine::AudioSegmentList::create (AudioClipBase & , bool relativeTime, bool crossFade) static
create() [3/4]
static std::unique_ptr< AudioSegmentList > tracktion::engine::AudioSegmentList::create (AudioClipBase & , const WarpTimeManager & , const AudioFile &) static
create() [4/4]
static std::unique_ptr< AudioSegmentList > tracktion::engine::AudioSegmentList::create (AudioClipBase & , const WarpTimeManager & , const AudioFileInfo & , const LoopInfo &) static
getSegments()
const juce::Array< Segment > & tracktion::engine::AudioSegmentList::getSegments () const
getStart()
TimePosition tracktion::engine::AudioSegmentList::getStart () const
Referenced by getLength().
getEnd()
TimePosition tracktion::engine::AudioSegmentList::getEnd () const
Referenced by getLength().
getLength()
TimeDuration tracktion::engine::AudioSegmentList::getLength () const
References getEnd(), and getStart().
getCrossfadeLength()
TimeDuration tracktion::engine::AudioSegmentList::getCrossfadeLength () const
operator==()
bool tracktion::engine::AudioSegmentList::operator== (const AudioSegmentList &) const noexcept
operator!=()
bool tracktion::engine::AudioSegmentList::operator!= (const AudioSegmentList &) const noexcept
The documentation for this class was generated from the following file:
tracktion_AudioSegmentList.h