TracktionEngine: tracktion_engine::TracktionNodePlayer Class Reference
tracktion_engine::TracktionNodePlayer Class Reference
Plays back a Node with PlayHeadState and ProcessState.
Public Member Functions
TracktionNodePlayer (ProcessState &processStateToUse, tracktion_graph::LockFreeMultiThreadedNodePlayer::ThreadPoolCreator poolCreator)
Creates an NodePlayer to process a Node.
TracktionNodePlayer (std::unique_ptr< tracktion_graph::Node > node, ProcessState &processStateToUse, double sampleRate, int blockSize, tracktion_graph::LockFreeMultiThreadedNodePlayer::ThreadPoolCreator poolCreator)
Creates an NodePlayer to process a Node.
void setNumThreads (size_t numThreads)
Sets the number of threads to use for rendering.
tracktion_graph::Node * getNode ()
void setNode (std::unique_ptr< tracktion_graph::Node > newNode)
void setNode (std::unique_ptr< tracktion_graph::Node > newNode, double sampleRateToUse, int blockSizeToUse)
void prepareToPlay (double sampleRateToUse, int blockSizeToUse)
int process (const tracktion_graph::Node::ProcessContext &pc)
Processes a block of audio and MIDI data.
void clearNode ()
Clears the Node currently playing.
double getSampleRate () const
Returns the current sample rate.
void enablePooledMemoryAllocations (bool enablePooledMemory)
Detailed Description
Plays back a Node with PlayHeadState and ProcessState.
Constructor & Destructor Documentation
TracktionNodePlayer() [1/2]
tracktion_engine::TracktionNodePlayer::TracktionNodePlayer (ProcessState & processStateToUse, tracktion_graph::LockFreeMultiThreadedNodePlayer::ThreadPoolCreator poolCreator)
Creates an NodePlayer to process a Node.
TracktionNodePlayer() [2/2]
tracktion_engine::TracktionNodePlayer::TracktionNodePlayer (std::unique_ptr< tracktion_graph::Node > node, ProcessState & processStateToUse, double sampleRate, int blockSize, tracktion_graph::LockFreeMultiThreadedNodePlayer::ThreadPoolCreator poolCreator)
Creates an NodePlayer to process a Node.
References tracktion_graph::LockFreeMultiThreadedNodePlayer::setNode().
Member Function Documentation
setNumThreads()
void tracktion_engine::TracktionNodePlayer::setNumThreads (size_t numThreads)
Sets the number of threads to use for rendering.
This can be 0 in which case only the process calling thread will be used for processing. N.B. this will pause processing whilst updating the threads so there will be a gap in the audio.
References tracktion_graph::LockFreeMultiThreadedNodePlayer::setNumThreads().
getNode()
tracktion_graph::Node* tracktion_engine::TracktionNodePlayer::getNode ()
References tracktion_graph::LockFreeMultiThreadedNodePlayer::getNode().
setNode() [1/2]
void tracktion_engine::TracktionNodePlayer::setNode (std::unique_ptr< tracktion_graph::Node > newNode)
References tracktion_graph::LockFreeMultiThreadedNodePlayer::setNode().
setNode() [2/2]
void tracktion_engine::TracktionNodePlayer::setNode (std::unique_ptr< tracktion_graph::Node > newNode, double sampleRateToUse, int blockSizeToUse)
References tracktion_graph::LockFreeMultiThreadedNodePlayer::setNode().
prepareToPlay()
void tracktion_engine::TracktionNodePlayer::prepareToPlay (double sampleRateToUse, int blockSizeToUse)
References tracktion_graph::LockFreeMultiThreadedNodePlayer::prepareToPlay().
process()
int tracktion_engine::TracktionNodePlayer::process (const tracktion_graph::Node::ProcessContext & pc)
Processes a block of audio and MIDI data.
Returns the number of times a node was checked but unable to be processed.
References tracktion_graph::PlayHeadState::playHead, tracktion_graph::Node::ProcessContext::referenceSampleRange, and tracktion_graph::PlayHead::setReferenceSampleRange().
clearNode()
void tracktion_engine::TracktionNodePlayer::clearNode ()
Clears the Node currently playing.
References tracktion_graph::LockFreeMultiThreadedNodePlayer::clearNode().
getSampleRate()
double tracktion_engine::TracktionNodePlayer::getSampleRate () const
Returns the current sample rate.
References tracktion_graph::LockFreeMultiThreadedNodePlayer::getSampleRate().
enablePooledMemoryAllocations()
void tracktion_engine::TracktionNodePlayer::enablePooledMemoryAllocations (bool enablePooledMemory)
References tracktion_graph::LockFreeMultiThreadedNodePlayer::enablePooledMemoryAllocations().
The documentation for this class was generated from the following file:
tracktion_TracktionNodePlayer.h