TracktionEngine: PlaybackRegionAndSource Class Reference
PlaybackRegionAndSource Class Reference
Public Member Functions
PlaybackRegionAndSource (ARADocument &doc, AudioClipBase &audioClip, const ARAFactory &f, const ARAPlugInExtensionInstance &pluginExtensionInstance, const juce::String &itemID, PlaybackRegionAndSource *instanceToClone)
~PlaybackRegionAndSource ()
void enable ()
void disable ()
void setViewSelection ()
Public Attributes
std::unique_ptr< PlaybackRegionWrapper > playbackRegion
std::unique_ptr< AudioSourceWrapper > audioSource
Constructor & Destructor Documentation
PlaybackRegionAndSource()
PlaybackRegionAndSource::PlaybackRegionAndSource (ARADocument & doc, AudioClipBase & audioClip, const ARAFactory & f, const ARAPlugInExtensionInstance & pluginExtensionInstance, const juce::String & itemID, PlaybackRegionAndSource * instanceToClone)
References audioSource, CRASH_TRACER, enable(), and playbackRegion.
~PlaybackRegionAndSource()
PlaybackRegionAndSource::~PlaybackRegionAndSource ()
Note
Destruction order matters here
References audioSource, CRASH_TRACER, disable(), and playbackRegion.
Member Function Documentation
enable()
void PlaybackRegionAndSource::enable ()
References audioSource, and CRASH_TRACER.
Referenced by PlaybackRegionAndSource().
disable()
void PlaybackRegionAndSource::disable ()
References audioSource, and CRASH_TRACER.
Referenced by ~PlaybackRegionAndSource().
setViewSelection()
void PlaybackRegionAndSource::setViewSelection ()
References playbackRegion.
Member Data Documentation
playbackRegion
std::unique_ptr<PlaybackRegionWrapper> PlaybackRegionAndSource::playbackRegion
Referenced by PlaybackRegionAndSource(), setViewSelection(), and ~PlaybackRegionAndSource().
audioSource
std::unique_ptr<AudioSourceWrapper> PlaybackRegionAndSource::audioSource
Referenced by disable(), enable(), PlaybackRegionAndSource(), and ~PlaybackRegionAndSource().
The documentation for this class was generated from the following file:
tracktion_ARAWrapperInterfaces.h