TracktionEngine: tracktion_graph::ForwardingNode Class Reference
tracktion_graph::ForwardingNode Class Reference final
Takes a non-owning input node and simply forwards its outputs on.
Public Member Functions
ForwardingNode (tracktion_graph::Node *inputNode)
ForwardingNode (std::shared_ptr< tracktion_graph::Node > inputNode)
tracktion_graph::NodeProperties getNodeProperties () override
Should return the properties of the node.
std::vector< tracktion_graph::Node * > getDirectInputNodes () override
Should return all the inputs directly feeding in to this node.
bool isReadyToProcess () override
Should return true when this node is ready to be processed.
void process (ProcessContext &pc) override
Called when the node is to be processed.
Public Member Functions inherited from tracktion_graph::Node
Node ()=default
virtual ~Node ()=default
void initialise (const PlaybackInitialisationInfo &)
Call once after the graph has been constructed to initialise buffers etc.
void prepareForNextBlock (juce::Range< int64_t > referenceSampleRange)
Call before processing the next block, used to reset the process status.
void process (juce::Range< int64_t > referenceSampleRange)
Call to process the node, which will in turn call the process method with the buffers to fill.
bool hasProcessed () const
Returns true if this node has processed and its outputs can be retrieved.
AudioAndMidiBuffer getProcessedOutput ()
Returns the processed audio and MIDI output.
virtual bool transform (Node &)
Called after construction to give the node a chance to modify its topology.
void retain ()
Retains the buffers so they won't be deallocated after the Node has processed.
void release ()
Releases the buffers allowing internal storage to be deallocated.
virtual size_t getAllocatedBytes () const
Additional Inherited Members
Public Attributes inherited from tracktion_graph::Node
void * internal = nullptr
int numOutputNodes = -1
Protected Member Functions inherited from tracktion_graph::Node
virtual void prepareToPlay (const PlaybackInitialisationInfo &)
Called once before playback begins for each node.
virtual void prefetchBlock (juce::Range< int64_t >)
Called before once on all Nodes before they are processed.
void setOptimisations (NodeOptimisations)
This can be called to provide some hints about allocating or playing back a Node to improve efficiency.
void setAudioOutput (Node *sourceNode, const choc::buffer::ChannelArrayView< float > &)
This can be called during your process function to set a view to the output.
Detailed Description
Takes a non-owning input node and simply forwards its outputs on.
Constructor & Destructor Documentation
ForwardingNode() [1/2]
tracktion_graph::ForwardingNode::ForwardingNode (tracktion_graph::Node * inputNode)
ForwardingNode() [2/2]
tracktion_graph::ForwardingNode::ForwardingNode (std::shared_ptr< tracktion_graph::Node > inputNode)
Member Function Documentation
getNodeProperties()
tracktion_graph::NodeProperties tracktion_graph::ForwardingNode::getNodeProperties () override virtual
Should return the properties of the node.
This should not be called until after initialise.
Implements tracktion_graph::Node.
References tracktion_graph::hash_combine().
getDirectInputNodes()
std::vector<tracktion_graph::Node*> tracktion_graph::ForwardingNode::getDirectInputNodes () override virtual
Should return all the inputs directly feeding in to this node.
Reimplemented from tracktion_graph::Node.
isReadyToProcess()
bool tracktion_graph::ForwardingNode::isReadyToProcess () override virtual
Should return true when this node is ready to be processed.
This is usually when its input's output buffers are ready.
Implements tracktion_graph::Node.
process()
void tracktion_graph::ForwardingNode::process (ProcessContext &) override virtual
Called when the node is to be processed.
This should add in to the buffers available making sure not to change their size at all.
Implements tracktion_graph::Node.
References tracktion_graph::Node::AudioAndMidiBuffer::audio, tracktion_graph::Node::ProcessContext::buffers, tracktion_engine::AppFunctions::copy(), tracktion_engine::MidiMessageArray::copyFrom(), and tracktion_graph::Node::AudioAndMidiBuffer::midi.
The documentation for this class was generated from the following file:
tracktion_graph_TestNodes.h