TracktionEngine: tracktion::engine::AudioNode Class Reference
tracktion::engine::AudioNode Class Reference abstract
Base class for nodes in an audio playback graph.
Public Types
using VisitorFn = std::function< void(AudioNode &)>
Public Member Functions
AudioNode ()
virtual ~AudioNode ()
virtual void getAudioNodeProperties (AudioNodeProperties &)=0
virtual void prepareAudioNodeToPlay (const PlaybackInitialisationInfo &)=0
tells the node to initialise itself ready for playing from the given time.
virtual bool purgeSubNodes (bool keepAudio, bool keepMidi)=0
Tells the node to delete any sub-nodes that don't produce the required type of output.
virtual void releaseAudioNodeResources ()=0
tells the node that play has stopped, and it can free up anything it no longer needs.
virtual void visitNodes (const VisitorFn &)=0
virtual juce::ReferenceCountedObjectPtr< Plugin > getPlugin () const
virtual void prepareForNextBlock (const AudioRenderContext &)
virtual bool isReadyToRender ()=0
virtual void renderOver (const AudioRenderContext &)=0
virtual void renderAdding (const AudioRenderContext &)=0
void callRenderAdding (const AudioRenderContext &)
void callRenderOver (const AudioRenderContext &)
Static Public Member Functions
template<typename CallbackType >
static void invokeSplitRender (const AudioRenderContext &rc, CallbackType &target)
Detailed Description
Base class for nodes in an audio playback graph.
Member Typedef Documentation
VisitorFn
using tracktion::engine::AudioNode::VisitorFn = std::function<void(AudioNode&)>
Constructor & Destructor Documentation
AudioNode()
tracktion::engine::AudioNode::AudioNode ()
~AudioNode()
virtual tracktion::engine::AudioNode::~AudioNode () virtual
Member Function Documentation
getAudioNodeProperties()
virtual void tracktion::engine::AudioNode::getAudioNodeProperties (AudioNodeProperties &) pure virtual
Implemented in tracktion::engine::SubSampleWaveAudioNode, tracktion::engine::PluginAudioNode, tracktion::engine::SingleInputAudioNode, tracktion::engine::CombiningAudioNode, and tracktion::engine::WaveAudioNode.
prepareAudioNodeToPlay()
virtual void tracktion::engine::AudioNode::prepareAudioNodeToPlay (const PlaybackInitialisationInfo &) pure virtual
tells the node to initialise itself ready for playing from the given time.
This call may be made more than once before releaseAudioNodeResources() is called
Implemented in tracktion::engine::PluginAudioNode, tracktion::engine::SubSampleWaveAudioNode, tracktion::engine::SingleInputAudioNode, tracktion::engine::CombiningAudioNode, and tracktion::engine::WaveAudioNode.
purgeSubNodes()
virtual bool tracktion::engine::AudioNode::purgeSubNodes (bool keepAudio, bool keepMidi) pure virtual
Tells the node to delete any sub-nodes that don't produce the required type of output.
This optimises out any unplayable bits of the audio graph. Returns true if this node should be kept, false if this node can itself be deleted.
Implemented in tracktion::engine::SubSampleWaveAudioNode, tracktion::engine::SingleInputAudioNode, tracktion::engine::PluginAudioNode, tracktion::engine::CombiningAudioNode, and tracktion::engine::WaveAudioNode.
releaseAudioNodeResources()
virtual void tracktion::engine::AudioNode::releaseAudioNodeResources () pure virtual
tells the node that play has stopped, and it can free up anything it no longer needs.
Implemented in tracktion::engine::SingleInputAudioNode, tracktion::engine::PluginAudioNode, tracktion::engine::SubSampleWaveAudioNode, tracktion::engine::CombiningAudioNode, and tracktion::engine::WaveAudioNode.
visitNodes()
virtual void tracktion::engine::AudioNode::visitNodes (const VisitorFn &) pure virtual
Implemented in tracktion::engine::PluginAudioNode, tracktion::engine::SubSampleWaveAudioNode, tracktion::engine::SingleInputAudioNode, tracktion::engine::CombiningAudioNode, and tracktion::engine::WaveAudioNode.
getPlugin()
virtual juce::ReferenceCountedObjectPtr<Plugin> tracktion::engine::AudioNode::getPlugin () const virtual
Reimplemented in tracktion::engine::SingleInputAudioNode, and tracktion::engine::PluginAudioNode.
prepareForNextBlock()
virtual void tracktion::engine::AudioNode::prepareForNextBlock (const AudioRenderContext &) virtual
Reimplemented in tracktion::engine::PluginAudioNode, tracktion::engine::SubSampleWaveAudioNode, tracktion::engine::SingleInputAudioNode, tracktion::engine::CombiningAudioNode, and tracktion::engine::WaveAudioNode.
isReadyToRender()
virtual bool tracktion::engine::AudioNode::isReadyToRender () pure virtual
Implemented in tracktion::engine::SingleInputAudioNode, tracktion::engine::PluginAudioNode, tracktion::engine::SubSampleWaveAudioNode, tracktion::engine::CombiningAudioNode, and tracktion::engine::WaveAudioNode.
renderOver()
virtual void tracktion::engine::AudioNode::renderOver (const AudioRenderContext &) pure virtual
Implemented in tracktion::engine::MuteAudioNode, tracktion::engine::SpeedRampAudioNode, tracktion::engine::PluginAudioNode, tracktion::engine::SubSampleWaveAudioNode, tracktion::engine::TimedMutingAudioNode, tracktion::engine::FadeInOutAudioNode, tracktion::engine::SingleInputAudioNode, tracktion::engine::CombiningAudioNode, and tracktion::engine::WaveAudioNode.
renderAdding()
virtual void tracktion::engine::AudioNode::renderAdding (const AudioRenderContext &) pure virtual
Implemented in tracktion::engine::MuteAudioNode, tracktion::engine::SpeedRampAudioNode, tracktion::engine::PluginAudioNode, tracktion::engine::SubSampleWaveAudioNode, tracktion::engine::TimedMutingAudioNode, tracktion::engine::FadeInOutAudioNode, tracktion::engine::SingleInputAudioNode, tracktion::engine::CombiningAudioNode, and tracktion::engine::WaveAudioNode.
callRenderAdding()
void tracktion::engine::AudioNode::callRenderAdding (const AudioRenderContext &)
Referenced by tracktion::engine::SubSampleWaveAudioNode::renderOver().
callRenderOver()
void tracktion::engine::AudioNode::callRenderOver (const AudioRenderContext &)
Referenced by tracktion::engine::TimedMutingAudioNode::renderAdding(), tracktion::engine::PluginAudioNode::renderAdding(), tracktion::engine::SpeedRampAudioNode::renderAdding(), and tracktion::engine::MuteAudioNode::renderAdding().
invokeSplitRender()
template<typename CallbackType > static void tracktion::engine::AudioNode::invokeSplitRender (const AudioRenderContext & rc, CallbackType & target) static
References tracktion::engine::AudioRenderContext::bufferNumSamples, tracktion::engine::AudioRenderContext::bufferStartSample, tracktion::engine::AudioRenderContext::continuity, tracktion::engine::PlayHead::EditTimeWindow::editRange1, tracktion::engine::PlayHead::EditTimeWindow::editRange2, tracktion::engine::AudioRenderContext::firstBlockOfLoop, tracktion::engine::AudioRenderContext::getEditTime(), tracktion::engine::legacy::EditTimeRange::getEnd(), tracktion::engine::legacy::EditTimeRange::getLength(), tracktion::engine::PlayHead::getLoopTimes(), tracktion::engine::legacy::EditTimeRange::getStart(), tracktion::engine::PlayHead::isLooping(), tracktion::engine::PlayHead::isRollingIntoLoop(), tracktion::engine::PlayHead::EditTimeWindow::isSplit, tracktion::engine::AudioRenderContext::lastBlockBeforeLoop, tracktion::engine::AudioRenderContext::midiBufferOffset, tracktion::engine::AudioRenderContext::playhead, tracktion::engine::AudioRenderContext::streamTime, and tracktion::engine::legacy::EditTimeRange::withLength().
Referenced by tracktion::engine::SubSampleWaveAudioNode::renderAdding(), tracktion::engine::TimedMutingAudioNode::renderOver(), and tracktion::engine::SpeedRampAudioNode::renderOver().
The documentation for this class was generated from the following file:
tracktion_AudioNode.h