TracktionEngine: tracktion::engine::ControlSurface Class Reference
tracktion::engine::ControlSurface Class Reference
Base class for types of control surface.
Public Member Functions
ControlSurface (ExternalControllerManager &)
~ControlSurface () override
virtual void initialiseDevice ([[maybe_unused]] bool connect)
virtual void shutDownDevice ()
virtual void updateOSCSettings (int, int, juce::String)
virtual void updateMiscFeatures ()
virtual void numExtendersChanged ([[maybe_unused]] int num, [[maybe_unused]] int main)
virtual void acceptMidiMessage ([[maybe_unused]] int idx, const juce::MidiMessage &)
virtual void moveFader (int channelNum, float newSliderPos)
virtual void moveMasterLevelFader (float newLeftSliderPos, float newRightSliderPos)
virtual void movePanPot ([[maybe_unused]] int channelNum, [[maybe_unused]] float newPan)
virtual void moveAux ([[maybe_unused]] int channel, [[maybe_unused]] const char *bus, [[maybe_unused]] float newPos)
virtual void clearAux (int)
virtual void updateSoloAndMute ([[maybe_unused]] int channelNum, Track::MuteAndSoloLightState, [[maybe_unused]] bool isBright)
virtual void soloCountChanged ([[maybe_unused]] bool anySoloTracks)
virtual void playStateChanged ([[maybe_unused]] bool isPlaying)
virtual void recordStateChanged ([[maybe_unused]] bool isRecording)
virtual void automationReadModeChanged ([[maybe_unused]] bool isReading)
virtual void automationWriteModeChanged ([[maybe_unused]] bool isWriting)
virtual void faderBankChanged ([[maybe_unused]] int newStartChannelNumber, [[maybe_unused]] const juce::StringArray &trackNames)
virtual void channelLevelChanged ([[maybe_unused]] int channel, [[maybe_unused]] float l, [[maybe_unused]] float r)
virtual void trackSelectionChanged ([[maybe_unused]] int channel, [[maybe_unused]] bool isSelected)
virtual void trackRecordEnabled ([[maybe_unused]] int channel, [[maybe_unused]] bool isEnabled)
virtual void masterLevelsChanged ([[maybe_unused]] float leftLevel, [[maybe_unused]] float rightLevel)
virtual void timecodeChanged ([[maybe_unused]] int barsOrHours, [[maybe_unused]] int beatsOrMinutes, [[maybe_unused]] int ticksOrSeconds, [[maybe_unused]] int millisecs, [[maybe_unused]] bool isBarsBeats, [[maybe_unused]] bool isFrames)
virtual void clickOnOffChanged ([[maybe_unused]] bool isClickOn)
virtual void snapOnOffChanged ([[maybe_unused]] bool isSnapOn)
virtual void loopOnOffChanged ([[maybe_unused]] bool isLoopOn)
virtual void slaveOnOffChanged ([[maybe_unused]] bool isSlaving)
virtual void punchOnOffChanged ([[maybe_unused]] bool isPunching)
virtual void scrollOnOffChanged ([[maybe_unused]] bool isScroll)
virtual void undoStatusChanged ([[maybe_unused]] bool canUundo, [[maybe_unused]] bool canReo)
virtual void parameterChanged ([[maybe_unused]] int parameterNumber, [[maybe_unused]] const ParameterSetting &newValue)
virtual void clearParameter ([[maybe_unused]] int parameterNumber)
virtual void markerChanged ([[maybe_unused]] int parameterNumber, [[maybe_unused]] const MarkerSetting &newValue)
virtual void clearMarker ([[maybe_unused]] int parameterNumber)
virtual void auxBankChanged (int)
virtual bool wantsMessage (int, const juce::MidiMessage &)
virtual bool eatsAllMessages ()
virtual bool canSetEatsAllMessages ()
virtual void setEatsAllMessages (bool)
virtual bool canChangeSelectedPlugin ()
virtual void currentSelectionChanged (juce::String)
juce::String getSelectableDescription () override
Subclasses must return a description of what they are.
virtual bool showingPluginParams ()
virtual bool showingMarkers ()
virtual bool showingTracks ()
virtual void deleteController ()
virtual void pluginBypass (bool)
virtual bool isPluginSelected (Plugin *)
virtual void currentEditChanged (Edit *e)
Edit * getEdit () const noexcept
TransportControl * getTransport () const noexcept
bool isSafeRecording () const
int getMarkerBankOffset () const
int getFaderBankOffset () const
int getAuxBankOffset () const
int getParamBankOffset () const
void sendMidiCommandToController (int idx, const void *midiData, int numBytes)
void sendMidiCommandToController (int idx, const juce::MidiMessage &)
template<size_t size>
void sendMidiArray (int idx, const uint8_t(&rawData)[size])
void userMovedFader (int channelNum, float newFaderPosition, bool delta=false)
void userMovedPanPot (int channelNum, float newPanPosition, bool delta=false)
void userMovedMasterLevelFader (float newLevel, bool delta=false)
void userMovedMasterPanPot (float newLevel)
void userMovedAux (int channelNum, float newPosition)
void userPressedAux (int channelNum)
void userMovedQuickParam (float newLevel)
void userPressedSolo (int channelNum)
void userPressedSoloIsolate (int channelNum)
void userPressedMute (int channelNum, bool muteVolumeControl)
void userSelectedTrack (int channelNum)
void userSelectedClipInTrack (int channelNum)
void userSelectedPluginInTrack (int channelNum)
void userPressedRecEnable (int channelNum, bool enableEtoE)
void userPressedPlay ()
void userPressedRecord ()
void userPressedStop ()
void userPressedHome ()
void userPressedEnd ()
void userPressedMarkIn ()
void userPressedMarkOut ()
void userPressedAutomationReading ()
void userPressedAutomationWriting ()
void userToggledBeatsSecondsMode ()
void userPressedSave ()
void userPressedSaveAs ()
void userPressedArmAll ()
void userPressedJumpToMarkIn ()
void userPressedJumpToMarkOut ()
void userPressedZoomIn ()
void userPressedZoomOut ()
void userPressedZoomToFit ()
void userPressedCreateMarker ()
void userPressedNextMarker ()
void userPressedPreviousMarker ()
void userPressedRedo ()
void userPressedUndo ()
void userPressedAbort ()
void userPressedAbortRestart ()
void userPressedCut ()
void userPressedCopy ()
void userPressedPaste (bool insert)
void userPressedDelete (bool marked)
void userPressedZoomFitToTracks ()
void userPressedInsertTempoChange ()
void userPressedInsertPitchChange ()
void userPressedInsertTimeSigChange ()
void userToggledVideoWindow ()
void userToggledMixerWindow (bool fullscreen)
void userToggledMidiEditorWindow (bool fullscreen)
void userToggledTrackEditorWindow (bool zoomed)
void userToggledBrowserWindow ()
void userToggledActionsWindow ()
void userPressedUserAction (int)
void userPressedFreeze ()
void userPressedClearAllSolo ()
void userPressedClearAllMute ()
void userToggledLoopOnOff ()
void userToggledPunchOnOff ()
void userToggledClickOnOff ()
void userToggledSnapOnOff ()
void userToggledSlaveOnOff ()
void userToggledEtoE ()
void userToggledScroll ()
void userSkippedToNextMarkerLeft ()
void userSkippedToNextMarkerRight ()
void userNudgedLeft ()
void userNudgedRight ()
void userZoomedIn ()
void userZoomedOut ()
void userScrolledTracksUp ()
void userScrolledTracksDown ()
void userScrolledTracksLeft ()
void userScrolledTracksRight ()
void userZoomedTracksIn ()
void userZoomedTracksOut ()
void selectOtherObject (SelectableClass::Relationship, bool moveFromCurrentPlugin)
void muteOrUnmutePluginsInTrack ()
void userChangedFaderBanks (int channelNumDelta)
void userMovedJogWheel (float amount)
void userChangedRewindButton (bool isButtonDown)
void userChangedFastForwardButton (bool isButtonDown)
void userMovedParameterControl (int parameter, float newValue)
void userPressedParameterControl (int paramNumber)
void userChangedParameterBank (int deltaParams)
void userChangedMarkerBank (int deltaMarkers)
void userPressedGoToMarker (int marker)
void userChangedAuxBank (int delta)
void updateDeviceState ()
void redrawSelectedPlugin ()
void redrawSelectedTracks ()
Edit * getEditIfOnEditScreen () const
Public Member Functions inherited from tracktion::engine::Selectable
Selectable ()
virtual ~Selectable ()
virtual void selectionStatusChanged (bool isNowSelected)
Can be overridden to tell this object that it has just been selected or deselected.
virtual void changed ()
This should be called to send a change notification to any SelectableListeners that are registered with this object.
virtual void selectableAboutToBeDeleted ()
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void addSelectableListener (SelectableListener *)
void removeSelectableListener (SelectableListener *)
void cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
void deselect ()
void propertiesChanged ()
void notifyListenersOfDeletion ()
WeakRef getWeakRef ()
Public Attributes
juce::String deviceDescription
These values need to be set by the subclass.
int supportedExtenders = 0
bool needsMidiChannel = true
juce::String midiChannelName
bool needsMidiBackChannel = false
juce::String midiBackChannelName
bool needsOSCSocket = false
bool wantsClock = false
bool deletable = false
int numberOfFaderChannels = 0
int numCharactersForTrackNames = 0
bool allowBankingOffEnd = false
int numParameterControls = 0
int numCharactersForParameterLabels = 0
int numMarkers = 0
int numCharactersForMarkerLabels = 0
bool pickUpMode = false
int numAuxes = 0
int numCharactersForAuxLabels = 0
bool wantsAuxBanks = false
bool followsTrackSelection = false
Engine & engine
ExternalControllerManager & externalControllerManager
ExternalController * owner = nullptr
Public Attributes inherited from tracktion::engine::Selectable
WeakRef::Master masterReference
Additional Inherited Members
Public Types inherited from tracktion::engine::Selectable
using WeakRef = juce::WeakReference< Selectable >
Static Public Member Functions inherited from tracktion::engine::Selectable
static void initialise ()
static bool isSelectableValid (const Selectable *) noexcept
checks whether this object has been deleted.
Detailed Description
Base class for types of control surface.
Constructor & Destructor Documentation
ControlSurface()
tracktion::engine::ControlSurface::ControlSurface (ExternalControllerManager &)
~ControlSurface()
tracktion::engine::ControlSurface::~ControlSurface () override
Member Function Documentation
initialiseDevice()
virtual void tracktion::engine::ControlSurface::initialiseDevice ([[maybe_unused] ] bool connect) virtual
shutDownDevice()
virtual void tracktion::engine::ControlSurface::shutDownDevice () virtual
Reimplemented in tracktion::engine::CustomControlSurface, tracktion::engine::AlphaTrackControlSurface, tracktion::engine::MackieC4, tracktion::engine::MackieMCU, tracktion::engine::NovationRemoteSl, tracktion::engine::MackieXT, and tracktion::engine::TranzportControlSurface.
updateOSCSettings()
virtual void tracktion::engine::ControlSurface::updateOSCSettings (int , int , juce::String) virtual
Reimplemented in tracktion::engine::CustomControlSurface.
updateMiscFeatures()
virtual void tracktion::engine::ControlSurface::updateMiscFeatures () virtual
Reimplemented in tracktion::engine::CustomControlSurface, tracktion::engine::AlphaTrackControlSurface, tracktion::engine::MackieC4, tracktion::engine::MackieMCU, and tracktion::engine::NovationRemoteSl.
numExtendersChanged()
virtual void tracktion::engine::ControlSurface::numExtendersChanged ([[maybe_unused] ] int num, [[maybe_unused] ] int main) virtual
acceptMidiMessage()
virtual void tracktion::engine::ControlSurface::acceptMidiMessage ([[maybe_unused] ] int idx, const juce::MidiMessage &) virtual
moveFader()
virtual void tracktion::engine::ControlSurface::moveFader (int channelNum, float newSliderPos) virtual
Reimplemented in tracktion::engine::CustomControlSurface, tracktion::engine::MackieMCU, tracktion::engine::AlphaTrackControlSurface, tracktion::engine::MackieC4, tracktion::engine::NovationRemoteSl, and tracktion::engine::TranzportControlSurface.
moveMasterLevelFader()
virtual void tracktion::engine::ControlSurface::moveMasterLevelFader (float newLeftSliderPos, float newRightSliderPos) virtual
Reimplemented in tracktion::engine::CustomControlSurface, and tracktion::engine::MackieMCU.
movePanPot()
virtual void tracktion::engine::ControlSurface::movePanPot ([[maybe_unused] ] int channelNum, [[maybe_unused] ] float newPan) virtual
moveAux()
virtual void tracktion::engine::ControlSurface::moveAux ([[maybe_unused] ] int channel, [[maybe_unused] ] const char * bus, [[maybe_unused] ] float newPos) virtual
clearAux()
virtual void tracktion::engine::ControlSurface::clearAux (int) virtual
Reimplemented in tracktion::engine::MackieMCU, and tracktion::engine::MackieC4.
updateSoloAndMute()
virtual void tracktion::engine::ControlSurface::updateSoloAndMute ([[maybe_unused] ] int channelNum, Track::MuteAndSoloLightState , [[maybe_unused] ] bool isBright) virtual
soloCountChanged()
virtual void tracktion::engine::ControlSurface::soloCountChanged ([[maybe_unused] ] bool anySoloTracks) virtual
playStateChanged()
virtual void tracktion::engine::ControlSurface::playStateChanged ([[maybe_unused] ] bool isPlaying) virtual
recordStateChanged()
virtual void tracktion::engine::ControlSurface::recordStateChanged ([[maybe_unused] ] bool isRecording) virtual
automationReadModeChanged()
virtual void tracktion::engine::ControlSurface::automationReadModeChanged ([[maybe_unused] ] bool isReading) virtual
automationWriteModeChanged()
virtual void tracktion::engine::ControlSurface::automationWriteModeChanged ([[maybe_unused] ] bool isWriting) virtual
faderBankChanged()
virtual void tracktion::engine::ControlSurface::faderBankChanged ([[maybe_unused] ] int newStartChannelNumber, [[maybe_unused] ] const juce::StringArray & trackNames) virtual
channelLevelChanged()
virtual void tracktion::engine::ControlSurface::channelLevelChanged ([[maybe_unused] ] int channel, [[maybe_unused] ] float l, [[maybe_unused] ] float r) virtual
trackSelectionChanged()
virtual void tracktion::engine::ControlSurface::trackSelectionChanged ([[maybe_unused] ] int channel, [[maybe_unused] ] bool isSelected) virtual
trackRecordEnabled()
virtual void tracktion::engine::ControlSurface::trackRecordEnabled ([[maybe_unused] ] int channel, [[maybe_unused] ] bool isEnabled) virtual
masterLevelsChanged()
virtual void tracktion::engine::ControlSurface::masterLevelsChanged ([[maybe_unused] ] float leftLevel, [[maybe_unused] ] float rightLevel) virtual
timecodeChanged()
virtual void tracktion::engine::ControlSurface::timecodeChanged ([[maybe_unused] ] int barsOrHours, [[maybe_unused] ] int beatsOrMinutes, [[maybe_unused] ] int ticksOrSeconds, [[maybe_unused] ] int millisecs, [[maybe_unused] ] bool isBarsBeats, [[maybe_unused] ] bool isFrames) virtual
clickOnOffChanged()
virtual void tracktion::engine::ControlSurface::clickOnOffChanged ([[maybe_unused] ] bool isClickOn) virtual
snapOnOffChanged()
virtual void tracktion::engine::ControlSurface::snapOnOffChanged ([[maybe_unused] ] bool isSnapOn) virtual
loopOnOffChanged()
virtual void tracktion::engine::ControlSurface::loopOnOffChanged ([[maybe_unused] ] bool isLoopOn) virtual
slaveOnOffChanged()
virtual void tracktion::engine::ControlSurface::slaveOnOffChanged ([[maybe_unused] ] bool isSlaving) virtual
punchOnOffChanged()
virtual void tracktion::engine::ControlSurface::punchOnOffChanged ([[maybe_unused] ] bool isPunching) virtual
scrollOnOffChanged()
virtual void tracktion::engine::ControlSurface::scrollOnOffChanged ([[maybe_unused] ] bool isScroll) virtual
undoStatusChanged()
virtual void tracktion::engine::ControlSurface::undoStatusChanged ([[maybe_unused] ] bool canUundo, [[maybe_unused] ] bool canReo) virtual
parameterChanged()
virtual void tracktion::engine::ControlSurface::parameterChanged ([[maybe_unused] ] int parameterNumber, [[maybe_unused] ] const ParameterSetting & newValue) virtual
clearParameter()
virtual void tracktion::engine::ControlSurface::clearParameter ([[maybe_unused] ] int parameterNumber) virtual
markerChanged()
virtual void tracktion::engine::ControlSurface::markerChanged ([[maybe_unused] ] int parameterNumber, [[maybe_unused] ] const MarkerSetting & newValue) virtual
clearMarker()
virtual void tracktion::engine::ControlSurface::clearMarker ([[maybe_unused] ] int parameterNumber) virtual
auxBankChanged()
virtual void tracktion::engine::ControlSurface::auxBankChanged (int) virtual
Reimplemented in tracktion::engine::MackieMCU, and tracktion::engine::MackieC4.
wantsMessage()
virtual bool tracktion::engine::ControlSurface::wantsMessage (int , const juce::MidiMessage &) virtual
Reimplemented in tracktion::engine::CustomControlSurface, tracktion::engine::NovationRemoteSl, and tracktion::engine::RemoteSLCompact.
eatsAllMessages()
virtual bool tracktion::engine::ControlSurface::eatsAllMessages () virtual
Reimplemented in tracktion::engine::CustomControlSurface, tracktion::engine::NovationRemoteSl, and tracktion::engine::RemoteSLCompact.
canSetEatsAllMessages()
virtual bool tracktion::engine::ControlSurface::canSetEatsAllMessages () virtual
Reimplemented in tracktion::engine::CustomControlSurface, and tracktion::engine::RemoteSLCompact.
setEatsAllMessages()
virtual void tracktion::engine::ControlSurface::setEatsAllMessages (bool) virtual
Reimplemented in tracktion::engine::CustomControlSurface.
canChangeSelectedPlugin()
virtual bool tracktion::engine::ControlSurface::canChangeSelectedPlugin () virtual
Reimplemented in tracktion::engine::CustomControlSurface, tracktion::engine::MackieC4, tracktion::engine::NovationRemoteSl, tracktion::engine::TranzportControlSurface, and tracktion::engine::RemoteSLCompact.
currentSelectionChanged()
virtual void tracktion::engine::ControlSurface::currentSelectionChanged (juce::String) virtual
Reimplemented in tracktion::engine::CustomControlSurface, tracktion::engine::NovationRemoteSl, and tracktion::engine::MackieC4.
getSelectableDescription()
juce::String tracktion::engine::ControlSurface::getSelectableDescription () override virtual
Subclasses must return a description of what they are.
Implements tracktion::engine::Selectable.
showingPluginParams()
virtual bool tracktion::engine::ControlSurface::showingPluginParams () virtual
Reimplemented in tracktion::engine::MackieMCU, tracktion::engine::MackieC4, tracktion::engine::NovationRemoteSl, and tracktion::engine::RemoteSLCompact.
showingMarkers()
virtual bool tracktion::engine::ControlSurface::showingMarkers () virtual
Reimplemented in tracktion::engine::MackieMCU, and tracktion::engine::RemoteSLCompact.
showingTracks()
virtual bool tracktion::engine::ControlSurface::showingTracks () virtual
Reimplemented in tracktion::engine::MackieMCU, tracktion::engine::MackieC4, tracktion::engine::NovationRemoteSl, and tracktion::engine::RemoteSLCompact.
deleteController()
virtual void tracktion::engine::ControlSurface::deleteController () virtual
Reimplemented in tracktion::engine::CustomControlSurface.
pluginBypass()
virtual void tracktion::engine::ControlSurface::pluginBypass (bool) virtual
Reimplemented in tracktion::engine::MackieC4, and tracktion::engine::AlphaTrackControlSurface.
isPluginSelected()
virtual bool tracktion::engine::ControlSurface::isPluginSelected (Plugin *) virtual
Reimplemented in tracktion::engine::AlphaTrackControlSurface, and tracktion::engine::RemoteSLCompact.
currentEditChanged()
virtual void tracktion::engine::ControlSurface::currentEditChanged (Edit * e) virtual
getEdit()
Edit* tracktion::engine::ControlSurface::getEdit () const noexcept
Referenced by tracktion::engine::ExternalController::getEdit().
getTransport()
TransportControl* tracktion::engine::ControlSurface::getTransport () const noexcept
References tracktion::engine::Edit::getTransport().
Referenced by tracktion::engine::ExternalController::getTransport().
isSafeRecording()
bool tracktion::engine::ControlSurface::isSafeRecording () const
getMarkerBankOffset()
int tracktion::engine::ControlSurface::getMarkerBankOffset () const
getFaderBankOffset()
int tracktion::engine::ControlSurface::getFaderBankOffset () const
getAuxBankOffset()
int tracktion::engine::ControlSurface::getAuxBankOffset () const
getParamBankOffset()
int tracktion::engine::ControlSurface::getParamBankOffset () const
sendMidiCommandToController() [1/2]
void tracktion::engine::ControlSurface::sendMidiCommandToController (int idx, const void * midiData, int numBytes)
Referenced by sendMidiArray().
sendMidiCommandToController() [2/2]
void tracktion::engine::ControlSurface::sendMidiCommandToController (int idx, const juce::MidiMessage &)
sendMidiArray()
template<size_t size> void tracktion::engine::ControlSurface::sendMidiArray (int idx, const uint8_t(&) rawData[size])
References sendMidiCommandToController().
userMovedFader()
void tracktion::engine::ControlSurface::userMovedFader (int channelNum, float newFaderPosition, bool delta = false)
userMovedPanPot()
void tracktion::engine::ControlSurface::userMovedPanPot (int channelNum, float newPanPosition, bool delta = false)
userMovedMasterLevelFader()
void tracktion::engine::ControlSurface::userMovedMasterLevelFader (float newLevel, bool delta = false)
userMovedMasterPanPot()
void tracktion::engine::ControlSurface::userMovedMasterPanPot (float newLevel)
userMovedAux()
void tracktion::engine::ControlSurface::userMovedAux (int channelNum, float newPosition)
userPressedAux()
void tracktion::engine::ControlSurface::userPressedAux (int channelNum)
userMovedQuickParam()
void tracktion::engine::ControlSurface::userMovedQuickParam (float newLevel)
userPressedSolo()
void tracktion::engine::ControlSurface::userPressedSolo (int channelNum)
userPressedSoloIsolate()
void tracktion::engine::ControlSurface::userPressedSoloIsolate (int channelNum)
userPressedMute()
void tracktion::engine::ControlSurface::userPressedMute (int channelNum, bool muteVolumeControl)
userSelectedTrack()
void tracktion::engine::ControlSurface::userSelectedTrack (int channelNum)
userSelectedClipInTrack()
void tracktion::engine::ControlSurface::userSelectedClipInTrack (int channelNum)
userSelectedPluginInTrack()
void tracktion::engine::ControlSurface::userSelectedPluginInTrack (int channelNum)
userPressedRecEnable()
void tracktion::engine::ControlSurface::userPressedRecEnable (int channelNum, bool enableEtoE)
userPressedPlay()
void tracktion::engine::ControlSurface::userPressedPlay ()
userPressedRecord()
void tracktion::engine::ControlSurface::userPressedRecord ()
userPressedStop()
void tracktion::engine::ControlSurface::userPressedStop ()
userPressedHome()
void tracktion::engine::ControlSurface::userPressedHome ()
userPressedEnd()
void tracktion::engine::ControlSurface::userPressedEnd ()
userPressedMarkIn()
void tracktion::engine::ControlSurface::userPressedMarkIn ()
userPressedMarkOut()
void tracktion::engine::ControlSurface::userPressedMarkOut ()
userPressedAutomationReading()
void tracktion::engine::ControlSurface::userPressedAutomationReading ()
userPressedAutomationWriting()
void tracktion::engine::ControlSurface::userPressedAutomationWriting ()
userToggledBeatsSecondsMode()
void tracktion::engine::ControlSurface::userToggledBeatsSecondsMode ()
userPressedSave()
void tracktion::engine::ControlSurface::userPressedSave ()
userPressedSaveAs()
void tracktion::engine::ControlSurface::userPressedSaveAs ()
userPressedArmAll()
void tracktion::engine::ControlSurface::userPressedArmAll ()
userPressedJumpToMarkIn()
void tracktion::engine::ControlSurface::userPressedJumpToMarkIn ()
userPressedJumpToMarkOut()
void tracktion::engine::ControlSurface::userPressedJumpToMarkOut ()
userPressedZoomIn()
void tracktion::engine::ControlSurface::userPressedZoomIn ()
userPressedZoomOut()
void tracktion::engine::ControlSurface::userPressedZoomOut ()
userPressedZoomToFit()
void tracktion::engine::ControlSurface::userPressedZoomToFit ()
userPressedCreateMarker()
void tracktion::engine::ControlSurface::userPressedCreateMarker ()
userPressedNextMarker()
void tracktion::engine::ControlSurface::userPressedNextMarker ()
userPressedPreviousMarker()
void tracktion::engine::ControlSurface::userPressedPreviousMarker ()
userPressedRedo()
void tracktion::engine::ControlSurface::userPressedRedo ()
userPressedUndo()
void tracktion::engine::ControlSurface::userPressedUndo ()
userPressedAbort()
void tracktion::engine::ControlSurface::userPressedAbort ()
userPressedAbortRestart()
void tracktion::engine::ControlSurface::userPressedAbortRestart ()
userPressedCut()
void tracktion::engine::ControlSurface::userPressedCut ()
userPressedCopy()
void tracktion::engine::ControlSurface::userPressedCopy ()
userPressedPaste()
void tracktion::engine::ControlSurface::userPressedPaste (bool insert)
userPressedDelete()
void tracktion::engine::ControlSurface::userPressedDelete (bool marked)
userPressedZoomFitToTracks()
void tracktion::engine::ControlSurface::userPressedZoomFitToTracks ()
userPressedInsertTempoChange()
void tracktion::engine::ControlSurface::userPressedInsertTempoChange ()
userPressedInsertPitchChange()
void tracktion::engine::ControlSurface::userPressedInsertPitchChange ()
userPressedInsertTimeSigChange()
void tracktion::engine::ControlSurface::userPressedInsertTimeSigChange ()
userToggledVideoWindow()
void tracktion::engine::ControlSurface::userToggledVideoWindow ()
userToggledMixerWindow()
void tracktion::engine::ControlSurface::userToggledMixerWindow (bool fullscreen)
userToggledMidiEditorWindow()
void tracktion::engine::ControlSurface::userToggledMidiEditorWindow (bool fullscreen)
userToggledTrackEditorWindow()
void tracktion::engine::ControlSurface::userToggledTrackEditorWindow (bool zoomed)
userToggledBrowserWindow()
void tracktion::engine::ControlSurface::userToggledBrowserWindow ()
userToggledActionsWindow()
void tracktion::engine::ControlSurface::userToggledActionsWindow ()
userPressedUserAction()
void tracktion::engine::ControlSurface::userPressedUserAction (int)
userPressedFreeze()
void tracktion::engine::ControlSurface::userPressedFreeze ()
userPressedClearAllSolo()
void tracktion::engine::ControlSurface::userPressedClearAllSolo ()
userPressedClearAllMute()
void tracktion::engine::ControlSurface::userPressedClearAllMute ()
userToggledLoopOnOff()
void tracktion::engine::ControlSurface::userToggledLoopOnOff ()
userToggledPunchOnOff()
void tracktion::engine::ControlSurface::userToggledPunchOnOff ()
userToggledClickOnOff()
void tracktion::engine::ControlSurface::userToggledClickOnOff ()
userToggledSnapOnOff()
void tracktion::engine::ControlSurface::userToggledSnapOnOff ()
userToggledSlaveOnOff()
void tracktion::engine::ControlSurface::userToggledSlaveOnOff ()
userToggledEtoE()
void tracktion::engine::ControlSurface::userToggledEtoE ()
userToggledScroll()
void tracktion::engine::ControlSurface::userToggledScroll ()
userSkippedToNextMarkerLeft()
void tracktion::engine::ControlSurface::userSkippedToNextMarkerLeft ()
userSkippedToNextMarkerRight()
void tracktion::engine::ControlSurface::userSkippedToNextMarkerRight ()
userNudgedLeft()
void tracktion::engine::ControlSurface::userNudgedLeft ()
userNudgedRight()
void tracktion::engine::ControlSurface::userNudgedRight ()
userZoomedIn()
void tracktion::engine::ControlSurface::userZoomedIn ()
userZoomedOut()
void tracktion::engine::ControlSurface::userZoomedOut ()
userScrolledTracksUp()
void tracktion::engine::ControlSurface::userScrolledTracksUp ()
userScrolledTracksDown()
void tracktion::engine::ControlSurface::userScrolledTracksDown ()
userScrolledTracksLeft()
void tracktion::engine::ControlSurface::userScrolledTracksLeft ()
userScrolledTracksRight()
void tracktion::engine::ControlSurface::userScrolledTracksRight ()
userZoomedTracksIn()
void tracktion::engine::ControlSurface::userZoomedTracksIn ()
userZoomedTracksOut()
void tracktion::engine::ControlSurface::userZoomedTracksOut ()
selectOtherObject()
void tracktion::engine::ControlSurface::selectOtherObject (SelectableClass::Relationship , bool moveFromCurrentPlugin)
muteOrUnmutePluginsInTrack()
void tracktion::engine::ControlSurface::muteOrUnmutePluginsInTrack ()
userChangedFaderBanks()
void tracktion::engine::ControlSurface::userChangedFaderBanks (int channelNumDelta)
userMovedJogWheel()
void tracktion::engine::ControlSurface::userMovedJogWheel (float amount)
userChangedRewindButton()
void tracktion::engine::ControlSurface::userChangedRewindButton (bool isButtonDown)
userChangedFastForwardButton()
void tracktion::engine::ControlSurface::userChangedFastForwardButton (bool isButtonDown)
userMovedParameterControl()
void tracktion::engine::ControlSurface::userMovedParameterControl (int parameter, float newValue)
userPressedParameterControl()
void tracktion::engine::ControlSurface::userPressedParameterControl (int paramNumber)
userChangedParameterBank()
void tracktion::engine::ControlSurface::userChangedParameterBank (int deltaParams)
userChangedMarkerBank()
void tracktion::engine::ControlSurface::userChangedMarkerBank (int deltaMarkers)
userPressedGoToMarker()
void tracktion::engine::ControlSurface::userPressedGoToMarker (int marker)
userChangedAuxBank()
void tracktion::engine::ControlSurface::userChangedAuxBank (int delta)
updateDeviceState()
void tracktion::engine::ControlSurface::updateDeviceState ()
redrawSelectedPlugin()
void tracktion::engine::ControlSurface::redrawSelectedPlugin ()
redrawSelectedTracks()
void tracktion::engine::ControlSurface::redrawSelectedTracks ()
getEditIfOnEditScreen()
Edit* tracktion::engine::ControlSurface::getEditIfOnEditScreen () const
Member Data Documentation
deviceDescription
juce::String tracktion::engine::ControlSurface::deviceDescription
These values need to be set by the subclass.
supportedExtenders
int tracktion::engine::ControlSurface::supportedExtenders = 0
needsMidiChannel
bool tracktion::engine::ControlSurface::needsMidiChannel = true
midiChannelName
juce::String tracktion::engine::ControlSurface::midiChannelName
needsMidiBackChannel
bool tracktion::engine::ControlSurface::needsMidiBackChannel = false
midiBackChannelName
juce::String tracktion::engine::ControlSurface::midiBackChannelName
needsOSCSocket
bool tracktion::engine::ControlSurface::needsOSCSocket = false
Referenced by tracktion::engine::CustomControlSurface::allowsManualEditing().
wantsClock
bool tracktion::engine::ControlSurface::wantsClock = false
deletable
bool tracktion::engine::ControlSurface::deletable = false
numberOfFaderChannels
int tracktion::engine::ControlSurface::numberOfFaderChannels = 0
numCharactersForTrackNames
int tracktion::engine::ControlSurface::numCharactersForTrackNames = 0
allowBankingOffEnd
bool tracktion::engine::ControlSurface::allowBankingOffEnd = false
numParameterControls
int tracktion::engine::ControlSurface::numParameterControls = 0
numCharactersForParameterLabels
int tracktion::engine::ControlSurface::numCharactersForParameterLabels = 0
numMarkers
int tracktion::engine::ControlSurface::numMarkers = 0
numCharactersForMarkerLabels
int tracktion::engine::ControlSurface::numCharactersForMarkerLabels = 0
pickUpMode
bool tracktion::engine::ControlSurface::pickUpMode = false
numAuxes
int tracktion::engine::ControlSurface::numAuxes = 0
numCharactersForAuxLabels
int tracktion::engine::ControlSurface::numCharactersForAuxLabels = 0
wantsAuxBanks
bool tracktion::engine::ControlSurface::wantsAuxBanks = false
followsTrackSelection
bool tracktion::engine::ControlSurface::followsTrackSelection = false
engine
Engine& tracktion::engine::ControlSurface::engine
externalControllerManager
ExternalControllerManager& tracktion::engine::ControlSurface::externalControllerManager
owner
ExternalController* tracktion::engine::ControlSurface::owner = nullptr
The documentation for this class was generated from the following file:
tracktion_ControlSurface.h