TracktionEngine: tracktion::engine::AudioFile Class Reference
tracktion::engine::AudioFile Class Reference
Public Member Functions
AudioFile ()=delete
AudioFile (Engine &e) noexcept
AudioFile (Engine &, const juce::File &) noexcept
AudioFile (const AudioFile &) noexcept
AudioFile & operator= (const AudioFile &) noexcept
~AudioFile ()
const juce::File & getFile () const noexcept
HashCode getHash () const noexcept
juce::String getHashString () const
bool operator== (const AudioFile &other) const noexcept
bool operator!= (const AudioFile &other) const noexcept
bool deleteFile () const
bool moveToTrash () const
bool isNull () const noexcept
bool isValid () const
AudioFileInfo getInfo () const
int64_t getLengthInSamples () const
double getLength () const
int getNumChannels () const
double getSampleRate () const
int getBitsPerSample () const
bool isFloatingPoint () const
juce::StringPairArray getMetadata () const
juce::AudioFormat * getFormat () const
bool isWavFile () const
bool isAiffFile () const
bool isOggFile () const
bool isMp3File () const
bool isFlacFile () const
bool isRexFile () const
Static Public Member Functions
static bool deleteFiles (Engine &, const juce::Array< juce::File > &files)
Public Attributes
Engine * engine = nullptr
Constructor & Destructor Documentation
AudioFile() [1/4]
tracktion::engine::AudioFile::AudioFile () delete
AudioFile() [2/4]
tracktion::engine::AudioFile::AudioFile (Engine & e) noexcept
AudioFile() [3/4]
tracktion::engine::AudioFile::AudioFile (Engine & , const juce::File &) explicit noexcept
AudioFile() [4/4]
tracktion::engine::AudioFile::AudioFile (const AudioFile &) noexcept
~AudioFile()
tracktion::engine::AudioFile::~AudioFile ()
Member Function Documentation
operator=()
AudioFile& tracktion::engine::AudioFile::operator= (const AudioFile &) noexcept
getFile()
const juce::File& tracktion::engine::AudioFile::getFile () const noexcept
Referenced by tracktion::engine::ReverseRenderJob::renderNextBlock(), and tracktion::engine::WarpTimeRenderJob::renderNextBlock().
getHash()
HashCode tracktion::engine::AudioFile::getHash () const noexcept
getHashString()
juce::String tracktion::engine::AudioFile::getHashString () const
operator==()
bool tracktion::engine::AudioFile::operator== (const AudioFile & other) const noexcept
operator!=()
bool tracktion::engine::AudioFile::operator!= (const AudioFile & other) const noexcept
deleteFile()
bool tracktion::engine::AudioFile::deleteFile () const
deleteFiles()
static bool tracktion::engine::AudioFile::deleteFiles (Engine & , const juce::Array< juce::File > & files) static
moveToTrash()
bool tracktion::engine::AudioFile::moveToTrash () const
isNull()
bool tracktion::engine::AudioFile::isNull () const noexcept
Referenced by tracktion::engine::SubSampleWaveAudioNode::isReadyToRender().
isValid()
bool tracktion::engine::AudioFile::isValid () const
getInfo()
AudioFileInfo tracktion::engine::AudioFile::getInfo () const
Referenced by tracktion::engine::WarpTimeRenderJob::renderNextBlock().
getLengthInSamples()
int64_t tracktion::engine::AudioFile::getLengthInSamples () const
getLength()
double tracktion::engine::AudioFile::getLength () const
getNumChannels()
int tracktion::engine::AudioFile::getNumChannels () const
Referenced by tracktion::engine::SubSampleWaveAudioNode::getAudioNodeProperties().
getSampleRate()
double tracktion::engine::AudioFile::getSampleRate () const
getBitsPerSample()
int tracktion::engine::AudioFile::getBitsPerSample () const
isFloatingPoint()
bool tracktion::engine::AudioFile::isFloatingPoint () const
getMetadata()
juce::StringPairArray tracktion::engine::AudioFile::getMetadata () const
getFormat()
juce::AudioFormat* tracktion::engine::AudioFile::getFormat () const
isWavFile()
bool tracktion::engine::AudioFile::isWavFile () const
isAiffFile()
bool tracktion::engine::AudioFile::isAiffFile () const
isOggFile()
bool tracktion::engine::AudioFile::isOggFile () const
isMp3File()
bool tracktion::engine::AudioFile::isMp3File () const
isFlacFile()
bool tracktion::engine::AudioFile::isFlacFile () const
isRexFile()
bool tracktion::engine::AudioFile::isRexFile () const
Member Data Documentation
engine
Engine* tracktion::engine::AudioFile::engine = nullptr
The documentation for this class was generated from the following file:
tracktion_AudioFile.h