TracktionEngine: tracktion_engine::MidiNote Class Reference
tracktion_engine::MidiNote Class Reference
Public Types
enum NoteEdge { startEdge, endEdge }
Public Member Functions
MidiNote (const juce::ValueTree &)
MidiNote (MidiNote &&)=default
bool operator== (const MidiNote &other) const noexcept
bool operator!= (const MidiNote &other) const noexcept
double getBeatPosition () const noexcept
Start pos, in beats, from the start of the clip.
double getStartBeat () const noexcept
double getEndBeat () const noexcept
double getLengthBeats () const noexcept
juce::Range< double > getRangeBeats () const noexcept
double getPlaybackTime (NoteEdge, const MidiClip &, const GrooveTemplate *) const
double getQuantisedStartBeat (const MidiClip &) const
Returns the start, quantised according to the clip's settings.
double getQuantisedStartBeat (const MidiClip *) const
double getQuantisedEndBeat (const MidiClip &) const
double getQuantisedEndBeat (const MidiClip *) const
double getQuantisedLengthBeats (const MidiClip &) const
double getQuantisedLengthBeats (const MidiClip *) const
double getEditStartTime (const MidiClip &) const
Gets the start of this note in terms of edit time, taking into account quantising, groove templates, clip offset, etc...
double getEditEndTime (const MidiClip &) const
double getLengthSeconds (const MidiClip &) const
EditTimeRange getEditTimeRange (const MidiClip &) const
void setStartAndLength (double newStartBeat, double newLengthInBeats, juce::UndoManager *)
int getNoteNumber () const noexcept
void setNoteNumber (int newNoteNumber, juce::UndoManager *)
int getVelocity () const noexcept
void setVelocity (int newVelocity, juce::UndoManager *)
int getColour () const noexcept
void setColour (int newColourIndex, juce::UndoManager *)
bool isMute () const noexcept
void setMute (bool shouldMute, juce::UndoManager *)
Static Public Member Functions
static juce::ValueTree createNote (const MidiNote &, double newStart, double newLength)
Public Attributes
juce::ValueTree state
Member Enumeration Documentation
NoteEdge
enum tracktion_engine::MidiNote::NoteEdge
Enumerator
startEdge
endEdge
Constructor & Destructor Documentation
MidiNote() [1/2]
tracktion_engine::MidiNote::MidiNote (const juce::ValueTree &)
MidiNote() [2/2]
tracktion_engine::MidiNote::MidiNote (MidiNote &&) default
Member Function Documentation
createNote()
static juce::ValueTree tracktion_engine::MidiNote::createNote (const MidiNote & , double newStart, double newLength) static
operator==()
bool tracktion_engine::MidiNote::operator== (const MidiNote & other) const noexcept
References state.
operator!=()
bool tracktion_engine::MidiNote::operator!= (const MidiNote & other) const noexcept
References state.
getBeatPosition()
double tracktion_engine::MidiNote::getBeatPosition () const noexcept
Start pos, in beats, from the start of the clip.
getStartBeat()
double tracktion_engine::MidiNote::getStartBeat () const noexcept
Referenced by getRangeBeats().
getEndBeat()
double tracktion_engine::MidiNote::getEndBeat () const noexcept
Referenced by getRangeBeats().
getLengthBeats()
double tracktion_engine::MidiNote::getLengthBeats () const noexcept
getRangeBeats()
juce::Range<double> tracktion_engine::MidiNote::getRangeBeats () const noexcept
References getEndBeat(), and getStartBeat().
getPlaybackTime()
double tracktion_engine::MidiNote::getPlaybackTime (NoteEdge , const MidiClip & , const GrooveTemplate *) const
getQuantisedStartBeat() [1/2]
double tracktion_engine::MidiNote::getQuantisedStartBeat (const MidiClip &) const
Returns the start, quantised according to the clip's settings.
getQuantisedStartBeat() [2/2]
double tracktion_engine::MidiNote::getQuantisedStartBeat (const MidiClip *) const
getQuantisedEndBeat() [1/2]
double tracktion_engine::MidiNote::getQuantisedEndBeat (const MidiClip &) const
getQuantisedEndBeat() [2/2]
double tracktion_engine::MidiNote::getQuantisedEndBeat (const MidiClip *) const
getQuantisedLengthBeats() [1/2]
double tracktion_engine::MidiNote::getQuantisedLengthBeats (const MidiClip &) const
getQuantisedLengthBeats() [2/2]
double tracktion_engine::MidiNote::getQuantisedLengthBeats (const MidiClip *) const
getEditStartTime()
double tracktion_engine::MidiNote::getEditStartTime (const MidiClip &) const
Gets the start of this note in terms of edit time, taking into account quantising, groove templates, clip offset, etc...
getEditEndTime()
double tracktion_engine::MidiNote::getEditEndTime (const MidiClip &) const
getLengthSeconds()
double tracktion_engine::MidiNote::getLengthSeconds (const MidiClip &) const
getEditTimeRange()
EditTimeRange tracktion_engine::MidiNote::getEditTimeRange (const MidiClip &) const
setStartAndLength()
void tracktion_engine::MidiNote::setStartAndLength (double newStartBeat, double newLengthInBeats, juce::UndoManager *)
getNoteNumber()
int tracktion_engine::MidiNote::getNoteNumber () const noexcept
setNoteNumber()
void tracktion_engine::MidiNote::setNoteNumber (int newNoteNumber, juce::UndoManager *)
getVelocity()
int tracktion_engine::MidiNote::getVelocity () const noexcept
setVelocity()
void tracktion_engine::MidiNote::setVelocity (int newVelocity, juce::UndoManager *)
getColour()
int tracktion_engine::MidiNote::getColour () const noexcept
setColour()
void tracktion_engine::MidiNote::setColour (int newColourIndex, juce::UndoManager *)
isMute()
bool tracktion_engine::MidiNote::isMute () const noexcept
setMute()
void tracktion_engine::MidiNote::setMute (bool shouldMute, juce::UndoManager *)
Member Data Documentation
state
juce::ValueTree tracktion_engine::MidiNote::state
Referenced by operator!=(), and operator==().
The documentation for this class was generated from the following file:
tracktion_MidiNote.h