TracktionEngine: tracktion_engine::SidechainSendAudioNode Class Reference
tracktion_engine::SidechainSendAudioNode Class Reference
Public Member Functions
SidechainSendAudioNode (AudioNode *source, EditItemID sourceTrackID)
void prepareAudioNodeToPlay (const PlaybackInitialisationInfo &info) override
tells the node to initialise itself ready for playing from the given time.
void prepareForNextBlock (const AudioRenderContext &rc) override
void renderOver (const AudioRenderContext &rc) override
void renderAdding (const AudioRenderContext &rc) override
Public Member Functions inherited from tracktion_engine::SingleInputAudioNode
SingleInputAudioNode (AudioNode *input)
void getAudioNodeProperties (AudioNodeProperties &) override
void visitNodes (const VisitorFn &) override
juce::ReferenceCountedObjectPtr< Plugin > getPlugin () const override
bool isReadyToRender () override
bool purgeSubNodes (bool keepAudio, bool keepMidi) override
Tells the node to delete any sub-nodes that don't produce the required type of output.
void releaseAudioNodeResources () override
tells the node that play has stopped, and it can free up anything it no longer needs.
Public Member Functions inherited from tracktion_engine::AudioNode
AudioNode ()
virtual ~AudioNode ()
void callRenderAdding (const AudioRenderContext &)
void callRenderOver (const AudioRenderContext &)
Public Attributes
const EditItemID srcTrackID
juce::AudioBuffer< float > lastBlock
Public Attributes inherited from tracktion_engine::SingleInputAudioNode
const std::unique_ptr< AudioNode > input
Additional Inherited Members
Public Types inherited from tracktion_engine::AudioNode
using VisitorFn = std::function< void(AudioNode &)>
Static Public Member Functions inherited from tracktion_engine::AudioNode
template<typename CallbackType >
static void invokeSplitRender (const AudioRenderContext &rc, CallbackType &target)
Constructor & Destructor Documentation
SidechainSendAudioNode()
tracktion_engine::SidechainSendAudioNode::SidechainSendAudioNode (AudioNode * source, EditItemID sourceTrackID)
Member Function Documentation
prepareAudioNodeToPlay()
void tracktion_engine::SidechainSendAudioNode::prepareAudioNodeToPlay (const PlaybackInitialisationInfo &) override virtual
tells the node to initialise itself ready for playing from the given time.
This call may be made more than once before releaseAudioNodeResources() is called
Reimplemented from tracktion_engine::SingleInputAudioNode.
References tracktion_engine::PlaybackInitialisationInfo::blockSizeSamples, tracktion_engine::SingleInputAudioNode::input, lastBlock, and tracktion_engine::PlaybackInitialisationInfo::sampleRate.
prepareForNextBlock()
void tracktion_engine::SidechainSendAudioNode::prepareForNextBlock (const AudioRenderContext & rc) override virtual
Reimplemented from tracktion_engine::SingleInputAudioNode.
References tracktion_engine::AudioRenderContext::bufferStartSample, tracktion_engine::SingleInputAudioNode::input, lastBlock, and tracktion_engine::MidiMessageArray::swapWith().
renderOver()
void tracktion_engine::SidechainSendAudioNode::renderOver (const AudioRenderContext & rc) override virtual
Reimplemented from tracktion_engine::SingleInputAudioNode.
References tracktion_engine::AudioRenderContext::bufferForMidiMessages, tracktion_engine::AudioRenderContext::bufferNumSamples, tracktion_engine::AudioRenderContext::bufferStartSample, tracktion_engine::AudioRenderContext::destBuffer, tracktion_engine::SingleInputAudioNode::input, lastBlock, and tracktion_engine::MidiMessageArray::swapWith().
renderAdding()
void tracktion_engine::SidechainSendAudioNode::renderAdding (const AudioRenderContext & rc) override virtual
Reimplemented from tracktion_engine::SingleInputAudioNode.
References tracktion_engine::AudioNode::callRenderOver().
Member Data Documentation
srcTrackID
const EditItemID tracktion_engine::SidechainSendAudioNode::srcTrackID
lastBlock
juce::AudioBuffer<float> tracktion_engine::SidechainSendAudioNode::lastBlock
Referenced by prepareAudioNodeToPlay(), prepareForNextBlock(), renderOver(), and tracktion_engine::SidechainReceiveAudioNode::renderOver().
The documentation for this class was generated from the following file:
tracktion_SidechainAudioNode.h