TracktionEngine: tracktion_engine::AudioNode Class Reference
tracktion_engine::AudioNode Class Reference abstract
Base class for nodes in an audio playback graph.
Public Types
using VisitorFn = std::function< void(AudioNode &)>
Public Member Functions
AudioNode ()
virtual ~AudioNode ()
virtual void getAudioNodeProperties (AudioNodeProperties &)=0
virtual void prepareAudioNodeToPlay (const PlaybackInitialisationInfo &)=0
tells the node to initialise itself ready for playing from the given time.
virtual bool purgeSubNodes (bool keepAudio, bool keepMidi)=0
Tells the node to delete any sub-nodes that don't produce the required type of output.
virtual void releaseAudioNodeResources ()=0
tells the node that play has stopped, and it can free up anything it no longer needs.
virtual void visitNodes (const VisitorFn &)=0
virtual juce::ReferenceCountedObjectPtr< Plugin > getPlugin () const
virtual void prepareForNextBlock (const AudioRenderContext &)
virtual bool isReadyToRender ()=0
virtual void renderOver (const AudioRenderContext &)=0
virtual void renderAdding (const AudioRenderContext &)=0
void callRenderAdding (const AudioRenderContext &)
void callRenderOver (const AudioRenderContext &)
Static Public Member Functions
template<typename CallbackType >
static void invokeSplitRender (const AudioRenderContext &rc, CallbackType &target)
Detailed Description
Base class for nodes in an audio playback graph.
Member Typedef Documentation
VisitorFn
using tracktion_engine::AudioNode::VisitorFn = std::function<void(AudioNode&)>
Constructor & Destructor Documentation
AudioNode()
tracktion_engine::AudioNode::AudioNode ()
~AudioNode()
virtual tracktion_engine::AudioNode::~AudioNode () virtual
Member Function Documentation
getAudioNodeProperties()
virtual void tracktion_engine::AudioNode::getAudioNodeProperties (AudioNodeProperties &) pure virtual
Implemented in tracktion_engine::SubSampleWaveAudioNode, tracktion_engine::PluginAudioNode, tracktion_engine::SingleInputAudioNode, tracktion_engine::CombiningAudioNode, and tracktion_engine::WaveAudioNode.
prepareAudioNodeToPlay()
virtual void tracktion_engine::AudioNode::prepareAudioNodeToPlay (const PlaybackInitialisationInfo &) pure virtual
tells the node to initialise itself ready for playing from the given time.
This call may be made more than once before releaseAudioNodeResources() is called
Implemented in tracktion_engine::PluginAudioNode, tracktion_engine::SubSampleWaveAudioNode, tracktion_engine::SingleInputAudioNode, tracktion_engine::CombiningAudioNode, and tracktion_engine::WaveAudioNode.
purgeSubNodes()
virtual bool tracktion_engine::AudioNode::purgeSubNodes (bool keepAudio, bool keepMidi) pure virtual
Tells the node to delete any sub-nodes that don't produce the required type of output.
This optimises out any unplayable bits of the audio graph. Returns true if this node should be kept, false if this node can itself be deleted.
Implemented in tracktion_engine::SubSampleWaveAudioNode, tracktion_engine::SingleInputAudioNode, tracktion_engine::PluginAudioNode, tracktion_engine::CombiningAudioNode, and tracktion_engine::WaveAudioNode.
releaseAudioNodeResources()
virtual void tracktion_engine::AudioNode::releaseAudioNodeResources () pure virtual
tells the node that play has stopped, and it can free up anything it no longer needs.
Implemented in tracktion_engine::SingleInputAudioNode, tracktion_engine::PluginAudioNode, tracktion_engine::SubSampleWaveAudioNode, tracktion_engine::CombiningAudioNode, and tracktion_engine::WaveAudioNode.
visitNodes()
virtual void tracktion_engine::AudioNode::visitNodes (const VisitorFn &) pure virtual
Implemented in tracktion_engine::PluginAudioNode, tracktion_engine::SubSampleWaveAudioNode, tracktion_engine::SingleInputAudioNode, tracktion_engine::CombiningAudioNode, and tracktion_engine::WaveAudioNode.
getPlugin()
virtual juce::ReferenceCountedObjectPtr<Plugin> tracktion_engine::AudioNode::getPlugin () const virtual
Reimplemented in tracktion_engine::SingleInputAudioNode, and tracktion_engine::PluginAudioNode.
prepareForNextBlock()
virtual void tracktion_engine::AudioNode::prepareForNextBlock (const AudioRenderContext &) virtual
Reimplemented in tracktion_engine::PluginAudioNode, tracktion_engine::SubSampleWaveAudioNode, tracktion_engine::SingleInputAudioNode, tracktion_engine::CombiningAudioNode, and tracktion_engine::WaveAudioNode.
isReadyToRender()
virtual bool tracktion_engine::AudioNode::isReadyToRender () pure virtual
Implemented in tracktion_engine::SingleInputAudioNode, tracktion_engine::PluginAudioNode, tracktion_engine::SubSampleWaveAudioNode, tracktion_engine::CombiningAudioNode, and tracktion_engine::WaveAudioNode.
renderOver()
virtual void tracktion_engine::AudioNode::renderOver (const AudioRenderContext &) pure virtual
Implemented in tracktion_engine::MuteAudioNode, tracktion_engine::SpeedRampAudioNode, tracktion_engine::PluginAudioNode, tracktion_engine::SubSampleWaveAudioNode, tracktion_engine::TimedMutingAudioNode, tracktion_engine::FadeInOutAudioNode, tracktion_engine::SingleInputAudioNode, tracktion_engine::CombiningAudioNode, and tracktion_engine::WaveAudioNode.
renderAdding()
virtual void tracktion_engine::AudioNode::renderAdding (const AudioRenderContext &) pure virtual
Implemented in tracktion_engine::MuteAudioNode, tracktion_engine::SpeedRampAudioNode, tracktion_engine::PluginAudioNode, tracktion_engine::SubSampleWaveAudioNode, tracktion_engine::TimedMutingAudioNode, tracktion_engine::FadeInOutAudioNode, tracktion_engine::SingleInputAudioNode, tracktion_engine::CombiningAudioNode, and tracktion_engine::WaveAudioNode.
callRenderAdding()
void tracktion_engine::AudioNode::callRenderAdding (const AudioRenderContext &)
Referenced by tracktion_engine::SubSampleWaveAudioNode::renderOver().
callRenderOver()
void tracktion_engine::AudioNode::callRenderOver (const AudioRenderContext &)
Referenced by tracktion_engine::TimedMutingAudioNode::renderAdding(), tracktion_engine::PluginAudioNode::renderAdding(), tracktion_engine::SpeedRampAudioNode::renderAdding(), and tracktion_engine::MuteAudioNode::renderAdding().
invokeSplitRender()
template<typename CallbackType > static void tracktion_engine::AudioNode::invokeSplitRender (const AudioRenderContext & rc, CallbackType & target) static
References tracktion_engine::AudioRenderContext::bufferNumSamples, tracktion_engine::AudioRenderContext::bufferStartSample, tracktion_engine::AudioRenderContext::continuity, tracktion_engine::PlayHead::EditTimeWindow::editRange1, tracktion_engine::PlayHead::EditTimeWindow::editRange2, tracktion_engine::AudioRenderContext::firstBlockOfLoop, tracktion_engine::AudioRenderContext::getEditTime(), tracktion_engine::EditTimeRange::getEnd(), tracktion_engine::EditTimeRange::getLength(), tracktion_engine::PlayHead::getLoopTimes(), tracktion_engine::EditTimeRange::getStart(), tracktion_engine::PlayHead::isLooping(), tracktion_engine::PlayHead::isRollingIntoLoop(), tracktion_engine::PlayHead::EditTimeWindow::isSplit, tracktion_engine::AudioRenderContext::lastBlockBeforeLoop, tracktion_engine::AudioRenderContext::midiBufferOffset, tracktion_engine::AudioRenderContext::playhead, tracktion_engine::AudioRenderContext::streamTime, and tracktion_engine::EditTimeRange::withLength().
Referenced by tracktion_engine::SubSampleWaveAudioNode::renderAdding(), tracktion_engine::TimedMutingAudioNode::renderOver(), and tracktion_engine::SpeedRampAudioNode::renderOver().
The documentation for this class was generated from the following file:
tracktion_AudioNode.h