TracktionEngine: tracktion_engine::TrackMutingAudioNode Class Reference
tracktion_engine::TrackMutingAudioNode Class Reference
tracktion_engine » playback
An AudioNode that handles muting/soloing of its input node, according to the audibility of a track.
Public Member Functions
TrackMutingAudioNode (Track &t, AudioNode *f, bool muteForInputsWhenRecording)
TrackMutingAudioNode (Edit &e, AudioNode *f)
void renderOver (const AudioRenderContext &rc) override
void renderAdding (const AudioRenderContext &rc) override
Public Member Functions inherited from tracktion_engine::SingleInputAudioNode
SingleInputAudioNode (AudioNode *input)
void getAudioNodeProperties (AudioNodeProperties &) override
void visitNodes (const VisitorFn &) override
void prepareAudioNodeToPlay (const PlaybackInitialisationInfo &) override
tells the node to initialise itself ready for playing from the given time.
juce::ReferenceCountedObjectPtr< Plugin > getPlugin () const override
bool isReadyToRender () override
bool purgeSubNodes (bool keepAudio, bool keepMidi) override
Tells the node to delete any sub-nodes that don't produce the required type of output.
void releaseAudioNodeResources () override
tells the node that play has stopped, and it can free up anything it no longer needs.
void prepareForNextBlock (const AudioRenderContext &) override
Public Member Functions inherited from tracktion_engine::AudioNode
AudioNode ()
virtual ~AudioNode ()
void callRenderAdding (const AudioRenderContext &)
void callRenderOver (const AudioRenderContext &)
Additional Inherited Members
Public Types inherited from tracktion_engine::AudioNode
using VisitorFn = std::function< void(AudioNode &)>
Static Public Member Functions inherited from tracktion_engine::AudioNode
template<typename CallbackType >
static void invokeSplitRender (const AudioRenderContext &rc, CallbackType &target)
Public Attributes inherited from tracktion_engine::SingleInputAudioNode
const std::unique_ptr< AudioNode > input
Detailed Description
An AudioNode that handles muting/soloing of its input node, according to the audibility of a track.
Constructor & Destructor Documentation
TrackMutingAudioNode() [1/2]
tracktion_engine::TrackMutingAudioNode::TrackMutingAudioNode (Track & t, AudioNode * f, bool muteForInputsWhenRecording)
References tracktion_engine::Edit::getAllInputDevices(), tracktion_engine::Track::processAudioNodesWhileMuted(), and tracktion_engine::Track::shouldBePlayed().
TrackMutingAudioNode() [2/2]
tracktion_engine::TrackMutingAudioNode::TrackMutingAudioNode (Edit & e, AudioNode * f)
References tracktion_engine::Edit::areAnyTracksSolo().
Member Function Documentation
renderOver()
void tracktion_engine::TrackMutingAudioNode::renderOver (const AudioRenderContext & rc) override virtual
Reimplemented from tracktion_engine::SingleInputAudioNode.
References tracktion_engine::AudioRenderContext::clearAll(), tracktion_engine::AudioRenderContext::clearAudioBuffer(), tracktion_engine::AudioRenderContext::clearMidiBuffer(), and tracktion_engine::SingleInputAudioNode::input.
renderAdding()
void tracktion_engine::TrackMutingAudioNode::renderAdding (const AudioRenderContext & rc) override virtual
Reimplemented from tracktion_engine::SingleInputAudioNode.
References tracktion_engine::Edit::areAnyTracksSolo(), tracktion_engine::AudioRenderContext::bufferForMidiMessages, tracktion_engine::AudioRenderContext::bufferNumSamples, tracktion_engine::AudioRenderContext::bufferStartSample, tracktion_engine::AudioNode::callRenderOver(), tracktion_engine::AudioRenderContext::destBuffer, tracktion_engine::SingleInputAudioNode::input, tracktion_engine::MidiMessageArray::isAllNotesOff, and tracktion_engine::AppFunctions::start().
The documentation for this class was generated from the following file:
tracktion_TrackMutingAudioNode.h