TracktionEngine: tracktion_engine::InputDevice Class Reference
tracktion_engine::InputDevice Class Reference abstract
Represents an input device.
Public Types
enum DeviceType {
waveDevice, trackWaveDevice, physicalMidiDevice, virtualMidiDevice,
trackMidiDevice
}
enum to allow quick querying of the device type.
Public Types inherited from tracktion_engine::Selectable
using WeakRef = juce::WeakReference< Selectable >
Public Member Functions
InputDevice (Engine &, const juce::String &type, const juce::String &name)
~InputDevice () override
const juce::String & getName () const
const juce::String & getType () const
virtual DeviceType getDeviceType () const =0
bool isTrackDevice () const
juce::String getAlias () const
the alias is the name shown in the draggable input device components
void setAlias (const juce::String &newAlias)
void initialiseDefaultAlias ()
called after all devices are constructed, so it can use all the device names in its calculations.
virtual bool isAvailableToEdit () const
bool isEnabled () const
virtual void setEnabled (bool)=0
virtual bool isMidi () const
bool isEndToEndEnabled () const
virtual void flipEndToEnd ()=0
virtual InputDeviceInstance * createInstance (EditPlaybackContext &)=0
Creates an instance to use for a given playback context.
virtual void masterTimeUpdate (double time)=0
This is a bit of a hack but allows the time for MIDI devices to be set through the base class interface.
virtual void updateRetrospectiveBufferLength (double length)=0
juce::String getSelectableDescription () override
Subclasses must return a description of what they are.
juce::String getGlobalPropertyName () const
Public Member Functions inherited from tracktion_engine::Selectable
Selectable ()
virtual ~Selectable ()
virtual void selectionStatusChanged (bool isNowSelected)
Can be overridden to tell this object that it has just been selected or deselected.
virtual void changed ()
This should be called to send a change notification to any SelectableListeners that are registered with this object.
virtual void selectableAboutToBeDeleted ()
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void addSelectableListener (SelectableListener *)
void removeSelectableListener (SelectableListener *)
void cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
void deselect ()
void propertiesChanged ()
void notifyListenersOfDeletion ()
WeakRef getWeakRef ()
Static Public Member Functions
static void setRetrospectiveLock (Engine &engine, const juce::Array< InputDeviceInstance * > &devices, bool lock)
Static Public Member Functions inherited from tracktion_engine::Selectable
static void initialise ()
static bool isSelectableValid (const Selectable *) noexcept
checks whether this object has been deleted.
Public Attributes
Engine & engine
LevelMeasurer levelMeasurer
Public Attributes inherited from tracktion_engine::Selectable
WeakRef::Master masterReference
Protected Attributes
std::atomic< bool > enabled { false }
bool endToEndEnabled = false
bool retrospectiveRecordLock = false
Detailed Description
Represents an input device.
A single InputDevice object exists for each device in the system. For each InputDevice, there may be multiple InputDeviceInstance objects, for all the active EditPlaybackContexts
Member Enumeration Documentation
DeviceType
enum tracktion_engine::InputDevice::DeviceType
enum to allow quick querying of the device type.
Enumerator
waveDevice
trackWaveDevice
physicalMidiDevice
virtualMidiDevice
trackMidiDevice
Constructor & Destructor Documentation
InputDevice()
tracktion_engine::InputDevice::InputDevice (Engine & , const juce::String & type, const juce::String & name)
~InputDevice()
tracktion_engine::InputDevice::~InputDevice () override
Member Function Documentation
getName()
const juce::String& tracktion_engine::InputDevice::getName () const
getType()
const juce::String& tracktion_engine::InputDevice::getType () const
getDeviceType()
virtual DeviceType tracktion_engine::InputDevice::getDeviceType () const pure virtual
Implemented in tracktion_engine::PhysicalMidiInputDevice, tracktion_engine::VirtualMidiInputDevice, and tracktion_engine::WaveInputDevice.
Referenced by tracktion_engine::InputDeviceInstance::InputDeviceDestinationList::createNewObject().
isTrackDevice()
bool tracktion_engine::InputDevice::isTrackDevice () const
getAlias()
juce::String tracktion_engine::InputDevice::getAlias () const
the alias is the name shown in the draggable input device components
setAlias()
void tracktion_engine::InputDevice::setAlias (const juce::String & newAlias)
initialiseDefaultAlias()
void tracktion_engine::InputDevice::initialiseDefaultAlias ()
called after all devices are constructed, so it can use all the device names in its calculations.
isAvailableToEdit()
virtual bool tracktion_engine::InputDevice::isAvailableToEdit () const virtual
Reimplemented in tracktion_engine::PhysicalMidiInputDevice.
References isEnabled().
isEnabled()
bool tracktion_engine::InputDevice::isEnabled () const
Referenced by isAvailableToEdit().
setEnabled()
virtual void tracktion_engine::InputDevice::setEnabled (bool) pure virtual
Implemented in tracktion_engine::WaveInputDevice, tracktion_engine::VirtualMidiInputDevice, and tracktion_engine::MidiInputDevice.
isMidi()
virtual bool tracktion_engine::InputDevice::isMidi () const virtual
Reimplemented in tracktion_engine::MidiInputDevice.
isEndToEndEnabled()
bool tracktion_engine::InputDevice::isEndToEndEnabled () const
References endToEndEnabled.
flipEndToEnd()
virtual void tracktion_engine::InputDevice::flipEndToEnd () pure virtual
Implemented in tracktion_engine::MidiInputDevice, and tracktion_engine::WaveInputDevice.
createInstance()
virtual InputDeviceInstance* tracktion_engine::InputDevice::createInstance (EditPlaybackContext &) pure virtual
Creates an instance to use for a given playback context.
Implemented in tracktion_engine::WaveInputDevice, tracktion_engine::PhysicalMidiInputDevice, and tracktion_engine::VirtualMidiInputDevice.
masterTimeUpdate()
virtual void tracktion_engine::InputDevice::masterTimeUpdate (double time) pure virtual
This is a bit of a hack but allows the time for MIDI devices to be set through the base class interface.
Implemented in tracktion_engine::WaveInputDevice, and tracktion_engine::MidiInputDevice.
setRetrospectiveLock()
static void tracktion_engine::InputDevice::setRetrospectiveLock (Engine & engine, const juce::Array< InputDeviceInstance * > & devices, bool lock) static
updateRetrospectiveBufferLength()
virtual void tracktion_engine::InputDevice::updateRetrospectiveBufferLength (double length) pure virtual
Implemented in tracktion_engine::MidiInputDevice, and tracktion_engine::WaveInputDevice.
getSelectableDescription()
juce::String tracktion_engine::InputDevice::getSelectableDescription () override virtual
Subclasses must return a description of what they are.
Implements tracktion_engine::Selectable.
Reimplemented in tracktion_engine::WaveInputDevice, and tracktion_engine::VirtualMidiInputDevice.
Referenced by tracktion_engine::InputDeviceInstance::InputDeviceDestination::getSelectableDescription().
getGlobalPropertyName()
juce::String tracktion_engine::InputDevice::getGlobalPropertyName () const
Member Data Documentation
engine
Engine& tracktion_engine::InputDevice::engine
levelMeasurer
LevelMeasurer tracktion_engine::InputDevice::levelMeasurer
enabled
std::atomic<bool> tracktion_engine::InputDevice::enabled { false } protected
endToEndEnabled
bool tracktion_engine::InputDevice::endToEndEnabled = false protected
Referenced by tracktion_engine::MidiInputDevice::isEndToEndEnabled(), and isEndToEndEnabled().
retrospectiveRecordLock
bool tracktion_engine::InputDevice::retrospectiveRecordLock = false protected
The documentation for this class was generated from the following file:
tracktion_InputDevice.h