TracktionEngine: tracktion_engine::Benchmark Class Reference
tracktion_engine::Benchmark Class Reference
An indiviual Benchmark.
Public Member Functions
Benchmark (BenchmarkDescription desc)
Creates a Benchmark for a given BenchmarkDescription.
void start ()
Starts timing the benchmark.
void stop ()
Stops timing the benchmark.
BenchmarkResult getResult () const
Returns the timing results.
Detailed Description
An indiviual Benchmark.
To masure a benchmark, simply create one of these with a valid description then before the code you are measuring call start and stop afterwards. Once you've done that, call getResult() to return the duration the benchmark took to run.
To collect a set of BenchmarkResults see @BenchmarkList
Constructor & Destructor Documentation
Benchmark()
tracktion_engine::Benchmark::Benchmark (BenchmarkDescription desc)
Creates a Benchmark for a given BenchmarkDescription.
Member Function Documentation
start()
void tracktion_engine::Benchmark::start ()
Starts timing the benchmark.
References tracktion_graph::PerformanceMeasurement::start().
Referenced by tracktion_engine::ScopedBenchmark::ScopedBenchmark().
stop()
void tracktion_engine::Benchmark::stop ()
Stops timing the benchmark.
References tracktion_graph::PerformanceMeasurement::stop().
Referenced by tracktion_engine::ScopedBenchmark::~ScopedBenchmark().
getResult()
BenchmarkResult tracktion_engine::Benchmark::getResult () const
Returns the timing results.
References tracktion_engine::createBenchmarkResult(), and tracktion_graph::PerformanceMeasurement::getStatistics().
Referenced by tracktion_engine::ScopedBenchmark::~ScopedBenchmark().
The documentation for this class was generated from the following file:
tracktion_Benchmark.h