TracktionEngine: tracktion_engine::WaveInputDevice Class Reference
tracktion_engine::WaveInputDevice Class Reference
tracktion_engine » playback
A (virtual) audio input device.
Public Member Functions
WaveInputDevice (Engine &, const juce::String &name, const juce::String &type, const std::vector< ChannelIndex > &, DeviceType)
~WaveInputDevice () override
juce::StringArray getRecordFormatNames ()
void resetToDefault ()
void setEnabled (bool) override
DeviceType getDeviceType () const override
InputDeviceInstance * createInstance (EditPlaybackContext &) override
Creates an instance to use for a given playback context.
void flipEndToEnd () override
void setEndToEnd (bool)
void setRecordAdjustmentMs (double ms)
double getRecordAdjustmentMs () const
bool isStereoPair () const
void setStereoPair (bool)
juce::Array< int > getAvailableBitDepths () const
void setBitDepth (int)
int getBitDepth () const
void checkBitDepth ()
void setInputGainDb (float gain)
float getInputGainDb () const
void setRecordTriggerDb (float)
float getRecordTriggerDb () const
void setFilenameMask (const juce::String &)
juce::String getFilenameMask () const
void setFilenameMaskToDefault ()
void setOutputFormat (const juce::String &)
juce::String getOutputFormat () const
void setMergeMode (const juce::String &)
juce::String getMergeMode () const
const std::vector< ChannelIndex > & getChannels () const noexcept
const juce::AudioChannelSet & getChannelSet () const noexcept
void masterTimeUpdate (double) override
This is a bit of a hack but allows the time for MIDI devices to be set through the base class interface.
void consumeNextAudioBlock (const float **allChannels, int numChannels, int numSamples, double streamTime)
RetrospectiveRecordBuffer * getRetrospectiveRecordBuffer ()
void updateRetrospectiveBufferLength (double length) override
AudioNode * createWaveInputDeviceNode (AudioNode *input)
Creates an AudioNode that calls consumeNextAudioBlock during it's render callback.
juce::String getSelectableDescription () override
Subclasses must return a description of what they are.
Public Member Functions inherited from tracktion_engine::InputDevice
InputDevice (Engine &, const juce::String &type, const juce::String &name)
~InputDevice () override
const juce::String & getName () const
const juce::String & getType () const
bool isTrackDevice () const
juce::String getAlias () const
the alias is the name shown in the draggable input device components
void setAlias (const juce::String &newAlias)
void initialiseDefaultAlias ()
called after all devices are constructed, so it can use all the device names in its calculations.
virtual bool isAvailableToEdit () const
bool isEnabled () const
virtual bool isMidi () const
bool isEndToEndEnabled () const
juce::String getGlobalPropertyName () const
Public Member Functions inherited from tracktion_engine::Selectable
Selectable ()
virtual ~Selectable ()
virtual void selectionStatusChanged (bool isNowSelected)
Can be overridden to tell this object that it has just been selected or deselected.
virtual void changed ()
This should be called to send a change notification to any SelectableListeners that are registered with this object.
virtual void selectableAboutToBeDeleted ()
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void addSelectableListener (SelectableListener *)
void removeSelectableListener (SelectableListener *)
void cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
void deselect ()
void propertiesChanged ()
void notifyListenersOfDeletion ()
WeakRef getWeakRef ()
Static Public Member Functions
static juce::StringArray getMergeModes ()
static juce::String getDefaultMask ()
Static Public Member Functions inherited from tracktion_engine::InputDevice
static void setRetrospectiveLock (Engine &engine, const juce::Array< InputDeviceInstance *> &devices, bool lock)
Static Public Member Functions inherited from tracktion_engine::Selectable
static void initialise ()
static bool isSelectableValid (const Selectable *) noexcept
checks whether this object has been deleted.
Protected Member Functions
juce::String openDevice ()
void closeDevice ()
Additional Inherited Members
Public Types inherited from tracktion_engine::InputDevice
enum DeviceType {
waveDevice, trackWaveDevice, physicalMidiDevice, virtualMidiDevice,
trackMidiDevice
}
enum to allow quick querying of the device type.
Public Types inherited from tracktion_engine::Selectable
using WeakRef = juce::WeakReference< Selectable >
Public Attributes inherited from tracktion_engine::InputDevice
Engine & engine
LevelMeasurer levelMeasurer
Public Attributes inherited from tracktion_engine::Selectable
WeakRef::Master masterReference
Protected Attributes inherited from tracktion_engine::InputDevice
std::atomic< bool > enabled { false }
bool endToEndEnabled = false
bool retrospectiveRecordLock = false
Detailed Description
A (virtual) audio input device.
There'll be multiple instances of these, representing mono or stereo pairs of input channels.
Constructor & Destructor Documentation
WaveInputDevice()
tracktion_engine::WaveInputDevice::WaveInputDevice (Engine & , const juce::String & name, const juce::String & type, const std::vector< ChannelIndex > & , DeviceType)
~WaveInputDevice()
tracktion_engine::WaveInputDevice::~WaveInputDevice () override
Member Function Documentation
getMergeModes()
static juce::StringArray tracktion_engine::WaveInputDevice::getMergeModes () static
getRecordFormatNames()
juce::StringArray tracktion_engine::WaveInputDevice::getRecordFormatNames ()
resetToDefault()
void tracktion_engine::WaveInputDevice::resetToDefault ()
setEnabled()
void tracktion_engine::WaveInputDevice::setEnabled (bool) override virtual
Implements tracktion_engine::InputDevice.
getDeviceType()
DeviceType tracktion_engine::WaveInputDevice::getDeviceType () const override virtual
Implements tracktion_engine::InputDevice.
References createInstance(), flipEndToEnd(), setEndToEnd(), and setRecordAdjustmentMs().
createInstance()
InputDeviceInstance* tracktion_engine::WaveInputDevice::createInstance (EditPlaybackContext &) override virtual
Creates an instance to use for a given playback context.
Implements tracktion_engine::InputDevice.
Referenced by getDeviceType().
flipEndToEnd()
void tracktion_engine::WaveInputDevice::flipEndToEnd () override virtual
Implements tracktion_engine::InputDevice.
Referenced by getDeviceType().
setEndToEnd()
void tracktion_engine::WaveInputDevice::setEndToEnd (bool)
Referenced by getDeviceType().
setRecordAdjustmentMs()
void tracktion_engine::WaveInputDevice::setRecordAdjustmentMs (double ms)
Referenced by getDeviceType().
getRecordAdjustmentMs()
double tracktion_engine::WaveInputDevice::getRecordAdjustmentMs () const
References getAvailableBitDepths(), isStereoPair(), setBitDepth(), and setStereoPair().
isStereoPair()
bool tracktion_engine::WaveInputDevice::isStereoPair () const
Referenced by getRecordAdjustmentMs().
setStereoPair()
void tracktion_engine::WaveInputDevice::setStereoPair (bool)
Referenced by getRecordAdjustmentMs().
getAvailableBitDepths()
juce::Array<int> tracktion_engine::WaveInputDevice::getAvailableBitDepths () const
Referenced by getRecordAdjustmentMs().
setBitDepth()
void tracktion_engine::WaveInputDevice::setBitDepth (int)
Referenced by getRecordAdjustmentMs().
getBitDepth()
int tracktion_engine::WaveInputDevice::getBitDepth () const
References checkBitDepth(), and setInputGainDb().
checkBitDepth()
void tracktion_engine::WaveInputDevice::checkBitDepth ()
Referenced by getBitDepth().
setInputGainDb()
void tracktion_engine::WaveInputDevice::setInputGainDb (float gain)
Referenced by getBitDepth().
getInputGainDb()
float tracktion_engine::WaveInputDevice::getInputGainDb () const
References setRecordTriggerDb().
setRecordTriggerDb()
void tracktion_engine::WaveInputDevice::setRecordTriggerDb (float)
Referenced by getInputGainDb().
getRecordTriggerDb()
float tracktion_engine::WaveInputDevice::getRecordTriggerDb () const
References setFilenameMask().
setFilenameMask()
void tracktion_engine::WaveInputDevice::setFilenameMask (const juce::String &)
Referenced by getRecordTriggerDb().
getFilenameMask()
juce::String tracktion_engine::WaveInputDevice::getFilenameMask () const
References getDefaultMask(), setFilenameMaskToDefault(), and setOutputFormat().
setFilenameMaskToDefault()
void tracktion_engine::WaveInputDevice::setFilenameMaskToDefault ()
Referenced by getFilenameMask().
getDefaultMask()
static juce::String tracktion_engine::WaveInputDevice::getDefaultMask () static
Referenced by getFilenameMask().
setOutputFormat()
void tracktion_engine::WaveInputDevice::setOutputFormat (const juce::String &)
Referenced by getFilenameMask().
getOutputFormat()
juce::String tracktion_engine::WaveInputDevice::getOutputFormat () const
References getMergeMode(), and setMergeMode().
setMergeMode()
void tracktion_engine::WaveInputDevice::setMergeMode (const juce::String &)
Referenced by getOutputFormat().
getMergeMode()
juce::String tracktion_engine::WaveInputDevice::getMergeMode () const
Referenced by getOutputFormat().
getChannels()
const std::vector<ChannelIndex>& tracktion_engine::WaveInputDevice::getChannels () const noexcept
getChannelSet()
const juce::AudioChannelSet& tracktion_engine::WaveInputDevice::getChannelSet () const noexcept
masterTimeUpdate()
void tracktion_engine::WaveInputDevice::masterTimeUpdate (double time) override virtual
This is a bit of a hack but allows the time for MIDI devices to be set through the base class interface.
Implements tracktion_engine::InputDevice.
References consumeNextAudioBlock().
consumeNextAudioBlock()
void tracktion_engine::WaveInputDevice::consumeNextAudioBlock (const float ** allChannels, int numChannels, int numSamples, double streamTime)
Referenced by masterTimeUpdate().
getRetrospectiveRecordBuffer()
RetrospectiveRecordBuffer* tracktion_engine::WaveInputDevice::getRetrospectiveRecordBuffer ()
References closeDevice(), createWaveInputDeviceNode(), getSelectableDescription(), openDevice(), and updateRetrospectiveBufferLength().
updateRetrospectiveBufferLength()
void tracktion_engine::WaveInputDevice::updateRetrospectiveBufferLength (double length) override virtual
Implements tracktion_engine::InputDevice.
Referenced by getRetrospectiveRecordBuffer().
createWaveInputDeviceNode()
AudioNode* tracktion_engine::WaveInputDevice::createWaveInputDeviceNode (AudioNode * input)
Creates an AudioNode that calls consumeNextAudioBlock during it's render callback.
Referenced by getRetrospectiveRecordBuffer().
getSelectableDescription()
juce::String tracktion_engine::WaveInputDevice::getSelectableDescription () override virtual
Subclasses must return a description of what they are.
Reimplemented from tracktion_engine::InputDevice.
Referenced by getRetrospectiveRecordBuffer().
openDevice()
juce::String tracktion_engine::WaveInputDevice::openDevice () protected
Referenced by getRetrospectiveRecordBuffer().
closeDevice()
void tracktion_engine::WaveInputDevice::closeDevice () protected
Referenced by getRetrospectiveRecordBuffer().
The documentation for this class was generated from the following file:
tracktion_WaveInputDevice.h