TracktionEngine: tracktion_engine::TrackItem Class Reference
tracktion_engine::TrackItem Class Reference abstract
Base class for EditItems that live in a Track, e.g.
Public Types
enum Type {
Type::unknown, Type::wave, Type::midi, Type::edit,
Type::step, Type::marker, Type::pitch, Type::timeSig,
Type::collection, Type::video, Type::recording, Type::chord,
Type::arranger
}
Defines the types of item that can live on Track[s].
Public Types inherited from tracktion_engine::Selectable
using WeakRef = juce::WeakReference< Selectable >
Public Member Functions
TrackItem (Edit &, EditItemID, Type)
Creates a TrackItem with an ID and type.
~TrackItem ()
Destructor.
virtual Track * getTrack () const =0
Must return the track this item lives on.
virtual bool isGrouped () const
Should return true if this clip is part of a group.
virtual TrackItem * getGroupParent () const
If this clip is part of a group, this should return the parent item it belongs to.
virtual ClipPosition getPosition () const =0
Must return the position of this item.
EditTimeRange getEditTimeRange () const
Returns the time range of this item.
double getStartBeat () const
Returns the start beat in the Edit of this item.
double getContentStartBeat () const
Returns the start beat of the content in the Edit of this item.
double getEndBeat () const
Returns the end beat in the Edit of this item.
double getLengthInBeats () const
Returns the duration in beats the of this item.
double getTimeOfRelativeBeat (double beat) const
Returns an Edit time point for a given number of beats from the start of this item.
double getBeatOfRelativeTime (double t) const
Returns an Edit beat point for a given number of seconds from the start of this item.
double getOffsetInBeats () const
Returns an the offset of this item in beats.
EditItemID getTrackID () const
Returns the ID of the Track this item lives on.
Public Member Functions inherited from tracktion_engine::EditItem
EditItem (EditItemID, Edit &)
virtual ~EditItem ()=default
virtual juce::String getName ()=0
Public Member Functions inherited from tracktion_engine::Selectable
Selectable ()
virtual ~Selectable ()
virtual juce::String getSelectableDescription ()=0
Subclasses must return a description of what they are.
virtual void selectionStatusChanged (bool isNowSelected)
Can be overridden to tell this object that it has just been selected or deselected.
virtual void changed ()
This should be called to send a change notification to any SelectableListeners that are registered with this object.
virtual void selectableAboutToBeDeleted ()
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void addSelectableListener (SelectableListener *)
void removeSelectableListener (SelectableListener *)
void cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
void deselect ()
void propertiesChanged ()
void notifyListenersOfDeletion ()
WeakRef getWeakRef ()
Static Public Member Functions
static const char * typeToString (Type)
Returns the string version of a TrackItem::Type.
static juce::Identifier clipTypeToXMLType (Type)
Returns an Identifier version of a TrackItem::Type.
static TrackItem::Type xmlTagToType (juce::StringRef)
Returns the TrackItem::Type of a type string.
static TrackItem::Type stringToType (const juce::String &)
Returns the TrackItem::Type of a type string.
static juce::String getSuggestedNameForNewItem (Type)
Returns a text string for a new clip of the given type.
template<typename ArrayType >
static void sortByTime (ArrayType &items)
Helper function to sort an array of TrackItem[s] by their start time.
template<typename ArrayType >
static void stableSortByTime (ArrayType &items)
Helper function to sort an array of TrackItem[s] by their start time without changing the order of items at the same time.
Static Public Member Functions inherited from tracktion_engine::Selectable
static void initialise ()
static bool isSelectableValid (const Selectable *) noexcept
checks whether this object has been deleted.
Public Attributes
const Type type
The type of this item.
Public Attributes inherited from tracktion_engine::EditItem
Edit & edit
const EditItemID itemID
Every EditItem has an ID which is unique within the edit.
Public Attributes inherited from tracktion_engine::Selectable
WeakRef::Master masterReference
Detailed Description
Base class for EditItems that live in a Track, e.g.
clips
See also
WaveAudioClip, MidiClip, StepClip, MarkerClip, PitchSetting, TimeSigSetting
Member Enumeration Documentation
Type
enum tracktion_engine::TrackItem::Type strong
Defines the types of item that can live on Track[s].
Enumerator
unknown
A placeholder for unknown items.
wave
A wave clip.
See also
WaveAudioClip
midi
A MIDI clip.
See also
MidiClip.
edit
An Edit clip.
See also
EditClip.
step
A MIDI step clip.
See also
StepClip.
marker
A marker clip.
See also
MarkerClip.
pitch
A pitch setting.
See also
PitchSetting.
timeSig
A time signature settings.
See also
TimeSigSetting.
collection
A collection clip.
See also
CollectionClip.
video
A video clip.
N.B. not yet imlemented.
recording
A temporary recording clip.
chord
A chord clip.
See also
ChordClip.
arranger
An arranger clip.
See also
ArrangerClip.
Constructor & Destructor Documentation
TrackItem()
tracktion_engine::TrackItem::TrackItem (Edit & , EditItemID , Type)
Creates a TrackItem with an ID and type.
IDs should be unique within an Edit.
~TrackItem()
tracktion_engine::TrackItem::~TrackItem ()
Destructor.
Member Function Documentation
typeToString()
static const char* tracktion_engine::TrackItem::typeToString (Type) static
Returns the string version of a TrackItem::Type.
clipTypeToXMLType()
static juce::Identifier tracktion_engine::TrackItem::clipTypeToXMLType (Type) static
Returns an Identifier version of a TrackItem::Type.
xmlTagToType()
static TrackItem::Type tracktion_engine::TrackItem::xmlTagToType (juce::StringRef) static
Returns the TrackItem::Type of a type string.
stringToType()
static TrackItem::Type tracktion_engine::TrackItem::stringToType (const juce::String &) static
Returns the TrackItem::Type of a type string.
getSuggestedNameForNewItem()
static juce::String tracktion_engine::TrackItem::getSuggestedNameForNewItem (Type) static
Returns a text string for a new clip of the given type.
E.g. "New Audio Clip" for Type::wave
getTrack()
virtual Track* tracktion_engine::TrackItem::getTrack () const pure virtual
Must return the track this item lives on.
Implemented in tracktion_engine::Clip, tracktion_engine::PitchSetting, tracktion_engine::TimeSigSetting, and tracktion_engine::CollectionClip.
Referenced by tracktion_engine::TrackSection::merge().
isGrouped()
virtual bool tracktion_engine::TrackItem::isGrouped () const virtual
Should return true if this clip is part of a group.
Reimplemented in tracktion_engine::Clip.
getGroupParent()
virtual TrackItem* tracktion_engine::TrackItem::getGroupParent () const virtual
If this clip is part of a group, this should return the parent item it belongs to.
Reimplemented in tracktion_engine::Clip.
getPosition()
virtual ClipPosition tracktion_engine::TrackItem::getPosition () const pure virtual
Must return the position of this item.
Implemented in tracktion_engine::Clip, tracktion_engine::PitchSetting, tracktion_engine::CollectionClip, and tracktion_engine::TimeSigSetting.
Referenced by getEditTimeRange().
getEditTimeRange()
EditTimeRange tracktion_engine::TrackItem::getEditTimeRange () const
Returns the time range of this item.
References getPosition(), and tracktion_engine::ClipPosition::time.
Referenced by tracktion_engine::TrackSection::merge().
getStartBeat()
double tracktion_engine::TrackItem::getStartBeat () const
Returns the start beat in the Edit of this item.
getContentStartBeat()
double tracktion_engine::TrackItem::getContentStartBeat () const
Returns the start beat of the content in the Edit of this item.
I.e. the beat index of (start - offset)
getEndBeat()
double tracktion_engine::TrackItem::getEndBeat () const
Returns the end beat in the Edit of this item.
getLengthInBeats()
double tracktion_engine::TrackItem::getLengthInBeats () const
Returns the duration in beats the of this item.
getTimeOfRelativeBeat()
double tracktion_engine::TrackItem::getTimeOfRelativeBeat (double beat) const
Returns an Edit time point for a given number of beats from the start of this item.
getBeatOfRelativeTime()
double tracktion_engine::TrackItem::getBeatOfRelativeTime (double t) const
Returns an Edit beat point for a given number of seconds from the start of this item.
getOffsetInBeats()
double tracktion_engine::TrackItem::getOffsetInBeats () const
Returns an the offset of this item in beats.
getTrackID()
EditItemID tracktion_engine::TrackItem::getTrackID () const
Returns the ID of the Track this item lives on.
sortByTime()
template<typename ArrayType > static void tracktion_engine::TrackItem::sortByTime (ArrayType & items) static
Helper function to sort an array of TrackItem[s] by their start time.
stableSortByTime()
template<typename ArrayType > static void tracktion_engine::TrackItem::stableSortByTime (ArrayType & items) static
Helper function to sort an array of TrackItem[s] by their start time without changing the order of items at the same time.
Member Data Documentation
type
const Type tracktion_engine::TrackItem::type
The type of this item.
The documentation for this class was generated from the following file:
tracktion_TrackItem.h