TracktionEngine: tracktion::graph::PlayHeadState Class Reference
tracktion::graph::PlayHeadState Class Reference
tracktion_graph » tracktion_graph
Determines how this block releates to other previous render blocks and if the play head has jumped in time.
#include <tracktion_PlayHeadState.h>
Public Member Functions
PlayHeadState (PlayHead &ph)
void update (juce::Range< int64_t > referenceSampleRange)
Call once per block to update the jumped state.
bool isContiguousWithPreviousBlock () noexcept
Returns true if the play head did not jump and this block is contiguous with the previous block.
bool didPlayheadJump () noexcept
Returns true if the play head jumped.
bool isFirstBlockOfLoop () noexcept
Returns true if this is the first block of a loop.
bool isLastBlockOfLoop () noexcept
Returns true if this is the last block of a loop.
Public Attributes
PlayHead & playHead
bool isPlayHeadRunning = false
bool playheadJumped = false
bool lastBlockOfLoop = false
bool firstBlockOfLoop = false
Detailed Description
Determines how this block releates to other previous render blocks and if the play head has jumped in time.
Constructor & Destructor Documentation
PlayHeadState()
tracktion::graph::PlayHeadState::PlayHeadState (PlayHead & ph)
Member Function Documentation
update()
void tracktion::graph::PlayHeadState::update (juce::Range< int64_t > referenceSampleRange)
Call once per block to update the jumped state.
Usually called at the same time as the PlayHead::incrementReferenceSampleCount method.
References firstBlockOfLoop, tracktion::graph::PlayHead::getLastUserInteractionTime(), tracktion::graph::PlayHead::getLoopRange(), tracktion::graph::PlayHead::isLooping(), isPlayHeadRunning, tracktion::graph::PlayHead::isPlaying(), tracktion::graph::PlayHead::isRollingIntoLoop(), lastBlockOfLoop, playHead, playheadJumped, and tracktion::graph::PlayHead::referenceSamplePositionToTimelinePosition().
Referenced by tracktion::graph::NodePlayer::processWithPlayHeadState().
isContiguousWithPreviousBlock()
bool tracktion::graph::PlayHeadState::isContiguousWithPreviousBlock () noexcept
Returns true if the play head did not jump and this block is contiguous with the previous block.
References didPlayheadJump(), and isFirstBlockOfLoop().
didPlayheadJump()
bool tracktion::graph::PlayHeadState::didPlayheadJump () noexcept
Returns true if the play head jumped.
References playheadJumped.
Referenced by isContiguousWithPreviousBlock().
isFirstBlockOfLoop()
bool tracktion::graph::PlayHeadState::isFirstBlockOfLoop () noexcept
Returns true if this is the first block of a loop.
References firstBlockOfLoop.
Referenced by isContiguousWithPreviousBlock().
isLastBlockOfLoop()
bool tracktion::graph::PlayHeadState::isLastBlockOfLoop () noexcept
Returns true if this is the last block of a loop.
References lastBlockOfLoop.
Member Data Documentation
playHead
PlayHead& tracktion::graph::PlayHeadState::playHead
Referenced by tracktion::engine::TracktionEngineNode::getPlayHead(), tracktion::engine::benchmark_utilities::prepareRenderAndDestroy(), tracktion::graph::NodePlayer::prepareToPlay(), tracktion::engine::MultiThreadedNodePlayer::process(), tracktion::engine::TracktionNodePlayer::process(), tracktion::graph::NodePlayer::processWithPlayHeadState(), and update().
isPlayHeadRunning
bool tracktion::graph::PlayHeadState::isPlayHeadRunning = false
Referenced by update().
playheadJumped
bool tracktion::graph::PlayHeadState::playheadJumped = false
Referenced by didPlayheadJump(), and update().
lastBlockOfLoop
bool tracktion::graph::PlayHeadState::lastBlockOfLoop = false
Referenced by isLastBlockOfLoop(), and update().
firstBlockOfLoop
bool tracktion::graph::PlayHeadState::firstBlockOfLoop = false
Referenced by isFirstBlockOfLoop(), and update().
The documentation for this class was generated from the following file:
tracktion_PlayHeadState.h