TracktionEngine: utilities
utilities
tracktion_graph
Functions
PerformanceMeasurement::PerformanceMeasurement (const std::string &counterName, int runsPerPrintout=100)
Creates a PerformanceMeasurement object.
PerformanceMeasurement::~PerformanceMeasurement ()
Destructor.
void PerformanceMeasurement::Statistics::clear () noexcept
void PerformanceMeasurement::Statistics::addResult (double elapsed) noexcept
std::string PerformanceMeasurement::Statistics::toString () const
void PerformanceMeasurement::start () noexcept
Starts timing.
bool PerformanceMeasurement::stop ()
Stops timing and prints out the results.
void PerformanceMeasurement::printStatistics ()
Dumps the current metrics to std::cout.
Statistics PerformanceMeasurement::getStatisticsAndReset ()
Returns a copy of the current stats, and resets the internal counter.
Detailed Description
Function Documentation
PerformanceMeasurement()
PerformanceMeasurement::PerformanceMeasurement (const std::string & counterName, int runsPerPrintout = 100)
Creates a PerformanceMeasurement object.
Parameters
counterName the name used when printing out the statistics
runsPerPrintout the number of start/stop iterations before calling printStatistics()
References PerformanceMeasurement::Statistics::name.
~PerformanceMeasurement()
PerformanceMeasurement::~PerformanceMeasurement ()
Destructor.
References PerformanceMeasurement::Statistics::numRuns, and PerformanceMeasurement::printStatistics().
clear()
void PerformanceMeasurement::Statistics::clear () noexcept
References PerformanceMeasurement::Statistics::m2, PerformanceMeasurement::Statistics::maximumSeconds, PerformanceMeasurement::Statistics::meanSeconds, PerformanceMeasurement::Statistics::minimumSeconds, PerformanceMeasurement::Statistics::numRuns, and PerformanceMeasurement::Statistics::totalSeconds.
Referenced by PerformanceMeasurement::getStatisticsAndReset().
addResult()
void PerformanceMeasurement::Statistics::addResult (double elapsed) noexcept
Referenced by PerformanceMeasurement::stop().
toString()
std::string PerformanceMeasurement::Statistics::toString () const
Referenced by tracktion_engine::benchmark_utilities::prepareRenderAndDestroy(), and PerformanceMeasurement::printStatistics().
start()
void PerformanceMeasurement::start () noexcept
Starts timing.
See also
stop
Referenced by ScopedPerformanceMeasurement::ScopedPerformanceMeasurement().
stop()
bool PerformanceMeasurement::stop ()
Stops timing and prints out the results.
The number of iterations before doing a printout of the results is set in the constructor.
See also
start
References PerformanceMeasurement::Statistics::addResult(), PerformanceMeasurement::Statistics::numRuns, and PerformanceMeasurement::printStatistics().
Referenced by ScopedPerformanceMeasurement::~ScopedPerformanceMeasurement().
printStatistics()
void PerformanceMeasurement::printStatistics ()
Dumps the current metrics to std::cout.
References PerformanceMeasurement::getStatisticsAndReset(), and PerformanceMeasurement::Statistics::toString().
Referenced by PerformanceMeasurement::stop(), and PerformanceMeasurement::~PerformanceMeasurement().
getStatisticsAndReset()
PerformanceMeasurement::Statistics PerformanceMeasurement::getStatisticsAndReset ()
Returns a copy of the current stats, and resets the internal counter.
References PerformanceMeasurement::Statistics::clear().
Referenced by tracktion_graph::test_utilities::TestProcess< NodePlayerType >::getStatisticsAndReset(), and PerformanceMeasurement::printStatistics().