TracktionEngine: engine::details Namespace Reference
engine::details Namespace Reference
Classes
struct ExitMapWithMutex
Functions
std::atomic< bool > & getShouldExitFlag (std::thread::id id, bool canCreate)
Function Documentation
getShouldExitFlag()
std::atomic<bool>& engine::details::getShouldExitFlag (std::thread::id id, bool canCreate)
Referenced by engine::prepareThreadForShouldExit(), engine::shouldCurrentThreadExit(), and engine::signalThreadShouldExit().