TracktionEngine: tracktion::engine Namespace Reference
tracktion::engine Namespace Reference
tracktion_engine » audio_files | tracktion_engine » control_surfaces | tracktion_engine » midi | tracktion_engine » model | tracktion_engine » playback | tracktion_engine » plugins | tracktion_engine » project | tracktion_engine » selection | tracktion_engine » timestretch | tracktion_engine » utilities | tracktion_graph » utilities
Namespaces
namespace AppFunctions
namespace benchmark_utilities
namespace Click
namespace ClipConstants
Constraints for clip speeds.
namespace detail
namespace details
namespace IDs
namespace MidiNodeHelpers
namespace modifier
namespace ModifierCommon
namespace PredefinedWavetable
namespace RackNodeBuilder
namespace TracktionBinaryData
Classes
class AbletonLink
Manages an Ableton Link session connecting an Edit with a number of networked peers, syncronising their tempos, bar phases and start/stop statuses.
struct ActiveEdits
A list of all currently open edits.
struct ActiveNoteList
class AirWindowsAutomatableParameter
class AirWindowsBase
class AirWindowsCallback
class AirWindowsPlugin
class AlphaTrackControlSurface
struct ARADocumentHolder
class ArrangerClip
class ArrangerLauncherSwitchingNode
A Node that switches between two of its inputs based on a flag.
class ArrangerTrack
A track similar to the MarkerTrack but can be used to move sections of an Edit around.
struct AsyncCaller
Asyncronously call a function.
struct AsyncFunctionCaller
Holds a list of function objects and enables you to call them asyncronously.
struct AtomicWrapper
Wraps an atomic with an interface compatible with var so it can be used within CachedValues in a thread safe way.
class AudioBufferSnapshot
class AudioClipBase
Base class for Clips that produce some kind of audio e.g.
struct AudioFadeCurve
class AudioFifo
class AudioFile
class AudioFileCache
class AudioFileFormatManager
Keeps a list of available wave formats and can create a format object for a file.
struct AudioFileInfo
class AudioFileManager
struct AudioFileUtils
class AudioFileWriter
Smart wrapper for writing to an audio file.
class AudioMidiFifo
class AudioProxyGenerator
class AudioScratchBuffer
An audio scratch buffer that has pooled storage.
class AudioSegmentList
Holds a list of audio regions for playback of things like warp time.
class AudioTrack
class AutomatableEditItem
Base class for elements that have some kind of automatable parameters.
class AutomatableParameter
class AutomatableParameterTree
class AutomationDragDropTarget
Components can implement this to let things know which automatable parameter they control.
struct AutomationIterator
A cache of automation points, with a cursor which moves through it.
class AutomationTrack
class AuxReturnPlugin
class AuxSendNode
Node for an aux send.
class AuxSendPlugin
class BackgroundJobManager
Manages a set of background tasks that can be run concurrently on a background thread.
class BandlimitedWaveLookupTables
struct BeatDetect
struct BlockingFunction
class BreakpointOscillatorModifier
class BufferedAudioFileManager
class BufferedAudioReader
class BufferedFileReader
class BufferedFileReaderWrapper
class BufferingAudioReaderWrapper
FallbackReader that wraps a BufferingAudioReader to avoid reading on the audio thread.
struct ChannelIndex
Describes a channel of a WaveInputDevice or WaveOutputDevice by specifying the channel index in the global device's audio buffer and the purpose as an AudioChannelSet::ChannelType e.g.
class Chord
class ChordClip
class ChordTrack
class ChorusPlugin
class ClickGenerator
Generates click audio and MIDI and adds them to the provided buffer.
class ClickNode
Adds audio and MIDI clicks to the input buffers.
class Clip
A clip in an edit.
class Clipboard
class ClipEffect
class ClipEffects
struct ClipLevel
Holds a clip's level state.
class ClipOwner
Base class for items that can contain clips.
struct ClipPosition
Represents the position of a clip on a timeline.
struct ClipPositionBeats
Represents the position of a clip on a timeline.
class ClipSlot
Represents a slot on a track that a Clip can live in to be played as a launched clip.
class ClipSlotList
A list of the ClipSlots on a Track.
class ClipTrack
class CollectionClip
struct ColourArea
An area of the edit currently control by a control surface.
class CombiningNode
An Node that mixes a sequence of clips of other nodes.
class CompFactory
class CompManager
class CompressorPlugin
class ConstrainedCachedValue
A CachedValue that can take a std::function to constrain its value.
class ContainerClip
A clip that can contain multiple other clips and mix their output together.
class ContainerClipNode
class ControlSurface
Base class for types of control surface.
struct CrashStackTracer
Used by the CRASH_TRACER macros to help provide a useful crash log of the stack.
struct CreateNodeParams
Contains options for Edit Node content creation.
class CurveEditor
class CurveEditorPoint
struct CurvePoint
class CustomControlSurface
struct DbTimePair
struct DeadMansPedalMessage
This RAII class saves a property which will be reported at startup as a failure if the app disappears before its destructor is called.
struct DelayBufferBase
class DelayPlugin
class DeviceManager
struct Ditherer
An extremely naive ditherer.
struct DummyConstrainer
Dummy constrainer which should optimise away to nothing.
class DynamicallyOffsettableNodeBase
class DynamicOffsetNode
class Edit
The Tracktion Edit class!
class EditClip
This is the main source of an Edit clip and is responsible for managing its properties.
struct EditDeleter
Deferred Edit object deleter.
class EditFileOperations
Contains methods for saving an Edit to a file.
class EditInputDevices
class EditInsertPoint
An EditInsertPoint is like a "paste location".
class EditItem
Base class for objects that live inside an edit - e.g.
struct EditItemCache
struct EditItemID
ID for objects of type EditElement - e.g.
struct EditLimits
Contains the limits of the various elements that can be added to an Edit.
struct EditNodeBuilder
class EditPlaybackContext
struct EditPosition
Represents a time point in an Edit stored as either time or beats.
class EditPositionWithTempoSequence
class EditRenderJob
class EditSnapshot
Holds a snapshot of an Edit file of the last time it was saved.
struct EditTimecodeRemapperSnapshot
Takes a copy of all the beat related things in an edit in terms of bars/beats and then remaps these after a tempo change.
struct EditTimeRange
Represents a time range in an Edit stored as either time or beats.
class Engine
The Engine is the central class for all tracktion sessions.
class EngineBehaviour
Provides custom handlers to control various aspects of the engine's behaviour.
class EnvelopeFollowerModifier
class EqualiserPlugin
class ExpEnvelope
class Exportable
An interface for objects within an edit that can be exported.
class ExportJob
class ExternalAutomatableParameter
class ExternalController
Acts as a holder for a ControlSurface object.
class ExternalControllerManager
Keeps a list of external controllers and keeps them connected to the right MIDI in/out devices.
class ExternalPlayheadSynchroniser
An ExternalPlayheadSynchroniser is used to synchronise the internal Edit's playhead with an AudioProcessor, for use in plugins.
class ExternalPlugin
struct FadeInOutEffect
class FadeInOutNode
A Node that fades in and out given time regions.
struct FallbackReader
struct FileDragList
class FloatAudioFormat
A raw, proprietary, simple floating point format used for freeze files, etc.
class FolderTrack
class FourOscPlugin
class FreezePointPlugin
class GrooveTemplate
class GrooveTemplateManager
Looks after the list of groove templates.
struct HertzTag
class HostedAudioDeviceInterface
The HostedAudioDeviceInterface allows an application or plugin to pass audio and midi buffers to the engine, rather than the engine directly opening the audio devices.
class HostedMidiInputDeviceNode
A Node that intercepts MIDI from a plugin callback and inserts it in to the playback graph.
class IconProG2
class ImpulseResponsePlugin
ImpulseResponsePlugin that loads an impulse response and applies it the audio stream.
class InputDevice
Represents an input device.
class InputDeviceInstance
An instance of an InputDevice that's available to an Edit.
struct InputProvider
class InsertNode
class InsertPlugin
class InsertSendNode
The send node picks up audio/MIDI data from the InsertPlugin and then its output will be sent to the corresponding OutputDevice.
struct InvertEffect
struct KeyResult
class LambdaSelectableListener
A SelectableListener that safely handles listener to a Selectable and uses a lambda for its callback.
class LambdaTimer
class LambdaValueTreeAllEventListener
class LAMEManager
Manages the LAME location property and an AudioFormat if the LAME encoder is provided.
class LatencyPlugin
A test plugin that introduces latency to the incoming signal.
class LauncherClipPlaybackHandle
class LaunchQuantisation
Represents a launch quantisation.
class LevelMeasurer
Monitors the levels of buffers that are passed in, and keeps peak values, overloads, etc., for display in a level meter component.
class LevelMeasurerProcessingNode
A Node that introduces latency to balance the latency at the root Node and its position in the graph.
class LevelMeasuringNode
A Node that passes its incoming audio and MIDI through a LevelMeasurer.
class LevelMeterPlugin
class LFOModifier
class LinEnvelope
struct LiveClipLevel
Provides a thread-safe way to share a clip's levels with an audio engine without worrying about the Clip being deleted from underneath you.
class LiveMidiInjectingNode
A Node that injects MIDI message in to the stream, for keyboard key entry, note previews and MIDI step entry etc.
class LiveMidiOutputNode
A Node that calls the listeners of an AudioTrack with any incoming MIDI.
class LoopInfo
Holds tempo/beat information about an audio file.
class LoopingMidiNode
A Node that plays MIDI data from a MidiMessageSequence, at a specific MIDI channel.
class LowPassPlugin
class MackieC4
class MackieMCU
class MackieXT
class MacroParameter
A MacroParameter is an AutomatableParameter which is a collection of Mappings.
class MacroParameterElement
Base class for elements which can contain macro parameters.
class MacroParameterList
struct MakeMonoEffect
class MarkerClip
class MarkerManager
struct MarkerSetting
class MarkerTrack
class MasterTrack
A track to represent the master plugins.
class MelodyneFileReader
class MelodyneNode
Plays back a Melodyne plugin.
struct MemoryMappedFileReader
FallbackReader that wraps a MemoryMappedFile which usually improves read speeds.
class MessageThreadCallback
Calls a function on the message thread checking a calling thread for an exit signal.
class MidiAssignable
Base class for things that can be assigned to external control surfaces, not plugin paramters.
struct MidiChannel
Represents a MIDI channel 1-16, and also contains extra ID bits to encode info about the event's origin.
class MidiClip
class MidiCompManager
class MidiControllerEvent
struct MidiExpression
struct MidiID
class MidiInputDevice
class MidiInputDeviceNode
A Node that intercepts incoming live MIDI and inserts it in to the playback graph.
class MidiLearnState
Manages the Midi learn state and Listener interface to notify subclasses when the state changes.
class MidiList
struct MidiMessageArray
struct MidiMessageWithSource
class MidiModifierPlugin
class MidiNode
A Node that plays MIDI data from a MidiMessageSequence, at a specific MIDI channel.
class MidiNote
class MidiNoteDispatcher
class MidiOutputDevice
class MidiOutputDeviceInstance
class MidiOutputDeviceInstanceInjectingNode
A Node that injects the MIDI buffer of its input to the MidiOutputDevice.
class MidiPatchBayPlugin
class MidiProgramManager
class MidiSysexEvent
class MIDITrackerModifier
struct Modifier
Bass class for parameter Modifiers.
class ModifierList
Holds a list of Modifiers that have been added to a Track.
class ModifierNode
Node for processing a Modifier.
struct ModifierTimer
Base class for objects which need to know about the global Edit time every block.
struct MonotonicBeat
struct MonotonicBeatRange
class MouseHoverDetector
struct MPEStartTrimmer
If you need to play back MPE data from a point after the data starts, it's important to reconstruct the expression values immediately preceding the last note-on, then the note on, then the last expression values before the trim point.
class MultiThreadedNodePlayer
Plays back a Node with PlayHeadState and ProcessState.
class MultiVoiceOscillator
class NodeRenderContext
Holds the state of an audio render procedure so it can be rendered in blocks.
struct NormaliseEffect
class NovationRemoteSl
struct OldEditConversion
Logic for reading legacy tracktion edit files.
class Oscillator
class OutputDevice
Base class for audio or midi output devices, to which a track's output can be sent.
class OutputDeviceInstance
class ParameterChangeHandler
Manages a set of AutomatableParameters for an Edit and notifies controllers and registered listeners when they change.
class ParameterControlMappings
Controls the set of midi-controller-to-parameter mappings.
class ParameterisableDragDropSource
struct ParameterSetting
class PatchBayPlugin
class PatternGenerator
class PhaserPlugin
class PhysicalMidiInputDevice
struct Pitch
class PitchSequence
class PitchSetting
struct PitchShiftEffect
class PitchShiftPlugin
class PlayHeadPositionNode
A Node that calculates a position to show visually what time is currently being processed by the graph based on its internal latency.
class Plugin
class PluginCache
struct PluginComponent
Components that represent a Plugin should inherit from this to ensure they are correctly notified when their colour changes e.g.
struct PluginCreationInfo
struct PluginEffect
struct PluginInitialisationInfo
Passed into Plugins when they are being initialised, to give them useful contextual information that they may need.
class PluginList
Holds a sequence of plugins.
class PluginManager
class PluginNode
Node for processing a plugin.
struct PluginRenderContext
The context passed to plugin render methods to provide it with buffers to fill.
struct PluginScanHelpers
struct PluginWetDryAutomatableParam
specialised AutomatableParameter for wet/dry.
struct PluginWindowState
struct ProcessState
Holds the state of a process call.
class Project
A tracktion project.
class ProjectItem
Represents a file-based resource that is used in a project.
class ProjectItemID
An ID representing one of the items in a Project.
class ProjectManager
class ProjectSearchIndex
class PropertyStorage
Create a subclass of PropertyStorage to customize how settings are saved and recalled.
class QuantisationType
struct RackConnection
class RackInstance
class RackInstanceNode
Sends an input Node to a Rack bus handling the channel mapping and channel gain levels.
class RackNodePlayer
Simple processor for a Node which uses an InputProvider to pass input in to the graph.
class RackReturnNode
Sends an input Node to a Rack bus handling the channel mapping and channel gain levels.
class RackType
class RackTypeList
struct Ramp
A ramp which goes between 0 and 1 over a set duration.
class RandomModifier
class RecordingThumbnailManager
Holds a pool of Thumbnails that are populated whilst recording.
class ReferenceCountedValueTree
Holds a ValueTree as a ReferenceCountedObject.
class ReferencedMaterialList
A list of all the source files needed by an edit (or a section of an edit).
class RemoteSLCompact
class RenderManager
Manages a set of reference counted render jobs and can be used to retrieve matching jobs or create new ones.
class RenderOptions
Represents a set of user properties used to control a render operation, using a ValueTree to hold them so that they can be saved and reloaded.
class ReverbPlugin
struct ReverseEffect
class ReverseRenderJob
class SafeScopedListener
Manages adding and removing listeners in an RAII way so you don't forget to unregister a listener.
class SafeSelectable
Holds a pointer to some type of Selectable, which automatically becomes null if the selectable is deleted.
class SampleFader
class SamplerPlugin
class Scale
class Scene
A Scene is a collection of ClipSlots across tracks.
class SceneList
Represents the Scenes in an Edit.
class SceneWatcher
Notifies UI components of changes to the scenes and clips.
struct ScopedCpuMeter
struct ScopedDirectoryDeleter
class ScopedListener
Manages adding and removing listeners in an RAII way so you don't forget to unregister a listener.
struct ScopedPluginUnloadInhibitor
class ScopedSteadyLoad
class ScopedWaitCursor
Shows and hides the mouse wait cursor where appropriate.
struct ScreenSaverDefeater
As long as at least one of these objects exists, the screensaver will be disabled.
class SearchOperation
class Selectable
Base class for things that can be selected, and whose properties can appear in the properties panel.
class SelectableClass
Represents a type of object that can be selected.
class SelectableClassWithPan
class SelectableClassWithVolume
struct SelectableList
A list of Selectables, similar to a juce::Array but contains a cached list of the SelectableClasses for each entry.
class SelectableListener
class SelectedMidiEvents
Represents a set of selected MIDI notes.
class SelectionManager
Manages a list of items that are currently selected.
class SharedLevelMeasurer
A shared level measurer that can be used by several threads to provide a total output level.
class SharedLevelMeasuringNode
Applies a SharedLevelMeter to the audio passing through this node.
class SharedTimer
class SimpleLFO
class SlotControlNode
class SmartThumbnail
SmartThumnail automatically tracks changes to an AudioFile and will update its cache if the file changes.
class SoftwareMidiOutputDevice
Create a software midi port on macOS.
struct SortedValueTreeObjectList
class SourceFileReference
This class wraps a string that is generally held in a 'source' property, and which is a reference to some sort of file, either in the form of a local filename or as a project ID that can be resolved.
struct SpeedFadeDescription
Describes the time and type of the speed fade in/outs.
class SpeedRampWaveNode
An Node that plays back a wave file.
struct Spline
An interpolated spline curve, used by the EQ to draw its response graph.
class StepClip
class StepModifier
struct StepVolumeEffect
struct StopwatchTimer
struct SyncPoint
Holds a reference sample position and the Edit time and beat that it corresponds to.
struct SyncRange
class TempoDetect
Uses the SoundTouch BPMDetect class to guess the tempo of some audio.
class TemporaryFileManager
Holds info about where temp files should go, and tidies up old ones when needed.
class TempoSequence
Holds a list of TempoSetting objects, to form a sequence of tempo changes.
class TempoSetting
A tempo value, as used in a TempoSequence.
class TempoTrack
A track to represent the "global" items such as tempo, key changes etc.
class TextPlugin
class ThreadPoolJobWithProgress
struct TimecodeDisplayFormat
A timecode display mode, e.g.
struct TimecodeDisplayIterator
Iterates along a timeline for drawing things like the ticks on the timebar.
class TimecodeDuration
Stores a duration in both beats and seconds.
struct TimecodeSnapType
A snap mode, e.g.
class TimedMutingNode
A Node that mutes its input at specific time ranges.
class TimeSigSetting
class TimeStretcher
Handles time/pitch stretching using various supported libraries.
class TimeStretchingWaveNode
Node that reads from a file node and timestretches its output.
class ToneGeneratorPlugin
class Track
Base class for tracks which contain clips and plugins and can be added to Edit[s].
struct TrackAutomationSection
Holds a reference to a section of automation for a given Track.
class TrackCompManager
struct TrackInsertPoint
Defines the place to insert Track[s].
class TrackItem
Base class for EditItems that live in a Track, e.g.
struct TrackList
An iterable list of Track[s] that live either in an Edit or as subtracks of a Track.
class TrackMidiInputDeviceNode
A Node that takes MIDI from the output of a track and sends it to its corresponding InputDevice.
class TrackMuteState
Holds the state of a Track and if its contents/plugins should be played or not.
class TrackMutingNode
A Node that handles muting/soloing of its input node, according to the audibility of a track.
class TrackOutput
Represents the destination output device(s) for a track.
struct TrackSection
Defines a time raneg sectin of a Track.
class TracktionArchiveFile
class TracktionEngineNode
Base class for Nodes that provides information about the current process call.
class TracktionNodePlayer
Plays back a Node with PlayHeadState and ProcessState.
class TrackWaveInputDeviceNode
A Node that takes audio from the output of a track and sends it to its corresponding InputDevice.
struct TransparentToMouseInTrackItemComp
class TransportControl
Controls the transport of an Edit's playback.
class TranzportControlSurface
class UIBehaviour
Create a subclass of UIBehaviour to custom UI elements created by the engine.
class ValueSmoother
Smooths a value between 0 and 1 at a constant rate.
struct ValueTreeAllEventListener
struct ValueTreeComparator
class ValueTreeObjectList
class ValueTreePropertyChangedListener
class VCAPlugin
The VCA plugin sits on a folder track to control the overall level of all the volume/pan plugins in its child tracks.
class VirtualMidiInputDevice
class VolumeAndPanPlugin
The built-in Tracktion volume/pan plugin.
struct VolumeEffect
class VSTXML
struct WarpMarker
A WarpMarker is a point that maps from a linear "source" time to a "warped" time.
struct WarpPoint
struct WarpTimeEffect
class WarpTimeFactory
A WarpTimeFactory manages WarpTimeManagers for Clips living in an Edit.
class WarpTimeManager
A WarpTimeManager contains a list of WarpMarkers and some source material and maps times from a linear "view" time to a "wapred" source time.
class WarpTimeRenderJob
class WaveAudioClip
An audio clip that uses an audio file as its source.
class WaveCompManager
struct WaveDeviceDescription
Describes a WaveDevice from which the WaveOutputDevice and WaveInputDevice lists will be built.
class WaveInputDevice
A (virtual) audio input device.
class WaveInputDeviceNode
A Node that intercepts incoming live audio and inserts it in to the playback graph.
class WaveInputRecordingThread
class WaveNode
An Node that plays back a wave file.
class WaveNodeRealTime
An Node that plays back a wave file.
class WaveOutputDevice
A (virtual) audio output device.
class WaveOutputDeviceInstance
Concepts
concept WeakReferenceable
Typedefs
using EditDuration = std::variant< TimeDuration, BeatDuration >
Alias for a duration.
using EditTime = EditPosition
Alias provided for compatibility, may be removed in future.
using WarpMap = std::vector< WarpPoint >
template<typename Type , typename Constrainer = DummyConstrainer<Type>>
using AtomicWrapperRelaxed = AtomicWrapper< Type, Constrainer, std::memory_order_relaxed, std::memory_order_relaxed >
template<typename Type , typename Constrainer = DummyConstrainer<Type>>
using AtomicWrapperAcqRel = AtomicWrapper< Type, Constrainer, std::memory_order_acquire, std::memory_order_release >
using SampleCount = int64_t
using SampleRange = juce::Range< SampleCount >
using HashCode = int64_t
using MPESourceID = uint32_t
Enumerations
enum class DeleteExistingClips { no , yes }
Determines behaviour for overwriting clips.
enum class CloseGap { no , yes }
An enum to specify if gaps deleted should be closed or not.
enum class MoveClipAction { moveToEndOfLast , moveToStartOfNext , moveStartToCursor , moveEndToCursor }
Enum to dictate move clip behaviour.
enum class LaunchQType {
none , eightBars , fourBars , twoBars ,
bar , halfT , half , halfD ,
quarterT , quarter , quarterD , eighthT ,
eighth , eighthD , sixteenthT , sixteenth ,
sixteenthD , thirtySecondT , thirtySecond , thirtySecondD ,
sixtyFourthT , sixtyFourth , sixtyFourthD
}
enum class TimecodeType {
millisecs , barsBeats , fps24 , fps25 ,
fps30
}
enum class ResamplingQuality { lagrange , sincFast , sincMedium , sincBest }
Specifies a number of resampling qualities that can be used.
enum PanLaw {
PanLawDefault = -1 , PanLawLinear = 0 , PanLaw2point5dBCenter = 1 , PanLaw3dBCenter = 2 ,
PanLaw4point5dBCenter = 3 , PanLaw6dBCenter = 4
}
All laws have been designed to be equal-power, excluding linear respectively.
enum class AuxPosition { byBus , byPosition }
enum class SettingID {
invalid , addAntiDenormalNoise , audio_device_setup , audiosettings ,
autoFreeze , autoTempoMatch , autoTempoDetect , automapVst ,
automapNative , automapGuids1 , automapGuids2 , cacheSizeSamples ,
compCrossfadeMs , countInMode , clickTrackMidiNoteBig , clickTrackMidiNoteLittle ,
clickTrackSampleSmall , clickTrackSampleBig , crossfadeBlock , cpu ,
customMidiControllers , deadMansPedal , defaultMidiOutDevice , defaultWaveOutDevice ,
defaultMidiInDevice , defaultWaveInDevice , externControlIn , externControlOut ,
externControlNum , externControlMain , externControlShowSelection , externControlSelectionColour ,
externControlEnable , externOscInputPort , externOscOutputPort , externOscOutputAddr ,
filterControlMappingPresets , filterGui , fitClipsToRegion , findExamples ,
freezePoint , hasEnabledMidiDefaultDevs , glideLength , grooveTemplates ,
knownPluginList , knownPluginList64 , lameEncoder , lastClickTrackLevel ,
lastEditRender , lowLatencyBuffer , MCUoneTouchRecord , maxLatency ,
midiin , midiout , midiEditorOctaves , midiProgramManager ,
newMarker , numThreadsForPluginScanning , projectList , projects ,
recentProjects , renameClipRenamesSource , renameMode , renderRecentFilesList ,
resetCursorOnPlay , retrospectiveRecord , reWireEnabled , safeRecord ,
sendControllerOffMessages , simplifyAfterRecording , snapCursor , tempDirectory ,
trackExpansionMode , use64Bit , xFade , xtCount ,
xtIndices , virtualmididevices , virtualmidiin , midiScanIntervalSeconds ,
useSeparateProcessForScanning , useRealtime , wavein , waveout ,
windowsDoubleClick , renderFormat , trackRenderSampRate , trackRenderBits ,
bypassFilters , markedRegion , editClipRenderSampRate , editClipRenderBits ,
editClipRenderDither , editClipRealtime , editClipRenderStereo , editClipRenderNormalise ,
editClipRenderRMS , editClipRenderRMSLevelDb , editClipRenderPeakLevelDb , editClipPassThroughFilters ,
exportFormat , renderOnlySelectedClips , renderOnlyMarked , renderNormalise ,
renderRMS , renderRMSLevelDb , renderPeakLevelDb , renderTrimSilence ,
renderSampRate , renderStereo , renderBits , renderDither ,
quality , addId3Info , realtime , passThroughFilters ,
externControlShowClipSlotSelection , addAcidMetadata
}
A list of settings the engine will get and set.
Functions
juce::Array< KeyResult > determineKeyOfNotes (const juce::Array< MidiNote * > &notes)
AutomationMode getAutomationMode (const AutomatableParameter &)
Looks for the Track this parameter is currently on and returns the AutomationMode for it.
template<typename AssignmentType >
juce::ReferenceCountedArray< AssignmentType > getAssignmentsOfType (const AutomatableParameter &ap)
Returns all the Assignments of a specific type.
template<typename ModifierType >
juce::Array< ModifierType * > getModifiersOfType (const AutomatableParameter &ap)
Returns all the modifers in use of a specific type.
template<typename AssignmentType , typename ModifierSourceType , typename EditType >
juce::ReferenceCountedArray< AssignmentType > getAssignmentsForSource (EditType &edit, const ModifierSourceType &source)
Iterates an Edit looking for all parameters that assigned to a given parameter.
AutomatableParameter::ModifierSource * getSourceForAssignment (const AutomatableParameter::ModifierAssignment &)
Iterates an Edit looking for the source of this assignment.
juce::ReferenceCountedArray< AutomatableParameter > getAllParametersBeingModifiedBy (Edit &, AutomatableParameter::ModifierSource &)
Iterates an Edit looking for all parameters that are being modified by the given ModifierSource.
AutomatableParameter * getParameter (AutomatableParameter::ModifierAssignment &)
Iterates an Edit looking for the parameter that this ModifierAssignment has been made from.
int getIntParamValue (const AutomatableParameter &ap)
Returns an int version of an AutomatableParameter.
bool getBoolParamValue (const AutomatableParameter &ap)
Returns a bool version of an AutomatableParameter.
template<typename Type >
Type getTypedParamValue (const AutomatableParameter &ap)
Returns an int version of an AutomatableParameter cast to a enum type.
MacroParameter::Ptr getMacroParameterForID (Edit &, EditItemID)
Searched the Edit for a MacroParameter with this ID.
juce::ReferenceCountedObjectPtr< Plugin > getOwnerPlugin (MacroParameterList *)
If this MacroParameterList belongs to an Plugin, this will return it.
template<typename ModifierType >
juce::ReferenceCountedArray< ModifierType > getModifiersOfType (const ModifierList &ml)
Returns the modifers of a specific type.
Modifier::Ptr findModifierForID (ModifierList &, EditItemID)
Returns a Modifier if it can be found in the list.
Clip * findClipForState (ClipOwner &, const juce::ValueTree &)
Returns a clip with the given state if the ClipOwner contains it.
Clip * findClipForID (ClipOwner &, EditItemID)
Returns a clip with the given ID if the ClipOwner contains it.
Clip * insertClipWithState (ClipOwner &, juce::ValueTree)
Inserts a clip with the given state in to the ClipOwner's clip list.
Clip * insertClipWithState (ClipOwner &, const juce::ValueTree &stateToUse, const juce::String &name, TrackItem::Type, ClipPosition, DeleteExistingClips, bool allowSpottingAdjustment)
Inserts a clip with the given state in to the ClipOwner's clip list.
Clip * insertNewClip (ClipOwner &, TrackItem::Type, EditTimeRange)
Inserts a new clip with the given type and a default name.
Clip * insertNewClip (ClipOwner &, TrackItem::Type, const juce::String &name, EditTimeRange)
Inserts a new clip with the given type and name.
Clip * insertNewClip (ClipOwner &, TrackItem::Type, const juce::String &name, ClipPosition)
Inserts a new clip with the given type and name.
juce::ReferenceCountedObjectPtr< WaveAudioClip > insertWaveClip (ClipOwner &, const juce::String &name, const juce::File &sourceFile, ClipPosition, DeleteExistingClips)
Inserts a new WaveAudioClip into the ClipOwner's clip list.
juce::ReferenceCountedObjectPtr< WaveAudioClip > insertWaveClip (ClipOwner &, const juce::String &name, ProjectItemID sourceID, ClipPosition, DeleteExistingClips)
Inserts a new WaveAudioClip into the ClipOwner's clip list.
juce::ReferenceCountedObjectPtr< MidiClip > insertMIDIClip (ClipOwner &, const juce::String &name, TimeRange)
Inserts a new MidiClip into the ClipOwner's clip list.
juce::ReferenceCountedObjectPtr< MidiClip > insertMIDIClip (ClipOwner &, TimeRange)
Inserts a new MidiClip into the ClipOwner's clip list.
juce::ReferenceCountedObjectPtr< EditClip > insertEditClip (ClipOwner &, TimeRange, ProjectItemID)
Inserts a new EditClip into the ClipOwner's clip list.
juce::Array< Clip * > deleteRegion (ClipOwner &, TimeRange)
Removes a region of a ClipOwner and returns any newly created clips.
juce::Array< Clip * > deleteRegion (Clip &, TimeRange)
Removes a region of a clip and returns any newly created clips.
juce::Array< Clip * > split (ClipOwner &, TimePosition)
Splits the given clp owner at the time and returns any newly created clips.
Clip * split (Clip &, TimePosition)
Splits the given clip at the time and returns the newly created clip.
bool containsAnyMIDIClips (const ClipOwner &)
Returns true if the clip owner contains any MIDI clips.
template<typename ClipType >
juce::Array< ClipType * > getClipsOfType (const ClipOwner &)
Returns the subclips of the given type.
template<typename ClipType >
juce::Array< ClipType * > getClipsOfTypeRecursive (const ClipOwner &)
Returns the subclips of the given type, if any clips contain other clips, this will also return those.
bool isMasterTrack (const Track &)
Returns true if this is a MasterTrack.
bool isTempoTrack (const Track &)
Returns true if this is a TempoTrack.
bool isAutomationTrack (const Track &)
Returns true if this is an AutomationTrack.
bool isAudioTrack (const Track &)
Returns true if this is an AudioTrack.
bool isFolderTrack (const Track &)
Returns true if this is a FolderTrack.
bool isMarkerTrack (const Track &)
Returns true if this is a MarkerTrack.
bool isChordTrack (const Track &)
Returns true if this is a ChordTrack.
bool isArrangerTrack (const Track &)
Returns true if this is an ArrangerTrack.
bool isAudioTrack (const ClipOwner &)
Returns true if this is an AudioTrack.
bool isFolderTrack (const ClipOwner &)
Returns true if this is a FolderTrack.
bool isMarkerTrack (const ClipOwner &)
Returns true if this is a MarkerTrack.
bool isChordTrack (const ClipOwner &)
Returns true if this is a ChordTrack.
bool isArrangerTrack (const ClipOwner &)
Returns true if this is an ArrangerTrack.
bool canContainMIDI (const ClipOwner &)
Returns true if this Track can contain MidiClip[s].
bool canContainAudio (const ClipOwner &)
Returns true if this Track can contain WaveAudioClip[s].
bool isMovable (const Track &)
Returns true if this Track is movable.
bool isOnTop (const Track &)
Returns true if this a global Track and should be on top of others.
void mergeInMidiSequence (MidiClip &, juce::MidiMessageSequence, TimeDuration offsetToApply, MidiList::NoteAutomationType)
Copies a zero-time origin based MIDI sequence in to a MidiClip.
std::unique_ptr< Edit > loadEditFromFile (Engine &, const juce::File &, Edit::EditRole role=Edit::EditRole::forEditing)
Loads an edit from a file, ready for playback / editing.
std::unique_ptr< Edit > loadEditFromState (Engine &, const juce::ValueTree &, Edit::EditRole role=Edit::EditRole::forEditing)
Loads an edit from a ValueTree, ready for playback / editing.
std::unique_ptr< Edit > createEmptyEdit (Engine &, const juce::File &)
Creates a new edit for a file, ready for playback / editing.
juce::ValueTree loadEditFromProjectManager (ProjectManager &, ProjectItemID)
Uses the ProjectManager to find an Edit file and load it as a ValueTree.
std::unique_ptr< Edit > loadEditForExamining (ProjectManager &, ProjectItemID, Edit::EditRole role=Edit::EditRole::forExamining, Edit::LoadContext *=nullptr)
Uses the ProjectManager to find an Edit file and open it.
juce::ValueTree loadEditFromFile (Engine &, const juce::File &, ProjectItemID)
Legacy, will be deprecated soon.
juce::ValueTree createEmptyEdit (Engine &)
Legacy, will be deprecated soon.
juce::ValueTree updateLegacyEdit (const juce::ValueTree &)
Converts old edit formats to the latest structure.
void updateLegacyEdit (juce::XmlElement &editXML)
Converts old edit formats to the latest structure.
Project::Ptr getProjectForEdit (const Edit &)
Tries to find the project that contains this edit (but may return nullptr!)
ProjectItem::Ptr getProjectItemForEdit (const Edit &)
Tries to find the project item that refers to this edit (but may return nullptr!)
juce::File getEditFileFromProjectManager (Edit &)
Uses the ProjectManager to look up the file for an Edit.
bool referencesProjectItem (Edit &, ProjectItemID)
Returns true if the ProjectItemID is being used for any of the Edit's elements.
void insertSpaceIntoEdit (Edit &, TimeRange timeRangeToInsert)
Inserts blank space in to an Edit, splitting clips if necessary.
void insertSpaceIntoEditFromBeatRange (Edit &, BeatRange)
Inserts a number of blank beats in to the Edit.
EditItem * findEditItemForID (Edit &, EditItemID)
Looks for an item in an edit with a given ID.
juce::Array< Track * > getAllTracks (const Edit &)
Returns all the tracks in an Edit.
juce::Array< Track * > getTopLevelTracks (const Edit &)
Returns all of the non-foldered tracks in an Edit.
template<typename TrackType >
juce::Array< TrackType * > getTracksOfType (const Edit &, bool recursive)
Returns the tracks of a given type in an Edit.
juce::Array< AudioTrack * > getAudioTracks (const Edit &)
Returns all the AudioTracks in an Edit.
juce::Array< ClipTrack * > getClipTracks (const Edit &)
Returns all the ClipTracks in an Edit.
int getTotalNumTracks (const Edit &)
Returns the total number of Tracks in an Edit.
Track * findTrackForID (const Edit &, EditItemID)
Returns the Track with a given ID if contained in the Edit.
AudioTrack * findAudioTrackForID (const Edit &, EditItemID)
Returns the AudioTrack with a given ID if contained in the Edit.
juce::Array< Track * > findTracksForIDs (const Edit &, const juce::Array< EditItemID > &)
Returns the Tracks for the given IDs in the Edit.
Track * findTrackForState (const Edit &, const juce::ValueTree &)
Returns the Track with a given state if contained in the Edit.
AudioTrack * getFirstAudioTrack (const Edit &)
Returns the first audio track in an Edit.
juce::Array< Track * > findAllTracksContainingSelectedItems (const SelectableList &)
Returns all the tracks containing the selected tracks or TrackItems.
ClipTrack * findFirstClipTrackFromSelection (const SelectableList &)
Returns the first ClipTrack from the selected tracks or clips.
bool containsTrack (const Edit &, const Track &)
Returns true if the Edit contains this Track.
TrackOutput * getTrackOutput (Track &)
Returns the TrackOutput if the given track has one.
juce::BigInteger toBitSet (const juce::Array< Track * > &)
Returns the set of tracks as a BigInteger with each bit corresponding to the array of all tracks in an Edit.
juce::Array< Track * > toTrackArray (Edit &, const juce::BigInteger &)
Returns an Array of Track[s] corresponding to the set bits of all tracks in an Edit.
template<typename TrackItemType >
juce::Array< TrackItemType * > getTrackItemsOfType (const Track &)
ClipOwner * findClipOwnerForID (const Edit &, EditItemID)
Returns the ClipOwner with a given ID if it can be found in the Edit.
ClipSlot * findClipSlotForID (const Edit &, EditItemID)
Returns the ClipSlot for the given ID.
int findClipSlotIndex (ClipSlot &)
Returns the index of the ClipSlot in the list it is owned by.
Clip * findClipForID (const Edit &, EditItemID)
Returns the Clip with a given ID if contained in the Edit.
Clip * findClipForState (const Edit &, const juce::ValueTree &)
Returns the Clip for a given state if contained in the Edit.
bool containsClip (const Edit &, Clip *)
Returns true if an Edit contains a given clip.
Clip::Ptr duplicateClip (const Clip &)
Creates a unique copy of this clip with a new EditItemID.
void visitAllTrackItems (const Edit &, std::function< bool(TrackItem &)>)
Calls a function for all TrackItems in an Edit.
TimeRange getTimeRangeForSelectedItems (const SelectableList &)
Returns the time range covered by the given items.
void deleteRegionOfTracks (Edit &, TimeRange rangeToDelete, bool onlySelectedTracks, CloseGap, SelectionManager *)
Deletes a time range of an Edit, optionally closing the gap.
void deleteRegionOfClip (Clip &, TimeRange rangeToDelete)
Deletes a time range of a Clip.
void deleteRegionOfSelectedClips (SelectionManager &, TimeRange rangeToDelete, CloseGap, bool moveAllSubsequentClipsOnTrack)
Deletes a time range of a Clip selection, optionally closing the gap.
SelectableList splitClips (const SelectableList &clips, TimePosition time)
Splits the clips at a given time.
void moveSelectedClips (const SelectableList &, Edit &, MoveClipAction mode, bool alsoMoveAutomation)
Moves the selected clips within their track.
SelectableList getClipSelectionWithCollectionClipContents (const SelectableList &)
Returns a list of clips.
juce::Array< ClipEffect * > getAllClipEffects (Edit &edit)
Returns all clip effects.
MidiNote * findNoteForState (const Edit &, const juce::ValueTree &)
Returns the MidiNote with a given state.
juce::Result mergeMidiClips (juce::Array< MidiClip * >, SelectionManager *sm=nullptr)
Merges a set of MIDI clips in to one new one.
juce::OwnedArray< MidiList > readFileToMidiList (juce::File midiFile, bool importAsNoteExpression)
Helper function to read a file to a number of MidiLists.
MidiClip::Ptr createClipFromFile (juce::File midiFile, ClipOwner &, bool importAsNoteExpression)
Helper function to read a MIDI file and create a MidiClip from it.
Plugin::Array getAllPlugins (const Edit &, bool includeMasterVolume)
Returns all the plugins in a given Edit.
Plugin::Ptr findPluginForState (const Edit &, const juce::ValueTree &)
Returns the plugin with given state.
Plugin::Ptr findPluginForID (const Edit &, EditItemID)
Returns the plugin with given EditItemID.
Track * getTrackContainingPlugin (const Edit &, const Plugin *)
Returns the track for the track which the plugin is located on.
bool areAnyPluginsMissing (const Edit &)
Returns true if any plugins couldn't be loaded beacuse their files are missing.
juce::Array< RackInstance * > getRackInstancesInEditForType (const RackType &)
Returns all of the instances of a specific RackType in an Edit.
void muteOrUnmuteAllPlugins (const Edit &)
Toggles the enabled state of all plugins in an Edit.
void midiPanic (Edit &, bool resetPlugins)
Performs a "MIDI panic" on the edit, by sending all-note-off messages directly to all plugins in the edit, and optionally resetting them to kill any reverb tails, etc.
template<typename PluginType >
juce::ReferenceCountedObjectPtr< PluginType > insertNewPlugin (Track &, int index=0)
Adds a new instance of the given plugin to the track's plugin list at the specified index.
juce::Array< AutomatableEditItem * > getAllAutomatableEditItems (const Edit &)
Returns all AutomatableEditItems in an Edit.
void deleteAutomation (const SelectableList &selectedClips)
Deletes the automation covered by the selected clips.
juce::Array< AutomatableParameter::ModifierSource * > getAllModifierSources (const Edit &)
Returns all the ModifierSources in an Edit.
juce::ReferenceCountedArray< Modifier > getAllModifiers (const Edit &)
Returns all the Modifiers in an Edit.
template<typename ModifierType >
ModifierType::Ptr findModifierTypeForID (const Edit &, EditItemID)
Returns the Modifier with a given type and ID.
Modifier::Ptr findModifierForID (const Edit &, EditItemID)
Returns the Modifier with a given ID.
Modifier::Ptr findModifierForID (const RackType &, EditItemID)
Returns the Modifier with a given ID if the RackType contains it.
Track * getTrackContainingModifier (const Edit &, const Modifier::Ptr &)
Returns the Track containing a Modifier.
juce::Array< MacroParameterList * > getAllMacroParameterLists (const Edit &)
Returns all the MacroParameterLists in an Edit.
juce::Array< MacroParameterElement * > getAllMacroParameterElements (const Edit &)
Returns all the MacroParameterElement in an Edit.
InputDeviceInstance::RecordingParameters getDefaultRecordingParameters (const EditPlaybackContext &, TimePosition playStart, TimePosition punchIn)
Returns the default set of recording parameters.
juce::Result prepareAndPunchRecord (InputDeviceInstance &, EditItemID)
Starts an InputDeviceInstance recording to the given target without any count-in etc.
tl::expected< Clip::Array, juce::String > punchOutRecording (InputDeviceInstance &)
If the instance is currently recording, this will stop it and return any created clips or an error message.
bool isRecording (EditPlaybackContext &)
Returns true if any inputs are currently recording.
InputDeviceInstance::Destination * assignTrackAsInput (AudioTrack &destinationTrack, const AudioTrack &sourceTrack, InputDevice::DeviceType)
Creates an InputDeviceInstance::Destination on the destinationTrack from the sourceTrack if possible.
template<typename Type >
requires (std::is_same_v<Type, Edit> || requires (Type t) { t.edit; } || requires (Type t) { t.getEdit(); })
Edit & getEdit (Type &type)
Returns a reference to the Edit if accessible by the given object.
TempoSequence & getTempoSequence (auto &type)
juce::UndoManager & getUndoManager (auto &type)
juce::UndoManager * getUndoManager_p (auto &type)
juce::StringArray getLaunchQTypeChoices ()
Returns a list of quantisation type options in the order of LaunchQType.
std::optional< LaunchQType > launchQTypeFromName (const juce::String &)
Returns a the launch Q from a string returned from getLaunchQTypeChoices().
juce::String getName (LaunchQType)
Retuns the name of a LaunchQType for display purposes.
double toBarFraction (LaunchQType) noexcept
Returns the fraction of a bar to be used for a given rate type.
LaunchQType fromBarFraction (double) noexcept
Returns the fraction of a bar to be used for a given rate type.
BeatPosition getNext (LaunchQType, const TempoSequence &, BeatPosition) noexcept
Returns the next quantised position.
BeatPosition getNext (LaunchQType, const tempo::Sequence &, BeatPosition) noexcept
Returns the next quantised position.
bool operator< (const PitchSetting &p1, const PitchSetting &p2) noexcept
tempo::Sequence::Position createPosition (const TempoSequence &)
Creates a Position to iterate over the given TempoSequence.
BeatPosition toBeats (TimePosition, const TempoSequence &)
Converts a TimePosition to a BeatPosition given a TempoSequence.
BeatPosition toBeats (TimePosition, const tempo::Sequence &)
TimePosition toTime (BeatPosition, const TempoSequence &)
Converts a BeatPosition to a TimePosition given a TempoSequence.
TimePosition toTime (BeatPosition, const tempo::Sequence &)
BeatRange toBeats (TimeRange, const TempoSequence &)
Converts a TimeRange to a BeatRange given a TempoSequence.
BeatRange toBeats (TimeRange, const tempo::Sequence &)
TimeRange toTime (BeatRange, const TempoSequence &)
Converts a BeatRange to a TimeRange given a TempoSequence.
TimeRange toTime (BeatRange, const tempo::Sequence &)
EditPosition toPosition (EditDuration)
Returns the raw value of beats or seconds, only really useful for comparing two EditDurations with the same time base.
double toUnderlying (EditDuration)
Returns the raw value of beats or seconds, only really useful for comparing two EditDurations with the same time base.
bool isZero (EditDuration)
Returns true if the duration is 0 beats or seconds.
bool isGreaterThanZero (EditDuration)
Returns true if the duration is greater than zero beats or seconds.
EditPosition plus (const EditPosition &lhs, const EditDuration &rhs, const TempoSequence &ts)
EditPosition minus (const EditPosition &lhs, const EditDuration &rhs, const TempoSequence &ts)
bool equals (const EditPosition &lhs, const EditPosition &rhs, const TempoSequence &ts)
EditDuration minus (const EditPosition &lhs, const EditPosition &rhs, const TempoSequence &ts)
bool less (const EditPosition &lhs, const EditPosition &rhs, const TempoSequence &ts)
bool greater (const EditPosition &lhs, const EditPosition &rhs, const TempoSequence &ts)
bool lessThanOrEqualTo (const EditPosition &lhs, const EditPosition &rhs, const TempoSequence &ts)
bool greaterThanOrEqualTo (const EditPosition &lhs, const EditPosition &rhs, const TempoSequence &ts)
EditPosition min (const EditPosition &lhs, const EditPosition &rhs, const TempoSequence &ts)
EditPosition max (const EditPosition &lhs, const EditPosition &rhs, const TempoSequence &ts)
EditDuration toDuration (const EditPosition &p)
bool operator== (const EditPositionWithTempoSequence &lhs, const EditPositionWithTempoSequence &rhs)
bool operator< (const EditPositionWithTempoSequence &lhs, const EditPositionWithTempoSequence &rhs)
bool operator<= (const EditPositionWithTempoSequence &lhs, const EditPositionWithTempoSequence &rhs)
bool operator> (const EditPositionWithTempoSequence &lhs, const EditPositionWithTempoSequence &rhs)
bool operator>= (const EditPositionWithTempoSequence &lhs, const EditPositionWithTempoSequence &rhs)
EditDuration operator- (const EditPositionWithTempoSequence &lhs, const EditPositionWithTempoSequence &rhs)
EditPosition operator+ (const EditPositionWithTempoSequence &lhs, const EditDuration &rhs)
EditPosition operator- (const EditPositionWithTempoSequence &lhs, const EditDuration &rhs)
TimePosition toTime (EditPosition, const TempoSequence &)
Converts an EditTime to a TimePosition.
BeatPosition toBeats (EditPosition, const TempoSequence &)
Converts an EditTime to a BeatPosition.
double toUnderlying (EditPosition)
Returns the raw number of seconds or beats.
juce::Range< double > toUnderlying (EditTimeRange)
Returns the raw number of seconds or beats.
bool contains (EditTimeRange, EditPosition, const TempoSequence &)
Returns true if the given position is contained within the given range.
bool containsInclusive (EditTimeRange, EditPosition, const TempoSequence &)
Returns true if the given position is contained within the given closed range.
TimeRange toTime (EditTimeRange, const TempoSequence &)
Converts an EditTimeRange to a TimeRange.
BeatRange toBeats (EditTimeRange, const TempoSequence &)
Converts an EditTimeRange to a BeatRange.
ClipPosition createClipPosition (const TempoSequence &, TimeRange, TimeDuration offset={})
Creates a ClipPosition from either a time or beat range.
ClipPosition createClipPosition (const TempoSequence &, BeatRange, BeatDuration offset={})
Creates a ClipPosition from either a time or beat range.
TimePosition toTime (EditPosition et, const tempo::Sequence &ts)
BeatPosition toBeats (EditPosition et, const tempo::Sequence &ts)
TimeRange toTime (EditTimeRange r, const tempo::Sequence &ts)
BeatRange toBeats (EditTimeRange r, const tempo::Sequence &ts)
int countNumTracks (const juce::ValueTree &)
Returns the number of tracks from this tree recursively.
void moveAutomation (const juce::Array< TrackAutomationSection > &, TimeDuration offset, bool copy)
Moves a set of automation optionally applying an offset and copying the automation (rather than moving it).
template<typename ArrayType >
int findIndexOfNextItemAt (const ArrayType &items, TimePosition time)
Returns the index of the next item after the given time.
template<typename ArrayType >
TimeRange findUnionOfEditTimeRanges (const ArrayType &items)
Returns the the time range that covers all the given TrackItems.
juce::Array< std::pair< AudioTrack *, int > > getTargetTracksAndIndexes (InputDeviceInstance &)
Returns the AudioTracks and their indexes this instance is assigned to.
juce::Array< AudioTrack * > getTargetTracks (InputDeviceInstance &)
Returns the AudioTracks this instance is assigned to.
bool isOnTargetTrack (InputDeviceInstance &, const Track &, int idx)
Returns true if this instance is assigned to the given Track at the given index .
bool isAttached (InputDeviceInstance &)
Returns true if this input is assigned to a target.
juce::Result clearFromTargets (InputDeviceInstance &, juce::UndoManager *)
Removes this instance from all assigned targets.
InputDeviceInstance::Destination * getDestination (InputDeviceInstance &, const Track &track, int index)
Returns the destination if one has been assigned for the given arguments.
InputDeviceInstance::Destination * getDestination (InputDeviceInstance &, const ClipSlot &)
Returns the destination if one has been assigned for the given arguments.
InputDeviceInstance::Destination * getDestination (InputDeviceInstance &, const juce::ValueTree &destinationState)
Returns the destination if one has been assigned for the given arguments.
bool hasErrors (const InputDeviceInstance::PreparedContext &pc)
Returns true if all the targets were fully prepared.
InputDeviceInstance::PreparedContext & append (InputDeviceInstance::PreparedContext &dest, InputDeviceInstance::PreparedContext &&src)
Appends a PreparedContent to another.
std::pair< std::vector< std::unique_ptr< InputDeviceInstance::RecordingContext > >, juce::StringArray > extract (InputDeviceInstance::PreparedContext &&pc)
Splits the PreparedContext in to valid RecordingContexts and an array of error messages.
juce::String createDescriptionOfChannels (const std::vector< ChannelIndex > &)
Creates a String description of the channels.
juce::AudioChannelSet createChannelSet (const std::vector< ChannelIndex > &)
Creates an AudioChannelSet for a list of ChannelIndexes.
juce::AudioChannelSet::ChannelType channelTypeFromAbbreviatedName (const juce::String &)
Returns the ChannelType for an abbreviated name.
juce::AudioChannelSet channelSetFromSpeakerArrangmentString (const juce::String &)
Creates an AudioChannelSet from a list of abbreviated channel names.
std::unique_ptr< tracktion::graph::Node > createNodeForEdit (EditPlaybackContext &, std::atomic< double > &audibleTimeToUpdate, const CreateNodeParams &)
Creates a Node to play back an Edit with live inputs and outputs.
std::unique_ptr< tracktion::graph::Node > createNodeForEdit (Edit &, const CreateNodeParams &)
Creates a Node to render an Edit.
void toStart (TransportControl &, const SelectableList &)
Moves the transport to the start of the selected objects.
void toEnd (TransportControl &, const SelectableList &)
Moves the transport to the end of the selected objects.
void tabBack (TransportControl &)
Moves the transport back to the previous point of interest.
void tabForward (TransportControl &)
Moves the transport forwards to the next point of interest.
void markIn (TransportControl &)
Sets the mark in position to the current transport position.
void markOut (TransportControl &)
Sets the mark out position to the current transport position.
void scrub (TransportControl &, double unitsForwards)
Scrubs back and forth in 'units', where a unit is about 1/50th of the width of the strip window.
void freePlaybackContextIfNotRecording (TransportControl &)
Frees the playback context if no recording is in progress, useful for when an app is minimised.
void float2string (float f, char *text, int len)
void int2string (float i, char *text, int len)
void dB2string (float value, char *text, int maxLen)
std::string getCmajorVersion ()
std::unique_ptr< juce::AudioPluginFormat > createCmajorPatchPluginFormat (Engine &)
bool isCmajorPatchPluginFormat (const juce::PluginDescription &)
bool isCmajorPatchPluginFormat (const juce::String &formatName)
juce::String getCmajorPatchPluginFormatName ()
juce::String getCmajorPatchCompileError (Plugin &)
juce::String createIdentifierString (const juce::PluginDescription &)
SearchOperation * createSearchForKeywords (const juce::String &keywords)
Turns a keyword string into a search condition tree.
AudioTrack * getOrInsertAudioTrackNearestIndex (Edit &edit, int trackIndex)
template<typename SelectableType >
SafeSelectable< SelectableType > makeSafeRef (SelectableType &selectable)
Creates a SafeSelectable for a given selectable object.
template<typename Iterable >
auto makeSafeVector (const Iterable &selectables) -> std::vector< SafeSelectable< typename std::remove_reference< decltype(*selectables[0])>::type > >
Creates a std::vector<SafeSelectable<Something>> for a given juce::Array of selectable objects.
template<typename WeakReferenceable >
juce::WeakReference< WeakReferenceable > makeWeakRef (WeakReferenceable &object)
Creates a juce::WeakReference for an object.
template<typename WeakReferenceable >
juce::WeakReference< WeakReferenceable > makeWeakRef (WeakReferenceable *object)
Creates a juce::WeakReference for an object pointer (which may be null)
bool callBlocking (std::function< void()> f)
Calls a function on the message thread by posting a message and then waiting for it to be delivered.
bool callBlockingCatching (std::function< void()> f) noexcept
The same as callBlocking expect the exception is caught and ignored.
float dbToGain (float db) noexcept
float gainToDb (float gain) noexcept
juce::String gainToDbString (float gain, float infLevel=-96.0f, int decPlaces=2)
float dbStringToDb (const juce::String &dbStr)
float dbStringToGain (const juce::String &dbStr)
juce::String getPanString (float pan)
juce::String getSemitonesAsString (double semitones)
template<typename FloatType >
FloatType midiNoteToFrequency (FloatType midiNote)
template<typename FloatType >
FloatType frequencyToMidiNote (FloatType freq)
void sanitiseValues (juce::AudioBuffer< float > &, int startSample, int numSamples, float maxAbsValue, float minAbsThreshold=1.0f/262144.0f)
void addAntiDenormalisationNoise (juce::AudioBuffer< float > &, int start, int numSamples) noexcept
void resetFP () noexcept
bool hasFloatingPointDenormaliseOccurred () noexcept
void zeroDenormalisedValuesIfNeeded (juce::AudioBuffer< float > &) noexcept
bool isAudioDataAlmostSilent (const float *data, int num)
float getAudioDataMagnitude (const float *data, int num)
void convertIntsToFloats (juce::AudioBuffer< float > &)
void convertFloatsToInts (juce::AudioBuffer< float > &)
void yieldGUIThread () noexcept
template<typename SampleType >
choc::buffer::BufferView< SampleType, choc::buffer::SeparateChannelLayout > toBufferView (juce::AudioBuffer< SampleType > &buffer)
Converts a juce::AudioBuffer<SampleType> to a choc::buffer::BufferView.
PanLaw getDefaultPanLaw () noexcept
void setDefaultPanLaw (PanLaw)
juce::StringArray getPanLawChoices (bool includeDefault) noexcept
float decibelsToVolumeFaderPosition (float dB) noexcept
float volumeFaderPositionToDB (float position) noexcept
float volumeFaderPositionToGain (float position) noexcept
float gainToVolumeFaderPosition (float gain) noexcept
void getGainsFromVolumeFaderPositionAndPan (float volSliderPos, float pan, PanLaw lawToUse, float &leftGain, float &rightGain) noexcept
void clearChannels (juce::AudioBuffer< float > &buffer, int startChannel, int endChannel=-1, int startSample=0, int endSample=-1)
juce::AudioPlayHead::CurrentPositionInfo getCurrentPositionInfo (Edit &)
Converts an Edit's internal transport information to a juce::AudioPlayHead::CurrentPositionInfo.
void synchroniseEditPosition (Edit &, const juce::AudioPlayHead::CurrentPositionInfo &)
Syncs an Edit's transport and tempo sequence to a juce AudioPlayHead.
bool isMidiFile (const juce::File &)
bool isTracktionEditFile (const juce::File &)
bool isTracktionArchiveFile (const juce::File &)
bool isTracktionProjectFile (const juce::File &)
bool isTracktionPresetFile (const juce::File &)
juce::File getNonExistentSiblingWithIncrementedNumberSuffix (const juce::File &, bool addHashSymbol)
void addSortedListToMenu (juce::PopupMenu &m, juce::StringArray names, int startID)
juce::AffineTransform getScaleAroundCentre (juce::Rectangle< float > r, float numPixels)
void moveXMLAttributeToStart (juce::XmlElement &xml, juce::StringRef att)
template<typename Vector , typename Predicate >
bool removeIf (Vector &v, Predicate &&pred)
template<typename FloatingPointType >
bool almostEqual (FloatingPointType firstValue, FloatingPointType secondValue, FloatingPointType precision=(FloatingPointType) 0.00001)
Checks to see if two values are equal within a given precision.
MonotonicBeatRange getMonotonicBeatRange (const SyncRange &)
BeatRange getBeatRange (const SyncRange &)
int64_t getNumSamples (const SyncRange &)
template<typename VarType >
void convertPropertyToType (juce::ValueTree &v, const juce::Identifier &id)
Ensures a property is a given type which can avoid having to parse a string every time it is read after loading from XML.
template<typename Type >
bool matchesAnyOf (const Type &needle, const std::initializer_list< Type > &haystack)
Returns true if the needle is found in the haystack.
template<typename Type , typename UnaryFunction >
void forEachItem (const juce::Array< Type * > &items, const UnaryFunction &fn)
Calls a function object on each item in an array.
template<typename... Others>
void addValueTreeProperties (juce::ValueTree &v, const juce::Identifier &name, const juce::var &value, Others &&... others)
template<typename... Properties>
juce::ValueTree createValueTree (const juce::Identifier &name, Properties &&... properties)
juce::Array< juce::ValueTree > & removeInvalidValueTrees (juce::Array< juce::ValueTree > &trees)
Strips out any invalid trees from the array.
juce::Array< juce::ValueTree > getTreesOfType (const juce::Array< juce::ValueTree > &trees, const juce::Identifier &type)
Returns a new array with any trees without the given type removed.
void getChildTreesRecursive (juce::Array< juce::ValueTree > &result, const juce::ValueTree &tree)
void renamePropertyRecursive (juce::ValueTree &tree, const juce::Identifier &oldName, const juce::Identifier &newName, juce::UndoManager *um)
juce::ValueTree getOrCreateChildWithTypeAndProperty (juce::ValueTree &tree, const juce::Identifier &type, const juce::Identifier &property, const juce::var &propertyValue, juce::UndoManager *undoManager)
Looks for a chile with the given name and property, if one doesn't exist, creates it.
Variables
const char *const projectFileSuffix = ".tracktion"
const char *const editFileSuffix = ".tracktionedit"
const char *const legacyEditFileSuffix = ".trkedit"
const char *const archiveFileSuffix = ".trkarch"
const char *const soundFileWildCard = "*.wav;*.aiff;*.aif;*.ogg;*.mp3;*.flac;*.au;*.voc;*.caf;*.w64;*.rx2;*.rcy;*.rex;*.wfaf"
const char *const soundFileAndMidiWildCard = "*.wav;*.aiff;*.aif;*.ogg;*.mp3;*.mid;*.midi;*.flac;*.au;*.voc;*.caf;*.w64;*.rx2;*.rcy;*.rex;*.wfaf"
const char *const midiFileWildCard = "*.midi;*.mid"
const char *const soundFileExtensions = "wav;aiff;aif;ogg;mp3;flac;au;voc;caf;w64;rx2;rcy;rex;wfaf"
const char *const soundFileAndMidiExtensions = "wav;aiff;aif;ogg;mp3;flac;au;voc;caf;w64;rx2;rcy;rex;wfaf;midi;mid"
const char *const midiFileExtensions = "midi;mid"
const char *const keyMapWildCard = "*.tracktionkeys"
const char *const keyMapSuffix = ".tracktionkeys"
const char *const customControllerFileSuffix = ".trkctrlr"
const char *const customProgramSetWildcard = "*.trkmidi;*.midnam"
const char *const customProgramSetFileSuffix = ".trkmidi"
const char *const presetFileSuffix = ".trkpreset"
const char *const rackFileSuffix = ".trkrack"
const char *const scriptFileSuffix = ".tracktionscript"
const char *const grooveTemplateSuffix = ".trkgroove"
const char *const grooveTemplateWildCard = "*.trkgroove"
constexpr HertzTag HertzTag_t {}
Typedef Documentation
EditDuration
using tracktion::engine::EditDuration = typedef std::variant<TimeDuration, BeatDuration>
Alias for a duration.
Note this isn't a proper type like EditPosition as a duration by itself doesn't make sense for beats, you can't convert to/from Time without a position as well. So most of the time you'd specify this as an EditRange.
EditTime
using tracktion::engine::EditTime = typedef EditPosition
Alias provided for compatibility, may be removed in future.
WarpMap
using tracktion::engine::WarpMap = typedef std::vector<WarpPoint>
AtomicWrapperRelaxed
template<typename Type , typename Constrainer = DummyConstrainer<Type>> using tracktion::engine::AtomicWrapperRelaxed = typedef AtomicWrapper<Type, Constrainer, std::memory_order_relaxed, std::memory_order_relaxed>
AtomicWrapperAcqRel
template<typename Type , typename Constrainer = DummyConstrainer<Type>> using tracktion::engine::AtomicWrapperAcqRel = typedef AtomicWrapper<Type, Constrainer, std::memory_order_acquire, std::memory_order_release>
SampleCount
using tracktion::engine::SampleCount = typedef int64_t
SampleRange
using tracktion::engine::SampleRange = typedef juce::Range<SampleCount>
HashCode
using tracktion::engine::HashCode = typedef int64_t
MPESourceID
using tracktion::engine::MPESourceID = typedef uint32_t
Enumeration Type Documentation
DeleteExistingClips
enum class tracktion::engine::DeleteExistingClips strong
Determines behaviour for overwriting clips.
Enumerator
no
yes
CloseGap
enum class tracktion::engine::CloseGap strong
An enum to specify if gaps deleted should be closed or not.
Enumerator
no
Don't move up subsequent track content.
yes
Do move up subsequent track content.
MoveClipAction
enum class tracktion::engine::MoveClipAction strong
Enum to dictate move clip behaviour.
Enumerator
moveToEndOfLast
moveToStartOfNext
moveStartToCursor
moveEndToCursor
LaunchQType
enum class tracktion::engine::LaunchQType strong
Enumerator
none
eightBars
fourBars
twoBars
bar
halfT
half
halfD
quarterT
quarter
quarterD
eighthT
eighth
eighthD
sixteenthT
sixteenth
sixteenthD
thirtySecondT
thirtySecond
thirtySecondD
sixtyFourthT
sixtyFourth
sixtyFourthD
TimecodeType
enum class tracktion::engine::TimecodeType strong
Enumerator
millisecs
barsBeats
fps24
fps25
fps30
ResamplingQuality
enum class tracktion::engine::ResamplingQuality strong
Specifies a number of resampling qualities that can be used.
Enumerator
lagrange
Lagrange interpolation.
sincFast
Fast sinc interpolation provided by libsamplerate.
sincMedium
Medium quality sinc interpolation provided by libsamplerate.
sincBest
Best quality sinc interpolation provided by libsamplerate.
PanLaw
enum tracktion::engine::PanLaw
All laws have been designed to be equal-power, excluding linear respectively.
Enumerator
PanLawDefault
PanLawLinear
PanLaw2point5dBCenter
PanLaw3dBCenter
PanLaw4point5dBCenter
PanLaw6dBCenter
AuxPosition
enum class tracktion::engine::AuxPosition strong
Enumerator
byBus
byPosition
SettingID
enum class tracktion::engine::SettingID strong
A list of settings the engine will get and set.
Enumerator
invalid
addAntiDenormalNoise
audio_device_setup
audiosettings
autoFreeze
autoTempoMatch
autoTempoDetect
automapVst
automapNative
automapGuids1
automapGuids2
cacheSizeSamples
compCrossfadeMs
countInMode
clickTrackMidiNoteBig
clickTrackMidiNoteLittle
clickTrackSampleSmall
clickTrackSampleBig
crossfadeBlock
cpu
customMidiControllers
deadMansPedal
defaultMidiOutDevice
defaultWaveOutDevice
defaultMidiInDevice
defaultWaveInDevice
externControlIn
externControlOut
externControlNum
externControlMain
externControlShowSelection
externControlSelectionColour
externControlEnable
externOscInputPort
externOscOutputPort
externOscOutputAddr
filterControlMappingPresets
filterGui
fitClipsToRegion
findExamples
freezePoint
hasEnabledMidiDefaultDevs
glideLength
grooveTemplates
knownPluginList
knownPluginList64
lameEncoder
lastClickTrackLevel
lastEditRender
lowLatencyBuffer
MCUoneTouchRecord
maxLatency
midiin
midiout
midiEditorOctaves
midiProgramManager
newMarker
numThreadsForPluginScanning
projectList
projects
recentProjects
renameClipRenamesSource
renameMode
renderRecentFilesList
resetCursorOnPlay
retrospectiveRecord
reWireEnabled
safeRecord
sendControllerOffMessages
simplifyAfterRecording
snapCursor
tempDirectory
trackExpansionMode
use64Bit
xFade
xtCount
xtIndices
virtualmididevices
virtualmidiin
midiScanIntervalSeconds
useSeparateProcessForScanning
useRealtime
wavein
waveout
windowsDoubleClick
renderFormat
trackRenderSampRate
trackRenderBits
bypassFilters
markedRegion
editClipRenderSampRate
editClipRenderBits
editClipRenderDither
editClipRealtime
editClipRenderStereo
editClipRenderNormalise
editClipRenderRMS
editClipRenderRMSLevelDb
editClipRenderPeakLevelDb
editClipPassThroughFilters
exportFormat
renderOnlySelectedClips
renderOnlyMarked
renderNormalise
renderRMS
renderRMSLevelDb
renderPeakLevelDb
renderTrimSilence
renderSampRate
renderStereo
renderBits
renderDither
quality
addId3Info
realtime
passThroughFilters
externControlShowClipSlotSelection
addAcidMetadata
Function Documentation
determineKeyOfNotes()
juce::Array< KeyResult > tracktion::engine::determineKeyOfNotes (const juce::Array< MidiNote * > & notes)
getAutomationMode()
AutomationMode tracktion::engine::getAutomationMode (const AutomatableParameter &)
Looks for the Track this parameter is currently on and returns the AutomationMode for it.
getAssignmentsOfType()
template<typename AssignmentType > juce::ReferenceCountedArray< AssignmentType > tracktion::engine::getAssignmentsOfType (const AutomatableParameter & ap)
Returns all the Assignments of a specific type.
getModifiersOfType() [1/2]
template<typename ModifierType > juce::Array< ModifierType * > tracktion::engine::getModifiersOfType (const AutomatableParameter & ap)
Returns all the modifers in use of a specific type.
getAssignmentsForSource()
template<typename AssignmentType , typename ModifierSourceType , typename EditType > juce::ReferenceCountedArray< AssignmentType > tracktion::engine::getAssignmentsForSource (EditType & edit, const ModifierSourceType & source)
Iterates an Edit looking for all parameters that assigned to a given parameter.
getSourceForAssignment()
AutomatableParameter::ModifierSource * tracktion::engine::getSourceForAssignment (const AutomatableParameter::ModifierAssignment &)
Iterates an Edit looking for the source of this assignment.
getAllParametersBeingModifiedBy()
juce::ReferenceCountedArray< AutomatableParameter > tracktion::engine::getAllParametersBeingModifiedBy (Edit & , AutomatableParameter::ModifierSource &)
Iterates an Edit looking for all parameters that are being modified by the given ModifierSource.
getParameter()
AutomatableParameter * tracktion::engine::getParameter (AutomatableParameter::ModifierAssignment &)
Iterates an Edit looking for the parameter that this ModifierAssignment has been made from.
getIntParamValue()
int tracktion::engine::getIntParamValue (const AutomatableParameter & ap)
Returns an int version of an AutomatableParameter.
getBoolParamValue()
bool tracktion::engine::getBoolParamValue (const AutomatableParameter & ap)
Returns a bool version of an AutomatableParameter.
getTypedParamValue()
template<typename Type > Type tracktion::engine::getTypedParamValue (const AutomatableParameter & ap)
Returns an int version of an AutomatableParameter cast to a enum type.
getMacroParameterForID()
MacroParameter::Ptr tracktion::engine::getMacroParameterForID (Edit & , EditItemID)
Searched the Edit for a MacroParameter with this ID.
getOwnerPlugin()
juce::ReferenceCountedObjectPtr< Plugin > tracktion::engine::getOwnerPlugin (MacroParameterList *)
If this MacroParameterList belongs to an Plugin, this will return it.
getModifiersOfType() [2/2]
template<typename ModifierType > juce::ReferenceCountedArray< ModifierType > tracktion::engine::getModifiersOfType (const ModifierList & ml)
Returns the modifers of a specific type.
findModifierForID() [1/3]
Modifier::Ptr tracktion::engine::findModifierForID (ModifierList & , EditItemID)
Returns a Modifier if it can be found in the list.
findClipForState() [1/2]
Clip * tracktion::engine::findClipForState (ClipOwner & , const juce::ValueTree &)
Returns a clip with the given state if the ClipOwner contains it.
findClipForID() [1/2]
Clip * tracktion::engine::findClipForID (ClipOwner & , EditItemID)
Returns a clip with the given ID if the ClipOwner contains it.
insertClipWithState() [1/2]
Clip * tracktion::engine::insertClipWithState (ClipOwner & , juce::ValueTree)
Inserts a clip with the given state in to the ClipOwner's clip list.
insertClipWithState() [2/2]
Clip * tracktion::engine::insertClipWithState (ClipOwner & , const juce::ValueTree & stateToUse, const juce::String & name, TrackItem::Type , ClipPosition , DeleteExistingClips , bool allowSpottingAdjustment)
Inserts a clip with the given state in to the ClipOwner's clip list.
insertNewClip() [1/3]
Clip * tracktion::engine::insertNewClip (ClipOwner & , TrackItem::Type , EditTimeRange)
Inserts a new clip with the given type and a default name.
insertNewClip() [2/3]
Clip * tracktion::engine::insertNewClip (ClipOwner & , TrackItem::Type , const juce::String & name, EditTimeRange)
Inserts a new clip with the given type and name.
insertNewClip() [3/3]
Clip * tracktion::engine::insertNewClip (ClipOwner & , TrackItem::Type , const juce::String & name, ClipPosition)
Inserts a new clip with the given type and name.
insertWaveClip() [1/2]
juce::ReferenceCountedObjectPtr< WaveAudioClip > tracktion::engine::insertWaveClip (ClipOwner & , const juce::String & name, const juce::File & sourceFile, ClipPosition , DeleteExistingClips)
Inserts a new WaveAudioClip into the ClipOwner's clip list.
insertWaveClip() [2/2]
juce::ReferenceCountedObjectPtr< WaveAudioClip > tracktion::engine::insertWaveClip (ClipOwner & , const juce::String & name, ProjectItemID sourceID, ClipPosition , DeleteExistingClips)
Inserts a new WaveAudioClip into the ClipOwner's clip list.
insertMIDIClip() [1/2]
juce::ReferenceCountedObjectPtr< MidiClip > tracktion::engine::insertMIDIClip (ClipOwner & , const juce::String & name, TimeRange)
Inserts a new MidiClip into the ClipOwner's clip list.
insertMIDIClip() [2/2]
juce::ReferenceCountedObjectPtr< MidiClip > tracktion::engine::insertMIDIClip (ClipOwner & , TimeRange)
Inserts a new MidiClip into the ClipOwner's clip list.
insertEditClip()
juce::ReferenceCountedObjectPtr< EditClip > tracktion::engine::insertEditClip (ClipOwner & , TimeRange , ProjectItemID)
Inserts a new EditClip into the ClipOwner's clip list.
deleteRegion() [1/2]
juce::Array< Clip * > tracktion::engine::deleteRegion (ClipOwner & , TimeRange)
Removes a region of a ClipOwner and returns any newly created clips.
deleteRegion() [2/2]
juce::Array< Clip * > tracktion::engine::deleteRegion (Clip & , TimeRange)
Removes a region of a clip and returns any newly created clips.
split() [1/2]
juce::Array< Clip * > tracktion::engine::split (ClipOwner & , TimePosition)
Splits the given clp owner at the time and returns any newly created clips.
split() [2/2]
Clip * tracktion::engine::split (Clip & , TimePosition)
Splits the given clip at the time and returns the newly created clip.
containsAnyMIDIClips()
bool tracktion::engine::containsAnyMIDIClips (const ClipOwner &)
Returns true if the clip owner contains any MIDI clips.
getClipsOfType()
template<typename ClipType > juce::Array< ClipType * > tracktion::engine::getClipsOfType (const ClipOwner & parent)
Returns the subclips of the given type.
getClipsOfTypeRecursive()
template<typename ClipType > juce::Array< ClipType * > tracktion::engine::getClipsOfTypeRecursive (const ClipOwner & parent)
Returns the subclips of the given type, if any clips contain other clips, this will also return those.
isMasterTrack()
bool tracktion::engine::isMasterTrack (const Track &)
Returns true if this is a MasterTrack.
isTempoTrack()
bool tracktion::engine::isTempoTrack (const Track &)
Returns true if this is a TempoTrack.
isAutomationTrack()
bool tracktion::engine::isAutomationTrack (const Track &)
Returns true if this is an AutomationTrack.
isAudioTrack() [1/2]
bool tracktion::engine::isAudioTrack (const Track &)
Returns true if this is an AudioTrack.
isFolderTrack() [1/2]
bool tracktion::engine::isFolderTrack (const Track &)
Returns true if this is a FolderTrack.
isMarkerTrack() [1/2]
bool tracktion::engine::isMarkerTrack (const Track &)
Returns true if this is a MarkerTrack.
isChordTrack() [1/2]
bool tracktion::engine::isChordTrack (const Track &)
Returns true if this is a ChordTrack.
isArrangerTrack() [1/2]
bool tracktion::engine::isArrangerTrack (const Track &)
Returns true if this is an ArrangerTrack.
isAudioTrack() [2/2]
bool tracktion::engine::isAudioTrack (const ClipOwner &)
Returns true if this is an AudioTrack.
isFolderTrack() [2/2]
bool tracktion::engine::isFolderTrack (const ClipOwner &)
Returns true if this is a FolderTrack.
isMarkerTrack() [2/2]
bool tracktion::engine::isMarkerTrack (const ClipOwner &)
Returns true if this is a MarkerTrack.
isChordTrack() [2/2]
bool tracktion::engine::isChordTrack (const ClipOwner &)
Returns true if this is a ChordTrack.
isArrangerTrack() [2/2]
bool tracktion::engine::isArrangerTrack (const ClipOwner &)
Returns true if this is an ArrangerTrack.
canContainMIDI()
bool tracktion::engine::canContainMIDI (const ClipOwner &)
Returns true if this Track can contain MidiClip[s].
canContainAudio()
bool tracktion::engine::canContainAudio (const ClipOwner &)
Returns true if this Track can contain WaveAudioClip[s].
isMovable()
bool tracktion::engine::isMovable (const Track &)
Returns true if this Track is movable.
See also
AudioTrack, FolderTrack
isOnTop()
bool tracktion::engine::isOnTop (const Track &)
Returns true if this a global Track and should be on top of others.
See also
MarkerTrack, TempoTrack
mergeInMidiSequence()
void tracktion::engine::mergeInMidiSequence (MidiClip & , juce::MidiMessageSequence , TimeDuration offsetToApply, MidiList::NoteAutomationType)
Copies a zero-time origin based MIDI sequence in to a MidiClip.
This zill extend the start and end of the clip to fit the whole sequence.
Parameters
MidiClip The destination clip
MidiMessageSequence The zero-based MIDI sequence
offsetToApply An offset to apply to all MIDI message timestamps
NoteAutomationType Whether to use standard MIDI or MPE
loadEditFromFile() [1/2]
std::unique_ptr< Edit > tracktion::engine::loadEditFromFile (Engine & , const juce::File & , Edit::EditRole role = Edit::EditRole::forEditing)
Loads an edit from a file, ready for playback / editing.
Referenced by tracktion::engine::benchmark_utilities::openEditfromArchiveData().
loadEditFromState()
std::unique_ptr< Edit > tracktion::engine::loadEditFromState (Engine & , const juce::ValueTree & , Edit::EditRole role = Edit::EditRole::forEditing)
Loads an edit from a ValueTree, ready for playback / editing.
createEmptyEdit() [1/2]
std::unique_ptr< Edit > tracktion::engine::createEmptyEdit (Engine & , const juce::File &)
Creates a new edit for a file, ready for playback / editing.
loadEditFromProjectManager()
juce::ValueTree tracktion::engine::loadEditFromProjectManager (ProjectManager & , ProjectItemID)
Uses the ProjectManager to find an Edit file and load it as a ValueTree.
loadEditForExamining()
std::unique_ptr< Edit > tracktion::engine::loadEditForExamining (ProjectManager & , ProjectItemID , Edit::EditRole role = Edit::EditRole::forExamining, Edit::LoadContext * = nullptr)
Uses the ProjectManager to find an Edit file and open it.
loadEditFromFile() [2/2]
juce::ValueTree tracktion::engine::loadEditFromFile (Engine & , const juce::File & , ProjectItemID)
Legacy, will be deprecated soon.
Use version that returns an edit. Loads a ValueTree from a file to load an Edit. If the file is empty, a new Edit state will be created with the given ProjectItemID.
createEmptyEdit() [2/2]
juce::ValueTree tracktion::engine::createEmptyEdit (Engine &)
Legacy, will be deprecated soon.
Use version that returns an edit. Creates an empty Edit with no project.
updateLegacyEdit() [1/2]
juce::ValueTree tracktion::engine::updateLegacyEdit (const juce::ValueTree & v)
Converts old edit formats to the latest structure.
updateLegacyEdit() [2/2]
void tracktion::engine::updateLegacyEdit (juce::XmlElement & editXML)
Converts old edit formats to the latest structure.
getProjectForEdit()
Project::Ptr tracktion::engine::getProjectForEdit (const Edit &)
Tries to find the project that contains this edit (but may return nullptr!)
getProjectItemForEdit()
ProjectItem::Ptr tracktion::engine::getProjectItemForEdit (const Edit &)
Tries to find the project item that refers to this edit (but may return nullptr!)
getEditFileFromProjectManager()
juce::File tracktion::engine::getEditFileFromProjectManager (Edit &)
Uses the ProjectManager to look up the file for an Edit.
referencesProjectItem()
bool tracktion::engine::referencesProjectItem (Edit & , ProjectItemID)
Returns true if the ProjectItemID is being used for any of the Edit's elements.
insertSpaceIntoEdit()
void tracktion::engine::insertSpaceIntoEdit (Edit & , TimeRange timeRangeToInsert)
Inserts blank space in to an Edit, splitting clips if necessary.
insertSpaceIntoEditFromBeatRange()
void tracktion::engine::insertSpaceIntoEditFromBeatRange (Edit & , BeatRange)
Inserts a number of blank beats in to the Edit.
findEditItemForID()
EditItem * tracktion::engine::findEditItemForID (Edit & , EditItemID)
Looks for an item in an edit with a given ID.
getAllTracks()
juce::Array< Track * > tracktion::engine::getAllTracks (const Edit &)
Returns all the tracks in an Edit.
getTopLevelTracks()
juce::Array< Track * > tracktion::engine::getTopLevelTracks (const Edit &)
Returns all of the non-foldered tracks in an Edit.
getTracksOfType()
template<typename TrackType > juce::Array< TrackType * > tracktion::engine::getTracksOfType (const Edit & edit, bool recursive)
Returns the tracks of a given type in an Edit.
getAudioTracks()
juce::Array< AudioTrack * > tracktion::engine::getAudioTracks (const Edit &)
Returns all the AudioTracks in an Edit.
getClipTracks()
juce::Array< ClipTrack * > tracktion::engine::getClipTracks (const Edit &)
Returns all the ClipTracks in an Edit.
getTotalNumTracks()
int tracktion::engine::getTotalNumTracks (const Edit &)
Returns the total number of Tracks in an Edit.
findTrackForID()
Track * tracktion::engine::findTrackForID (const Edit & , EditItemID)
Returns the Track with a given ID if contained in the Edit.
findAudioTrackForID()
AudioTrack * tracktion::engine::findAudioTrackForID (const Edit & , EditItemID)
Returns the AudioTrack with a given ID if contained in the Edit.
findTracksForIDs()
juce::Array< Track * > tracktion::engine::findTracksForIDs (const Edit & , const juce::Array< EditItemID > &)
Returns the Tracks for the given IDs in the Edit.
findTrackForState()
Track * tracktion::engine::findTrackForState (const Edit & , const juce::ValueTree &)
Returns the Track with a given state if contained in the Edit.
getFirstAudioTrack()
AudioTrack * tracktion::engine::getFirstAudioTrack (const Edit &)
Returns the first audio track in an Edit.
findAllTracksContainingSelectedItems()
juce::Array< Track * > tracktion::engine::findAllTracksContainingSelectedItems (const SelectableList &)
Returns all the tracks containing the selected tracks or TrackItems.
findFirstClipTrackFromSelection()
ClipTrack * tracktion::engine::findFirstClipTrackFromSelection (const SelectableList &)
Returns the first ClipTrack from the selected tracks or clips.
containsTrack()
bool tracktion::engine::containsTrack (const Edit & , const Track &)
Returns true if the Edit contains this Track.
getTrackOutput()
TrackOutput * tracktion::engine::getTrackOutput (Track &)
Returns the TrackOutput if the given track has one.
toBitSet()
juce::BigInteger tracktion::engine::toBitSet (const juce::Array< Track * > &)
Returns the set of tracks as a BigInteger with each bit corresponding to the array of all tracks in an Edit.
Used in Renderer.
toTrackArray()
juce::Array< Track * > tracktion::engine::toTrackArray (Edit & , const juce::BigInteger &)
Returns an Array of Track[s] corresponding to the set bits of all tracks in an Edit.
Used in Renderer.
getTrackItemsOfType()
template<typename TrackItemType > juce::Array< TrackItemType * > tracktion::engine::getTrackItemsOfType (const Track & track)
findClipOwnerForID()
ClipOwner * tracktion::engine::findClipOwnerForID (const Edit & , EditItemID)
Returns the ClipOwner with a given ID if it can be found in the Edit.
findClipSlotForID()
ClipSlot * tracktion::engine::findClipSlotForID (const Edit & , EditItemID)
Returns the ClipSlot for the given ID.
findClipSlotIndex()
int tracktion::engine::findClipSlotIndex (ClipSlot &)
Returns the index of the ClipSlot in the list it is owned by.
findClipForID() [2/2]
Clip * tracktion::engine::findClipForID (const Edit & , EditItemID)
Returns the Clip with a given ID if contained in the Edit.
findClipForState() [2/2]
Clip * tracktion::engine::findClipForState (const Edit & , const juce::ValueTree &)
Returns the Clip for a given state if contained in the Edit.
containsClip()
bool tracktion::engine::containsClip (const Edit & , Clip *)
Returns true if an Edit contains a given clip.
duplicateClip()
Clip::Ptr tracktion::engine::duplicateClip (const Clip &)
Creates a unique copy of this clip with a new EditItemID.
visitAllTrackItems()
void tracktion::engine::visitAllTrackItems (const Edit & , std::function< bool(TrackItem &)>)
Calls a function for all TrackItems in an Edit.
getTimeRangeForSelectedItems()
TimeRange tracktion::engine::getTimeRangeForSelectedItems (const SelectableList &)
Returns the time range covered by the given items.
deleteRegionOfTracks()
void tracktion::engine::deleteRegionOfTracks (Edit & , TimeRange rangeToDelete, bool onlySelectedTracks, CloseGap , SelectionManager *)
Deletes a time range of an Edit, optionally closing the gap.
deleteRegionOfClip()
void tracktion::engine::deleteRegionOfClip (Clip & , TimeRange rangeToDelete)
Deletes a time range of a Clip.
deleteRegionOfSelectedClips()
void tracktion::engine::deleteRegionOfSelectedClips (SelectionManager & , TimeRange rangeToDelete, CloseGap , bool moveAllSubsequentClipsOnTrack)
Deletes a time range of a Clip selection, optionally closing the gap.
splitClips()
SelectableList tracktion::engine::splitClips (const SelectableList & clips, TimePosition time)
Splits the clips at a given time.
moveSelectedClips()
void tracktion::engine::moveSelectedClips (const SelectableList & , Edit & , MoveClipAction mode, bool alsoMoveAutomation)
Moves the selected clips within their track.
getClipSelectionWithCollectionClipContents()
SelectableList tracktion::engine::getClipSelectionWithCollectionClipContents (const SelectableList &)
Returns a list of clips.
If any of these are collection clips, this will return their contained clips.
getAllClipEffects()
juce::Array< ClipEffect * > tracktion::engine::getAllClipEffects (Edit & edit)
Returns all clip effects.
findNoteForState()
MidiNote * tracktion::engine::findNoteForState (const Edit & , const juce::ValueTree &)
Returns the MidiNote with a given state.
mergeMidiClips()
juce::Result tracktion::engine::mergeMidiClips (juce::Array< MidiClip * > , SelectionManager * sm = nullptr)
Merges a set of MIDI clips in to one new one.
readFileToMidiList()
juce::OwnedArray< MidiList > tracktion::engine::readFileToMidiList (juce::File midiFile, bool importAsNoteExpression)
Helper function to read a file to a number of MidiLists.
createClipFromFile()
MidiClip::Ptr tracktion::engine::createClipFromFile (juce::File midiFile, ClipOwner & , bool importAsNoteExpression)
Helper function to read a MIDI file and create a MidiClip from it.
N.B. This will only use the first track in the file, any other tracks will be discarded. The clip will be positioned at 0 with a beat length the duration of the imported list.
getAllPlugins()
Plugin::Array tracktion::engine::getAllPlugins (const Edit & , bool includeMasterVolume)
Returns all the plugins in a given Edit.
findPluginForState()
Plugin::Ptr tracktion::engine::findPluginForState (const Edit & , const juce::ValueTree &)
Returns the plugin with given state.
findPluginForID()
Plugin::Ptr tracktion::engine::findPluginForID (const Edit & , EditItemID)
Returns the plugin with given EditItemID.
getTrackContainingPlugin()
Track * tracktion::engine::getTrackContainingPlugin (const Edit & , const Plugin *)
Returns the track for the track which the plugin is located on.
areAnyPluginsMissing()
bool tracktion::engine::areAnyPluginsMissing (const Edit &)
Returns true if any plugins couldn't be loaded beacuse their files are missing.
getRackInstancesInEditForType()
juce::Array< RackInstance * > tracktion::engine::getRackInstancesInEditForType (const RackType &)
Returns all of the instances of a specific RackType in an Edit.
muteOrUnmuteAllPlugins()
void tracktion::engine::muteOrUnmuteAllPlugins (const Edit &)
Toggles the enabled state of all plugins in an Edit.
midiPanic()
void tracktion::engine::midiPanic (Edit & , bool resetPlugins)
Performs a "MIDI panic" on the edit, by sending all-note-off messages directly to all plugins in the edit, and optionally resetting them to kill any reverb tails, etc.
insertNewPlugin()
template<typename PluginType > juce::ReferenceCountedObjectPtr< PluginType > tracktion::engine::insertNewPlugin (Track & track, int index)
Adds a new instance of the given plugin to the track's plugin list at the specified index.
getAllAutomatableEditItems()
juce::Array< AutomatableEditItem * > tracktion::engine::getAllAutomatableEditItems (const Edit &)
Returns all AutomatableEditItems in an Edit.
deleteAutomation()
void tracktion::engine::deleteAutomation (const SelectableList & selectedClips)
Deletes the automation covered by the selected clips.
getAllModifierSources()
juce::Array< AutomatableParameter::ModifierSource * > tracktion::engine::getAllModifierSources (const Edit &)
Returns all the ModifierSources in an Edit.
getAllModifiers()
juce::ReferenceCountedArray< Modifier > tracktion::engine::getAllModifiers (const Edit &)
Returns all the Modifiers in an Edit.
findModifierTypeForID()
template<typename ModifierType > ModifierType::Ptr tracktion::engine::findModifierTypeForID (const Edit & edit, EditItemID id)
Returns the Modifier with a given type and ID.
findModifierForID() [2/3]
Modifier::Ptr tracktion::engine::findModifierForID (const Edit & , EditItemID)
Returns the Modifier with a given ID.
findModifierForID() [3/3]
Modifier::Ptr tracktion::engine::findModifierForID (const RackType & , EditItemID)
Returns the Modifier with a given ID if the RackType contains it.
getTrackContainingModifier()
Track * tracktion::engine::getTrackContainingModifier (const Edit & , const Modifier::Ptr &)
Returns the Track containing a Modifier.
getAllMacroParameterLists()
juce::Array< MacroParameterList * > tracktion::engine::getAllMacroParameterLists (const Edit &)
Returns all the MacroParameterLists in an Edit.
getAllMacroParameterElements()
juce::Array< MacroParameterElement * > tracktion::engine::getAllMacroParameterElements (const Edit &)
Returns all the MacroParameterElement in an Edit.
getDefaultRecordingParameters()
InputDeviceInstance::RecordingParameters tracktion::engine::getDefaultRecordingParameters (const EditPlaybackContext & , TimePosition playStart, TimePosition punchIn)
Returns the default set of recording parameters.
This behaviour may not be desirable in which case it might make more sense to just construct your own RecordingParameters and pass them to InputDeviceInstance::prepareToRecord.
prepareAndPunchRecord()
juce::Result tracktion::engine::prepareAndPunchRecord (InputDeviceInstance & , EditItemID)
Starts an InputDeviceInstance recording to the given target without any count-in etc.
N.B. The input must already be assigned to the target and armed for the punch to start.
punchOutRecording()
tl::expected< Clip::Array, juce::String > tracktion::engine::punchOutRecording (InputDeviceInstance &)
If the instance is currently recording, this will stop it and return any created clips or an error message.
isRecording()
bool tracktion::engine::isRecording (EditPlaybackContext &)
Returns true if any inputs are currently recording.
assignTrackAsInput()
InputDeviceInstance::Destination * tracktion::engine::assignTrackAsInput (AudioTrack & destinationTrack, const AudioTrack & sourceTrack, InputDevice::DeviceType)
Creates an InputDeviceInstance::Destination on the destinationTrack from the sourceTrack if possible.
getEdit()
template<typename Type > requires (std::is_same_v<Type, Edit> || requires (Type t) { t.edit; } || requires (Type t) { t.getEdit(); }) Edit & tracktion::engine::getEdit (Type & type)
Returns a reference to the Edit if accessible by the given object.
getTempoSequence()
TempoSequence & tracktion::engine::getTempoSequence (auto & type)
getUndoManager()
juce::UndoManager & tracktion::engine::getUndoManager (auto & type)
getUndoManager_p()
juce::UndoManager * tracktion::engine::getUndoManager_p (auto & type)
getLaunchQTypeChoices()
juce::StringArray tracktion::engine::getLaunchQTypeChoices ()
Returns a list of quantisation type options in the order of LaunchQType.
launchQTypeFromName()
std::optional< LaunchQType > tracktion::engine::launchQTypeFromName (const juce::String &)
Returns a the launch Q from a string returned from getLaunchQTypeChoices().
getName()
juce::String tracktion::engine::getName (LaunchQType)
Retuns the name of a LaunchQType for display purposes.
toBarFraction()
double tracktion::engine::toBarFraction (LaunchQType) noexcept
Returns the fraction of a bar to be used for a given rate type.
Referenced by juce::VariantConverter< tracktion::engine::LaunchQType >::toVar().
fromBarFraction()
LaunchQType tracktion::engine::fromBarFraction (double) noexcept
Returns the fraction of a bar to be used for a given rate type.
Referenced by juce::VariantConverter< tracktion::engine::LaunchQType >::fromVar().
getNext() [1/2]
BeatPosition tracktion::engine::getNext (LaunchQType , const TempoSequence & , BeatPosition) noexcept
Returns the next quantised position.
getNext() [2/2]
BeatPosition tracktion::engine::getNext (LaunchQType , const tempo::Sequence & , BeatPosition) noexcept
Returns the next quantised position.
operator<() [1/2]
bool tracktion::engine::operator< (const PitchSetting & p1, const PitchSetting & p2) noexcept
createPosition()
tempo::Sequence::Position tracktion::engine::createPosition (const TempoSequence &)
Creates a Position to iterate over the given TempoSequence.
One of these lets you take a position in a tempo sequence, and skip forwards/backwards either by absolute times, or by bar/beat amounts. This is dynamic and if the TempoSequence changes, the position will update to reflect this.
N.B. It is only safe to call this from the message thread or during audio callbacks. Access at any other time could incur data races.
toBeats() [1/8]
BeatPosition tracktion::engine::toBeats (TimePosition , const TempoSequence &)
Converts a TimePosition to a BeatPosition given a TempoSequence.
toBeats() [2/8]
BeatPosition tracktion::engine::toBeats (TimePosition , const tempo::Sequence &)
toTime() [1/8]
TimePosition tracktion::engine::toTime (BeatPosition , const TempoSequence &)
Converts a BeatPosition to a TimePosition given a TempoSequence.
toTime() [2/8]
TimePosition tracktion::engine::toTime (BeatPosition , const tempo::Sequence &)
toBeats() [3/8]
BeatRange tracktion::engine::toBeats (TimeRange , const TempoSequence &)
Converts a TimeRange to a BeatRange given a TempoSequence.
toBeats() [4/8]
BeatRange tracktion::engine::toBeats (TimeRange , const tempo::Sequence &)
toTime() [3/8]
TimeRange tracktion::engine::toTime (BeatRange , const TempoSequence &)
Converts a BeatRange to a TimeRange given a TempoSequence.
toTime() [4/8]
TimeRange tracktion::engine::toTime (BeatRange , const tempo::Sequence &)
toPosition()
EditPosition tracktion::engine::toPosition (EditDuration duration)
Returns the raw value of beats or seconds, only really useful for comparing two EditDurations with the same time base.
toUnderlying() [1/3]
double tracktion::engine::toUnderlying (EditDuration duration)
Returns the raw value of beats or seconds, only really useful for comparing two EditDurations with the same time base.
isZero()
bool tracktion::engine::isZero (EditDuration duration)
Returns true if the duration is 0 beats or seconds.
isGreaterThanZero()
bool tracktion::engine::isGreaterThanZero (EditDuration duration)
Returns true if the duration is greater than zero beats or seconds.
plus()
EditPosition tracktion::engine::plus (const EditPosition & lhs, const EditDuration & rhs, const TempoSequence & ts)
minus() [1/2]
EditPosition tracktion::engine::minus (const EditPosition & lhs, const EditDuration & rhs, const TempoSequence & ts)
equals()
bool tracktion::engine::equals (const EditPosition & lhs, const EditPosition & rhs, const TempoSequence & ts)
minus() [2/2]
EditDuration tracktion::engine::minus (const EditPosition & lhs, const EditPosition & rhs, const TempoSequence & ts)
less()
bool tracktion::engine::less (const EditPosition & lhs, const EditPosition & rhs, const TempoSequence & ts)
greater()
bool tracktion::engine::greater (const EditPosition & lhs, const EditPosition & rhs, const TempoSequence & ts)
lessThanOrEqualTo()
bool tracktion::engine::lessThanOrEqualTo (const EditPosition & lhs, const EditPosition & rhs, const TempoSequence & ts)
greaterThanOrEqualTo()
bool tracktion::engine::greaterThanOrEqualTo (const EditPosition & lhs, const EditPosition & rhs, const TempoSequence & ts)
min()
EditPosition tracktion::engine::min (const EditPosition & lhs, const EditPosition & rhs, const TempoSequence & ts)
max()
EditPosition tracktion::engine::max (const EditPosition & lhs, const EditPosition & rhs, const TempoSequence & ts)
toDuration()
EditDuration tracktion::engine::toDuration (const EditPosition & p)
Referenced by tracktion::engine::Clip::getMaximumLength().
operator==()
bool tracktion::engine::operator== (const EditPositionWithTempoSequence & lhs, const EditPositionWithTempoSequence & rhs)
operator<() [2/2]
bool tracktion::engine::operator< (const EditPositionWithTempoSequence & lhs, const EditPositionWithTempoSequence & rhs)
operator<=()
bool tracktion::engine::operator<= (const EditPositionWithTempoSequence & lhs, const EditPositionWithTempoSequence & rhs)
operator>()
bool tracktion::engine::operator> (const EditPositionWithTempoSequence & lhs, const EditPositionWithTempoSequence & rhs)
operator>=()
bool tracktion::engine::operator>= (const EditPositionWithTempoSequence & lhs, const EditPositionWithTempoSequence & rhs)
operator-() [1/2]
EditDuration tracktion::engine::operator- (const EditPositionWithTempoSequence & lhs, const EditPositionWithTempoSequence & rhs)
operator+()
EditPosition tracktion::engine::operator+ (const EditPositionWithTempoSequence & lhs, const EditDuration & rhs)
operator-() [2/2]
EditPosition tracktion::engine::operator- (const EditPositionWithTempoSequence & lhs, const EditDuration & rhs)
toTime() [5/8]
TimePosition tracktion::engine::toTime (EditPosition et, const TempoSequence & ts)
Converts an EditTime to a TimePosition.
N.B. This may be a slow operation if this was created using a BeatPosition.
toBeats() [5/8]
BeatPosition tracktion::engine::toBeats (EditPosition et, const TempoSequence & ts)
Converts an EditTime to a BeatPosition.
N.B. This may be a slow operation if this was created using a TimePosition.
toUnderlying() [2/3]
double tracktion::engine::toUnderlying (EditPosition et)
Returns the raw number of seconds or beats.
Mostly useful for testing.
toUnderlying() [3/3]
juce::Range< double > tracktion::engine::toUnderlying (EditTimeRange r)
Returns the raw number of seconds or beats.
Mostly useful for testing.
contains()
bool tracktion::engine::contains (EditTimeRange r, EditPosition pos, const TempoSequence & ts)
Returns true if the given position is contained within the given range.
Referenced by tracktion::engine::Pitch::getPitchFromString().
containsInclusive()
bool tracktion::engine::containsInclusive (EditTimeRange r, EditPosition pos, const TempoSequence & ts)
Returns true if the given position is contained within the given closed range.
toTime() [6/8]
TimeRange tracktion::engine::toTime (EditTimeRange r, const TempoSequence & ts)
Converts an EditTimeRange to a TimeRange.
N.B. This may be a slow operation if this was created using a BeatRange.
toBeats() [6/8]
BeatRange tracktion::engine::toBeats (EditTimeRange r, const TempoSequence & ts)
Converts an EditTimeRange to a BeatRange.
N.B. This may be a slow operation if this was created using a TimeRange.
createClipPosition() [1/2]
ClipPosition tracktion::engine::createClipPosition (const TempoSequence & , TimeRange , TimeDuration offset = {})
Creates a ClipPosition from either a time or beat range.
createClipPosition() [2/2]
ClipPosition tracktion::engine::createClipPosition (const TempoSequence & , BeatRange , BeatDuration offset = {})
Creates a ClipPosition from either a time or beat range.
toTime() [7/8]
TimePosition tracktion::engine::toTime (EditPosition et, const tempo::Sequence & ts)
toBeats() [7/8]
BeatPosition tracktion::engine::toBeats (EditPosition et, const tempo::Sequence & ts)
toTime() [8/8]
TimeRange tracktion::engine::toTime (EditTimeRange r, const tempo::Sequence & ts)
toBeats() [8/8]
BeatRange tracktion::engine::toBeats (EditTimeRange r, const tempo::Sequence & ts)
countNumTracks()
int tracktion::engine::countNumTracks (const juce::ValueTree &)
Returns the number of tracks from this tree recursively.
moveAutomation()
void tracktion::engine::moveAutomation (const juce::Array< TrackAutomationSection > & , TimeDuration offset, bool copy)
Moves a set of automation optionally applying an offset and copying the automation (rather than moving it).
findIndexOfNextItemAt()
template<typename ArrayType > int tracktion::engine::findIndexOfNextItemAt (const ArrayType & items, TimePosition time)
Returns the index of the next item after the given time.
findUnionOfEditTimeRanges()
template<typename ArrayType > TimeRange tracktion::engine::findUnionOfEditTimeRanges (const ArrayType & items)
Returns the the time range that covers all the given TrackItems.
getTargetTracksAndIndexes()
juce::Array< std::pair< AudioTrack *, int > > tracktion::engine::getTargetTracksAndIndexes (InputDeviceInstance &)
Returns the AudioTracks and their indexes this instance is assigned to.
getTargetTracks()
juce::Array< AudioTrack * > tracktion::engine::getTargetTracks (InputDeviceInstance &)
Returns the AudioTracks this instance is assigned to.
isOnTargetTrack()
bool tracktion::engine::isOnTargetTrack (InputDeviceInstance & , const Track & , int idx)
Returns true if this instance is assigned to the given Track at the given index .
isAttached()
bool tracktion::engine::isAttached (InputDeviceInstance &)
Returns true if this input is assigned to a target.
clearFromTargets()
juce::Result tracktion::engine::clearFromTargets (InputDeviceInstance & , juce::UndoManager *)
Removes this instance from all assigned targets.
getDestination() [1/3]
InputDeviceInstance::Destination * tracktion::engine::getDestination (InputDeviceInstance & , const Track & track, int index)
Returns the destination if one has been assigned for the given arguments.
getDestination() [2/3]
InputDeviceInstance::Destination * tracktion::engine::getDestination (InputDeviceInstance & , const ClipSlot &)
Returns the destination if one has been assigned for the given arguments.
getDestination() [3/3]
InputDeviceInstance::Destination * tracktion::engine::getDestination (InputDeviceInstance & , const juce::ValueTree & destinationState)
Returns the destination if one has been assigned for the given arguments.
hasErrors()
bool tracktion::engine::hasErrors (const InputDeviceInstance::PreparedContext & pc)
Returns true if all the targets were fully prepared.
append()
InputDeviceInstance::PreparedContext & tracktion::engine::append (InputDeviceInstance::PreparedContext & dest, InputDeviceInstance::PreparedContext && src)
Appends a PreparedContent to another.
extract()
std::pair< std::vector< std::unique_ptr< InputDeviceInstance::RecordingContext > >, juce::StringArray > tracktion::engine::extract (InputDeviceInstance::PreparedContext && pc)
Splits the PreparedContext in to valid RecordingContexts and an array of error messages.
createDescriptionOfChannels()
juce::String tracktion::engine::createDescriptionOfChannels (const std::vector< ChannelIndex > &)
Creates a String description of the channels.
Useful for debugging.
createChannelSet()
juce::AudioChannelSet tracktion::engine::createChannelSet (const std::vector< ChannelIndex > &)
Creates an AudioChannelSet for a list of ChannelIndexes.
channelTypeFromAbbreviatedName()
juce::AudioChannelSet::ChannelType tracktion::engine::channelTypeFromAbbreviatedName (const juce::String &)
Returns the ChannelType for an abbreviated name.
See also
AudioChannelSet::getAbbreviatedChannelTypeName.
channelSetFromSpeakerArrangmentString()
juce::AudioChannelSet tracktion::engine::channelSetFromSpeakerArrangmentString (const juce::String &)
Creates an AudioChannelSet from a list of abbreviated channel names.
E.g. "L R"
createNodeForEdit() [1/2]
std::unique_ptr< tracktion::graph::Node > tracktion::engine::createNodeForEdit (EditPlaybackContext & , std::atomic< double > & audibleTimeToUpdate, const CreateNodeParams &)
Creates a Node to play back an Edit with live inputs and outputs.
Referenced by tracktion::engine::benchmark_utilities::createNode().
createNodeForEdit() [2/2]
std::unique_ptr< tracktion::graph::Node > tracktion::engine::createNodeForEdit (Edit & , const CreateNodeParams &)
Creates a Node to render an Edit.
toStart()
void tracktion::engine::toStart (TransportControl & , const SelectableList &)
Moves the transport to the start of the selected objects.
toEnd()
void tracktion::engine::toEnd (TransportControl & , const SelectableList &)
Moves the transport to the end of the selected objects.
tabBack()
void tracktion::engine::tabBack (TransportControl &)
Moves the transport back to the previous point of interest.
tabForward()
void tracktion::engine::tabForward (TransportControl &)
Moves the transport forwards to the next point of interest.
markIn()
void tracktion::engine::markIn (TransportControl &)
Sets the mark in position to the current transport position.
markOut()
void tracktion::engine::markOut (TransportControl &)
Sets the mark out position to the current transport position.
scrub()
void tracktion::engine::scrub (TransportControl & , double unitsForwards)
Scrubs back and forth in 'units', where a unit is about 1/50th of the width of the strip window.
freePlaybackContextIfNotRecording()
void tracktion::engine::freePlaybackContextIfNotRecording (TransportControl &)
Frees the playback context if no recording is in progress, useful for when an app is minimised.
float2string()
void tracktion::engine::float2string (float f, char * text, int len)
int2string()
void tracktion::engine::int2string (float i, char * text, int len)
dB2string()
void tracktion::engine::dB2string (float value, char * text, int maxLen)
getCmajorVersion()
std::string tracktion::engine::getCmajorVersion ()
createCmajorPatchPluginFormat()
std::unique_ptr< juce::AudioPluginFormat > tracktion::engine::createCmajorPatchPluginFormat (Engine &)
isCmajorPatchPluginFormat() [1/2]
bool tracktion::engine::isCmajorPatchPluginFormat (const juce::PluginDescription &)
isCmajorPatchPluginFormat() [2/2]
bool tracktion::engine::isCmajorPatchPluginFormat (const juce::String & formatName)
getCmajorPatchPluginFormatName()
juce::String tracktion::engine::getCmajorPatchPluginFormatName ()
getCmajorPatchCompileError()
juce::String tracktion::engine::getCmajorPatchCompileError (Plugin &)
createIdentifierString()
juce::String tracktion::engine::createIdentifierString (const juce::PluginDescription &)
Referenced by tracktion::engine::ExternalPlugin::getIdentifierString().
createSearchForKeywords()
SearchOperation * tracktion::engine::createSearchForKeywords (const juce::String & keywords)
Turns a keyword string into a search condition tree.
getOrInsertAudioTrackNearestIndex()
AudioTrack * tracktion::engine::getOrInsertAudioTrackNearestIndex (Edit & edit, int trackIndex)
makeSafeRef()
template<typename SelectableType > SafeSelectable< SelectableType > tracktion::engine::makeSafeRef (SelectableType & selectable)
Creates a SafeSelectable for a given selectable object.
makeSafeVector()
template<typename Iterable > auto tracktion::engine::makeSafeVector (const Iterable & selectables) -> std::vector<SafeSelectable<typename std::remove_reference<decltype(*selectables[0])>::type>>
Creates a std::vector<SafeSelectable<Something>> for a given juce::Array of selectable objects.
makeWeakRef() [1/2]
template<typename WeakReferenceable > juce::WeakReference< WeakReferenceable > tracktion::engine::makeWeakRef (WeakReferenceable & object)
Creates a juce::WeakReference for an object.
makeWeakRef() [2/2]
template<typename WeakReferenceable > juce::WeakReference< WeakReferenceable > tracktion::engine::makeWeakRef (WeakReferenceable * object)
Creates a juce::WeakReference for an object pointer (which may be null)
callBlocking()
bool tracktion::engine::callBlocking (std::function< void()> f)
Calls a function on the message thread by posting a message and then waiting for it to be delivered.
If this fails for some reason, e.g. the calling thread is trying to exit or is blocking the message thread, this will throw an exception.
callBlockingCatching()
bool tracktion::engine::callBlockingCatching (std::function< void()> f) noexcept
The same as callBlocking expect the exception is caught and ignored.
Use this when failue is ok.
dbToGain()
float tracktion::engine::dbToGain (float db) noexcept
Referenced by tracktion::engine::AudioClipBase::getGain(), and tracktion::engine::LiveClipLevel::getGain().
gainToDb()
float tracktion::engine::gainToDb (float gain) noexcept
gainToDbString()
juce::String tracktion::engine::gainToDbString (float gain, float infLevel = -96.0f, int decPlaces = 2)
dbStringToDb()
float tracktion::engine::dbStringToDb (const juce::String & dbStr)
Referenced by tracktion::engine::ExternalAutomatableParameter::stringToValue().
dbStringToGain()
float tracktion::engine::dbStringToGain (const juce::String & dbStr)
getPanString()
juce::String tracktion::engine::getPanString (float pan)
getSemitonesAsString()
juce::String tracktion::engine::getSemitonesAsString (double semitones)
midiNoteToFrequency()
template<typename FloatType > FloatType tracktion::engine::midiNoteToFrequency (FloatType midiNote)
frequencyToMidiNote()
template<typename FloatType > FloatType tracktion::engine::frequencyToMidiNote (FloatType freq)
sanitiseValues()
void tracktion::engine::sanitiseValues (juce::AudioBuffer< float > & , int startSample, int numSamples, float maxAbsValue, float minAbsThreshold = 1.0f/262144.0f)
addAntiDenormalisationNoise()
void tracktion::engine::addAntiDenormalisationNoise (juce::AudioBuffer< float > & , int start, int numSamples) noexcept
resetFP()
void tracktion::engine::resetFP () noexcept
hasFloatingPointDenormaliseOccurred()
bool tracktion::engine::hasFloatingPointDenormaliseOccurred () noexcept
zeroDenormalisedValuesIfNeeded()
void tracktion::engine::zeroDenormalisedValuesIfNeeded (juce::AudioBuffer< float > &) noexcept
isAudioDataAlmostSilent()
bool tracktion::engine::isAudioDataAlmostSilent (const float * data, int num)
getAudioDataMagnitude()
float tracktion::engine::getAudioDataMagnitude (const float * data, int num)
convertIntsToFloats()
void tracktion::engine::convertIntsToFloats (juce::AudioBuffer< float > &)
convertFloatsToInts()
void tracktion::engine::convertFloatsToInts (juce::AudioBuffer< float > &)
yieldGUIThread()
void tracktion::engine::yieldGUIThread () noexcept
toBufferView()
template<typename SampleType > choc::buffer::BufferView< SampleType, choc::buffer::SeparateChannelLayout > tracktion::engine::toBufferView (juce::AudioBuffer< SampleType > & buffer)
Converts a juce::AudioBuffer<SampleType> to a choc::buffer::BufferView.
getDefaultPanLaw()
PanLaw tracktion::engine::getDefaultPanLaw () noexcept
setDefaultPanLaw()
void tracktion::engine::setDefaultPanLaw (PanLaw)
getPanLawChoices()
juce::StringArray tracktion::engine::getPanLawChoices (bool includeDefault) noexcept
decibelsToVolumeFaderPosition()
float tracktion::engine::decibelsToVolumeFaderPosition (float dB) noexcept
volumeFaderPositionToDB()
float tracktion::engine::volumeFaderPositionToDB (float position) noexcept
Referenced by tracktion::engine::AuxSendPlugin::getGainDb().
volumeFaderPositionToGain()
float tracktion::engine::volumeFaderPositionToGain (float position) noexcept
gainToVolumeFaderPosition()
float tracktion::engine::gainToVolumeFaderPosition (float gain) noexcept
getGainsFromVolumeFaderPositionAndPan()
void tracktion::engine::getGainsFromVolumeFaderPositionAndPan (float volSliderPos, float pan, PanLaw lawToUse, float & leftGain, float & rightGain) noexcept
clearChannels()
void tracktion::engine::clearChannels (juce::AudioBuffer< float > & buffer, int startChannel, int endChannel = -1, int startSample = 0, int endSample = -1)
getCurrentPositionInfo()
juce::AudioPlayHead::CurrentPositionInfo tracktion::engine::getCurrentPositionInfo (Edit &)
Converts an Edit's internal transport information to a juce::AudioPlayHead::CurrentPositionInfo.
synchroniseEditPosition()
void tracktion::engine::synchroniseEditPosition (Edit & , const juce::AudioPlayHead::CurrentPositionInfo &)
Syncs an Edit's transport and tempo sequence to a juce AudioPlayHead.
isMidiFile()
bool tracktion::engine::isMidiFile (const juce::File &)
isTracktionEditFile()
bool tracktion::engine::isTracktionEditFile (const juce::File &)
Referenced by tracktion::engine::benchmark_utilities::openEditfromArchiveData().
isTracktionArchiveFile()
bool tracktion::engine::isTracktionArchiveFile (const juce::File &)
isTracktionProjectFile()
bool tracktion::engine::isTracktionProjectFile (const juce::File &)
isTracktionPresetFile()
bool tracktion::engine::isTracktionPresetFile (const juce::File &)
getNonExistentSiblingWithIncrementedNumberSuffix()
juce::File tracktion::engine::getNonExistentSiblingWithIncrementedNumberSuffix (const juce::File & , bool addHashSymbol)
addSortedListToMenu()
void tracktion::engine::addSortedListToMenu (juce::PopupMenu & m, juce::StringArray names, int startID)
getScaleAroundCentre()
juce::AffineTransform tracktion::engine::getScaleAroundCentre (juce::Rectangle< float > r, float numPixels)
moveXMLAttributeToStart()
void tracktion::engine::moveXMLAttributeToStart (juce::XmlElement & xml, juce::StringRef att)
removeIf()
template<typename Vector , typename Predicate > bool tracktion::engine::removeIf (Vector & v, Predicate && pred)
almostEqual()
template<typename FloatingPointType > bool tracktion::engine::almostEqual (FloatingPointType firstValue, FloatingPointType secondValue, FloatingPointType precision = (FloatingPointType) 0.00001)
Checks to see if two values are equal within a given precision.
getMonotonicBeatRange()
MonotonicBeatRange tracktion::engine::getMonotonicBeatRange (const SyncRange & r)
getBeatRange()
BeatRange tracktion::engine::getBeatRange (const SyncRange & r)
getNumSamples()
int64_t tracktion::engine::getNumSamples (const SyncRange & r)
convertPropertyToType()
template<typename VarType > void tracktion::engine::convertPropertyToType (juce::ValueTree & v, const juce::Identifier & id)
Ensures a property is a given type which can avoid having to parse a string every time it is read after loading from XML.
matchesAnyOf()
template<typename Type > bool tracktion::engine::matchesAnyOf (const Type & needle, const std::initializer_list< Type > & haystack)
Returns true if the needle is found in the haystack.
forEachItem()
template<typename Type , typename UnaryFunction > void tracktion::engine::forEachItem (const juce::Array< Type * > & items, const UnaryFunction & fn)
Calls a function object on each item in an array.
addValueTreeProperties()
template<typename... Others> void tracktion::engine::addValueTreeProperties (juce::ValueTree & v, const juce::Identifier & name, const juce::var & value, Others &&... others)
createValueTree()
template<typename... Properties> juce::ValueTree tracktion::engine::createValueTree (const juce::Identifier & name, Properties &&... properties)
removeInvalidValueTrees()
juce::Array< juce::ValueTree > & tracktion::engine::removeInvalidValueTrees (juce::Array< juce::ValueTree > & trees)
Strips out any invalid trees from the array.
getTreesOfType()
juce::Array< juce::ValueTree > tracktion::engine::getTreesOfType (const juce::Array< juce::ValueTree > & trees, const juce::Identifier & type)
Returns a new array with any trees without the given type removed.
getChildTreesRecursive()
void tracktion::engine::getChildTreesRecursive (juce::Array< juce::ValueTree > & result, const juce::ValueTree & tree)
renamePropertyRecursive()
void tracktion::engine::renamePropertyRecursive (juce::ValueTree & tree, const juce::Identifier & oldName, const juce::Identifier & newName, juce::UndoManager * um)
getOrCreateChildWithTypeAndProperty()
juce::ValueTree tracktion::engine::getOrCreateChildWithTypeAndProperty (juce::ValueTree & tree, const juce::Identifier & type, const juce::Identifier & property, const juce::var & propertyValue, juce::UndoManager * undoManager)
Looks for a chile with the given name and property, if one doesn't exist, creates it.
Variable Documentation
projectFileSuffix
const char* const tracktion::engine::projectFileSuffix = ".tracktion"
editFileSuffix
const char* const tracktion::engine::editFileSuffix = ".tracktionedit"
legacyEditFileSuffix
const char* const tracktion::engine::legacyEditFileSuffix = ".trkedit"
archiveFileSuffix
const char* const tracktion::engine::archiveFileSuffix = ".trkarch"
soundFileWildCard
const char* const tracktion::engine::soundFileWildCard = "*.wav;*.aiff;*.aif;*.ogg;*.mp3;*.flac;*.au;*.voc;*.caf;*.w64;*.rx2;*.rcy;*.rex;*.wfaf"
soundFileAndMidiWildCard
const char* const tracktion::engine::soundFileAndMidiWildCard = "*.wav;*.aiff;*.aif;*.ogg;*.mp3;*.mid;*.midi;*.flac;*.au;*.voc;*.caf;*.w64;*.rx2;*.rcy;*.rex;*.wfaf"
midiFileWildCard
const char* const tracktion::engine::midiFileWildCard = "*.midi;*.mid"
soundFileExtensions
const char* const tracktion::engine::soundFileExtensions = "wav;aiff;aif;ogg;mp3;flac;au;voc;caf;w64;rx2;rcy;rex;wfaf"
soundFileAndMidiExtensions
const char* const tracktion::engine::soundFileAndMidiExtensions = "wav;aiff;aif;ogg;mp3;flac;au;voc;caf;w64;rx2;rcy;rex;wfaf;midi;mid"
midiFileExtensions
const char* const tracktion::engine::midiFileExtensions = "midi;mid"
keyMapWildCard
const char* const tracktion::engine::keyMapWildCard = "*.tracktionkeys"
keyMapSuffix
const char* const tracktion::engine::keyMapSuffix = ".tracktionkeys"
customControllerFileSuffix
const char* const tracktion::engine::customControllerFileSuffix = ".trkctrlr"
customProgramSetWildcard
const char* const tracktion::engine::customProgramSetWildcard = "*.trkmidi;*.midnam"
customProgramSetFileSuffix
const char* const tracktion::engine::customProgramSetFileSuffix = ".trkmidi"
presetFileSuffix
const char* const tracktion::engine::presetFileSuffix = ".trkpreset"
rackFileSuffix
const char* const tracktion::engine::rackFileSuffix = ".trkrack"
scriptFileSuffix
const char* const tracktion::engine::scriptFileSuffix = ".tracktionscript"
grooveTemplateSuffix
const char* const tracktion::engine::grooveTemplateSuffix = ".trkgroove"
grooveTemplateWildCard
const char* const tracktion::engine::grooveTemplateWildCard = "*.trkgroove"
HertzTag_t
constexpr HertzTag tracktion::engine::HertzTag_t {} constexpr