TracktionEngine: tracktion_engine::AppFunctions Namespace Reference
tracktion_engine::AppFunctions Namespace Reference
Functions
void cut ()
void copy ()
void paste ()
bool pasteIntoProject (Project &)
void insertPaste ()
void deleteSelected ()
void deleteRegion ()
void deleteRegionAndCloseGapFromSelected ()
void deleteRegionAndCloseGap ()
void goToStart ()
void goToEnd ()
void markIn ()
void markOut ()
void start ()
void stop ()
void startStopPlay ()
void record ()
void toggleTimecode ()
void toggleLoop ()
void togglePunch ()
void toggleSnap ()
void toggleClick ()
void toggleMidiChase ()
void tabBack ()
void tabForward ()
void nudgeUp ()
void nudgeDown ()
void nudgeLeft ()
void nudgeRight ()
void zoomIn ()
void zoomOut ()
void scrollTracksUp ()
void scrollTracksDown ()
void scrollTracksLeft ()
void scrollTracksRight ()
void toggleEndToEnd ()
bool saveEdit ()
bool saveEditAs ()
void armOrDisarmAllInputs ()
void goToMarkIn ()
void goToMarkOut ()
void zoomTracksIn ()
void zoomTracksOut ()
void zoomToFitVertically ()
void zoomToFitHorizontally ()
void zoomToFitAll ()
void zoomToSelection ()
void moveToNextMarker ()
void moveToPrevMarker ()
void redo ()
void undo ()
void toggleScroll ()
void stopRecordingAndDiscard ()
void stopRecordingAndRestart ()
void insertTempoChange ()
void insertPitchChange ()
void insertTimeSigChange ()
void insertChord ()
void showHideVideo ()
void showHideAllPanes ()
void split ()
void toggleAutomationReadMode ()
void toggleAutomationWriteMode ()
void showHideBigMeters ()
void showHideInputs ()
void showHideOutputs ()
void showProjectScreen ()
void showSettingsScreen ()
void showEditScreen ()
void resetOverloads ()
void resetPeaks ()
void toggleTrackFreeze ()
Function Documentation
cut()
void tracktion_engine::AppFunctions::cut ()
copy()
void tracktion_engine::AppFunctions::copy ()
Referenced by tracktion_engine::PlayHeadPositionNode::process(), tracktion_engine::LevelMeasurerProcessingNode::process(), tracktion_graph::GainNode::process(), tracktion_graph::ForwardingNode::process(), NodeReader::readAudioSamples(), and tracktion_graph::AudioFifo::readOverwriting().
paste()
void tracktion_engine::AppFunctions::paste ()
pasteIntoProject()
bool tracktion_engine::AppFunctions::pasteIntoProject (Project &)
insertPaste()
void tracktion_engine::AppFunctions::insertPaste ()
deleteSelected()
void tracktion_engine::AppFunctions::deleteSelected ()
deleteRegion()
void tracktion_engine::AppFunctions::deleteRegion ()
deleteRegionAndCloseGapFromSelected()
void tracktion_engine::AppFunctions::deleteRegionAndCloseGapFromSelected ()
deleteRegionAndCloseGap()
void tracktion_engine::AppFunctions::deleteRegionAndCloseGap ()
goToStart()
void tracktion_engine::AppFunctions::goToStart ()
goToEnd()
void tracktion_engine::AppFunctions::goToEnd ()
markIn()
void tracktion_engine::AppFunctions::markIn ()
markOut()
void tracktion_engine::AppFunctions::markOut ()
start()
void tracktion_engine::AppFunctions::start ()
Referenced by tracktion_engine::ReferencedMaterialList::add(), tracktion_engine::ReferencedMaterialList::IntervalList::addInterval(), tracktion_graph::channelRangeWithStartAndLength(), and tracktion_graph::frameRangeWithStartAndLength().
stop()
void tracktion_engine::AppFunctions::stop ()
startStopPlay()
void tracktion_engine::AppFunctions::startStopPlay ()
record()
void tracktion_engine::AppFunctions::record ()
toggleTimecode()
void tracktion_engine::AppFunctions::toggleTimecode ()
toggleLoop()
void tracktion_engine::AppFunctions::toggleLoop ()
togglePunch()
void tracktion_engine::AppFunctions::togglePunch ()
toggleSnap()
void tracktion_engine::AppFunctions::toggleSnap ()
toggleClick()
void tracktion_engine::AppFunctions::toggleClick ()
toggleMidiChase()
void tracktion_engine::AppFunctions::toggleMidiChase ()
tabBack()
void tracktion_engine::AppFunctions::tabBack ()
tabForward()
void tracktion_engine::AppFunctions::tabForward ()
nudgeUp()
void tracktion_engine::AppFunctions::nudgeUp ()
nudgeDown()
void tracktion_engine::AppFunctions::nudgeDown ()
nudgeLeft()
void tracktion_engine::AppFunctions::nudgeLeft ()
nudgeRight()
void tracktion_engine::AppFunctions::nudgeRight ()
zoomIn()
void tracktion_engine::AppFunctions::zoomIn ()
zoomOut()
void tracktion_engine::AppFunctions::zoomOut ()
scrollTracksUp()
void tracktion_engine::AppFunctions::scrollTracksUp ()
scrollTracksDown()
void tracktion_engine::AppFunctions::scrollTracksDown ()
scrollTracksLeft()
void tracktion_engine::AppFunctions::scrollTracksLeft ()
scrollTracksRight()
void tracktion_engine::AppFunctions::scrollTracksRight ()
toggleEndToEnd()
void tracktion_engine::AppFunctions::toggleEndToEnd ()
saveEdit()
bool tracktion_engine::AppFunctions::saveEdit ()
saveEditAs()
bool tracktion_engine::AppFunctions::saveEditAs ()
armOrDisarmAllInputs()
void tracktion_engine::AppFunctions::armOrDisarmAllInputs ()
goToMarkIn()
void tracktion_engine::AppFunctions::goToMarkIn ()
goToMarkOut()
void tracktion_engine::AppFunctions::goToMarkOut ()
zoomTracksIn()
void tracktion_engine::AppFunctions::zoomTracksIn ()
zoomTracksOut()
void tracktion_engine::AppFunctions::zoomTracksOut ()
zoomToFitVertically()
void tracktion_engine::AppFunctions::zoomToFitVertically ()
zoomToFitHorizontally()
void tracktion_engine::AppFunctions::zoomToFitHorizontally ()
zoomToFitAll()
void tracktion_engine::AppFunctions::zoomToFitAll ()
zoomToSelection()
void tracktion_engine::AppFunctions::zoomToSelection ()
moveToNextMarker()
void tracktion_engine::AppFunctions::moveToNextMarker ()
moveToPrevMarker()
void tracktion_engine::AppFunctions::moveToPrevMarker ()
redo()
void tracktion_engine::AppFunctions::redo ()
undo()
void tracktion_engine::AppFunctions::undo ()
toggleScroll()
void tracktion_engine::AppFunctions::toggleScroll ()
stopRecordingAndDiscard()
void tracktion_engine::AppFunctions::stopRecordingAndDiscard ()
stopRecordingAndRestart()
void tracktion_engine::AppFunctions::stopRecordingAndRestart ()
insertTempoChange()
void tracktion_engine::AppFunctions::insertTempoChange ()
insertPitchChange()
void tracktion_engine::AppFunctions::insertPitchChange ()
insertTimeSigChange()
void tracktion_engine::AppFunctions::insertTimeSigChange ()
insertChord()
void tracktion_engine::AppFunctions::insertChord ()
showHideVideo()
void tracktion_engine::AppFunctions::showHideVideo ()
showHideAllPanes()
void tracktion_engine::AppFunctions::showHideAllPanes ()
split()
void tracktion_engine::AppFunctions::split ()
toggleAutomationReadMode()
void tracktion_engine::AppFunctions::toggleAutomationReadMode ()
toggleAutomationWriteMode()
void tracktion_engine::AppFunctions::toggleAutomationWriteMode ()
showHideBigMeters()
void tracktion_engine::AppFunctions::showHideBigMeters ()
showHideInputs()
void tracktion_engine::AppFunctions::showHideInputs ()
showHideOutputs()
void tracktion_engine::AppFunctions::showHideOutputs ()
showProjectScreen()
void tracktion_engine::AppFunctions::showProjectScreen ()
showSettingsScreen()
void tracktion_engine::AppFunctions::showSettingsScreen ()
showEditScreen()
void tracktion_engine::AppFunctions::showEditScreen ()
resetOverloads()
void tracktion_engine::AppFunctions::resetOverloads ()
resetPeaks()
void tracktion_engine::AppFunctions::resetPeaks ()
toggleTrackFreeze()
void tracktion_engine::AppFunctions::toggleTrackFreeze ()