TracktionEngine: tracktion_engine::benchmark_utilities Namespace Reference
tracktion_engine::benchmark_utilities Namespace Reference
Classes
struct BenchmarkOptions
Enumerations
enum MultiThreaded { MultiThreaded::no, MultiThreaded::yes }
enum LockFree { LockFree::no, LockFree::yes }
enum PoolMemoryAllocations { PoolMemoryAllocations::no, PoolMemoryAllocations::yes }
Functions
juce::String getDescription (const BenchmarkOptions &opts)
std::unique_ptr< tracktion_graph::Node > createNode (Edit &edit, ProcessState &processState, double sampleRate, int blockSize)
template<typename NodePlayerType >
void prepareRenderAndDestroy (juce::UnitTest &ut, juce::String editName, juce::String description, tracktion_graph::test_utilities::TestProcess< NodePlayerType > &testContext, tracktion_graph::PlayHeadState &playHeadState, MultiThreaded isMultiThreaded)
void renderEdit (juce::UnitTest &ut, BenchmarkOptions opts)
void renderEdit (juce::UnitTest &ut, juce::String editName, Edit &edit, tracktion_graph::test_utilities::TestSetup ts, MultiThreaded isMultiThreaded, LockFree isLockFree, tracktion_graph::ThreadPoolStrategy poolType)
std::unique_ptr< Edit > openEditfromArchiveData (Engine &engine, const char *data, int size)
std::unique_ptr< Edit > loadEditFromValueTree (Engine &engine, const juce::ValueTree &editState)
Loads an Edit from a value tree with no Project file references.
std::unique_ptr< Edit > openEditFromZipData (Engine &engine, const void *data, size_t numBytes)
Loads an Edit that was saved directly from the state to a GZip stream.
Enumeration Type Documentation
MultiThreaded
enum tracktion_engine::benchmark_utilities::MultiThreaded strong
Enumerator
no
yes
LockFree
enum tracktion_engine::benchmark_utilities::LockFree strong
Enumerator
no
yes
PoolMemoryAllocations
enum tracktion_engine::benchmark_utilities::PoolMemoryAllocations strong
Enumerator
no
yes
Function Documentation
getDescription()
juce::String tracktion_engine::benchmark_utilities::getDescription (const BenchmarkOptions & opts)
References tracktion_graph::test_utilities::getName(), tracktion_engine::benchmark_utilities::BenchmarkOptions::isLockFree, tracktion_engine::benchmark_utilities::BenchmarkOptions::isMultiThreaded, tracktion_engine::benchmark_utilities::BenchmarkOptions::poolMemoryAllocations, tracktion_engine::benchmark_utilities::BenchmarkOptions::poolType, tracktion_engine::benchmark_utilities::BenchmarkOptions::testSetup, and yes.
Referenced by renderEdit().
createNode()
std::unique_ptr<tracktion_graph::Node> tracktion_engine::benchmark_utilities::createNode (Edit & edit, ProcessState & processState, double sampleRate, int blockSize)
References tracktion_engine::createNodeForEdit(), and tracktion_engine::ProcessState::sampleRate.
Referenced by renderEdit().
prepareRenderAndDestroy()
template<typename NodePlayerType > void tracktion_engine::benchmark_utilities::prepareRenderAndDestroy (juce::UnitTest & ut, juce::String editName, juce::String description, tracktion_graph::test_utilities::TestProcess< NodePlayerType > & testContext, tracktion_graph::PlayHeadState & playHeadState, MultiThreaded isMultiThreaded)
References tracktion_engine::StopwatchTimer::getDescription(), tracktion_graph::test_utilities::TestProcess< NodePlayerType >::getNode(), tracktion_graph::test_utilities::TestProcess< NodePlayerType >::getNodePlayer(), tracktion_graph::test_utilities::TestProcess< NodePlayerType >::getStatisticsAndReset(), no, tracktion_graph::PlayHeadState::playHead, tracktion_graph::PlayHead::playSyncedToRange(), tracktion_graph::postordering, tracktion_graph::test_utilities::TestProcess< NodePlayerType >::processAll(), tracktion_graph::test_utilities::TestProcess< NodePlayerType >::setPlayHead(), and tracktion_graph::PerformanceMeasurement::Statistics::toString().
Referenced by renderEdit().
renderEdit() [1/2]
void tracktion_engine::benchmark_utilities::renderEdit (juce::UnitTest & ut, BenchmarkOptions opts)
References tracktion_graph::test_utilities::TestSetup::blockSize, createNode(), tracktion_engine::benchmark_utilities::BenchmarkOptions::edit, tracktion_engine::benchmark_utilities::BenchmarkOptions::editName, getDescription(), tracktion_engine::Edit::getLength(), tracktion_graph::test_utilities::TestProcess< NodePlayerType >::getNodePlayer(), tracktion_graph::getPoolCreatorFunction(), tracktion_engine::benchmark_utilities::BenchmarkOptions::isLockFree, tracktion_engine::benchmark_utilities::BenchmarkOptions::isMultiThreaded, tracktion_engine::benchmark_utilities::BenchmarkOptions::poolMemoryAllocations, tracktion_engine::benchmark_utilities::BenchmarkOptions::poolType, prepareRenderAndDestroy(), tracktion_graph::test_utilities::TestSetup::sampleRate, tracktion_engine::benchmark_utilities::BenchmarkOptions::testSetup, and yes.
Referenced by renderEdit().
renderEdit() [2/2]
void tracktion_engine::benchmark_utilities::renderEdit (juce::UnitTest & ut, juce::String editName, Edit & edit, tracktion_graph::test_utilities::TestSetup ts, MultiThreaded isMultiThreaded, LockFree isLockFree, tracktion_graph::ThreadPoolStrategy poolType)
References renderEdit().
openEditfromArchiveData()
std::unique_ptr<Edit> tracktion_engine::benchmark_utilities::openEditfromArchiveData (Engine & engine, const char * data, int size)
References tracktion_engine::TracktionArchiveFile::extractAll(), tracktion_engine::isTracktionEditFile(), and tracktion_engine::loadEditFromFile().
loadEditFromValueTree()
std::unique_ptr<Edit> tracktion_engine::benchmark_utilities::loadEditFromValueTree (Engine & engine, const juce::ValueTree & editState)
Loads an Edit from a value tree with no Project file references.
References tracktion_engine::ProjectItemID::createNewID(), tracktion_engine::Edit::forEditing, tracktion_engine::ProjectItemID::fromProperty(), and tracktion_engine::Edit::getDefaultNumUndoLevels().
Referenced by openEditFromZipData().
openEditFromZipData()
std::unique_ptr<Edit> tracktion_engine::benchmark_utilities::openEditFromZipData (Engine & engine, const void * data, size_t numBytes)
Loads an Edit that was saved directly from the state to a GZip stream.
References loadEditFromValueTree().