TracktionEngine: tracktion::engine::AppFunctions Namespace Reference
tracktion::engine::AppFunctions Namespace Reference
Functions
void cut ()
void copy ()
void paste ()
bool pasteIntoProject (Project &)
void insertPaste ()
void deleteSelected ()
void deleteRegion ()
void deleteRegionAndCloseGapFromSelected ()
void deleteRegionAndCloseGap ()
void goToStart ()
void goToEnd ()
void markIn (bool forceAtCursor)
void markOut (bool forceAtCursor)
void start ()
void stop ()
void startStopPlay ()
void continueStopPlay ()
void record ()
void toggleTimecode ()
void toggleLoop ()
void togglePunch ()
void toggleSnap ()
void toggleClick ()
void toggleMidiChase ()
void tabBack ()
void tabForward ()
void nudgeUp ()
void nudgeDown ()
void nudgeLeft ()
void nudgeRight ()
void zoomIn ()
void zoomOut ()
void scrollTracksUp ()
void scrollTracksDown ()
void scrollTracksLeft ()
void scrollTracksRight ()
void toggleEndToEnd ()
bool saveEdit ()
bool saveEditAs ()
void armOrDisarmAllInputs ()
void goToMarkIn ()
void goToMarkOut ()
void zoomTracksIn ()
void zoomTracksOut ()
void zoomToFitVertically ()
void zoomToFitHorizontally ()
void zoomToFitAll ()
void zoomToSelection ()
void moveToNextMarker ()
void moveToPrevMarker ()
void redo ()
void undo ()
void toggleScroll ()
bool isScrolling ()
void stopRecordingAndDiscard ()
void stopRecordingAndRestart ()
void insertTempoChange ()
void insertPitchChange ()
void insertTimeSigChange ()
void insertChord ()
void showHideVideo ()
void showHideMixer (bool fs)
void showHideMidiEditor (bool fs)
void showHideTrackEditor (bool zoom)
void showHideBrowser ()
void showHideActions ()
void performUserAction (int)
void showHideAllPanes ()
void split ()
void toggleAutomationReadMode ()
void toggleAutomationWriteMode ()
void showHideBigMeters ()
void showHideInputs ()
void showHideOutputs ()
void showProjectScreen ()
void showSettingsScreen ()
void showEditScreen ()
void resetOverloads ()
void resetPeaks ()
void toggleTrackFreeze ()
Function Documentation
cut()
void tracktion::engine::AppFunctions::cut ()
copy()
void tracktion::engine::AppFunctions::copy ()
Referenced by tracktion::engine::MidiMessageArray::mergeFromWithOffset(), tracktion::graph::GainNode::process(), tracktion::graph::ForwardingNode::process(), NodeReader::readAudioSamples(), and tracktion::graph::AudioFifo::readOverwriting().
paste()
void tracktion::engine::AppFunctions::paste ()
pasteIntoProject()
bool tracktion::engine::AppFunctions::pasteIntoProject (Project &)
insertPaste()
void tracktion::engine::AppFunctions::insertPaste ()
deleteSelected()
void tracktion::engine::AppFunctions::deleteSelected ()
deleteRegion()
void tracktion::engine::AppFunctions::deleteRegion ()
deleteRegionAndCloseGapFromSelected()
void tracktion::engine::AppFunctions::deleteRegionAndCloseGapFromSelected ()
deleteRegionAndCloseGap()
void tracktion::engine::AppFunctions::deleteRegionAndCloseGap ()
goToStart()
void tracktion::engine::AppFunctions::goToStart ()
goToEnd()
void tracktion::engine::AppFunctions::goToEnd ()
markIn()
void tracktion::engine::AppFunctions::markIn (bool forceAtCursor)
markOut()
void tracktion::engine::AppFunctions::markOut (bool forceAtCursor)
start()
void tracktion::engine::AppFunctions::start ()
Referenced by tracktion::engine::ReferencedMaterialList::add(), tracktion::engine::ReferencedMaterialList::IntervalList::addInterval(), tracktion::engine::MidiInputDevice::NoteFilterRange::set(), and tracktion::engine::PluginScanHelpers::PluginScanMasterProcess::waitForReply().
stop()
void tracktion::engine::AppFunctions::stop ()
startStopPlay()
void tracktion::engine::AppFunctions::startStopPlay ()
continueStopPlay()
void tracktion::engine::AppFunctions::continueStopPlay ()
record()
void tracktion::engine::AppFunctions::record ()
toggleTimecode()
void tracktion::engine::AppFunctions::toggleTimecode ()
toggleLoop()
void tracktion::engine::AppFunctions::toggleLoop ()
togglePunch()
void tracktion::engine::AppFunctions::togglePunch ()
toggleSnap()
void tracktion::engine::AppFunctions::toggleSnap ()
toggleClick()
void tracktion::engine::AppFunctions::toggleClick ()
toggleMidiChase()
void tracktion::engine::AppFunctions::toggleMidiChase ()
tabBack()
void tracktion::engine::AppFunctions::tabBack ()
tabForward()
void tracktion::engine::AppFunctions::tabForward ()
nudgeUp()
void tracktion::engine::AppFunctions::nudgeUp ()
nudgeDown()
void tracktion::engine::AppFunctions::nudgeDown ()
nudgeLeft()
void tracktion::engine::AppFunctions::nudgeLeft ()
nudgeRight()
void tracktion::engine::AppFunctions::nudgeRight ()
zoomIn()
void tracktion::engine::AppFunctions::zoomIn ()
zoomOut()
void tracktion::engine::AppFunctions::zoomOut ()
scrollTracksUp()
void tracktion::engine::AppFunctions::scrollTracksUp ()
scrollTracksDown()
void tracktion::engine::AppFunctions::scrollTracksDown ()
scrollTracksLeft()
void tracktion::engine::AppFunctions::scrollTracksLeft ()
scrollTracksRight()
void tracktion::engine::AppFunctions::scrollTracksRight ()
toggleEndToEnd()
void tracktion::engine::AppFunctions::toggleEndToEnd ()
saveEdit()
bool tracktion::engine::AppFunctions::saveEdit ()
saveEditAs()
bool tracktion::engine::AppFunctions::saveEditAs ()
armOrDisarmAllInputs()
void tracktion::engine::AppFunctions::armOrDisarmAllInputs ()
goToMarkIn()
void tracktion::engine::AppFunctions::goToMarkIn ()
goToMarkOut()
void tracktion::engine::AppFunctions::goToMarkOut ()
zoomTracksIn()
void tracktion::engine::AppFunctions::zoomTracksIn ()
zoomTracksOut()
void tracktion::engine::AppFunctions::zoomTracksOut ()
zoomToFitVertically()
void tracktion::engine::AppFunctions::zoomToFitVertically ()
zoomToFitHorizontally()
void tracktion::engine::AppFunctions::zoomToFitHorizontally ()
zoomToFitAll()
void tracktion::engine::AppFunctions::zoomToFitAll ()
zoomToSelection()
void tracktion::engine::AppFunctions::zoomToSelection ()
moveToNextMarker()
void tracktion::engine::AppFunctions::moveToNextMarker ()
moveToPrevMarker()
void tracktion::engine::AppFunctions::moveToPrevMarker ()
redo()
void tracktion::engine::AppFunctions::redo ()
undo()
void tracktion::engine::AppFunctions::undo ()
toggleScroll()
void tracktion::engine::AppFunctions::toggleScroll ()
isScrolling()
bool tracktion::engine::AppFunctions::isScrolling ()
stopRecordingAndDiscard()
void tracktion::engine::AppFunctions::stopRecordingAndDiscard ()
stopRecordingAndRestart()
void tracktion::engine::AppFunctions::stopRecordingAndRestart ()
insertTempoChange()
void tracktion::engine::AppFunctions::insertTempoChange ()
insertPitchChange()
void tracktion::engine::AppFunctions::insertPitchChange ()
insertTimeSigChange()
void tracktion::engine::AppFunctions::insertTimeSigChange ()
insertChord()
void tracktion::engine::AppFunctions::insertChord ()
showHideVideo()
void tracktion::engine::AppFunctions::showHideVideo ()
showHideMixer()
void tracktion::engine::AppFunctions::showHideMixer (bool fs)
showHideMidiEditor()
void tracktion::engine::AppFunctions::showHideMidiEditor (bool fs)
showHideTrackEditor()
void tracktion::engine::AppFunctions::showHideTrackEditor (bool zoom)
showHideBrowser()
void tracktion::engine::AppFunctions::showHideBrowser ()
showHideActions()
void tracktion::engine::AppFunctions::showHideActions ()
performUserAction()
void tracktion::engine::AppFunctions::performUserAction (int)
showHideAllPanes()
void tracktion::engine::AppFunctions::showHideAllPanes ()
split()
void tracktion::engine::AppFunctions::split ()
toggleAutomationReadMode()
void tracktion::engine::AppFunctions::toggleAutomationReadMode ()
toggleAutomationWriteMode()
void tracktion::engine::AppFunctions::toggleAutomationWriteMode ()
showHideBigMeters()
void tracktion::engine::AppFunctions::showHideBigMeters ()
showHideInputs()
void tracktion::engine::AppFunctions::showHideInputs ()
showHideOutputs()
void tracktion::engine::AppFunctions::showHideOutputs ()
showProjectScreen()
void tracktion::engine::AppFunctions::showProjectScreen ()
showSettingsScreen()
void tracktion::engine::AppFunctions::showSettingsScreen ()
showEditScreen()
void tracktion::engine::AppFunctions::showEditScreen ()
resetOverloads()
void tracktion::engine::AppFunctions::resetOverloads ()
resetPeaks()
void tracktion::engine::AppFunctions::resetPeaks ()
toggleTrackFreeze()
void tracktion::engine::AppFunctions::toggleTrackFreeze ()