TracktionEngine: tracktion::engine::details Namespace Reference
tracktion::engine::details Namespace Reference
Functions
Clip::FollowActionDurationType followActionDurationTypeFromString (juce::String)
juce::String toString (Clip::FollowActionDurationType)
Function Documentation
followActionDurationTypeFromString()
Clip::FollowActionDurationType tracktion::engine::details::followActionDurationTypeFromString (juce::String)
Referenced by juce::VariantConverter< tracktion::engine::Clip::FollowActionDurationType >::fromVar().
toString()
juce::String tracktion::engine::details::toString (Clip::FollowActionDurationType)
Referenced by tracktion::engine::ValueTreeComparator< Type >::compareElements(), and juce::VariantConverter< tracktion::engine::Clip::FollowActionDurationType >::toVar().