TracktionEngine: tracktion::graph::test_utilities Namespace Reference
tracktion::graph::test_utilities Namespace Reference
tracktion_graph » tracktion_graph
Classes
struct SineOscillator
struct TestContext
struct TestProcess
struct TestSetup
Functions
template<typename AudioFormatType >
void writeToFile (juce::File file, choc::buffer::ChannelArrayView< float > block, double sampleRate, int qualityOptionIndex)
Writes an audio buffer to a file.
template<typename AudioFormatType >
std::unique_ptr< juce::TemporaryFile > writeToTemporaryFile (choc::buffer::ChannelArrayView< float > block, double sampleRate, int qualityOptionIndex=0)
Writes an audio buffer to a file.
juce::String getName (ThreadPoolStrategy type)
Returns the ammount of internal memory allocated for buffers.
std::vector< ThreadPoolStrategy > getThreadPoolStrategies ()
void logGraph (Node &node)
Logs the graph structure to the console.
std::string createGraphDescription (Node &)
Returns the graph structure in a dot textual description.
template<typename AudioFormatType >
std::unique_ptr< juce::TemporaryFile > getSinFile (double sampleRate, double durationInSeconds, int numChannels=1, float frequency=220.0f, int qualityOptionIndex=-1)
template<typename AudioFormatType >
std::unique_ptr< juce::TemporaryFile > getSquareFile (double sampleRate, double durationInSeconds, int numChannels=1, float frequency=220.0f, int qualityOptionIndex=-1)
template<typename AudioFormatType >
std::unique_ptr< juce::TemporaryFile > getTimeEncodedFile (double sampleRate, TimeDuration duration, TimeDuration stepDuration, int numChannels=1, int qualityOptionIndex=-1)
template<typename AudioFormatType >
std::unique_ptr< juce::TemporaryFile > getTransientFile (double sampleRate, TimeDuration duration, TimePosition transientPos, float transientVal, int numChannels=1, int qualityOptionIndex=-1)
bool buffersAreEqual (const juce::AudioBuffer< float > &a, const juce::AudioBuffer< float > &b, float absSampleTolerance=0.0f)
bool buffersAreEqual (const choc::buffer::ChannelArrayView< float > &a, const choc::buffer::ChannelArrayView< float > &b, float absSampleTolerance=0.0f)
std::optional< std::pair< choc::buffer::FrameCount, float > > findFirstNonZeroSample (choc::buffer::MonoView< float > buffer)
Function Documentation
writeToFile()
template<typename AudioFormatType > void tracktion::graph::test_utilities::writeToFile (juce::File file, choc::buffer::ChannelArrayView< float > block, double sampleRate, int qualityOptionIndex)
Writes an audio buffer to a file.
References tracktion::graph::toAudioBuffer().
writeToTemporaryFile()
template<typename AudioFormatType > std::unique_ptr< juce::TemporaryFile > tracktion::graph::test_utilities::writeToTemporaryFile (choc::buffer::ChannelArrayView< float > block, double sampleRate, int qualityOptionIndex = 0)
Writes an audio buffer to a file.
getName()
juce::String tracktion::graph::test_utilities::getName (ThreadPoolStrategy type)
Returns the ammount of internal memory allocated for buffers.
References tracktion::graph::conditionVariable, tracktion::graph::hybrid, tracktion::graph::lightweightSemaphore, tracktion::graph::lightweightSemHybrid, tracktion::graph::realTime, and tracktion::graph::semaphore.
Referenced by tracktion::engine::benchmark_utilities::getDescription().
getThreadPoolStrategies()
std::vector< ThreadPoolStrategy > tracktion::graph::test_utilities::getThreadPoolStrategies ()
References tracktion::graph::conditionVariable, tracktion::graph::hybrid, tracktion::graph::lightweightSemaphore, tracktion::graph::lightweightSemHybrid, tracktion::graph::realTime, and tracktion::graph::semaphore.
logGraph()
void tracktion::graph::test_utilities::logGraph (Node & node)
Logs the graph structure to the console.
References tracktion::graph::Node::getDirectInputNodes().
createGraphDescription()
std::string tracktion::graph::test_utilities::createGraphDescription (Node &)
Returns the graph structure in a dot textual description.
Save this to a file and then run it through graphviz's dot program to plot the graph. E.g. cat output.txt | dot -Tsvg > output.svg
getSinFile()
template<typename AudioFormatType > std::unique_ptr< juce::TemporaryFile > tracktion::graph::test_utilities::getSinFile (double sampleRate, double durationInSeconds, int numChannels = 1, float frequency = 220.0f, int qualityOptionIndex = -1)
getSquareFile()
template<typename AudioFormatType > std::unique_ptr< juce::TemporaryFile > tracktion::graph::test_utilities::getSquareFile (double sampleRate, double durationInSeconds, int numChannels = 1, float frequency = 220.0f, int qualityOptionIndex = -1)
getTimeEncodedFile()
template<typename AudioFormatType > std::unique_ptr< juce::TemporaryFile > tracktion::graph::test_utilities::getTimeEncodedFile (double sampleRate, TimeDuration duration, TimeDuration stepDuration, int numChannels = 1, int qualityOptionIndex = -1)
getTransientFile()
template<typename AudioFormatType > std::unique_ptr< juce::TemporaryFile > tracktion::graph::test_utilities::getTransientFile (double sampleRate, TimeDuration duration, TimePosition transientPos, float transientVal, int numChannels = 1, int qualityOptionIndex = -1)
buffersAreEqual() [1/2]
bool tracktion::graph::test_utilities::buffersAreEqual (const juce::AudioBuffer< float > & a, const juce::AudioBuffer< float > & b, float absSampleTolerance = 0.0f)
Referenced by buffersAreEqual().
buffersAreEqual() [2/2]
bool tracktion::graph::test_utilities::buffersAreEqual (const choc::buffer::ChannelArrayView< float > & a, const choc::buffer::ChannelArrayView< float > & b, float absSampleTolerance = 0.0f)
References buffersAreEqual(), and tracktion::graph::toAudioBuffer().
findFirstNonZeroSample()
std::optional< std::pair< choc::buffer::FrameCount, float > > tracktion::graph::test_utilities::findFirstNonZeroSample (choc::buffer::MonoView< float > buffer)