TracktionEngine: tracktion::engine::MidiNodeHelpers Namespace Reference
tracktion::engine::MidiNodeHelpers Namespace Reference
tracktion_engine » playback
Functions
void createMessagesForTime (MidiMessageArray &destBuffer, juce::MidiMessageSequence &sourceSequence, double time, juce::Range< int > channelNumbers, LiveClipLevel &clipLevel, bool useMPEChannelMode, MPESourceID midiSourceID, juce::Array< juce::MidiMessage > &controllerMessagesScratchBuffer)
void createNoteOffs (MidiMessageArray &destination, const juce::MidiMessageSequence &sourceSequence, MPESourceID midiSourceID, double time, double midiTimeOffset, bool isPlaying)
void sanityCheckMidiBuffer (const MidiMessageArray &midi, double maxTimeStamp)
Asserts if any MIDI messages are timestamped outside the given range.
void createNoteOffs (ActiveNoteList &activeNoteList, MidiMessageArray &destination, MPESourceID midiSourceID, double midiTimeOffset, bool isPlaying)
Function Documentation
createMessagesForTime()
void tracktion::engine::MidiNodeHelpers::createMessagesForTime (MidiMessageArray & destBuffer, juce::MidiMessageSequence & sourceSequence, double time, juce::Range< int > channelNumbers, LiveClipLevel & clipLevel, bool useMPEChannelMode, MPESourceID midiSourceID, juce::Array< juce::MidiMessage > & controllerMessagesScratchBuffer)
References tracktion::engine::MidiMessageArray::addMidiMessage(), tracktion::engine::LiveClipLevel::getGain(), tracktion::engine::LiveClipLevel::isMute(), and tracktion::engine::MPEStartTrimmer::reconstructExpression().
createNoteOffs() [1/2]
void tracktion::engine::MidiNodeHelpers::createNoteOffs (MidiMessageArray & destination, const juce::MidiMessageSequence & sourceSequence, MPESourceID midiSourceID, double time, double midiTimeOffset, bool isPlaying)
References tracktion::engine::MidiMessageArray::addMidiMessage().
sanityCheckMidiBuffer()
void tracktion::engine::MidiNodeHelpers::sanityCheckMidiBuffer (const MidiMessageArray & midi, double maxTimeStamp)
Asserts if any MIDI messages are timestamped outside the given range.
createNoteOffs() [2/2]
void tracktion::engine::MidiNodeHelpers::createNoteOffs (ActiveNoteList & activeNoteList, MidiMessageArray & destination, MPESourceID midiSourceID, double midiTimeOffset, bool isPlaying)
References tracktion::engine::MidiMessageArray::addMidiMessage(), tracktion::engine::ActiveNoteList::iterate(), and tracktion::engine::ActiveNoteList::reset().