TracktionEngine: tracktion_engine Namespace Reference
tracktion_engine Namespace Reference
Namespaces
AppFunctions
benchmark_utilities
Click
ClipConstants
Constraints for clip speeds.
IDs
modifier
ModifierCommon
PredefinedWavetable
RackNodeBuilder
TracktionBinaryData
Classes
class AbletonLink
struct ActiveEdits
A list of all currently open edits.
struct ActiveNoteList
class AirWindowsCallback
class AirWindowsPlugin
class AlphaTrackControlSurface
struct ARADocumentHolder
class ArrangerClip
class ArrangerTrack
A track similar to the MarkerTrack but can be used to move sections of an Edit around.
struct AsyncCaller
Asyncronously call a function.
struct AsyncFunctionCaller
Holds a list of function objects and enables you to call them asyncronously.
class AudioBufferSnapshot
class AudioClipBase
Base class for Clips that produce some kind of audio e.g.
struct AudioFadeCurve
class AudioFifo
class AudioFile
class AudioFileCache
class AudioFileFormatManager
Keeps a list of available wave formats and can create a format object for a file.
struct AudioFileInfo
class AudioFileManager
struct AudioFileUtils
class AudioFileWriter
Smart wrapper for writing to an audio file.
class AudioMidiFifo
class AudioNode
Base class for nodes in an audio playback graph.
struct AudioNodeProperties
Holds some really basic properties of a node.
class AudioProxyGenerator
struct AudioRenderContext
Rendering target info.
class AudioScratchBuffer
An audio scratch buffer that has pooled storage.
class AudioSegmentList
Holds a list of audio regions for playback of things like warp time.
class AudioTrack
class AutomatableEditItem
Base class for elements that have some kind of automatable parameters.
class AutomatableParameter
class AutomatableParameterTree
class AutomationCurve
class AutomationDragDropTarget
Components can implement this to let things know which automatable parameter they control.
struct AutomationIterator
class AutomationRecordManager
Stores automation data as it's being read in, and writes it back to the edit when recording finishes.
class AutomationTrack
class AuxReturnPlugin
class AuxSendNode
Node for an aux send.
class AuxSendPlugin
class BackgroundJobManager
Manages a set of background tasks that can be run concurrently on a background thread.
class BandlimitedWaveLookupTables
struct BeatDetect
class Benchmark
An indiviual Benchmark.
struct BenchmarkDescription
Describes a benchmark.
class BenchmarkList
Contans a list of BenchmarkResult[s].
struct BenchmarkResult
Holds the duration a benchmark took to run.
struct BlockingFunction
class BreakpointOscillatorModifier
struct ChannelIndex
Describes a channel of a WaveInputDevice or WaveOutputDevice by specifying the channel index in the global device's audio buffer and the purpose as an AudioChannelSet::ChannelType e.g.
class Chord
class ChordClip
class ChordTrack
class ChorusPlugin
class ClickGenerator
Generates click audio and MIDI and adds them to the provided buffer.
class ClickNode
Adds audio and MIDI clicks to the input buffers.
class Clip
A clip in an edit.
class Clipboard
class ClipEffect
class ClipEffects
struct ClipLevel
Holds a clip's level state.
struct ClipPosition
class ClipTrack
class CollectionClip
class CombiningAudioNode
An AudioNode that mixes a sequence of clips of other nodes.
class CombiningNode
An Node that mixes a sequence of clips of other nodes.
class CompFactory
class CompManager
class CompressorPlugin
class ConstrainedCachedValue
A CachedValue that can take a std::function to constrain its value.
class ControlSurface
Base class for types of control surface.
struct CrashStackTracer
Used by the CRASH_TRACER macros to help provide a useful crash log of the stack.
struct CreateAudioNodeParams
A collection of settings that are generally needed when asking edit model objects to create AudioNodes to render them.
struct CreateNodeParams
Contains options for Edit Node content creation.
class CurveEditor
class CurveEditorPoint
struct CurvePoint
class CustomControlSurface
struct DbTimePair
struct DeadMansPedalMessage
This RAII class saves a property which will be reported at startup as a failure if the app disappears before its destructor is called.
struct DelayBufferBase
class DelayPlugin
class DeviceManager
struct DiscreteLabelledParameter
struct Ditherer
An extremely naive ditherer.
class Edit
The Tracktion Edit class!
class EditClip
This is the main source of an Edit clip and is responsible for managing its properties.
struct EditDeleter
Deferred Edit object deleter.
class EditFileOperations
Contains methods for saving an Edit to a file.
class EditInputDevices
class EditInsertPoint
class EditItem
Base class for objects that live inside an edit - e.g.
struct EditItemCache
struct EditItemID
ID for objects of type EditElement - e.g.
struct EditLimits
Contains the limits of the various elements that can be added to an Edit.
struct EditNodeBuilder
class EditPlaybackContext
class EditRenderJob
class EditSnapshot
Holds a snapshot of an Edit file of the last time it was saved.
struct EditTimecodeRemapperSnapshot
Takes a copy of all the beat related things in an edit in terms of bars/beats and then remaps these after a tempo change.
struct EditTimeRange
class Engine
The Engine is the central class for all tracktion sessions.
class EngineBehaviour
Provides custom handlers to control various aspects of the engine's behaviour.
class EnvelopeFollowerModifier
class EqualiserPlugin
class ExpEnvelope
class Exportable
An interface for objects within an edit that can be exported.
class ExportJob
class ExternalAutomatableParameter
class ExternalController
Acts as a holder for a ControlSurface object.
class ExternalControllerManager
Keeps a list of external controllers and keeps them connected to the right MIDI in/out devices.
class ExternalPlayheadSynchroniser
An ExternalPlayheadSynchroniser is used to synchronise the internal Edit's playhead with an AudioProcessor, for use in plugins.
class ExternalPlugin
class FadeInOutAudioNode
An AudioNode that fades its input node in/out at given times.
struct FadeInOutEffect
class FadeInOutNode
A Node that fades in and out given time regions.
struct FileDragList
class FloatAudioFormat
A raw, proprietary, simple floating point format used for freeze files, etc.
class FolderTrack
class FourOscPlugin
class FreezePointPlugin
class GrooveTemplate
class GrooveTemplateManager
Looks after the list of groove templates.
class HostedAudioDeviceInterface
The HostedAudioDeviceInterface allows an application or plugin to pass audio and midi buffers to the engine, rather than the engine directly opening the audio devices.
class HostedMidiInputDeviceNode
A Node that intercepts MIDI from a plugin callback and inserts it in to the playback graph.
class IconProG2
class ImpulseResponsePlugin
ImpulseResponsePlugin that loads an impulse response and applies it the audio stream.
class InputDevice
Represents an input device.
class InputDeviceInstance
struct InputProvider
class InsertPlugin
class InsertReturnNode
The return node hooks into the input device and fills the insert's return buffer with data from the input.
class InsertSendNode
The send node picks up audio/MIDI data from the InsertPlugin and then its output will be sent to the corresponding OutputDevice.
class InsertSendReturnDependencyNode
This is a bit confusing but is required to ensure the following set of dependencies in the graph: InsertSendNode -> InsertPluginNode InsertReturnNode ->
struct InvertEffect
struct KeyResult
class LambdaTimer
class LAMEManager
Manages the LAME location property and an AudioFormat if the LAME encoder is provided.
class LatencyPlugin
A test plugin that introduces latency to the incomming signal.
class LevelMeasurer
Monitors the levels of buffers that are passed in, and keeps peak values, overloads, etc., for display in a level meter component.
class LevelMeasurerProcessingNode
A Node that introduces latency to balance the latency at the root Node and its position in the graph.
class LevelMeasuringNode
A Node that passes its incomming audio and MIDI through a LevelMeasurer.
class LevelMeterPlugin
class LFOModifier
class LinEnvelope
struct LiveClipLevel
Provides a thread-safe way to share a clip's levels with an audio engine without worrying about the Clip being deleted from underneath you.
class LiveMidiInjectingNode
A Node that injects MIDI message in to the stream, for keyboard key entry, note previews and MIDI step entry etc.
class LiveMidiOutputNode
A Node that calls the listeners of an AudioTrack with any incomming MIDI.
class LoopInfo
class LowPassPlugin
class MackieC4
class MackieMCU
class MackieXT
class MacroParameter
A MacroParameter is an AutomatableParameter which is a collection of Mappings.
class MacroParameterElement
Base class for elements which can contain macro parameters.
class MacroParameterList
struct MakeMonoEffect
class MarkerClip
class MarkerManager
struct MarkerSetting
class MarkerTrack
class MasterTrack
A track to represent the master plugins.
class MelodyneFileReader
class MelodyneNode
Plays back a Melodyne plugin.
class MessageThreadCallback
Calls a function on the message thread checking a calling thread for an exit signal.
class MidiAssignable
Base class for things that can be assigned to external control surfaces, not plugin paramters.
struct MidiChannel
Represents a MIDI channel 1-16, and also contains extra ID bits to encode info about the event's origin.
class MidiClip
class MidiCompManager
class MidiControllerEvent
struct MidiExpression
class MidiInputDevice
class MidiInputDeviceNode
A Node that intercepts incoming live MIDI and inserts it in to the playback graph.
class MidiLearnState
Manages the Midi learn state and Listener interface to notify subclasses when the state changes.
class MidiList
struct MidiMessageArray
class MidiModifierPlugin
class MidiNode
A Node that plays MIDI data from a MidiMessageSequence, at a specific MIDI channel.
class MidiNote
class MidiNoteDispatcher
class MidiOutputDevice
class MidiOutputDeviceInstance
class MidiOutputDeviceInstanceInjectingNode
A Node that injects the MIDI buffer of its input to the MidiOutputDevice.
class MidiPatchBayPlugin
class MidiProgramManager
class MidiSysexEvent
class MIDITrackerModifier
struct Modifier
Bass class for parameter Modifiers.
class ModifierList
Holds a list of Modifiers that have been added to a Track.
class ModifierNode
Node for processing a Modifier.
struct ModifierTimer
Base class for objects which need to know about the global Edit time every block.
class MouseHoverDetector
struct MPEStartTrimmer
If you need to play back MPE data from a point after the data starts, it's important to reconstruct the expression values immediately preceding the last note-on, then the note on, then the last expression values before the trim point.
class MultiThreadedNodePlayer
Plays back a Node with PlayHeadState and ProcessState.
class MultiVoiceOscillator
struct MuteAudioNode
class NodeRenderContext
Holds the state of an audio render procedure so it can be rendered in blocks.
struct NormaliseEffect
class NovationRemoteSl
struct OldEditConversion
Logic for reading legacy tracktion edit files.
class Oscillator
class OutputDevice
Base class for audio or midi output devices, to which a track's output can be sent.
class OutputDeviceInstance
class ParameterChangeHandler
Manages a set of AutomatableParameters for an Edit and notifies controllers and registered listeners when they change.
class ParameterControlMappings
Controls the set of midi-controller-to-parameter mappings.
class ParameterisableDragDropSource
struct ParameterSetting
class PatchBayPlugin
class PatternGenerator
class PhaserPlugin
class PhysicalMidiInputDevice
struct Pitch
class PitchSequence
class PitchSetting
struct PitchShiftEffect
class PitchShiftPlugin
struct PlaybackInitialisationInfo
Passed into AudioNodes when they are being initialised, to give them useful contextual information that they may need.
class PlayHead
class PlayHeadPositionNode
A Node that calculates a position to show visually what time is currently being processed by the graph based on its internal latency.
class Plugin
class PluginAudioNode
class PluginCache
struct PluginComponent
Components that represent a Plugin should inherit from this to ensure they are correctly notified when their colour changes e.g.
struct PluginCreationInfo
struct PluginEffect
struct PluginInitialisationInfo
Passed into Plugins when they are being initialised, to give them useful contextual information that they may need.
class PluginList
Holds a sequence of plugins.
class PluginManager
class PluginNode
Node for processing a plugin.
struct PluginRenderContext
The context passed to plugin render methods to provide it with buffers to fill.
struct PluginWetDryAutomatableParam
specialised AutomatableParameter for wet/dry.
struct PluginWindowState
struct ProcessState
Holds the state of a process call.
class Project
A tracktion project.
class ProjectItem
Represents a file-based resource that is used in a project.
class ProjectItemID
An ID representing one of the items in a Project.
class ProjectManager
class ProjectSearchIndex
class PropertyStorage
Create a subclass of PropertyStorage to customize how settings are saved and recalled.
class QuantisationType
struct RackConnection
class RackInstance
class RackInstanceNode
Sends an input Node to a Rack bus handling the channel mapping and channel gain levels.
class RackNodePlayer
Simple processor for a Node which uses an InputProvider to pass input in to the graph.
class RackReturnNode
Sends an input Node to a Rack bus handling the channel mapping and channel gain levels.
class RackType
class RackTypeList
struct Ramp
A ramp which goes between 0 and 1 over a set duration.
class RandomModifier
class RecordingThumbnailManager
class ReferenceCountedValueTree
Holds a ValueTree as a ReferenceCountedObject.
class ReferencedMaterialList
A list of all the source files needed by an edit (or a section of an edit).
class RemoteSLCompact
class Renderer
class RenderManager
Manages a set of reference counted render jobs and can be used to retrieve matching jobs or create new ones.
class RenderOptions
Represents a set of user properties used to control a render operation, using a ValueTree to hold them so that they can be saved and reloaded.
class ReverbPlugin
struct ReverseEffect
class ReverseRenderJob
class SamplerPlugin
class Scale
struct ScopedBenchmark
Helper class for measuring a benchmark and adding it to the singleton BenchmarkList list.
struct ScopedCpuMeter
struct ScopedDirectoryDeleter
struct ScopedPluginUnloadInhibitor
class ScopedSteadyLoad
class ScopedWaitCursor
Shows and hides the mouse wait cursor where appropriate.
class SearchOperation
class Selectable
Base class for things that can be selected, and whose properties can appear in the properties panel.
class SelectableClass
Represents a type of object that can be selected.
class SelectableClassWithPan
class SelectableClassWithVolume
struct SelectableList
A list of Selectables, similar to a juce::Array but contains a cached list of the SelectableClasses for each entry.
class SelectableListener
class SelectedMidiEvents
Represents a set of selected MIDI notes.
class SelectionManager
Manages a list of items that are currently selected.
class SharedLevelMeasurer
A shared level measurer that can be used by several threads to provide a total output level.
class SharedLevelMeasuringNode
Applies a SharedLevelMeter to the audio passing through this node.
class SimpleLFO
class SingleInputAudioNode
class SmartThumbnail
SmartThumnail automatically tracks changes to an AudioFile and will update its cache if the file changes.
class SoftwareMidiOutputDevice
Create a software midi port on macOS.
struct SortedValueTreeObjectList
class SourceFileReference
This class wraps a string that is generally held in a 'source' property, and which is a reference to some sort of file, either in the form of a local filename or as a project ID that can be resolved.
struct SpeedFadeDescription
Describes the time and type of the speed fade in/outs.
class SpeedRampAudioNode
An AudioNode that speeds up and slows down its input node in/out at given times.
class SpeedRampWaveNode
An Node that plays back a wave file.
struct Spline
An interpolated spline curve, used by the EQ to draw its response graph.
class StepClip
class StepModifier
struct StepVolumeEffect
struct StopwatchTimer
class SubSampleWaveAudioNode
struct SuffixedParameter
class TempoDetect
Uses the SoundTouch BPMDetect class to guess the tempo of some audio.
class TemporaryFileManager
Holds info about where temp files should go, and tidies up old ones when needed.
class TempoSequence
Holds a list of TempoSetting objects, to form a sequence of tempo changes.
class TempoSequencePosition
Iterates a TempoSequence.
class TempoSetting
A tempo value, as used in a TempoSequence.
class TempoTrack
A track to represent the "global" items such as tempo, key changes etc.
class TextPlugin
class ThreadPoolJobWithProgress
struct TimecodeDisplayFormat
A timecode display mode, e.g.
struct TimecodeDisplayIterator
Iterates along a timeline for drawing things like the ticks on the timebar.
class TimecodeDuration
Stores a duration in both beats and seconds.
struct TimecodeSnapType
A snap mode, e.g.
class TimedMutingAudioNode
class TimedMutingNode
A Node that mutes its input at specific time ranges.
class TimeSigSetting
class TimeStretcher
Handles time/pitch stretching using various supported libraries.
class TimeStretchingWaveNode
Node that reads from a file node and timestretches its output.
class ToneGeneratorPlugin
class Track
Base class for tracks which contain clips and plugins and can be added to Edit[s].
struct TrackAutomationSection
Holds a reference to a section of automation for a given Track.
class TrackCompManager
struct TrackInsertPoint
Defines the place to insert Track[s].
class TrackItem
Base class for EditItems that live in a Track, e.g.
struct TrackList
An iterable list of Track[s] that live either in an Edit or as subtracks of a Track.
class TrackMidiInputDeviceNode
A Node that takes MIDI from the output of a track and sends it to its corresponding InputDevice.
class TrackMuteState
Holds the state of a Track and if its contents/plugins should be played or not.
class TrackMutingNode
A Node that handles muting/soloing of its input node, according to the audibility of a track.
class TrackOutput
Represents the destination output device(s) for a track.
struct TrackSection
Defines a time raneg sectin of a Track.
class TracktionArchiveFile
class TracktionEngineNode
Base class for Nodes that provides information about the current process call.
class TracktionNodePlayer
Plays back a Node with PlayHeadState and ProcessState.
class TracktionThumbnail
class TrackWaveInputDeviceNode
A Node that takes audio from the output of a track and sends it to its corresponding InputDevice.
struct TransparentToMouseInTrackItemComp
class TransportControl
Controls the transport of an Edit's playback.
class TranzportControlSurface
class UIBehaviour
Create a subclass of UIBehaviour to custom UI elements created by the engine.
class ValueSmoother
Smooths a value between 0 and 1 at a constant rate.
struct ValueTreeAllEventListener
struct ValueTreeComparator
class ValueTreeObjectList
class VCAPlugin
The VCA plugin sits on a folder track to control the overall level of all the volume/pan plugins in its child tracks.
class VirtualMidiInputDevice
class VolumeAndPanPlugin
The built-in Tracktion volume/pan plugin.
struct VolumeEffect
class VSTXML
struct WarpMarker
A WarpMarker is a point that maps from a linear "source" time to a "warped" time.
struct WarpTimeEffect
class WarpTimeFactory
A WarpTimeFactory manages WarpTimeManagers for Clips living in an Edit.
class WarpTimeManager
A WarpTimeManager contains a list of WarpMarkers and some source material and maps times from a linear "view" time to a "wapred" source time.
class WarpTimeRenderJob
class WaveAudioClip
An audio clip that uses an audio file as its source.
class WaveAudioNode
An AudioNode that plays back a wave file.
class WaveCompManager
struct WaveDeviceDescription
Describes a WaveDevice from which the WaveOutputDevice and WaveInputDevice lists will be built.
class WaveInputDevice
A (virtual) audio input device.
class WaveInputDeviceNode
A Node that intercepts incoming live audio and inserts it in to the playback graph.
class WaveInputRecordingThread
class WaveNode
An Node that plays back a wave file.
class WaveOutputDevice
A (virtual) audio output device.
class WaveOutputDeviceInstance
Typedefs
using SampleCount = int64_t
using SampleRange = juce::Range< SampleCount >
using HashCode = int64_t
Enumerations
enum CloseGap { CloseGap::no, CloseGap::yes }
An enum to specify if gaps deleted should be closed or not.
enum MoveClipAction { MoveClipAction::moveToEndOfLast, MoveClipAction::moveToStartOfNext, MoveClipAction::moveStartToCursor, MoveClipAction::moveEndToCursor }
Enum to dictate move clip behaviour.
enum TimecodeType {
TimecodeType::millisecs, TimecodeType::barsBeats, TimecodeType::fps24, TimecodeType::fps25,
TimecodeType::fps30
}
enum PanLaw {
PanLawDefault = -1, PanLawLinear = 0, PanLaw2point5dBCenter = 1, PanLaw3dBCenter = 2,
PanLaw4point5dBCenter = 3, PanLaw6dBCenter = 4
}
All laws have been designed to be equal-power, excluding linear respectively.
enum SettingID {
SettingID::invalid, SettingID::addAntiDenormalNoise, SettingID::audio_device_setup, SettingID::audiosettings,
SettingID::autoFreeze, SettingID::autoTempoMatch, SettingID::autoTempoDetect, SettingID::automapVst,
SettingID::automapNative, SettingID::automapGuids1, SettingID::automapGuids2, SettingID::cacheSizeSamples,
SettingID::compCrossfadeMs, SettingID::countInMode, SettingID::clickTrackMidiNoteBig, SettingID::clickTrackMidiNoteLittle,
SettingID::clickTrackSampleSmall, SettingID::clickTrackSampleBig, SettingID::crossfadeBlock, SettingID::cpu,
SettingID::customMidiControllers, SettingID::deadMansPedal, SettingID::defaultMidiOutDevice, SettingID::defaultWaveOutDevice,
SettingID::defaultMidiInDevice, SettingID::defaultWaveInDevice, SettingID::externControlIn, SettingID::externControlOut,
SettingID::externControlShowSelection, SettingID::externControlSelectionColour, SettingID::externControlEnable, SettingID::externOscInputPort,
SettingID::externOscOutputPort, SettingID::externOscOutputAddr, SettingID::filterControlMappingPresets, SettingID::filterGui,
SettingID::fitClipsToRegion, SettingID::findExamples, SettingID::freezePoint, SettingID::hasEnabledMidiDefaultDevs,
SettingID::glideLength, SettingID::grooveTemplates, SettingID::knownPluginList, SettingID::knownPluginList64,
SettingID::lameEncoder, SettingID::lastClickTrackLevel, SettingID::lastEditRender, SettingID::lowLatencyBuffer,
SettingID::MCUoneTouchRecord, SettingID::maxLatency, SettingID::midiin, SettingID::midiout,
SettingID::midiEditorOctaves, SettingID::midiProgramManager, SettingID::newMarker, SettingID::numThreadsForPluginScanning,
SettingID::projectList, SettingID::projects, SettingID::recentProjects, SettingID::renameClipRenamesSource,
SettingID::renameMode, SettingID::renderRecentFilesList, SettingID::resetCursorOnStop, SettingID::retrospectiveRecord,
SettingID::reWireEnabled, SettingID::safeRecord, SettingID::sendControllerOffMessages, SettingID::simplifyAfterRecording,
SettingID::snapCursor, SettingID::tempDirectory, SettingID::trackExpansionMode, SettingID::use64Bit,
SettingID::xFade, SettingID::xtCount, SettingID::xtIndices, SettingID::virtualmididevices,
SettingID::virtualmidiin, SettingID::useSeparateProcessForScanning, SettingID::useRealtime, SettingID::wavein,
SettingID::waveout, SettingID::windowsDoubleClick, SettingID::renderFormat, SettingID::trackRenderSampRate,
SettingID::trackRenderBits, SettingID::bypassFilters, SettingID::markedRegion, SettingID::editClipRenderSampRate,
SettingID::editClipRenderBits, SettingID::editClipRenderDither, SettingID::editClipRealtime, SettingID::editClipRenderStereo,
SettingID::editClipRenderNormalise, SettingID::editClipRenderRMS, SettingID::editClipRenderRMSLevelDb, SettingID::editClipRenderPeakLevelDb,
SettingID::editClipPassThroughFilters, SettingID::exportFormat, SettingID::renderOnlySelectedClips, SettingID::renderOnlyMarked,
SettingID::renderNormalise, SettingID::renderRMS, SettingID::renderRMSLevelDb, SettingID::renderPeakLevelDb,
SettingID::renderTrimSilence, SettingID::renderSampRate, SettingID::renderStereo, SettingID::renderBits,
SettingID::renderDither, SettingID::quality, SettingID::addId3Info, SettingID::realtime,
SettingID::passThroughFilters
}
A list of settings the engine will get and set.
Functions
juce::Array< KeyResult > determineKeyOfNotes (const juce::Array< MidiNote * > &notes)
template<typename AssignmentType >
juce::ReferenceCountedArray< AssignmentType > getAssignmentsOfType (const AutomatableParameter &ap)
Returns all the Assignments of a specific type.
template<typename ModifierType >
juce::Array< ModifierType * > getModifiersOfType (const AutomatableParameter &ap)
Returns all the modifers in use of a specific type.
juce::Array< AutomatableParameter * > getAllAutomatableParameter (Edit &)
Returns all the automatable parameters in an Edit.
template<typename AssignmentType , typename ModifierSourceType >
juce::ReferenceCountedArray< AssignmentType > getAssignmentsForSource (Edit &edit, const ModifierSourceType &source)
Iterates an Edit looking for all parameters that assigned to a given parameter.
AutomatableParameter::ModifierSource * getSourceForAssignment (const AutomatableParameter::ModifierAssignment &)
Iterates an Edit looking for the source of this assignment.
juce::ReferenceCountedArray< AutomatableParameter > getAllParametersBeingModifiedBy (Edit &, AutomatableParameter::ModifierSource &)
Iterates an Edit looking for all parameters that are being modified by the given ModifierSource.
AutomatableParameter * getParameter (AutomatableParameter::ModifierAssignment &)
Iterates an Edit looking for the parameter that this ModifierAssignment has been made from.
int getIntParamValue (const AutomatableParameter &ap)
Returns an int version of an AutomatableParameter.
bool getBoolParamValue (const AutomatableParameter &ap)
Returns a bool version of an AutomatableParameter.
template<typename Type >
Type getTypedParamValue (const AutomatableParameter &ap)
Returns an int version of an AutomatableParameter cast to a enum type.
int simplify (AutomationCurve &, int strength, EditTimeRange range)
Removes points from the curve to simplfy it and returns the number of points removed.
MacroParameter::Ptr getMacroParameterForID (Edit &, EditItemID)
Searched the Edit for a MacroParameter with this ID.
juce::ReferenceCountedObjectPtr< Plugin > getOwnerPlugin (MacroParameterList *)
If this MacroParameterList belongs to an Plugin, this will return it.
template<typename ModifierType >
juce::ReferenceCountedArray< ModifierType > getModifiersOfType (const ModifierList &ml)
Returns the modifers of a specific type.
Modifier::Ptr findModifierForID (ModifierList &, EditItemID)
Returns a Modifier if it can be found in the list.
std::unique_ptr< Edit > loadEditFromFile (Engine &, const juce::File &)
Loads an edit from file, ready for playback / editing.
std::unique_ptr< Edit > createEmptyEdit (Engine &, const juce::File &)
Creates a new edit for a file, ready for playback / editing.
juce::ValueTree loadEditFromProjectManager (ProjectManager &, ProjectItemID)
Uses the ProjectManager to find an Edit file and load it as a ValueTree.
juce::ValueTree loadEditFromFile (Engine &, const juce::File &, ProjectItemID)
Legacy, will be deprecated soon.
juce::ValueTree createEmptyEdit (Engine &)
Legacy, will be deprecated soon.
juce::ValueTree updateLegacyEdit (const juce::ValueTree &)
Converts old edit formats to the latest structure.
void updateLegacyEdit (juce::XmlElement &editXML)
Converts old edit formats to the latest structure.
juce::File getEditFileFromProjectManager (Edit &)
Uses the ProjectManager to look up the file for an Edit.
bool referencesProjectItem (Edit &, ProjectItemID)
Returns true if the ProjectItemID is being used for any of the Edit's elements.
void insertSpaceIntoEdit (Edit &, EditTimeRange timeRangeToInsert)
Inserts blank space in to an Edit, splitting clips if necessary.
void insertSpaceIntoEditFromBeatRange (Edit &, juce::Range< double > beatRange)
Inserts a number of blank beats in to the Edit.
juce::Array< Track * > getAllTracks (const Edit &)
Returns all the tracks in an Edit.
juce::Array< Track * > getTopLevelTracks (const Edit &)
Returns all of the non-foldered tracks in an Edit.
template<typename TrackType >
juce::Array< TrackType * > getTracksOfType (const Edit &, bool recursive)
Returns the tracks of a given type in an Edit.
juce::Array< AudioTrack * > getAudioTracks (const Edit &)
Returns all the AudioTracks in an Edit.
juce::Array< ClipTrack * > getClipTracks (const Edit &)
Returns all the ClipTracks in an Edit.
int getTotalNumTracks (const Edit &)
Returns the total number of Tracks in an Edit.
Track * findTrackForID (const Edit &, EditItemID)
Returns the Track with a given ID if contained in the Edit.
juce::Array< Track * > findTracksForIDs (const Edit &, const juce::Array< EditItemID > &)
Returns the Tracks for the given IDs in the Edit.
Track * findTrackForState (const Edit &, const juce::ValueTree &)
Returns the Track with a given state if contained in the Edit.
AudioTrack * getFirstAudioTrack (const Edit &)
Returns the first audio track in an Edit.
juce::Array< Track * > findAllTracksContainingSelectedItems (const SelectableList &)
Returns all the tracks containing the selected tracks or TrackItems.
ClipTrack * findFirstClipTrackFromSelection (const SelectableList &)
Returns the first ClipTrack from the selected tracks or clips.
bool containsTrack (const Edit &, const Track &)
Returns true if the Edit contains this Track.
TrackOutput * getTrackOutput (Track &)
Returns the TrackOutput if the given track has one.
juce::BigInteger toBitSet (const juce::Array< Track * > &)
Returns the set of tracks as a BigInteger with each bit corresponding to the array of all tracks in an Edit.
juce::Array< Track * > toTrackArray (Edit &, const juce::BigInteger &)
Returns an Array of Track[s] corresponding to the set bits of all tracks in an Edit.
Clip * findClipForID (const Edit &, EditItemID)
Returns the Clip with a given ID if contained in the Edit.
Clip * findClipForState (const Edit &, const juce::ValueTree &)
Returns the Clip for a given state if contained in the Edit.
bool containsClip (const Edit &, Clip *)
Returns true if an Edit contains a given clip.
Clip::Ptr duplicateClip (const Clip &)
Creates a unique copy of this clip with a new EditItemID.
void visitAllTrackItems (const Edit &, std::function< bool(TrackItem &)>)
Calls a function for all TrackItems in an Edit.
EditTimeRange getTimeRangeForSelectedItems (const SelectableList &)
Returns the time range covered by the given items.
void deleteRegionOfTracks (Edit &, EditTimeRange rangeToDelete, bool onlySelectedTracks, CloseGap, SelectionManager *)
Deletes a time range of an Edit, optionally closing the gap.
void deleteRegionOfClip (Clip &, EditTimeRange rangeToDelete)
Deletes a time range of a Clip.
void deleteRegionOfSelectedClips (SelectionManager &, EditTimeRange rangeToDelete, CloseGap, bool moveAllSubsequentClipsOnTrack)
Deletes a time range of a Clip selection, optionally closing the gap.
SelectableList splitClips (const SelectableList &clips, double time)
Splits the clips at a given time.
void moveSelectedClips (const SelectableList &, Edit &, MoveClipAction mode, bool alsoMoveAutomation)
Moves the selected clips within their track.
SelectableList getClipSelectionWithCollectionClipContents (const SelectableList &)
Returns a list of clips.
juce::Array< ClipEffect * > getAllClipEffects (Edit &edit)
Returns all clip effects.
MidiNote * findNoteForState (const Edit &, const juce::ValueTree &)
Returns the MidiNote with a given state.
juce::Result mergeMidiClips (juce::Array< MidiClip * >)
Merges a set of MIDI clips in to one new one.
Plugin::Array getAllPlugins (const Edit &, bool includeMasterVolume)
Returns all the plugins in a given Edit.
Plugin::Ptr findPluginForState (const Edit &, const juce::ValueTree &)
Returns the plugin with given state.
Track * getTrackContainingPlugin (const Edit &, const Plugin *)
Returns the track for the track which the plugin is located on.
bool areAnyPluginsMissing (const Edit &)
Returns true if any plugins couldn't be loaded beacuse their files are missing.
juce::Array< RackInstance * > getRackInstancesInEditForType (const RackType &)
Returns all of the instances of a specific RackType in an Edit.
void muteOrUnmuteAllPlugins (Edit &)
Toggles the enabled state of all plugins in an Edit.
juce::Array< AutomatableEditItem * > getAllAutomatableEditItems (const Edit &)
Returns all AutomatableEditItems in an Edit.
void deleteAutomation (const SelectableList &selectedClips)
Deletes the automation covered by the selected clips.
juce::Array< AutomatableParameter::ModifierSource * > getAllModifierSources (const Edit &)
Returns all the ModifierSources in an Edit.
juce::ReferenceCountedArray< Modifier > getAllModifiers (const Edit &)
Returns all the Modifiers in an Edit.
template<typename ModifierType >
ModifierType::Ptr findModifierTypeForID (const Edit &, EditItemID)
Returns the Modifier with a given type and ID.
Modifier::Ptr findModifierForID (const Edit &, EditItemID)
Returns the Modifier with a given ID.
Modifier::Ptr findModifierForID (const RackType &, EditItemID)
Returns the Modifier with a given ID if the RackType contains it.
Track * getTrackContainingModifier (const Edit &, const Modifier::Ptr &)
Returns the Track containing a Modifier.
juce::Array< MacroParameterList * > getAllMacroParameterLists (const Edit &)
Returns all the MacroParameterLists in an Edit.
juce::Array< MacroParameterElement * > getAllMacroParameterElements (const Edit &)
Returns all the MacroParameterElement in an Edit.
bool operator< (const PitchSetting &p1, const PitchSetting &p2) noexcept
void moveAutomation (const juce::Array< TrackAutomationSection > &, double offset, bool copy)
Moves a set of automation optionally applying an offset and copying the automation (rather than moving it).
template<typename ArrayType >
int findIndexOfNextItemAt (const ArrayType &items, double time)
Returns the index of the next item after the given time.
template<typename ArrayType >
EditTimeRange findUnionOfEditTimeRanges (const ArrayType &items)
Returns the the time range that covers all the given TrackItems.
AudioNode * createTrackCompAudioNode (AudioNode *input, const juce::Array< EditTimeRange > &muteTimes, const juce::Array< EditTimeRange > &nonMuteTimes, double crossfadeTime)
AudioNode * createAudioNode (TrackCompManager::TrackComp &trackComp, Track &t, AudioNode *input)
juce::String createDescriptionOfChannels (const std::vector< ChannelIndex > &)
Creates a String description of the channels.
juce::AudioChannelSet createChannelSet (const std::vector< ChannelIndex > &)
Creates an AudioChannelSet for a list of ChannelIndexes.
juce::AudioChannelSet::ChannelType channelTypeFromAbbreviatedName (const juce::String &)
Returns the ChannelType for an abbreviated name.
juce::AudioChannelSet channelSetFromSpeakerArrangmentString (const juce::String &)
Creates an AudioChannelSet from a list of abbreviated channel names.
std::unique_ptr< tracktion_graph::Node > createNodeForEdit (EditPlaybackContext &, std::atomic< double > &audibleTimeToUpdate, const CreateNodeParams &)
Creates a Node to play back an Edit with live inputs and outputs.
std::unique_ptr< tracktion_graph::Node > createNodeForEdit (Edit &, const CreateNodeParams &)
Creates a Node to render an Edit.
void toStart (TransportControl &, const SelectableList &)
Moves the transport to the start of the selected objects.
void toEnd (TransportControl &, const SelectableList &)
Moves the transport to the end of the selected objects.
void tabBack (TransportControl &)
Moves the transport back to the previous point of interest.
void tabForward (TransportControl &)
Moves the transport forwards to the next point of interest.
void markIn (TransportControl &)
Sets the mark in position to the current transport position.
void markOut (TransportControl &)
Sets the mark out position to the current transport position.
void scrub (TransportControl &, double unitsForwards)
Scrubs back and forth in 'units', where a unit is about 1/50th of the width of the strip window.
void freePlaybackContextIfNotRecording (TransportControl &)
Frees the playback context if no recording is in progress, useful for when an app is minimised.
AIRWINDOWSPLUGIN (AirWindowsADClip7, "ADClip 7")
AIRWINDOWSPLUGIN (AirWindowsADT, "ADT")
AIRWINDOWSPLUGIN (AirWindowsAQuickVoiceClip, "A Quick Voice Clip")
AIRWINDOWSPLUGIN (AirWindowsAcceleration, "Acceleration")
AIRWINDOWSPLUGIN (AirWindowsAir, "Air")
AIRWINDOWSPLUGIN (AirWindowsAtmosphereBuss, "Atmosphere Buss")
AIRWINDOWSPLUGIN (AirWindowsAtmosphereChannel, "Atmosphere Channel")
AIRWINDOWSPLUGIN (AirWindowsAura, "Aura")
AIRWINDOWSPLUGIN (AirWindowsAverage, "Average")
AIRWINDOWSPLUGIN (AirWindowsBassDrive, "Bass Drive")
AIRWINDOWSPLUGIN (AirWindowsBassKit, "Bass Kit")
AIRWINDOWSPLUGIN (AirWindowsBiquad, "Biquad")
AIRWINDOWSPLUGIN (AirWindowsBiquad2, "Biquad 2")
AIRWINDOWSPLUGIN (AirWindowsBitGlitter, "Bit Glitter")
AIRWINDOWSPLUGIN (AirWindowsBitShiftGain, "Bit Shift Gain")
AIRWINDOWSPLUGIN (AirWindowsBite, "Bite")
AIRWINDOWSPLUGIN (AirWindowsBlockParty, "Block Party")
AIRWINDOWSPLUGIN (AirWindowsBrassRider, "Brass Rider")
AIRWINDOWSPLUGIN (AirWindowsBuildATPDF, "Build ATPDF")
AIRWINDOWSPLUGIN (AirWindowsBussColors4, "Buss Colors 4")
AIRWINDOWSPLUGIN (AirWindowsButterComp, "Butter Comp")
AIRWINDOWSPLUGIN (AirWindowsButterComp2, "Butter Comp 2")
AIRWINDOWSPLUGIN (AirWindowsC5RawBuss, "C5 Raw Buss")
AIRWINDOWSPLUGIN (AirWindowsC5RawChannel, "C5 Raw Channel")
AIRWINDOWSPLUGIN (AirWindowsCStrip, "C Strip")
AIRWINDOWSPLUGIN (AirWindowsCapacitor, "Capacitor")
AIRWINDOWSPLUGIN (AirWindowsChannel4, "Channel 4")
AIRWINDOWSPLUGIN (AirWindowsChannel5, "Channel 5")
AIRWINDOWSPLUGIN (AirWindowsChannel6, "Channel 6")
AIRWINDOWSPLUGIN (AirWindowsChannel7, "Channel 7")
AIRWINDOWSPLUGIN (AirWindowsChorus, "Chorus")
AIRWINDOWSPLUGIN (AirWindowsChorusEnsemble, "Chorus Ensemble")
AIRWINDOWSPLUGIN (AirWindowsClipOnly, "Clip Only")
AIRWINDOWSPLUGIN (AirWindowsCoils, "Coils")
AIRWINDOWSPLUGIN (AirWindowsCojones, "Cojones")
AIRWINDOWSPLUGIN (AirWindowsCompresaturator, "Compresaturator")
AIRWINDOWSPLUGIN (AirWindowsConsole4Buss, "Console 4 Buss")
AIRWINDOWSPLUGIN (AirWindowsConsole4Channel, "Console 4 Channel")
AIRWINDOWSPLUGIN (AirWindowsConsole5Buss, "Console 5 Buss")
AIRWINDOWSPLUGIN (AirWindowsConsole5Channel, "Console 5 Channel")
AIRWINDOWSPLUGIN (AirWindowsConsole5DarkCh, "Console 5 Dark Ch")
AIRWINDOWSPLUGIN (AirWindowsConsole6Buss, "Console 6 Buss")
AIRWINDOWSPLUGIN (AirWindowsConsole6Channel, "Console 6 Channel")
AIRWINDOWSPLUGIN (AirWindowsCrunchyGrooveWear, "Crunchy Groove Wear")
AIRWINDOWSPLUGIN (AirWindowsCrystal, "Crystal")
AIRWINDOWSPLUGIN (AirWindowsDCVoltage, "DC Voltage")
AIRWINDOWSPLUGIN (AirWindowsDeBess, "De Bess")
AIRWINDOWSPLUGIN (AirWindowsDeEss, "De Ess")
AIRWINDOWSPLUGIN (AirWindowsDeHiss, "De Hiss")
AIRWINDOWSPLUGIN (AirWindowsDeRez, "De Rez")
AIRWINDOWSPLUGIN (AirWindowsDeRez2, "De Rez 2")
AIRWINDOWSPLUGIN (AirWindowsDeckwrecka, "Deckwrecka")
AIRWINDOWSPLUGIN (AirWindowsDensity, "Density")
AIRWINDOWSPLUGIN (AirWindowsDesk, "Desk")
AIRWINDOWSPLUGIN (AirWindowsDesk4, "Desk 4")
AIRWINDOWSPLUGIN (AirWindowsDistance, "Distance")
AIRWINDOWSPLUGIN (AirWindowsDistance2, "Distance 2")
AIRWINDOWSPLUGIN (AirWindowsDitherFloat, "Dither Float")
AIRWINDOWSPLUGIN (AirWindowsDitherMeDiskers, "Dither Me Diskers")
AIRWINDOWSPLUGIN (AirWindowsDitherMeTimbers, "Dither Me Timbers")
AIRWINDOWSPLUGIN (AirWindowsDitherbox, "Ditherbox")
AIRWINDOWSPLUGIN (AirWindowsDoublePaul, "Double Paul")
AIRWINDOWSPLUGIN (AirWindowsDrive, "Drive")
AIRWINDOWSPLUGIN (AirWindowsDrumSlam, "Drum Slam")
AIRWINDOWSPLUGIN (AirWindowsDubCenter, "Dub Center")
AIRWINDOWSPLUGIN (AirWindowsDubSub, "Dub Sub")
AIRWINDOWSPLUGIN (AirWindowsDustBunny, "Dust Bunny")
AIRWINDOWSPLUGIN (AirWindowsDyno, "Dyno")
AIRWINDOWSPLUGIN (AirWindowsEQ, "EQ")
AIRWINDOWSPLUGIN (AirWindowsEdIsDim, "Ed Is Dim")
AIRWINDOWSPLUGIN (AirWindowsElectroHat, "Electro Hat")
AIRWINDOWSPLUGIN (AirWindowsEnergy, "Energy")
AIRWINDOWSPLUGIN (AirWindowsEnsemble, "Ensemble")
AIRWINDOWSPLUGIN (AirWindowsEveryTrim, "Every Trim")
AIRWINDOWSPLUGIN (AirWindowsFacet, "Facet")
AIRWINDOWSPLUGIN (AirWindowsFathomFive, "Fathom Five")
AIRWINDOWSPLUGIN (AirWindowsFloor, "Floor")
AIRWINDOWSPLUGIN (AirWindowsFocus, "Focus")
AIRWINDOWSPLUGIN (AirWindowsFracture, "Fracture")
AIRWINDOWSPLUGIN (AirWindowsFromTape, "From Tape")
AIRWINDOWSPLUGIN (AirWindowsGatelope, "Gatelope")
AIRWINDOWSPLUGIN (AirWindowsGolem, "Golem")
AIRWINDOWSPLUGIN (AirWindowsGringer, "Gringer")
AIRWINDOWSPLUGIN (AirWindowsGrooveWear, "Groove Wear")
AIRWINDOWSPLUGIN (AirWindowsGuitarConditioner, "Guitar Conditioner")
AIRWINDOWSPLUGIN (AirWindowsHardVacuum, "Hard Vacuum")
AIRWINDOWSPLUGIN (AirWindowsHermeTrim, "Herme Trim")
AIRWINDOWSPLUGIN (AirWindowsHermepass, "Hermepass")
AIRWINDOWSPLUGIN (AirWindowsHighGlossDither, "High Gloss Dither")
AIRWINDOWSPLUGIN (AirWindowsHighImpact, "High Impact")
AIRWINDOWSPLUGIN (AirWindowsHighpass, "Highpass")
AIRWINDOWSPLUGIN (AirWindowsHighpass2, "Highpass 2")
AIRWINDOWSPLUGIN (AirWindowsHolt, "Holt")
AIRWINDOWSPLUGIN (AirWindowsHombre, "Hombre")
AIRWINDOWSPLUGIN (AirWindowsInterstage, "Interstage")
AIRWINDOWSPLUGIN (AirWindowsIronOxide5, "Iron Oxide 5")
AIRWINDOWSPLUGIN (AirWindowsIronOxideClassic, "Iron Oxide Classic")
AIRWINDOWSPLUGIN (AirWindowsLeftoMono, "Lefto Mono")
AIRWINDOWSPLUGIN (AirWindowsLogical4, "Logical 4")
AIRWINDOWSPLUGIN (AirWindowsLoud, "Loud")
AIRWINDOWSPLUGIN (AirWindowsLowpass, "Lowpass")
AIRWINDOWSPLUGIN (AirWindowsLowpass2, "Lowpass 2")
AIRWINDOWSPLUGIN (AirWindowsMV, "MV")
AIRWINDOWSPLUGIN (AirWindowsMelt, "Melt")
AIRWINDOWSPLUGIN (AirWindowsMidSide, "Mid Side")
AIRWINDOWSPLUGIN (AirWindowsMoNoam, "Mo Noam")
AIRWINDOWSPLUGIN (AirWindowsMojo, "Mojo")
AIRWINDOWSPLUGIN (AirWindowsMonitoring, "Monitoring")
AIRWINDOWSPLUGIN (AirWindowsNCSeventeen, "NC-17")
AIRWINDOWSPLUGIN (AirWindowsNaturalizeDither, "Naturalize Dither")
AIRWINDOWSPLUGIN (AirWindowsNodeDither, "Node Dither")
AIRWINDOWSPLUGIN (AirWindowsNoise, "Noise")
AIRWINDOWSPLUGIN (AirWindowsNonlinearSpace, "Nonlinear Space")
AIRWINDOWSPLUGIN (AirWindowsNotJustAnotherCD, "Not Just Another CD")
AIRWINDOWSPLUGIN (AirWindowsNotJustAnotherDither, "Not Just Another Dither")
AIRWINDOWSPLUGIN (AirWindowsOneCornerClip, "One Corner Clip")
AIRWINDOWSPLUGIN (AirWindowsPDBuss, "PD Buss")
AIRWINDOWSPLUGIN (AirWindowsPDChannel, "PD Channel")
AIRWINDOWSPLUGIN (AirWindowsPafnuty, "Pafnuty")
AIRWINDOWSPLUGIN (AirWindowsPaulDither, "Paul Dither")
AIRWINDOWSPLUGIN (AirWindowsPeaksOnly, "Peaks Only")
AIRWINDOWSPLUGIN (AirWindowsPhaseNudge, "Phase Nudge")
AIRWINDOWSPLUGIN (AirWindowsPocketVerbs, "Pocket Verbs")
AIRWINDOWSPLUGIN (AirWindowsPodcast, "Podcast")
AIRWINDOWSPLUGIN (AirWindowsPodcastDeluxe, "Podcast Deluxe")
AIRWINDOWSPLUGIN (AirWindowsPoint, "Point")
AIRWINDOWSPLUGIN (AirWindowsPop, "Pop")
AIRWINDOWSPLUGIN (AirWindowsPowerSag, "Power Sag")
AIRWINDOWSPLUGIN (AirWindowsPowerSag2, "Power Sag 2")
AIRWINDOWSPLUGIN (AirWindowsPressure4, "Pressure 4")
AIRWINDOWSPLUGIN (AirWindowsPurestAir, "Purest Air")
AIRWINDOWSPLUGIN (AirWindowsPurestConsoleBuss, "Purest Console Buss")
AIRWINDOWSPLUGIN (AirWindowsPurestConsoleChannel, "Purest Console Channel")
AIRWINDOWSPLUGIN (AirWindowsPurestDrive, "Purest Drive")
AIRWINDOWSPLUGIN (AirWindowsPurestEcho, "Purest Echo")
AIRWINDOWSPLUGIN (AirWindowsPurestGain, "Purest Gain")
AIRWINDOWSPLUGIN (AirWindowsPurestSquish, "Purest Squish")
AIRWINDOWSPLUGIN (AirWindowsPurestWarm, "Purest Warm")
AIRWINDOWSPLUGIN (AirWindowsPyewacket, "Pyewacket")
AIRWINDOWSPLUGIN (AirWindowsRawGlitters, "Raw Glitters")
AIRWINDOWSPLUGIN (AirWindowsRawTimbers, "Raw Timbers")
AIRWINDOWSPLUGIN (AirWindowsRecurve, "Recurve")
AIRWINDOWSPLUGIN (AirWindowsRemap, "Remap")
AIRWINDOWSPLUGIN (AirWindowsResEQ, "ResEQ")
AIRWINDOWSPLUGIN (AirWindowsRighteous4, "Righteous 4")
AIRWINDOWSPLUGIN (AirWindowsRightoMono, "Righto Mono")
AIRWINDOWSPLUGIN (AirWindowsSideDull, "Side Dull")
AIRWINDOWSPLUGIN (AirWindowsSidepass, "Sidepass")
AIRWINDOWSPLUGIN (AirWindowsSingleEndedTriode, "Single Ended Triode")
AIRWINDOWSPLUGIN (AirWindowsSlew, "Slew")
AIRWINDOWSPLUGIN (AirWindowsSlew2, "Slew 2")
AIRWINDOWSPLUGIN (AirWindowsSlewOnly, "Slew Only")
AIRWINDOWSPLUGIN (AirWindowsSmooth, "Smooth")
AIRWINDOWSPLUGIN (AirWindowsSoftGate, "Soft Gate")
AIRWINDOWSPLUGIN (AirWindowsSpatializeDither, "Spatialize Dither")
AIRWINDOWSPLUGIN (AirWindowsSpiral, "Spiral")
AIRWINDOWSPLUGIN (AirWindowsSpiral2, "Spiral 2")
AIRWINDOWSPLUGIN (AirWindowsStarChild, "Star Child")
AIRWINDOWSPLUGIN (AirWindowsStereoFX, "Stereo FX")
AIRWINDOWSPLUGIN (AirWindowsStudioTan, "Studio Tan")
AIRWINDOWSPLUGIN (AirWindowsSubsOnly, "Subs Only")
AIRWINDOWSPLUGIN (AirWindowsSurge, "Surge")
AIRWINDOWSPLUGIN (AirWindowsSurgeTide, "Surge Tide")
AIRWINDOWSPLUGIN (AirWindowsSwell, "Swell")
AIRWINDOWSPLUGIN (AirWindowsTPDFDither, "TPDF Dither")
AIRWINDOWSPLUGIN (AirWindowsTapeDelay, "Tape Delay")
AIRWINDOWSPLUGIN (AirWindowsTapeDither, "Tape Dither")
AIRWINDOWSPLUGIN (AirWindowsTapeDust, "Tape Dust")
AIRWINDOWSPLUGIN (AirWindowsTapeFat, "Tape Fat")
AIRWINDOWSPLUGIN (AirWindowsThunder, "Thunder")
AIRWINDOWSPLUGIN (AirWindowsToTape5, "To Tape 5")
AIRWINDOWSPLUGIN (AirWindowsToVinyl4, "To Vinyl 4")
AIRWINDOWSPLUGIN (AirWindowsToneSlant, "Tone Slant")
AIRWINDOWSPLUGIN (AirWindowsTransDesk, "Trans Desk")
AIRWINDOWSPLUGIN (AirWindowsTremolo, "Tremolo")
AIRWINDOWSPLUGIN (AirWindowsTubeDesk, "Tube Desk")
AIRWINDOWSPLUGIN (AirWindowsUnBox, "Un Box")
AIRWINDOWSPLUGIN (AirWindowsVariMu, "Vari Mu")
AIRWINDOWSPLUGIN (AirWindowsVibrato, "Vibrato")
AIRWINDOWSPLUGIN (AirWindowsVinylDither, "Vinyl Dither")
AIRWINDOWSPLUGIN (AirWindowsVoiceOfTheStarship, "Voice Of The Starship")
AIRWINDOWSPLUGIN (AirWindowsVoiceTrick, "Voice Trick")
AIRWINDOWSPLUGIN (AirWindowsWider, "Wider")
AIRWINDOWSPLUGIN (AirWindowscurve, "curve")
AIRWINDOWSPLUGIN (AirWindowsuLawDecode, "u Law Decode")
AIRWINDOWSPLUGIN (AirWindowsuLawEncode, "u Law Encode")
juce::String createIdentifierString (const juce::PluginDescription &)
SearchOperation * createSearchForKeywords (const juce::String &keywords)
turns a keyword string into a search condition tree.
bool callBlocking (std::function< void()> f)
float dbToGain (float db) noexcept
float gainToDb (float gain) noexcept
juce::String gainToDbString (float gain, float infLevel=-96.0f, int decPlaces=2)
float dbStringToDb (const juce::String &dbStr)
float dbStringToGain (const juce::String &dbStr)
juce::String getPanString (float pan)
juce::String getSemitonesAsString (double semitones)
template<typename FloatType >
FloatType midiNoteToFrequency (FloatType midiNote)
template<typename FloatType >
FloatType frequencyToMidiNote (FloatType freq)
void sanitiseValues (juce::AudioBuffer< float > &, int startSample, int numSamples, float maxAbsValue, float minAbsThreshold=1.0f/262144.0f)
void addAntiDenormalisationNoise (juce::AudioBuffer< float > &, int start, int numSamples) noexcept
void resetFP () noexcept
bool hasFloatingPointDenormaliseOccurred () noexcept
void zeroDenormalisedValuesIfNeeded (juce::AudioBuffer< float > &) noexcept
bool isAudioDataAlmostSilent (const float *data, int num)
float getAudioDataMagnitude (const float *data, int num)
void convertIntsToFloats (juce::AudioBuffer< float > &)
void convertFloatsToInts (juce::AudioBuffer< float > &)
void yieldGUIThread () noexcept
template<typename SampleType >
choc::buffer::BufferView< SampleType, choc::buffer::SeparateChannelLayout > toBufferView (juce::AudioBuffer< SampleType > &buffer)
Converts a juce::AudioBuffer<SampleType> to a choc::buffer::BufferView.
PanLaw getDefaultPanLaw () noexcept
void setDefaultPanLaw (PanLaw)
juce::StringArray getPanLawChoices (bool includeDefault) noexcept
float decibelsToVolumeFaderPosition (float dB) noexcept
float volumeFaderPositionToDB (float position) noexcept
float volumeFaderPositionToGain (float position) noexcept
float gainToVolumeFaderPosition (float gain) noexcept
void getGainsFromVolumeFaderPositionAndPan (float volSliderPos, float pan, PanLaw lawToUse, float &leftGain, float &rightGain) noexcept
void clearChannels (juce::AudioBuffer< float > &buffer, int startChannel, int endChannel=-1, int startSample=0, int endSample=-1)
BenchmarkDescription createBenchmarkDescription (std::string category, std::string name, std::string description)
Creates a description by hashing the name and description fields.
BenchmarkResult createBenchmarkResult (BenchmarkDescription description, const tracktion_graph::PerformanceMeasurement::Statistics &stats)
Creates a BenchmarkResult from a set of Statistics.
juce::PropertiesFile * getApplicationSettings ()
juce::AudioPlayHead::CurrentPositionInfo getCurrentPositionInfo (Edit &)
Converts an Edit's internal transport information to a juce::AudioPlayHead::CurrentPositionInfo.
void synchroniseEditPosition (Edit &, const juce::AudioPlayHead::CurrentPositionInfo &)
Syncs an Edit's transport and tempo sequence to a juce AudioPlayHead.
bool isMidiFile (const juce::File &)
bool isTracktionEditFile (const juce::File &)
bool isTracktionArchiveFile (const juce::File &)
bool isTracktionProjectFile (const juce::File &)
bool isTracktionPresetFile (const juce::File &)
juce::File getNonExistentSiblingWithIncrementedNumberSuffix (const juce::File &, bool addHashSymbol)
void addSortedListToMenu (juce::PopupMenu &m, juce::StringArray names, int startID)
juce::AffineTransform getScaleAroundCentre (juce::Rectangle< float > r, float numPixels)
int indexOfFirstFoundInSecond (const juce::StringArray &array1, const juce::StringArray &array2) noexcept
Returns the index in the first array of the first match found.
bool allFirstFoundInSecond (const juce::StringArray &array1, const juce::StringArray &array2) noexcept
Returns true if all of the strings of the first array are found in the second array.
void moveXMLAttributeToStart (juce::XmlElement &xml, juce::StringRef att)
template<typename Vector , typename Predicate >
bool removeIf (Vector &v, Predicate &&pred)
template<typename FloatingPointType >
bool almostEqual (FloatingPointType firstValue, FloatingPointType secondValue, FloatingPointType precision=(FloatingPointType) 0.00001)
Checks to see if two values are equal within a given precision.
template<typename Type >
bool matchesAnyOf (const Type &needle, const std::initializer_list< Type > &haystack)
Returns true if the needle is found in the haystack.
template<typename Type , typename UnaryFunction >
void forEachItem (const juce::Array< Type * > &items, const UnaryFunction &fn)
Calls a function object on each item in an array.
template<typename... Others>
void addValueTreeProperties (juce::ValueTree &v, const juce::Identifier &name, const juce::var &value, Others &&... others)
template<typename... Properties>
juce::ValueTree createValueTree (const juce::Identifier &name, Properties &&... properties)
juce::Array< juce::ValueTree > & removeInvalidValueTrees (juce::Array< juce::ValueTree > &trees)
Strips out any invalid trees from the array.
juce::Array< juce::ValueTree > getTreesOfType (const juce::Array< juce::ValueTree > &trees, const juce::Identifier &type)
Returns a new array with any trees without the given type removed.
void getChildTreesRecursive (juce::Array< juce::ValueTree > &result, const juce::ValueTree &tree)
void renamePropertyRecursive (juce::ValueTree &tree, const juce::Identifier &oldName, const juce::Identifier &newName, juce::UndoManager *um)
Variables
const char *const projectFileSuffix = ".tracktion"
const char *const editFileSuffix = ".tracktionedit"
const char *const legacyEditFileSuffix = ".trkedit"
const char *const archiveFileSuffix = ".trkarch"
const char *const soundFileWildCard = "*.wav;*.aiff;*.aif;*.ogg;*.mp3;*.flac;*.au;*.voc;*.caf;*.w64;*.rx2;*.rcy;*.rex;*.wfaf"
const char *const soundFileAndMidiWildCard = "*.wav;*.aiff;*.aif;*.ogg;*.mp3;*.mid;*.midi;*.flac;*.au;*.voc;*.caf;*.w64;*.rx2;*.rcy;*.rex;*.wfaf"
const char *const midiFileWildCard = "*.midi;*.mid"
const char *const keyMapWildCard = "*.tracktionkeys"
const char *const keyMapSuffix = ".tracktionkeys"
const char *const customControllerFileSuffix = ".trkctrlr"
const char *const customProgramSetWildcard = "*.trkmidi;*.midnam"
const char *const customProgramSetFileSuffix = ".trkmidi"
const char *const presetFileSuffix = ".trkpreset"
const char *const rackFileSuffix = ".trkrack"
const char *const scriptFileSuffix = ".tracktionscript"
const char *const grooveTemplateSuffix = ".trkgroove"
const char *const grooveTemplateWildCard = "*.trkgroove"
Typedef Documentation
SampleCount
using tracktion_engine::SampleCount = typedef int64_t
SampleRange
using tracktion_engine::SampleRange = typedef juce::Range<SampleCount>
HashCode
using tracktion_engine::HashCode = typedef int64_t
Enumeration Type Documentation
CloseGap
enum tracktion_engine::CloseGap strong
An enum to specify if gaps deleted should be closed or not.
Enumerator
no
Don't move up subsequent track content.
yes
Do move up subsequent track content.
MoveClipAction
enum tracktion_engine::MoveClipAction strong
Enum to dictate move clip behaviour.
Enumerator
moveToEndOfLast
moveToStartOfNext
moveStartToCursor
moveEndToCursor
TimecodeType
enum tracktion_engine::TimecodeType strong
Enumerator
millisecs
barsBeats
fps24
fps25
fps30
PanLaw
enum tracktion_engine::PanLaw
All laws have been designed to be equal-power, excluding linear respectively.
Enumerator
PanLawDefault
PanLawLinear
PanLaw2point5dBCenter
PanLaw3dBCenter
PanLaw4point5dBCenter
PanLaw6dBCenter
SettingID
enum tracktion_engine::SettingID strong
A list of settings the engine will get and set.
Enumerator
invalid
addAntiDenormalNoise
audio_device_setup
audiosettings
autoFreeze
autoTempoMatch
autoTempoDetect
automapVst
automapNative
automapGuids1
automapGuids2
cacheSizeSamples
compCrossfadeMs
countInMode
clickTrackMidiNoteBig
clickTrackMidiNoteLittle
clickTrackSampleSmall
clickTrackSampleBig
crossfadeBlock
cpu
customMidiControllers
deadMansPedal
defaultMidiOutDevice
defaultWaveOutDevice
defaultMidiInDevice
defaultWaveInDevice
externControlIn
externControlOut
externControlShowSelection
externControlSelectionColour
externControlEnable
externOscInputPort
externOscOutputPort
externOscOutputAddr
filterControlMappingPresets
filterGui
fitClipsToRegion
findExamples
freezePoint
hasEnabledMidiDefaultDevs
glideLength
grooveTemplates
knownPluginList
knownPluginList64
lameEncoder
lastClickTrackLevel
lastEditRender
lowLatencyBuffer
MCUoneTouchRecord
maxLatency
midiin
midiout
midiEditorOctaves
midiProgramManager
newMarker
numThreadsForPluginScanning
projectList
projects
recentProjects
renameClipRenamesSource
renameMode
renderRecentFilesList
resetCursorOnStop
retrospectiveRecord
reWireEnabled
safeRecord
sendControllerOffMessages
simplifyAfterRecording
snapCursor
tempDirectory
trackExpansionMode
use64Bit
xFade
xtCount
xtIndices
virtualmididevices
virtualmidiin
useSeparateProcessForScanning
useRealtime
wavein
waveout
windowsDoubleClick
renderFormat
trackRenderSampRate
trackRenderBits
bypassFilters
markedRegion
editClipRenderSampRate
editClipRenderBits
editClipRenderDither
editClipRealtime
editClipRenderStereo
editClipRenderNormalise
editClipRenderRMS
editClipRenderRMSLevelDb
editClipRenderPeakLevelDb
editClipPassThroughFilters
exportFormat
renderOnlySelectedClips
renderOnlyMarked
renderNormalise
renderRMS
renderRMSLevelDb
renderPeakLevelDb
renderTrimSilence
renderSampRate
renderStereo
renderBits
renderDither
quality
addId3Info
realtime
passThroughFilters
Function Documentation
determineKeyOfNotes()
juce::Array<KeyResult> tracktion_engine::determineKeyOfNotes (const juce::Array< MidiNote * > & notes)
getAssignmentsOfType()
template<typename AssignmentType > juce::ReferenceCountedArray<AssignmentType> tracktion_engine::getAssignmentsOfType (const AutomatableParameter & ap)
Returns all the Assignments of a specific type.
References tracktion_engine::AutomatableParameter::getAssignments().
getModifiersOfType() [1/2]
template<typename ModifierType > juce::Array<ModifierType*> tracktion_engine::getModifiersOfType (const AutomatableParameter & ap)
Returns all the modifers in use of a specific type.
References tracktion_engine::AutomatableParameter::getModifiers().
getAllAutomatableParameter()
juce::Array<AutomatableParameter*> tracktion_engine::getAllAutomatableParameter (Edit &)
Returns all the automatable parameters in an Edit.
Referenced by getAssignmentsForSource().
getAssignmentsForSource()
template<typename AssignmentType , typename ModifierSourceType > juce::ReferenceCountedArray<AssignmentType> tracktion_engine::getAssignmentsForSource (Edit & edit, const ModifierSourceType & source)
Iterates an Edit looking for all parameters that assigned to a given parameter.
References getAllAutomatableParameter().
getSourceForAssignment()
AutomatableParameter::ModifierSource* tracktion_engine::getSourceForAssignment (const AutomatableParameter::ModifierAssignment &)
Iterates an Edit looking for the source of this assignment.
getAllParametersBeingModifiedBy()
juce::ReferenceCountedArray<AutomatableParameter> tracktion_engine::getAllParametersBeingModifiedBy (Edit & , AutomatableParameter::ModifierSource &)
Iterates an Edit looking for all parameters that are being modified by the given ModifierSource.
getParameter()
AutomatableParameter* tracktion_engine::getParameter (AutomatableParameter::ModifierAssignment &)
Iterates an Edit looking for the parameter that this ModifierAssignment has been made from.
getIntParamValue()
int tracktion_engine::getIntParamValue (const AutomatableParameter & ap)
Returns an int version of an AutomatableParameter.
References tracktion_engine::AutomatableParameter::getCurrentValue().
Referenced by getBoolParamValue(), and getTypedParamValue().
getBoolParamValue()
bool tracktion_engine::getBoolParamValue (const AutomatableParameter & ap)
Returns a bool version of an AutomatableParameter.
References getIntParamValue().
getTypedParamValue()
template<typename Type > Type tracktion_engine::getTypedParamValue (const AutomatableParameter & ap)
Returns an int version of an AutomatableParameter cast to a enum type.
References getIntParamValue().
simplify()
int tracktion_engine::simplify (AutomationCurve & , int strength, EditTimeRange range)
Removes points from the curve to simplfy it and returns the number of points removed.
getMacroParameterForID()
MacroParameter::Ptr tracktion_engine::getMacroParameterForID (Edit & , EditItemID)
Searched the Edit for a MacroParameter with this ID.
getOwnerPlugin()
juce::ReferenceCountedObjectPtr<Plugin> tracktion_engine::getOwnerPlugin (MacroParameterList *)
If this MacroParameterList belongs to an Plugin, this will return it.
getModifiersOfType() [2/2]
template<typename ModifierType > juce::ReferenceCountedArray<ModifierType> tracktion_engine::getModifiersOfType (const ModifierList & ml)
Returns the modifers of a specific type.
References tracktion_engine::ModifierList::getModifiers().
findModifierForID() [1/3]
Modifier::Ptr tracktion_engine::findModifierForID (ModifierList & , EditItemID)
Returns a Modifier if it can be found in the list.
loadEditFromFile() [1/2]
std::unique_ptr<Edit> tracktion_engine::loadEditFromFile (Engine & , const juce::File &)
Loads an edit from file, ready for playback / editing.
Referenced by tracktion_engine::benchmark_utilities::openEditfromArchiveData().
createEmptyEdit() [1/2]
std::unique_ptr<Edit> tracktion_engine::createEmptyEdit (Engine & , const juce::File &)
Creates a new edit for a file, ready for playback / editing.
loadEditFromProjectManager()
juce::ValueTree tracktion_engine::loadEditFromProjectManager (ProjectManager & , ProjectItemID)
Uses the ProjectManager to find an Edit file and load it as a ValueTree.
loadEditFromFile() [2/2]
juce::ValueTree tracktion_engine::loadEditFromFile (Engine & , const juce::File & , ProjectItemID)
Legacy, will be deprecated soon.
Use version that returns an edit. Loads a ValueTree from a file to load an Edit. If the file is empty, a new Edit state will be created with the given ProjectItemID.
createEmptyEdit() [2/2]
juce::ValueTree tracktion_engine::createEmptyEdit (Engine &)
Legacy, will be deprecated soon.
Use version that returns an edit. Creates an empty Edit with no project.
updateLegacyEdit() [1/2]
juce::ValueTree tracktion_engine::updateLegacyEdit (const juce::ValueTree & v)
Converts old edit formats to the latest structure.
References tracktion_engine::OldEditConversion::convert().
updateLegacyEdit() [2/2]
void tracktion_engine::updateLegacyEdit (juce::XmlElement & editXML)
Converts old edit formats to the latest structure.
References tracktion_engine::OldEditConversion::convert().
getEditFileFromProjectManager()
juce::File tracktion_engine::getEditFileFromProjectManager (Edit &)
Uses the ProjectManager to look up the file for an Edit.
referencesProjectItem()
bool tracktion_engine::referencesProjectItem (Edit & , ProjectItemID)
Returns true if the ProjectItemID is being used for any of the Edit's elements.
insertSpaceIntoEdit()
void tracktion_engine::insertSpaceIntoEdit (Edit & , EditTimeRange timeRangeToInsert)
Inserts blank space in to an Edit, splitting clips if necessary.
insertSpaceIntoEditFromBeatRange()
void tracktion_engine::insertSpaceIntoEditFromBeatRange (Edit & , juce::Range< double > beatRange)
Inserts a number of blank beats in to the Edit.
getAllTracks()
juce::Array<Track*> tracktion_engine::getAllTracks (const Edit &)
Returns all the tracks in an Edit.
getTopLevelTracks()
juce::Array<Track*> tracktion_engine::getTopLevelTracks (const Edit &)
Returns all of the non-foldered tracks in an Edit.
getTracksOfType()
template<typename TrackType > juce::Array< TrackType * > tracktion_engine::getTracksOfType (const Edit & edit, bool recursive)
Returns the tracks of a given type in an Edit.
References tracktion_engine::Edit::visitAllTracks().
getAudioTracks()
juce::Array<AudioTrack*> tracktion_engine::getAudioTracks (const Edit &)
Returns all the AudioTracks in an Edit.
getClipTracks()
juce::Array<ClipTrack*> tracktion_engine::getClipTracks (const Edit &)
Returns all the ClipTracks in an Edit.
getTotalNumTracks()
int tracktion_engine::getTotalNumTracks (const Edit &)
Returns the total number of Tracks in an Edit.
findTrackForID()
Track* tracktion_engine::findTrackForID (const Edit & , EditItemID)
Returns the Track with a given ID if contained in the Edit.
findTracksForIDs()
juce::Array<Track*> tracktion_engine::findTracksForIDs (const Edit & , const juce::Array< EditItemID > &)
Returns the Tracks for the given IDs in the Edit.
findTrackForState()
Track* tracktion_engine::findTrackForState (const Edit & , const juce::ValueTree &)
Returns the Track with a given state if contained in the Edit.
getFirstAudioTrack()
AudioTrack* tracktion_engine::getFirstAudioTrack (const Edit &)
Returns the first audio track in an Edit.
findAllTracksContainingSelectedItems()
juce::Array<Track*> tracktion_engine::findAllTracksContainingSelectedItems (const SelectableList &)
Returns all the tracks containing the selected tracks or TrackItems.
findFirstClipTrackFromSelection()
ClipTrack* tracktion_engine::findFirstClipTrackFromSelection (const SelectableList &)
Returns the first ClipTrack from the selected tracks or clips.
containsTrack()
bool tracktion_engine::containsTrack (const Edit & , const Track &)
Returns true if the Edit contains this Track.
getTrackOutput()
TrackOutput* tracktion_engine::getTrackOutput (Track &)
Returns the TrackOutput if the given track has one.
toBitSet()
juce::BigInteger tracktion_engine::toBitSet (const juce::Array< Track * > &)
Returns the set of tracks as a BigInteger with each bit corresponding to the array of all tracks in an Edit.
Used in Renderer.
toTrackArray()
juce::Array<Track*> tracktion_engine::toTrackArray (Edit & , const juce::BigInteger &)
Returns an Array of Track[s] corresponding to the set bits of all tracks in an Edit.
Used in Renderer.
findClipForID()
Clip* tracktion_engine::findClipForID (const Edit & , EditItemID)
Returns the Clip with a given ID if contained in the Edit.
findClipForState()
Clip* tracktion_engine::findClipForState (const Edit & , const juce::ValueTree &)
Returns the Clip for a given state if contained in the Edit.
containsClip()
bool tracktion_engine::containsClip (const Edit & , Clip *)
Returns true if an Edit contains a given clip.
duplicateClip()
Clip::Ptr tracktion_engine::duplicateClip (const Clip &)
Creates a unique copy of this clip with a new EditItemID.
visitAllTrackItems()
void tracktion_engine::visitAllTrackItems (const Edit & , std::function< bool(TrackItem &)>)
Calls a function for all TrackItems in an Edit.
getTimeRangeForSelectedItems()
EditTimeRange tracktion_engine::getTimeRangeForSelectedItems (const SelectableList &)
Returns the time range covered by the given items.
deleteRegionOfTracks()
void tracktion_engine::deleteRegionOfTracks (Edit & , EditTimeRange rangeToDelete, bool onlySelectedTracks, CloseGap , SelectionManager *)
Deletes a time range of an Edit, optionally closing the gap.
deleteRegionOfClip()
void tracktion_engine::deleteRegionOfClip (Clip & , EditTimeRange rangeToDelete)
Deletes a time range of a Clip.
deleteRegionOfSelectedClips()
void tracktion_engine::deleteRegionOfSelectedClips (SelectionManager & , EditTimeRange rangeToDelete, CloseGap , bool moveAllSubsequentClipsOnTrack)
Deletes a time range of a Clip selection, optionally closing the gap.
splitClips()
SelectableList tracktion_engine::splitClips (const SelectableList & clips, double time)
Splits the clips at a given time.
moveSelectedClips()
void tracktion_engine::moveSelectedClips (const SelectableList & , Edit & , MoveClipAction mode, bool alsoMoveAutomation)
Moves the selected clips within their track.
getClipSelectionWithCollectionClipContents()
SelectableList tracktion_engine::getClipSelectionWithCollectionClipContents (const SelectableList &)
Returns a list of clips.
If any of these are collection clips, this will return their contained clips.
getAllClipEffects()
juce::Array<ClipEffect*> tracktion_engine::getAllClipEffects (Edit & edit)
Returns all clip effects.
findNoteForState()
MidiNote* tracktion_engine::findNoteForState (const Edit & , const juce::ValueTree &)
Returns the MidiNote with a given state.
mergeMidiClips()
juce::Result tracktion_engine::mergeMidiClips (juce::Array< MidiClip * >)
Merges a set of MIDI clips in to one new one.
getAllPlugins()
Plugin::Array tracktion_engine::getAllPlugins (const Edit & , bool includeMasterVolume)
Returns all the plugins in a given Edit.
findPluginForState()
Plugin::Ptr tracktion_engine::findPluginForState (const Edit & , const juce::ValueTree &)
Returns the plugin with given state.
getTrackContainingPlugin()
Track* tracktion_engine::getTrackContainingPlugin (const Edit & , const Plugin *)
Returns the track for the track which the plugin is located on.
areAnyPluginsMissing()
bool tracktion_engine::areAnyPluginsMissing (const Edit &)
Returns true if any plugins couldn't be loaded beacuse their files are missing.
getRackInstancesInEditForType()
juce::Array<RackInstance*> tracktion_engine::getRackInstancesInEditForType (const RackType &)
Returns all of the instances of a specific RackType in an Edit.
muteOrUnmuteAllPlugins()
void tracktion_engine::muteOrUnmuteAllPlugins (Edit &)
Toggles the enabled state of all plugins in an Edit.
getAllAutomatableEditItems()
juce::Array<AutomatableEditItem*> tracktion_engine::getAllAutomatableEditItems (const Edit &)
Returns all AutomatableEditItems in an Edit.
deleteAutomation()
void tracktion_engine::deleteAutomation (const SelectableList & selectedClips)
Deletes the automation covered by the selected clips.
getAllModifierSources()
juce::Array<AutomatableParameter::ModifierSource*> tracktion_engine::getAllModifierSources (const Edit &)
Returns all the ModifierSources in an Edit.
getAllModifiers()
juce::ReferenceCountedArray<Modifier> tracktion_engine::getAllModifiers (const Edit &)
Returns all the Modifiers in an Edit.
Referenced by findModifierTypeForID().
findModifierTypeForID()
template<typename ModifierType > ModifierType::Ptr tracktion_engine::findModifierTypeForID (const Edit & edit, EditItemID id)
Returns the Modifier with a given type and ID.
References getAllModifiers().
findModifierForID() [2/3]
Modifier::Ptr tracktion_engine::findModifierForID (const Edit & , EditItemID)
Returns the Modifier with a given ID.
findModifierForID() [3/3]
Modifier::Ptr tracktion_engine::findModifierForID (const RackType & , EditItemID)
Returns the Modifier with a given ID if the RackType contains it.
getTrackContainingModifier()
Track* tracktion_engine::getTrackContainingModifier (const Edit & , const Modifier::Ptr &)
Returns the Track containing a Modifier.
getAllMacroParameterLists()
juce::Array<MacroParameterList*> tracktion_engine::getAllMacroParameterLists (const Edit &)
Returns all the MacroParameterLists in an Edit.
getAllMacroParameterElements()
juce::Array<MacroParameterElement*> tracktion_engine::getAllMacroParameterElements (const Edit &)
Returns all the MacroParameterElement in an Edit.
operator<()
bool tracktion_engine::operator< (const PitchSetting & p1, const PitchSetting & p2) noexcept
Referenced by addSortedListToMenu().
moveAutomation()
void tracktion_engine::moveAutomation (const juce::Array< TrackAutomationSection > & , double offset, bool copy)
Moves a set of automation optionally applying an offset and copying the automation (rather than moving it).
findIndexOfNextItemAt()
template<typename ArrayType > int tracktion_engine::findIndexOfNextItemAt (const ArrayType & items, double time)
Returns the index of the next item after the given time.
findUnionOfEditTimeRanges()
template<typename ArrayType > EditTimeRange tracktion_engine::findUnionOfEditTimeRanges (const ArrayType & items)
Returns the the time range that covers all the given TrackItems.
References tracktion_engine::EditTimeRange::getUnionWith().
createTrackCompAudioNode()
AudioNode* tracktion_engine::createTrackCompAudioNode (AudioNode * input, const juce::Array< EditTimeRange > & muteTimes, const juce::Array< EditTimeRange > & nonMuteTimes, double crossfadeTime)
References tracktion_engine::AudioFadeCurve::convex.
Referenced by createAudioNode().
createAudioNode()
AudioNode* tracktion_engine::createAudioNode (TrackCompManager::TrackComp & trackComp, Track & t, AudioNode * input)
References compCrossfadeMs, createTrackCompAudioNode(), tracktion_engine::TrackCompManager::TrackComp::edit, tracktion_engine::Edit::engine, tracktion_engine::TrackCompManager::TrackComp::getMuteTimes(), tracktion_engine::TrackCompManager::TrackComp::getNonMuteTimes(), tracktion_engine::PropertyStorage::getProperty(), and tracktion_engine::Engine::getPropertyStorage().
createDescriptionOfChannels()
juce::String tracktion_engine::createDescriptionOfChannels (const std::vector< ChannelIndex > &)
Creates a String description of the channels.
Useful for debugging.
createChannelSet()
juce::AudioChannelSet tracktion_engine::createChannelSet (const std::vector< ChannelIndex > &)
Creates an AudioChannelSet for a list of ChannelIndexes.
channelTypeFromAbbreviatedName()
juce::AudioChannelSet::ChannelType tracktion_engine::channelTypeFromAbbreviatedName (const juce::String &)
Returns the ChannelType for an abbreviated name.
See also
AudioChannelSet::getAbbreviatedChannelTypeName.
channelSetFromSpeakerArrangmentString()
juce::AudioChannelSet tracktion_engine::channelSetFromSpeakerArrangmentString (const juce::String &)
Creates an AudioChannelSet from a list of abbreviated channel names.
E.g. "L R"
createNodeForEdit() [1/2]
std::unique_ptr<tracktion_graph::Node> tracktion_engine::createNodeForEdit (EditPlaybackContext & , std::atomic< double > & audibleTimeToUpdate, const CreateNodeParams &)
Creates a Node to play back an Edit with live inputs and outputs.
Referenced by tracktion_engine::benchmark_utilities::createNode().
createNodeForEdit() [2/2]
std::unique_ptr<tracktion_graph::Node> tracktion_engine::createNodeForEdit (Edit & , const CreateNodeParams &)
Creates a Node to render an Edit.
toStart()
void tracktion_engine::toStart (TransportControl & , const SelectableList &)
Moves the transport to the start of the selected objects.
toEnd()
void tracktion_engine::toEnd (TransportControl & , const SelectableList &)
Moves the transport to the end of the selected objects.
tabBack()
void tracktion_engine::tabBack (TransportControl &)
Moves the transport back to the previous point of interest.
tabForward()
void tracktion_engine::tabForward (TransportControl &)
Moves the transport forwards to the next point of interest.
markIn()
void tracktion_engine::markIn (TransportControl &)
Sets the mark in position to the current transport position.
markOut()
void tracktion_engine::markOut (TransportControl &)
Sets the mark out position to the current transport position.
scrub()
void tracktion_engine::scrub (TransportControl & , double unitsForwards)
Scrubs back and forth in 'units', where a unit is about 1/50th of the width of the strip window.
freePlaybackContextIfNotRecording()
void tracktion_engine::freePlaybackContextIfNotRecording (TransportControl &)
Frees the playback context if no recording is in progress, useful for when an app is minimised.
AIRWINDOWSPLUGIN() [1/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsADClip7 , "ADClip 7")
AIRWINDOWSPLUGIN() [2/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsADT , "ADT")
AIRWINDOWSPLUGIN() [3/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsAQuickVoiceClip , "A Quick Voice Clip")
AIRWINDOWSPLUGIN() [4/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsAcceleration , "Acceleration")
AIRWINDOWSPLUGIN() [5/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsAir , "Air")
AIRWINDOWSPLUGIN() [6/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsAtmosphereBuss , "Atmosphere Buss")
AIRWINDOWSPLUGIN() [7/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsAtmosphereChannel , "Atmosphere Channel")
AIRWINDOWSPLUGIN() [8/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsAura , "Aura")
AIRWINDOWSPLUGIN() [9/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsAverage , "Average")
AIRWINDOWSPLUGIN() [10/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsBassDrive , "Bass Drive")
AIRWINDOWSPLUGIN() [11/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsBassKit , "Bass Kit")
AIRWINDOWSPLUGIN() [12/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsBiquad , "Biquad")
AIRWINDOWSPLUGIN() [13/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsBiquad2 , "Biquad 2")
AIRWINDOWSPLUGIN() [14/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsBitGlitter , "Bit Glitter")
AIRWINDOWSPLUGIN() [15/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsBitShiftGain , "Bit Shift Gain")
AIRWINDOWSPLUGIN() [16/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsBite , "Bite")
AIRWINDOWSPLUGIN() [17/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsBlockParty , "Block Party")
AIRWINDOWSPLUGIN() [18/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsBrassRider , "Brass Rider")
AIRWINDOWSPLUGIN() [19/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsBuildATPDF , "Build ATPDF")
AIRWINDOWSPLUGIN() [20/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsBussColors4 , "Buss Colors 4")
AIRWINDOWSPLUGIN() [21/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsButterComp , "Butter Comp")
AIRWINDOWSPLUGIN() [22/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsButterComp2 , "Butter Comp 2")
AIRWINDOWSPLUGIN() [23/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsC5RawBuss , "C5 Raw Buss")
AIRWINDOWSPLUGIN() [24/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsC5RawChannel , "C5 Raw Channel")
AIRWINDOWSPLUGIN() [25/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsCStrip , "C Strip")
AIRWINDOWSPLUGIN() [26/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsCapacitor , "Capacitor")
AIRWINDOWSPLUGIN() [27/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsChannel4 , "Channel 4")
AIRWINDOWSPLUGIN() [28/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsChannel5 , "Channel 5")
AIRWINDOWSPLUGIN() [29/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsChannel6 , "Channel 6")
AIRWINDOWSPLUGIN() [30/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsChannel7 , "Channel 7")
AIRWINDOWSPLUGIN() [31/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsChorus , "Chorus")
AIRWINDOWSPLUGIN() [32/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsChorusEnsemble , "Chorus Ensemble")
AIRWINDOWSPLUGIN() [33/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsClipOnly , "Clip Only")
AIRWINDOWSPLUGIN() [34/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsCoils , "Coils")
AIRWINDOWSPLUGIN() [35/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsCojones , "Cojones")
AIRWINDOWSPLUGIN() [36/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsCompresaturator , "Compresaturator")
AIRWINDOWSPLUGIN() [37/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsConsole4Buss , "Console 4 Buss")
AIRWINDOWSPLUGIN() [38/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsConsole4Channel , "Console 4 Channel")
AIRWINDOWSPLUGIN() [39/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsConsole5Buss , "Console 5 Buss")
AIRWINDOWSPLUGIN() [40/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsConsole5Channel , "Console 5 Channel")
AIRWINDOWSPLUGIN() [41/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsConsole5DarkCh , "Console 5 Dark Ch")
AIRWINDOWSPLUGIN() [42/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsConsole6Buss , "Console 6 Buss")
AIRWINDOWSPLUGIN() [43/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsConsole6Channel , "Console 6 Channel")
AIRWINDOWSPLUGIN() [44/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsCrunchyGrooveWear , "Crunchy Groove Wear")
AIRWINDOWSPLUGIN() [45/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsCrystal , "Crystal")
AIRWINDOWSPLUGIN() [46/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDCVoltage , "DC Voltage")
AIRWINDOWSPLUGIN() [47/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDeBess , "De Bess")
AIRWINDOWSPLUGIN() [48/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDeEss , "De Ess")
AIRWINDOWSPLUGIN() [49/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDeHiss , "De Hiss")
AIRWINDOWSPLUGIN() [50/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDeRez , "De Rez")
AIRWINDOWSPLUGIN() [51/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDeRez2 , "De Rez 2")
AIRWINDOWSPLUGIN() [52/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDeckwrecka , "Deckwrecka")
AIRWINDOWSPLUGIN() [53/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDensity , "Density")
AIRWINDOWSPLUGIN() [54/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDesk , "Desk")
AIRWINDOWSPLUGIN() [55/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDesk4 , "Desk 4")
AIRWINDOWSPLUGIN() [56/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDistance , "Distance")
AIRWINDOWSPLUGIN() [57/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDistance2 , "Distance 2")
AIRWINDOWSPLUGIN() [58/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDitherFloat , "Dither Float")
AIRWINDOWSPLUGIN() [59/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDitherMeDiskers , "Dither Me Diskers")
AIRWINDOWSPLUGIN() [60/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDitherMeTimbers , "Dither Me Timbers")
AIRWINDOWSPLUGIN() [61/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDitherbox , "Ditherbox")
AIRWINDOWSPLUGIN() [62/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDoublePaul , "Double Paul")
AIRWINDOWSPLUGIN() [63/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDrive , "Drive")
AIRWINDOWSPLUGIN() [64/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDrumSlam , "Drum Slam")
AIRWINDOWSPLUGIN() [65/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDubCenter , "Dub Center")
AIRWINDOWSPLUGIN() [66/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDubSub , "Dub Sub")
AIRWINDOWSPLUGIN() [67/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDustBunny , "Dust Bunny")
AIRWINDOWSPLUGIN() [68/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsDyno , "Dyno")
AIRWINDOWSPLUGIN() [69/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsEQ , "EQ")
AIRWINDOWSPLUGIN() [70/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsEdIsDim , "Ed Is Dim")
AIRWINDOWSPLUGIN() [71/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsElectroHat , "Electro Hat")
AIRWINDOWSPLUGIN() [72/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsEnergy , "Energy")
AIRWINDOWSPLUGIN() [73/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsEnsemble , "Ensemble")
AIRWINDOWSPLUGIN() [74/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsEveryTrim , "Every Trim")
AIRWINDOWSPLUGIN() [75/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsFacet , "Facet")
AIRWINDOWSPLUGIN() [76/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsFathomFive , "Fathom Five")
AIRWINDOWSPLUGIN() [77/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsFloor , "Floor")
AIRWINDOWSPLUGIN() [78/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsFocus , "Focus")
AIRWINDOWSPLUGIN() [79/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsFracture , "Fracture")
AIRWINDOWSPLUGIN() [80/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsFromTape , "From Tape")
AIRWINDOWSPLUGIN() [81/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsGatelope , "Gatelope")
AIRWINDOWSPLUGIN() [82/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsGolem , "Golem")
AIRWINDOWSPLUGIN() [83/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsGringer , "Gringer")
AIRWINDOWSPLUGIN() [84/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsGrooveWear , "Groove Wear")
AIRWINDOWSPLUGIN() [85/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsGuitarConditioner , "Guitar Conditioner")
AIRWINDOWSPLUGIN() [86/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsHardVacuum , "Hard Vacuum")
AIRWINDOWSPLUGIN() [87/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsHermeTrim , "Herme Trim")
AIRWINDOWSPLUGIN() [88/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsHermepass , "Hermepass")
AIRWINDOWSPLUGIN() [89/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsHighGlossDither , "High Gloss Dither")
AIRWINDOWSPLUGIN() [90/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsHighImpact , "High Impact")
AIRWINDOWSPLUGIN() [91/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsHighpass , "Highpass")
AIRWINDOWSPLUGIN() [92/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsHighpass2 , "Highpass 2")
AIRWINDOWSPLUGIN() [93/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsHolt , "Holt")
AIRWINDOWSPLUGIN() [94/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsHombre , "Hombre")
AIRWINDOWSPLUGIN() [95/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsInterstage , "Interstage")
AIRWINDOWSPLUGIN() [96/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsIronOxide5 , "Iron Oxide 5")
AIRWINDOWSPLUGIN() [97/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsIronOxideClassic , "Iron Oxide Classic")
AIRWINDOWSPLUGIN() [98/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsLeftoMono , "Lefto Mono")
AIRWINDOWSPLUGIN() [99/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsLogical4 , "Logical 4")
AIRWINDOWSPLUGIN() [100/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsLoud , "Loud")
AIRWINDOWSPLUGIN() [101/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsLowpass , "Lowpass")
AIRWINDOWSPLUGIN() [102/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsLowpass2 , "Lowpass 2")
AIRWINDOWSPLUGIN() [103/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsMV , "MV")
AIRWINDOWSPLUGIN() [104/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsMelt , "Melt")
AIRWINDOWSPLUGIN() [105/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsMidSide , "Mid Side")
AIRWINDOWSPLUGIN() [106/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsMoNoam , "Mo Noam")
AIRWINDOWSPLUGIN() [107/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsMojo , "Mojo")
AIRWINDOWSPLUGIN() [108/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsMonitoring , "Monitoring")
AIRWINDOWSPLUGIN() [109/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsNCSeventeen , "NC-17")
AIRWINDOWSPLUGIN() [110/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsNaturalizeDither , "Naturalize Dither")
AIRWINDOWSPLUGIN() [111/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsNodeDither , "Node Dither")
AIRWINDOWSPLUGIN() [112/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsNoise , "Noise")
AIRWINDOWSPLUGIN() [113/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsNonlinearSpace , "Nonlinear Space")
AIRWINDOWSPLUGIN() [114/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsNotJustAnotherCD , "Not Just Another CD")
AIRWINDOWSPLUGIN() [115/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsNotJustAnotherDither , "Not Just Another Dither")
AIRWINDOWSPLUGIN() [116/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsOneCornerClip , "One Corner Clip")
AIRWINDOWSPLUGIN() [117/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPDBuss , "PD Buss")
AIRWINDOWSPLUGIN() [118/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPDChannel , "PD Channel")
AIRWINDOWSPLUGIN() [119/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPafnuty , "Pafnuty")
AIRWINDOWSPLUGIN() [120/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPaulDither , "Paul Dither")
AIRWINDOWSPLUGIN() [121/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPeaksOnly , "Peaks Only")
AIRWINDOWSPLUGIN() [122/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPhaseNudge , "Phase Nudge")
AIRWINDOWSPLUGIN() [123/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPocketVerbs , "Pocket Verbs")
AIRWINDOWSPLUGIN() [124/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPodcast , "Podcast")
AIRWINDOWSPLUGIN() [125/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPodcastDeluxe , "Podcast Deluxe")
AIRWINDOWSPLUGIN() [126/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPoint , "Point")
AIRWINDOWSPLUGIN() [127/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPop , "Pop")
AIRWINDOWSPLUGIN() [128/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPowerSag , "Power Sag")
AIRWINDOWSPLUGIN() [129/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPowerSag2 , "Power Sag 2")
AIRWINDOWSPLUGIN() [130/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPressure4 , "Pressure 4")
AIRWINDOWSPLUGIN() [131/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPurestAir , "Purest Air")
AIRWINDOWSPLUGIN() [132/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPurestConsoleBuss , "Purest Console Buss")
AIRWINDOWSPLUGIN() [133/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPurestConsoleChannel , "Purest Console Channel")
AIRWINDOWSPLUGIN() [134/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPurestDrive , "Purest Drive")
AIRWINDOWSPLUGIN() [135/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPurestEcho , "Purest Echo")
AIRWINDOWSPLUGIN() [136/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPurestGain , "Purest Gain")
AIRWINDOWSPLUGIN() [137/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPurestSquish , "Purest Squish")
AIRWINDOWSPLUGIN() [138/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPurestWarm , "Purest Warm")
AIRWINDOWSPLUGIN() [139/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsPyewacket , "Pyewacket")
AIRWINDOWSPLUGIN() [140/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsRawGlitters , "Raw Glitters")
AIRWINDOWSPLUGIN() [141/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsRawTimbers , "Raw Timbers")
AIRWINDOWSPLUGIN() [142/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsRecurve , "Recurve")
AIRWINDOWSPLUGIN() [143/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsRemap , "Remap")
AIRWINDOWSPLUGIN() [144/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsResEQ , "ResEQ")
AIRWINDOWSPLUGIN() [145/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsRighteous4 , "Righteous 4")
AIRWINDOWSPLUGIN() [146/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsRightoMono , "Righto Mono")
AIRWINDOWSPLUGIN() [147/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsSideDull , "Side Dull")
AIRWINDOWSPLUGIN() [148/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsSidepass , "Sidepass")
AIRWINDOWSPLUGIN() [149/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsSingleEndedTriode , "Single Ended Triode")
AIRWINDOWSPLUGIN() [150/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsSlew , "Slew")
AIRWINDOWSPLUGIN() [151/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsSlew2 , "Slew 2")
AIRWINDOWSPLUGIN() [152/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsSlewOnly , "Slew Only")
AIRWINDOWSPLUGIN() [153/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsSmooth , "Smooth")
AIRWINDOWSPLUGIN() [154/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsSoftGate , "Soft Gate")
AIRWINDOWSPLUGIN() [155/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsSpatializeDither , "Spatialize Dither")
AIRWINDOWSPLUGIN() [156/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsSpiral , "Spiral")
AIRWINDOWSPLUGIN() [157/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsSpiral2 , "Spiral 2")
AIRWINDOWSPLUGIN() [158/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsStarChild , "Star Child")
AIRWINDOWSPLUGIN() [159/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsStereoFX , "Stereo FX")
AIRWINDOWSPLUGIN() [160/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsStudioTan , "Studio Tan")
AIRWINDOWSPLUGIN() [161/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsSubsOnly , "Subs Only")
AIRWINDOWSPLUGIN() [162/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsSurge , "Surge")
AIRWINDOWSPLUGIN() [163/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsSurgeTide , "Surge Tide")
AIRWINDOWSPLUGIN() [164/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsSwell , "Swell")
AIRWINDOWSPLUGIN() [165/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsTPDFDither , "TPDF Dither")
AIRWINDOWSPLUGIN() [166/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsTapeDelay , "Tape Delay")
AIRWINDOWSPLUGIN() [167/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsTapeDither , "Tape Dither")
AIRWINDOWSPLUGIN() [168/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsTapeDust , "Tape Dust")
AIRWINDOWSPLUGIN() [169/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsTapeFat , "Tape Fat")
AIRWINDOWSPLUGIN() [170/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsThunder , "Thunder")
AIRWINDOWSPLUGIN() [171/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsToTape5 , "To Tape 5")
AIRWINDOWSPLUGIN() [172/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsToVinyl4 , "To Vinyl 4")
AIRWINDOWSPLUGIN() [173/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsToneSlant , "Tone Slant")
AIRWINDOWSPLUGIN() [174/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsTransDesk , "Trans Desk")
AIRWINDOWSPLUGIN() [175/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsTremolo , "Tremolo")
AIRWINDOWSPLUGIN() [176/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsTubeDesk , "Tube Desk")
AIRWINDOWSPLUGIN() [177/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsUnBox , "Un Box")
AIRWINDOWSPLUGIN() [178/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsVariMu , "Vari Mu")
AIRWINDOWSPLUGIN() [179/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsVibrato , "Vibrato")
AIRWINDOWSPLUGIN() [180/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsVinylDither , "Vinyl Dither")
AIRWINDOWSPLUGIN() [181/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsVoiceOfTheStarship , "Voice Of The Starship")
AIRWINDOWSPLUGIN() [182/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsVoiceTrick , "Voice Trick")
AIRWINDOWSPLUGIN() [183/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsWider , "Wider")
AIRWINDOWSPLUGIN() [184/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowscurve , "curve")
AIRWINDOWSPLUGIN() [185/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsuLawDecode , "u Law Decode")
AIRWINDOWSPLUGIN() [186/186]
tracktion_engine::AIRWINDOWSPLUGIN (AirWindowsuLawEncode , "u Law Encode")
createIdentifierString()
juce::String tracktion_engine::createIdentifierString (const juce::PluginDescription &)
Referenced by tracktion_engine::ExternalPlugin::getIdentifierString().
createSearchForKeywords()
SearchOperation* tracktion_engine::createSearchForKeywords (const juce::String & keywords)
turns a keyword string into a search condition tree.
callBlocking()
bool tracktion_engine::callBlocking (std::function< void()> f)
References tracktion_engine::MessageThreadCallback::hasFinished(), and tracktion_engine::MessageThreadCallback::triggerAndWaitForCallback().
dbToGain()
float tracktion_engine::dbToGain (float db) noexcept
Referenced by tracktion_engine::LiveClipLevel::getGain(), and tracktion_engine::AudioClipBase::getGain().
gainToDb()
float tracktion_engine::gainToDb (float gain) noexcept
gainToDbString()
juce::String tracktion_engine::gainToDbString (float gain, float infLevel = -96.0f, int decPlaces = 2)
dbStringToDb()
float tracktion_engine::dbStringToDb (const juce::String & dbStr)
Referenced by tracktion_engine::ExternalAutomatableParameter::stringToValue().
dbStringToGain()
float tracktion_engine::dbStringToGain (const juce::String & dbStr)
getPanString()
juce::String tracktion_engine::getPanString (float pan)
getSemitonesAsString()
juce::String tracktion_engine::getSemitonesAsString (double semitones)
midiNoteToFrequency()
template<typename FloatType > FloatType tracktion_engine::midiNoteToFrequency (FloatType midiNote)
frequencyToMidiNote()
template<typename FloatType > FloatType tracktion_engine::frequencyToMidiNote (FloatType freq)
sanitiseValues()
void tracktion_engine::sanitiseValues (juce::AudioBuffer< float > & , int startSample, int numSamples, float maxAbsValue, float minAbsThreshold = 1.0f/262144.0f)
addAntiDenormalisationNoise()
void tracktion_engine::addAntiDenormalisationNoise (juce::AudioBuffer< float > & , int start, int numSamples) noexcept
resetFP()
void tracktion_engine::resetFP () noexcept
hasFloatingPointDenormaliseOccurred()
bool tracktion_engine::hasFloatingPointDenormaliseOccurred () noexcept
zeroDenormalisedValuesIfNeeded()
void tracktion_engine::zeroDenormalisedValuesIfNeeded (juce::AudioBuffer< float > &) noexcept
isAudioDataAlmostSilent()
bool tracktion_engine::isAudioDataAlmostSilent (const float * data, int num)
getAudioDataMagnitude()
float tracktion_engine::getAudioDataMagnitude (const float * data, int num)
convertIntsToFloats()
void tracktion_engine::convertIntsToFloats (juce::AudioBuffer< float > &)
convertFloatsToInts()
void tracktion_engine::convertFloatsToInts (juce::AudioBuffer< float > &)
yieldGUIThread()
void tracktion_engine::yieldGUIThread () noexcept
toBufferView()
template<typename SampleType > choc::buffer::BufferView<SampleType, choc::buffer::SeparateChannelLayout> tracktion_engine::toBufferView (juce::AudioBuffer< SampleType > & buffer)
Converts a juce::AudioBuffer<SampleType> to a choc::buffer::BufferView.
getDefaultPanLaw()
PanLaw tracktion_engine::getDefaultPanLaw () noexcept
setDefaultPanLaw()
void tracktion_engine::setDefaultPanLaw (PanLaw)
getPanLawChoices()
juce::StringArray tracktion_engine::getPanLawChoices (bool includeDefault) noexcept
decibelsToVolumeFaderPosition()
float tracktion_engine::decibelsToVolumeFaderPosition (float dB) noexcept
volumeFaderPositionToDB()
float tracktion_engine::volumeFaderPositionToDB (float position) noexcept
Referenced by tracktion_engine::AuxSendPlugin::getGainDb().
volumeFaderPositionToGain()
float tracktion_engine::volumeFaderPositionToGain (float position) noexcept
gainToVolumeFaderPosition()
float tracktion_engine::gainToVolumeFaderPosition (float gain) noexcept
getGainsFromVolumeFaderPositionAndPan()
void tracktion_engine::getGainsFromVolumeFaderPositionAndPan (float volSliderPos, float pan, PanLaw lawToUse, float & leftGain, float & rightGain) noexcept
clearChannels()
void tracktion_engine::clearChannels (juce::AudioBuffer< float > & buffer, int startChannel, int endChannel = -1, int startSample = 0, int endSample = -1)
createBenchmarkDescription()
BenchmarkDescription tracktion_engine::createBenchmarkDescription (std::string category, std::string name, std::string description)
Creates a description by hashing the name and description fields.
Referenced by tracktion_engine::benchmark_utilities::prepareRenderAndDestroy(), and tracktion_engine::benchmark_utilities::renderEdit().
createBenchmarkResult()
BenchmarkResult tracktion_engine::createBenchmarkResult (BenchmarkDescription description, const tracktion_graph::PerformanceMeasurement::Statistics & stats)
Creates a BenchmarkResult from a set of Statistics.
References tracktion_graph::PerformanceMeasurement::Statistics::getVariance(), tracktion_graph::PerformanceMeasurement::Statistics::maximumSeconds, tracktion_graph::PerformanceMeasurement::Statistics::meanSeconds, tracktion_graph::PerformanceMeasurement::Statistics::minimumSeconds, and tracktion_graph::PerformanceMeasurement::Statistics::totalSeconds.
Referenced by tracktion_engine::Benchmark::getResult(), and tracktion_engine::benchmark_utilities::prepareRenderAndDestroy().
getApplicationSettings()
juce::PropertiesFile* tracktion_engine::getApplicationSettings ()
getCurrentPositionInfo()
juce::AudioPlayHead::CurrentPositionInfo tracktion_engine::getCurrentPositionInfo (Edit &)
Converts an Edit's internal transport information to a juce::AudioPlayHead::CurrentPositionInfo.
synchroniseEditPosition()
void tracktion_engine::synchroniseEditPosition (Edit & , const juce::AudioPlayHead::CurrentPositionInfo &)
Syncs an Edit's transport and tempo sequence to a juce AudioPlayHead.
isMidiFile()
bool tracktion_engine::isMidiFile (const juce::File &)
isTracktionEditFile()
bool tracktion_engine::isTracktionEditFile (const juce::File &)
Referenced by tracktion_engine::benchmark_utilities::openEditfromArchiveData().
isTracktionArchiveFile()
bool tracktion_engine::isTracktionArchiveFile (const juce::File &)
isTracktionProjectFile()
bool tracktion_engine::isTracktionProjectFile (const juce::File &)
isTracktionPresetFile()
bool tracktion_engine::isTracktionPresetFile (const juce::File &)
getNonExistentSiblingWithIncrementedNumberSuffix()
juce::File tracktion_engine::getNonExistentSiblingWithIncrementedNumberSuffix (const juce::File & , bool addHashSymbol)
addSortedListToMenu()
void tracktion_engine::addSortedListToMenu (juce::PopupMenu & m, juce::StringArray names, int startID)
References operator<().
getScaleAroundCentre()
juce::AffineTransform tracktion_engine::getScaleAroundCentre (juce::Rectangle< float > r, float numPixels)
indexOfFirstFoundInSecond()
int tracktion_engine::indexOfFirstFoundInSecond (const juce::StringArray & array1, const juce::StringArray & array2) noexcept
Returns the index in the first array of the first match found.
This is usually just used to find out if there are any matches between the two arrays.
allFirstFoundInSecond()
bool tracktion_engine::allFirstFoundInSecond (const juce::StringArray & array1, const juce::StringArray & array2) noexcept
Returns true if all of the strings of the first array are found in the second array.
moveXMLAttributeToStart()
void tracktion_engine::moveXMLAttributeToStart (juce::XmlElement & xml, juce::StringRef att)
removeIf()
template<typename Vector , typename Predicate > bool tracktion_engine::removeIf (Vector & v, Predicate && pred)
almostEqual()
template<typename FloatingPointType > bool tracktion_engine::almostEqual (FloatingPointType firstValue, FloatingPointType secondValue, FloatingPointType precision = (FloatingPointType) 0.00001)
Checks to see if two values are equal within a given precision.
matchesAnyOf()
template<typename Type > bool tracktion_engine::matchesAnyOf (const Type & needle, const std::initializer_list< Type > & haystack)
Returns true if the needle is found in the haystack.
forEachItem()
template<typename Type , typename UnaryFunction > void tracktion_engine::forEachItem (const juce::Array< Type * > & items, const UnaryFunction & fn)
Calls a function object on each item in an array.
addValueTreeProperties()
template<typename... Others> void tracktion_engine::addValueTreeProperties (juce::ValueTree & v, const juce::Identifier & name, const juce::var & value, Others &&... others)
Referenced by createValueTree().
createValueTree()
template<typename... Properties> juce::ValueTree tracktion_engine::createValueTree (const juce::Identifier & name, Properties &&... properties)
References addValueTreeProperties().
removeInvalidValueTrees()
juce::Array<juce::ValueTree>& tracktion_engine::removeInvalidValueTrees (juce::Array< juce::ValueTree > & trees)
Strips out any invalid trees from the array.
getTreesOfType()
juce::Array<juce::ValueTree> tracktion_engine::getTreesOfType (const juce::Array< juce::ValueTree > & trees, const juce::Identifier & type)
Returns a new array with any trees without the given type removed.
getChildTreesRecursive()
void tracktion_engine::getChildTreesRecursive (juce::Array< juce::ValueTree > & result, const juce::ValueTree & tree)
renamePropertyRecursive()
void tracktion_engine::renamePropertyRecursive (juce::ValueTree & tree, const juce::Identifier & oldName, const juce::Identifier & newName, juce::UndoManager * um)
Variable Documentation
projectFileSuffix
const char* const tracktion_engine::projectFileSuffix = ".tracktion"
editFileSuffix
const char* const tracktion_engine::editFileSuffix = ".tracktionedit"
legacyEditFileSuffix
const char* const tracktion_engine::legacyEditFileSuffix = ".trkedit"
archiveFileSuffix
const char* const tracktion_engine::archiveFileSuffix = ".trkarch"
soundFileWildCard
const char* const tracktion_engine::soundFileWildCard = "*.wav;*.aiff;*.aif;*.ogg;*.mp3;*.flac;*.au;*.voc;*.caf;*.w64;*.rx2;*.rcy;*.rex;*.wfaf"
soundFileAndMidiWildCard
const char* const tracktion_engine::soundFileAndMidiWildCard = "*.wav;*.aiff;*.aif;*.ogg;*.mp3;*.mid;*.midi;*.flac;*.au;*.voc;*.caf;*.w64;*.rx2;*.rcy;*.rex;*.wfaf"
midiFileWildCard
const char* const tracktion_engine::midiFileWildCard = "*.midi;*.mid"
keyMapWildCard
const char* const tracktion_engine::keyMapWildCard = "*.tracktionkeys"
keyMapSuffix
const char* const tracktion_engine::keyMapSuffix = ".tracktionkeys"
customControllerFileSuffix
const char* const tracktion_engine::customControllerFileSuffix = ".trkctrlr"
customProgramSetWildcard
const char* const tracktion_engine::customProgramSetWildcard = "*.trkmidi;*.midnam"
customProgramSetFileSuffix
const char* const tracktion_engine::customProgramSetFileSuffix = ".trkmidi"
presetFileSuffix
const char* const tracktion_engine::presetFileSuffix = ".trkpreset"
rackFileSuffix
const char* const tracktion_engine::rackFileSuffix = ".trkrack"
scriptFileSuffix
const char* const tracktion_engine::scriptFileSuffix = ".tracktionscript"
grooveTemplateSuffix
const char* const tracktion_engine::grooveTemplateSuffix = ".trkgroove"
grooveTemplateWildCard
const char* const tracktion_engine::grooveTemplateWildCard = "*.trkgroove"