TracktionEngine: tracktion_graph Namespace Reference
tracktion_graph Namespace Reference
Namespaces
detail
node_player_utils
test_utilities
Classes
class AudioBufferPool
A lock-free pool of audio buffers.
class AudioBufferStack
A stack of audio buffers.
class AudioFifo
class BasicSummingNode
struct ChannelConnection
class ChannelRemappingNode
Maps channels from one to another.
class ConnectedNode
An Node which sums together the multiple inputs adding additional latency to provide a coherent output.
class ForwardingNode
Takes a non-owning input node and simply forwards its outputs on.
class FunctionNode
class GainNode
class LatencyNode
struct LatencyProcessor
class LightweightSemaphore
A counting semaphore that spins on a atomic before waiting so will avoid system calls if wait periods are very short.
class LockFreeMultiThreadedNodePlayer
Plays back a node with mutiple threads.
class MidiNode
Plays back a MIDI sequence.
class MultiThreadedNodePlayer
Plays back a node with mutiple threads.
class Node
Main graph Node processor class.
struct NodeBuffer
Holds a view over some data and optionally some storage for that data.
struct NodeOptimisations
Holds some hints that might be used by the Node or players to improve efficiency.
class NodePlayer
Simple player for an Node.
struct NodeProperties
Holds some really basic properties of a node.
struct PlaybackInitialisationInfo
Passed into Nodes when they are being initialised, to give them useful contextual information that they may need.
class PlayHead
Converts a monotonically increasing reference range in to a timeline range.
class PlayHeadState
Determines how this block releates to other previous render blocks and if the play head has jumped in time.
class RealTimeSpinLock
A basic spin lock that uses an atomic_flag to store the locked state so should never result in a system call.
class ReturnNode
class Semaphore
A basic counting semaphore.
class SendNode
class SilentNode
Just a simple audio node that doesn't take any input so can be used as a stub.
class SimpleNodePlayer
Simple player for a Node.
class SinkNode
Blocks audio and MIDI input from reaching the outputs.
class SinNode
struct SplitTimelineRange
Represents a pair of timeline ranges which could be wraped around the loop end.
class SummingNode
An Node which sums together the multiple inputs adding additional latency to provide a coherent output.
Enumerations
enum ClearBuffers { ClearBuffers::no, ClearBuffers::yes }
enum AllocateAudioBuffer { AllocateAudioBuffer::no, AllocateAudioBuffer::yes }
enum VertexOrdering {
VertexOrdering::preordering, VertexOrdering::postordering, VertexOrdering::reversePreordering, VertexOrdering::reversePostordering,
VertexOrdering::bfsPreordering, VertexOrdering::bfsReversePreordering
}
Specifies the ordering algorithm.
enum ThreadPoolStrategy {
ThreadPoolStrategy::conditionVariable, ThreadPoolStrategy::realTime, ThreadPoolStrategy::hybrid, ThreadPoolStrategy::semaphore,
ThreadPoolStrategy::lightweightSemaphore, ThreadPoolStrategy::lightweightSemHybrid
}
Available strategies for thread pools.
Functions
template<typename NodeType , typename... Args>
std::unique_ptr< Node > makeNode (Args &&... args)
Creates a node of the given type and returns it as the base Node class.
template<typename Visitor >
void visitNodes (Node &, Visitor &&, bool preordering)
Should call the visitor for any direct inputs to the node exactly once.
template<typename Visitor >
void visitNodesBFS (Node &node, Visitor &&visitor)
LockFreeMultiThreadedNodePlayer::ThreadPoolCreator getPoolCreatorFunction (ThreadPoolStrategy)
Returns a function to create a ThreadPool for the given stategy.
template<typename T >
void hash_combine (size_t &seed, const T &v)
template<typename It >
std::size_t hash_range (It first, It last)
template<typename It >
void hash_range (std::size_t &seed, It first, It last)
template<typename T >
size_t hash (size_t seed, const T &v)
Hashes a type with a given seed and returns the new hash value.
template<typename IntType >
constexpr double sampleToTime (IntType samplePosition, double sampleRate)
Converts an integer sample number to a time in seconds.
constexpr int64_t timeToSample (double timeInSeconds, double sampleRate)
Converts a time in seconds to a sample number.
template<typename IntType >
constexpr juce::Range< double > sampleToTime (juce::Range< IntType > sampleRange, double sampleRate)
Converts an integer sample range to a time range in seconds.
constexpr juce::Range< int64_t > timeToSample (juce::Range< double > timeInSeconds, double sampleRate)
Converts a time range in seconds to a range of sample numbers.
template<typename RangeType >
constexpr juce::Range< int64_t > timeToSample (RangeType timeInSeconds, double sampleRate)
Converts a time range in seconds to a range of sample numbers.
juce::AudioBuffer< float > toAudioBuffer (choc::buffer::ChannelArrayView< float > view)
Creates a juce::AudioBuffer from a choc::buffer::BufferView.
template<typename SampleType >
choc::buffer::BufferView< SampleType, choc::buffer::SeparateChannelLayout > toBufferView (juce::AudioBuffer< SampleType > &buffer)
Converts a juce::AudioBuffer<SampleType> to a choc::buffer::BufferView.
template<typename BufferViewType , typename SampleType , typename SmoothingType >
void multiplyBy (BufferViewType &view, juce::SmoothedValue< SampleType, SmoothingType > &value) noexcept
Mutiplies a choc::buffer::BufferView by a juce::SmoothedValue.
choc::buffer::FrameRange frameRangeWithStartAndLength (choc::buffer::FrameCount start, choc::buffer::FrameCount length)
Returns a FrameRange with a start and length.
choc::buffer::ChannelRange channelRangeWithStartAndLength (choc::buffer::ChannelCount start, choc::buffer::ChannelCount length)
Returns a ChannelRange with a start and length.
template<typename SampleType , template< typename > typename LayoutType>
void sanityCheckView (const choc::buffer::BufferView< SampleType, LayoutType > &view)
Checks that the channels have valid pointers if they have a non-zero number of frames.
bool setThreadPriority (std::thread &, int priority)
Changes the thread's priority.
Detailed Description
Aims:
Separate graph structure from processing and any model
Ensure nodes can be processed multi-threaded which scales independantly of graph complexity
Processing can happen in any sized block (up to the maximum prepared for)
Process calls will only ever get the number of channels to fill that they report
Process calls will always provide empty buffers so nodes can simply "add" in to them. (Measure performance here)
Processing in float or double
Notes:
Each node should have pointers to its inputs
When a node is processed, it should check its inputs to see if they have produced outputs
If they have, that node can be processed. If they haven't the processor can try another node
If one node reports latency, every other node being summed with it will need to be delayed up to the same ammount
The reported latency of a node is the max of all its input latencies
Initialisation:
There really needs to be two stages for this:
Stage 1 is a simple visit of all the base nodes (i.e. no send/return connections). This will get a list of all the nodes in the graph
Stage 2 will be the initialise call with a flat list of all the nodes. Send/return nodes can use this to add inputs from the graph (e.g. based on busNum) (However, at this stage, return nodes might choose to add latency nodes to balance themselves???) (Maybe this should have to happen when the graph is built? That would mean latency needs to be fixed, and therefore plugins would need to be initialised before graph construction.)
Now we have a fully connected graph we can do a proper DFS:
This can be used to balance processing buffers between the graph by finding unconnected nodes
Finding a processing order by building "stacks" of nodes starting with leafs
This might look like the following steps:
visitAcyclic (Visitor) [only visit nodes that it was constructed with, used to create the flat list]
initialise (const PlaybackInitialisationInfo&) [used to add extra connections and balance latency etc.]
visitDFS (Visitor) [used to get list of nodes to process and can be called multiple times to optomise graph etc.]
Avoiding incontinuities when latency changes:
One of the bg problems with this latency balancing approach is when the graph is rebuilt, any stateful buffers will be lost.
The only way I can think of solving this is to either reusue the latency nodes directly or reuse the buffers
The biggest problem here is finding which nodes correspond to the new and old graphs
The only way I can currently think of is:
Each node to have a UID when it is constructed based on its properties (source material, connections etc.)
During the initialisation stage, the old nodes can be passed on to the new nodes and if they have the same UID, the take any resources they need
There will probably need to be some validation to ensure that two nodes don't have the same UID
For things like clip/plugin nodes the UID is simple (EditItemID)
For latency nodes etc. it will probably have to be based on the input ID and channel index etc.
Buffer optimisation:
As there will be a lot of nodes, it makes sense to reduce the memory footprint by reusing audio and MIDI buffers
There are two ways I can think of doing this:
Analyse the graph and where nodes are sequential but not directly connected, use the same buffer
Use a buffer pool and release it when all nodes have read from it.
This would probably require all nodes that need the output buffer to call "retain" on the node before the processing stage and then "release" once they're done with it. When the count drops to 0 the buffers can be released back to the pool
Enumeration Type Documentation
ClearBuffers
enum tracktion_graph::ClearBuffers strong
Enumerator
no
Don't clear buffers before passing them to process, your subclass will take care of that.
yes
Do clear buffers before passing to process so your subclass can simply add in to them.
AllocateAudioBuffer
enum tracktion_graph::AllocateAudioBuffer strong
Enumerator
no
Don't allocate an audio buffer, your subclass will ignore the dest buffer passed to process and simply use setAudioOutput to pass the buffer along.
yes
Do allocate an audio buffer so your subclass use the dest buffer passed to process.
VertexOrdering
enum tracktion_graph::VertexOrdering strong
Specifies the ordering algorithm.
Enumerator
preordering
postordering
reversePreordering
reversePostordering
bfsPreordering
bfsReversePreordering
ThreadPoolStrategy
enum tracktion_graph::ThreadPoolStrategy strong
Available strategies for thread pools.
This will determine how worker threads are handled when no Nodes are available for processing.
Enumerator
conditionVariable
Uses CVs to pause threads.
realTime
Uses pause, yield and sleeps to suspend threads.
hybrid
Uses a combination of the above, avoiding CVs on the audio thread.
semaphore
Uses a semaphore to suspend threads.
lightweightSemaphore
Uses a semaphore/spin mechanism to suspend threads.
lightweightSemHybrid
Uses a combination of semaphores/spin and yields to suspend threads.
Function Documentation
makeNode()
template<typename NodeType , typename... Args> std::unique_ptr<Node> tracktion_graph::makeNode (Args &&... args)
Creates a node of the given type and returns it as the base Node class.
visitNodes()
template<typename Visitor > void tracktion_graph::visitNodes (Node & node, Visitor && visitor, bool preordering)
Should call the visitor for any direct inputs to the node exactly once.
If preordering is true, nodes will be visited before their inputs, if false, inputs will be visited first.
Parameters
Visitor has the signature
void (Node&)
References preordering, and tracktion_graph::detail::VisitNodesWithRecord::visit().
Referenced by tracktion_graph::ConnectedNode::addAudioConnection(), and tracktion_graph::ConnectedNode::addMidiConnection().
visitNodesBFS()
template<typename Visitor > void tracktion_graph::visitNodesBFS (Node & node, Visitor && visitor)
References tracktion_graph::detail::VisitNodesWithRecordBFS::visit().
getPoolCreatorFunction()
LockFreeMultiThreadedNodePlayer::ThreadPoolCreator tracktion_graph::getPoolCreatorFunction (ThreadPoolStrategy)
Returns a function to create a ThreadPool for the given stategy.
Referenced by tracktion_engine::benchmark_utilities::renderEdit().
hash_combine()
template<typename T > void tracktion_graph::hash_combine (size_t & seed, const T & v)
Referenced by tracktion_engine::PlayHeadPositionNode::getNodeProperties(), tracktion_graph::LatencyNode::getNodeProperties(), tracktion_graph::ConnectedNode::getNodeProperties(), tracktion_graph::SummingNode::getNodeProperties(), tracktion_graph::GainNode::getNodeProperties(), tracktion_graph::SendNode::getNodeProperties(), tracktion_graph::ReturnNode::getNodeProperties(), tracktion_graph::ChannelRemappingNode::getNodeProperties(), tracktion_graph::SinkNode::getNodeProperties(), tracktion_graph::ForwardingNode::getNodeProperties(), hash(), and hash_range().
hash_range() [1/2]
template<typename It > std::size_t tracktion_graph::hash_range (It first, It last)
References hash_combine().
hash_range() [2/2]
template<typename It > void tracktion_graph::hash_range (std::size_t & seed, It first, It last)
References hash_combine().
hash()
template<typename T > size_t tracktion_graph::hash (size_t seed, const T & v)
Hashes a type with a given seed and returns the new hash value.
References hash_combine().
sampleToTime() [1/2]
template<typename IntType > constexpr double tracktion_graph::sampleToTime (IntType samplePosition, double sampleRate) constexpr
Converts an integer sample number to a time in seconds.
Referenced by tracktion_graph::LatencyProcessor::clearMIDI(), tracktion_graph::LatencyProcessor::prepareToPlay(), tracktion_graph::LatencyProcessor::readMIDI(), and sampleToTime().
timeToSample() [1/3]
constexpr int64_t tracktion_graph::timeToSample (double timeInSeconds, double sampleRate) constexpr
Converts a time in seconds to a sample number.
Referenced by tracktion_graph::NodePlayer::prepareToPlay(), and timeToSample().
sampleToTime() [2/2]
template<typename IntType > constexpr juce::Range<double> tracktion_graph::sampleToTime (juce::Range< IntType > sampleRange, double sampleRate) constexpr
Converts an integer sample range to a time range in seconds.
References sampleToTime().
timeToSample() [2/3]
constexpr juce::Range<int64_t> tracktion_graph::timeToSample (juce::Range< double > timeInSeconds, double sampleRate) constexpr
Converts a time range in seconds to a range of sample numbers.
References timeToSample().
timeToSample() [3/3]
template<typename RangeType > constexpr juce::Range<int64_t> tracktion_graph::timeToSample (RangeType timeInSeconds, double sampleRate) constexpr
Converts a time range in seconds to a range of sample numbers.
References timeToSample().
toAudioBuffer()
juce::AudioBuffer<float> tracktion_graph::toAudioBuffer (choc::buffer::ChannelArrayView< float > view)
Creates a juce::AudioBuffer from a choc::buffer::BufferView.
Referenced by tracktion_graph::test_utilities::TestProcess< NodePlayerType >::process().
toBufferView()
template<typename SampleType > choc::buffer::BufferView<SampleType, choc::buffer::SeparateChannelLayout> tracktion_graph::toBufferView (juce::AudioBuffer< SampleType > & buffer)
Converts a juce::AudioBuffer<SampleType> to a choc::buffer::BufferView.
multiplyBy()
template<typename BufferViewType , typename SampleType , typename SmoothingType > void tracktion_graph::multiplyBy (BufferViewType & view, juce::SmoothedValue< SampleType, SmoothingType > & value) noexcept
Mutiplies a choc::buffer::BufferView by a juce::SmoothedValue.
frameRangeWithStartAndLength()
choc::buffer::FrameRange tracktion_graph::frameRangeWithStartAndLength (choc::buffer::FrameCount start, choc::buffer::FrameCount length)
Returns a FrameRange with a start and length.
References tracktion_engine::AppFunctions::start().
Referenced by tracktion_graph::NodePlayer::processWithPlayHeadState().
channelRangeWithStartAndLength()
choc::buffer::ChannelRange tracktion_graph::channelRangeWithStartAndLength (choc::buffer::ChannelCount start, choc::buffer::ChannelCount length)
Returns a ChannelRange with a start and length.
References tracktion_engine::AppFunctions::start().
sanityCheckView()
template<typename SampleType , template< typename > typename LayoutType> void tracktion_graph::sanityCheckView (const choc::buffer::BufferView< SampleType, LayoutType > & view)
Checks that the channels have valid pointers if they have a non-zero number of frames.
Referenced by tracktion_engine::InputProvider::getInputs(), and tracktion_engine::InputProvider::setInputs().
setThreadPriority()
bool tracktion_graph::setThreadPriority (std::thread & , int priority)
Changes the thread's priority.
May return false if for some reason the priority can't be changed.
Parameters
priority the new priority, in the range 0 (lowest) to 10 (highest). A priority of 5 is normal.