TracktionEngine: tracktion_engine::TimeStretcher::ElastiqueProOptions Struct Reference
tracktion_engine::TimeStretcher::ElastiqueProOptions Struct Reference
tracktion_engine » timestretch
Public Member Functions
ElastiqueProOptions ()
ElastiqueProOptions (const juce::String &string)
juce::String toString () const
bool operator== (const ElastiqueProOptions &other) const
bool operator!= (const ElastiqueProOptions &other) const
Public Attributes
bool midSideStereo = false
bool syncTimeStrPitchShft = false
bool preserveFormants = false
int envelopeOrder = 64
Constructor & Destructor Documentation
ElastiqueProOptions() [1/2]
tracktion_engine::TimeStretcher::ElastiqueProOptions::ElastiqueProOptions ()
References operator!=(), operator==(), and toString().
ElastiqueProOptions() [2/2]
tracktion_engine::TimeStretcher::ElastiqueProOptions::ElastiqueProOptions (const juce::String & string)
Member Function Documentation
toString()
juce::String tracktion_engine::TimeStretcher::ElastiqueProOptions::toString () const
Referenced by ElastiqueProOptions(), and juce::VariantConverter< tracktion_engine::TimeStretcher::ElastiqueProOptions >::toVar().
operator==()
bool tracktion_engine::TimeStretcher::ElastiqueProOptions::operator== (const ElastiqueProOptions & other) const
Referenced by ElastiqueProOptions().
operator!=()
bool tracktion_engine::TimeStretcher::ElastiqueProOptions::operator!= (const ElastiqueProOptions & other) const
Referenced by ElastiqueProOptions().
Member Data Documentation
midSideStereo
bool tracktion_engine::TimeStretcher::ElastiqueProOptions::midSideStereo = false
syncTimeStrPitchShft
bool tracktion_engine::TimeStretcher::ElastiqueProOptions::syncTimeStrPitchShft = false
preserveFormants
bool tracktion_engine::TimeStretcher::ElastiqueProOptions::preserveFormants = false
envelopeOrder
int tracktion_engine::TimeStretcher::ElastiqueProOptions::envelopeOrder = 64
The documentation for this struct was generated from the following file:
tracktion_TimeStretch.h