TracktionEngine: tracktion_engine::OldEditConversion Struct Reference
tracktion_engine::OldEditConversion Struct Reference
tracktion_engine » model
Logic for reading legacy tracktion edit files.
Static Public Member Functions
static juce::ValueTree convert (const juce::ValueTree &v)
static void convert (juce::XmlElement &editXML)
Detailed Description
Logic for reading legacy tracktion edit files.
(This is an internal class, not intended for public use)
Member Function Documentation
convert() [1/2]
static juce::ValueTree tracktion_engine::OldEditConversion::convert (const juce::ValueTree & v) static
Referenced by tracktion_engine::updateLegacyEdit().
convert() [2/2]
static void tracktion_engine::OldEditConversion::convert (juce::XmlElement & editXML) static
References tracktion_engine::barsBeats, tracktion_engine::TrackItem::clipTypeToXMLType(), CRASH_TRACER, tracktion_engine::decibelsToVolumeFaderPosition(), tracktion_engine::MidiList::defaultInitialPitchBendValue, tracktion_engine::MidiList::defaultInitialPressureValue, tracktion_engine::MidiList::defaultInitialTimbreValue, tracktion_engine::fps24, tracktion_engine::fps25, tracktion_engine::fps30, tracktion_engine::EditItemID::fromRawID(), tracktion_engine::EditItemID::fromXML(), tracktion_engine::ModifierList::isModifier(), tracktion_engine::TrackList::isTrack(), tracktion_engine::EditItemID::isValid(), tracktion_engine::markIn(), tracktion_engine::markOut(), tracktion_engine::millisecs, tracktion_engine::moveXMLAttributeToStart(), tracktion_engine::ModifierCommon::note, tracktion_engine::EditItemID::remapIDs(), tracktion_engine::AppFunctions::start(), tracktion_engine::TrackItem::stringToType(), and tracktion_engine::AuxSendPlugin::xmlTypeName.
The documentation for this struct was generated from the following file:
tracktion_OldEditConversion.h