TracktionEngine: tracktion_engine::Edit::WastedMidiMessagesListener Struct Reference
tracktion_engine::Edit::WastedMidiMessagesListener Struct Reference abstract
tracktion_engine » model
Public Member Functions
virtual ~WastedMidiMessagesListener ()
virtual void warnOfWastedMidiMessages (InputDevice *, Track *)=0
Constructor & Destructor Documentation
~WastedMidiMessagesListener()
virtual tracktion_engine::Edit::WastedMidiMessagesListener::~WastedMidiMessagesListener () virtual
References tracktion_engine::Edit::addWastedMidiMessagesListener(), tracktion_engine::Edit::removeWastedMidiMessagesListener(), and tracktion_engine::Edit::warnOfWastedMidiMessages().
Member Function Documentation
warnOfWastedMidiMessages()
virtual void tracktion_engine::Edit::WastedMidiMessagesListener::warnOfWastedMidiMessages (InputDevice * , Track *) pure virtual
The documentation for this struct was generated from the following file:
tracktion_Edit.h