TracktionEngine: tracktion_engine::SelectableList Struct Reference
tracktion_engine::SelectableList Struct Reference
A list of Selectables, similar to a juce::Array but contains a cached list of the SelectableClasses for each entry.
Public Types
using ScopedLockType = juce::Array< Selectable * >::ScopedLockType
Public Member Functions
SelectableList ()=default
SelectableList (const std::initializer_list< Selectable * > &initialItems)
template<typename SelectableType >
SelectableList (const juce::Array< SelectableType * > &initialItems)
template<typename SelectableType >
SelectableList (const juce::ReferenceCountedArray< SelectableType > &initialItems)
SelectableClass * getSelectableClass (int index) const
Returns the selectable class for a given Selectable in the list.
std::pair< Selectable *, SelectableClass * > getSelectableAndClass (int index) const
Returns the selectable and it's associated class.
template<typename SubclassType >
juce::Array< SubclassType * > getItemsOfType () const
template<typename SubclassType >
SubclassType * getFirstOfType () const
template<typename SubclassType >
bool containsType () const
int size () const
bool isEmpty () const
bool isNotEmpty () const
Selectable ** begin ()
Selectable *const * begin () const
Selectable ** end ()
Selectable *const * end () const
Selectable ** data ()
Selectable *const * data () const
Selectable * operator[] (int index) const
Selectable * getUnchecked (int index) const
Selectable * getFirst () const
Selectable * getLast () const
template<class OtherArrayType >
void addArray (const OtherArrayType &arrayToAddFrom, int startIndex=0, int numElementsToAdd=-1)
template<class OtherArrayType >
void mergeArray (const OtherArrayType &arrayToMergeFrom)
void add (Selectable *newElement)
bool addIfNotAlreadyThere (Selectable *newElement)
void clear ()
void remove (int indexToRemove)
int removeAllInstancesOf (Selectable *s)
Selectable * removeAndReturn (int indexToRemove)
bool contains (Selectable *elementToLookFor) const
int indexOf (Selectable *elementToLookFor) const
juce::Array< Selectable::WeakRef > getAsWeakRefList () const
template<class OtherArrayType >
bool operator== (const OtherArrayType &other) const
template<class OtherArrayType >
bool operator!= (const OtherArrayType &other) const
bool operator== (const SelectableList &other) const
bool operator!= (const SelectableList &other) const
const juce::DummyCriticalSection & getLock () const noexcept
Detailed Description
A list of Selectables, similar to a juce::Array but contains a cached list of the SelectableClasses for each entry.
Member Typedef Documentation
ScopedLockType
using tracktion_engine::SelectableList::ScopedLockType = juce::Array<Selectable*>::ScopedLockType
Constructor & Destructor Documentation
SelectableList() [1/4]
tracktion_engine::SelectableList::SelectableList () default
SelectableList() [2/4]
tracktion_engine::SelectableList::SelectableList (const std::initializer_list< Selectable * > & initialItems)
SelectableList() [3/4]
template<typename SelectableType > tracktion_engine::SelectableList::SelectableList (const juce::Array< SelectableType * > & initialItems)
SelectableList() [4/4]
template<typename SelectableType > tracktion_engine::SelectableList::SelectableList (const juce::ReferenceCountedArray< SelectableType > & initialItems)
Member Function Documentation
getSelectableClass()
SelectableClass* tracktion_engine::SelectableList::getSelectableClass (int index) const
Returns the selectable class for a given Selectable in the list.
getSelectableAndClass()
std::pair<Selectable*, SelectableClass*> tracktion_engine::SelectableList::getSelectableAndClass (int index) const
Returns the selectable and it's associated class.
N.B. This does no bounds checking so make sure index is in range!
getItemsOfType()
template<typename SubclassType > juce::Array<SubclassType*> tracktion_engine::SelectableList::getItemsOfType () const
getFirstOfType()
template<typename SubclassType > SubclassType* tracktion_engine::SelectableList::getFirstOfType () const
containsType()
template<typename SubclassType > bool tracktion_engine::SelectableList::containsType () const
Referenced by tracktion_engine::SelectionManager::containsType().
size()
int tracktion_engine::SelectableList::size () const
isEmpty()
bool tracktion_engine::SelectableList::isEmpty () const
Referenced by isNotEmpty().
isNotEmpty()
bool tracktion_engine::SelectableList::isNotEmpty () const
References isEmpty().
begin() [1/2]
Selectable** tracktion_engine::SelectableList::begin ()
Referenced by data().
begin() [2/2]
Selectable* const* tracktion_engine::SelectableList::begin () const
end() [1/2]
Selectable** tracktion_engine::SelectableList::end ()
end() [2/2]
Selectable* const* tracktion_engine::SelectableList::end () const
data() [1/2]
Selectable** tracktion_engine::SelectableList::data ()
References begin().
data() [2/2]
Selectable* const* tracktion_engine::SelectableList::data () const
References begin().
operator[]()
Selectable* tracktion_engine::SelectableList::operator[] (int index) const
getUnchecked()
Selectable* tracktion_engine::SelectableList::getUnchecked (int index) const
getFirst()
Selectable* tracktion_engine::SelectableList::getFirst () const
getLast()
Selectable* tracktion_engine::SelectableList::getLast () const
addArray()
template<class OtherArrayType > void tracktion_engine::SelectableList::addArray (const OtherArrayType & arrayToAddFrom, int startIndex = 0, int numElementsToAdd = -1)
mergeArray()
template<class OtherArrayType > void tracktion_engine::SelectableList::mergeArray (const OtherArrayType & arrayToMergeFrom)
References addIfNotAlreadyThere().
add()
void tracktion_engine::SelectableList::add (Selectable * newElement)
addIfNotAlreadyThere()
bool tracktion_engine::SelectableList::addIfNotAlreadyThere (Selectable * newElement)
Referenced by mergeArray().
clear()
void tracktion_engine::SelectableList::clear ()
remove()
void tracktion_engine::SelectableList::remove (int indexToRemove)
removeAllInstancesOf()
int tracktion_engine::SelectableList::removeAllInstancesOf (Selectable * s)
removeAndReturn()
Selectable* tracktion_engine::SelectableList::removeAndReturn (int indexToRemove)
contains()
bool tracktion_engine::SelectableList::contains (Selectable * elementToLookFor) const
indexOf()
int tracktion_engine::SelectableList::indexOf (Selectable * elementToLookFor) const
getAsWeakRefList()
juce::Array<Selectable::WeakRef> tracktion_engine::SelectableList::getAsWeakRefList () const
operator==() [1/2]
template<class OtherArrayType > bool tracktion_engine::SelectableList::operator== (const OtherArrayType & other) const
operator!=() [1/2]
template<class OtherArrayType > bool tracktion_engine::SelectableList::operator!= (const OtherArrayType & other) const
operator==() [2/2]
bool tracktion_engine::SelectableList::operator== (const SelectableList & other) const
operator!=() [2/2]
bool tracktion_engine::SelectableList::operator!= (const SelectableList & other) const
getLock()
const juce::DummyCriticalSection& tracktion_engine::SelectableList::getLock () const noexcept
The documentation for this struct was generated from the following file:
tracktion_Selectable.h