TracktionEngine: tracktion::engine::InputDeviceInstance::InputDeviceDestinationList Struct Reference
tracktion::engine::InputDeviceInstance::InputDeviceDestinationList Struct Reference
Public Member Functions
InputDeviceDestinationList (InputDeviceInstance &i, const juce::ValueTree &v)
~InputDeviceDestinationList () override
bool isSuitableType (const juce::ValueTree &v) const override
InputDeviceDestination * createNewObject (const juce::ValueTree &v) override
void deleteObject (InputDeviceDestination *c) override
void newObjectAdded (InputDeviceDestination *) override
void objectRemoved (InputDeviceDestination *) override
void objectOrderChanged () override
Public Member Functions inherited from tracktion::engine::ValueTreeObjectList< InputDeviceDestination >
ValueTreeObjectList (const juce::ValueTree &parentTree)
~ValueTreeObjectList () override
int size () const
bool isEmpty () const noexcept
InputDeviceDestination * operator[] (int idx) const
InputDeviceDestination * at (int idx)
InputDeviceDestination ** begin ()
InputDeviceDestination *const * begin () const
InputDeviceDestination ** end ()
InputDeviceDestination *const * end () const
void rebuildObjects ()
void freeObjects ()
virtual void deleteObject (InputDeviceDestination *)=0
virtual void newObjectAdded (InputDeviceDestination *)=0
virtual void objectRemoved (InputDeviceDestination *)=0
void valueTreeChildAdded (juce::ValueTree &, juce::ValueTree &tree) override
void valueTreeChildRemoved (juce::ValueTree &exParent, juce::ValueTree &tree, int) override
void valueTreeChildOrderChanged (juce::ValueTree &tree, int, int) override
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeParentChanged (juce::ValueTree &) override
void valueTreeRedirected (juce::ValueTree &) override
int compareElements (InputDeviceDestination *first, InputDeviceDestination *second) const
ValueTreeObjectList (const juce::ValueTree &parentTree)
~ValueTreeObjectList () override
int size () const
bool isEmpty () const noexcept
InputDeviceDestination * operator[] (int idx) const
InputDeviceDestination * at (int idx)
InputDeviceDestination ** begin ()
InputDeviceDestination *const * begin () const
InputDeviceDestination ** end ()
InputDeviceDestination *const * end () const
void rebuildObjects ()
void freeObjects ()
virtual void deleteObject (InputDeviceDestination *)=0
virtual void newObjectAdded (InputDeviceDestination *)=0
virtual void objectRemoved (InputDeviceDestination *)=0
void valueTreeChildAdded (juce::ValueTree &, juce::ValueTree &tree) override
void valueTreeChildRemoved (juce::ValueTree &exParent, juce::ValueTree &tree, int) override
void valueTreeChildOrderChanged (juce::ValueTree &tree, int, int) override
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeParentChanged (juce::ValueTree &) override
void valueTreeRedirected (juce::ValueTree &) override
int compareElements (InputDeviceDestination *first, InputDeviceDestination *second) const
Public Attributes
InputDeviceInstance & input
Public Attributes inherited from tracktion::engine::ValueTreeObjectList< InputDeviceDestination >
juce::Array< InputDeviceDestination * > objects
juce::DummyCriticalSection arrayLock
juce::Array< InputDeviceDestination * > objects
juce::DummyCriticalSection arrayLock
Additional Inherited Members
Public Types inherited from tracktion::engine::ValueTreeObjectList< InputDeviceDestination >
using ScopedLockType = typename CriticalSectionType::ScopedLockType
using ScopedLockType = typename CriticalSectionType::ScopedLockType
Protected Member Functions inherited from tracktion::engine::ValueTreeObjectList< InputDeviceDestination >
void deleteAllObjects ()
bool isChildTree (juce::ValueTree &v) const
int indexOf (const juce::ValueTree &v) const noexcept
void sortArray ()
void deleteAllObjects ()
bool isChildTree (juce::ValueTree &v) const
int indexOf (const juce::ValueTree &v) const noexcept
void sortArray ()
Protected Attributes inherited from tracktion::engine::ValueTreeObjectList< InputDeviceDestination >
juce::ValueTree parent
juce::ValueTree parent
Constructor & Destructor Documentation
InputDeviceDestinationList()
tracktion::engine::InputDeviceInstance::InputDeviceDestinationList::InputDeviceDestinationList (InputDeviceInstance & i, const juce::ValueTree & v)
References tracktion::engine::ValueTreeObjectList< InputDeviceDestination >::rebuildObjects().
~InputDeviceDestinationList()
tracktion::engine::InputDeviceInstance::InputDeviceDestinationList::~InputDeviceDestinationList () override
References tracktion::engine::ValueTreeObjectList< InputDeviceDestination >::freeObjects().
Member Function Documentation
isSuitableType()
bool tracktion::engine::InputDeviceInstance::InputDeviceDestinationList::isSuitableType (const juce::ValueTree & v) const override virtual
Implements tracktion::engine::ValueTreeObjectList< InputDeviceDestination >.
createNewObject()
InputDeviceDestination* tracktion::engine::InputDeviceInstance::InputDeviceDestinationList::createNewObject (const juce::ValueTree & v) override virtual
Implements tracktion::engine::ValueTreeObjectList< InputDeviceDestination >.
References tracktion::engine::InputDevice::getDeviceType(), tracktion::engine::InputDeviceInstance::getInputDevice(), input, tracktion::engine::InputDevice::physicalMidiDevice, tracktion::engine::InputDevice::trackMidiDevice, tracktion::engine::InputDevice::trackWaveDevice, tracktion::engine::InputDevice::virtualMidiDevice, and tracktion::engine::InputDevice::waveDevice.
deleteObject()
void tracktion::engine::InputDeviceInstance::InputDeviceDestinationList::deleteObject (InputDeviceDestination * c) override
newObjectAdded()
void tracktion::engine::InputDeviceInstance::InputDeviceDestinationList::newObjectAdded (InputDeviceDestination *) override
objectRemoved()
void tracktion::engine::InputDeviceInstance::InputDeviceDestinationList::objectRemoved (InputDeviceDestination *) override
objectOrderChanged()
void tracktion::engine::InputDeviceInstance::InputDeviceDestinationList::objectOrderChanged () override virtual
Implements tracktion::engine::ValueTreeObjectList< InputDeviceDestination >.
Member Data Documentation
input
InputDeviceInstance& tracktion::engine::InputDeviceInstance::InputDeviceDestinationList::input
Referenced by createNewObject().
The documentation for this struct was generated from the following file:
tracktion_InputDevice.h