TracktionEngine: tracktion::engine::MidiChannel Struct Reference
tracktion::engine::MidiChannel Struct Reference
Represents a MIDI channel 1-16, and also contains extra ID bits to encode info about the event's origin.
Public Member Functions
MidiChannel ()=default
MidiChannel (const MidiChannel &)=default
MidiChannel & operator= (const MidiChannel &)=default
MidiChannel (int channelNumber1to16) noexcept
MidiChannel (const juce::var &storedChannel) noexcept
int getChannelNumber () const noexcept
bool isValid () const noexcept
bool operator== (const MidiChannel &other) const noexcept
bool operator!= (const MidiChannel &other) const noexcept
operator juce::var () const
Static Public Member Functions
static MidiChannel fromChannelOrZero (int channel) noexcept
Detailed Description
Represents a MIDI channel 1-16, and also contains extra ID bits to encode info about the event's origin.
Constructor & Destructor Documentation
MidiChannel() [1/4]
tracktion::engine::MidiChannel::MidiChannel () default
MidiChannel() [2/4]
tracktion::engine::MidiChannel::MidiChannel (const MidiChannel &) default
MidiChannel() [3/4]
tracktion::engine::MidiChannel::MidiChannel (int channelNumber1to16) explicit noexcept
MidiChannel() [4/4]
tracktion::engine::MidiChannel::MidiChannel (const juce::var & storedChannel) explicit noexcept
References isValid().
Member Function Documentation
operator=()
MidiChannel& tracktion::engine::MidiChannel::operator= (const MidiChannel &) default
fromChannelOrZero()
static MidiChannel tracktion::engine::MidiChannel::fromChannelOrZero (int channel) static noexcept
getChannelNumber()
int tracktion::engine::MidiChannel::getChannelNumber () const noexcept
Referenced by tracktion::engine::MidiClip::isRhythm(), and operator juce::var().
isValid()
bool tracktion::engine::MidiChannel::isValid () const noexcept
Referenced by MidiChannel().
operator==()
bool tracktion::engine::MidiChannel::operator== (const MidiChannel & other) const noexcept
operator!=()
bool tracktion::engine::MidiChannel::operator!= (const MidiChannel & other) const noexcept
operator juce::var()
tracktion::engine::MidiChannel::operator juce::var () const
References getChannelNumber().
The documentation for this struct was generated from the following file:
tracktion_MidiChannel.h