TracktionEngine: tracktion_engine::EditTimeRange Struct Reference
tracktion_engine::EditTimeRange Struct Reference
Public Member Functions
EditTimeRange ()=default
EditTimeRange (const EditTimeRange &)=default
EditTimeRange & operator= (const EditTimeRange &)=default
EditTimeRange (double start, double end)
EditTimeRange (juce::Range< double > timeRange)
double getStart () const
double getEnd () const
double getLength () const
double getCentre () const
double clipValue (double value) const
bool isEmpty () const
bool operator== (const EditTimeRange &other) const
bool operator!= (const EditTimeRange &other) const
bool overlaps (const EditTimeRange &other) const
bool contains (const EditTimeRange &other) const
bool contains (double time) const
bool containsInclusive (double time) const
EditTimeRange getUnionWith (EditTimeRange other) const
EditTimeRange getIntersectionWith (EditTimeRange other) const
EditTimeRange rescaled (double anchorTime, double factor) const
EditTimeRange constrainRange (EditTimeRange rangeToConstrain) const
EditTimeRange expanded (double amount) const
EditTimeRange reduced (double amount) const
EditTimeRange movedToStartAt (double newStart) const
EditTimeRange movedToEndAt (double newEnd) const
EditTimeRange withStart (double newStart) const
EditTimeRange withEnd (double newEnd) const
EditTimeRange withLength (double newLength) const
EditTimeRange operator+ (double amount) const
EditTimeRange operator- (double amount) const
Static Public Member Functions
static EditTimeRange between (double time1, double time2)
Returns the range that lies between two positions (in either order).
static EditTimeRange withStartAndLength (double time1, double length)
Returns a range with a given start and length.
static EditTimeRange emptyRange (double start)
Returns a range with the specified start position and a length of zero.
Public Attributes
double start = 0
double end = 0
Constructor & Destructor Documentation
EditTimeRange() [1/4]
tracktion_engine::EditTimeRange::EditTimeRange () default
EditTimeRange() [2/4]
tracktion_engine::EditTimeRange::EditTimeRange (const EditTimeRange &) default
EditTimeRange() [3/4]
tracktion_engine::EditTimeRange::EditTimeRange (double start, double end)
EditTimeRange() [4/4]
tracktion_engine::EditTimeRange::EditTimeRange (juce::Range< double > timeRange)
Member Function Documentation
operator=()
EditTimeRange& tracktion_engine::EditTimeRange::operator= (const EditTimeRange &) default
between()
static EditTimeRange tracktion_engine::EditTimeRange::between (double time1, double time2) static
Returns the range that lies between two positions (in either order).
withStartAndLength()
static EditTimeRange tracktion_engine::EditTimeRange::withStartAndLength (double time1, double length) static
Returns a range with a given start and length.
emptyRange()
static EditTimeRange tracktion_engine::EditTimeRange::emptyRange (double start) static
Returns a range with the specified start position and a length of zero.
getStart()
double tracktion_engine::EditTimeRange::getStart () const
References start.
Referenced by tracktion_engine::PluginAudioNode::createPluginRenderContext(), tracktion_engine::AudioNode::invokeSplitRender(), tracktion_engine::SubSampleWaveAudioNode::prepareForNextBlock(), tracktion_engine::PluginAudioNode::prepareForNextBlock(), tracktion_engine::PluginAudioNode::renderPlugin(), tracktion_engine::TimedMutingAudioNode::renderSection(), tracktion_engine::SubSampleWaveAudioNode::renderSection(), and tracktion_engine::SpeedRampAudioNode::renderSection().
getEnd()
double tracktion_engine::EditTimeRange::getEnd () const
References end.
Referenced by tracktion_engine::AudioNode::invokeSplitRender(), tracktion_engine::TimedMutingAudioNode::renderSection(), tracktion_engine::SubSampleWaveAudioNode::renderSection(), and tracktion_engine::SpeedRampAudioNode::renderSection().
getLength()
double tracktion_engine::EditTimeRange::getLength () const
References end, and start.
Referenced by tracktion_engine::ClipPosition::getLength(), tracktion_engine::AudioNode::invokeSplitRender(), tracktion_engine::PlayHead::linearTimeToLoopTime(), tracktion_engine::PlayHead::play(), and tracktion_engine::SpeedRampAudioNode::renderSection().
getCentre()
double tracktion_engine::EditTimeRange::getCentre () const
References end, and start.
clipValue()
double tracktion_engine::EditTimeRange::clipValue (double value) const
References end, and start.
Referenced by tracktion_engine::PlayHead::overridePosition().
isEmpty()
bool tracktion_engine::EditTimeRange::isEmpty () const
References end, and start.
Referenced by tracktion_engine::SpeedRampAudioNode::SpeedRampAudioNode().
operator==()
bool tracktion_engine::EditTimeRange::operator== (const EditTimeRange & other) const
References end, and start.
Referenced by operator!=().
operator!=()
bool tracktion_engine::EditTimeRange::operator!= (const EditTimeRange & other) const
References operator==().
overlaps()
bool tracktion_engine::EditTimeRange::overlaps (const EditTimeRange & other) const
References end, and start.
Referenced by tracktion_engine::TrackSection::merge(), and tracktion_engine::SpeedRampAudioNode::renderSection().
contains() [1/2]
bool tracktion_engine::EditTimeRange::contains (const EditTimeRange & other) const
References end, and start.
Referenced by tracktion_engine::TimedMutingAudioNode::renderSection().
contains() [2/2]
bool tracktion_engine::EditTimeRange::contains (double time) const
References end, and start.
containsInclusive()
bool tracktion_engine::EditTimeRange::containsInclusive (double time) const
References end, and start.
getUnionWith()
EditTimeRange tracktion_engine::EditTimeRange::getUnionWith (EditTimeRange other) const
Referenced by tracktion_engine::findUnionOfEditTimeRanges(), and tracktion_engine::TrackSection::merge().
getIntersectionWith()
EditTimeRange tracktion_engine::EditTimeRange::getIntersectionWith (EditTimeRange other) const
Referenced by tracktion_engine::SpeedRampAudioNode::renderSection().
rescaled()
EditTimeRange tracktion_engine::EditTimeRange::rescaled (double anchorTime, double factor) const
constrainRange()
EditTimeRange tracktion_engine::EditTimeRange::constrainRange (EditTimeRange rangeToConstrain) const
expanded()
EditTimeRange tracktion_engine::EditTimeRange::expanded (double amount) const
Referenced by tracktion_engine::TrackSection::merge().
reduced()
EditTimeRange tracktion_engine::EditTimeRange::reduced (double amount) const
movedToStartAt()
EditTimeRange tracktion_engine::EditTimeRange::movedToStartAt (double newStart) const
movedToEndAt()
EditTimeRange tracktion_engine::EditTimeRange::movedToEndAt (double newEnd) const
withStart()
EditTimeRange tracktion_engine::EditTimeRange::withStart (double newStart) const
withEnd()
EditTimeRange tracktion_engine::EditTimeRange::withEnd (double newEnd) const
withLength()
EditTimeRange tracktion_engine::EditTimeRange::withLength (double newLength) const
Referenced by tracktion_engine::AudioNode::invokeSplitRender(), and tracktion_engine::SpeedRampAudioNode::renderSection().
operator+()
EditTimeRange tracktion_engine::EditTimeRange::operator+ (double amount) const
Referenced by operator-().
operator-()
EditTimeRange tracktion_engine::EditTimeRange::operator- (double amount) const
References operator+().
Member Data Documentation
start
double tracktion_engine::EditTimeRange::start = 0
Referenced by clipValue(), contains(), containsInclusive(), tracktion_engine::PlayHead::deviceManagerPositionUpdate(), getCentre(), getLength(), getStart(), tracktion_engine::ClipPosition::getStart(), tracktion_engine::ClipPosition::getStartOfSource(), isEmpty(), tracktion_engine::PlayHead::linearTimeToLoopTime(), operator==(), overlaps(), tracktion_engine::PlayHead::play(), and tracktion_engine::PlayHead::streamTimeToEditWindow().
end
double tracktion_engine::EditTimeRange::end = 0
Referenced by clipValue(), contains(), containsInclusive(), getCentre(), getEnd(), tracktion_engine::ClipPosition::getEnd(), getLength(), isEmpty(), operator==(), overlaps(), tracktion_engine::PlayHead::overridePosition(), tracktion_engine::PlayHead::setRollInToLoop(), and tracktion_engine::PlayHead::streamTimeToEditWindow().
The documentation for this struct was generated from the following file:
tracktion_EditTimeRange.h