TracktionEngine: tracktion::engine::MidiMessageArray Struct Reference
tracktion::engine::MidiMessageArray Struct Reference
tracktion_graph » utilities
#include <tracktion_MidiMessageArray.h>
Public Types
using MidiMessageWithSource = tracktion::engine::MidiMessageWithSource
using MPESourceID = tracktion::engine::MPESourceID
Public Member Functions
bool isEmpty () const noexcept
bool isNotEmpty () const noexcept
int size () const noexcept
MidiMessageWithSource & operator[] (int i)
const MidiMessageWithSource & operator[] (int i) const
MidiMessageWithSource * begin () noexcept
const MidiMessageWithSource * begin () const noexcept
MidiMessageWithSource * end () noexcept
const MidiMessageWithSource * end () const noexcept
void remove (int index)
void swapWith (MidiMessageArray &other) noexcept
void clear () noexcept
void addMidiMessage (const juce::MidiMessage &m, MPESourceID mpeSourceID)
void addMidiMessage (juce::MidiMessage &&m, MPESourceID mpeSourceID)
void addMidiMessage (const juce::MidiMessage &m, double time, MPESourceID mpeSourceID)
void addMidiMessage (juce::MidiMessage &&m, double time, MPESourceID mpeSourceID)
void add (const MidiMessageWithSource &m)
void add (MidiMessageWithSource &&m)
void add (const MidiMessageWithSource &m, double time)
void add (MidiMessageWithSource &&m, double time)
void copyFrom (const MidiMessageArray &source)
void mergeFrom (const MidiMessageArray &source)
void mergeFromWithOffset (const MidiMessageArray &source, double delta)
void mergeFromAndClear (MidiMessageArray &source)
void mergeFromAndClearWithOffset (MidiMessageArray &source, double delta)
void mergeFromAndClearWithOffsetAndLimit (MidiMessageArray &source, double delta, int numItemsToTake)
void mergeFromAndClear (juce::Array< juce::MidiMessage > &source, MPESourceID mpeSourceID)
void removeNoteOnsAndOffs ()
template<typename Predicate >
void removeIf (Predicate &&pred)
Removes any notes that match the given predicate.
void addToTimestamps (double delta) noexcept
void addToNoteNumbers (int delta) noexcept
void multiplyVelocities (float factor) noexcept
void sortByTimestamp ()
void reserve (int size)
Static Public Member Functions
static tracktion::engine::MPESourceID createUniqueMPESourceID ()
Public Attributes
bool isAllNotesOff = false
Static Public Attributes
static constexpr tracktion::engine::MPESourceID notMPE = {}
Member Typedef Documentation
MidiMessageWithSource
using tracktion::engine::MidiMessageArray::MidiMessageWithSource = tracktion::engine::MidiMessageWithSource
MPESourceID
using tracktion::engine::MidiMessageArray::MPESourceID = tracktion::engine::MPESourceID
Member Function Documentation
isEmpty()
bool tracktion::engine::MidiMessageArray::isEmpty () const noexcept
Referenced by mergeFrom(), mergeFromAndClear(), mergeFromAndClearWithOffset(), and mergeFromWithOffset().
isNotEmpty()
bool tracktion::engine::MidiMessageArray::isNotEmpty () const noexcept
size()
int tracktion::engine::MidiMessageArray::size () const noexcept
Referenced by mergeFrom(), mergeFromAndClear(), mergeFromAndClearWithOffset(), mergeFromAndClearWithOffsetAndLimit(), and mergeFromWithOffset().
operator[]() [1/2]
MidiMessageWithSource & tracktion::engine::MidiMessageArray::operator[] (int i)
operator[]() [2/2]
const MidiMessageWithSource & tracktion::engine::MidiMessageArray::operator[] (int i) const
begin() [1/2]
MidiMessageWithSource * tracktion::engine::MidiMessageArray::begin () noexcept
begin() [2/2]
const MidiMessageWithSource * tracktion::engine::MidiMessageArray::begin () const noexcept
end() [1/2]
MidiMessageWithSource * tracktion::engine::MidiMessageArray::end () noexcept
end() [2/2]
const MidiMessageWithSource * tracktion::engine::MidiMessageArray::end () const noexcept
remove()
void tracktion::engine::MidiMessageArray::remove (int index)
swapWith()
void tracktion::engine::MidiMessageArray::swapWith (MidiMessageArray & other) noexcept
References isAllNotesOff.
Referenced by mergeFromAndClear(), and mergeFromAndClearWithOffset().
clear()
void tracktion::engine::MidiMessageArray::clear () noexcept
References isAllNotesOff.
Referenced by copyFrom(), mergeFromAndClear(), mergeFromAndClearWithOffset(), tracktion::engine::MultiThreadedNodePlayer::process(), and tracktion::engine::LevelMeasurerProcessingNode::process().
addMidiMessage() [1/4]
void tracktion::engine::MidiMessageArray::addMidiMessage (const juce::MidiMessage & m, MPESourceID mpeSourceID)
Referenced by tracktion::engine::MidiNodeHelpers::createMessagesForTime(), tracktion::engine::MidiNodeHelpers::createNoteOffs(), tracktion::engine::MidiNodeHelpers::createNoteOffs(), and mergeFromAndClear().
addMidiMessage() [2/4]
void tracktion::engine::MidiMessageArray::addMidiMessage (juce::MidiMessage && m, MPESourceID mpeSourceID)
addMidiMessage() [3/4]
void tracktion::engine::MidiMessageArray::addMidiMessage (const juce::MidiMessage & m, double time, MPESourceID mpeSourceID)
addMidiMessage() [4/4]
void tracktion::engine::MidiMessageArray::addMidiMessage (juce::MidiMessage && m, double time, MPESourceID mpeSourceID)
add() [1/4]
void tracktion::engine::MidiMessageArray::add (const MidiMessageWithSource & m)
add() [2/4]
void tracktion::engine::MidiMessageArray::add (MidiMessageWithSource && m)
add() [3/4]
void tracktion::engine::MidiMessageArray::add (const MidiMessageWithSource & m, double time)
add() [4/4]
void tracktion::engine::MidiMessageArray::add (MidiMessageWithSource && m, double time)
copyFrom()
void tracktion::engine::MidiMessageArray::copyFrom (const MidiMessageArray & source)
References clear(), and mergeFrom().
Referenced by tracktion::engine::InputProvider::setInputs().
mergeFrom()
void tracktion::engine::MidiMessageArray::mergeFrom (const MidiMessageArray & source)
References isAllNotesOff, isEmpty(), and size().
Referenced by copyFrom().
mergeFromWithOffset()
void tracktion::engine::MidiMessageArray::mergeFromWithOffset (const MidiMessageArray & source, double delta)
References isAllNotesOff, isEmpty(), and size().
mergeFromAndClear() [1/2]
void tracktion::engine::MidiMessageArray::mergeFromAndClear (MidiMessageArray & source)
References clear(), isAllNotesOff, isEmpty(), size(), and swapWith().
mergeFromAndClearWithOffset()
void tracktion::engine::MidiMessageArray::mergeFromAndClearWithOffset (MidiMessageArray & source, double delta)
References addToTimestamps(), clear(), isAllNotesOff, isEmpty(), size(), and swapWith().
Referenced by mergeFromAndClearWithOffsetAndLimit().
mergeFromAndClearWithOffsetAndLimit()
void tracktion::engine::MidiMessageArray::mergeFromAndClearWithOffsetAndLimit (MidiMessageArray & source, double delta, int numItemsToTake)
References isAllNotesOff, mergeFromAndClearWithOffset(), and size().
mergeFromAndClear() [2/2]
void tracktion::engine::MidiMessageArray::mergeFromAndClear (juce::Array< juce::MidiMessage > & source, MPESourceID mpeSourceID)
References addMidiMessage().
removeNoteOnsAndOffs()
void tracktion::engine::MidiMessageArray::removeNoteOnsAndOffs ()
removeIf()
template<typename Predicate > void tracktion::engine::MidiMessageArray::removeIf (Predicate && pred)
Removes any notes that match the given predicate.
addToTimestamps()
void tracktion::engine::MidiMessageArray::addToTimestamps (double delta) noexcept
Referenced by mergeFromAndClearWithOffset().
addToNoteNumbers()
void tracktion::engine::MidiMessageArray::addToNoteNumbers (int delta) noexcept
multiplyVelocities()
void tracktion::engine::MidiMessageArray::multiplyVelocities (float factor) noexcept
sortByTimestamp()
void tracktion::engine::MidiMessageArray::sortByTimestamp ()
reserve()
void tracktion::engine::MidiMessageArray::reserve (int size)
createUniqueMPESourceID()
static tracktion::engine::MPESourceID tracktion::engine::MidiMessageArray::createUniqueMPESourceID () static
Member Data Documentation
isAllNotesOff
bool tracktion::engine::MidiMessageArray::isAllNotesOff = false
Referenced by clear(), mergeFrom(), mergeFromAndClear(), mergeFromAndClearWithOffset(), mergeFromAndClearWithOffsetAndLimit(), mergeFromWithOffset(), and swapWith().
notMPE
constexpr tracktion::engine::MPESourceID tracktion::engine::MidiMessageArray::notMPE = {} static constexpr
The documentation for this struct was generated from the following file:
tracktion_MidiMessageArray.h