TracktionEngine: tracktion_engine::RecordingThumbnailManager::Thumbnail Struct Reference
tracktion_engine::RecordingThumbnailManager::Thumbnail Struct Reference
Inherits ReferenceCountedObject.
Public Types
using Ptr = juce::ReferenceCountedObjectPtr< Thumbnail >
Public Member Functions
~Thumbnail ()
void reset (int numChannels, double sampleRate)
void addBlock (const juce::AudioBuffer< float > &incoming, int startOffsetInBuffer, int numSamples)
Public Attributes
Engine & engine
TracktionThumbnail thumb
juce::File file
const HashCode hash
double punchInTime = 0
Member Typedef Documentation
Ptr
using tracktion_engine::RecordingThumbnailManager::Thumbnail::Ptr = juce::ReferenceCountedObjectPtr<Thumbnail>
Constructor & Destructor Documentation
~Thumbnail()
tracktion_engine::RecordingThumbnailManager::Thumbnail::~Thumbnail ()
References engine, and tracktion_engine::Engine::getRecordingThumbnailManager().
Member Function Documentation
reset()
void tracktion_engine::RecordingThumbnailManager::Thumbnail::reset (int numChannels, double sampleRate)
References tracktion_engine::TracktionThumbnail::reset(), and thumb.
addBlock()
void tracktion_engine::RecordingThumbnailManager::Thumbnail::addBlock (const juce::AudioBuffer< float > & incoming, int startOffsetInBuffer, int numSamples)
References tracktion_engine::TracktionThumbnail::addBlock(), and thumb.
Member Data Documentation
engine
Engine& tracktion_engine::RecordingThumbnailManager::Thumbnail::engine
Referenced by ~Thumbnail().
thumb
TracktionThumbnail tracktion_engine::RecordingThumbnailManager::Thumbnail::thumb
Referenced by addBlock(), and reset().
file
juce::File tracktion_engine::RecordingThumbnailManager::Thumbnail::file
hash
const HashCode tracktion_engine::RecordingThumbnailManager::Thumbnail::hash
punchInTime
double tracktion_engine::RecordingThumbnailManager::Thumbnail::punchInTime = 0
The documentation for this struct was generated from the following file:
tracktion_RecordingThumbnailManager.h