TracktionEngine: tracktion_engine::AutomationCurve::AutomationPoint Struct Reference
tracktion_engine::AutomationCurve::AutomationPoint Struct Reference
tracktion_engine » model
Public Member Functions
AutomationPoint () noexcept
AutomationPoint (double t, float v, float c) noexcept
juce::ValueTree toValueTree () const
bool operator< (const AutomationPoint &other) const
Public Attributes
double time = 0
float value = 0
float curve = 0
Constructor & Destructor Documentation
AutomationPoint() [1/2]
tracktion_engine::AutomationCurve::AutomationPoint::AutomationPoint () noexcept
AutomationPoint() [2/2]
tracktion_engine::AutomationCurve::AutomationPoint::AutomationPoint (double t, float v, float c) noexcept
References toValueTree().
Member Function Documentation
toValueTree()
juce::ValueTree tracktion_engine::AutomationCurve::AutomationPoint::toValueTree () const
Referenced by AutomationPoint().
operator<()
bool tracktion_engine::AutomationCurve::AutomationPoint::operator< (const AutomationPoint & other) const
References tracktion_engine::AutomationCurve::addPoint(), tracktion_engine::AutomationCurve::addToAllTimes(), tracktion_engine::AutomationCurve::addToValues(), tracktion_engine::AutomationCurve::clear(), tracktion_engine::AutomationCurve::countPointsInRegion(), curve, tracktion_engine::AutomationCurve::getBezierEnds(), tracktion_engine::AutomationCurve::getBezierHandle(), tracktion_engine::AutomationCurve::getBezierPoint(), tracktion_engine::AutomationCurve::getBezierXfromT(), tracktion_engine::AutomationCurve::getBezierYFromX(), tracktion_engine::AutomationCurve::getLength(), tracktion_engine::AutomationCurve::getNearestPoint(), tracktion_engine::AutomationCurve::getNumPoints(), tracktion_engine::AutomationCurve::getPoint(), tracktion_engine::AutomationCurve::getPointCurve(), tracktion_engine::AutomationCurve::getPointsInRegion(), tracktion_engine::AutomationCurve::getPointTime(), tracktion_engine::AutomationCurve::getPointValue(), tracktion_engine::AutomationCurve::getValueAt(), tracktion_engine::AutomationCurve::getValueLimits(), tracktion_engine::AutomationCurve::indexBefore(), tracktion_engine::AutomationCurve::mergeOtherCurve(), tracktion_engine::AutomationCurve::movePoint(), tracktion_engine::AutomationCurve::nextIndexAfter(), tracktion_engine::AutomationCurve::removeAllAutomationCurvesRecursively(), tracktion_engine::AutomationCurve::removePoint(), tracktion_engine::AutomationCurve::removePointsInRegion(), tracktion_engine::AutomationCurve::removeRedundantPoints(), tracktion_engine::AutomationCurve::removeRegionAndCloseGap(), tracktion_engine::AutomationCurve::rescaleAllTimes(), tracktion_engine::AutomationCurve::rescaleValues(), tracktion_engine::AutomationCurve::setCurveValue(), tracktion_engine::AutomationCurve::setPointTime(), tracktion_engine::AutomationCurve::setPointValue(), tracktion_engine::AutomationCurve::simplify(), time, and value.
Member Data Documentation
time
double tracktion_engine::AutomationCurve::AutomationPoint::time = 0
Referenced by operator<().
value
float tracktion_engine::AutomationCurve::AutomationPoint::value = 0
Referenced by operator<().
curve
float tracktion_engine::AutomationCurve::AutomationPoint::curve = 0
Referenced by operator<().
The documentation for this struct was generated from the following file:
tracktion_AutomationCurve.h