TracktionEngine: tracktion_engine::ValueTreeAllEventListener Struct Reference
tracktion_engine::ValueTreeAllEventListener Struct Reference abstract
Public Member Functions
virtual void valueTreeChanged ()=0
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeChildAdded (juce::ValueTree &, juce::ValueTree &) override
void valueTreeChildRemoved (juce::ValueTree &, juce::ValueTree &, int) override
void valueTreeChildOrderChanged (juce::ValueTree &, int, int) override
void valueTreeParentChanged (juce::ValueTree &) override
void valueTreeRedirected (juce::ValueTree &) override
Member Function Documentation
valueTreeChanged()
virtual void tracktion_engine::ValueTreeAllEventListener::valueTreeChanged () pure virtual
Implemented in tracktion_engine::PluginEffect, tracktion_engine::PitchShiftEffect, tracktion_engine::Plugin, tracktion_engine::VolumeEffect, and tracktion_engine::ClipEffect.
Referenced by valueTreeChildAdded(), valueTreeChildOrderChanged(), valueTreeChildRemoved(), valueTreeParentChanged(), valueTreePropertyChanged(), and valueTreeRedirected().
valueTreePropertyChanged()
void tracktion_engine::ValueTreeAllEventListener::valueTreePropertyChanged (juce::ValueTree & , const juce::Identifier &) override
References valueTreeChanged().
valueTreeChildAdded()
void tracktion_engine::ValueTreeAllEventListener::valueTreeChildAdded (juce::ValueTree & , juce::ValueTree &) override
References valueTreeChanged().
valueTreeChildRemoved()
void tracktion_engine::ValueTreeAllEventListener::valueTreeChildRemoved (juce::ValueTree & , juce::ValueTree & , int) override
References valueTreeChanged().
valueTreeChildOrderChanged()
void tracktion_engine::ValueTreeAllEventListener::valueTreeChildOrderChanged (juce::ValueTree & , int , int) override
References valueTreeChanged().
valueTreeParentChanged()
void tracktion_engine::ValueTreeAllEventListener::valueTreeParentChanged (juce::ValueTree &) override
References valueTreeChanged().
valueTreeRedirected()
void tracktion_engine::ValueTreeAllEventListener::valueTreeRedirected (juce::ValueTree &) override
References valueTreeChanged().
The documentation for this struct was generated from the following file:
tracktion_ValueTreeUtilities.h