TracktionEngine: tracktion::engine::ProjectManager::TempProject Struct Reference
tracktion::engine::ProjectManager::TempProject Struct Reference
Public Member Functions
TempProject (ProjectManager &pm, const juce::File &f, bool createNewProjectID)
Public Attributes
Project::Ptr project
Constructor & Destructor Documentation
TempProject()
tracktion::engine::ProjectManager::TempProject::TempProject (ProjectManager & pm, const juce::File & f, bool createNewProjectID)
References tracktion::engine::ProjectManager::createNewProject(), tracktion::engine::Project::createNewProjectId(), project, and tracktion::engine::Project::save().
Member Data Documentation
project
Project::Ptr tracktion::engine::ProjectManager::TempProject::project
Referenced by TempProject().
The documentation for this struct was generated from the following file:
tracktion_ProjectManager.h