TracktionEngine: tracktion::engine::ActiveNoteList Struct Reference
tracktion::engine::ActiveNoteList Struct Reference
tracktion_engine » midi
#include <tracktion_ActiveNoteList.h>
Public Member Functions
void reset () noexcept
bool isNoteActive (int channel, int note) const noexcept
void startNote (int channel, int note) noexcept
void clearNote (int channel, int note) noexcept
bool areAnyNotesActive () const noexcept
template<typename Visitor >
void iterate (Visitor &&v) const noexcept
Static Public Member Functions
static bool isValidIndex (int channel, int note) noexcept
Public Attributes
juce::uint16 activeChannels [128] = {}
Member Function Documentation
reset()
void tracktion::engine::ActiveNoteList::reset () noexcept
References activeChannels.
Referenced by tracktion::engine::MidiNodeHelpers::createNoteOffs().
isNoteActive()
bool tracktion::engine::ActiveNoteList::isNoteActive (int channel, int note) const noexcept
References activeChannels, and isValidIndex().
startNote()
void tracktion::engine::ActiveNoteList::startNote (int channel, int note) noexcept
References activeChannels, and isValidIndex().
clearNote()
void tracktion::engine::ActiveNoteList::clearNote (int channel, int note) noexcept
References activeChannels, and isValidIndex().
areAnyNotesActive()
bool tracktion::engine::ActiveNoteList::areAnyNotesActive () const noexcept
References activeChannels.
iterate()
template<typename Visitor > void tracktion::engine::ActiveNoteList::iterate (Visitor && v) const noexcept
References activeChannels.
Referenced by tracktion::engine::MidiNodeHelpers::createNoteOffs().
isValidIndex()
static bool tracktion::engine::ActiveNoteList::isValidIndex (int channel, int note) static noexcept
Referenced by clearNote(), isNoteActive(), and startNote().
Member Data Documentation
activeChannels
juce::uint16 tracktion::engine::ActiveNoteList::activeChannels[128] = {}
Referenced by areAnyNotesActive(), clearNote(), isNoteActive(), iterate(), reset(), and startNote().
The documentation for this struct was generated from the following file:
tracktion_ActiveNoteList.h