TracktionEngine: tracktion_engine::MidiMessageArray Struct Reference
tracktion_engine::MidiMessageArray Struct Reference
Classes
struct MidiMessageWithSource
Public Types
using MPESourceID = uint32_t
Public Member Functions
bool isEmpty () const noexcept
bool isNotEmpty () const noexcept
int size () const noexcept
MidiMessageWithSource & operator[] (int i)
const MidiMessageWithSource & operator[] (int i) const
MidiMessageWithSource * begin () noexcept
const MidiMessageWithSource * begin () const noexcept
MidiMessageWithSource * end () noexcept
const MidiMessageWithSource * end () const noexcept
void remove (int index)
void swapWith (MidiMessageArray &other) noexcept
void clear () noexcept
void addMidiMessage (const juce::MidiMessage &m, MPESourceID mpeSourceID)
void addMidiMessage (juce::MidiMessage &&m, MPESourceID mpeSourceID)
void addMidiMessage (const juce::MidiMessage &m, double time, MPESourceID mpeSourceID)
void addMidiMessage (juce::MidiMessage &&m, double time, MPESourceID mpeSourceID)
void add (const MidiMessageWithSource &m)
void add (MidiMessageWithSource &&m)
void add (const MidiMessageWithSource &m, double time)
void add (MidiMessageWithSource &&m, double time)
void copyFrom (const MidiMessageArray &source)
void mergeFrom (const MidiMessageArray &source)
void mergeFromWithOffset (const MidiMessageArray &source, double delta)
void mergeFromAndClear (MidiMessageArray &source)
void mergeFromAndClearWithOffset (MidiMessageArray &source, double delta)
void mergeFromAndClearWithOffsetAndLimit (MidiMessageArray &source, double delta, int numItemsToTake)
void mergeFromAndClear (juce::Array< juce::MidiMessage > &source, MPESourceID mpeSourceID)
void removeNoteOnsAndOffs ()
void addToTimestamps (double delta) noexcept
void addToNoteNumbers (int delta) noexcept
void multiplyVelocities (float factor) noexcept
void sortByTimestamp ()
void reserve (int size)
Static Public Member Functions
static MPESourceID createUniqueMPESourceID () noexcept
Public Attributes
bool isAllNotesOff = false
Static Public Attributes
static constexpr MPESourceID notMPE = 0
Member Typedef Documentation
MPESourceID
using tracktion_engine::MidiMessageArray::MPESourceID = uint32_t
Member Function Documentation
createUniqueMPESourceID()
static MPESourceID tracktion_engine::MidiMessageArray::createUniqueMPESourceID () static noexcept
isEmpty()
bool tracktion_engine::MidiMessageArray::isEmpty () const noexcept
Referenced by mergeFrom(), mergeFromAndClear(), mergeFromAndClearWithOffset(), and mergeFromWithOffset().
isNotEmpty()
bool tracktion_engine::MidiMessageArray::isNotEmpty () const noexcept
size()
int tracktion_engine::MidiMessageArray::size () const noexcept
Referenced by tracktion_graph::LatencyProcessor::clearMIDI(), tracktion_graph::Node::getAllocatedBytes(), mergeFrom(), mergeFromAndClear(), mergeFromAndClearWithOffset(), mergeFromAndClearWithOffsetAndLimit(), mergeFromWithOffset(), and tracktion_graph::LatencyProcessor::readMIDI().
operator[]() [1/2]
MidiMessageWithSource& tracktion_engine::MidiMessageArray::operator[] (int i)
operator[]() [2/2]
const MidiMessageWithSource& tracktion_engine::MidiMessageArray::operator[] (int i) const
begin() [1/2]
MidiMessageWithSource* tracktion_engine::MidiMessageArray::begin () noexcept
begin() [2/2]
const MidiMessageWithSource* tracktion_engine::MidiMessageArray::begin () const noexcept
end() [1/2]
MidiMessageWithSource* tracktion_engine::MidiMessageArray::end () noexcept
end() [2/2]
const MidiMessageWithSource* tracktion_engine::MidiMessageArray::end () const noexcept
remove()
void tracktion_engine::MidiMessageArray::remove (int index)
Referenced by tracktion_graph::LatencyProcessor::clearMIDI(), and tracktion_graph::LatencyProcessor::readMIDI().
swapWith()
void tracktion_engine::MidiMessageArray::swapWith (MidiMessageArray & other) noexcept
References isAllNotesOff.
Referenced by mergeFromAndClear(), mergeFromAndClearWithOffset(), tracktion_engine::LevelMeasurerProcessingNode::process(), and tracktion_graph::SendNode::process().
clear()
void tracktion_engine::MidiMessageArray::clear () noexcept
References isAllNotesOff.
Referenced by copyFrom(), tracktion_engine::LevelMeasurerProcessingNode::process(), tracktion_graph::LatencyNode::process(), tracktion_graph::SilentNode::process(), tracktion_graph::Node::process(), tracktion_graph::test_utilities::TestProcess< NodePlayerType >::process(), and tracktion_graph::ReturnNode::process().
addMidiMessage() [1/4]
void tracktion_engine::MidiMessageArray::addMidiMessage (const juce::MidiMessage & m, MPESourceID mpeSourceID)
Referenced by mergeFromAndClear(), and tracktion_graph::MidiNode::process().
addMidiMessage() [2/4]
void tracktion_engine::MidiMessageArray::addMidiMessage (juce::MidiMessage && m, MPESourceID mpeSourceID)
addMidiMessage() [3/4]
void tracktion_engine::MidiMessageArray::addMidiMessage (const juce::MidiMessage & m, double time, MPESourceID mpeSourceID)
addMidiMessage() [4/4]
void tracktion_engine::MidiMessageArray::addMidiMessage (juce::MidiMessage && m, double time, MPESourceID mpeSourceID)
add() [1/4]
void tracktion_engine::MidiMessageArray::add (const MidiMessageWithSource & m)
Referenced by tracktion_graph::LatencyProcessor::readMIDI().
add() [2/4]
void tracktion_engine::MidiMessageArray::add (MidiMessageWithSource && m)
add() [3/4]
void tracktion_engine::MidiMessageArray::add (const MidiMessageWithSource & m, double time)
add() [4/4]
void tracktion_engine::MidiMessageArray::add (MidiMessageWithSource && m, double time)
copyFrom()
void tracktion_engine::MidiMessageArray::copyFrom (const MidiMessageArray & source)
References clear(), and mergeFrom().
Referenced by tracktion_engine::PlayHeadPositionNode::process(), tracktion_engine::LevelMeasurerProcessingNode::process(), tracktion_graph::SendNode::process(), tracktion_graph::ReturnNode::process(), tracktion_graph::ForwardingNode::process(), and tracktion_engine::InputProvider::setInputs().
mergeFrom()
void tracktion_engine::MidiMessageArray::mergeFrom (const MidiMessageArray & source)
References isAllNotesOff, isEmpty(), and size().
Referenced by copyFrom(), tracktion_graph::SimpleNodePlayer::process(), tracktion_graph::BasicSummingNode::process(), tracktion_graph::GainNode::process(), tracktion_graph::ChannelRemappingNode::process(), and tracktion_graph::NodePlayer::processPostorderedNodesSingleThreaded().
mergeFromWithOffset()
void tracktion_engine::MidiMessageArray::mergeFromWithOffset (const MidiMessageArray & source, double delta)
References isAllNotesOff, isEmpty(), and size().
Referenced by tracktion_graph::LatencyProcessor::writeMIDI().
mergeFromAndClear() [1/2]
void tracktion_engine::MidiMessageArray::mergeFromAndClear (MidiMessageArray & source)
References isAllNotesOff, isEmpty(), size(), and swapWith().
mergeFromAndClearWithOffset()
void tracktion_engine::MidiMessageArray::mergeFromAndClearWithOffset (MidiMessageArray & source, double delta)
References addToTimestamps(), isAllNotesOff, isEmpty(), size(), and swapWith().
Referenced by mergeFromAndClearWithOffsetAndLimit().
mergeFromAndClearWithOffsetAndLimit()
void tracktion_engine::MidiMessageArray::mergeFromAndClearWithOffsetAndLimit (MidiMessageArray & source, double delta, int numItemsToTake)
References isAllNotesOff, mergeFromAndClearWithOffset(), and size().
mergeFromAndClear() [2/2]
void tracktion_engine::MidiMessageArray::mergeFromAndClear (juce::Array< juce::MidiMessage > & source, MPESourceID mpeSourceID)
References addMidiMessage().
removeNoteOnsAndOffs()
void tracktion_engine::MidiMessageArray::removeNoteOnsAndOffs ()
addToTimestamps()
void tracktion_engine::MidiMessageArray::addToTimestamps (double delta) noexcept
Referenced by tracktion_graph::LatencyProcessor::clearMIDI(), mergeFromAndClearWithOffset(), and tracktion_graph::LatencyProcessor::readMIDI().
addToNoteNumbers()
void tracktion_engine::MidiMessageArray::addToNoteNumbers (int delta) noexcept
multiplyVelocities()
void tracktion_engine::MidiMessageArray::multiplyVelocities (float factor) noexcept
sortByTimestamp()
void tracktion_engine::MidiMessageArray::sortByTimestamp ()
reserve()
void tracktion_engine::MidiMessageArray::reserve (int size)
Member Data Documentation
notMPE
constexpr MPESourceID tracktion_engine::MidiMessageArray::notMPE = 0 static constexpr
Referenced by tracktion_graph::MidiNode::process().
isAllNotesOff
bool tracktion_engine::MidiMessageArray::isAllNotesOff = false
Referenced by clear(), mergeFrom(), mergeFromAndClear(), mergeFromAndClearWithOffset(), mergeFromAndClearWithOffsetAndLimit(), mergeFromWithOffset(), and swapWith().
The documentation for this struct was generated from the following file:
tracktion_MidiMessageArray.h