TracktionEngine: tracktion::engine::ValueTreeAllEventListener Struct Reference
tracktion::engine::ValueTreeAllEventListener Struct Reference abstract
tracktion_engine » utilities
#include <tracktion_ValueTreeUtilities.h>
Public Member Functions
virtual void valueTreeChanged ()=0
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeChildAdded (juce::ValueTree &, juce::ValueTree &) override
void valueTreeChildRemoved (juce::ValueTree &, juce::ValueTree &, int) override
void valueTreeChildOrderChanged (juce::ValueTree &, int, int) override
void valueTreeParentChanged (juce::ValueTree &) override
void valueTreeRedirected (juce::ValueTree &) override
Member Function Documentation
valueTreeChanged()
virtual void tracktion::engine::ValueTreeAllEventListener::valueTreeChanged () pure virtual
Implemented in tracktion::engine::ClipEffect, tracktion::engine::VolumeEffect, tracktion::engine::PitchShiftEffect, tracktion::engine::PluginEffect, and tracktion::engine::Plugin.
Referenced by valueTreeChildAdded(), valueTreeChildOrderChanged(), valueTreeChildRemoved(), valueTreeParentChanged(), valueTreePropertyChanged(), and valueTreeRedirected().
valueTreePropertyChanged()
void tracktion::engine::ValueTreeAllEventListener::valueTreePropertyChanged (juce::ValueTree & , const juce::Identifier &) override
References valueTreeChanged().
valueTreeChildAdded()
void tracktion::engine::ValueTreeAllEventListener::valueTreeChildAdded (juce::ValueTree & , juce::ValueTree &) override
References valueTreeChanged().
valueTreeChildRemoved()
void tracktion::engine::ValueTreeAllEventListener::valueTreeChildRemoved (juce::ValueTree & , juce::ValueTree & , int) override
References valueTreeChanged().
valueTreeChildOrderChanged()
void tracktion::engine::ValueTreeAllEventListener::valueTreeChildOrderChanged (juce::ValueTree & , int , int) override
References valueTreeChanged().
valueTreeParentChanged()
void tracktion::engine::ValueTreeAllEventListener::valueTreeParentChanged (juce::ValueTree &) override
References valueTreeChanged().
valueTreeRedirected()
void tracktion::engine::ValueTreeAllEventListener::valueTreeRedirected (juce::ValueTree &) override
References valueTreeChanged().
The documentation for this struct was generated from the following file:
tracktion_ValueTreeUtilities.h