TracktionEngine: tracktion_graph::LatencyProcessor Struct Reference
tracktion_graph::LatencyProcessor Struct Reference
Public Member Functions
LatencyProcessor ()=default
bool hasSameConfigurationAs (const LatencyProcessor &o) const
Returns ture if the the sample rate, channels etc.
bool hasConfiguration (int numLatencySamples, double preparedSampleRate, int numberOfChannels) const
Returns ture if the the sample rate, channels etc.
int getLatencyNumSamples () const
void setLatencyNumSamples (int numLatencySamples)
void prepareToPlay (double sampleRateToUse, int blockSize, int numChannels)
void writeAudio (choc::buffer::ChannelArrayView< float > src)
void writeMIDI (const tracktion_engine::MidiMessageArray &src)
void readAudioAdding (choc::buffer::ChannelArrayView< float > dst)
void readAudioOverwriting (choc::buffer::ChannelArrayView< float > dst)
void readMIDI (tracktion_engine::MidiMessageArray &dst, int numSamples)
void clearAudio (int numSamples)
void clearMIDI (int numSamples)
Constructor & Destructor Documentation
LatencyProcessor()
tracktion_graph::LatencyProcessor::LatencyProcessor () default
Member Function Documentation
hasSameConfigurationAs()
bool tracktion_graph::LatencyProcessor::hasSameConfigurationAs (const LatencyProcessor & o) const
Returns ture if the the sample rate, channels etc.
are the same between the two objects.
References tracktion_graph::AudioFifo::getNumChannels().
hasConfiguration()
bool tracktion_graph::LatencyProcessor::hasConfiguration (int numLatencySamples, double preparedSampleRate, int numberOfChannels) const
Returns ture if the the sample rate, channels etc.
are those specified.
References tracktion_graph::AudioFifo::getNumChannels().
getLatencyNumSamples()
int tracktion_graph::LatencyProcessor::getLatencyNumSamples () const
setLatencyNumSamples()
void tracktion_graph::LatencyProcessor::setLatencyNumSamples (int numLatencySamples)
prepareToPlay()
void tracktion_graph::LatencyProcessor::prepareToPlay (double sampleRateToUse, int blockSize, int numChannels)
References tracktion_graph::AudioFifo::getNumReady(), tracktion_graph::sampleToTime(), tracktion_graph::AudioFifo::setSize(), and tracktion_graph::AudioFifo::writeSilence().
writeAudio()
void tracktion_graph::LatencyProcessor::writeAudio (choc::buffer::ChannelArrayView< float > src)
References tracktion_graph::AudioFifo::getNumChannels(), and tracktion_graph::AudioFifo::write().
writeMIDI()
void tracktion_graph::LatencyProcessor::writeMIDI (const tracktion_engine::MidiMessageArray & src)
References tracktion_engine::MidiMessageArray::mergeFromWithOffset().
readAudioAdding()
void tracktion_graph::LatencyProcessor::readAudioAdding (choc::buffer::ChannelArrayView< float > dst)
References tracktion_graph::AudioFifo::getNumChannels(), tracktion_graph::AudioFifo::getNumReady(), and tracktion_graph::AudioFifo::readAdding().
readAudioOverwriting()
void tracktion_graph::LatencyProcessor::readAudioOverwriting (choc::buffer::ChannelArrayView< float > dst)
References tracktion_graph::AudioFifo::getNumChannels(), tracktion_graph::AudioFifo::getNumReady(), and tracktion_graph::AudioFifo::readOverwriting().
readMIDI()
void tracktion_graph::LatencyProcessor::readMIDI (tracktion_engine::MidiMessageArray & dst, int numSamples)
References tracktion_engine::MidiMessageArray::add(), tracktion_engine::MidiMessageArray::addToTimestamps(), tracktion_engine::MidiMessageArray::remove(), tracktion_graph::sampleToTime(), and tracktion_engine::MidiMessageArray::size().
clearAudio()
void tracktion_graph::LatencyProcessor::clearAudio (int numSamples)
References tracktion_graph::AudioFifo::removeSamples().
clearMIDI()
void tracktion_graph::LatencyProcessor::clearMIDI (int numSamples)
References tracktion_engine::MidiMessageArray::addToTimestamps(), tracktion_engine::MidiMessageArray::remove(), tracktion_graph::sampleToTime(), and tracktion_engine::MidiMessageArray::size().
The documentation for this struct was generated from the following file:
tracktion_graph_LatencyProcessor.h