TracktionEngine: tracktion::graph::test_utilities::TestProcess< NodePlayerType > Struct Template Reference
tracktion::graph::test_utilities::TestProcess< NodePlayerType > Struct Template Reference
Public Member Functions
TestProcess (std::unique_ptr< NodePlayerType > playerToUse, TestSetup ts, const int numChannelsToUse, const double duration, bool writeToBuffer)
std::string getDescription () const
Returns a description of the number of channels and length of rendering.
PerformanceMeasurement::Statistics getStatisticsAndReset ()
Node & getNode () const
NodePlayerType & getNodePlayer () const
void setNode (std::unique_ptr< Node > newNode)
void setPlayer (std::unique_ptr< NodePlayerType > newPlayerToUse)
void setPlayHead (tracktion::graph::PlayHead *newPlayHead)
bool process (int maxNumSamples)
Processes a number of samples.
std::shared_ptr< TestContext > processAll ()
std::shared_ptr< TestContext > getTestResult ()
Constructor & Destructor Documentation
TestProcess()
template<typename NodePlayerType > tracktion::graph::test_utilities::TestProcess< NodePlayerType >::TestProcess (std::unique_ptr< NodePlayerType > playerToUse, TestSetup ts, const int numChannelsToUse, const double duration, bool writeToBuffer)
References tracktion::graph::test_utilities::TestSetup::blockSize, tracktion::graph::test_utilities::TestSetup::sampleRate, and tracktion::graph::test_utilities::TestProcess< NodePlayerType >::setPlayer().
Member Function Documentation
getDescription()
template<typename NodePlayerType > std::string tracktion::graph::test_utilities::TestProcess< NodePlayerType >::getDescription () const
Returns a description of the number of channels and length of rendering.
Referenced by tracktion::engine::benchmark_utilities::prepareRenderAndDestroy().
getStatisticsAndReset()
template<typename NodePlayerType > PerformanceMeasurement::Statistics tracktion::graph::test_utilities::TestProcess< NodePlayerType >::getStatisticsAndReset ()
References tracktion::graph::PerformanceMeasurement::getStatisticsAndReset().
Referenced by tracktion::engine::benchmark_utilities::prepareRenderAndDestroy().
getNode()
template<typename NodePlayerType > Node& tracktion::graph::test_utilities::TestProcess< NodePlayerType >::getNode () const
Referenced by tracktion::engine::benchmark_utilities::prepareRenderAndDestroy().
getNodePlayer()
template<typename NodePlayerType > NodePlayerType& tracktion::graph::test_utilities::TestProcess< NodePlayerType >::getNodePlayer () const
Referenced by tracktion::engine::benchmark_utilities::prepareRenderAndDestroy(), and tracktion::engine::benchmark_utilities::renderEdit().
setNode()
template<typename NodePlayerType > void tracktion::graph::test_utilities::TestProcess< NodePlayerType >::setNode (std::unique_ptr< Node > newNode)
setPlayer()
template<typename NodePlayerType > void tracktion::graph::test_utilities::TestProcess< NodePlayerType >::setPlayer (std::unique_ptr< NodePlayerType > newPlayerToUse)
References tracktion::graph::test_utilities::TestSetup::blockSize, and tracktion::graph::test_utilities::TestSetup::sampleRate.
Referenced by tracktion::graph::test_utilities::TestProcess< NodePlayerType >::TestProcess().
setPlayHead()
template<typename NodePlayerType > void tracktion::graph::test_utilities::TestProcess< NodePlayerType >::setPlayHead (tracktion::graph::PlayHead * newPlayHead)
Referenced by tracktion::engine::benchmark_utilities::prepareRenderAndDestroy().
process()
template<typename NodePlayerType > bool tracktion::graph::test_utilities::TestProcess< NodePlayerType >::process (int maxNumSamples)
Processes a number of samples.
Returns true if there is still more processing to be done.
References tracktion::graph::test_utilities::TestSetup::blockSize, tracktion::graph::test_utilities::TestSetup::random, tracktion::graph::test_utilities::TestSetup::randomiseBlockSizes, tracktion::graph::test_utilities::TestSetup::sampleRate, tracktion::graph::PlayHead::setReferenceSampleRange(), and tracktion::graph::toAudioBuffer().
Referenced by tracktion::graph::test_utilities::TestProcess< NodePlayerType >::processAll().
processAll()
template<typename NodePlayerType > std::shared_ptr<TestContext> tracktion::graph::test_utilities::TestProcess< NodePlayerType >::processAll ()
References tracktion::graph::test_utilities::TestProcess< NodePlayerType >::getTestResult(), and tracktion::graph::test_utilities::TestProcess< NodePlayerType >::process().
Referenced by tracktion::engine::benchmark_utilities::prepareRenderAndDestroy().
getTestResult()
template<typename NodePlayerType > std::shared_ptr<TestContext> tracktion::graph::test_utilities::TestProcess< NodePlayerType >::getTestResult ()
Referenced by tracktion::graph::test_utilities::TestProcess< NodePlayerType >::processAll().
The documentation for this struct was generated from the following file:
tracktion_graph/tracktion_graph/tracktion_TestUtilities.h