TracktionEngine: tracktion::engine::PluginScanHelpers::PluginScanMasterProcess Struct Reference
tracktion::engine::PluginScanHelpers::PluginScanMasterProcess Struct Reference
Inherits juce::ChildProcessCoordinator.
Public Member Functions
PluginScanMasterProcess (Engine &e)
bool ensureChildProcessLaunched ()
bool sendScanRequest (juce::AudioPluginFormat &format, const juce::String &fileOrIdentifier, int requestID)
bool waitForReply (int requestID, const juce::String &fileOrIdentifier, juce::OwnedArray< juce::PluginDescription > &result, CustomScanner &scanner)
void handleMessage (const juce::XmlElement &xml)
void handleConnectionLost () override
Public Attributes
volatile bool launched = false
volatile bool crashed = false
Constructor & Destructor Documentation
PluginScanMasterProcess()
tracktion::engine::PluginScanHelpers::PluginScanMasterProcess::PluginScanMasterProcess (Engine & e)
Member Function Documentation
ensureChildProcessLaunched()
bool tracktion::engine::PluginScanHelpers::PluginScanMasterProcess::ensureChildProcessLaunched ()
References tracktion::engine::PluginScanHelpers::commandLineUID, crashed, and launched.
sendScanRequest()
bool tracktion::engine::PluginScanHelpers::PluginScanMasterProcess::sendScanRequest (juce::AudioPluginFormat & format, const juce::String & fileOrIdentifier, int requestID)
References tracktion::engine::PluginScanHelpers::createScanMessage().
waitForReply()
bool tracktion::engine::PluginScanHelpers::PluginScanMasterProcess::waitForReply (int requestID, const juce::String & fileOrIdentifier, juce::OwnedArray< juce::PluginDescription > & result, CustomScanner & scanner)
References crashed, launched, tracktion::engine::PluginScanHelpers::CustomScanner::shouldAbortScan(), and tracktion::engine::AppFunctions::start().
handleMessage()
void tracktion::engine::PluginScanHelpers::PluginScanMasterProcess::handleMessage (const juce::XmlElement & xml)
handleConnectionLost()
void tracktion::engine::PluginScanHelpers::PluginScanMasterProcess::handleConnectionLost () override
References crashed.
Member Data Documentation
launched
volatile bool tracktion::engine::PluginScanHelpers::PluginScanMasterProcess::launched = false
Referenced by ensureChildProcessLaunched(), and waitForReply().
crashed
volatile bool tracktion::engine::PluginScanHelpers::PluginScanMasterProcess::crashed = false
Referenced by ensureChildProcessLaunched(), handleConnectionLost(), and waitForReply().
The documentation for this struct was generated from the following file:
tracktion_PluginScanHelpers.h