TracktionEngine: tracktion_engine::AudioFileUtils Struct Reference
tracktion_engine::AudioFileUtils Struct Reference
Classes
class EnvelopeFollower
Static Public Member Functions
static juce::AudioFormatReader * createReaderFor (Engine &, const juce::File &)
static juce::AudioFormatReader * createReaderFindingFormat (Engine &, const juce::File &, juce::AudioFormat *&)
static juce::MemoryMappedAudioFormatReader * createMemoryMappedReader (Engine &, const juce::File &, juce::AudioFormat *&)
static juce::AudioFormatWriter * createWriterFor (Engine &, const juce::File &, double sampleRate, unsigned int numChannels, int bitsPerSample, const juce::StringPairArray &metadata, int quality)
static juce::AudioFormatWriter * createWriterFor (juce::AudioFormat *, const juce::File &, double sampleRate, unsigned int numChannels, int bitsPerSample, const juce::StringPairArray &metadata, int quality)
static juce::Range< juce::int64 > scanForNonZeroSamples (Engine &, const juce::File &, float maxZeroLevelDb)
static juce::Range< juce::int64 > copyNonSilentSectionToNewFile (Engine &e, const juce::File &sourceFile, const juce::File &destFile, float maxZeroLevelDb)
static juce::Range< juce::int64 > trimSilence (Engine &e, const juce::File &, float maxZeroLevelDb)
static bool reverse (Engine &, const juce::File &source, const juce::File &destination, std::atomic< float > &progress, juce::ThreadPoolJob *job=nullptr, bool canCreateWavIntermediate=true)
Reverses a file updating a progress value and checking the exit status of a given job.
static juce::int64 copySectionToNewFile (Engine &e, const juce::File &sourceFile, const juce::File &destFile, const juce::Range< juce::int64 > &range)
static juce::int64 copySectionToNewFile (Engine &e, const juce::File &sourceFile, const juce::File &destFile, EditTimeRange range)
static void addBWAVStartToMetadata (juce::StringPairArray &metadata, juce::int64 time)
static void applyBWAVStartTime (const juce::File &, juce::int64 time)
static juce::int64 getFileLengthSamples (Engine &e, const juce::File &)
template<class TargetFormat >
static bool convertToFormat (Engine &e, const juce::File &sourceFile, juce::OutputStream &destStream, int quality, const juce::StringPairArray &metadata)
template<class TargetFormat >
static bool convertToFormat (juce::AudioFormatReader *reader, juce::OutputStream &destStream, int quality, const juce::StringPairArray &metadata)
template<typename SourceFormat >
static bool readFromFormat (Engine &engine, juce::InputStream &source, const juce::File &dest)
Member Function Documentation
createReaderFor()
static juce::AudioFormatReader* tracktion_engine::AudioFileUtils::createReaderFor (Engine & , const juce::File &) static
Referenced by convertToFormat().
createReaderFindingFormat()
static juce::AudioFormatReader* tracktion_engine::AudioFileUtils::createReaderFindingFormat (Engine & , const juce::File & , juce::AudioFormat *&) static
createMemoryMappedReader()
static juce::MemoryMappedAudioFormatReader* tracktion_engine::AudioFileUtils::createMemoryMappedReader (Engine & , const juce::File & , juce::AudioFormat *&) static
createWriterFor() [1/2]
static juce::AudioFormatWriter* tracktion_engine::AudioFileUtils::createWriterFor (Engine & , const juce::File & , double sampleRate, unsigned int numChannels, int bitsPerSample, const juce::StringPairArray & metadata, int quality) static
createWriterFor() [2/2]
static juce::AudioFormatWriter* tracktion_engine::AudioFileUtils::createWriterFor (juce::AudioFormat * , const juce::File & , double sampleRate, unsigned int numChannels, int bitsPerSample, const juce::StringPairArray & metadata, int quality) static
scanForNonZeroSamples()
static juce::Range<juce::int64> tracktion_engine::AudioFileUtils::scanForNonZeroSamples (Engine & , const juce::File & , float maxZeroLevelDb) static
copyNonSilentSectionToNewFile()
static juce::Range<juce::int64> tracktion_engine::AudioFileUtils::copyNonSilentSectionToNewFile (Engine & e, const juce::File & sourceFile, const juce::File & destFile, float maxZeroLevelDb) static
trimSilence()
static juce::Range<juce::int64> tracktion_engine::AudioFileUtils::trimSilence (Engine & e, const juce::File & , float maxZeroLevelDb) static
reverse()
static bool tracktion_engine::AudioFileUtils::reverse (Engine & , const juce::File & source, const juce::File & destination, std::atomic< float > & progress, juce::ThreadPoolJob * job = nullptr, bool canCreateWavIntermediate = true) static
Reverses a file updating a progress value and checking the exit status of a given job.
Referenced by tracktion_engine::ReverseRenderJob::renderNextBlock().
copySectionToNewFile() [1/2]
static juce::int64 tracktion_engine::AudioFileUtils::copySectionToNewFile (Engine & e, const juce::File & sourceFile, const juce::File & destFile, const juce::Range< juce::int64 > & range) static
copySectionToNewFile() [2/2]
static juce::int64 tracktion_engine::AudioFileUtils::copySectionToNewFile (Engine & e, const juce::File & sourceFile, const juce::File & destFile, EditTimeRange range) static
addBWAVStartToMetadata()
static void tracktion_engine::AudioFileUtils::addBWAVStartToMetadata (juce::StringPairArray & metadata, juce::int64 time) static
applyBWAVStartTime()
static void tracktion_engine::AudioFileUtils::applyBWAVStartTime (const juce::File & , juce::int64 time) static
getFileLengthSamples()
static juce::int64 tracktion_engine::AudioFileUtils::getFileLengthSamples (Engine & e, const juce::File &) static
convertToFormat() [1/2]
template<class TargetFormat > static bool tracktion_engine::AudioFileUtils::convertToFormat (Engine & e, const juce::File & sourceFile, juce::OutputStream & destStream, int quality, const juce::StringPairArray & metadata) static
References createReaderFor(), and tracktion_engine::quality.
convertToFormat() [2/2]
template<class TargetFormat > static bool tracktion_engine::AudioFileUtils::convertToFormat (juce::AudioFormatReader * reader, juce::OutputStream & destStream, int quality, const juce::StringPairArray & metadata) static
References tracktion_engine::quality.
readFromFormat()
template<typename SourceFormat > static bool tracktion_engine::AudioFileUtils::readFromFormat (Engine & engine, juce::InputStream & source, const juce::File & dest) static
References tracktion_engine::Engine::getAudioFileFormatManager(), tracktion_engine::AudioFileWriter::isOpen(), tracktion_engine::AudioFileFormatManager::writeFormatManager, and tracktion_engine::AudioFileWriter::writeFromAudioReader().
The documentation for this struct was generated from the following file:
tracktion_AudioFileUtils.h