TracktionEngine: tracktion::engine::legacy::EditTimeRange Struct Reference
tracktion::engine::legacy::EditTimeRange Struct Reference
Public Member Functions
EditTimeRange ()=default
EditTimeRange (const EditTimeRange &)=default
EditTimeRange & operator= (const EditTimeRange &)=default
EditTimeRange (double start, double end)
EditTimeRange (juce::Range< double > timeRange)
double getStart () const
double getEnd () const
double getLength () const
double getCentre () const
double clipValue (double value) const
bool isEmpty () const
bool operator== (const EditTimeRange &other) const
bool operator!= (const EditTimeRange &other) const
bool overlaps (const EditTimeRange &other) const
bool contains (const EditTimeRange &other) const
bool contains (double time) const
bool containsInclusive (double time) const
EditTimeRange getUnionWith (EditTimeRange other) const
EditTimeRange getIntersectionWith (EditTimeRange other) const
EditTimeRange rescaled (double anchorTime, double factor) const
EditTimeRange constrainRange (EditTimeRange rangeToConstrain) const
EditTimeRange expanded (double amount) const
EditTimeRange reduced (double amount) const
EditTimeRange movedToStartAt (double newStart) const
EditTimeRange movedToEndAt (double newEnd) const
EditTimeRange withStart (double newStart) const
EditTimeRange withEnd (double newEnd) const
EditTimeRange withLength (double newLength) const
EditTimeRange operator+ (double amount) const
EditTimeRange operator- (double amount) const
Static Public Member Functions
static EditTimeRange between (double time1, double time2)
Returns the range that lies between two positions (in either order).
static EditTimeRange withStartAndLength (double time1, double length)
Returns a range with a given start and length.
static EditTimeRange emptyRange (double start)
Returns a range with the specified start position and a length of zero.
Public Attributes
double start = 0
double end = 0
Constructor & Destructor Documentation
EditTimeRange() [1/4]
tracktion::engine::legacy::EditTimeRange::EditTimeRange () default
Referenced by between(), and emptyRange().
EditTimeRange() [2/4]
tracktion::engine::legacy::EditTimeRange::EditTimeRange (const EditTimeRange &) default
EditTimeRange() [3/4]
tracktion::engine::legacy::EditTimeRange::EditTimeRange (double start, double end)
EditTimeRange() [4/4]
tracktion::engine::legacy::EditTimeRange::EditTimeRange (juce::Range< double > timeRange)
Member Function Documentation
operator=()
EditTimeRange& tracktion::engine::legacy::EditTimeRange::operator= (const EditTimeRange &) default
between()
EditTimeRange tracktion::engine::legacy::EditTimeRange::between (double time1, double time2) static
Returns the range that lies between two positions (in either order).
References EditTimeRange().
withStartAndLength()
EditTimeRange tracktion::engine::legacy::EditTimeRange::withStartAndLength (double time1, double length) static
Returns a range with a given start and length.
emptyRange()
EditTimeRange tracktion::engine::legacy::EditTimeRange::emptyRange (double start) static
Returns a range with the specified start position and a length of zero.
References EditTimeRange(), and start.
getStart()
double tracktion::engine::legacy::EditTimeRange::getStart () const
References start.
Referenced by constrainRange(), tracktion::engine::PluginAudioNode::createPluginRenderContext(), tracktion::engine::AudioNode::invokeSplitRender(), tracktion::engine::SubSampleWaveAudioNode::prepareForNextBlock(), tracktion::engine::PluginAudioNode::prepareForNextBlock(), tracktion::engine::PluginAudioNode::renderPlugin(), tracktion::engine::TimedMutingAudioNode::renderSection(), tracktion::engine::SubSampleWaveAudioNode::renderSection(), tracktion::engine::SpeedRampAudioNode::renderSection(), tracktion::engine::toEditTimeRange(), and tracktion::engine::toTimeRange().
getEnd()
double tracktion::engine::legacy::EditTimeRange::getEnd () const
References end.
Referenced by tracktion::engine::AudioNode::invokeSplitRender(), tracktion::engine::TimedMutingAudioNode::renderSection(), tracktion::engine::SubSampleWaveAudioNode::renderSection(), tracktion::engine::SpeedRampAudioNode::renderSection(), and tracktion::engine::toTimeRange().
getLength()
double tracktion::engine::legacy::EditTimeRange::getLength () const
References end, and start.
Referenced by constrainRange(), tracktion::engine::AudioNode::invokeSplitRender(), tracktion::engine::PlayHead::linearTimeToLoopTime(), tracktion::engine::PlayHead::play(), reduced(), and tracktion::engine::SpeedRampAudioNode::renderSection().
getCentre()
double tracktion::engine::legacy::EditTimeRange::getCentre () const
References end, and start.
clipValue()
double tracktion::engine::legacy::EditTimeRange::clipValue (double value) const
References end, and start.
Referenced by tracktion::engine::PlayHead::overridePosition().
isEmpty()
bool tracktion::engine::legacy::EditTimeRange::isEmpty () const
References end, and start.
Referenced by tracktion::engine::SpeedRampAudioNode::SpeedRampAudioNode().
operator==()
bool tracktion::engine::legacy::EditTimeRange::operator== (const EditTimeRange & other) const
References end, and start.
Referenced by operator!=().
operator!=()
bool tracktion::engine::legacy::EditTimeRange::operator!= (const EditTimeRange & other) const
References operator==().
overlaps()
bool tracktion::engine::legacy::EditTimeRange::overlaps (const EditTimeRange & other) const
References end, and start.
Referenced by tracktion::engine::SpeedRampAudioNode::renderSection().
contains() [1/2]
bool tracktion::engine::legacy::EditTimeRange::contains (const EditTimeRange & other) const
References end, and start.
Referenced by tracktion::engine::TimedMutingAudioNode::renderSection().
contains() [2/2]
bool tracktion::engine::legacy::EditTimeRange::contains (double time) const
References end, and start.
containsInclusive()
bool tracktion::engine::legacy::EditTimeRange::containsInclusive (double time) const
References end, and start.
getUnionWith()
EditTimeRange tracktion::engine::legacy::EditTimeRange::getUnionWith (EditTimeRange other) const
References end, and start.
getIntersectionWith()
EditTimeRange tracktion::engine::legacy::EditTimeRange::getIntersectionWith (EditTimeRange other) const
References end, and start.
Referenced by tracktion::engine::SpeedRampAudioNode::renderSection().
rescaled()
EditTimeRange tracktion::engine::legacy::EditTimeRange::rescaled (double anchorTime, double factor) const
References end, and start.
constrainRange()
EditTimeRange tracktion::engine::legacy::EditTimeRange::constrainRange (EditTimeRange rangeToConstrain) const
References end, getLength(), getStart(), movedToStartAt(), and start.
expanded()
EditTimeRange tracktion::engine::legacy::EditTimeRange::expanded (double amount) const
References end, and start.
reduced()
EditTimeRange tracktion::engine::legacy::EditTimeRange::reduced (double amount) const
References end, getLength(), and start.
movedToStartAt()
EditTimeRange tracktion::engine::legacy::EditTimeRange::movedToStartAt (double newStart) const
References end, and start.
Referenced by constrainRange().
movedToEndAt()
EditTimeRange tracktion::engine::legacy::EditTimeRange::movedToEndAt (double newEnd) const
References end, and start.
withStart()
EditTimeRange tracktion::engine::legacy::EditTimeRange::withStart (double newStart) const
References end.
withEnd()
EditTimeRange tracktion::engine::legacy::EditTimeRange::withEnd (double newEnd) const
References start.
withLength()
EditTimeRange tracktion::engine::legacy::EditTimeRange::withLength (double newLength) const
References start.
Referenced by tracktion::engine::AudioNode::invokeSplitRender(), and tracktion::engine::SpeedRampAudioNode::renderSection().
operator+()
EditTimeRange tracktion::engine::legacy::EditTimeRange::operator+ (double amount) const
References end, and start.
Referenced by operator-().
operator-()
EditTimeRange tracktion::engine::legacy::EditTimeRange::operator- (double amount) const
References operator+().
Member Data Documentation
start
double tracktion::engine::legacy::EditTimeRange::start = 0
Referenced by clipValue(), constrainRange(), contains(), containsInclusive(), tracktion::engine::PlayHead::deviceManagerPositionUpdate(), emptyRange(), expanded(), getCentre(), getIntersectionWith(), getLength(), getStart(), getUnionWith(), isEmpty(), tracktion::engine::PlayHead::linearTimeToLoopTime(), movedToEndAt(), movedToStartAt(), operator+(), operator==(), overlaps(), tracktion::engine::PlayHead::play(), reduced(), rescaled(), tracktion::engine::PlayHead::streamTimeToEditWindow(), withEnd(), and withLength().
end
double tracktion::engine::legacy::EditTimeRange::end = 0
Referenced by clipValue(), constrainRange(), contains(), containsInclusive(), expanded(), getCentre(), getEnd(), getIntersectionWith(), getLength(), getUnionWith(), isEmpty(), movedToEndAt(), movedToStartAt(), operator+(), operator==(), overlaps(), tracktion::engine::PlayHead::overridePosition(), reduced(), rescaled(), tracktion::engine::PlayHead::setRollInToLoop(), tracktion::engine::PlayHead::streamTimeToEditWindow(), and withStart().
The documentation for this struct was generated from the following file:
tracktion_EditTimeRange.h