TracktionEngine: tracktion_engine::VolumeEffect Struct Reference
tracktion_engine::VolumeEffect Struct Reference
tracktion_engine » model
Public Member Functions
VolumeEffect (const juce::ValueTree &, ClipEffects &)
juce::ReferenceCountedObjectPtr< ClipEffectRenderJob > createRenderJob (const AudioFile &sourceFile, double sourceLength) override
Subclasses should return a job that can render the source.
void initialise () override
bool hasProperties () override
Return true here to show a properties button in the editor and enable the propertiesButtonPressed callback.
void propertiesButtonPressed (SelectionManager &) override
juce::int64 getIndividualHash () const override
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeChanged () override
void timerCallback () override
Public Member Functions inherited from tracktion_engine::ClipEffect
ClipEffect (const juce::ValueTree &, ClipEffects &)
EffectType getType () const
virtual void sourceChanged ()
Callback to indicate the destination file has changed.
juce::int64 getHash () const
Returns the hash for this effect.
AudioFile getSourceFile () const
AudioFile getDestinationFile () const
bool isUsingFile (const AudioFile &) const
virtual void flushStateToValueTree ()
juce::UndoManager & getUndoManager ()
AudioClipBase & getClip ()
Public Attributes
VolumeAndPanPlugin::Ptr plugin
std::unique_ptr< ClipEffects::RenderInhibitor > inhibitor
Public Attributes inherited from tracktion_engine::ClipEffect
Edit & edit
juce::ValueTree state
ClipEffects & clipEffects
Additional Inherited Members
Public Types inherited from tracktion_engine::ClipEffect
enum EffectType {
EffectType::none, EffectType::volume, EffectType::fadeInOut, EffectType::tapeStartStop,
EffectType::stepVolume, EffectType::pitchShift, EffectType::warpTime, EffectType::normalise,
EffectType::makeMono, EffectType::reverse, EffectType::invert, EffectType::filter,
EffectType::firstEffect = volume, EffectType::lastEffect = filter
}
Static Public Member Functions inherited from tracktion_engine::ClipEffect
static juce::ValueTree create (EffectType)
static ClipEffect * create (const juce::ValueTree &, ClipEffects &)
static void createEffectAndAddToValueTree (Edit &, juce::ValueTree parent, ClipEffect::EffectType, int index)
static juce::String getTypeDisplayName (EffectType)
static void addEffectsToMenu (juce::PopupMenu &)
Protected Member Functions inherited from tracktion_engine::ValueTreeAllEventListener
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeChildAdded (juce::ValueTree &, juce::ValueTree &) override
void valueTreeChildRemoved (juce::ValueTree &, juce::ValueTree &, int) override
void valueTreeChildOrderChanged (juce::ValueTree &, int, int) override
void valueTreeParentChanged (juce::ValueTree &) override
void valueTreeRedirected (juce::ValueTree &) override
Constructor & Destructor Documentation
VolumeEffect()
tracktion_engine::VolumeEffect::VolumeEffect (const juce::ValueTree & , ClipEffects &)
Member Function Documentation
createRenderJob()
juce::ReferenceCountedObjectPtr<ClipEffectRenderJob> tracktion_engine::VolumeEffect::createRenderJob (const AudioFile & sourceFile, double sourceLength) override virtual
Subclasses should return a job that can render the source.
N.B. because the sourceFile may not be valid at the time of job creation you should use the sourceLength parameter to determine how to build the render node.
Implements tracktion_engine::ClipEffect.
initialise()
void tracktion_engine::VolumeEffect::initialise () override virtual
Reimplemented from tracktion_engine::ClipEffect.
References tracktion_engine::ClipEffect::getIndividualHash(), tracktion_engine::ClipEffect::hasProperties(), tracktion_engine::ClipEffect::propertiesButtonPressed(), tracktion_engine::ClipEffect::valueTreeChanged(), and tracktion_engine::ValueTreeAllEventListener::valueTreePropertyChanged().
hasProperties()
bool tracktion_engine::VolumeEffect::hasProperties () override virtual
Return true here to show a properties button in the editor and enable the propertiesButtonPressed callback.
Reimplemented from tracktion_engine::ClipEffect.
propertiesButtonPressed()
void tracktion_engine::VolumeEffect::propertiesButtonPressed (SelectionManager &) override virtual
Reimplemented from tracktion_engine::ClipEffect.
getIndividualHash()
juce::int64 tracktion_engine::VolumeEffect::getIndividualHash () const override virtual
Reimplemented from tracktion_engine::ClipEffect.
valueTreePropertyChanged()
void tracktion_engine::VolumeEffect::valueTreePropertyChanged (juce::ValueTree & , const juce::Identifier &) override
valueTreeChanged()
void tracktion_engine::VolumeEffect::valueTreeChanged () override virtual
Reimplemented from tracktion_engine::ClipEffect.
timerCallback()
void tracktion_engine::VolumeEffect::timerCallback () override
Member Data Documentation
plugin
VolumeAndPanPlugin::Ptr tracktion_engine::VolumeEffect::plugin
inhibitor
std::unique_ptr<ClipEffects::RenderInhibitor> tracktion_engine::VolumeEffect::inhibitor
The documentation for this struct was generated from the following file:
tracktion_ClipEffects.h