TracktionEngine: tracktion_graph::test_utilities::TestProcess< NodePlayerType > Struct Template Reference
tracktion_graph::test_utilities::TestProcess< NodePlayerType > Struct Template Reference
Public Member Functions
TestProcess (std::unique_ptr< NodePlayerType > playerToUse, TestSetup ts, const int numChannelsToUse, const double duration, bool writeToBuffer)
std::string getDescription () const
Returns a description of the number of channels and length of rendering.
PerformanceMeasurement::Statistics getStatisticsAndReset ()
Node & getNode () const
NodePlayerType & getNodePlayer () const
void setNode (std::unique_ptr< Node > newNode)
void setPlayer (std::unique_ptr< NodePlayerType > newPlayerToUse)
void setPlayHead (tracktion_graph::PlayHead *newPlayHead)
bool process (int maxNumSamples)
Processes a number of samples.
std::shared_ptr< TestContext > processAll ()
std::shared_ptr< TestContext > getTestResult ()
Constructor & Destructor Documentation
TestProcess()
template<typename NodePlayerType > tracktion_graph::test_utilities::TestProcess< NodePlayerType >::TestProcess (std::unique_ptr< NodePlayerType > playerToUse, TestSetup ts, const int numChannelsToUse, const double duration, bool writeToBuffer)
References tracktion_graph::test_utilities::TestSetup::blockSize, tracktion_graph::test_utilities::TestSetup::sampleRate, and tracktion_graph::test_utilities::TestProcess< NodePlayerType >::setPlayer().
Member Function Documentation
getDescription()
template<typename NodePlayerType > std::string tracktion_graph::test_utilities::TestProcess< NodePlayerType >::getDescription () const
Returns a description of the number of channels and length of rendering.
Referenced by tracktion_engine::benchmark_utilities::prepareRenderAndDestroy().
getStatisticsAndReset()
template<typename NodePlayerType > PerformanceMeasurement::Statistics tracktion_graph::test_utilities::TestProcess< NodePlayerType >::getStatisticsAndReset ()
References tracktion_graph::PerformanceMeasurement::getStatisticsAndReset().
Referenced by tracktion_engine::benchmark_utilities::prepareRenderAndDestroy().
getNode()
template<typename NodePlayerType > Node& tracktion_graph::test_utilities::TestProcess< NodePlayerType >::getNode () const
Referenced by tracktion_engine::benchmark_utilities::prepareRenderAndDestroy().
getNodePlayer()
template<typename NodePlayerType > NodePlayerType& tracktion_graph::test_utilities::TestProcess< NodePlayerType >::getNodePlayer () const
Referenced by tracktion_engine::benchmark_utilities::prepareRenderAndDestroy(), and tracktion_engine::benchmark_utilities::renderEdit().
setNode()
template<typename NodePlayerType > void tracktion_graph::test_utilities::TestProcess< NodePlayerType >::setNode (std::unique_ptr< Node > newNode)
setPlayer()
template<typename NodePlayerType > void tracktion_graph::test_utilities::TestProcess< NodePlayerType >::setPlayer (std::unique_ptr< NodePlayerType > newPlayerToUse)
References tracktion_graph::test_utilities::TestSetup::blockSize, and tracktion_graph::test_utilities::TestSetup::sampleRate.
Referenced by tracktion_graph::test_utilities::TestProcess< NodePlayerType >::TestProcess().
setPlayHead()
template<typename NodePlayerType > void tracktion_graph::test_utilities::TestProcess< NodePlayerType >::setPlayHead (tracktion_graph::PlayHead * newPlayHead)
Referenced by tracktion_engine::benchmark_utilities::prepareRenderAndDestroy().
process()
template<typename NodePlayerType > bool tracktion_graph::test_utilities::TestProcess< NodePlayerType >::process (int maxNumSamples)
Processes a number of samples.
Returns true if there is still more processing to be done.
References tracktion_graph::test_utilities::TestSetup::blockSize, tracktion_engine::MidiMessageArray::clear(), tracktion_graph::test_utilities::TestSetup::random, tracktion_graph::test_utilities::TestSetup::randomiseBlockSizes, tracktion_graph::test_utilities::TestSetup::sampleRate, tracktion_graph::PlayHead::setReferenceSampleRange(), and tracktion_graph::toAudioBuffer().
Referenced by tracktion_graph::test_utilities::TestProcess< NodePlayerType >::processAll().
processAll()
template<typename NodePlayerType > std::shared_ptr<TestContext> tracktion_graph::test_utilities::TestProcess< NodePlayerType >::processAll ()
References tracktion_graph::test_utilities::TestProcess< NodePlayerType >::getTestResult(), and tracktion_graph::test_utilities::TestProcess< NodePlayerType >::process().
Referenced by tracktion_engine::benchmark_utilities::prepareRenderAndDestroy().
getTestResult()
template<typename NodePlayerType > std::shared_ptr<TestContext> tracktion_graph::test_utilities::TestProcess< NodePlayerType >::getTestResult ()
Referenced by tracktion_graph::test_utilities::TestProcess< NodePlayerType >::processAll().
The documentation for this struct was generated from the following file:
tracktion_graph_TestUtilities.h