TracktionEngine: tracktion_engine::ProjectManager::TempProject Struct Reference
tracktion_engine::ProjectManager::TempProject Struct Reference
Public Member Functions
TempProject (ProjectManager &pm, const juce::File &f, bool createNewProjectID)
Public Attributes
Project::Ptr project
Constructor & Destructor Documentation
TempProject()
tracktion_engine::ProjectManager::TempProject::TempProject (ProjectManager & pm, const juce::File & f, bool createNewProjectID)
References tracktion_engine::ProjectManager::createNewProject(), tracktion_engine::Project::createNewProjectId(), project, and tracktion_engine::Project::save().
Member Data Documentation
project
Project::Ptr tracktion_engine::ProjectManager::TempProject::project
Referenced by TempProject().
The documentation for this struct was generated from the following file:
tracktion_ProjectManager.h