TracktionEngine: tracktion_engine::AsyncFunctionCaller Struct Reference
tracktion_engine::AsyncFunctionCaller Struct Reference
Holds a list of function objects and enables you to call them asyncronously.
Inherits AsyncUpdater.
Public Member Functions
AsyncFunctionCaller ()=default
Creates an empty AsyncFunctionCaller.
~AsyncFunctionCaller () override
Destructor.
void addFunction (int functionID, const std::function< void()> &f)
Adds a function and associates a functionID with it.
void updateAsync (int functionID)
Triggers an asyncronous call to one of the functions.
void handleAsyncUpdate () override
Public Attributes
std::map< int, std::pair< bool, std::function< void(void)> > > functions
Detailed Description
Holds a list of function objects and enables you to call them asyncronously.
Constructor & Destructor Documentation
AsyncFunctionCaller()
tracktion_engine::AsyncFunctionCaller::AsyncFunctionCaller () default
Creates an empty AsyncFunctionCaller.
~AsyncFunctionCaller()
tracktion_engine::AsyncFunctionCaller::~AsyncFunctionCaller () override
Destructor.
Member Function Documentation
addFunction()
void tracktion_engine::AsyncFunctionCaller::addFunction (int functionID, const std::function< void()> & f)
Adds a function and associates a functionID with it.
References functions.
updateAsync()
void tracktion_engine::AsyncFunctionCaller::updateAsync (int functionID)
Triggers an asyncronous call to one of the functions.
References functions.
handleAsyncUpdate()
void tracktion_engine::AsyncFunctionCaller::handleAsyncUpdate () override
.
References functions.
Member Data Documentation
functions
std::map<int, std::pair<bool, std::function<void (void)> > > tracktion_engine::AsyncFunctionCaller::functions
Referenced by addFunction(), handleAsyncUpdate(), and updateAsync().
The documentation for this struct was generated from the following file:
tracktion_AsyncFunctionUtils.h