TracktionEngine: tracktion_engine::LoopInfo::LoopPoint Struct Reference
tracktion_engine::LoopInfo::LoopPoint Struct Reference
tracktion_engine » audio_files
Public Member Functions
bool isAutomatic () const
Public Attributes
juce::int64 pos = 0
LoopPointType type = LoopPointType::manual
Member Function Documentation
isAutomatic()
bool tracktion_engine::LoopInfo::LoopPoint::isAutomatic () const
References tracktion_engine::LoopInfo::addLoopPoint(), tracktion_engine::LoopInfo::addTag(), tracktion_engine::LoopInfo::addTags(), tracktion_engine::LoopInfo::automatic, tracktion_engine::LoopInfo::changeLoopPoint(), tracktion_engine::LoopInfo::clearLoopPoints(), tracktion_engine::LoopInfo::clearTags(), tracktion_engine::LoopInfo::deleteLoopPoint(), tracktion_engine::LoopInfo::getLoopPoint(), tracktion_engine::LoopInfo::getNumLoopPoints(), tracktion_engine::LoopInfo::getNumTags(), and tracktion_engine::LoopInfo::getTag().
Member Data Documentation
pos
juce::int64 tracktion_engine::LoopInfo::LoopPoint::pos = 0
type
LoopPointType tracktion_engine::LoopInfo::LoopPoint::type = LoopPointType::manual
The documentation for this struct was generated from the following file:
tracktion_LoopInfo.h