TracktionEngine: tracktion_engine::TrackSection Struct Reference
tracktion_engine::TrackSection Struct Reference
Defines a time raneg sectin of a Track.
Public Member Functions
bool merge (const TrackItem &c)
Merges an overlapping TrackItem track/time range with this section.
Static Public Member Functions
template<typename TrackItemArray >
static juce::Array< TrackSection > findSections (const TrackItemArray &trackItems)
Returns a set of TrackSections for the given TrackItems.
Public Attributes
Track * track = nullptr
The Track this section refers to.
EditTimeRange range
The time range this section refers to.
Detailed Description
Defines a time raneg sectin of a Track.
Member Function Documentation
merge()
bool tracktion_engine::TrackSection::merge (const TrackItem & c)
Merges an overlapping TrackItem track/time range with this section.
Returns
true if this item was from the same track and overlapping time range and could be merged. false if it didn't intersect and should be its own section.
References tracktion_engine::EditTimeRange::expanded(), tracktion_engine::TrackItem::getEditTimeRange(), tracktion_engine::TrackItem::getTrack(), tracktion_engine::EditTimeRange::getUnionWith(), tracktion_engine::EditTimeRange::overlaps(), range, and track.
findSections()
template<typename TrackItemArray > static juce::Array<TrackSection> tracktion_engine::TrackSection::findSections (const TrackItemArray & trackItems) static
Returns a set of TrackSections for the given TrackItems.
References range, and track.
Member Data Documentation
track
Track* tracktion_engine::TrackSection::track = nullptr
The Track this section refers to.
Referenced by findSections(), and merge().
range
EditTimeRange tracktion_engine::TrackSection::range
The time range this section refers to.
Referenced by findSections(), and merge().
The documentation for this struct was generated from the following file:
tracktion_TrackUtils.h