TracktionEngine: tracktion_engine::ActiveNoteList Struct Reference
tracktion_engine::ActiveNoteList Struct Reference
Public Member Functions
void reset () noexcept
bool isNoteActive (int channel, int note) const noexcept
void startNote (int channel, int note) noexcept
void clearNote (int channel, int note) noexcept
template<typename Visitor >
void iterate (Visitor &&v) const noexcept
Static Public Member Functions
static bool isValidIndex (int channel, int note) noexcept
Public Attributes
juce::uint16 activeChannels [128] = {}
Member Function Documentation
reset()
void tracktion_engine::ActiveNoteList::reset () noexcept
References activeChannels.
isNoteActive()
bool tracktion_engine::ActiveNoteList::isNoteActive (int channel, int note) const noexcept
References activeChannels, isValidIndex(), and tracktion_engine::ModifierCommon::note.
startNote()
void tracktion_engine::ActiveNoteList::startNote (int channel, int note) noexcept
References activeChannels, isValidIndex(), and tracktion_engine::ModifierCommon::note.
clearNote()
void tracktion_engine::ActiveNoteList::clearNote (int channel, int note) noexcept
References activeChannels, isValidIndex(), and tracktion_engine::ModifierCommon::note.
iterate()
template<typename Visitor > void tracktion_engine::ActiveNoteList::iterate (Visitor && v) const noexcept
References activeChannels, and tracktion_engine::ModifierCommon::note.
isValidIndex()
static bool tracktion_engine::ActiveNoteList::isValidIndex (int channel, int note) static noexcept
References tracktion_engine::ModifierCommon::note.
Referenced by clearNote(), isNoteActive(), and startNote().
Member Data Documentation
activeChannels
juce::uint16 tracktion_engine::ActiveNoteList::activeChannels[128] = {}
Referenced by clearNote(), isNoteActive(), iterate(), reset(), and startNote().
The documentation for this struct was generated from the following file:
tracktion_ActiveNoteList.h