TracktionEngine: tracktion::graph::LatencyProcessor Struct Reference
tracktion::graph::LatencyProcessor Struct Reference
tracktion_graph » utilities
#include <tracktion_LatencyProcessor.h>
Public Member Functions
LatencyProcessor ()=default
bool hasSameConfigurationAs (const LatencyProcessor &o) const
Returns ture if the the sample rate, channels etc.
bool hasConfiguration (int numLatencySamples, double preparedSampleRate, int numberOfChannels) const
Returns ture if the the sample rate, channels etc.
int getLatencyNumSamples () const
void setLatencyNumSamples (int numLatencySamples)
void prepareToPlay (double sampleRateToUse, int blockSize, int numChannels)
void writeAudio (choc::buffer::ChannelArrayView< float > src)
void writeMIDI (const tracktion_engine::MidiMessageArray &src)
void readAudioAdding (choc::buffer::ChannelArrayView< float > dst)
void readAudioOverwriting (choc::buffer::ChannelArrayView< float > dst)
void readMIDI (tracktion_engine::MidiMessageArray &dst, int numSamples)
void clearAudio (int numSamples)
void clearMIDI (int numSamples)
Constructor & Destructor Documentation
LatencyProcessor()
tracktion::graph::LatencyProcessor::LatencyProcessor () default
Member Function Documentation
hasSameConfigurationAs()
bool tracktion::graph::LatencyProcessor::hasSameConfigurationAs (const LatencyProcessor & o) const
Returns ture if the the sample rate, channels etc.
are the same between the two objects.
References tracktion::graph::AudioFifo::getNumChannels().
hasConfiguration()
bool tracktion::graph::LatencyProcessor::hasConfiguration (int numLatencySamples, double preparedSampleRate, int numberOfChannels) const
Returns ture if the the sample rate, channels etc.
are those specified.
References tracktion::graph::AudioFifo::getNumChannels().
getLatencyNumSamples()
int tracktion::graph::LatencyProcessor::getLatencyNumSamples () const
setLatencyNumSamples()
void tracktion::graph::LatencyProcessor::setLatencyNumSamples (int numLatencySamples)
prepareToPlay()
void tracktion::graph::LatencyProcessor::prepareToPlay (double sampleRateToUse, int blockSize, int numChannels)
References tracktion::graph::AudioFifo::getNumReady(), tracktion::graph::sampleToTime(), tracktion::graph::AudioFifo::setSize(), and tracktion::graph::AudioFifo::writeSilence().
writeAudio()
void tracktion::graph::LatencyProcessor::writeAudio (choc::buffer::ChannelArrayView< float > src)
References tracktion::graph::AudioFifo::getNumChannels(), and tracktion::graph::AudioFifo::write().
writeMIDI()
void tracktion::graph::LatencyProcessor::writeMIDI (const tracktion_engine::MidiMessageArray & src)
readAudioAdding()
void tracktion::graph::LatencyProcessor::readAudioAdding (choc::buffer::ChannelArrayView< float > dst)
References tracktion::graph::AudioFifo::getNumChannels(), tracktion::graph::AudioFifo::getNumReady(), and tracktion::graph::AudioFifo::readAdding().
readAudioOverwriting()
void tracktion::graph::LatencyProcessor::readAudioOverwriting (choc::buffer::ChannelArrayView< float > dst)
References tracktion::graph::AudioFifo::getNumChannels(), tracktion::graph::AudioFifo::getNumReady(), and tracktion::graph::AudioFifo::readOverwriting().
readMIDI()
void tracktion::graph::LatencyProcessor::readMIDI (tracktion_engine::MidiMessageArray & dst, int numSamples)
References tracktion::graph::sampleToTime().
clearAudio()
void tracktion::graph::LatencyProcessor::clearAudio (int numSamples)
References tracktion::graph::AudioFifo::removeSamples().
clearMIDI()
void tracktion::graph::LatencyProcessor::clearMIDI (int numSamples)
References tracktion::graph::sampleToTime().
The documentation for this struct was generated from the following file:
tracktion_LatencyProcessor.h