TracktionEngine: tracktion::engine::RecordingThumbnailManager::Thumbnail Struct Reference
tracktion::engine::RecordingThumbnailManager::Thumbnail Struct Reference
Inherits juce::ReferenceCountedObject.
Public Types
using Ptr = juce::ReferenceCountedObjectPtr< Thumbnail >
Public Member Functions
~Thumbnail ()
void reset (int numChannels, double sampleRate)
void addBlock (const juce::AudioBuffer< float > &incoming, int startOffsetInBuffer, int numSamples)
Public Attributes
Engine & engine
TracktionThumbnail thumb
juce::File file
const HashCode hash
TimePosition punchInTime
Member Typedef Documentation
Ptr
using tracktion::engine::RecordingThumbnailManager::Thumbnail::Ptr = juce::ReferenceCountedObjectPtr<Thumbnail>
Constructor & Destructor Documentation
~Thumbnail()
tracktion::engine::RecordingThumbnailManager::Thumbnail::~Thumbnail ()
References engine, and tracktion::engine::Engine::getRecordingThumbnailManager().
Member Function Documentation
reset()
void tracktion::engine::RecordingThumbnailManager::Thumbnail::reset (int numChannels, double sampleRate)
References tracktion::engine::TracktionThumbnail::reset(), and thumb.
addBlock()
void tracktion::engine::RecordingThumbnailManager::Thumbnail::addBlock (const juce::AudioBuffer< float > & incoming, int startOffsetInBuffer, int numSamples)
References tracktion::engine::TracktionThumbnail::addBlock(), and thumb.
Member Data Documentation
engine
Engine& tracktion::engine::RecordingThumbnailManager::Thumbnail::engine
Referenced by ~Thumbnail().
thumb
TracktionThumbnail tracktion::engine::RecordingThumbnailManager::Thumbnail::thumb
Referenced by addBlock(), and reset().
file
juce::File tracktion::engine::RecordingThumbnailManager::Thumbnail::file
hash
const HashCode tracktion::engine::RecordingThumbnailManager::Thumbnail::hash
punchInTime
TimePosition tracktion::engine::RecordingThumbnailManager::Thumbnail::punchInTime
The documentation for this struct was generated from the following file:
tracktion_RecordingThumbnailManager.h