TracktionEngine: tracktion::engine::ClipEffects::Listener Struct Reference
tracktion::engine::ClipEffects::Listener Struct Reference
Public Member Functions
virtual ~Listener ()
virtual void effectChanged ()
virtual void effectAdded (ClipEffect *)
virtual void effectRemoved (ClipEffect *)
virtual void effectsReordered ()
virtual void renderComplete ()
Constructor & Destructor Documentation
~Listener()
virtual tracktion::engine::ClipEffects::Listener::~Listener () virtual
Member Function Documentation
effectChanged()
virtual void tracktion::engine::ClipEffects::Listener::effectChanged () virtual
effectAdded()
virtual void tracktion::engine::ClipEffects::Listener::effectAdded (ClipEffect *) virtual
Referenced by tracktion::engine::ClipEffects::createNewObject().
effectRemoved()
virtual void tracktion::engine::ClipEffects::Listener::effectRemoved (ClipEffect *) virtual
Referenced by tracktion::engine::ClipEffects::deleteObject().
effectsReordered()
virtual void tracktion::engine::ClipEffects::Listener::effectsReordered () virtual
Referenced by tracktion::engine::ClipEffects::objectOrderChanged().
renderComplete()
virtual void tracktion::engine::ClipEffects::Listener::renderComplete () virtual
Referenced by tracktion::engine::ClipEffects::notifyListenersOfRenderCompletion().
The documentation for this struct was generated from the following file:
tracktion_ClipEffects.h