TracktionEngine: tracktion::engine::PluginScanHelpers::PluginScanChildProcess Struct Reference
tracktion::engine::PluginScanHelpers::PluginScanChildProcess Struct Reference
Inherits juce::ChildProcessWorker, and juce::AsyncUpdater.
Public Member Functions
PluginScanChildProcess ()
void handleConnectionMade () override
void handleConnectionLost () override
void handleScanMessage (int requestID, const juce::String &formatName, const juce::String &fileOrIdentifier)
void handleMessage (const juce::XmlElement &xml)
Constructor & Destructor Documentation
PluginScanChildProcess()
tracktion::engine::PluginScanHelpers::PluginScanChildProcess::PluginScanChildProcess ()
Member Function Documentation
handleConnectionMade()
void tracktion::engine::PluginScanHelpers::PluginScanChildProcess::handleConnectionMade () override
handleConnectionLost()
void tracktion::engine::PluginScanHelpers::PluginScanChildProcess::handleConnectionLost () override
handleScanMessage()
void tracktion::engine::PluginScanHelpers::PluginScanChildProcess::handleScanMessage (int requestID, const juce::String & formatName, const juce::String & fileOrIdentifier)
References tracktion::engine::PluginScanHelpers::createScanMessage().
Referenced by handleMessage().
handleMessage()
void tracktion::engine::PluginScanHelpers::PluginScanChildProcess::handleMessage (const juce::XmlElement & xml)
References handleScanMessage().
The documentation for this struct was generated from the following file:
tracktion_PluginScanHelpers.h