TracktionEngine: tracktion::engine::Pitch Struct Reference
tracktion::engine::Pitch Struct Reference
Static Public Member Functions
static juce::String getPitchAsString (Engine &engine, int pitch)
static juce::StringArray getPitchAsStrings (Engine &engine, int pitch)
static int getPitchFromString (Engine &engine, const juce::String &str)
static juce::StringArray getPitchStrings (Engine &engine, bool separateSharpFlat)
static float semitonesToRatio (float semitonesUp) noexcept
Member Function Documentation
getPitchAsString()
static juce::String tracktion::engine::Pitch::getPitchAsString (Engine & engine, int pitch) static
References tracktion::engine::Engine::getEngineBehaviour(), and tracktion::engine::EngineBehaviour::getMiddleCOctave().
Referenced by getPitchStrings().
getPitchAsStrings()
static juce::StringArray tracktion::engine::Pitch::getPitchAsStrings (Engine & engine, int pitch) static
References tracktion::engine::Engine::getEngineBehaviour(), and tracktion::engine::EngineBehaviour::getMiddleCOctave().
Referenced by getPitchFromString(), and getPitchStrings().
getPitchFromString()
static int tracktion::engine::Pitch::getPitchFromString (Engine & engine, const juce::String & str) static
References getPitchAsStrings().
getPitchStrings()
static juce::StringArray tracktion::engine::Pitch::getPitchStrings (Engine & engine, bool separateSharpFlat) static
References getPitchAsString(), and getPitchAsStrings().
semitonesToRatio()
static float tracktion::engine::Pitch::semitonesToRatio (float semitonesUp) static noexcept
The documentation for this struct was generated from the following file:
tracktion_Pitch.h