TracktionEngine: tracktion::engine::InputDeviceInstance::DestinationList Struct Reference
tracktion::engine::InputDeviceInstance::DestinationList Struct Reference
tracktion_engine » playback
#include <tracktion_InputDevice.h>
Public Member Functions
DestinationList (InputDeviceInstance &i, const juce::ValueTree &v)
~DestinationList () override
bool isSuitableType (const juce::ValueTree &v) const override
Destination * createNewObject (const juce::ValueTree &v) override
void deleteObject (Destination *c) override
void newObjectAdded (Destination *) override
void objectRemoved (Destination *) override
void objectOrderChanged () override
Public Member Functions inherited from tracktion::engine::ValueTreeObjectList< Destination >
ValueTreeObjectList (const juce::ValueTree &parentTree)
~ValueTreeObjectList () override
int size () const
bool isEmpty () const noexcept
Destination * operator[] (int idx) const
Destination * at (int idx)
Destination ** begin ()
Destination *const * begin () const
Destination ** end ()
Destination *const * end () const
void rebuildObjects ()
void freeObjects ()
virtual void deleteObject (Destination *)=0
virtual void newObjectAdded (Destination *)=0
virtual void objectRemoved (Destination *)=0
void valueTreeChildAdded (juce::ValueTree &, juce::ValueTree &tree) override
void valueTreeChildRemoved (juce::ValueTree &exParent, juce::ValueTree &tree, int) override
void valueTreeChildOrderChanged (juce::ValueTree &tree, int, int) override
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeParentChanged (juce::ValueTree &) override
void valueTreeRedirected (juce::ValueTree &) override
int compareElements (Destination *first, Destination *second) const
ValueTreeObjectList (const juce::ValueTree &parentTree)
~ValueTreeObjectList () override
int size () const
bool isEmpty () const noexcept
Destination * operator[] (int idx) const
Destination * at (int idx)
Destination ** begin ()
Destination *const * begin () const
Destination ** end ()
Destination *const * end () const
void rebuildObjects ()
void freeObjects ()
virtual void deleteObject (Destination *)=0
virtual void newObjectAdded (Destination *)=0
virtual void objectRemoved (Destination *)=0
void valueTreeChildAdded (juce::ValueTree &, juce::ValueTree &tree) override
void valueTreeChildRemoved (juce::ValueTree &exParent, juce::ValueTree &tree, int) override
void valueTreeChildOrderChanged (juce::ValueTree &tree, int, int) override
void valueTreePropertyChanged (juce::ValueTree &, const juce::Identifier &) override
void valueTreeParentChanged (juce::ValueTree &) override
void valueTreeRedirected (juce::ValueTree &) override
int compareElements (Destination *first, Destination *second) const
Public Attributes
InputDeviceInstance & input
Public Attributes inherited from tracktion::engine::ValueTreeObjectList< Destination >
juce::Array< Destination * > objects
juce::DummyCriticalSection arrayLock
juce::Array< Destination * > objects
juce::DummyCriticalSection arrayLock
Additional Inherited Members
Public Types inherited from tracktion::engine::ValueTreeObjectList< Destination >
using ScopedLockType = typename CriticalSectionType::ScopedLockType
using ScopedLockType = typename CriticalSectionType::ScopedLockType
Protected Member Functions inherited from tracktion::engine::ValueTreeObjectList< Destination >
void deleteAllObjects ()
bool isChildTree (juce::ValueTree &v) const
int indexOf (const juce::ValueTree &v) const noexcept
void sortArray ()
void deleteAllObjects ()
bool isChildTree (juce::ValueTree &v) const
int indexOf (const juce::ValueTree &v) const noexcept
void sortArray ()
Protected Attributes inherited from tracktion::engine::ValueTreeObjectList< Destination >
juce::ValueTree parent
juce::ValueTree parent
Constructor & Destructor Documentation
DestinationList()
tracktion::engine::InputDeviceInstance::DestinationList::DestinationList (InputDeviceInstance & i, const juce::ValueTree & v)
References tracktion::engine::ValueTreeObjectList< Destination >::rebuildObjects().
~DestinationList()
tracktion::engine::InputDeviceInstance::DestinationList::~DestinationList () override
References tracktion::engine::ValueTreeObjectList< Destination >::freeObjects().
Member Function Documentation
isSuitableType()
bool tracktion::engine::InputDeviceInstance::DestinationList::isSuitableType (const juce::ValueTree & v) const override virtual
Implements tracktion::engine::ValueTreeObjectList< Destination >.
createNewObject()
Destination * tracktion::engine::InputDeviceInstance::DestinationList::createNewObject (const juce::ValueTree & v) override virtual
Implements tracktion::engine::ValueTreeObjectList< Destination >.
References tracktion::engine::InputDevice::getDeviceType(), tracktion::engine::InputDeviceInstance::getInputDevice(), input, tracktion::engine::InputDevice::physicalMidiDevice, tracktion::engine::InputDevice::trackMidiDevice, tracktion::engine::InputDevice::trackWaveDevice, tracktion::engine::InputDevice::virtualMidiDevice, and tracktion::engine::InputDevice::waveDevice.
deleteObject()
void tracktion::engine::InputDeviceInstance::DestinationList::deleteObject (Destination * c) override
newObjectAdded()
void tracktion::engine::InputDeviceInstance::DestinationList::newObjectAdded (Destination *) override
objectRemoved()
void tracktion::engine::InputDeviceInstance::DestinationList::objectRemoved (Destination *) override
objectOrderChanged()
void tracktion::engine::InputDeviceInstance::DestinationList::objectOrderChanged () override virtual
Implements tracktion::engine::ValueTreeObjectList< Destination >.
Member Data Documentation
input
InputDeviceInstance& tracktion::engine::InputDeviceInstance::DestinationList::input
Referenced by createNewObject().
The documentation for this struct was generated from the following file:
tracktion_InputDevice.h