TracktionEngine: tracktion::engine::ReferencedMaterialList::IntervalList Struct Reference
tracktion::engine::ReferencedMaterialList::IntervalList Struct Reference
Represents the sections of a wave file that are being used.
Public Member Functions
IntervalList ()
int getNumIntervals () const
double getStart (int index) const
double getLength (int index) const
double getEnd (int index) const
void addInterval (double start, double length)
Detailed Description
Represents the sections of a wave file that are being used.
Constructor & Destructor Documentation
IntervalList()
tracktion::engine::ReferencedMaterialList::IntervalList::IntervalList ()
Member Function Documentation
getNumIntervals()
int tracktion::engine::ReferencedMaterialList::IntervalList::getNumIntervals () const
Referenced by addInterval().
getStart()
double tracktion::engine::ReferencedMaterialList::IntervalList::getStart (int index) const
Referenced by addInterval().
getLength()
double tracktion::engine::ReferencedMaterialList::IntervalList::getLength (int index) const
getEnd()
double tracktion::engine::ReferencedMaterialList::IntervalList::getEnd (int index) const
Referenced by addInterval().
addInterval()
void tracktion::engine::ReferencedMaterialList::IntervalList::addInterval (double start, double length)
References getEnd(), getNumIntervals(), getStart(), and tracktion::engine::AppFunctions::start().
The documentation for this struct was generated from the following file:
tracktion_ReferencedMaterialList.h