TracktionEngine: tracktion::engine::PluginScanHelpers::CustomScanner Struct Reference
tracktion::engine::PluginScanHelpers::CustomScanner Struct Reference
Inherits juce::KnownPluginList::CustomScanner.
Public Member Functions
CustomScanner (Engine &e)
bool findPluginTypesFor (juce::AudioPluginFormat &format, juce::OwnedArray< juce::PluginDescription > &result, const juce::String &fileOrIdentifier) override
void scanFinished () override
void cancelScan ()
bool shouldAbortScan () const
Static Public Member Functions
static bool shouldUseSeparateProcessToScan (juce::AudioPluginFormat &format, const juce::String fileOrIdentifier)
static bool requiresUnblockedMessageThread (juce::AudioPluginFormat &format, const juce::String fileOrIdentifier)
Public Attributes
Engine & engine
std::unique_ptr< PluginScanMasterProcess > masterProcess
std::atomic< bool > abortScan { false }
Constructor & Destructor Documentation
CustomScanner()
tracktion::engine::PluginScanHelpers::CustomScanner::CustomScanner (Engine & e)
Member Function Documentation
findPluginTypesFor()
bool tracktion::engine::PluginScanHelpers::CustomScanner::findPluginTypesFor (juce::AudioPluginFormat & format, juce::OwnedArray< juce::PluginDescription > & result, const juce::String & fileOrIdentifier) override
References CRASH_TRACER, masterProcess, shouldAbortScan(), and shouldUseSeparateProcessToScan().
shouldUseSeparateProcessToScan()
static bool tracktion::engine::PluginScanHelpers::CustomScanner::shouldUseSeparateProcessToScan (juce::AudioPluginFormat & format, const juce::String fileOrIdentifier) static
References requiresUnblockedMessageThread().
Referenced by findPluginTypesFor().
requiresUnblockedMessageThread()
static bool tracktion::engine::PluginScanHelpers::CustomScanner::requiresUnblockedMessageThread (juce::AudioPluginFormat & format, const juce::String fileOrIdentifier) static
Referenced by shouldUseSeparateProcessToScan().
scanFinished()
void tracktion::engine::PluginScanHelpers::CustomScanner::scanFinished () override
References abortScan, and masterProcess.
cancelScan()
void tracktion::engine::PluginScanHelpers::CustomScanner::cancelScan ()
References abortScan.
shouldAbortScan()
bool tracktion::engine::PluginScanHelpers::CustomScanner::shouldAbortScan () const
References abortScan.
Referenced by findPluginTypesFor(), and tracktion::engine::PluginScanHelpers::PluginScanMasterProcess::waitForReply().
Member Data Documentation
engine
Engine& tracktion::engine::PluginScanHelpers::CustomScanner::engine
masterProcess
std::unique_ptr<PluginScanMasterProcess> tracktion::engine::PluginScanHelpers::CustomScanner::masterProcess
Referenced by findPluginTypesFor(), and scanFinished().
abortScan
std::atomic<bool> tracktion::engine::PluginScanHelpers::CustomScanner::abortScan { false }
Referenced by cancelScan(), scanFinished(), and shouldAbortScan().
The documentation for this struct was generated from the following file:
tracktion_PluginScanHelpers.h