TracktionEngine: tracktion::engine::StopwatchTimer Struct Reference
tracktion::engine::StopwatchTimer Struct Reference
tracktion_engine » utilities
#include <tracktion_CpuMeasurement.h>
Public Member Functions
StopwatchTimer () noexcept
juce::RelativeTime getTime () const noexcept
juce::String getDescription () const
double getSeconds () const noexcept
Constructor & Destructor Documentation
StopwatchTimer()
tracktion::engine::StopwatchTimer::StopwatchTimer () noexcept
Member Function Documentation
getTime()
juce::RelativeTime tracktion::engine::StopwatchTimer::getTime () const noexcept
Referenced by getDescription(), and getSeconds().
getDescription()
juce::String tracktion::engine::StopwatchTimer::getDescription () const
References getTime().
Referenced by tracktion::engine::benchmark_utilities::prepareRenderAndDestroy().
getSeconds()
double tracktion::engine::StopwatchTimer::getSeconds () const noexcept
References getTime().
The documentation for this struct was generated from the following file:
tracktion_CpuMeasurement.h