TracktionEngine: tracktion_engine::InputDeviceInstance::InputDeviceDestination Struct Reference
tracktion_engine::InputDeviceInstance::InputDeviceDestination Struct Reference
Public Member Functions
InputDeviceDestination (InputDeviceInstance &i, juce::ValueTree v)
~InputDeviceDestination () override
juce::String getSelectableDescription () override
Subclasses must return a description of what they are.
Public Member Functions inherited from tracktion_engine::Selectable
Selectable ()
virtual ~Selectable ()
virtual void selectionStatusChanged (bool isNowSelected)
Can be overridden to tell this object that it has just been selected or deselected.
virtual void changed ()
This should be called to send a change notification to any SelectableListeners that are registered with this object.
virtual void selectableAboutToBeDeleted ()
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void addSelectableListener (SelectableListener *)
void removeSelectableListener (SelectableListener *)
void cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
void deselect ()
void propertiesChanged ()
void notifyListenersOfDeletion ()
WeakRef getWeakRef ()
Public Attributes
InputDeviceInstance & input
juce::ValueTree state
juce::CachedValue< bool > recordEnabled
juce::CachedValue< EditItemID > targetTrack
juce::CachedValue< int > targetIndex
Public Attributes inherited from tracktion_engine::Selectable
WeakRef::Master masterReference
Additional Inherited Members
Public Types inherited from tracktion_engine::Selectable
using WeakRef = juce::WeakReference< Selectable >
Static Public Member Functions inherited from tracktion_engine::Selectable
static void initialise ()
static bool isSelectableValid (const Selectable *) noexcept
checks whether this object has been deleted.
Constructor & Destructor Documentation
InputDeviceDestination()
tracktion_engine::InputDeviceInstance::InputDeviceDestination::InputDeviceDestination (InputDeviceInstance & i, juce::ValueTree v)
References recordEnabled, state, targetIndex, and targetTrack.
~InputDeviceDestination()
tracktion_engine::InputDeviceInstance::InputDeviceDestination::~InputDeviceDestination () override
References tracktion_engine::Selectable::notifyListenersOfDeletion().
Member Function Documentation
getSelectableDescription()
juce::String tracktion_engine::InputDeviceInstance::InputDeviceDestination::getSelectableDescription () override virtual
Subclasses must return a description of what they are.
Implements tracktion_engine::Selectable.
References tracktion_engine::InputDeviceInstance::getInputDevice(), tracktion_engine::InputDevice::getSelectableDescription(), and input.
Member Data Documentation
input
InputDeviceInstance& tracktion_engine::InputDeviceInstance::InputDeviceDestination::input
Referenced by getSelectableDescription().
state
juce::ValueTree tracktion_engine::InputDeviceInstance::InputDeviceDestination::state
Referenced by InputDeviceDestination().
recordEnabled
juce::CachedValue<bool> tracktion_engine::InputDeviceInstance::InputDeviceDestination::recordEnabled
Referenced by InputDeviceDestination().
targetTrack
juce::CachedValue<EditItemID> tracktion_engine::InputDeviceInstance::InputDeviceDestination::targetTrack
Referenced by InputDeviceDestination().
targetIndex
juce::CachedValue<int> tracktion_engine::InputDeviceInstance::InputDeviceDestination::targetIndex
Referenced by InputDeviceDestination().
The documentation for this struct was generated from the following file:
tracktion_InputDevice.h