TracktionEngine: tracktion_engine::ScopedBenchmark Struct Reference
tracktion_engine::ScopedBenchmark Struct Reference
Helper class for measuring a benchmark and adding it to the singleton BenchmarkList list.
Public Member Functions
ScopedBenchmark (BenchmarkDescription desc)
Constructs and starts a Benchmark.
~ScopedBenchmark ()
Stops the Benchmark and adds the result to the BenchmarkList.
Detailed Description
Helper class for measuring a benchmark and adding it to the singleton BenchmarkList list.
{
    ScopedBenchmark sb (getBenchmarkDescription ("Save random tree as XML"));
    doSomeLongCalculation();
}
publish (BenchmarkList::getInstance().getResults());
Constructor & Destructor Documentation
ScopedBenchmark()
tracktion_engine::ScopedBenchmark::ScopedBenchmark (BenchmarkDescription desc)
Constructs and starts a Benchmark.
References tracktion_engine::Benchmark::start().
~ScopedBenchmark()
tracktion_engine::ScopedBenchmark::~ScopedBenchmark ()
Stops the Benchmark and adds the result to the BenchmarkList.
References tracktion_engine::BenchmarkList::addResult(), tracktion_engine::BenchmarkList::getInstance(), tracktion_engine::Benchmark::getResult(), and tracktion_engine::Benchmark::stop().
The documentation for this struct was generated from the following file:
tracktion_Benchmark.h