TracktionEngine: tracktion::engine::InputDeviceInstance::Destination Struct Reference
tracktion::engine::InputDeviceInstance::Destination Struct Reference
tracktion_engine » playback
#include <tracktion_InputDevice.h>
Public Member Functions
~Destination () override
Destructor.
Destination (InputDeviceInstance &i, juce::ValueTree v)
juce::String getSelectableDescription () override
Public Member Functions inherited from tracktion::engine::Selectable
Selectable ()
virtual ~Selectable ()
virtual void selectionStatusChanged (bool isNowSelected)
Can be overridden to tell this object that it has just been selected or deselected.
virtual void changed ()
This should be called to send a change notification to any SelectableListeners that are registered with this object.
virtual void selectableAboutToBeDeleted ()
Called just before the selectable is about to be deleted so any subclasses should still be valid at this point.
void addListener (SelectableListener *)
void removeListener (SelectableListener *)
void addSelectableListener (SelectableListener *)
void removeSelectableListener (SelectableListener *)
void cancelAnyPendingUpdates ()
If changed() has been called, this will cancel any pending async change notificaions.
void deselect ()
void propertiesChanged ()
void notifyListenersOfDeletion ()
WeakRef getWeakRef ()
Public Attributes
InputDeviceInstance & input
The instance this belongs to.
juce::ValueTree state
The state of this destination.
const EditItemID targetID = EditItemID::fromProperty (state, IDs::targetID)
The target for this destination, either an AudioTrack or ClipSlot.
const int targetIndex = state[IDs::targetIndex]
The target index for this destination, if it is an AudioTrack.
juce::CachedValue< bool > recordEnabled
Property to control whether the destination is armed to record or not.
Public Attributes inherited from tracktion::engine::Selectable
WeakRef::Master masterReference
Additional Inherited Members
Public Types inherited from tracktion::engine::Selectable
using WeakRef = juce::WeakReference< Selectable >
Static Public Member Functions inherited from tracktion::engine::Selectable
static void initialise ()
static bool isSelectableValid (const Selectable *) noexcept
checks whether this object has been deleted.
Constructor & Destructor Documentation
~Destination()
tracktion::engine::InputDeviceInstance::Destination::~Destination () override
Destructor.
References tracktion::engine::Selectable::notifyListenersOfDeletion().
Destination()
tracktion::engine::InputDeviceInstance::Destination::Destination (InputDeviceInstance & i, juce::ValueTree v)
References tracktion::engine::EditItemID::isValid(), recordEnabled, state, and targetID.
Member Function Documentation
getSelectableDescription()
juce::String tracktion::engine::InputDeviceInstance::Destination::getSelectableDescription () override virtual
Implements tracktion::engine::Selectable.
References tracktion::engine::InputDeviceInstance::getInputDevice(), tracktion::engine::InputDevice::getSelectableDescription(), and input.
Member Data Documentation
input
InputDeviceInstance& tracktion::engine::InputDeviceInstance::Destination::input
The instance this belongs to.
Referenced by getSelectableDescription().
state
juce::ValueTree tracktion::engine::InputDeviceInstance::Destination::state
The state of this destination.
Referenced by Destination().
targetID
const EditItemID tracktion::engine::InputDeviceInstance::Destination::targetID = EditItemID::fromProperty (state, IDs::targetID)
The target for this destination, either an AudioTrack or ClipSlot.
Referenced by Destination().
targetIndex
const int tracktion::engine::InputDeviceInstance::Destination::targetIndex = state[IDs::targetIndex]
The target index for this destination, if it is an AudioTrack.
recordEnabled
juce::CachedValue<bool> tracktion::engine::InputDeviceInstance::Destination::recordEnabled
Property to control whether the destination is armed to record or not.
Referenced by Destination().
The documentation for this struct was generated from the following file:
tracktion_InputDevice.h