var searchData=
[
  ['safescopedlistener_0',['safescopedlistener',['../classtracktion_1_1engine_1_1SafeScopedListener.html',1,'tracktion::SafeScopedListener'],['../classtracktion_1_1engine_1_1SafeScopedListener.html',1,'tracktion::engine::SafeScopedListener']]],
  ['safeselectable_1',['safeselectable',['../classtracktion_1_1engine_1_1SafeSelectable.html',1,'tracktion::SafeSelectable&lt; SelectableType &gt;'],['../classtracktion_1_1engine_1_1SafeSelectable.html',1,'tracktion::engine::SafeSelectable&lt; SelectableType &gt;']]],
  ['safeselectable_3c_20tracktion_3a_3aengine_3a_3aclip_20_3e_2',['SafeSelectable&lt; tracktion::engine::Clip &gt;',['../classtracktion_1_1engine_1_1SafeSelectable.html',1,'tracktion::engine']]],
  ['safeselectable_3c_20tracktion_3a_3aengine_3a_3aedit_20_3e_3',['SafeSelectable&lt; tracktion::engine::Edit &gt;',['../classtracktion_1_1engine_1_1SafeSelectable.html',1,'tracktion::engine']]],
  ['safeselectable_3c_20tracktion_3a_3aengine_3a_3afoldertrack_20_3e_4',['SafeSelectable&lt; tracktion::engine::FolderTrack &gt;',['../classtracktion_1_1engine_1_1SafeSelectable.html',1,'tracktion::engine']]],
  ['safeselectable_3c_20tracktion_3a_3aengine_3a_3aplugin_20_3e_5',['SafeSelectable&lt; tracktion::engine::Plugin &gt;',['../classtracktion_1_1engine_1_1SafeSelectable.html',1,'tracktion::engine']]],
  ['safeselectable_3c_20tracktion_3a_3aengine_3a_3aselectable_20_3e_6',['SafeSelectable&lt; tracktion::engine::Selectable &gt;',['../classtracktion_1_1engine_1_1SafeSelectable.html',1,'tracktion::engine']]],
  ['safeselectable_3c_20tracktion_3a_3aengine_3a_3atrack_20_3e_7',['SafeSelectable&lt; tracktion::engine::Track &gt;',['../classtracktion_1_1engine_1_1SafeSelectable.html',1,'tracktion::engine']]],
  ['samplefader_8',['samplefader',['../classtracktion_1_1engine_1_1SampleFader.html',1,'tracktion::engine::SampleFader'],['../classtracktion_1_1engine_1_1SampleFader.html',1,'tracktion::SampleFader']]],
  ['samplerplugin_9',['samplerplugin',['../classtracktion_1_1engine_1_1SamplerPlugin.html',1,'tracktion::engine::SamplerPlugin'],['../classtracktion_1_1engine_1_1SamplerPlugin.html',1,'tracktion::SamplerPlugin']]],
  ['samplersound_10',['SamplerSound',['../structtracktion_1_1engine_1_1SamplerPlugin_1_1SamplerSound.html',1,'tracktion::engine::SamplerPlugin']]],
  ['scale_11',['scale',['../classtracktion_1_1engine_1_1Scale.html',1,'tracktion::engine::Scale'],['../classtracktion_1_1engine_1_1Scale.html',1,'tracktion::Scale']]],
  ['scene_12',['scene',['../classtracktion_1_1engine_1_1Scene.html',1,'tracktion::engine::Scene'],['../classtracktion_1_1engine_1_1Scene.html',1,'tracktion::Scene']]],
  ['sceneinfo_13',['SceneInfo',['../structtracktion_1_1engine_1_1Clipboard_1_1Scenes_1_1SceneInfo.html',1,'tracktion::engine::Clipboard::Scenes']]],
  ['scenelist_14',['scenelist',['../classtracktion_1_1engine_1_1SceneList.html',1,'tracktion::SceneList'],['../classtracktion_1_1engine_1_1SceneList.html',1,'tracktion::engine::SceneList']]],
  ['scenes_15',['Scenes',['../structtracktion_1_1engine_1_1Clipboard_1_1Scenes.html',1,'tracktion::engine::Clipboard']]],
  ['scenewatcher_16',['scenewatcher',['../classtracktion_1_1engine_1_1SceneWatcher.html',1,'tracktion::engine::SceneWatcher'],['../classtracktion_1_1engine_1_1SceneWatcher.html',1,'tracktion::SceneWatcher']]],
  ['scopedactiveparameter_17',['ScopedActiveParameter',['../structtracktion_1_1engine_1_1AutomatableParameter_1_1ScopedActiveParameter.html',1,'tracktion::engine::AutomatableParameter']]],
  ['scopedactiverecordingdevice_18',['ScopedActiveRecordingDevice',['../structtracktion_1_1engine_1_1detail_1_1ScopedActiveRecordingDevice.html',1,'tracktion::engine::detail']]],
  ['scopedchangecaller_19',['ScopedChangeCaller',['../structtracktion_1_1engine_1_1MidiLearnState_1_1ScopedChangeCaller.html',1,'tracktion::engine::MidiLearnState']]],
  ['scopedclipslotdisabler_20',['ScopedClipSlotDisabler',['../structengine_1_1Renderer_1_1ScopedClipSlotDisabler.html',1,'engine::Renderer']]],
  ['scopedcontextallocator_21',['ScopedContextAllocator',['../structtracktion_1_1engine_1_1TransportControl_1_1ScopedContextAllocator.html',1,'tracktion::engine::TransportControl']]],
  ['scopedcpumeter_22',['scopedcpumeter',['../structtracktion_1_1engine_1_1ScopedCpuMeter.html',1,'tracktion::engine::ScopedCpuMeter'],['../structtracktion_1_1engine_1_1ScopedCpuMeter.html',1,'tracktion::ScopedCpuMeter']]],
  ['scopeddevicelistreleaser_23',['ScopedDeviceListReleaser',['../structtracktion_1_1engine_1_1EditPlaybackContext_1_1ScopedDeviceListReleaser.html',1,'tracktion::engine::EditPlaybackContext']]],
  ['scopeddirectorydeleter_24',['scopeddirectorydeleter',['../structtracktion_1_1engine_1_1ScopedDirectoryDeleter.html',1,'tracktion::engine::ScopedDirectoryDeleter'],['../structtracktion_1_1engine_1_1ScopedDirectoryDeleter.html',1,'tracktion::ScopedDirectoryDeleter']]],
  ['scopedeventslist_25',['ScopedEventsList',['../structtracktion_1_1engine_1_1MidiClip_1_1ScopedEventsList.html',1,'tracktion::engine::MidiClip']]],
  ['scopedinitialiser_26',['ScopedInitialiser',['../structtracktion_1_1engine_1_1WaveInputRecordingThread_1_1ScopedInitialiser.html',1,'tracktion::engine::WaveInputRecordingThread']]],
  ['scopedlistener_27',['scopedlistener',['../classtracktion_1_1engine_1_1ScopedListener.html',1,'tracktion::engine::ScopedListener'],['../classtracktion_1_1engine_1_1ScopedListener.html',1,'tracktion::ScopedListener']]],
  ['scopedperformancemeasurement_28',['scopedperformancemeasurement',['../classtracktion_1_1graph_1_1ScopedPerformanceMeasurement.html',1,'tracktion::graph::ScopedPerformanceMeasurement'],['../classtracktion_1_1graph_1_1ScopedPerformanceMeasurement.html',1,'tracktion::ScopedPerformanceMeasurement']]],
  ['scopedplaybackrestarter_29',['ScopedPlaybackRestarter',['../structtracktion_1_1engine_1_1TransportControl_1_1ScopedPlaybackRestarter.html',1,'tracktion::engine::TransportControl']]],
  ['scopedplugindisabler_30',['ScopedPluginDisabler',['../structtracktion_1_1engine_1_1FreezePointPlugin_1_1ScopedPluginDisabler.html',1,'tracktion::engine::FreezePointPlugin']]],
  ['scopedpluginunloadinhibitor_31',['scopedpluginunloadinhibitor',['../structtracktion_1_1engine_1_1ScopedPluginUnloadInhibitor.html',1,'tracktion::engine::ScopedPluginUnloadInhibitor'],['../structtracktion_1_1engine_1_1ScopedPluginUnloadInhibitor.html',1,'tracktion::ScopedPluginUnloadInhibitor']]],
  ['scopedrealtimeaccess_32',['ScopedRealTimeAccess',['../classtracktion_1_1graph_1_1LockFreeObject_1_1ScopedRealTimeAccess.html',1,'tracktion::graph::LockFreeObject']]],
  ['scopedrenderstatus_33',['ScopedRenderStatus',['../structtracktion_1_1engine_1_1Edit_1_1ScopedRenderStatus.html',1,'tracktion::engine::Edit']]],
  ['scopedselectionstate_34',['ScopedSelectionState',['../structtracktion_1_1engine_1_1SelectionManager_1_1ScopedSelectionState.html',1,'tracktion::engine::SelectionManager']]],
  ['scopedsignpost_35',['scopedsignpost',['../structtracktion_1_1graph_1_1ScopedSignpost.html',1,'tracktion::graph::ScopedSignpost'],['../structtracktion_1_1graph_1_1ScopedSignpost.html',1,'tracktion::ScopedSignpost']]],
  ['scopedsteadyload_36',['scopedsteadyload',['../classtracktion_1_1engine_1_1ScopedSteadyLoad.html',1,'tracktion::engine::ScopedSteadyLoad'],['../classtracktion_1_1engine_1_1ScopedSteadyLoad.html',1,'tracktion::ScopedSteadyLoad']]],
  ['scopedthreadexitstatusenabler_37',['ScopedThreadExitStatusEnabler',['../structengine_1_1ScopedThreadExitStatusEnabler.html',1,'engine']]],
  ['scopedtrackfreezer_38',['ScopedTrackFreezer',['../structtracktion_1_1engine_1_1FreezePointPlugin_1_1ScopedTrackFreezer.html',1,'tracktion::engine::FreezePointPlugin']]],
  ['scopedtracksoloisolator_39',['ScopedTrackSoloIsolator',['../structtracktion_1_1engine_1_1FreezePointPlugin_1_1ScopedTrackSoloIsolator.html',1,'tracktion::engine::FreezePointPlugin']]],
  ['scopedtrackunsoloer_40',['ScopedTrackUnsoloer',['../structtracktion_1_1engine_1_1FreezePointPlugin_1_1ScopedTrackUnsoloer.html',1,'tracktion::engine::FreezePointPlugin']]],
  ['scopedwaitcursor_41',['scopedwaitcursor',['../classtracktion_1_1engine_1_1ScopedWaitCursor.html',1,'tracktion::engine::ScopedWaitCursor'],['../classtracktion_1_1engine_1_1ScopedWaitCursor.html',1,'tracktion::ScopedWaitCursor']]],
  ['screensaverdefeater_42',['screensaverdefeater',['../structtracktion_1_1engine_1_1ScreenSaverDefeater.html',1,'tracktion::engine::ScreenSaverDefeater'],['../structtracktion_1_1engine_1_1ScreenSaverDefeater.html',1,'tracktion::ScreenSaverDefeater']]],
  ['scurve_43',['SCurve',['../structtracktion_1_1engine_1_1AudioFadeCurve_1_1SCurve.html',1,'tracktion::engine::AudioFadeCurve']]],
  ['searchoperation_44',['searchoperation',['../classtracktion_1_1engine_1_1SearchOperation.html',1,'tracktion::engine::SearchOperation'],['../classtracktion_1_1engine_1_1SearchOperation.html',1,'tracktion::SearchOperation']]],
  ['section_45',['Section',['../structtracktion_1_1engine_1_1TrackCompManager_1_1TrackComp_1_1Section.html',1,'tracktion::engine::TrackCompManager::TrackComp']]],
  ['segment_46',['Segment',['../structtracktion_1_1engine_1_1AudioSegmentList_1_1Segment.html',1,'tracktion::engine::AudioSegmentList']]],
  ['selectable_47',['selectable',['../classtracktion_1_1engine_1_1Selectable.html',1,'tracktion::engine::Selectable'],['../classtracktion_1_1engine_1_1Selectable.html',1,'tracktion::Selectable']]],
  ['selectableclass_48',['selectableclass',['../classtracktion_1_1engine_1_1SelectableClass.html',1,'tracktion::engine::SelectableClass'],['../classtracktion_1_1engine_1_1SelectableClass.html',1,'tracktion::SelectableClass']]],
  ['selectableclasswithpan_49',['selectableclasswithpan',['../classtracktion_1_1engine_1_1SelectableClassWithPan.html',1,'tracktion::engine::SelectableClassWithPan'],['../classtracktion_1_1engine_1_1SelectableClassWithPan.html',1,'tracktion::SelectableClassWithPan']]],
  ['selectableclasswithvolume_50',['selectableclasswithvolume',['../classtracktion_1_1engine_1_1SelectableClassWithVolume.html',1,'tracktion::engine::SelectableClassWithVolume'],['../classtracktion_1_1engine_1_1SelectableClassWithVolume.html',1,'tracktion::SelectableClassWithVolume']]],
  ['selectablelist_51',['selectablelist',['../structtracktion_1_1engine_1_1SelectableList.html',1,'tracktion::engine::SelectableList'],['../structtracktion_1_1engine_1_1SelectableList.html',1,'tracktion::SelectableList']]],
  ['selectablelistener_52',['selectablelistener',['../classtracktion_1_1engine_1_1SelectableListener.html',1,'tracktion::engine::SelectableListener'],['../classtracktion_1_1engine_1_1SelectableListener.html',1,'tracktion::SelectableListener']]],
  ['selectedmidievents_53',['selectedmidievents',['../classtracktion_1_1engine_1_1SelectedMidiEvents.html',1,'tracktion::engine::SelectedMidiEvents'],['../classtracktion_1_1engine_1_1SelectedMidiEvents.html',1,'tracktion::SelectedMidiEvents']]],
  ['selectionmanager_54',['selectionmanager',['../classtracktion_1_1engine_1_1SelectionManager.html',1,'tracktion::engine::SelectionManager'],['../classtracktion_1_1engine_1_1SelectionManager.html',1,'tracktion::SelectionManager']]],
  ['selectotherobjectsparams_55',['SelectOtherObjectsParams',['../structtracktion_1_1engine_1_1SelectableClass_1_1SelectOtherObjectsParams.html',1,'tracktion::engine::SelectableClass']]],
  ['semaphore_56',['semaphore',['../classtracktion_1_1graph_1_1Semaphore.html',1,'tracktion::graph::Semaphore'],['../classtracktion_1_1graph_1_1Semaphore.html',1,'tracktion::Semaphore']]],
  ['sendnode_57',['sendnode',['../classtracktion_1_1graph_1_1SendNode.html',1,'tracktion::graph::SendNode'],['../classtracktion_1_1graph_1_1SendNode.html',1,'tracktion::SendNode']]],
  ['sharedlevelmeasurer_58',['sharedlevelmeasurer',['../classtracktion_1_1engine_1_1SharedLevelMeasurer.html',1,'tracktion::engine::SharedLevelMeasurer'],['../classtracktion_1_1engine_1_1SharedLevelMeasurer.html',1,'tracktion::SharedLevelMeasurer']]],
  ['sharedlevelmeasuringnode_59',['sharedlevelmeasuringnode',['../classtracktion_1_1engine_1_1SharedLevelMeasuringNode.html',1,'tracktion::engine::SharedLevelMeasuringNode'],['../classtracktion_1_1engine_1_1SharedLevelMeasuringNode.html',1,'tracktion::SharedLevelMeasuringNode']]],
  ['sharedtimer_60',['sharedtimer',['../classtracktion_1_1engine_1_1SharedTimer.html',1,'tracktion::SharedTimer'],['../classtracktion_1_1engine_1_1SharedTimer.html',1,'tracktion::engine::SharedTimer']]],
  ['silentnode_61',['silentnode',['../classtracktion_1_1graph_1_1SilentNode.html',1,'tracktion::graph::SilentNode'],['../classtracktion_1_1graph_1_1SilentNode.html',1,'tracktion::SilentNode']]],
  ['simplelfo_62',['simplelfo',['../classtracktion_1_1engine_1_1SimpleLFO.html',1,'tracktion::engine::SimpleLFO'],['../classtracktion_1_1engine_1_1SimpleLFO.html',1,'tracktion::SimpleLFO']]],
  ['simplenodeplayer_63',['simplenodeplayer',['../classtracktion_1_1graph_1_1SimpleNodePlayer.html',1,'tracktion::graph::SimpleNodePlayer'],['../classtracktion_1_1graph_1_1SimpleNodePlayer.html',1,'tracktion::SimpleNodePlayer']]],
  ['sineoscillator_64',['SineOscillator',['../structtracktion_1_1graph_1_1test__utilities_1_1SineOscillator.html',1,'tracktion::graph::test_utilities']]],
  ['sinknode_65',['sinknode',['../classtracktion_1_1graph_1_1SinkNode.html',1,'tracktion::graph::SinkNode'],['../classtracktion_1_1graph_1_1SinkNode.html',1,'tracktion::SinkNode']]],
  ['sinnode_66',['sinnode',['../classtracktion_1_1graph_1_1SinNode.html',1,'tracktion::graph::SinNode'],['../classtracktion_1_1graph_1_1SinNode.html',1,'tracktion::SinNode']]],
  ['slotcontrolnode_67',['slotcontrolnode',['../classtracktion_1_1engine_1_1SlotControlNode.html',1,'tracktion::engine::SlotControlNode'],['../classtracktion_1_1engine_1_1SlotControlNode.html',1,'tracktion::SlotControlNode']]],
  ['smartthumbnail_68',['smartthumbnail',['../classtracktion_1_1engine_1_1SmartThumbnail.html',1,'tracktion::engine::SmartThumbnail'],['../classtracktion_1_1engine_1_1SmartThumbnail.html',1,'tracktion::SmartThumbnail']]],
  ['softwaremidioutputdevice_69',['softwaremidioutputdevice',['../classtracktion_1_1engine_1_1SoftwareMidiOutputDevice.html',1,'tracktion::engine::SoftwareMidiOutputDevice'],['../classtracktion_1_1engine_1_1SoftwareMidiOutputDevice.html',1,'tracktion::SoftwareMidiOutputDevice']]],
  ['sortedvaluetreeobjectlist_70',['sortedvaluetreeobjectlist',['../structtracktion_1_1engine_1_1SortedValueTreeObjectList.html',1,'tracktion::engine::SortedValueTreeObjectList&lt; ObjectType &gt;'],['../structtracktion_1_1engine_1_1SortedValueTreeObjectList.html',1,'tracktion::SortedValueTreeObjectList&lt; ObjectType &gt;']]],
  ['sourcefilereference_71',['sourcefilereference',['../classtracktion_1_1engine_1_1SourceFileReference.html',1,'tracktion::engine::SourceFileReference'],['../classtracktion_1_1engine_1_1SourceFileReference.html',1,'tracktion::SourceFileReference']]],
  ['speedfadedescription_72',['speedfadedescription',['../structtracktion_1_1engine_1_1SpeedFadeDescription.html',1,'tracktion::engine::SpeedFadeDescription'],['../structtracktion_1_1engine_1_1SpeedFadeDescription.html',1,'tracktion::SpeedFadeDescription']]],
  ['speedrampwavenode_73',['speedrampwavenode',['../classtracktion_1_1engine_1_1SpeedRampWaveNode.html',1,'tracktion::engine::SpeedRampWaveNode'],['../classtracktion_1_1engine_1_1SpeedRampWaveNode.html',1,'tracktion::SpeedRampWaveNode']]],
  ['spline_74',['spline',['../structtracktion_1_1engine_1_1Spline.html',1,'tracktion::engine::Spline'],['../structtracktion_1_1engine_1_1Spline.html',1,'tracktion::Spline']]],
  ['splitbeatrange_75',['SplitBeatRange',['../structtracktion_1_1engine_1_1LauncherClipPlaybackHandle_1_1SplitBeatRange.html',1,'tracktion::engine::LauncherClipPlaybackHandle']]],
  ['splitstatus_76',['SplitStatus',['../structengine_1_1LaunchHandle_1_1SplitStatus.html',1,'engine::LaunchHandle']]],
  ['splittimelinerange_77',['splittimelinerange',['../structtracktion_1_1graph_1_1SplitTimelineRange.html',1,'tracktion::graph::SplitTimelineRange'],['../structtracktion_1_1graph_1_1SplitTimelineRange.html',1,'tracktion::SplitTimelineRange']]],
  ['stage_78',['Stage',['../structtracktion_1_1engine_1_1BreakpointOscillatorModifier_1_1Stage.html',1,'tracktion::engine::BreakpointOscillatorModifier']]],
  ['statistics_79',['statistics',['../structtracktion_1_1graph_1_1PerformanceMeasurement_1_1Statistics.html',1,'tracktion::graph::PerformanceMeasurement::Statistics'],['../structengine_1_1Renderer_1_1Statistics.html',1,'engine::Renderer::Statistics']]],
  ['stepclip_80',['stepclip',['../classtracktion_1_1engine_1_1StepClip.html',1,'tracktion::engine::StepClip'],['../classtracktion_1_1engine_1_1StepClip.html',1,'tracktion::StepClip']]],
  ['stepmodifier_81',['stepmodifier',['../classtracktion_1_1engine_1_1StepModifier.html',1,'tracktion::engine::StepModifier'],['../classtracktion_1_1engine_1_1StepModifier.html',1,'tracktion::StepModifier']]],
  ['stepvolumeeffect_82',['stepvolumeeffect',['../structtracktion_1_1engine_1_1StepVolumeEffect.html',1,'tracktion::engine::StepVolumeEffect'],['../structtracktion_1_1engine_1_1StepVolumeEffect.html',1,'tracktion::StepVolumeEffect']]],
  ['stoprecordingparameters_83',['StopRecordingParameters',['../structtracktion_1_1engine_1_1InputDeviceInstance_1_1StopRecordingParameters.html',1,'tracktion::engine::InputDeviceInstance']]],
  ['stopwatchtimer_84',['stopwatchtimer',['../structtracktion_1_1engine_1_1StopwatchTimer.html',1,'tracktion::engine::StopwatchTimer'],['../structtracktion_1_1engine_1_1StopwatchTimer.html',1,'tracktion::StopwatchTimer']]],
  ['suffixedparameter_85',['SuffixedParameter',['../structengine_1_1SuffixedParameter.html',1,'engine']]],
  ['summingnode_86',['summingnode',['../classtracktion_1_1graph_1_1SummingNode.html',1,'tracktion::graph::SummingNode'],['../classtracktion_1_1graph_1_1SummingNode.html',1,'tracktion::SummingNode']]],
  ['syncpoint_87',['syncpoint',['../structtracktion_1_1engine_1_1SyncPoint.html',1,'tracktion::engine::SyncPoint'],['../structtracktion_1_1engine_1_1SyncPoint.html',1,'tracktion::SyncPoint']]],
  ['syncrange_88',['syncrange',['../structtracktion_1_1engine_1_1SyncRange.html',1,'tracktion::engine::SyncRange'],['../structtracktion_1_1engine_1_1SyncRange.html',1,'tracktion::SyncRange']]]
];
