#!/bin/bash -e

#========================================================
# Configure build environment
#========================================================
if [[ "$OSTYPE" == "linux-gnu" ]];          then PLATFORM=linux
elif [[ "$OSTYPE" == "darwin"* ]];          then PLATFORM=mac
elif [[ "$OSTYPE" == "msys" ]];             then PLATFORM=windows
elif [[ "$OSTYPE" == "linux-gnueabihf" ]];  then PLATFORM=pi
fi

echo PLATFORM: "$PLATFORM"

if [ -z "$PLATFORM" ]; then
    echo ERROR: Unknown platform
    exit 1
fi

ROOT=$(cd "$(dirname "$0")/.."; pwd)
echo ROOT: "$ROOT"


#==========================================================
# Build examples and run tests
#==========================================================
if [ "$PLATFORM" == "mac" ]; then
    "$ROOT/tests/mac/build_examples"

    TESTRUNNER_ROOT=$ROOT/examples/projects/TestRunner/Builds/MacOSX
    TESTRUNNER_EXE=$TESTRUNNER_ROOT/build/Release/TestRunner
    cd "$TESTRUNNER_ROOT"

    # xcodebuild -configuration Release LLVM_LTO=NO GCC_TREAT_WARNINGS_AS_ERRORS=YES
    "$TESTRUNNER_EXE"
    
    xcodebuild -configuration Release -enableAddressSanitizer YES LLVM_LTO=NO GCC_TREAT_WARNINGS_AS_ERRORS=YES
    "$TESTRUNNER_EXE"

    xcodebuild -configuration Release -enableThreadSanitizer YES LLVM_LTO=NO GCC_TREAT_WARNINGS_AS_ERRORS=YES
    "$TESTRUNNER_EXE"

    xcodebuild analyze -quiet -configuration Release LLVM_LTO=NO
fi

# ==========================================================
if [ "$PLATFORM" == "windows" ]; then
    if [ -z "$MSBUILD_EXE" ]; then
        export MSBUILD_EXE="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe"
    fi

    "$ROOT/tests/windows/build_examples.bat"

    TESTRUNNER_ROOT=$ROOT/examples/projects/TestRunner/Builds/VisualStudio2017
    TESTRUNNER_EXE=$TESTRUNNER_ROOT/x64/Release/ConsoleApp/TestRunner.exe
    cd "$TESTRUNNER_ROOT"

    # "$MSBUILD_EXE" TestRunner.sln -p:VisualStudioVersion=15.0 -m -p:Configuration=Release -p:Platform=x64 -p:PreferredToolArchitecture=x64

    "$TESTRUNNER_EXE"
fi

# ==========================================================
if [ "$PLATFORM" == "linux" ]; then
    "$ROOT/tests/linux/build_examples"

    TESTRUNNER_ROOT=$ROOT/examples/projects/TestRunner/Builds/LinuxMakefile
    TESTRUNNER_EXE=$TESTRUNNER_ROOT/build/TestRunner
    cd "$TESTRUNNER_ROOT"

    # make clean
    # make CONFIG=Release -j$(nproc)

    "$TESTRUNNER_EXE"
    
    if [ -z "$DISABLE_VALGRIND" ]; then
        valgrind "$TESTRUNNER_EXE"
    fi
fi
