#!/bin/bash -e

ROOT=$(cd "$(dirname "$0")/../.."; pwd)
TESTS_DIR="$ROOT/tests/linux"
EXAMPLES_DIR="$ROOT/examples"
JUCE_DIR="$ROOT/modules/juce"
TRACKTION_ENGINE_DIR="$ROOT/modules"
PROJUCER_DIR="$JUCE_DIR/extras/Projucer"
PROJUCER_EXE=$PROJUCER_DIR/Builds/LinuxMakefile/build/Projucer

#=========================================================
echo "Building Projucer"
#=========================================================
"$TESTS_DIR/build_projucer"

if [ -z "$PROJUCER_EXE" ]; then
    echo "ERROR: Projucer not built"
    exit 1
fi


#============================================================
echo "Building Examples"
#============================================================
buildExample()
{
    echo "=========================================================="
    echo "Building example: $1"
    EXAMPLE_NAME=$1
    EXAMPLE_PIP_FILE="$EXAMPLES_DIR/$1.h"
    EXAMPLE_DEST_DIR="$EXAMPLES_DIR/projects"
    EXAMPLE_ROOT_DIR="$EXAMPLE_DEST_DIR/$EXAMPLE_NAME"
    EXAMLE_PJ_FILE="$EXAMPLE_DEST_DIR/$EXAMPLE_NAME/$EXAMPLE_NAME.jucer"

    "$PROJUCER_EXE" --create-project-from-pip "$EXAMPLE_PIP_FILE" "$EXAMPLE_DEST_DIR" "$JUCE_DIR/modules" "$TRACKTION_ENGINE_DIR"
    sed -i.bak s/'<JUCERPROJECT /<JUCERPROJECT cppLanguageStandard="17" /' "$EXAMLE_PJ_FILE"
    "$PROJUCER_EXE" --resave "$EXAMLE_PJ_FILE"

    if [ -z "$DISABLE_BUILD" ]; then
        cd "$EXAMPLE_ROOT_DIR/Builds/LinuxMakefile"
        make clean
        make CONFIG=Release -j$(nproc) TARGET_ARCH="-latomic -m64"
    fi
}

buildExample "tracktion_graph_PerformanceTests"
buildExample "tracktion_graph_TestRunner"
buildExample "TestRunner"
buildExample "PlaybackDemo"
buildExample "PitchAndTimeDemo"
buildExample "StepSequencerDemo"
buildExample "PatternGeneratorDemo"
buildExample "RecordingDemo"
buildExample "PluginDemo"
buildExample "EngineInPluginDemo"
buildExample "MidiRecordingDemo"
