#!/bin/bash -e

#==============================================================================
echo $OSTYPE

if [[ "$OSTYPE" == "linux-gnu" ]]; then PLATFORM=linux
elif [[ "$OSTYPE" == "darwin"* ]]; then PLATFORM=mac
fi

if [ -z "$PLATFORM" ]; then
    echo ERROR: Unknown platform. Coverage can only be generated on macOS or Linux
    exit 1
fi

#==============================================================================
DIR=$(cd "$(dirname "$0")/"; pwd)
echo DIR: $DIR
cd "$DIR"

#==============================================================================
PROJECT_NAME=coverage
CONFIG=RelWithDebInfo

if [ "$PLATFORM" == "mac" ]; then
    CMAKE_BUILD_DIR=build_mac
    BINARY_DIR="${CMAKE_BUILD_DIR}/${PROJECT_NAME}_artefacts/${CONFIG}"
    GENERATOR="-G Xcode"
elif [ "$PLATFORM" == "linux" ]; then
    CMAKE_BUILD_DIR=build_linux
    BINARY_DIR="${CMAKE_BUILD_DIR}/${PROJECT_NAME}_artefacts/${CONFIG}"
fi

BINARY="${BINARY_DIR}/${PROJECT_NAME}"
COVERAGE_FILE_TMP="${CMAKE_BUILD_DIR}/coverage_tmp.info"
COVERAGE_FILE="${CMAKE_BUILD_DIR}/coverage.info"
HTML_DIR="${CMAKE_BUILD_DIR}/coverage_html"

#==============================================================================
# Generate project and build it
# export CXX=clang++
# export CC=clang
export CC=/usr/bin/gcc-12
export CXX=/usr/bin/g++-12
c++ --version
cmake ${GENERATOR} -B "$CMAKE_BUILD_DIR" -DCMAKE_BUILD_TYPE=${CONFIG}
cmake --build "$CMAKE_BUILD_DIR" --target "$PROJECT_NAME" --config ${CONFIG} --parallel

# Run app
./$BINARY

# Generate coverage and html report
rm -rf ${COVERAGE_FILE_TMP}
rm -rf ${COVERAGE_FILE}
rm -rf ${HTML_DIR}

# N.B. For some reason, harfbuzz in J8 seems to mess with the build and lcov seems to expect a bunch of "hb-" files in the build dir which don't exist, explicitly removing this seems to fix things
lcov --capture --directory "${CMAKE_BUILD_DIR}/" --exclude "tests/coverage/*"  --exclude "examples/common/*" --exclude "tests/coverage/coverage.h" --exclude "*juce_*" --exclude "*3rd_Party*" --exclude "*3rd_party*" --exclude "modules/3rd_party/*" --exclude "/Applications*" --exclude "/usr*" --exclude "*examples*" --output-file "$COVERAGE_FILE_TMP"
lcov --remove "$COVERAGE_FILE_TMP" 'tests/coverage/*' 'examples/common/*' 'tests/coverage/coverage.h' '*juce_*' '*3rd_Party*' '*3rd_party*' 'modules/3rd_party/*' '/Applications*' '/usr*' '*examples*' '*hb-*'  'NONE' --output-file "${COVERAGE_FILE}"
# genhtml --demangle-cpp "$COVERAGE_FILE" --output-directory ${HTML_DIR}
