#!/bin/bash

#==============================================================================
echo $OSTYPE

if [[ "$OSTYPE" == "linux-gnu" ]]; then PLATFORM=linux
elif [[ "$OSTYPE" == "darwin"* ]]; then PLATFORM=mac
fi

if [ -z "$PLATFORM" ]; then
    echo ERROR: Unknown platform. Coverage can only be generated on macOS or Linux
    exit 1
fi

#==============================================================================
DIR=$(cd "$(dirname "$0")/"; pwd)
echo DIR: $DIR
cd $DIR

#==============================================================================
PROJECT_NAME=coverage

if [ "$PLATFORM" == "mac" ]; then
    CMAKE_BUILD_DIR=build_mac
    BINARY_DIR="${CMAKE_BUILD_DIR}/${PROJECT_NAME}_artefacts/Release"
    GENERATOR="-G Xcode"
elif [ "$PLATFORM" == "linux" ]; then
    CMAKE_BUILD_DIR=build_linux
    BINARY_DIR="${CMAKE_BUILD_DIR}/${PROJECT_NAME}_artefacts/Release"
fi

BINARY="${BINARY_DIR}/${PROJECT_NAME}"
COVERAGE_FILE="${CMAKE_BUILD_DIR}/coverage.info"
HTML_DIR="${CMAKE_BUILD_DIR}/coverage_html"

#==============================================================================
# Generate project and build it
cmake ${GENERATOR} -B "$CMAKE_BUILD_DIR"
cmake --build "$CMAKE_BUILD_DIR" --target "$PROJECT_NAME" --config Release

# # Run app
./$BINARY

# # Generate coverage and html report
rm -rf ${COVERAGE_FILE}
rm -rf ${HTML_DIR}
lcov --capture --directory "${CMAKE_BUILD_DIR}/" -exclude "tests/coverage/coverage.h" -exclude "*juce_*" -exclude "*3rd_Party*" -exclude "*3rd_party*" -exclude "/Applications*" -exclude "/usr*" -exclude "*examples*" --output-file "$COVERAGE_FILE"
genhtml "$COVERAGE_FILE" --output-directory ${HTML_DIR}
